### ISSUE TITLE
Account lock and Forgot password email for PM

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#1087]
(Rephrasing this issue), the Auth Server is currently sending the same emails to the Participant Manager and Mobile App for the Forgot Password and Account Lock functionality. This needs to be corrected to send application-specific emails.

**Comment by harisboston** [comment]
@sharathblr Fix is deployed in QA environment, please confirm if issue is resolved.

**Comment by Lathan-btc** [comment]
@harisboston 
1. In mail template, change 'Support Team' to 'support team'
2. Mobile > Password help email template > App ID should be displayed
3. Mobile > Password help email template > in subject 'Help' should be 'help'

![mobile- pwd help](https://user-images.githubusercontent.com/71445210/103023398-e4f8d380-4573-11eb-87fd-a9a0b74a474f.png)


4. PM > Account lock email template > Org name should be same

![pm - account lock](https://user-images.githubusercontent.com/71445210/103023374-d9a5a800-4573-11eb-9277-f056353303ea.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and confirm.

**Comment by Lathan-btc** [comment]
@harisboston For all the mail templates line formatting should be proper.

**Comment by harisboston** [comment]
@Lathan-btc Line formatting is updated and deployed in QA environment, please test and confirm.

**Comment by Lathan-btc** [comment]
@harisboston issue is fixed in latest QA instance.

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in Dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
@harisboston 

AR : App id is displayed in the the template
ER : App name should be displayed in the email template

![al1](https://user-images.githubusercontent.com/71445210/103212473-de31de00-4930-11eb-8c63-4c257145c6ed.png)


[Note : 1. It should be fixed for both account lock and password help and in all the places where ever app id is displayed in the 
                template.
             2. Issue should be fixed in both QA and Dev instances ]

**Comment by Lathan-btc** [comment]
Issue is fixed in latest Dev instance.
