### ISSUE TITLE
Difference in login screen between iOS and Android

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#1144]
There is a difference in login screen in iOS and Android

1.Android
![image](https://user-images.githubusercontent.com/63578379/95302090-16c89b00-089f-11eb-8e94-47a898affd98.png)\

2. iOS:
![image](https://user-images.githubusercontent.com/63578379/96108877-b8816500-0efb-11eb-9c1f-f3116d9017b3.png)

expected: Android should follow the same design as iOS to maintain consistency and also as per the requirement document of the log in screen in hydra

**Comment by naveenr-btc** [comment]
Android uses custom chrome tabs to invoke the Auth-server based sign-in screen. This UI is by default from the custom chrome tabs and it doesn't allow us to remove the url on this screen.
