### ISSUE TITLE
[Android] Continuous loading animator and fails to navigate to app when internet is disrupted during sign in

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#1150]
Steps:
1. Click on signin
2. Enter valid email and password
3. Switch off the internet connection
4. Click on signin
5. Switch on the internet connection and refresh
6. Observe continuous loading animator

Actual Result: Continuous loading animator and user is not navigated further

Expected Result: User should be navigated further or proper error message along with navigating should be displayed so as user can go back to signin page and resubmit details again

Refer attached video 
[Android_signin.zip](https://github.com/GoogleCloudPlatform/fda-mystudies/files/5339773/Android_signin.zip)

**Comment by sharathblr** [comment]
@harisboston - This needs to be implemented for sing in the screen, I did verify for the other screen in PM and I see that there is not a continuous loader when the connection is established. Could you fix this for the sign-in screen as well.

**Comment by harisboston** [comment]
@nishit-v Fix is deployed in QA environment, kindly test and update.
Reduced the wait time and used `setInterval ` function instead of `setTimeout `, which will keep on trying after specified interval, if there is any network issue happened in between.

**Comment by harisboston** [comment]
@nishit-v Fix is deployed in Dev environment, kindly test and update this ticket

**Comment by nishit-v** [comment]
Issue is still not resolved in Dev instance. 

Steps:

1. Click on signin
2. Enter valid email and password
3. Switch off the internet connection
4. Click on signin
5. Switch on the internet connection and refresh
6. Observe continuous loading animator

Actual Result: Continuous loading animator and user is not navigated further

**Comment by nagarjunav1** [comment]
Issue is still reproducing in latest build

**Comment by harisboston** [comment]
@nagarjunav1 Fix is deployed in dev environment. Kindly clear the cache of chrome browser in mobile before testing and update this ticket.

If any network issue happened during sign-in, app will show error message ('Something went wrong. Please try again.') and error image after 10 seconds.
Then user can go back and try to sign-in again.

**Comment by nagarjunav1** [comment]
App is working now as per above comment in latest DEV build

**Comment by harisboston** [comment]
@nagarjunav1 Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by nagarjunav1** [comment]
Issue is not fixed in QA build.  Loading animator Continuously loading more than a minute without any error or successful login
