### ISSUE TITLE
Sign in not available page is continuously causing issue for sign in

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#1248]

**Comment by dhanyak-btc** [comment]
@nagarjunav1 @nishit-v please re-test in DEV env and close this issue if it's working.

**Comment by nishit-v** [comment]
Issue is observed again in Dev instance in Mobile builds. Please follow below steps to reproduce:

1. Click on forgot password
2. Enter email and submit
3. Wait for 15 mins
4. Enter email and temporary password in signin
5. Observe

**Comment by nishit-v** [comment]
Issue is observed again in Dev instance in Mobile builds for below scenario. Please follow below steps to reproduce:

1. Click on forgot password
2. Enter email and submit
3. Let sign in screen be open for 10 to 15 mins
4. Enter email and temporary password in signin
5. Observe

Lowering the priority as issue is not a direct positive flow.

![IMG-0825](https://user-images.githubusercontent.com/60386291/104736571-2e9a9f80-5769-11eb-98e8-52acb81b4075.PNG)

**Comment by nishit-v** [comment]
Issue also observed for PM for the same above mentioned steps

![Screenshot_1](https://user-images.githubusercontent.com/60386291/104742173-23973d80-5770-11eb-934b-6ca197f181f3.png)

**Comment by harisboston** [comment]
@nishit-v Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by harisboston** [comment]
@nishit-v Fix is deployed in Dev environment, kindly test and update this ticket

**Comment by nishit-v** [comment]
Issue is not observed now in Dev for PM and Mobile apps. Will re-open if issue is observed
