### ISSUE TITLE
Studies > Add Questionniare >Form step > Text choice > Response-level attributes > Description fields are having * symbol and alignment issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#1259]
AR : 1. Studies > Add Questionniare >Form step > Text choice > Response-level attributes > Description fields are having * 
           symbol 
       2. Studies > Add Questionniare >Add Question Step/Form step > Text choice > Response-level attributes > Allignment issue

ER : 1. Description fields should not have * symbol  because those are not mandatory fields

![Alignment issue](https://user-images.githubusercontent.com/71445210/95581526-cbf18380-0a56-11eb-9d3d-1301b1c5f228.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test in QA and DEV instance.

**Comment by Lathan-btc** [comment]
@madhurya-btc Studies > Add Questionniare >Add Question Step > Text choice > Response-level attributes > Include 'Other' as an option ?  > Allignment issue 

![alignment11](https://user-images.githubusercontent.com/71445210/102906796-27021680-449b-11eb-9e52-7dc0043efd27.png)

**Comment by Lathan-btc** [comment]
@madhurya-btc issue is fixed in latest QA instance.

**Comment by Lathan-btc** [comment]
@madhurya-btc Issue is still reproducing in latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirms in Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
@madhurya-btc 
1. Studies > Add Questionniare >Form step > Text choice > Response-level attributes > Description fields are having * symbol - Issue is reproducable in latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
