### ISSUE TITLE
Replace placeholder icon with FDA MyStudies icon throughout codebase

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#1270]
New icon assets can be found [here](https://drive.google.com/drive/folders/1-7v5tfUaXXx-5oTP9aU2b4JNJ0vLnuc_?usp=sharing)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV PM web app

**Comment by Lathan-btc** [comment]
Issue is resolved in latest Dev instance.
