### ISSUE TITLE
Study > Need to fix the issues with Summernote editor for all pages

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#1288]
Font Style and size are not saving 

Issue is happening only with some font styles
1. Arial black
2. Comic Sans
3. Courier new
4. Times new roman

**Comment by nagarjunav1** [comment]
Summer note editor is not able to save the font with font sizes like 10.5, 10.25 etc.. and Saving those text in fields is causing other issues in related Sections.  Need to fix the issue with permanent Solution.

Note:- Probabilistic fix for this issue is to save the text with font size 10.25 etc. as a 10.

**Comment by pujithr** [comment]
@nagarjunav1.Please verify this issue in DEV ins and update the ticket

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest DEV build

**Comment by pujithr** [comment]
@nagarjunav1. PR has merged. Please verify this issue in QA ins and update the ticket

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
