### ISSUE TITLE
User is not redirecting to the Login page after creating a user account

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#1415]
Steps
1. Login as userA and add userB
2. Create a userB account successfuly using activation link
3. After creating the account user should be redirected to the login page

AR : Currently user is getting navigated to the Dashboard screen in signed in state
ER : After creating the account, a new  user should be redirected to the Sign-in page of the application

**Comment by firdosebtc1** [comment]
@Lathan-btc can you please add video for this issue so that it will be easy to understand

**Comment by Lathan-btc** [comment]
@firdosebtc1 
AR : After successful account setup user is navigated to Dashboard
ER : User should be navigated to Sign in screen

![account setup (1)](https://user-images.githubusercontent.com/71445210/103026160-4cfde880-4579-11eb-82da-3d02bc8785c4.gif)

**Comment by firdosebtc1** [comment]
@Lathan-btcplease check this issue in QA

**Comment by Lathan-btc** [comment]
@firdosebtc1 Loading animator should be displayed after successful account setup

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
