### ISSUE TITLE
[PM] Emails are not auto-selected in the New tab of the Site Participant Registry screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#1448]
Steps:
1. Login into the Participant Manager web app
2. In sites tab click on any active site under close study
3. Add the participants to the site by adding email/importing emails and disable the invitation for that particupar participant
4. Go to disabled tab , select participants and Enable the invitation. 

AR : Emails are not auto-selected in the New tab of the Site Participant Registry screen
ER : User should be redirected to New tab with newly enabled emails auto-selected

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
