### ISSUE TITLE
[mobile] Account lock is not working as expected and blocking other functionalities

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#1477]
Account lock is not working as expected.
Steps:- 
1. Navigate to signin page and enter the invalid password for 5 attempts.
2. After account lock, check the mail and using temp password received login into the application
3. Once navigate to Reset password screen, enter required fields and proceed and verify 

**Actual**:-  User is navigating to signin with error message as shown in attachment and not allowing  the user to use forget password or Signin

**Expected**:- User should navigate to signin page and allow user to signin or use forget password without any error messages

![1603102048166](https://user-images.githubusercontent.com/60500517/96432381-6fdeea00-1222-11eb-9a21-f14f6299e590.JPEG)

**Comment by harisboston** [comment]
@nagarjunav1 Fix is deployed in dev environment. Kindly test this issue and update the ticket accordingly

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build for mobile. For PM there is a blocker issue #2722. Once mentioned issue fixed we can test for PM in DEV and raise if any issues separately.
