### ISSUE TITLE
[Mobile Apps] Time of day response attribute> Value for time of day is inconsistent in Android in response server

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#1527]
For 'Time of day' response attributes value is showing inconsistently in android and iOS.

Android:
![Android_Time](https://user-images.githubusercontent.com/60386291/96561205-e2140500-12dc-11eb-86b4-cd880cbeb3ba.png)

iOS: 
![iOS_Timeofday](https://user-images.githubusercontent.com/60386291/96561236-ea6c4000-12dc-11eb-9269-00fe4a9c7d2d.png)

**Comment by sharathblr** [comment]
The time of day in Android needs to be corrected as to its displaying the date along with time, whereas we need only time displayed as shown in for iOS in the response server. Hence Android needs to be corrected accordingly in this scenrio.

**Comment by nishit-v** [comment]
Issue is resolved in Android.

![Screenshot_4](https://user-images.githubusercontent.com/60386291/103208839-a1151e00-4927-11eb-940f-179ac60c9da6.png)
