### ISSUE TITLE
[PM]User is not forcefully logged out when superadmin changes any user related permissions for that user

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#1557]
**Actual**:- User is not forcefully logged out when superadmin changes any user related permissions for that user.
**Expected**:- User should forcefully logged out of the App, when superadmin changes any user related permissions for that user.
**Note**:- Issue also applies when Superadmin update any details for that user.

**Comment by sharathblr** [comment]
@Kantharajut-btc  and @firdosebtc1 -
The below scenario explains the session handling- forced logout behavior for PM: 

Scenario | EB | AB | Error message
-- | -- | -- | --
Admin/Super Admin session Timeout | User to be logged out when in idle state and navigated to sign in page and error message to be displayed in sign in page | User is logged out even when in idle state | EC_0080
Super Admin updates admin profile when logged in | User to be logged out and error message should be displayed in Sign in screen | Not implemented | EC_0080
Parallel Login in different browser | User to be logged out in previously logged in browser and the error message to be displayed in sign in screen | User logged out in previously logged in browser and the error message being  displayed in sign in screen | EC_0080
When superadmin update his own profile | NA | NA | NA

**Comment by prakashm181** [comment]
Due to technical feasibility issue, page will be redirecting to error page instead with appropriate error message

**Comment by nagarjunav1** [comment]
Scenarios Status in latest QA build
1. Parallel Login in different browser - Working as expected(Displaying error page once session expired)
2. Admin/Super Admin session Timeout - User Session will expire but displaying sign in page after 30 minutes of inactivity
3. Super Admin updates admin profile when logged in - No operation 
4. When super admin update his own profile - Working as Expected

**Comment by harisboston** [comment]
@nagarjunav1 Fix for this issue is deployed in QA environment, kindly test and update this ticket.
Super Admin updates admin profile when logged in - admin will redirect to error page with error message.

**Comment by nagarjunav1** [comment]
Issue is resolved in latest QA build
Super Admin updates admin profile when logged in - admin will redirect to error page with error message.

**Comment by harisboston** [comment]
@nagarjunav1  Fix for this issue is deployed in Dev environment, kindly test and update this ticket.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
