### ISSUE TITLE
{PM} Permissions display issue: when site only permission given, the same must be displayed in the UI

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#1789]
Stpe1: log into PM as super admin
           Naviagte to user>add role>give permission to only one site level(either view or view or edit)

![image](https://user-images.githubusercontent.com/63578379/98655152-28e99d80-2365-11eb-990b-96b6a88ae29a.png)

Stpe2:
now navigate back to user search the user and check the site level permission

![image](https://user-images.githubusercontent.com/63578379/98655370-62220d80-2365-11eb-9df2-7f913265dfbf.png)

AB: User unable to know to which site he was given access to
EB: even if access is given to a single site, the application should display it

this can be tested in any of the super admin

**Comment by firdosebtc1** [comment]
@sharathblr @fahad-kc please update the required changes in invision screen

**Comment by sharathblr** [comment]
Hi @fahadbtc-zz - Could you provide the required screen to @Madhud5.

**Comment by fahad-kc** [comment]
@sharathblr Updated the screens! Please check the Invision prototype and verify.

**Comment by sharathblr** [comment]
Hi @Madhud5  and @firdosebtc1 - Please find the updated UI details:

![image](https://user-images.githubusercontent.com/63578379/103196932-145c6700-490b-11eb-9be9-f4b970a042e7.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
