### ISSUE TITLE
[PM] Studies statuses 'Active'/ 'Paused'/ 'Deactivated' should display in PM for their respective sites/studies.

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#1802]
Currently, if a study is Paused/Deactivated from SB, PM admin/user is unable to identify these study's status in PM. 
Recommended approach: Studies statuses 'Active'/ 'Paused'/ 'Deactivated' should display in PM for their respective sites/studies.

**Comment by firdosebtc1** [comment]
@aswinijena100 for fixing this issue please add studyStatus attribute in Site, Site participant registry, Studies, Study participant registry, and participant details API and if that attribute is already added and values are setting in any of the above mentioned api please ignore in that api, please confirm here once changes are done in all 5 api's

**Comment by navya-BTC** [comment]
@firdosebtc1 changes are deployed in QA

**Comment by Madhud5** [comment]
1. Active | Green - 
 btn - classname - active_bg- 
text color - classname  - active_text

2.Paused | Orange
 btn - classname - paused_bg- 
text color - classname  - paused_text

3.Deactivated | Red
 btn - classname - deactivated_bg- 
text color - classname  - deactivated_text

Hi @firdosebtc1 i have added CSS and pushed code. please use above classes
Thank you

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
![Screenshot_9](https://user-images.githubusercontent.com/60500517/103091662-e6c9a200-461a-11eb-8272-ee5643e30022.png)

**Comment by nishit-v** [comment]
Issue is not fixed in Dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev
