### ISSUE TITLE
[Mobile Apps] Duplicate notifications are triggered from Study Builder when user logs out and logs in with another

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#1825]
**Steps:**

1. Freshly install the apps
2. Login/Signup as user A. Send Push notification.
3. Push notification is triggered once
4. Logout and login as User B. Send Push notification again
5. Duplicate notification is received for user B.

**A/R:** Duplicate notifications are triggered from Study Builder

**E/R:** Only single Notification should be triggered.

![1604494571580](https://user-images.githubusercontent.com/60386291/98197565-0ca4c580-1f4d-11eb-832a-4ab363c4efeb.JPEG)

**Comment by naveenr-btc** [comment]
@nishit-v @aswinijena100 This issue can happen in many scenario like logout, session expired and if user clears the data and then log in again. so this needs to handled from backend.
When the app is updating `device token` via `update profile` endpoint we need to have a check if the device token is already present for different user we need to clear those out, by doing this all the scenarios will be handled.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev instance and update.

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA environment and update.

**Comment by nishit-v** [comment]
Unable to test due to #3508.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance and verified in iOS build V1.0.206 and Android build V1.0(81)
