### ISSUE TITLE
In consistency in the email formate

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#1868]
When the email is triggered for the mobile app the org name is displayed as <Org name>
whereas when email for PM is triggered has org name and this is inconsistency when the actual org name is in place. Attaching screenshots:
 Mobile :
![image](https://user-images.githubusercontent.com/63578379/98244602-b314b900-1f95-11eb-95bd-d94daff00f3b.png)
for PM:

![image](https://user-images.githubusercontent.com/63578379/98245239-a3e23b00-1f96-11eb-92dc-6fffd8a98a8d.png)

**Comment by madhurya-btc** [comment]
@sharathblr please confirm this issue in DEV env and close if it's working.

**Comment by sharathblr** [comment]
Hi @Lathan-btc - could you check this and close if working in dev environment

**Comment by Lathan-btc** [comment]
@madhurya-btc issue is still reproducible in the latest dev instance

Remove the angular braces for Org name 

Mobile: 

![mobile1](https://user-images.githubusercontent.com/71445210/106434447-8f2f1980-6497-11eb-8aad-e62759da83e2.png)

**Comment by Lathan-btc** [comment]
@navya-BTC 
1. Change the email template for welcome email as per the document

![temp1](https://user-images.githubusercontent.com/71445210/106555989-9f510280-6544-11eb-826d-dc3033db9cec.png)

**Comment by navya-BTC** [comment]
@naveenr-btc @tushar-boston to fix this issue, please send a attribute `appName` in "/register" API.

**Comment by naveenr-btc** [comment]
@navya-BTC we're already sending appName.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
