### ISSUE TITLE
Improve application logs for production deployments

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#1875]
Currently there are a lot of debug and info logs being generated, even when application is running in prod profile. We should try to reduce the amount of generated logs as much as possible. Setting log level to warn for prod profiles or by default would reduce the amount.
In the GKE deployment all console logs will get sent to stackdriver; sending them to stderr would make them appear as errors in stackdriver automatically. There is no need to write these logs in file, since they will be preserved in stackdriver.

Actions to improve production logs (in prod profile or in default configuration)
- Set log level to warn (to output warning and error logs only)
- Set log destination to stderr only

**Comment by dhanyak-btc** [comment]
Fixed in PR #2434
