### ISSUE TITLE
[Response Server] iOS Active tasks > Tower of Hanoi and Spatial span memory > Response for 'Value' field is displayed as an array post submitting response

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#1905]
A/R: Value parameter is shown as an array in response server
Eg. for Tower of Hanoi active task

`{"resultType":"boolean","startTime":"2020-11-06T20:51:50.750+0530","key":"puzzleWasSolved","endTime":"2020-11-06T20:52:18.119+0530","value":true,"skipped":false},{"skipped":false,"resultType":"numeric","value":15,"key":"numberOfMoves","endTime":"2020-11-06T20:52:18.119+0530","startTime":"2020-11-06T20:51:50.750+0530"}`

Expected: Value parameter should show appropriate data as per active tasks requirement

![Response_AT](https://user-images.githubusercontent.com/60386291/98383581-add96c00-2072-11eb-8e0f-82b0fd1f33a3.png)

**Comment by nishit-v** [comment]
Attaching latest screenshots of `Value` field for Spatial span memory and Tower of hanoi.

**1. Tower of hanoi:**

`{"value":true,"endTime":"2021-04-19T18:41:22.855+0530","skipped":false,"resultType":"boolean","startTime":"2021-04-19T18:41:08.276+0530","key":"puzzleWasSolved"},{"startTime":"2021-04-19T18:41:08.276+0530","resultType":"numeric","key":"numberOfMoves","value":9,"skipped":false,"endTime":"2021-04-19T18:41:22.855+0530"}`

![Tower of hanoi](https://user-images.githubusercontent.com/60386291/115243554-abf6f700-a140-11eb-8136-66a9f1ad665f.png)

**2. Spatial span memory:**

`{"value":70,"startTime":"2021-04-19T18:49:33.403+0530","endTime":"2021-04-19T18:49:55.787+0530","key":"Score","resultType":"numeric","skipped":false},{"key":"NumberofGames","skipped":false,"value":2,"resultType":"numeric","endTime":"2021-04-19T18:49:55.787+0530","startTime":"2021-04-19T18:49:33.403+0530"},{"value":0,"endTime":"2021-04-19T18:49:55.787+0530","resultType":"numeric","skipped":false,"key":"NumberofFailures","startTime":"2021-04-19T18:49:33.403+0530"}`

![Spatial span memory](https://user-images.githubusercontent.com/60386291/115243651-c6c96b80-a140-11eb-8dca-004c1762e766.png)

**Comment by madhurya-btc** [comment]
![image](https://user-images.githubusercontent.com/65340564/115872350-559af880-a45f-11eb-8898-fd0fc6f9448a.png)
For Tower of Hanoi and Spatial span memory please send resultType as "grouped" as in Fetal kick counter.

**Comment by nishit-v** [comment]
Issue is still not fixed for **Tower of Hanoi** and **Spatial span memory** active tasks.

![t2](https://user-images.githubusercontent.com/60386291/116684479-a1edb780-a9ce-11eb-83a2-5d1f868e07ce.png)
![t1](https://user-images.githubusercontent.com/60386291/116684484-a31ee480-a9ce-11eb-90a8-59d6d0f27322.png)

**Comment by nishit-v** [comment]
Issue is resolved in latest iOS build V1.0.202. Tested for all available active tasks and working fine.

**Comment by nishit-v** [comment]
Issue is resolved in latest iOS build V1.0.203 pointing to QA (post PR merge)
