### ISSUE TITLE
Studies tab > Loader icon is missing at the bottom of the page

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#1925]
AR : Studies tab > Loader icon is missing at the bottom of the page
ER : Loader icon should be present 
(Note : Only 10 sets of data should load at a time)

![apps tab](https://user-images.githubusercontent.com/71445210/98634091-b66ac480-2348-11eb-97e0-1c76b3c8a25b.png)

**Comment by nishit-v** [comment]
Implemented in QA and Dev. Issues related to this is being tracked in #2510.
