### ISSUE TITLE
Apps tab > Loader icon is missing at the bottom of the page

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#1926]
AR :Apps tab > Loader icon is missing at the bottom of the page
ER : Loader icon should be present 
(Note : Only 10 sets of data should load at a time)

![apps tab1](https://user-images.githubusercontent.com/71445210/98634137-c08cc300-2348-11eb-8360-1248d5190d9e.png)

**Comment by nishit-v** [comment]
Implemented in QA and Dev. Issues related to this is being tracked in #2510.
