### ISSUE TITLE
User details page > Search bar is missing

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#1953]
AR : Search bar is missing
ER : Search bar should be present as per invision

![search bar](https://user-images.githubusercontent.com/71445210/98783031-e7b5c400-241e-11eb-9fb6-1f517496f78e.png)

**Comment by firdosebtc1** [comment]
@Madhud5 please do UI for search and let me know

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
@firdosebtc1 'App' should be displayed as 'app' 

![searsh](https://user-images.githubusercontent.com/71445210/105740586-52c36100-5f5f-11eb-9bb7-6d4eedd6395d.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
Issue is resolved in latest QA instance.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
