### ISSUE TITLE
[iOS] UI > Screens after enrollment token are showing in full screen and distorted after getting any error message in enrollment screen

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#1972]
Steps:

1. Login into iOS mobile app
2. Open any closed study
3. Enter any used/incorrect token
4. Click on 'Ok' in the error message
5. Enter valid token and proceed further
6. Observe the screens after enrollment token (consent, name field , signature screens etc.)

A/R: Screens after enrollment token are showing in full screen and distorted

E/R: Screens UI should be proper

![IMG_0551](https://user-images.githubusercontent.com/60386291/98815961-f1a2eb80-244d-11eb-8173-20f204172e40.gif)

**Comment by tushar-boston** [comment]
This is due to RK behavior and intermittent. Keeping this issue under observation for fixing at a later point.

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev build V1.0(23)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V1.0(241)
