### ISSUE TITLE
Fields should not be editable

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2026]
Fields should not be editable in the following
1. Edit user details page when user is deactivated
2. Edit Location details page when location is deactivated

**Comment by Lathan-btc** [comment]
@prakash Issue is fixed in latest QA instance.

**Comment by Lathan-btc** [comment]
@prakashm181 Changes should be moved to Dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV deployment
