### ISSUE TITLE
Delete Android  favicon from Participant Manager's assets

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#2037]

**Comment by dhanyak-btc** [comment]
@naveenr-btc please follow up on this and get this issue closed.

**Comment by naveenr-btc** [comment]
@jkrogers18 can you please check and let us know what's the status of this issue

**Comment by naveenr-btc** [comment]
@jkrogers18 we have checked with the participant manager team and confirmed that there's no android favicon in assets folder.
and for android we need the a favicon as default if the image is not provided so in android assets folder we have android favicon.
Hence closing this issue.
