### ISSUE TITLE
Add questionnaire / add active task > Regular and Anchor date based error message to be displayed when there is an overlapping time period

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2095]
Issue 1: Add questionnaire / add active task > Regular > Custom schedule > Select 2 time periods and enter overlapping time period > Again enter valid dates and observe

AR :  Error message is still displaying
ER : Error message should be removed when user enters valid inputs

Issue2: Add Questionnaire/Add active task>Anchor date>Custom Schedule> Select 2 time period and enter the overlapping time period

AR: Error message not displaying when time overlaps
ER: Error message should be displayed when time overlaps

![regular](https://user-images.githubusercontent.com/71445210/99525239-92018e80-29bf-11eb-8035-1fd6a107677d.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc This appears to be working as expected. Please test and confirms.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test in QA instance and confirms.

**Comment by Lathan-btc** [comment]
@madhurya-btc issue is fixed in latest QA instance

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test in Dev instance

**Comment by Lathan-btc** [comment]
Issue is  fixed in latest dev instance.
