### ISSUE TITLE
Study with 'Token Validation and Eligibility test' > Site participant registry page > Participant record is removing from the list if user not eligible for the study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2106]
Steps
1. Fails the eligibility test for the study with 'Token Validation with Eligibility test' 
2. Sites tab > Site participant registry > Observe the user record

AR : Record is not removing from the participants list
ER : Record should be removed if user not eligible for the study

![noteligible issue](https://user-images.githubusercontent.com/71445210/99794375-0ff49f80-2b50-11eb-8ed3-6228f01f7a95.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in dev environment as well and confirm back

**Comment by Lathan-btc** [comment]
@Kantharajut-btc issue is reproducible in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is not reproducible in the latest Dev instance.
