### ISSUE TITLE
[participant manager] add proper padding when there are no records 

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#2162]
<img width="1305" alt="Screen Shot 2020-11-26 at 4 58 29 PM" src="https://user-images.githubusercontent.com/3300694/100393747-bcc79480-3008-11eb-8094-162b123adffb.png">

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is fixed in latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV- QA its fixed. Please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5  Issue is fixed in latest QA instance.
