### ISSUE TITLE
Error messages should be updated as per document

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2166]
Error messages should be updated as per following document

https://docs.google.com/spreadsheets/d/1CEcgbG2Et3FCc5qbavewlNQapxNHG5kTSNMFYzdz4nc/edit?usp=sharing

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in dev

**Comment by Lathan-btc** [comment]
@chiranjibi009 
1. Change password
AR : 'Your password has been reset' (MSG_0019)' success message displayed
ER :  'Your password has been changed successfully' (MSG_0035) success message should be displayed

![change pwd1](https://user-images.githubusercontent.com/71445210/103065275-33da5380-45dc-11eb-8831-c119dfd7aed1.png)

2. If user tries to decommission the site when there are active participants > Text alignment issue

![active participant error msg](https://user-images.githubusercontent.com/71445210/103065295-46548d00-45dc-11eb-8f1a-4070b8e1dae0.png)

**Comment by chiranjibi009** [comment]
@firdosebtc1 please have a look into "Text alignment issue"

**Comment by firdosebtc1** [comment]
> @firdosebtc1 please have a look into "Text alignment issue"
@Madhud5 please look into this

**Comment by chiranjibi009** [comment]
@Lathan-btc please test Change password scenario in dev environment and update.

**Comment by Lathan-btc** [comment]
@chiranjibi009 Change password scenario is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
