### ISSUE TITLE
Terms of Service page > UI issue 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2204]
AR : title is displaying as Terms and Condition
ER : Title should be 'Terms of Service'

[ Note : Terms of Service page should be same as About page except title]

![terms of service](https://user-images.githubusercontent.com/71445210/100733962-f75c7300-33f4-11eb-818c-2c7d8ef83100.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have checked in DEV- QA its fixed. Please check and close the issue.

**Comment by nishit-v** [comment]
Issue is resolved
