### ISSUE TITLE
Sites tab > not getting proper result

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2255]
QA instance > Sites tab > Serach field > Enter 'Site' and press Enter button and observe the result
Dev instance > Sites tab > Serach field > Enter 'Location' and press Enter button and observe the result

**Comment by Lathan-btc** [comment]
@firdosebtc1 Issue is reproducible in the latest QA and Dev instances.

**Comment by firdosebtc1** [comment]
@aswinijena100 please check this issue as filtering is happening at the backend side

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
