### ISSUE TITLE
Response datastore fails to build on debian-10-buster

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2259]
Develop branch cloned on Dec 3rd 11pm ET `sudo mvn -B package -Pprod com.google.cloud.tools:jib-maven-plugin:2.5.2:dockerBuild -Dimage=response-datastore-image`

Log linked [here](https://drive.google.com/file/d/12TxDrvSnBemxRhzw8eR9BOEQatQZj5Qv/view?usp=sharing) (request access)

**Comment by aswinijena100** [comment]
@jkrogers18 can we close this issue ?

**Comment by jkrogers18** [comment]
Yes please go ahead

**Comment by aswinijena100** [comment]
Issue fixed with PR #2624
