### ISSUE TITLE
Branding Centralisation for Participant Manager

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#2317]
we require to centralize all branding elements to a single place in the code with additional properties file values as required.

Also update the readme documentation once the task is done

**Comment by SR-btc** [comment]
Also update the related readme documentation

**Comment by firdosebtc1** [comment]
@sharathblr PM web app branding centralization is done.

**Comment by aswinijena100** [comment]
@sharathblr branding centralization is done backend as well [Study Builder & Participant Datastore]. Please let me know if anything is pending.

**Comment by sharathblr** [comment]
Hi @Lathan-btc - can you verify this

**Comment by SR-btc** [comment]
@firdosebtc1 the readme documentation is to be updated and PR raised for it

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this in develop branch readme file for PM web app
https://github.com/GoogleCloudPlatform/fda-mystudies/blob/develop/participant-manager/README.md

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check and close this issue

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
