### ISSUE TITLE
Participant manager deployment missing /participant-manager/ context path

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2322]
For participant manager, forgot password link is currently `http://x.x.x.x/participant-manager/#/forgotPassword` which results in a 404. Manually adjusting this URL to `http://x.x.x.x/#/participant-manager/forgotPassword` results in the page loading correctly. It appears this could be fixed in [/fdamystudies/oauthscim/config/RedirectConfig.java#L78](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/b2934b7fbfc068c0611a465026e0fff2cb36f9d7/auth-server/oauth-scim-service/src/main/java/com/google/cloud/healthcare/fdamystudies/oauthscim/config/RedirectConfig.java#L78).

This pattern of /#/participant-manager/ vs /participant-manager/#/ occurs in other places throughout the application, for example `http://x.x.x.x/participant-manager/#/callback?code=xyz`

Relevant portion of config files below:

Environment.prod.ts
```
export const environment = {
  production: true,
  // remove http/https to appear relative. xsrf-token skips absolute paths.
  participantManagerDatastoreUrl:
    '//10.128.0.9/participant-manager-datastore',
  baseHref: '/participant-manager/',
  hydraLoginUrl: 'http://10.128.0.2:4444/oauth2/auth',
  authServerUrl: 'http://10.128.0.3/auth-server',
  authServerRedirectUrl:
    'http://10.128.0.3/auth-server/callback',
```

Dockerfile
```
FROM node:12.16.1 AS compile-image
WORKDIR /app
COPY . ./
RUN npm set progress=false
RUN npm install
RUN npm install -g @angular/cli
RUN ng build --aot --prod
```
The same behavior is observed when the Dockerfile has the following configuration:
```
FROM node:12.16.1 AS compile-image
WORKDIR /app
COPY . ./
RUN npm set progress=false
RUN npm install
RUN npm install -g @angular/cli --base-href='/participant-manager/'
RUN ng build --aot --prod
```

![Screenshot 2020-12-10 at 7 56 22 AM](https://user-images.githubusercontent.com/35972680/101776220-98ff5680-3abe-11eb-9811-66c5cd004757.png)

**Comment by firdosebtc1** [comment]
@jkrogers18 We are able to deploy PM web app with context path using docker container process but we have removed **--base-href=$basehref** from **RUN ng build --aot --prod --base-href=$basehref** in Docker file,
Please confirm if we can raise PR for the same

**Comment by jkrogers18** [comment]
Because `--base-href=$basehref` is parameterized with `ARG basehref` you can just use a command like `sudo docker build --build-arg basehref=/ -t participant-manager-image .` to make things work without the context path (see the participant manager README for more details)

**Comment by mohangmk** [comment]
@firdosebtc1
As per the discussion with Jamie, we need to specify only IP address for "PARTICIPANT_MANAGER_URL=" inside the Authserver/variables.env file, since we are using " --build-arg BASE_HREF=" as part of docker build command which was specified in participant-manager/cloudbuild. yaml file to build the docker image. Please try it and share your thoughts.

**Comment by firdosebtc1** [comment]
@mohangmk this change is related to terraform, Please check

**Comment by mohangmk** [comment]
@firdosebtc1 , please go through the above comment properly.

You need to change the value in environment variable then build the application

I have done required changes long ago

**Comment by mohangmk** [comment]
@firdosebtc1, Above changes will be applicable only for individual deployment not for terraform deployment. Based on recent terraform deployment, pm application is working normally
