### ISSUE TITLE
Make auth server login screens error toasts more visible

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2325]
Right now when a user is not found or a password is expired the login screen (participant manager) shows a red toast at the bottom of the screen. It is currently difficult to see and notice. To make it easier to see:
1. Increase toast duration (currently it looks like 1 second, so perhaps 5 seconds would be good)
1. Move toast to the space between "sign in" and "email" if there is room (this is lower priority than making the duration longer as I imagine this is more work than changing the timer on the toast) 

This same issue occurs in Android - the error message is often below the bottom of the screen and so goes unnoticed by the user.

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and update the ticket.

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in Dev environment, kindly test and update

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
