### ISSUE TITLE
[SB][Dev][UI] Need to adjust the UI for time Picker in Activities Screen 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2342]
Need to adjust the UI to eliminate the Overlapping of Error text with next time picker.

Note:- Issue needs to fix for both Regular and anchor Based Schedule

![Shedule3](https://user-images.githubusercontent.com/60500517/101911748-ce06c880-3be6-11eb-8c95-c02e2c25714e.png)

**Comment by pujithr** [comment]
@nagarjunav1 Please test in QA env and let me know if it's fine

**Comment by nagarjunav1** [comment]
![image](https://user-images.githubusercontent.com/60500517/104713292-b1136700-5749-11eb-8a58-e0d9c6b27083.png)
Overlapping Issue has been resolved in QA. But need to adjust colour and opacity everywhere to be consistent.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by pujithr** [comment]
To test in DEV env

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
