### ISSUE TITLE
Need to adjust UI for import email list error message

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2347]
Error message width should be increased

![import11](https://user-images.githubusercontent.com/71445210/101638987-c7484c00-3a54-11eb-93bc-137e7a368d3c.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check message change in QA

**Comment by Lathan-btc** [comment]
@firdosebtc1 issue is fixed in latest QA instance

**Comment by firdosebtc1** [comment]
@Lathan-btc please check message change in DEV

**Comment by Lathan-btc** [comment]
issue is fixed in latest Dev instance.
