### ISSUE TITLE
Add URLS_ERROR to Hydra terraform config

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2353]
@zohrehj We've fixed the issue and added `GenericErrorController `class to redirect to error page instead of displaying Hydra's fallback error page. @harisboston will raise the PR today with tests.

Please add below env in deployment script.
`-e URLS_ERROR="http://<AUTH_SERVER_URL>/error" `

_Originally posted by @dhanyak-btc in https://github.com/GoogleCloudPlatform/fda-mystudies/issues/2269#issuecomment-742367185_

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV deployment. App redirect to error page instead of displaying Hydra's fallback error page now.
