### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2354]
Platform components that have flaky tests:
- Participant enroll datastore
- Participant manager datastore
- Response datastore

Participant enroll datastore tests fail about 50% of the time. Participant manager datastore tests fail 80% of the time. Response datastore tests fail 100% of the time.

Environment is Debian 10 Buster (default compute engine VM instance).

Related issue is #2259

**Comment by aswinijena100** [comment]
@jkrogers18 Can we close this issue if it resolved in your environment ?

**Comment by jkrogers18** [comment]
Yes please go ahead and close

**Comment by aswinijena100** [comment]
Issue fixed with PR #2624
