### ISSUE TITLE
[SB][DEV] Thumbnail image uploaded is not saving 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2362]
![thubnail](https://user-images.githubusercontent.com/60500517/102073229-03025d80-3e29-11eb-8002-fcabd4c4dad2.gif)

**Comment by Lathan-btc** [comment]
@madhurya-btc issue is reproducible in latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
@madhurya-btc Issue is fixed in the latest QA instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
