### ISSUE TITLE
App participant registry > Enrolled studies pop-up > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2389]
App participant registry > Enrolled studies pop-up > UI issue

![app registry1](https://user-images.githubusercontent.com/71445210/102188609-867c8700-3edb-11eb-8f3a-69d05839ff1f.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
