### ISSUE TITLE
Adjust "no records found" text to have padding

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2410]
Add space between the "no records found" text and the top of the panel.

![Screenshot 2020-12-15 at 12 55 16 PM](https://user-images.githubusercontent.com/35972680/102253108-ef143580-3ed4-11eb-943b-862b323f2ff6.png)

**Comment by Lathan-btc** [comment]
Issue is resolved in latest Dev instance
