### ISSUE TITLE
Make display of "no records found" consistent across the participant manager

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2411]
Sometimes the 'no records found' text is left justified, other times it is centered, and here it is right justified. This should be consistent across the application.

![Screenshot 2020-12-15 at 12 58 41 PM](https://user-images.githubusercontent.com/35972680/102253512-68138d00-3ed5-11eb-9197-a662f1fa062b.png)

**Comment by Lathan-btc** [comment]
Issue is fixed fixed in latest Dev instance
