### ISSUE TITLE
Make clear what text is a link within participant manager

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2413]
Many of the tables within the participant manager UI have one column (typically the 'first name' column) that are links to the detailed information about that entry. However, there is no visual indication that this is a link and is not discoverable. We should add some visual indicator that this is a link and is the place that you click to edit this entry. Example below.

![Screenshot 2020-12-15 at 1 04 51 PM](https://user-images.githubusercontent.com/35972680/102254278-6c8c7580-3ed6-11eb-9df3-57fb4240a73d.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
@firdosebtc1 Issue is fixed in latest QA instance.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in dev

**Comment by Lathan-btc** [comment]
Issue is resolved in latest Dev instance.
