### ISSUE TITLE
Participant manager has checkbox in unexpected location with unclear purpose

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2420]
The checkbox in the screenshot attached is in a location that does not make its purpose very clear. I am guessing that checking that box means that I've selected all of the records on the page - but since the individual records do not have check boxes I can't really confirm that is the case.

![Screenshot 2020-12-15 at 6 41 23 PM](https://user-images.githubusercontent.com/35972680/102286018-6366cd00-3f05-11eb-90c3-02a188d15a7e.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in dev

**Comment by Lathan-btc** [comment]
Issue is not reproducable in latest Dev instance.
