### ISSUE TITLE
Mobile app sign-in hangs indefinitely

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2421]
When logging into the Android mobile application, the app hangs with the "Please wait while we set things up for you" message. This occurs with an existing user account and with a brand new user account that was just created. No errors or other messages show up in any of the application logs or in the Android logcat. The most recent audit log entry is:
```
{
  "insertId": "ajwkz5eih45n",
  "jsonPayload": {
    "userIp": "10.128.0.13",
    "participantId": null,
    "platformVersion": "1.0",
    "description": null,
    "occurred": 1608081641886,
    "studyVersion": null,
    "studyId": null,
    "destinationApplicationVersion": "1.0",
    "siteId": null,
    "appVersion": null,
    "appId": "TESTAPP",
    "eventCode": "SIGNIN_SUCCEEDED",
    "source": "MOBILE APPS",
    "correlationId": "GFgApiMciDWkwijUfyvAyASMCNa7KIFFNsmESvoTCbbdKzs70S",
    "mobilePlatform": "ANDROID",
    "resourceServer": "PARTICIPANT USER DATASTORE",
    "userId": "f5c5d8f2k13dfb4ed488babc37f4ba693137",
    "userAccessLevel": null,
    "sourceApplicationVersion": "1.0",
    "destination": "SCIM AUTH SERVER"
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "mystudies-test"
    }
  },
  "timestamp": "2020-12-16T01:20:41.886Z",
  "severity": "INFO",
  "logName": "projects/mystudies-test/logs/application-audit-log",
  "receiveTimestamp": "2020-12-16T01:20:42.047928166Z"
}
```

![Screenshot 2020-12-15 at 8 21 02 PM](https://user-images.githubusercontent.com/35972680/102292758-d414e600-3f13-11eb-878f-40b26f953a55.png)

**Comment by harisboston** [comment]
@nishit-v This issue is same as issue #1150 ([Android] Continuous loading animator and fails to navigate to app when internet is disrupted during sign in). You can close this issue.
Fix for #1150 is deployed is QA, kindly test and update.

**Comment by harisboston** [comment]
@nishit-v Fix is deployed in Dev environment, kindly test and update this ticket

**Comment by nishit-v** [comment]
Tracking this issue in #1150 and hence closing this ticket
