### ISSUE TITLE
Open study > Enrollment registry > Record is removing from the list of participants

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2423]
Steps 
1. Enroll into a open study
2. Withdrawn from the study/delete mobile app account
3. Again not eligible for the same study and Observe the participant record in enrollment registry

AR : Record is removed from the participant list
ER : Record should be displayed with Enrollment status = Withdrawn.

**Comment by SR-btc** [comment]
Such users must be displayed in the list with current  enrolled status indicated with a '-' or NA but with enrollment and consent history available.

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed, please test and confirm

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue fixed in dev, please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev
