### ISSUE TITLE
Participant registry >Enrollment history > 'Yet to enroll' status is displaying

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2425]
Steps
1. Add/Invite a Participant to a Closed study
2.  Navigate to Participant details page and observe Enrollment history

AR : History is displaying with 'Yet to enroll'
ER : 'No records found' text should be displayed when there are no records present in Enrollment history

![Yet to enroll](https://user-images.githubusercontent.com/71445210/102318029-a7f27700-3f9e-11eb-9d9d-ebcf71772ba1.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in dev

**Comment by Lathan-btc** [comment]
Issue is resolved in latest Dev instance.
