### ISSUE TITLE
Site participant registry > Invited tab > Alignment issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2428]
Site participant registry > Invited tab > Enrolled participants > Alignment should be same as invision screen

![enrolled1](https://user-images.githubusercontent.com/71445210/102326495-741d4e80-3faa-11eb-8717-97eabb45224d.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in latest Dev instance.
