### ISSUE TITLE
[PM] UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2429]
Thickness, font size and style should be same as invission screens for the following
1. Site participant registry 
2. Participant details page
3. App participant registry etc.. [ Please verify all the screens ]

[ Note : It should be fixed in both QA and Dev environment ]

**Comment by Lathan-btc** [comment]
@Madhud5 What is the status of this issue.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.
@Lathan-btc  @shanthala Please @fahadbtc-zz , Please note i have used font family as per Psd. (muli font family).
Thank you

![image](https://user-images.githubusercontent.com/59555917/105438663-7057a880-5c89-11eb-8ae5-707c10a76e9d.png)

**Comment by Lathan-btc** [comment]
As per the above comment, closing this issue.
