### ISSUE TITLE
[Mobile] [Dev] Signup > Email code expiry is set for 15 minutes instead of 48 hours

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2439]
Stesp:
1. SIgnup from mobile
2. Email received in email
3. Wait for > 15 mins
4. Enter the email code in verification step
5. Observe

A/R: Email code expiry is set for 15 minutes 

E/R: Email code expiry should be set for 48 hours

Note: In email text it's displayed as 48 hours

**Comment by Lathan-btc** [comment]
@chiranjibi009 issue is resolved in latest QA instance.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev environment and update.

**Comment by nishit-v** [comment]
Issue is resolved in Dev instance.
