### ISSUE TITLE
Fix XSRF for Participant manager

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2443]
Setting security.xsrf.enabled=false in the Participant manager datastore application.properties file allows the Participant manager to make PUT requests successfully. It will not otherwise succeed. See #2332 for more context.

**Comment by dhanyak-btc** [comment]
@madhurya-btc @prakashm181 Please refer below links and fix the issue.

[When to use CSRF protection](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#csrf-when)

[Angular 2 Spring Security CSRF Token](https://stackoverflow.com/questions/43349948/angular-2-spring-security-csrf-token)

[Spring Security and Angular](https://spring.io/guides/tutorials/spring-security-and-angular-js/)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and close this issue

**Comment by Lathan-btc** [comment]
Issue is fixed in the automated deployment QA branch.
