### ISSUE TITLE
[PM] [Dev] Studies > All studies are not displayed and loader icon is not shown at end even though there are >10 studies

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2451]
Steps:
1. Navigate to Studies tab
2. Scroll till end
3. Observe

A/R: Only 9 sets of studies are displayed

E/R: 10 studies should be displayed per set and loader icon should be displayed

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed, please check and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
