### ISSUE TITLE
[PM] [Dev] Open study > Enrollment registry > Participant records are not displaying

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2457]
Open study > Enrollment registry > Participant records are not displaying

Steps
1. Join any open study 
2. In Participant Manager web app, Click on particular study
3. Observe the participant records in Enrollment registry page

AR : Participant records are not displaying
ER : Enrolled participant records should be displayed

![open study](https://user-images.githubusercontent.com/71445210/102495170-c8542b80-409b-11eb-9dee-755e124cfa7e.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
@firdosebtc1 issue is fixed in latest Dev instance.
