### ISSUE TITLE
[Mobile apps] Unable to enroll into combined study

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2464]
User is unable to enroll into Combined Study(Token and Eligibility) in android mobile

![combined](https://user-images.githubusercontent.com/60500517/102499964-d147fb80-40a1-11eb-80e5-10a9fd85c221.jpg)

Instance- DEV

**Comment by nishit-v** [comment]
Issue is observed in QA and Dev

**Comment by nagarjunav1** [comment]
Issue is resolved in latest DEV build
