### ISSUE TITLE
[PM[ [Dev] Participant details page >Withdrawal date is displaying

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2465]
Participant details page >Withdrawal date is displaying

Steps
1. Join a study and withdrawn from the study 
2. Enable invitation for the same participant
3. Navigate to Participant details page and Observe the Withdrawal date 

AR : Withdrawal date is displaying
ER : Withdrawal date should be displayed as 'NA'

[ Note : It should also be fixed when user Invited the participant] 

![withdrawn date](https://user-images.githubusercontent.com/71445210/102498826-7530a780-40a0-11eb-9ab0-0a7ec30d2130.png)

**Comment by nishit-v** [comment]
Issue still exists in DEv

![Screenshot_1](https://user-images.githubusercontent.com/60386291/102753948-334e7c80-4392-11eb-99b7-804abc6690a2.png)

**Comment by Lathan-btc** [comment]
@monica-BTC issue is fixed in latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in latest Dev instance.
