### ISSUE TITLE
[PM] [Dev] Apps > App User Registry > Enrolled pop-up > Order of studies enrolled should be in descending order for iOS users

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2470]
Steps:

1. From iOS user join study A
2. Again join study B
3. Navigate to Apps > App User Registry > Enrolled pop-up
4. Observe the order of studies displayed

A/R: Latest joined study displaying in bottom i.e B displaying below A

E/R: Latest joined/withdrawn study should be in descending order i.e latest should be on top

Note: Issue not observed for Android users

![Screenshot_8](https://user-images.githubusercontent.com/60386291/102503269-8b8d3200-40a5-11eb-9c9c-d4c3dc418dbf.png)

**Comment by Lathan-btc** [comment]
@monica-BTC issue is fixed in latest QA instace.

**Comment by Lathan-btc** [comment]
Issue is resolved in latest Dev instance
