### ISSUE TITLE
[Mobile] Closed study > Not able to enroll into a study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2471]
Closed study > Not able to enroll into a study

Steps
1. Enroll into a closed study and withdrawn from the study
2. Add the withdrawn participant to another site present in the same study and invite
3. Try to enroll into the study

AR : User is getting error message
ER : User should be able to enroll into a study

![closed study1](https://user-images.githubusercontent.com/71445210/102502882-28030480-40a5-11eb-8de7-96b3d788015a.png)

Issue observed in QA and Dev

**Comment by nishit-v** [comment]
Issue is still observed for Android and iOS

**Comment by nishit-v** [comment]
Issue is resolved now.

**Comment by Lathan-btc** [comment]
@aswinijena100 Issue is reproducible in QA instance.
