### ISSUE TITLE
[PM] [Dev] Study with 'Enrollment token and Eligibility test' > 'Not eligible' status is not displaying

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2472]
Study with 'Enrollment token and Eligibility test' > 'Not eligible' status is not displaying

Steps
1. Study with 'Enrollment token and Eligibility test' > Enter enrollment token and click on next
2. Fail the eligibility test
3. Observe the enrollment status of the participant in both Site participant registry

AR : Enrollment status is displaying as 'Yet to enroll'
ER : Enrollment status should be displayed as ' Not eligible'

[Note : Issue should be fixed in Site participant registry, Study participant registry and Participant details page]

![combined study issue](https://user-images.githubusercontent.com/71445210/102505517-1bcc7680-40a8-11eb-9725-712a5aae6b74.png)

**Comment by Lathan-btc** [comment]
@aswinijena100 issue is still reproducing in latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed please check and confirm

**Comment by Lathan-btc** [comment]
@Kantharajut-btc issue is fixed in latest QA instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please retest the issue in dev environment and confirm back

**Comment by Lathan-btc** [comment]
Issue is reproducible in both QA and Dev instances.

**Comment by aswinijena100** [comment]
@Lathan-btc please test this issue in dev and let us know the status

**Comment by Lathan-btc** [comment]
@aswinijena100 Issue is reproducible in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in dev and confirm

**Comment by Lathan-btc** [comment]
@Kantharajut-btc for android
Study with 'Enrollment token and Eligibility test' > Fails the eligibility test > again for the same study pass the eligibility test and observe the enrollment status
AR : 'Not eligible' status is displayed
ER : Enrollment status should be displayed as 'Yet to enroll'

![not eligible](https://user-images.githubusercontent.com/71445210/103926616-2924d000-513f-11eb-814c-c3655afeb5a6.png)

**Comment by nishit-v** [comment]
@tushar-boston issue is not fixed for iOS.

**Comment by tushar-boston** [comment]
@nishit-v There's no issue from the iOS side. It's displaying the correct status even in the new session.

**Comment by Kantharajut-btc** [comment]
@nishit-v @Lathan-btc please test this issue in dev and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please close the issue if resolved
