### ISSUE TITLE
[study builder] old logo still used on logout page and mainpage

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#2476]

**Comment by madhurya-btc** [comment]
@zohrehj Its working in DEV and QA instance. Please confirm in which branch the issue was found.

**Comment by SR-btc** [comment]
@Lathan-btc please close this issue if verified in QA and dev

**Comment by Lathan-btc** [comment]
Issue is fixed in both QA and Dev instances.
