### ISSUE TITLE
[SB] UI of tool tip is incorrect for Active task and Questionnaires

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2494]
**Steps:**
1. Navigate to Active tasks
2. Navigate to scheduling 
3. Mouse hover on the tool tip for 'Daily' or any other schedulings
4. Observe

**Actual Result:** UI of tool tip is incorrect for Active task

**Expected Result:** UI of tool tip should be same as of questionnaires

Refer screenshot for Active task
![ActiveTask](https://user-images.githubusercontent.com/60386291/102591351-e53e3c80-4137-11eb-8ff4-ef960fbc59d9.png)

Refer screenshot for Questionnaires
![Questionnaires](https://user-images.githubusercontent.com/60386291/102591361-e96a5a00-4137-11eb-9a2e-42fb2919784d.png)

**Comment by ESWAR1994** [comment]
I worked on this issue and it is working

**Comment by nishit-v** [comment]
Issue is resolved in QA instance.

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
