### ISSUE TITLE
[SB] Instruction step > Instruction Text field (Rich Text Editor) should be mandatory field while saving and publishing

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2495]
Steps:

1. Navigating to Questionnaires
2. Add a questionnaire and add Instruction step
3. Enter key, Title and save
4. Error message is displayed but contents are saving and able to publish updates without entering in RTE field

A/R: Able to publish updates without entering in the Instruction Text field (Rich Text Editor)

E/R: Instruction Text field (Rich Text Editor) should be mandatory

Instance: QA

Refer attached video:

[SB_Inst.zip](https://github.com/GoogleCloudPlatform/fda-mystudies/files/5728100/SB_Inst.zip)

**Comment by ESWAR1994** [comment]
I worked on this and it is working

**Comment by nishit-v** [comment]
Issue is resolved in QA instance.

**Comment by ESWAR1994** [comment]
merging is completed need to test in dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
