### ISSUE TITLE
[SB] Sorting is not working for any columns in Study List screen 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2496]
Steps:- 
1. Login into the application 
2. Navigate to Manage studies and verify

A/R:- Sorting functionality is not working for columns
E/R:- Sorting functionality should work, which are having sorting buttons (Study ID, App ID, Study name, Status)

Instance - QA

**Comment by ESWAR1994** [comment]
I worked on this issue and it is working

**Comment by nagarjunav1** [comment]
Sorting is working now in recent QA build. But new studies should display in the first.

**Comment by ESWAR1994** [comment]
new studies are displayed in the first.

**Comment by ESWAR1994** [comment]
new studies are displayed in the first

**Comment by nagarjunav1** [comment]
New studies are not displayed in the first row. Confirm once whether your changes are deployed in QA.

**Comment by ESWAR1994** [comment]
okay

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by Lathan-btc** [comment]
Sorting is working in the latest Dev instance.
