### ISSUE TITLE
Study builder > Password criteria text change

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2497]
Study builder > Password criteria text change > Remove those special characters displaying at bottom

![pwd creteria](https://user-images.githubusercontent.com/71445210/102594847-c3938400-413c-11eb-9cd2-fadd18ee6950.png)

**Comment by nishit-v** [comment]
Issue is not fixed.

![SB_Dev](https://user-images.githubusercontent.com/60386291/102765549-c394bd80-43a2-11eb-9b01-8af7843e9e4b.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in dev environment.

**Comment by nishit-v** [comment]
Issue is not fixed in Dev

![Untitled](https://user-images.githubusercontent.com/60386291/102880922-12f5ef00-4472-11eb-9bf9-2983b14ce583.png)

**Comment by Lathan-btc** [comment]
@harisboston issue is fixed in latest Dev instance
