### ISSUE TITLE
[SB] Study Overview > Font size and style is incorrect for 'Default Image'  and 'Alternate Image' texts

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2499]
**Steps:**
1. Login to SB (QA Instance)
2. Navigate to overview pages
3. Observe the font size and style

**A/R:** 1. Font size is too small 
2. Font style is incorrect and not consistent as per other text used in SB

**E/R:** 1. Font size should be increased 
2. Font style should be consistent as per other text used in SB

![Screenshot_1](https://user-images.githubusercontent.com/60386291/102615755-732c1e80-415c-11eb-8e86-cb92ad800297.png)

**Comment by pujithr** [comment]
Font size and style are corrected

**Comment by nishit-v** [comment]
Issue is resolved in QA.

**Comment by pujithr** [comment]
To test in DEV

**Comment by Lathan-btc** [comment]
@nishit-v issue is fixed in latest Dev instance.
