### ISSUE TITLE
[SB] [Overview] Alternate Image shouldn't be mandatory to complete section

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2502]
Steps:- 
1. Navigate to Overview section
2. Upload a image for Alternate image field
3. click on 'Mark As Complete' button
4. Revisit the overview section and remove the image uploaded in step 2
5.click on 'Mark As Complete' button and verify

A/R:- App shouldn't allow the user to complete section without Alternate image
E/R:-App should allow the user to complete section without Alternate image

Instance - QA

https://user-images.githubusercontent.com/60386291/102618423-c607d500-4160-11eb-9424-80a71a23003d.mp4

**Comment by pujithr** [comment]
Issue had resolved. Able to complete section without uploading alternate image.

**Comment by nagarjunav1** [comment]
Issue is resolved in latest QA build

**Comment by pujithr** [comment]
to test in Dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
