### ISSUE TITLE
[PM] Browser icon should be replaced for Participant Manager

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2505]
Browser Icon of the Participant Manager should be same as Study builder. 

Participant Manager and Study builder logo

![logo](https://user-images.githubusercontent.com/71445210/102615125-65c26480-415b-11eb-846b-fe5275002bbf.png)

Mobile app logo

![mobile logo1](https://user-images.githubusercontent.com/71445210/102616443-91464e80-415d-11eb-8b3c-da3d9bf69905.png)

**Comment by firdosebtc1** [comment]
@fahad-kc I have used the browser icon (favicon) provided by you, Please check and confirm in this ticket

**Comment by fahad-kc** [comment]
Shared the updated fav icon.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
@firdosebtc1 Issue is fixed in latest QA instance.

**Comment by nishit-v** [comment]
Issue is resolved in Dev Instance
