### ISSUE TITLE
[PM] Sites and Apps tab > Load more icon is displaying at end of tabs even though there are only 10 set of list available and due to this continuous loading animator

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2510]
**Steps:**
1. Navigate to sites/apps tab
2. When there are only 10 sets of data in each set, observe the load more icon

**A/R:** Load more icon is displaying at end of tabs even though there are only 10 set of list available and due to this continuous loading animator

**E/R:** Load more icon should not be displayed when there only 10 sets of data

Instance: Dev

Refer attached video:

**Sites tab:**

https://user-images.githubusercontent.com/60386291/102751445-c6d17e80-438d-11eb-8b3a-43cf3b520be1.mp4

**Apps tab:** 

https://user-images.githubusercontent.com/60386291/102751489-d94bb800-438d-11eb-897e-8cbde1ab7020.mp4

**Comment by Madhud5** [comment]
@prakashm181  Can u please look into this

**Comment by nishit-v** [comment]
Issue is fixed on QA.

**Comment by nishit-v** [comment]
Issue is resolved in Dev instance.
