### ISSUE TITLE
[SB] Instruction step created in Questionnaires is not displaying in the list 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2518]
Steps:- 
1. Navigate to Questionnaires and click on add questionnaire
2. Fill the required details in the screen and click on save button 
3. click on Add instruction Step and create a instruction step and click on Done button
4.  Verify whether created Instruction step is displaying in the list once it is created

![instructionStep](https://user-images.githubusercontent.com/60500517/102860958-d1a31680-4454-11eb-95af-5a708b0aba55.png)

**Comment by ESWAR1994** [comment]
I have worked on this issue and it is working

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
