### ISSUE TITLE
[PM] Participant details > Consent document is not shown in consent history when user joins another site for the same study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2525]
**Steps:**

1. Login to PM
2. Invite participant to a study in site A
3. User enrolls successfully
4. Withdraw from the study
5. PM admin adds same user to site B for the same study
6. Enroll into the study again 
7. Observe the participant details in Site A and Site B

**Actual Result:**
1. Participant details for site B doesn't have any consent
2. Participant details for site A has consent of site B

**Expected Result:**
1. Participant details for site B should have consent of site B only
2. Participant details for site A should have consent of site A only

**Site A:**

![Screenshot_5](https://user-images.githubusercontent.com/60386291/102897577-40509600-448e-11eb-8c16-ddcffecce476.png)

**Site B:**

![Screenshot_6](https://user-images.githubusercontent.com/60386291/102897603-4b0b2b00-448e-11eb-898d-ba58a4e4ec6d.png)

**Comment by nishit-v** [comment]
Unable to test due to #2471

**Comment by nishit-v** [comment]
Issue is still observed in Dev

**Comment by navya-BTC** [comment]
@nishit-v please test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
