### ISSUE TITLE
[PM] Enrollment status is updating wrongly when user joins another site for the same study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2526]
Steps
1. Login to PM
2. Invite participant to a study in site A
3. User enrolls successfully
4. Withdraw from the study
5. PM admin adds same user to site B for the same study
6. Enroll into the study again
7. Observe the enrollment status in site A participant registry.

[ Note : Issue should be handled for Site Participant Registry, Study Partcipant Registry and Participant details page ]

![Disabled status](https://user-images.githubusercontent.com/71445210/102898977-4e071b00-4490-11eb-9fa9-9539b3d86c3c.png)

**Comment by nishit-v** [comment]
Unable to test due to #2471

**Comment by nishit-v** [comment]
Issue is still observed

![Screenshot_1](https://user-images.githubusercontent.com/60386291/103263155-05d68400-49cd-11eb-9f35-6f24b458944b.png)

**Comment by Lathan-btc** [comment]
@aswinijena100 Issue is reproducible in latest QA instance.

**Comment by aswinijena100** [comment]
@Lathan-btc please test this issue in dev and let me know if it works fine

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
