### ISSUE TITLE
[PM] [Android] Participant details > Consent document is not shown for closed study having Eligibility test

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2527]
**Steps:**

1. Publish a study having token validation and Eligibility test
2. PM admin invites a user
3. Android Mobile participant enrolls into the study using valid token and passes the eligibility test
4. User enrolls successfully
5. Observe the participant details --> Consent History

**A/R:** Consent document is not shown for closed study having Eligibility test

**E/R:** Consent document should be shown for all type of studies

Note: Issue is not observed for closed study having token validation
Issue not observed for iOS users
![Screenshot_7](https://user-images.githubusercontent.com/60386291/102899937-a854ab80-4491-11eb-9f82-55489b1c8b98.png)

**Comment by nagarjunav1** [comment]
Issue is resolved now in latest DEV build
