### ISSUE TITLE
[PM] [Dev] getting 500 error when site permission is not given

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2528]
Getting 500 error when site permission is not given

AR : Displaying general error message
ER : 'No sites found' (EC_0070) should be displayed

![permission1](https://user-images.githubusercontent.com/71445210/102902197-a7714900-4494-11eb-9665-e6dcd52c361e.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA

**Comment by Lathan-btc** [comment]
@monica-BTC issue is fixed in latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in latest Dev instance.
