### ISSUE TITLE
[PM] Overview > Alternate image/Default image options are not available while creating a new study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2529]
**Steps:**

1. Login to SB (QA Instance)
2. Create study
3. Complete Basic info, settings & Admins section
4. Navigate to 'Overview' section
5. Observe

**Actual Result:** Alternate image/Default image options are not available while creating a new study

**Expected Result:** Alternate image/Default image options should be available while creating a new study

![Overview_Issue](https://user-images.githubusercontent.com/60386291/102903602-91fd1e80-4496-11eb-8615-e4cedcec1479.png)

**Comment by pujithr** [comment]
to test in Dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev
