### ISSUE TITLE
[SB][Overview] Side menu UI is not proper in Overview section

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2530]
Steps:- 
1.Navigate to Manage Studies section
2. Navigate to Overview section in Studies 
3. Verify the side menu in the Overview section

![Overview_UI](https://user-images.githubusercontent.com/60500517/102904240-79d9cf00-4497-11eb-9f5f-837c305f2ced.png)

**Comment by pujithr** [comment]
side menu in the Overview section is fixed

**Comment by nagarjunav1** [comment]
Issue is resolved now in latest QA build

**Comment by pujithr** [comment]
to test in Dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
