### ISSUE TITLE
[PM] Participant details page > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2531]
Participant details page > UI issue

![ui 1](https://user-images.githubusercontent.com/71445210/102904318-96760700-4497-11eb-919b-05b8847e6b20.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check DEV and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
