### ISSUE TITLE
[SB] Overview > Default image is not reflected in Mobile apps overview screens

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2533]
Steps:

1. Login to SB
2. In overview pages, don't upload any files and let images be default
3. Publish the updates
4. Navigate to overview screens in Mobile

A/R: Default image is not reflected in Mobile apps overview screens

E/R: Default image should be reflected in Mobile apps overview screens

![unnamed](https://user-images.githubusercontent.com/60386291/102906144-39c81b80-449a-11eb-8b95-ead6697e1589.jpg)

**Comment by nishit-v** [comment]
`Image` tag is passing empty string for overview pages which are default in GetStudyInfo API

Eg.

```
{
    "message": "SUCCESS",
    "studyWebsite": "",
    "info": [
        {
            "type": "video",
            "image": "",
            "title": "Image Study",
            "text": "2",
            "videoLink": ""
        },
        {
            "type": "text",
            "image": "",
            "title": "2",
            "text": "2",
            "videoLink": ""
        },
        {
            "type": "text",
            "image": "https://storage.googleapis.com/study-resources/studypages/STUDY_PAGE_2_11_12222020151833.jpg",
            "title": "3",
            "text": "3",
            "videoLink": ""
        },
        {
            "type": "text",
            "image": "",
            "title": "4",
            "text": "4",
            "videoLink": ""
        },
        {
            "type": "text",
            "image": "https://storage.googleapis.com/study-resources/studypages/STUDY_PAGE_4_11_12222020151834.jpg",
            "title": "5",
            "text": "5",
            "videoLink": ""
        }
    ],
    "anchorDate": {
        "type": "",
        "questionInfo": {
            "activityId": "",
            "activityVersion": "",
            "key": ""
        }
    },
    "withdrawalConfig": {
        "type": "no_action",
        "message": "j"
    }
}
```

**Comment by pujithr** [comment]
Code changes are made and merged in QA. Can you please check whether issue is resolved or not

**Comment by nishit-v** [comment]
Issue is still observed in QA.

**Comment by pujithr** [comment]
Code changes are made and merged in QA. Latest changes are present in QA after deployment. Can you please check whether issue is resolved or not.

**Comment by nishit-v** [comment]
Issue is still observed in QA. Please recheck from your end.

**Comment by nishit-v** [comment]
For 2nd,3rd,4th and 5th overview pages default image resolution should be 750*570.

Current implementation: 750*1334 pixels

**Comment by pujithr** [comment]
@nishit-v please verify in QA and Dev env. Let me know if it's fine

**Comment by pujithr** [comment]
{
    "message": "SUCCESS",
    "studyWebsite": "",
    "info": [
        {
            "type": "video",
            "image": "https://storage.googleapis.com/study-resources/studylogo/Overview_1.jpg",
            "title": "ClosedStudyEnrollment",
            "text": "page1",
            "videoLink": ""
        },
        {
            "type": "text",
            "image": "https://storage.googleapis.com/study-resources/studylogo/STUDY_DEFAULTIMAGE2.jpg",
            "title": "page2",
            "text": "page3",
            "videoLink": ""
        },
        {
            "type": "text",
            "image": "https://storage.googleapis.com/study-resources/studylogo/STUDY_DEFAULTIMAGE2.jpg",
            "title": "3",
            "text": "3",
            "videoLink": ""
        },
        {
            "type": "text",
            "image": "https://storage.googleapis.com/study-resources/studylogo/STUDY_DEFAULTIMAGE2.jpg",
            "title": "4",
            "text": "4",
            "videoLink": ""
        },
        {
            "type": "text",
            "image": "https://storage.googleapis.com/study-resources/studylogo/STUDY_DEFAULTIMAGE2.jpg",
            "title": "5",
            "text": "5",
            "videoLink": ""
        }
    ],
    "anchorDate": {
        "type": "",
        "questionInfo": {
            "activityId": "",
            "activityVersion": "",
            "key": ""
        }
    },
    "withdrawalConfig": {
        "type": "no_action",
        "message": "Are you sure you want to leave the study?"
    }
}

**Comment by nishit-v** [comment]
Issue is resolved in QA and Dev
