### ISSUE TITLE
SB > Padding issues with logo on Terms, Privacy Policy screens

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2536]
Width of the top menu bar portion of the screen and padding for the logo needs to be adjusted on both screens.
![Terms screen](https://user-images.githubusercontent.com/63093896/102919540-0f348d80-44af-11eb-8eeb-d8f19b8a63ed.JPG)
![PP screen](https://user-images.githubusercontent.com/63093896/102919546-10fe5100-44af-11eb-8580-bdfff2f08eff.JPG)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirms in QA instance.

**Comment by Lathan-btc** [comment]
@madhurya-btc issue is fixed in latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in latest Dev instance.

**Comment by SR-btc** [comment]
Padding above and below logo still needs adjustment. The height of the top white bar as a whole should look similar to other screens of the SB that also have a top white bar.

**Comment by madhurya-btc** [comment]
@SR-btc Please test and confirm in QA instance

**Comment by madhurya-btc** [comment]
@SR-btc Please test in Dev instance and confirm.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and close in Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
