### ISSUE TITLE
SB > Study List UI

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2537]
Increase left margin for the Study ID column
Space out the column widths in a proportionate manner to be well-distributed across the screen

![SB list](https://user-images.githubusercontent.com/63093896/102919710-5b7fcd80-44af-11eb-9820-2318da914602.JPG)

**Comment by Madhud5** [comment]
Hi @ESWAR1994  please look into this issue.

**Comment by ESWAR1994** [comment]
left margin for the Study ID column is there for drag and drop Sharath need to looking into that

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
