### ISSUE TITLE
SB> Logo > Placement of 'Customer logo' text needs adjustment

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2538]
Consider making the 'Customer logo' text placement align with rest of the menu. 
Either center align to match with rest of menu, or decrease font size of Customer Logo and place it near the bottom right of the picture logo.
Please check this for PM web app as well
![logo bar](https://user-images.githubusercontent.com/63093896/102920173-3a6bac80-44b0-11eb-91b5-8fb9bdcc2077.JPG)

**Comment by fahad-kc** [comment]
Updated! Please check the following links. 

PM 
https://invis.io/PTZCZEAAV95#/399266904_02_Site_Listing

GCP
https://invis.io/GYZDI0WVF87#/436563835_08_Studies

**Comment by fahad-kc** [comment]
Updated logos has been shared!

**Comment by firdosebtc1** [comment]
@harisboston please change in login screen also

**Comment by madhurya-btc** [comment]
@firdosebtc1 For SB, I have pushed new logo to QA instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test in QA instance.
Note: Please clear cache before testing.

**Comment by Lathan-btc** [comment]
@madhurya-btc Customer logo should be aligned properly in 'Terms and Condistions' page

![logo2](https://user-images.githubusercontent.com/71445210/102986691-3a62bf80-4537-11eb-8f08-4a8bb77cea39.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this PM web app QA

**Comment by madhurya-btc** [comment]
> @madhurya-btc Customer logo should be aligned properly in 'Terms and Condistions' page
> 
> ![logo2](https://user-images.githubusercontent.com/71445210/102986691-3a62bf80-4537-11eb-8f08-4a8bb77cea39.png)

@Lathan-btc Please test now in QA instance and confirms the same.

**Comment by Lathan-btc** [comment]
@madhurya-btc issue is fixed for Study Builder

**Comment by firdosebtc1** [comment]
> @Lathan-btc I have changed the logo in PM web app QA, please check

@Lathan-btc please check this

**Comment by harisboston** [comment]
Customer Logo for Sign-in screen was fixed in PR:  oauth server- issue Replace placeholder icon with FDA MyStudies icon throughout codebase #1270 #2483

**Comment by Lathan-btc** [comment]
@firdosebtc1 issue is fixed in latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in latest Dev instance.
