### ISSUE TITLE
Hydra registration script - rm issue

### ISSUE THREAD

**Issue by moschetti** [GoogleCloudPlatform/fda-mystudies#2539]
When running this script, it returns:
```
rm: missing operand
Try 'rm --help' for more information.
```
Looks like the line below tries to remove a variable which isn't set.

https://github.com/GoogleCloudPlatform/fda-mystudies/blob/ae86296c0aa7d18951bdf48ad645b3d920c46331/deployment/scripts/register_clients_in_hydra.sh#L84

**Comment by mohangmk** [comment]
@moschetti ,

I would like to check whether this issue is valid any more or not. Since, we are not facing this error while executing the script from Master branch. Please let us know your thoughts.

If it is not valid any more then please close the issue

**Comment by mohangmk** [comment]
@moschetti 
I would like to follow up on above tickets, whether this ticket is valid or not. Please confirm

**Comment by mohangmk** [comment]
@moschetti 
We are closing this issue, as we didn't see this error anymore. Please feel free to reopen this ticket, if it is replicable.
