### ISSUE TITLE
Customer logo should be displayed in About and Terms of Service pages

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2542]
AR : Logo is not displayed in 'About' and 'Terms of Service' pages
ER : Customer logo should be displayed in 'About' and 'Terms of Service' pages

![logo terms](https://user-images.githubusercontent.com/71445210/102970167-09759100-451d-11eb-8f88-9c520fa7613a.png)

**Comment by Lathan-btc** [comment]
@Madhud5 and @firdosebtc1 Customer logo should be displayed in all the pages ( error page, 404 page).

**Comment by Madhud5** [comment]
i have checked in DEV- QA its fixed. Please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is fixed in latest QA instace.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 
404 error page

AR : 1. Customer logo is not displayed
       2. 'Page not found' text is displayed under 404
ER : 1. Customer logo should be displayed
       2. 'Page not found' text should not be displayed under 404

![page not found](https://user-images.githubusercontent.com/71445210/103985529-1cd85b80-51af-11eb-80cb-9ba69e5e5be2.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have fixed please check and close the issue.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check DEV and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
