### ISSUE TITLE
[PM] Site level permission > 'Add Site' button is displayed for users with 'View & Edit' site permission

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2545]
**Stesp:**

1. Assign a user with View and Edit site permission to any closed study
2. Login with that user
3. Navigate to sites tab
4. Observe that 'Add Site' button is displayed

**Actual Result:** 'Add Site' button is displayed for users with 'View & Edit' site permission

**Expected Result:** : 'Add Site' button should not be displayed for users with 'View & Edit' site permission and instead should be dislayed for Study level and app level

Issue observed in QA and Dev

![Screenshot_2](https://user-images.githubusercontent.com/60386291/102987789-e78a0780-4538-11eb-92a4-73a4144e0ccb.png)

**Comment by firdosebtc1** [comment]
@aswinijena100 in sites api response studyPermission attribute value is coming as 1 even though the user is having only site level permission, PLease see attached image

![image](https://user-images.githubusercontent.com/60000166/103079889-c853ae80-45fa-11eb-805e-70cf7f225557.png)

**Comment by chiranjibi009** [comment]
@nishit-v Please check this issue in QA environment and update.

**Comment by nishit-v** [comment]
Issue is resolved in QA.
