### ISSUE TITLE
Dashboard tab is not highlighted

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2546]
AR : Dashboard tab is not highlighted
ER : Dashboard tab should be highlighted when user is present in the following screens
       1. Site participant registry
       2. Study participant registry
       3. Participant details page  

![dashboard issue](https://user-images.githubusercontent.com/71445210/102988457-ec9b8680-4539-11eb-984e-22037371501b.png)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in latest Dev instance.
