### ISSUE TITLE
[PM] Participant details page > Alignment of participant emails is not proper for users with 'View' site/study/app permission

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2547]
**Steps:**

1. Login with the user having View site/Study/App level permission
2. Navigate to participant details page
3. Observe the alignment

**Actual:** Alignment of participant emails is not proper for users with 'View' site/study/app permission

**Expected:** Alignment should be proper

![Screenshot_1](https://user-images.githubusercontent.com/60386291/102988783-79464480-453a-11eb-9cfc-434ff5a9245d.png)

**Comment by Madhud5** [comment]
Hi @nishit-v i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is still reproducible in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is reproducible for both QA and Dev instances.

**Comment by Madhud5** [comment]
Hi @prakashm181, please look into this issue - depends on the user's role permission.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  I have fixed it please check-in QA env and confirms here.

**Comment by Madhud5** [comment]
Hi @Lathan-btc can u pls check this issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi, @Lathan-btc I have checked in DEV- QA it's fixed. Please check and close the issue.

**Comment by nishit-v** [comment]
Issue is resolved in QA Instance.
