### ISSUE TITLE
[SB] [Dev] Questionnaires > Unable to delete questionnaires

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2548]
**Steps:**

1. Create a questionnaire in SB
2. Create instr/question/form step
3. Click on done
4. Click on Delete
5. Observe that message is displayed but the questionnaire is not deleted

**A/R:** Unable to delete questionnaires

**E/R:** Questionnaires should be deleted

**Note:** Issue not observed in QA
Issue also observed for published Questionnaires
Issue also observed for instr/question/form step

**Refer video:**

https://user-images.githubusercontent.com/60386291/102990621-b19b5200-453d-11eb-83f2-4d76c12d0fc2.mp4

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm.

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
