### ISSUE TITLE
[Study builder] Studies > Questionnaires > Edit Questionnaires > Question step > Text choices > issue when user selects the 'Include 'Other' as an option ?' checkbox

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2549]
Steps

1. Click on any study
2. Questionnaires > Add Questionnaire > Question step
3. Question level attributes > select 'Text choice' response type
4. Navigate to Response level attributes > Don't enter any values in text choices
5. Select 'Include 'Other' as an option ?' checkbox and enter all the mandatory fields and create a questionnaire
6. Click on edit questionnaire and observe the displayed contents in response level atributes

![other option issue1](https://user-images.githubusercontent.com/71445210/102991193-c9bfa100-453e-11eb-8812-98a1c802e272.png)

**Comment by Lathan-btc** [comment]
@madhurya-btc issues
1. Create a questionnare with 'Text choice' response type (Single select) > Click on Edit questionnare > Response level attribute > observe the fields > 'Mark as exclusive' should not shown

![image111](https://user-images.githubusercontent.com/71445210/102996225-b74a6500-4548-11eb-8913-a7ebaf83cc63.png)


2. Create questionnaire > Text choice > Respose level attribute > enter the some values and select 'Include 'Other' as an option ?' checkbox > click on save > Click on back button > Again click on edit questionnare and observe the data > Selected checkbox is unselected

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test in QA and confirms

**Comment by Lathan-btc** [comment]
@madhurya-btc 
1. Create questionnaire > Text choice > Response level attribute > Select 'Include 'Other' as an option ?' checkbox and enter the values > click on save > Click on back button > Again click on edit questionnaire and deselect ''Include 'Other' as an option ?' and click on save  > again click on edit questionnaire and observe > previously selected values are displayed

2. Create questionnaire > Text choice > Response level attribute > enter the some values and select 'Include 'Other' as an option ?' checkbox > click on save > Click on back button > Again click on edit questionnaire add one more text choice and deselect the checkbox and try to delete the choices when user have only 2 choices
AR : User is able to delete the text choices when user have only 2 choices
ER : User should be able to delete the choices

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm

**Comment by Lathan-btc** [comment]
@madhurya-btc 
Add questionnaire > Question step > text choice > Response level attribute > Multiple select > Enter valid inputs  > Click on Save or Done button > click on edit question > go to response level attributes and observe the fields

AR : 'Mark as exclusive' field is not displayed and entered data in the description field is removed
ER : 'Mark as exclusive' field and entered data in the description field if the normal choice should be displayed.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
@madhurya-btc issue is fixed in latest QA instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.
