### ISSUE TITLE
[SB] Database > Users table > 'user_login_datetime' is not updated when SB admin log in

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2551]
**Steps:**
1. Login to SB as admin
2. Check 'user_login_datetime' column in 'users' table
3. Observe that value is not updated

**A/R:** 'user_login_datetime' is not updated when SB admin log in

**E/R:** 'user_login_datetime' should updated accordingly when SB admin log in

Instance: QA and Dev

**Comment by aswinijena100** [comment]
@nishit-v issue fixed in QA now. Please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in QA.

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
