### ISSUE TITLE
Cutomer logo > Alignment issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2555]
1. Cutomer logo > Alignment issue
2. My Account circle icon text is not centralized 

[Note : Issue should be fixed in all screens]

![logo3](https://user-images.githubusercontent.com/71445210/103030083-188e2a80-4581-11eb-8989-d4eed1c96e16.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
HI @Lathan-btc i have fixed please check and close the issue.
