### ISSUE TITLE
[PM & Mobile Apps] [QA] Customer logo should be displayed in Sign in screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2556]
Customer logo should be displayed in Sign in screen

[Note : Issue observed in QA instance]

![sign in](https://user-images.githubusercontent.com/71445210/103062308-c75b5680-45d3-11eb-993e-948e813bbe8f.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and confirm.

**Comment by Lathan-btc** [comment]
@harisboston Issue is fixed in latest QA instance.
