### ISSUE TITLE
[PM] Signin > Remove 'Forgot Password?' hyperlink in blank spaces

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2557]
Steps:
1. Navigate to login page
2. Mouse over the blank space present next to signin button
3. Observe

Refer attached screenshot:
![Signin](https://user-images.githubusercontent.com/60386291/103064232-9bdb6a80-45d9-11eb-8407-c66814b288bb.png)

**Comment by harisboston** [comment]
@nishit-v Fix is deployed in QA environment, kindly test and confirm.

**Comment by nishit-v** [comment]
Issue is resolved in QA.

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
