### ISSUE TITLE
'No records found' should be displayed when admin doesn't have any site level, study level, app level permission 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2561]
1. 'No records found' text should be displayed when there are no data in the database
2. 'No records found' text should be displayed when there are some data in the database and the user does not have any 
    permission for sites
3. Proper custom messages should be displayed when a normal admin user doesn't meet conditions related to permission for the following 
 
  i. Study level permission
AR : 'This view displays study-wise enrollment if you manage multiple sites' error message is displayed
ER : 'This view displays study-wise enrollment if you manage multiple sites' text should be displayed in the attached screen instead of an error message

   ii. App-level permission
AR : 'This view displays app-wise enrollment if you manage multiple studies.' error message is displayed
ER : 'This view displays app-wise enrollment if you manage multiple studies' text should be displayed in the attached screen instead of an error message

ER:
![permission ui](https://user-images.githubusercontent.com/71445210/103070664-fe3b6780-45e7-11eb-98d1-6e81689fdce8.png)

**Comment by firdosebtc1** [comment]
@Madhud5 please replace "No records found" text with new UI in the div mentioned below

`  <div class="bg__white card__inside__pad box__shadow-cmn m-none p-lg">
          <div class="text-center p-2" *ngIf="studies.studies.length === 0">
            No records found
          </div>
        </div>`

**Comment by Madhud5** [comment]
HI @firdosebtc1  its had  already "No records found" text with new UI in the div, please check with @Lathan-btc  will explain you.
Thank you

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
