### ISSUE TITLE
[iOS] [Audit Logs] "participantId" is displayed null for the events

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2562]
**Events:**

Module: **Consent Service(Participant Datastore):**
1. USER_ENROLLED_INTO_STUDY
2. READ_OPERATION_SUCCEEDED_FOR_SIGNED_CONSENT_DOCUMENT
3. SIGNED_CONSENT_DOCUMENT_SAVED

Module: **Enroll(Participant Datastore)**
4. STUDY_STATE_SAVED_OR_UPDATED_FOR_PARTICIPANT
5. READ_OPERATION_SUCCEEDED_FOR_STUDY_INFO

Module: **Response Datastore**
6. PARTICIPANT_ID_GENERATED

Sample snippet for event `PARTICIPANT_ID_GENERATED` event

```
{
  "insertId": "1s3rqdog25k19og",
  "jsonPayload": {
    "occurred": 1608726951718,
    "userIp": "35.222.67.4",
    "sourceApplicationVersion": "1.0",
    "source": "PARTICIPANT USER DATASTORE",
    "studyId": null,
    "siteId": null,
    "appVersion": "1.0.146",
    "mobilePlatform": "IOS",
    "eventCode": "PARTICIPANT_ID_GENERATED",
    "userAccessLevel": null,
    "resourceServer": null,
    "userId": "ad4b3ff0n3178t484bl8bdch9bd1ba58d9f8",
    "correlationId": "EC2192BC-A5B3-4040-AD48-EC1530795682",
    "participantId": null,
    "destinationApplicationVersion": "1.0",
    "studyVersion": null,
    "platformVersion": "1.0",
    "appId": "",
    "destination": "RESPONSE DATASTORE",
    "description": null
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "mystudies-open-impl-track1-dev"
    }
  },
  "timestamp": "2020-12-23T12:35:51.718Z",
  "severity": "INFO",
  "logName": "projects/mystudies-open-impl-track1-dev/logs/application-audit-log",
  "receiveTimestamp": "2020-12-23T12:35:51.864217708Z"
}
```

**Comment by chiranjibi009** [comment]
@nishit-v please test this issue and update

**Comment by nishit-v** [comment]
Issue is not fixed for below event:

STUDY_STATE_SAVED_OR_UPDATED_FOR_PARTICIPANT

![2562_1](https://user-images.githubusercontent.com/60386291/104698756-d9926580-5737-11eb-9be7-71694a447b5f.png)

Issue is resolved for other remaining events

**Comment by naveenr-btc** [comment]
@chiranjibi009 the default value should be n/a if mobile is not sending the participantId

**Comment by nishit-v** [comment]
STUDY_STATE_SAVED_OR_UPDATED_FOR_PARTICIPANT

participantId is displayed for iOS users in V1.0.167.

**Comment by nagarjunav1** [comment]
STUDY_STATE_SAVED_OR_UPDATED_FOR_PARTICIPANT

participant ID is displayed for Android users in V1.0.58

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue and update.

**Comment by nishit-v** [comment]
Issue is resolved in Dev. participantId value is displaying 'NA' before enrolling in mobile

![Screenshot_1](https://user-images.githubusercontent.com/60386291/105955904-02eab400-609d-11eb-990c-b1e7276f0107.png)
