### ISSUE TITLE
[iOS] [Audit Logs] "studyVersion" is displayed null for the events

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2565]
**Events:**

Module - **Consent Service(Participant Datastore):**

1. USER_ENROLLED_INTO_STUDY
2. READ_OPERATION_SUCCEEDED_FOR_SIGNED_CONSENT_DOCUMENT
3. SIGNED_CONSENT_DOCUMENT_SAVED

Module - **Enroll(Participant Datastore)**

1. USER_FOUND_ELIGIBLE_FOR_STUDY
2. ENROLLMENT_TOKEN_FOUND_INVALID
3. PARTICIPANT_ID_RECEIVED
4. STUDY_STATE_SAVED_OR_UPDATED_FOR_PARTICIPANT
5. WITHDRAWAL_FROM_STUDY_SUCCEEDED
6. READ_OPERATION_SUCCEEDED_FOR_ENROLLMENT_STATUS
7. READ_OPERATION_SUCCEEDED_FOR_STUDY_INFO

Module - **Response Datastore**

1. PARTICIPANT_ID_GENERATED
2. ACTIVITY_RESPONSE_RECEIVED
3. ACTIVTY_METADATA_RETRIEVED
4. ACTIVITY_METADATA_CONJOINED_WITH_RESPONSE_DATA
5. DATA_SHARING_CONSENT_VALUE_RETRIEVED
6. DATA_SHARING_CONSENT_VALUE_CONJOINED_WITH_ACTIVITY_RESPONSE_DATA
7. ACTIVITY_RESPONSE_SAVED
8. WITHDRAWAL_INFORMATION_UPDATED
9. PARTICIPANT_RESPONSE_DATA_DELETED
10. ACTIVITY_STATE_SAVED_OR_UPDATED_AFTER_RESPONSE_SUBMISSION
11. PARTICIPANT_ACTIVITY_DATA_DELETED
12. PARTICIPANT_WITHDRAWAL_INTIMATION_FROM_PARTICIPANT_DATASTORE
13. ACTIVITY_STATE_SAVED_OR_UPDATED
14. READ_OPERATION_FOR_ACTIVITY_STATE_INFO_SUCCEEDED

Sample snippet for event `PARTICIPANT_ID_GENERATED` event

```
{
  "insertId": "1s3rqdog25k19og",
  "jsonPayload": {
    "occurred": 1608726951718,
    "userIp": "35.222.67.4",
    "sourceApplicationVersion": "1.0",
    "source": "PARTICIPANT USER DATASTORE",
    "studyId": null,
    "siteId": null,
    "appVersion": "1.0.146",
    "mobilePlatform": "IOS",
    "eventCode": "PARTICIPANT_ID_GENERATED",
    "userAccessLevel": null,
    "resourceServer": null,
    "userId": "ad4b3ff0n3178t484bl8bdch9bd1ba58d9f8",
    "correlationId": "EC2192BC-A5B3-4040-AD48-EC1530795682",
    "participantId": null,
    "destinationApplicationVersion": "1.0",
    "studyVersion": null,
    "platformVersion": "1.0",
    "appId": "",
    "destination": "RESPONSE DATASTORE",
    "description": null
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "mystudies-open-impl-track1-dev"
    }
  },
  "timestamp": "2020-12-23T12:35:51.718Z",
  "severity": "INFO",
  "logName": "projects/mystudies-open-impl-track1-dev/logs/application-audit-log",
  "receiveTimestamp": "2020-12-23T12:35:51.864217708Z"
}
```

**Comment by chiranjibi009** [comment]
@nishit-v please test this issue and update

**Comment by nishit-v** [comment]
Issue is resolved for above Consent and Enroll module events.

@sharathblr "studyVersion" is displayed as null for all the response module events. Is this fine?

**Comment by sharathblr** [comment]
Study Version cannot be null for the triggered events.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue and update.

**Comment by nishit-v** [comment]
"StudyVersion" is displayed as "NA" /null for below events. Rest events are fixed

1. ACTIVITY_STATE_SAVED_OR_UPDATED
2. READ_OPERATION_FOR_ACTIVITY_STATE_INFO_SUCCEEDED
3. STUDY_METADATA_RECEIVED
4. READ_OPERATION_FOR_ACTIVITY_STATE_INFO_SUCCEEDED

![Screenshot_8](https://user-images.githubusercontent.com/60386291/105503770-0113a000-5ced-11eb-95d1-01ee4e7efcbc.png)
![Screenshot_7](https://user-images.githubusercontent.com/60386291/105503783-0375fa00-5ced-11eb-9a3c-415db7919b44.png)
![Screenshot_9](https://user-images.githubusercontent.com/60386291/105504179-77180700-5ced-11eb-8db7-1d3110607d7f.png)
![Screenshot_10](https://user-images.githubusercontent.com/60386291/105504478-d249f980-5ced-11eb-93bd-32df4d59365e.png)

**Comment by chiranjibi009** [comment]
@nishit-v `study version` should be `NA` as of now for below events as discussed with Shantala.
1. ACTIVITY_STATE_SAVED_OR_UPDATED (Study version  : NA)
2. READ_OPERATION_FOR_ACTIVITY_STATE_INFO_SUCCEEDED (Study version  : NA)

I have fixed the `study version` for this event.
3. STUDY_METADATA_RECEIVED

_4. READ_OPERATION_FOR_ACTIVITY_STATE_INFO_SUCCEEDED_ event is same as number 2.

Please test this fixes and update

**Comment by nishit-v** [comment]
Unable to test Event 3. STUDY_METADATA_RECEIVED due to #2572

**Comment by nishit-v** [comment]
Tracking above event in a seperate ticket #3039. Remaining events are tested and fixed.

**Comment by chiranjibi009** [comment]
![image](https://user-images.githubusercontent.com/59357395/105994691-fb8fce80-60cd-11eb-9fa2-ee17434b4152.png)

@nishit-v as I can see `study version` is getting captured for `STUDY_METADATA_RECEIVED `event.
Please test this issue form your end and update.

**Comment by nishit-v** [comment]
We have a sperate event STUDY_METADATA_RECEIVED in User management module where Destination is PARTICIPANT USER DATASTORE. You have attached the screenshot for this event.

Actual Issue is in Response Datastore module where Destination is RESPONSE DATASTORE

**Comment by chiranjibi009** [comment]
![image](https://user-images.githubusercontent.com/59357395/105995588-31818280-60cf-11eb-8141-c890bd20d97e.png)

Now, Please check this one.
