### ISSUE TITLE
[Hydra] [Audit Logs] Events are not triggered for PM and Mobile apps

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2568]
**Events:**

1. PASSWORD_HELP_EMAIL_FAILED
2. PASSWORD_RESET_EMAIL_SENT_FOR_LOCKED_ACCOUNT
3. PASSWORD_RESET_EMAIL_FAILED_FOR_LOCKED_ACCOUNT

Note: When Email service is disabled 1st and 3rd event should be triggered

**Comment by harisboston** [comment]
@nishit-v Fix is merged in Dev. environment, kindly test and update this ticket

**Comment by nagarjunav1** [comment]
Issue is resolved for event
1. PASSWORD_RESET_EMAIL_SENT_FOR_LOCKED_ACCOUNT
Issue is not resolved for events
2. PASSWORD_HELP_EMAIL_FAILED
3. PASSWORD_RESET_EMAIL_FAILED_FOR_LOCKED_ACCOUNT

**Comment by harisboston** [comment]
@nagarjunav1 Fix is deployed in QA environment, kindly test and update this ticket

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
