### ISSUE TITLE
[Audit Logs]  Event is not triggered for consent module in Android and iOS

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2569]
**Event:**

INFORMED_CONSENT_PROVIDED_FOR STUDY

**Comment by nagarjunav1** [comment]
Issue is fixed for IOS and not fixed for Android.

**Comment by navya-BTC** [comment]
@nagarjunav1 please retest this issue in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in Android in latest DEV build.
