### ISSUE TITLE
[Audit Logs] Events are not triggered for Mobile apps in User Management bundle

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2571]
**Events:**

1. REGISTRATION_SUCCEEDED
2. WITHDRAWAL_INTIMATED_TO_RESPONSE_DATASTORE
3. PARTICIPANT_DATA_DELETED

**Comment by monica-BTC** [comment]
@nishit-v Below events are triggered, please retest and confirm
STUDY_METADATA_RECEIVED
PUSH_NOTIFICATION_SENT
PUSH_NOTIFICATION_FAILED

**Comment by nishit-v** [comment]
@monica-BTC Below events are triggering now in Dev instance.

1. STUDY_METADATA_RECEIVED
2. PUSH_NOTIFICATION_SENT
3. PUSH_NOTIFICATION_FAILED

**Comment by monica-BTC** [comment]
@SR-btc , WITHDRAWAL_INTIMATED_TO_RESPONSE_DATASTORE and PARTICIPANT_DATA_DELETED will not be triggered. So needed clarification to remove the events.

**Comment by sharathblr** [comment]
Per the new implementation in the SB, the data deletion pop-up will not be available and data rentention will always be retained for the participant when the account deleted. Hence the below event will not be triggered, per the new requirement :
WITHDRAWAL_INTIMATED_TO_RESPONSE_DATASTORE
PARTICIPANT_DATA_DELETED

**Comment by monica-BTC** [comment]
@nishit-v , please test and confirm

**Comment by nishit-v** [comment]
Below event is not triggered for iOS.

WITHDRAWAL_INTIMATED_TO_RESPONSE_DATASTORE

Steps followed:
1. Login/signup
2. Enroll into a study successfully
3. Delete the app account
4. Observe the events

Issue not observed for android

**Comment by monica-BTC** [comment]
@tushar-boston, can you confirm that you are sending same request as Android when the user is enrolled into a study and deleting the app account.

**Comment by nishit-v** [comment]
Issue is resolved now in V1.0.165 iOS build.

**Comment by nagarjunav1** [comment]
@tushar-boston Raise the PR and attach to the Issue and close the issue once merged into DEV
