### ISSUE TITLE
[PM] [Dev] Open study > Enrollment registry > Pagination issue  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2575]
AR : 2nd page is getting displayed eventhough a study has less than or equal to 10 participant records
ER : If the study has less than or equal to 10 participant records, then 2nd page should not be displayed 

![pagination2](https://user-images.githubusercontent.com/71445210/103085324-651c4900-4607-11eb-9313-ef45029d98c7.png)

![pagination 1](https://user-images.githubusercontent.com/71445210/103085309-5897f080-4607-11eb-95e1-aee45c19c5fd.png)

**Comment by firdosebtc1** [comment]
@aswinijena100 totalParticipantCount: 12 is coming in ersponse but response has only 8 participants 

![image](https://user-images.githubusercontent.com/60000166/103093390-3199e880-4620-11eb-95ea-bfc7e4224931.png)

and when we click on second page ,response is having 0 participants

![image](https://user-images.githubusercontent.com/60000166/103093402-3e1e4100-4620-11eb-9932-8c031af7fb97.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
