### ISSUE TITLE
[Android] [Audit Logs] "studyVersion" is displayed null for the events

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2576]
Events:

Module - Consent Service(Participant Datastore):

1. USER_ENROLLED_INTO_STUDY
2. READ_OPERATION_SUCCEEDED_FOR_SIGNED_CONSENT_DOCUMENT
3. SIGNED_CONSENT_DOCUMENT_SAVED

Module - Enroll(Participant Datastore)

1. USER_FOUND_ELIGIBLE_FOR_STUDY
2. ENROLLMENT_TOKEN_FOUND_INVALID
3. PARTICIPANT_ID_RECEIVED
4. STUDY_STATE_SAVED_OR_UPDATED_FOR_PARTICIPANT
5. WITHDRAWAL_FROM_STUDY_SUCCEEDED
6. READ_OPERATION_SUCCEEDED_FOR_ENROLLMENT_STATUS
7. READ_OPERATION_SUCCEEDED_FOR_STUDY_INFO

Module - Response Datastore

1. PARTICIPANT_ID_GENERATED
2. ACTIVITY_RESPONSE_RECEIVED
3. ACTIVTY_METADATA_RETRIEVED
4. ACTIVITY_METADATA_CONJOINED_WITH_RESPONSE_DATA
5. DATA_SHARING_CONSENT_VALUE_RETRIEVED
5. DATA_SHARING_CONSENT_VALUE_CONJOINED_WITH_ACTIVITY_RESPONSE_DATA
6. ACTIVITY_RESPONSE_SAVED
7. WITHDRAWAL_INFORMATION_UPDATED
8. PARTICIPANT_RESPONSE_DATA_DELETED
9. ACTIVITY_STATE_SAVED_OR_UPDATED_AFTER_RESPONSE_SUBMISSION
10. PARTICIPANT_ACTIVITY_DATA_DELETED
11. PARTICIPANT_WITHDRAWAL_INTIMATION_FROM_PARTICIPANT_DATASTORE
12. ACTIVITY_STATE_SAVED_OR_UPDATED
13. READ_OPERATION_FOR_ACTIVITY_STATE_INFO_SUCCEEDED

 Sample snippet for event PARTICIPANT_ID_GENERATED event
 ```
 {
  "insertId": "1c0c40fg20iu35u",
  "jsonPayload": {
    "destinationApplicationVersion": "1.0",
    "userId": "0c63919ewc6bcy4aa7x9d3cnb89d0b9f9f89",
    "description": null,
    "platformVersion": "1.0",
    "sourceApplicationVersion": "1.0",
    "mobilePlatform": "ANDROID",
    "appId": "",
    "correlationId": "F0OOfsb13gjC1FrGz4juvLJZpMtix0MWtfONkRP36urUvEUXqZ",
    "studyVersion": null,
    "resourceServer": null,
    "appVersion": "1.0.42",
    "studyId": null,
    "userIp": "35.222.67.4",
    "occurred": 1608799292416,
    "destination": "RESPONSE DATASTORE",
    "source": "PARTICIPANT USER DATASTORE",
    "userAccessLevel": null,
    "participantId": null,
    "eventCode": "PARTICIPANT_ID_GENERATED",
    "siteId": null
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "mystudies-open-impl-track1-dev"
    }
  },
  "timestamp": "2020-12-24T08:41:32.416Z",
  "severity": "INFO",
  "logName": "projects/mystudies-open-impl-track1-dev/logs/application-audit-log",
  "receiveTimestamp": "2020-12-24T08:41:32.560097837Z"
}
 ```

**Comment by nishit-v** [comment]
Tracking same in #2565
