### ISSUE TITLE
SB > Redirect to/use new error page 

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2594]
Replace the existing UI for the error page with an updated design, redirect users to the new error page with appropriate message for all error page scenarios

**Comment by SR-btc** [comment]
![error page SB](https://user-images.githubusercontent.com/63093896/103403015-b92dad00-4b74-11eb-94dd-3f6b1974ffdd.JPG)

**Comment by Lathan-btc** [comment]
@monica-BTC Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
