### ISSUE TITLE
[SB] [Audit Logs] Event is not triggered for Replicate Notification

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2599]
**Event:**

APP_LEVEL_NOTIFICATION_REPLICATED_FOR_RESEND

**Steps:**
1. Navigate to Manage Notifications
2. Click on Replicate icon(copy)
3. Resend the notification
4. Observe the events

**Actual:** Event is not triggered for Replicate Notification

**Expected:** Event should be triggered for Replicate Notification

**Note:** Event is triggered for Resend notification

**Comment by aswinijena100** [comment]
@nishit-v Event logged in Dev without any changes . Please reverify and close the ticket.
![APP_LEVEL_NOTIFICATION_REPLICATED_FOR_RESEND](https://user-images.githubusercontent.com/59355719/105140086-39fd1a80-5b1d-11eb-8ced-a99b4c762c13.jpg)

**Comment by nishit-v** [comment]
Issue is resolved now in Dev on rechecking
