### ISSUE TITLE
[SB] [Audit Logs] "studyId" is displayed null for the events

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2601]
**Events:**

1. STUDY_VIEWED
2. LAST_PUBLISHED_VERSION_OF_STUDY_VIEWED
3. STUDY_ACCESSED_IN_EDIT_MODE
4. STUDY_PUBLISHED_AS_UPCOMING_STUDY
5. STUDY_LAUNCHED
6. STUDY_PAUSED
7. STUDY_RESUMED
8. UPDATES_PUBLISHED_TO_STUDY
9. STUDY_DEACTIVATED
10. NEW_STUDY_CREATION_INITIATED
11. STUDY_BASIC_INFO_SECTION_SAVED_OR_UPDATED
12. STUDY_BASIC_INFO_SECTION_MARKED_COMPLETE
13. STUDY_SETTINGS_SAVED_OR_UPDATED
14. STUDY_SETTINGS_MARKED_COMPLETE
15. STUDY_CONSENT_SECTIONS_SAVED_OR_UPDATED
16. STUDY_COMPREHENSION_TEST_SECTION_SAVED_OR_UPDATED
17. STUDY_COMPREHENSION_TEST_SECTION_MARKED_COMPLETE
18. STUDY_REVIEW_AND_E_CONSENT_SAVED_OR_UPDATED
19. STUDY_REVIEW_AND_E_CONSENT_MARKED_COMPLETE
20. STUDY_CONSENT_CONTENT_NEW_VERSION_PUBLISHED
21. STUDY_CONSENT_DOCUMENT_NEW_VERSION_PUBLISHED
22. STUDY_ACTIVE_TASK_SAVED_OR_UPDATED
23. STUDY_ACTIVE_TASK_MARKED_COMPLETE
24. STUDY_NEW_NOTIFICATION_CREATED
25. STUDY_NOTIFICATION_SAVED_OR_UPDATED
26. STUDY_NOTIFICATION_MARKED_COMPLETE

Sample snippet for STUDY_VIEWED event

```
{
  "insertId": "1sxzbptg1ecd7ci",
  "jsonPayload": {
    "mobilePlatform": null,
    "participantId": null,
    "userAccessLevel": "STUDY BUILDER ADMIN",
    "siteId": null,
    "appVersion": "1.0",
    "description": null,
    "occurred": 1608016529046,
    "resourceServer": null,
    "studyId": null,
    "studyVersion": null,
    "appId": "STUDY BUILDER",
    "destinationApplicationVersion": "1.0",
    "correlationId": "a7cbacad-3214-4b2d-b650-05d8d71891ad",
    "userIp": "59.92.251.162",
    "userId": "133",
    "eventCode": "STUDY_VIEWED",
    "platformVersion": "1.0",
    "destination": "STUDY DATASTORE",
    "source": "STUDY BUILDER",
    "sourceApplicationVersion": "1.0"
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "mystudies-open-impl-track1-dev"
    }
  },
  "timestamp": "2020-12-15T07:15:29.046Z",
  "severity": "INFO",
  "logName": "projects/mystudies-open-impl-track1-dev/logs/application-audit-log",
  "receiveTimestamp": "2020-12-15T07:15:29.185481944Z"
}
```

**Comment by nishit-v** [comment]
studyId is displayed null for below events

1. STUDY_SETTINGS_SAVED_OR_UPDATED
2. STUDY_SETTINGS_MARKED_COMPLETE

Refer screenshots:
![22](https://user-images.githubusercontent.com/60386291/104446229-294e2100-55c0-11eb-8619-961e7db08cea.png)

![Screenshot_2](https://user-images.githubusercontent.com/60386291/104446239-2c491180-55c0-11eb-9c24-00f77a5f86d0.png)


Issue is fixed for remaining events

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
