### ISSUE TITLE
[SB] [Audit Logs] "studyVersion" is displayed null for the events

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2603]
**Events:**

1. STUDY_VIEWED
2. LAST_PUBLISHED_VERSION_OF_STUDY_VIEWED
3. STUDY_ACCESSED_IN_EDIT_MODE
4. STUDY_LAUNCHED
5. STUDY_PAUSED
6. STUDY_RESUMED
7. UPDATES_PUBLISHED_TO_STUDY
8. STUDY_DEACTIVATED
9. STUDY_BASIC_INFO_SECTION_SAVED_OR_UPDATED
10. STUDY_BASIC_INFO_SECTION_MARKED_COMPLETE
11. STUDY_SETTINGS_SAVED_OR_UPDATED
12. STUDY_SETTINGS_MARKED_COMPLETE
13. STUDY_ELIGIBILITY_SECTION_SAVED_OR_UPDATED
14. STUDY_ELIGIBILITY_SECTION_MARKED_COMPLETE
15. STUDY_CONSENT_SECTIONS_SAVED_OR_UPDATED
16. STUDY_CONSENT_SECTIONS_MARKED_COMPLETE
17. STUDY_COMPREHENSION_TEST_SECTION_SAVED_OR_UPDATED
18. STUDY_COMPREHENSION_TEST_SECTION_MARKED_COMPLETE
19. STUDY_REVIEW_AND_E_CONSENT_SAVED_OR_UPDATED
20. STUDY_REVIEW_AND_E_CONSENT_MARKED_COMPLETE
21. STUDY_CONSENT_CONTENT_NEW_VERSION_PUBLISHED
22. STUDY_CONSENT_DOCUMENT_NEW_VERSION_PUBLISHED
23. STUDY_QUESTIONNAIRES_SECTION_MARKED_COMPLETE
24. STUDY_ACTIVE_TASK_SECTION_MARKED_COMPLETE
25. STUDY_INSTRUCTION_STEP_DELETED
26. STUDY_QUESTION_STEP_DELETED
27. STUDY_FORM_STEP_DELETED
28. STUDY_QUESTION_STEP_IN_FORM_DELETED
29. STUDY_ACTIVE_TASK_SAVED_OR_UPDATED
30. STUDY_ACTIVE_TASK_MARKED_COMPLETE
31. STUDY_QUESTIONNAIRE_DELETED
32. STUDY_ACTIVE_TASK_DELETED
33. STUDY_RESOURCE_SECTION_MARKED_COMPLETE
34. STUDY_NEW_RESOURCE_CREATED
35. STUDY_RESOURCE_SAVED_OR_UPDATED
36. STUDY_NOTIFICATIONS_SECTION_MARKED_COMPLETE
37. STUDY_NEW_NOTIFICATION_CREATED
38. STUDY_NOTIFICATION_SAVED_OR_UPDATED
39. STUDY_NOTIFICATION_MARKED_COMPLETE

Sample snippet for STUDY_VIEWED event

```
{
  "insertId": "1sxzbptg1ecd7ci",
  "jsonPayload": {
    "mobilePlatform": null,
    "participantId": null,
    "userAccessLevel": "STUDY BUILDER ADMIN",
    "siteId": null,
    "appVersion": "1.0",
    "description": null,
    "occurred": 1608016529046,
    "resourceServer": null,
    "studyId": null,
    "studyVersion": null,
    "appId": "STUDY BUILDER",
    "destinationApplicationVersion": "1.0",
    "correlationId": "a7cbacad-3214-4b2d-b650-05d8d71891ad",
    "userIp": "59.92.251.162",
    "userId": "133",
    "eventCode": "STUDY_VIEWED",
    "platformVersion": "1.0",
    "destination": "STUDY DATASTORE",
    "source": "STUDY BUILDER",
    "sourceApplicationVersion": "1.0"
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "mystudies-open-impl-track1-dev"
    }
  },
  "timestamp": "2020-12-15T07:15:29.046Z",
  "severity": "INFO",
  "logName": "projects/mystudies-open-impl-track1-dev/logs/application-audit-log",
  "receiveTimestamp": "2020-12-15T07:15:29.185481944Z"
}
```

**Comment by monica-BTC** [comment]
@nishit-v , please test this issue and confirm

**Comment by nishit-v** [comment]
Issues:

1. StudyVersion should be 0.0 for below event

STUDY_QUESTION_STEP_IN_FORM_DELETED

![Screenshot_5](https://user-images.githubusercontent.com/60386291/105362034-65b4f900-5c20-11eb-8e31-da32c4dec9f7.png)

2. StudyVersion should be Last Published version for below events

STUDY_LAUNCHED
STUDY_PAUSED
STUDY_RESUMED
UPDATES_PUBLISHED_TO_STUDY
STUDY_DEACTIVATED

**Comment by monica-BTC** [comment]
@nishit-v , please test and confirm

**Comment by nishit-v** [comment]
Issue is not fixed for Event STUDY_QUESTION_STEP_IN_FORM_DELETED

Actual: Last Published version is displayed

Expected: StudyVersion should be 0.0

![Screenshot_2](https://user-images.githubusercontent.com/60386291/105962441-d5eecf00-60a5-11eb-8a48-055a8b39f603.png)

**Comment by monica-BTC** [comment]
@nishit-v , please test and confirm in dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
