### ISSUE TITLE
[SB] [Audit Logs] "appid" is displayed incorrect value for the events

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2604]
**Events:**

1. STUDY_VIEWED
2. LAST_PUBLISHED_VERSION_OF_STUDY_VIEWED
3. STUDY_ACCESSED_IN_EDIT_MODE
4. STUDY_PUBLISHED_AS_UPCOMING_STUDY
5. STUDY_LAUNCHED
6. STUDY_PAUSED
7. STUDY_RESUMED
8. UPDATES_PUBLISHED_TO_STUDY
9. STUDY_DEACTIVATED
10. NEW_STUDY_CREATION_INITIATED
11. STUDY_SAVED_IN_DRAFT_STATE
12. STUDY_BASIC_INFO_SECTION_SAVED_OR_UPDATED
13. STUDY_BASIC_INFO_SECTION_MARKED_COMPLETE
14. STUDY_SETTINGS_SAVED_OR_UPDATED
15. STUDY_SETTINGS_MARKED_COMPLETE
16. STUDY_ELIGIBILITY_SECTION_SAVED_OR_UPDATED
17. STUDY_ELIGIBILITY_SECTION_MARKED_COMPLETE
18. STUDY_CONSENT_SECTIONS_SAVED_OR_UPDATED
19. STUDY_CONSENT_SECTIONS_MARKED_COMPLETE
20. STUDY_COMPREHENSION_TEST_SECTION_SAVED_OR_UPDATED
21. STUDY_COMPREHENSION_TEST_SECTION_MARKED_COMPLETE
22. STUDY_REVIEW_AND_E_CONSENT_SAVED_OR_UPDATED
23. STUDY_REVIEW_AND_E_CONSENT_MARKED_COMPLETE
24. STUDY_CONSENT_CONTENT_NEW_VERSION_PUBLISHED
25. STUDY_CONSENT_DOCUMENT_NEW_VERSION_PUBLISHED
26. STUDY_QUESTIONNAIRES_SECTION_MARKED_COMPLETE
27. STUDY_ACTIVE_TASK_SECTION_MARKED_COMPLETE
28. STUDY_INSTRUCTION_STEP_DELETED
29. STUDY_QUESTION_STEP_DELETED
30. STUDY_FORM_STEP_DELETED
31. STUDY_QUESTION_STEP_IN_FORM_DELETED
32. STUDY_ACTIVE_TASK_SAVED_OR_UPDATED
33. STUDY_ACTIVE_TASK_MARKED_COMPLETE
34. STUDY_QUESTIONNAIRE_DELETED
35. STUDY_ACTIVE_TASK_DELETED
36. STUDY_RESOURCE_SECTION_MARKED_COMPLETE
37. STUDY_NEW_RESOURCE_CREATED
38. STUDY_RESOURCE_SAVED_OR_UPDATED
39. STUDY_NOTIFICATIONS_SECTION_MARKED_COMPLETE
40. STUDY_NEW_NOTIFICATION_CREATED
41. STUDY_NOTIFICATION_SAVED_OR_UPDATED
42. STUDY_NOTIFICATION_MARKED_COMPLETE

**Actual:** appid is displayed as 'STUDY BUILDER'

**Expected:** appid should be actual App ID entered from SB

Sample snippet for STUDY_VIEWED event

```
{
  "insertId": "1sxzbptg1ecd7ci",
  "jsonPayload": {
    "mobilePlatform": null,
    "participantId": null,
    "userAccessLevel": "STUDY BUILDER ADMIN",
    "siteId": null,
    "appVersion": "1.0",
    "description": null,
    "occurred": 1608016529046,
    "resourceServer": null,
    "studyId": null,
    "studyVersion": null,
    "appId": "STUDY BUILDER",
    "destinationApplicationVersion": "1.0",
    "correlationId": "a7cbacad-3214-4b2d-b650-05d8d71891ad",
    "userIp": "59.92.251.162",
    "userId": "133",
    "eventCode": "STUDY_VIEWED",
    "platformVersion": "1.0",
    "destination": "STUDY DATASTORE",
    "source": "STUDY BUILDER",
    "sourceApplicationVersion": "1.0"
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "mystudies-open-impl-track1-dev"
    }
  },
  "timestamp": "2020-12-15T07:15:29.046Z",
  "severity": "INFO",
  "logName": "projects/mystudies-open-impl-track1-dev/logs/application-audit-log",
  "receiveTimestamp": "2020-12-15T07:15:29.185481944Z"
}
```

**Comment by monica-BTC** [comment]
@nishit-v please test this and confirm

**Comment by nishit-v** [comment]
Issue is resolved in dev
