### ISSUE TITLE
[SB] [Audit Logs] Events are not triggered in Study Builder

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2606]
**Events:**

1. PASSWORD_HELP_EMAIL_FAILED
2. PASSWORD_RESET_EMAIL_FAILED_FOR_LOCKED_ACCOUNT
3. NEW_USER_INVITATION_EMAIL_FAILED
4. PASSWORD_CHANGE_ENFORCEMENT_EMAIL_FAILED
5. STUDY_NEW_QUESTIONNAIRE_CREATED
6. STUDY_QUESTIONNAIRE_SAVED_OR_UPDATED
7. STUDY_QUESTIONNAIRE_MARKED_COMPLETED
8. STUDY_NEW_ACTIVE_TASK_CREATED
9. STUDY_RESOURCE_MARKED_COMPLETED
10. USER_RECORD_VIEWED

Note: When Email service is disabled Email failed events should be triggered (1st,2nd,3rd and 4th)

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev environment and update.

**Comment by nishit-v** [comment]
Below events are not triggered. Rest 7 events are fixed now.

1. STUDY_QUESTIONNAIRE_MARKED_COMPLETED
2. STUDY_NEW_ACTIVE_TASK_CREATED
3. PASSWORD_CHANGE_ENFORCEMENT_EMAIL_FAILED

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev environment and update.

**Comment by nishit-v** [comment]
Verified in latest Dev instance and above 2 events are fixed.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA environment and close if resolved.

**Comment by nishit-v** [comment]
Verified in Dev instance(Post PR), working fine.

Note: Unable to test Audit logs in QA as its not configured in QA instance
