### ISSUE TITLE
SB > Revise user account related flows to use unique link instead of access code

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2607]
The Study Builder currently requires users to enter an access code as part of account setup. This is to be modified to use a unique user-specific link instead (that follows the existing expiry, one-time-use behavior) so that the user need not enter an access code. 

The modification needs to be handled wherever there is a use of access code : Account setup, Account lock, Account reactivation, Account update with email change. Forgot password, Enforce password change.

Users should be redirected to SB error page with appropriate error messages in case of link expiry/invalidity.

**Comment by Lathan-btc** [comment]
@monica-BTC  Issue is fixed in latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
