### ISSUE TITLE
[SB] [Audit Logs] Value for ${questionnaire_id} , ${step_id}, ${activetask_id} and ${form_id} in description is incorrect for the events

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2610]
**Events:**

1. STUDY_INSTRUCTION_STEP_DELETED
2. STUDY_QUESTION_STEP_DELETED
3. STUDY_FORM_STEP_DELETED
4. STUDY_ACTIVE_TASK_SAVED_OR_UPDATED
5. STUDY_ACTIVE_TASK_MARKED_COMPLETE
6. STUDY_QUESTIONNAIRE_DELETED
7. STUDY_ACTIVE_TASK_DELETED

**Actual:** Value for ${questionnaire_id} , ${step_id}, ${activetask_id} and ${form_id} in description is showing Database Value

**Expected:** Value for ${questionnaire_id} , ${step_id}, ${activetask_id} and ${form_id} in description should be Short title key value entered from SB admin in SB web app

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev environment and update.

**Comment by nishit-v** [comment]
Issue is resolved in Dev
