### ISSUE TITLE
[PM] [Audit Logs] Events are not triggered in Participant Manager

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2611]
Events:
1. SITE_ADDED_FOR_STUDY
2. INVITATION_EMAIL_SENT
3. NEW_USER_ADDED
4. NEW_USER_INVITATION_EMAIL_SENT
5. NEW_USER_INVITATION_EMAIL_FAILED
7. PARTICIPANTS_EMAIL_LIST_IMPORTED
8. USER_DELETED
9. RESEND_INVITATION
10. USER_DEACTIVATED
11. USER_REACTIVATED
12. USER_ACCOUNT_ACTIVATION_FAILED_DUE_TO_EXPIRED_INVITATION

**Comment by nishit-v** [comment]
Below Events are not triggered:

NEW_USER_ADDED
ACCOUNT_UPDATE_BY_USER
PARTICIPANTS_EMAIL_LIST_IMPORTED

Remaining events are triggered

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
