### ISSUE TITLE
Mobile app (gateway) > Study List > Modifications to filters

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2613]
Modify filtering options to not include 'upcoming studies' and 'favorites'. Also, remove the bookmarking action on the study list and overview screens.

**Comment by nagarjunav1** [comment]
@naveenr-btc  Issue is fixed for Android, in recent build 1.0(42)

**Comment by nishit-v** [comment]
Above enhancement is verified and working fine in iOS builds - 1.0(148)
