### ISSUE TITLE
[Mobile] Email template > App name should be displayed 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2619]
AR : App id is displayed in the email template
ER : App name should be displayed in the email template for the following
       1. Account lock 
       2. Forgot password

![al1](https://user-images.githubusercontent.com/71445210/103219506-e9423980-4943-11eb-9adc-4edac9ce19f3.png)

**Comment by harisboston** [comment]
@naveenr-btc @tushar-boston Kindly add `appName` in `request_url` for mobile app

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA env, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Isuue is not fixed in the latest dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
