### ISSUE TITLE
[PM] Password help screen > Password help title is getting highlighted

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2622]
AR : Password help title is getting highlighted when user mouse hovered on the title or page back button
ER : Title should not be highlighted

![pwd help2](https://user-images.githubusercontent.com/71445210/103227933-9e312200-4955-11eb-8aae-f814c7296876.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in  QA its fixed. Please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 issue is fixed in latest QA instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
