### ISSUE TITLE
Mobile app > Password creation > Check password criteria after password is first entered

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2625]
Mobile app > Password creation > Sign up, reset password, change password flows  

Check for the user-entered password meeting the criteria at the point the password is first entered rather than after it is confirmed in the 'Confirm password' field.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest android build 1.0(46)

**Comment by nishit-v** [comment]
Not implemented in iOS Dev build.
Build version - 1.0(152)

**Comment by nishit-v** [comment]
Issue is fixed in latest iOS build 1.0(154)
