### ISSUE TITLE
[PM] [Dev] Studies created from SB having maximum Research Sponsor text are not reflected in Sites/Studies tab in PM

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2627]
Steps:
1. Create a study from SB by giving maximum Research Sponsor text in basic information
2. Launch the study
3. Navigate to PM --> Sites tab
4. Observe the list

A/R: Some of the studies created from SB are not reflected in Sites/Studies tab in PM

E/R: All studies created from SB should be reflected

Study details which is not reflected in PM

Study Name: Clinical Trial of the Moventis PNS for Knee Pain
Study ID: KneePain
App ID: BTCDEV001
Instance: Dev

**Comment by aswinijena100** [comment]
@nishit-v issue fixed in QA now. Please check and confirm.

**Comment by nishit-v** [comment]
Issue is resolved in QA Instance.

**Comment by nishit-v** [comment]
Issue is resolved in Dev Instance.
