### ISSUE TITLE
[iOS] Standalone app > Resources > Sub text 'This will also delete your app account.' is shown under resources on accessing for the first time

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2631]
**Steps:**
1. Login to standalone app
2. Enroll into the study
3. Navigate to resources
4. Observe the sub text is displayed even for resources also

**Actual:** Sub text 'This will also delete your app account.' is shown under resources

**Expected:** Sub text 'This will also delete your app account.' should not be shown under resources

Note: This issue is reproducible only for the first time post enrolling into the study

![iOS3](https://user-images.githubusercontent.com/60386291/103291398-9e8ef300-4a11-11eb-875f-61ba3093ed8e.png)

**Comment by tushar-boston** [comment]
Not reproducible except on one build/device, please keep under observation and report if found in new builds with other devices.

**Comment by nishit-v** [comment]
Retested in the new standalone build, Issue is not reproducible. Hence closing the ticket
