### ISSUE TITLE
[SB] Unable to publish any study with scheduled activities

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2633]
Steps:- 
1. Schedule an activity in a study(with scheduled time and date)
2. Complete the section with all the mandatory fields
3. Publish the updates for the study

A/R: -Unable to publish the studies 
E/R:- Admin should able to publish the updates for the study 

Study:- 1. COVID001
             2. RenalStudy

Instance:- Dev
Note:- Issue not observed in QA

![Screenshot_10](https://user-images.githubusercontent.com/60500517/103294961-ef561a00-4a18-11eb-856d-39b5f68fe9b0.png)

**Comment by aswinijena100** [comment]
@nagarjunav1 please check this in dev and let me know if it works fine

**Comment by nagarjunav1** [comment]
Issue is still reproducing in DEV

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test now and update the ticket accordingly

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest DEV build
