### ISSUE TITLE
ingress name is hardcoded

### ISSUE THREAD

**Issue by moschetti** [GoogleCloudPlatform/fda-mystudies#2634]
**Describe the bug**
The name of the ingress-ip rule is hardcoded [here](https://github.com/GoogleCloudPlatform/fda-mystudies/issues/2337).
This should be dynamically named using `{{.prefix}}-{{.env}}-ingress-ip` like the other resources.

**Comment by mohangmk** [comment]
@moschetti ,
As per the discussion in the last call, this issue was handled by Jamie / Andrew. Could you please close this issue if it resolved.
