### ISSUE TITLE
[PM] Security testing > Alerts found in Participant manager application

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2644]
Alerts found in Participant manager application as part of security testing.

Summary of Alerts

Risk Level | No. of alerts
-- | --
High | 0
Medium | 8
Low | 9
Informational | 7

Please find attached report for detailed summary of alerts including probable solution

[PM_SecurityReport.pdf](https://github.com/GoogleCloudPlatform/fda-mystudies/files/5754469/PM_SecurityReport.pdf)

**Comment by nishit-v** [comment]
Performed security testing scan on automated deployment QA environment which has HTTPs configured. Please find the attached report

Risk Level | No. of alerts
-- | --
High | 0
Medium | 7
Low | 17
Informational | 4

@dhanyak-btc @prakashm181 @aswinijena100 
[PM_SecuityReport_V1.1.html.pdf](https://github.com/GoogleCloudPlatform/fda-mystudies/files/5951484/PM_SecuityReport_V1.1.html.pdf)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Performed security testing scan on automated deployment QA environment which has HTTPs configured. Please find the attached report

Risk Level | No. of alerts
-- | --
High | 0
Medium | 8
Low | 13
Informational | 5

[PM_SecuityReport_V1.2.pdf](https://github.com/GoogleCloudPlatform/fda-mystudies/files/6044724/PM_SecuityReport_V1.2.pdf)

**Comment by nishit-v** [comment]
Performed security testing scan on automated deployment QA environment which has HTTPs configured. Please find the attached report. No High alerts found in the scanned report and hence closing this ticket.
[PM_SecuityReport_V1.3.pdf](https://github.com/GoogleCloudPlatform/fda-mystudies/files/6365243/PM_SecuityReport_V1.3.pdf)
