### ISSUE TITLE
[PM] Password should be expire for every 90 days and enforce the user to reset the Password

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2645]
Password should be expired for every 90 days and enforce the user to reset the Password, in case the password is not changed within that period by the user.

**Comment by harisboston** [comment]
Current implementation:

1) By default password will expire in 90 days and app will not allow user to sign-in and will show error message `PASSWORD_EXPIRED `.

PASSWORD_EXPIRED(
      400,
      "EC_0006",
      HttpStatus.BAD_REQUEST.toString(),
      "Your password has expired. Please use the Forgot Password link to get password help."),

2) Expiry time for:
Account lock: 15 minutes.
Reset password: 48 hours.

3) Another scenario: If we change the password by password help today but account was created 1 month back:  Then password expiry will be 3 months from the day we reset password again,, i.e. 3 months not 2 months.

@SR-btc Kindly let let us know if current implementation is proper or need any changes. Thanks.

**Comment by sharathblr** [comment]
Hi @harisboston - The expected behavior is upon the password expires on 90days, it should redirect to reset password change. The user should enter the current password in the reset password page and the message - Your password is expired, please reset your password ' message should be displayed in the reset password change.

**Comment by harisboston** [comment]
Handling the password expiry for every 90 days is already implemented in backend.
Sign-in API is responding with error message PASSWORD_EXPIRED(EC_0006) when password is expired.
@prakashm181 Frontend changes are required, to redirect to reset password change, when API is responding with error code EC_0006.
Kindly check and let me know any modification is required in backend as well.

**Comment by harisboston** [comment]
@sharathblr Please let us how mobile app should behave, when users password is expired.

**Comment by sharathblr** [comment]
> @sharathblr Please let us how mobile app should behave, when users password is expired.

There is no password expiration for mobile user.

**Comment by harisboston** [comment]
@nagarjunav1 Fix id deployed in Dev environment, kindly test and update this ticket.

**Comment by harisboston** [comment]
@nagarjunav1 Confirmed with BA, the requirement as commented above on Jan 16 is already implemented.
So kindly discuss with BA and close this issue.

**Comment by nagarjunav1** [comment]
Currently the User account will be expired for every 90 days and displayed the error message when password is expired.
Closing this ticket, as this behavior already available in last release as per BA confirmation.

![image](https://user-images.githubusercontent.com/60500517/112104548-5aa32880-8bd1-11eb-9720-6b5faa31d69e.png)
