### ISSUE TITLE
 [PM] Password strength meter to be implemented across the application

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2646]
Password strength meter should be implemented for 'New Password' fields for the below pages:

1. Change password page
2. Set up account page (for new user)
3. Set up password page (post forgot password/ account lock flow)

When setting up a password, a password meter should be displayed to the user. The password meter shall indicate weak,fair, good and strong passwords. The password should be allowed only if it meets all the required criteria (as displayed in the application) and is not 'weak'.

The following are some of the aspects that can be considered to determine password strength:
- existence of user name or service name in the password
- existence of consecutive or sequential characters 
- existence of commonly used words
- password length

In addition, password history must be checked for before allowing the password to be saved. The user should not be allowed to use any of the last x used passwords.

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm this issue in Dev

**Comment by nishit-v** [comment]
Password strength meter logic is not as expected.

**Actual:** 
<8 characters- Weak
8 to16 - Fair
17 to 32- Good
>33 - Strong

**Expected:**
< 8 Characters - Weak
8 - Fair
9 to 12 - Good
>12 - Strong

UI issue for password strength meter is being tracked in #3255

Unable to test the functionality for Setup account due to #3253

**Comment by monica-BTC** [comment]
@nishit-v, please test this issue and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev instance now. Verified for below screens:

1. Change password page
2. Set up account page (for new user)
3. Set up password page (post forgot password/ account lock flow)

UI issue is being tracked separately in #3255

**Comment by nishit-v** [comment]
Issue is resolved in QA instance now. Verified for below screens:

1. Change password page
2. Set up account page (for new user)
3. Set up password page (post forgot password/ account lock flow)
