### ISSUE TITLE
[SB] Setup account page > Phone number field is mandatory

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2647]
AR : Setup account page > Phone number field is mandatory
ER : Phone number field should be optional

![setup page1](https://user-images.githubusercontent.com/71445210/103364508-09a8fa00-4ae4-11eb-86c0-53c075f61c6e.png)

**Comment by pujithr** [comment]
Required changes are made and deployed to QA. Please check once and revert me back in case of issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in latest QA instance.

**Comment by pujithr** [comment]
Code is merged and need to test in Dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
