### ISSUE TITLE
[PM] Text fields are less secured for XSS

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2648]
AR : Text fields are allowed the user to insert scripts
ER : Text fields should not allow the user to insert the scripts

![xss](https://user-images.githubusercontent.com/71445210/103365701-aff5ff00-4ae6-11eb-8a58-7b41cc72caf4.png)

**Comment by aswinijena100** [comment]
@firdosebtc1 Added the backend changes and deployed in dev. Please verify and let me know if it works fine

**Comment by firdosebtc1** [comment]
@Lathan-btc please check front end changes via PM web app and to check backend changes via postman in DEV environment

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc @nishit-v please test it in QA and close it if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
