### ISSUE TITLE
[SB] User is unable to sign in with new email id, once the email id has been updated

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2650]
steps:-
1. Login into the application with Admin credentials with Users permission
2. Update the email of that user with new email Id
3. Verify the new email ID using link received
4. Login with the new email ID and verify
 
AR : User is unable to sign in with new email id after new email verification : getting error message
ER : User should be able to login with new email id

![new email](https://user-images.githubusercontent.com/71445210/103367161-66a7ae80-4aea-11eb-966e-5cc47222548f.png)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance
