### ISSUE TITLE
[Study Builder] Allow Participants error message inconsistency

### ISSUE THREAD

**Issue by moschetti** [GoogleCloudPlatform/fda-mystudies#2653]
**Describe the bug**
Error message when "Allow participants to enroll" is "No" is unclear to users if study is not active (and also is different than the error once it's active, but has been set back to no).

This causes user confusion because all sections show as completed with a green checkmark, but an attempt to launch the study will fail with the message `All Study Builder sections must be marked complete to publish the study. Please complete these sections to proceed.` which is inaccurate since sections are marked complete and the failure is due to "Allow" being set to "No."
![Screen Shot 2020-12-30 at 11 02 02 AM](https://user-images.githubusercontent.com/3644762/103376167-bfe2f400-4a90-11eb-8f77-4fa67acdfaf4.png)

**To Reproduce**
1. Create a study in Study Builder
2. Leave "Allow participants to enroll" is "No" and put test values for all other fields throughout study creation.
3. Click Launch Study
4. Actual behavior is an error saying `set "Allow participants to enroll?" to "Yes"` which is unclear. This message implies that it will set the value for me if I click OK, which is not true.
![Screen Shot 2020-12-30 at 11 05 31 AM](https://user-images.githubusercontent.com/3644762/103375634-88277c80-4a8f-11eb-916e-dfa3ae63c1c9.png)

**Expected behavior**
The full text of the error message should be shown as `You must set "Allow participants to enroll?" to "Yes" in the Settings section to launch your study`
Note that this is like the message that shows if you create a study, launch it, then set allow back to no, and attempt to publish updates. As seen here: 
![Screen Shot 2020-12-30 at 11 03 25 AM](https://user-images.githubusercontent.com/3644762/103375747-c755cd80-4a8f-11eb-87e2-64027bfcd46b.png)

**Comment by SR-btc** [comment]
There's another enhancement being pushed out in a day or two that will have the 'Allow enrollment' setting set to Yes by default (and non editable) until the study is launched. Post-launch, it will be made editable in case admins want to stop enrollment at any point during the course of the study. With these updates, it will not be necessary to check for the setting =Yes, for either Launch or Publish Updates actions and so we are removing these validations altogether. That should resolve this issue.

**Comment by SR-btc** [comment]
@moschetti we'll make sure to retest these scenarios once the above-mentioned enhancement is done and then update this ticket as fixed.

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed in QA please check and confirm

**Comment by nagarjunav1** [comment]
Issue is still not resolved in QA instance. Unable to test completely because of the #2713

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed, please test in dev environment

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
