### ISSUE TITLE
[Mobile Apps] Studies list > Progress bar is not updated for study completion % in studies list

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2659]
**Steps:**
1. Login to mobile
2. Enroll into a study
3. Complete some activities
4. Navigate to studies list
5. Observe the progress bar

**Actual**: Progress bar is not updated for study completion % in studies list - iOS
Progress bar is not updated for study completion % in studies list after logout and login - Android

**Expected**: Progress bar is should be updated for study completion % in studies list
![iOS_progress1](https://user-images.githubusercontent.com/60386291/103406417-a8833400-4b80-11eb-9fb9-b81afb62c211.png)

Completion % updating in Dashboard:
![Dashboard](https://user-images.githubusercontent.com/60386291/103406493-e84a1b80-4b80-11eb-8504-abe4c3ff6ae9.png)

**Comment by nishit-v** [comment]
Issue is still observed in latest build 1.0.154

**Comment by nishit-v** [comment]
Issue is observed in iOS and Android(after logout and login)

**Comment by aswinijena100** [comment]
@tushar-boston what is the issue here at backend ? could u please retest now and update the ticket accordingly if this issue still exist .

**Comment by tushar-boston** [comment]
@aswinijena100 Completion was coming null for get study state. Was any fix made?  @nishit-v can retest and update if it's working fine.

**Comment by nishit-v** [comment]
Issue is resolved in Android and iOS now after logout and login also
