### ISSUE TITLE
[Mobile] Html breaking in Resources Text 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2661]
Entered text in resource is breaking in mobile

![resources_](https://user-images.githubusercontent.com/60500517/103407288-28f76400-4b84-11eb-8d71-cb1d58e4ad95.png)

![Resources_text](https://user-images.githubusercontent.com/60500517/103407184-a373b400-4b83-11eb-98e5-a1ba8c4ce488.jpg)

**Comment by harisboston** [comment]
@nagarjunav1 Fix is deployed in Dev environment, kindly test and update this ticket

**Comment by nagarjunav1** [comment]
Html is not breaking now. But below two issues are reproduced in Resources
#2687 #2676

**Comment by nagarjunav1** [comment]
Closing this issue as the main issue is fixed in DEV

**Comment by nagarjunav1** [comment]
Issue is again reproduced in latest DEV build

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
