### ISSUE TITLE
[SB] [QA] Active tasks > Unable to add an active task

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2668]
Steps:

1. Login to SB
2. Navigate to edit study
3. Add an active task
4. Click on Save/Done
5. Observe the functionality

Actual: Unable to add an active task

Expected: User should be able to add active task

Issue not observed in Dev

**Comment by aswinijena100** [comment]
@nishit-v Can u please reverify in dev and closed this issue if it works fine. QA does not have updated code .

**Comment by nishit-v** [comment]
Issue is not reproducible in Dev, hence closing
