### ISSUE TITLE
Study Builder > Study Actions > Replace popup information with on-screen text

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2673]
In the Study Builder's study actions screen, replace the informational/validation popups associated with various actions, with on-screen explanatory text.

**Comment by nagarjunav1** [comment]
Enhancement is implemented in latest QA build

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed, please test in dev environment

**Comment by nagarjunav1** [comment]
Enhancement is implemented in latest DEV build
