### ISSUE TITLE
[SB] Instruction step > Remove character length range for Instruction Text field (Rich Text Editor)

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2675]
**Steps:**

1. Navigating to Questionnaires
2. Add a questionnaire and add Instruction step
3. Observe the character length range

**Actual:** _Instruction Text (1 to 500 characters) *_

**Expected:** _Instruction Text *_

![Screenshot_1](https://user-images.githubusercontent.com/60386291/103508986-1cc31d80-4e88-11eb-86f6-38adb398cd7c.png)

**Comment by ESWAR1994** [comment]
I removed that character length for instruction step

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by nishit-v** [comment]
Issue is not fixed in Dev.

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by nishit-v** [comment]
Issue is not fixed in Dev.
