### ISSUE TITLE
[SB] Issue in Instruction text field

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2676]
Steps:- 
1. Configure an instruction step for the Questionnaire
2.  Add the text in different lines and click on Done button and verify

A/R:- All the entered texts are displaying in a single line after Saving
E/R:- Entered text should be displayed as configured

Instance:- DEV

https://user-images.githubusercontent.com/60386291/103511869-cc4ebe80-4e8d-11eb-9014-fdfa95a40728.mp4

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
