### ISSUE TITLE
[PM] Sites > Load more icon is not displayed for >10 records for non super admin

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2677]
**Steps:**

1. Assign a user having >10 records in sites
2. Login with the user
3. Navigate to sites
4. Observe the list

Actual: Load more icon is not displayed for >10 records for non super admin

Expected:  Load more icon should be displayed at end of 10 records for non super admin also

Instance: Dev

https://user-images.githubusercontent.com/60386291/103512375-952cdd00-4e8e-11eb-9a35-9e48ff0a2077.mp4

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
