### ISSUE TITLE
[SB] UI > Signin page > Placeholder text turns grey on mouse hover of 'Forgot Password?' link

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2678]
Steps:
1. Open SB signin page
2. Mouse hover on 'Forgot Password?' link
3. Observe the colour

Actual: Placeholder text turns grey on mouse hover of 'Forgot Password?' link

Expected: When mouse hovered on the link, more visible colour should be displayed to user

![SB_ForgotPassword](https://user-images.githubusercontent.com/60386291/103514262-4a14c900-4e92-11eb-8a94-af845b128727.gif)

**Comment by fahad-kc** [comment]
Please use this color code for mouse hover
#84deff

**Comment by Madhud5** [comment]
Hi @nishit-v i have fixed please check and close the issue.

**Comment by nishit-v** [comment]
Issue is resolved in QA.

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
