### ISSUE TITLE
[SB] UI > Forgot Password page > Placeholder text turns grey on mouse hover of 'Back to sign in' link

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2679]
Steps:

1. Open SB signin page
2. Click on forgot passowrd
3. Mouse hover on 'Back to sign in' link
4. Observe the colour

Actual: Placeholder text turns grey on mouse hover of 'Back to sign in' link

Expected: When mouse hovered on the link, more visible colour should be displayed to user

![SB_Signin](https://user-images.githubusercontent.com/60386291/103514476-b7285e80-4e92-11eb-99dc-1f5d15b89abb.gif)

**Comment by fahad-kc** [comment]
Please use this color code for mouse hover
#84deff

**Comment by Madhud5** [comment]
Hi @nishit-v i have fixed please check and close the issue.

**Comment by nishit-v** [comment]
Issue is fixed in QA.

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
