### ISSUE TITLE
[SB] Users > Disable 'Re-send activation link' when viewing the users record in view mode

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2681]
Steps:
1. Login to SB having users permission or Superadmin
2. Navigate to users
3. Click on 'View' for any user record which is not yet activated
4. Mouse hover / click on the 'Re-send activation link'
5. Observe

**Actual:** 1. For superadmin navigating to users list
2. For admins with View User permission getting access denied page

**Expected:** Disable 'Re-send activation link'

![SB_disable](https://user-images.githubusercontent.com/60386291/103515135-323e4480-4e94-11eb-9bda-18d2033caf9e.png)

**Comment by aswinijena100** [comment]
@nishit-v please test this issue QA and let me know if it works fine

**Comment by nishit-v** [comment]
Issue is resolved in QA Instance for Superadmin and Admins with view user permission

**Comment by aswinijena100** [comment]
@nishit-v please test this in dev and close the ticket if fixed.
