### ISSUE TITLE
Password criteria display should be consistent

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2683]
Password criteria should be consistent
ER : ' Your password must be at least 8 characters long and contain lower case, upper case, numeric and special characters' should be displayed in the following screens
1. Change Password screen
2. Setup password screen 

![pwd123](https://user-images.githubusercontent.com/71445210/103521929-9adeee80-4e9f-11eb-9d7a-8c56a326c1af.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check issue #2414

**Comment by firdosebtc1** [comment]
@Madhud5 please update the password criteria text

**Comment by Madhud5** [comment]
@sharathblr  provide me updated text.
thank you

**Comment by sharathblr** [comment]
@Madhud5 - Please find the text
Passwords should be minimum 8 to maximum 64 characters.
should have at least one uppercase and one lowercase alphabet
include special characters  !@#$%^&*()‘*+,-:;<>{}~| and a number.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have fixed please check this in QA

**Comment by Lathan-btc** [comment]
@Madhud5 Adjust the alignment of the text


![image](https://user-images.githubusercontent.com/71445210/104874012-dc7b9900-5977-11eb-8115-c8d1bc03cb82.png)

**Comment by Madhud5** [comment]
HI @Lathan-btc i have fixed please check in QA

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest QA instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
