### ISSUE TITLE
[PM] Open study > Enrollment target > Entered data is getting removed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2684]
AR : Open study > Enrollment target > Entered data is getting removed when user enters the 6th digit
ER : It should not allow the user to enter 6th digit and entered data should not be removed

[ Note : It should also be fixed when user enters other characters after numbers ]

https://user-images.githubusercontent.com/60386291/103529284-65400280-4eab-11eb-82e6-015be0401bd1.mp4

**Comment by firdosebtc1** [comment]
@Lathan-btc this is happening because of validation on enrollment target value should not be extending above "99999"

**Comment by Lathan-btc** [comment]
@firdosebtc1 Entered data should not be removed.

**Comment by Lathan-btc** [comment]
@prakashm181 issue is reproducible in the latest Dev instance.

**Comment by Lathan-btc** [comment]
@prakashm181 issue is reproducible in the latest QA instance.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
@firdosebtc1 Enrollment registry should not allow the other characters except number

![ER1](https://user-images.githubusercontent.com/71445210/104460718-750ac580-55d4-11eb-80c2-247da593c0dc.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
