### ISSUE TITLE
Sites tab > Search bar issue > Unable to get search result 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2686]
AR : Sites tab > Search bar issue > 'No records found' is displayed when user search with next set of data ( Search result is getting displayed if user search for the 1st 10 set of data)
ER : User should get proper search result

![search2](https://user-images.githubusercontent.com/71445210/103534136-4eea7480-4eb4-11eb-86a5-265577f1db97.png)

**Comment by prakashm181** [comment]
search result returning empty array if we search anything after first set of 10 records in sites tab.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
