### ISSUE TITLE
[SB] Hyperlinks added in Instruction text field is not Saved

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2687]
Steps:- 
1. Configure the Hyperlinks in he Instruction text field
2. Click on Done button 
3. Edit the Instruction step created and verify

A/R:- Hyperlinks added are saved as normal text 
E/R:- Hyperlinks added should be saved as web links and open as webpages in mobile

https://user-images.githubusercontent.com/60500517/103534642-4c3c4f00-4eb5-11eb-8afa-f26b55915c9e.mp4

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
