### ISSUE TITLE
Study builder should advance from Notifications page to Actions page after pressing "Mark as Complete" on Notifications page

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2696]
Study builder should advance from Notifications page to Actions page after pressing "Mark as Complete" on Notifications page. Current behavior is to stay on Notifications page after pressing the complete button. All other sections advance to the next section when marked complete - this section should have the same behavior.

**Comment by aswinijena100** [comment]
@nishit-v can u pls check this issue fix in our QA and let me know if it works fine

**Comment by Lathan-btc** [comment]
@aswinijena100 issue is fixed in the latest QA instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test this issue in dev and share us the feedback.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
