### ISSUE TITLE
[SB] Questionnaires > Schedule type changes from 'Custom Schedule' to 'Manually Schedule' post deleting any activity 

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2697]
**Steps:**
1. Login to SB
2. Edit any study
3. Add a custom schedule activity for questionnaires
4. Delete any activity
5. Observe the schedule type for Custom scheduled activities activities

**Actual:** Schedule type is 'Manually Schedule' after deleting any activity

**Expected:** Schedule type should be 'Custom Schedule' 

Note:
1. Issue not observed for active tasks
2. Issue not observed after navigating to other pages and coming back to questionnaires

https://user-images.githubusercontent.com/60386291/103609560-21e5a280-4f44-11eb-87fc-ea0b9d2619a8.mp4

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirms in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in QA Instance.

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is resolved in Dev Instance.
