### ISSUE TITLE
[SB] Questionnaires > Mouse hovering on the title for questionnaires showing 'obj.title' text post deleting any activity

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2698]
**Steps:**

1. Login to SB
2. Edit any study
3. Delete any activity
4. Mouse hover on the questionnaires title and observe

**Actual:** Mouse hovering on the title for questionnaires showing _'obj.title'_ text post deleting any activity

**Expected:** Questionnaire title should be displayed

![SB_title](https://user-images.githubusercontent.com/60386291/103609930-ef887500-4f44-11eb-898a-6c51858ef290.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirms in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in QA Instance.

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is resolved in Dev Instance.
