### ISSUE TITLE
[SB] Tick mark for 'Study Activities' study zone section is not displayed after completing sections of Questionnaires and Active tasks

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2699]
**Steps:**
1. Login to SB
2. Edit the study
3. Complete all sections of Questionnaires and active tasks
4. Observe the 'Study Activities' section

**Actual:** Tick mark for 'Study Activities' study zone section is not displayed

**Expected:** Tick mark for 'Study Activities' study zone section should be displayed if all actions of questionnaires and active tasks are completed

![SB](https://user-images.githubusercontent.com/60386291/103610425-290db000-4f46-11eb-8167-135dae1f43ed.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in QA Instance.

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is resolved in Dev Instance.
