### ISSUE TITLE
App participant registry > Enrolled studies pop-up>Records should be displayed in descending order  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2702]
AR : App participant registry > Enrolled studies pop-up > Sites records present under studies are not displayed in descending order
ER : Records should be displayed in descending order

![orders](https://user-images.githubusercontent.com/71445210/103647235-f7fea100-4f80-11eb-8482-4b81fd7250f0.png)

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm

**Comment by Lathan-btc** [comment]
@monica-BTC issue is fixed in latest Dev instance.
