### ISSUE TITLE
SB > Study List > Modify the UI of the toggle switch that hides deactivated studies

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2703]
Modify the UI to show clear visual distinction between ON and OFF behavior of the toggle switch that shows or hides deactivated studies

**Comment by fahad-kc** [comment]
@Madhud5  Please use this color for study list switch. 
ON: #007cba
OFF: #95a3a6

**Comment by Madhud5** [comment]
Hi @sharathblr i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is not fixed in latest QA and Dev instances

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
