### ISSUE TITLE
[PM] Enrollment Registry > Hand cursor icon should be removed for 'Enrollment Target' text when mouse hovered on

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2704]
**Steps:**
1. Login to PM
2. Navigate to Sites/Studies tab
3. Navigate to any enrollment registry
4. Mouse hover on 'Enrollment Target' text
5. Obsevre the icon displayed

**Actual:** Hand cursor icon is displayed for 'Enrollment Target' text as it has no functionality

**Expected:** Hand cursor icon should be removed

**Note:** Issue also observed for admins having 'View' permission for open study

![HandCursor](https://user-images.githubusercontent.com/60386291/103649347-4f524080-4f84-11eb-9d06-d7664499635c.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check in DEV and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
