### ISSUE TITLE
[PM] Sites > Sites added for a study should be displayed in alphabetical order

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2705]
**Steps:**
1. Login to PM
2. Navigate to sites tab
3. Add a site to any closed study
4. Observe the order

**Actual:** Order of sites is displayed in Alphabetical order of location ID of sites

**Expected:** Records should be displayed in alphabetical order of sites name

https://user-images.githubusercontent.com/60386291/103650039-70676100-4f85-11eb-9494-0a091ee7134a.mp4

**Comment by monica-BTC** [comment]
@nishit-v , please test this in QA and confirm

**Comment by nishit-v** [comment]
Issue is resolved in QA.

**Comment by monica-BTC** [comment]
@nishit-v , please check this issue in Dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
