### ISSUE TITLE
[Study builder] Error text should be changed  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2706]
Add Questionnaire/Active task > Schedule tab > Error text should be changed if the user enters the value which is less than or equal to Y of the previous row 

AR :  'X should be less Y of the current and previous rows' error message is displayed 
ER : 'X should be less than Y of the current row and greater than Y of the previous row.' should be displayed

![text message1](https://user-images.githubusercontent.com/71445210/103658555-5fbce800-4f91-11eb-9f88-89837b491672.png)

**Comment by aswinijena100** [comment]
@Lathan-btc please test this issue in QA and let me know if it works fine.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by aswinijena100** [comment]
@Lathan-btc please test this in dev and close this ticket if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
