### ISSUE TITLE
[SB] Study Settings >Unable to save 'Allow enrollment for this study' setting on selecting 'No' option

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2713]
**Steps:**
1. Login to SB
2. Click on edit for any launched study
3. Navigate to study settings
4. Click on "no' for 'Allow enrollment for this study' setting
5. Click on Save
6. Observe

**Actual:** Unable to save 'Allow enrollment for this study' setting on selecting 'No' option

**Expected:** User should be able to save 'Allow enrollment for this study' setting on selecting 'No' option

https://user-images.githubusercontent.com/60386291/103749603-b7a82d00-502b-11eb-8685-81eafcef997e.mp4

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in QA please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue in dev environment and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev
