### ISSUE TITLE
[SB] UI is not proper in Actions screen as per design

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2716]
![Actions](https://user-images.githubusercontent.com/60500517/103757043-3609cc80-5036-11eb-842b-0dc0430badbd.png)

Update the placement of buttons and text as per design document(Invision)

Instance: QA

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by nagarjunav1** [comment]
Issue is not fixed in DEV

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed in dev, please check and confirm

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
