### ISSUE TITLE
[SB] Wrong validation message is displayed in particular scenario

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2717]
Steps:- 
1. Schedule an activities as per UTC time zone and complete the section
2. Complete all the sections of Study
3. Wait for the scheduled time to get expire
4. Click on Publish updates and verify the validation message displayed

A/R:- One or more of the study’s activities or resources has a schedule that needs an anchor date. Please add an anchor date and try again.
E/R:- One or more of the study's activities is scheduled for a date that has already expired. Please correct the same and try again.

Instance: QA

![ExpiredDate](https://user-images.githubusercontent.com/60500517/103759297-846c9a80-5039-11eb-9d90-88fda227ee1d.png)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed, please test in dev environment

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV deployment
