### ISSUE TITLE
[SB] Publish updates to the Study should not happen when scheduled time is expired for notifications

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2718]
Steps:-
1. Schedule a notification in the study
2. complete the section 
3. Complete the all  the sections of the study  by updating any of the study contents
4. Wait for the notification scheduled time to expire
5. Navigate to Actions screen and click on publish updates

A/R:- Updated contents are publishing to end users without any validation message

E/R:- It should display a validation message "One or more of the study's notifications is scheduled for a date in the past. Please correct ".  It should not allow to publish updates until scheduled time is updated.

Instance:- QA

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed, please test in dev environment

**Comment by Kantharajut-btc** [comment]
As discussed with @SR-btc, Added static text in add notification, edit notification and resend notification page and removed the validation when date is expired when publishing updates to study

**Comment by nagarjunav1** [comment]
As per above comments closing this issue as it is working as expected
