### ISSUE TITLE
[PM] Forgot password flow is not working

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2722]
AR : Forgot password flow is not working.
ER : In the password help screen if the user enters the valid email id and clicks on the submit  button then user should get a success message, user should be navigated to sign in screen and user should get a mail with a temporary password.

**Comment by harisboston** [comment]
Tested `reset_password` API in QA environment, getting proper response:

{
    "status": 200,
    "code": "MSG_0044",
    "message": "Password help has been sent to your registered email"
}

From console we can see, app is throwing HTTP error code 415, Unsupported Media type error.
Looks like Content-Type is not proper.

**Comment by Lathan-btc** [comment]
@prakashm181 issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
@harisboston @prakashm181 getting 400 error code on password help screen in both QA and Dev instances

![pwd help3](https://user-images.githubusercontent.com/71445210/104283204-35f64a80-54d6-11eb-8a5e-1a51839aaf2e.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
