### ISSUE TITLE
[Study builder][Dev] User is not able to create a comprehension test 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2723]
Steps
1. Go to the comprehension test  section
2.  Select the 'Yes' radio button and click on save
3. Click on add question and enter valid inputs for all the fields
4. Click on Done button and observe

AR : Created questions are not saved
ER : User should be able to create a comprehension test successfully 

https://user-images.githubusercontent.com/71445210/103773844-b12cac00-5051-11eb-8798-af098e1ca674.mp4

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm
