### ISSUE TITLE
[Mobile Apps] Studies list > Study status is getting changed to 'Yet to Enroll' when user email is enabled/invited in PM after the user withdraws from the study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2735]
Steps::
1. Login to PM
2. Invite a participant to a closed study
3. Login to iOS and user enrolls into study successfully
4. WIthdraw from the same study. Observe study status is 'Withdrawn'
5. From PM click on 'Enable Invitaation' for the user
6. Observe the study status in Studies list

Actual: Study status is showing as 'Yet to Enroll'

Expected: Study status should show as 'Withdrawn' unless user joins the study successfully

Issue not observed in Android

**Comment by tushar-boston** [comment]
The new status is coming from the server. 
See attachment of the user study status after withdrawal and after Enable Invitation. 
<img width="1280" alt="Screen Shot 2021-01-07 at 12 16 57 PM" src="https://user-images.githubusercontent.com/44088109/103860922-8e96a380-50e2-11eb-98f7-ace25cf3a327.png">

**Comment by aswinijena100** [comment]
@tushar-boston if it is issue at backend , how it is working fine in android ?

**Comment by tushar-boston** [comment]
I'm not sure how. But iOS is displaying the latest status coming from server.

**Comment by tushar-boston** [comment]
@aswinijena100 It's happening for Android as well when they log out and log in again. @nishit-v Please confirm the same. The updated status is coming from the server and should be fixed.

**Comment by nishit-v** [comment]
Issue is observed for Android also after logout and login.

**Comment by aswinijena100** [comment]
@nishit-v please check this issue and confirm if it fix now.

**Comment by nishit-v** [comment]
@aswinijena100 Please mention in which instance is this fixed?

**Comment by nishit-v** [comment]
Issue is not fixed in Dev

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev
