### ISSUE TITLE
[SB] Manage Studies screen is broken

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2745]
![Manage_Studies](https://user-images.githubusercontent.com/60500517/103867399-4af56700-50ed-11eb-9469-b242d1593bf1.png)

**Comment by aswinijena100** [comment]
@ESWAR1994 Please tag ur to this ticket if PR is already raised

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
