### ISSUE TITLE
[SB] Add Comprehension test question > User should not be able to delete any option when there are only 2 options

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2752]
AR : Add Comprehension test question > User is able to delete options when there are only 2 options
ER : Add Comprehension Test Question > if the user has only 2 answer options then the user should not be able to delete those options and the delete button should be disabled  

[Note : This should be fixed in both 'Add Comprehension test question' and 'Edit comprehension test question' pages ]

https://user-images.githubusercontent.com/71445210/103891673-468e7580-5110-11eb-8a66-99e78d96c418.mp4

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in DEV instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
