### ISSUE TITLE
[SB] Hyperlinks added in Resource text field is not Saved

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2754]
Steps:-

Configure the Hyperlinks in he Resource text field
Click on Done button
Edit the Resource created and verify
A/R:- Hyperlinks added are saved as normal text
E/R:- Hyperlinks added should be saved as web links and open as webpages in mobile

Refer issue #2687

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
