### ISSUE TITLE
[SB] Issue in Resource text field

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2755]
Steps:-

Configure an Resource
Add the text in different lines and click on Done button and verify
A/R:- All the entered texts are displaying in a single line after Saving
E/R:- Entered text should be displayed as configured

Instance:- DEV

Refer issue #2676

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in dev instance

**Comment by nagarjunav1** [comment]
Content added in resource text editor is not saving. Refer attached video

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
