### ISSUE TITLE
Create troubleshooting documentation page

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2774]
Create a page for troubleshooting the automated deployment and another page for troubleshooting applications. This could also be a FAQ type of document.

**Comment by mohangmk** [comment]
@moschetti 
Do we have to create this document?
As we are adding all the steps as part of readme document and also continuously updating based on the changes

-If we have to create this document then please let us know which are the areas need to be created.

**Comment by moschetti** [comment]
I believe at this point we've added troubleshooting to the deployment document as needed. Let's keep an eye on issues coming in and we can decide to add an additional troubleshooting doc here if needed in the future.
