### ISSUE TITLE
Create a tag for log entries that are created by the Kubernetes health checks

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2775]
Create a tag that is used to label log entries that are created by the Kubernetes health checks. This will be used by administrators when viewing log entries so that they can quickly filter out log entries that are from the health checks. In some services, health check logs are the majority of log entries which makes searching for more useful entries difficult.

**Comment by mohangmk** [comment]
@jkrogers18,
 I am able to query all health Check logs by using below query from the Logs Explorer
resource.type="gce_health_check"

Please let me know if you want me to add custom labels/tags then I may have to configure google-fluentd Agent by using above resource type.

If this serve your requirement , please let me know

**Comment by jkrogers18** [comment]
This seems like a good solution to the requirement. Thanks for looking into this! Will close.
