### ISSUE TITLE
[SB] Questionnaires > Unable to create weekly/monthly anchor based questionnaire by copying existing questionnaires

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2780]
**Steps:**
1. Create a regular questionnaire of any scheduling type
2. Click on save and mark as complete
3. Copy questionnaire
4. Select 'Anchor date-based' scheduling
5. Change frequency to weekly/monthly, Proceed further
6. Observe

**Actual:** Error message 'Please fill in mandatory fields' is displayed 

**Expected:** User should be able to copy questionnaire without any errors

**Refer attached video
Weekly**

https://user-images.githubusercontent.com/60386291/103988448-2a441480-51b4-11eb-8e5e-d48c83f24f44.mp4

**Monthly**

https://user-images.githubusercontent.com/60386291/103988582-66777500-51b4-11eb-8696-ad00dad29f68.mp4

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by madhurya-btc** [comment]
@nishit-v please test and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev

**Comment by nishit-v** [comment]
Issue is still observed when copying Anchor date based questionnaires to anchor based weekly/monthly

Steps:

1. Create a anchor type questionnaire of any scheduling type
2. Click on save and mark as complete
3. Copy questionnaire
4. Select 'Anchor date-based' scheduling
5. Change frequency to weekly/monthly, Proceed further
6. Observe

Actual: Error message 'Please fill in mandatory fields' is displayed

Expected: User should be able to copy questionnaire without any errors

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by madhurya-btc** [comment]
@nishit-v please test and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is resolved in Dev,
