### ISSUE TITLE
[SB] Add questionnaire > Form step > Text choice > Response level attributes > issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2785]
1. Add questionnaire > Form step > Text choice > Response level attributes > Enter values for all the fields except description fields > Click on save > Click on back button > Edit question > Go to Response level attributes >Observe the fields 
AR :  Entered value is getting removed
ER : Entered values should not be removed

2.  Add questionnaire > Form step > Text choice > Response level attributes > Add more than 2 options > Enter values for all the fields > Click on save > Click on back button > Edit question > Go to Response level attributes >Observe the fields 
AR :  2nd choice is getting removed
ER : Any one of the choices should not be removed

3. Add questionnaire > Form step > Text choice > Response level attributes > Delete button should be disabled when when there only 2 choices
AR : Delete button is enabled but no functionality
ER : Delete button should be disabled

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
