### ISSUE TITLE
[SB] E-consent steps > Data sharing > Explanatory text entered is not reflected in mobile screen preview and instead '[object Object]' is displayed

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2787]
**Steps:**
1. Login to SB
2. Edit the study
3. Navigate to 'E-Consent Steps'
4. Enable data sharing
5. Enter all mandatory fields
6. Click on Screen Preview and click on Load more
7. Observe the text

**Actual:** '[object Object]' is displayed

**Expected:** Text entered in Explanatory text should be displayed
![SB_datasharing](https://user-images.githubusercontent.com/60386291/104016154-b87fc100-51db-11eb-8a60-76205da22756.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm the same in dev instance

**Comment by nishit-v** [comment]
HMTL is broken in the preview screen in Dev instance.

![SB](https://user-images.githubusercontent.com/60386291/104418913-afa53b80-559d-11eb-83d4-dfa96495fa7e.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm

**Comment by nishit-v** [comment]
Issue is resolved in dev instance.
