### ISSUE TITLE
[SB] Add questionnaire > Question step > User is not able to delete the first two options when there are more than 2 options

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2793]
1. AR : Add questionnaire > Question step > User is not able to delete the first two options when there are more than 2 options
   ER : User should be able to delete the first two options when there are more than 2 options for the following response types
       1. Value Picker
       2. Image Choice

[ Note : It should be implemented as 'Text choice' response type in both 'Question step' and 'Form step' ]

https://user-images.githubusercontent.com/71445210/104026438-ea991f00-51eb-11eb-9f9c-2fe162d36f4e.mp4

2. Image choice > Informative icon > Alignment issue

![qa11](https://user-images.githubusercontent.com/71445210/104334955-f735b400-5518-11eb-85fc-a571254526dc.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
@madhurya-btc Issue is fixed in the latest QA instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm the same in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
