### ISSUE TITLE
App doesn't recognize Response Datastore failure

### ISSUE THREAD

**Issue by moschetti** [GoogleCloudPlatform/fda-mystudies#2799]
Related to https://github.com/GoogleCloudPlatform/fda-mystudies/issues/2339

Issue is that when Response Datastore does not save the response for the participant, the app still shows the questionnaire or action as completed. So even though the response wasn't saved, this data is lost and user is unable to retry the questionnaire.

**To Reproduce**
1. Submit questionnaire that will cause this error in Response Datastore: `ERROR 1 --- [io-8080-exec-10] .h.f.c.ProcessActivityResponseController : Could not save response for participant.` (Note, currently all my responses in test deployment do this)

**Expected Behavior**
If the response is not saved, the app should not show the activity as completed, and should instead show an error.

FYI @jkrogers18

**Comment by naveenr-btc** [comment]
@moschetti The app will store the failed response in the device and will try sync again later.
during this scenario app will consider that the activity is completed.

**Comment by dhanyak-btc** [comment]
@moschetti Naven responded to this issue, please close this issue.

**Comment by dhanyak-btc** [comment]
@SR-btc Is this issue needs to be fixed or working as per the requirements?

**Comment by SR-btc** [comment]
@naveenr-btc could you confirm that the behavior you described applies for offline behavior only or for any scenario for which response submission fails?

**Comment by naveenr-btc** [comment]
@SR-btc For all the scenario for which response submission fails.

**Comment by naveenr-btc** [comment]
If response are getting failed, the app tries to sync again later. In the meantime the users will see completed status for activity on the mobile app, since they has completed the activity.
