### ISSUE TITLE
Enrollment token case sensitivity

### ISSUE THREAD

**Issue by moschetti** [GoogleCloudPlatform/fda-mystudies#2803]
**Describe the bug**
When enrolling, the hash of the enrollment token seen in `participant_info` table does not match the enrollment token that was emailed, it matches the hash of the ALL CAPS version of the emailed token.

2 issues:
1. The `participant_info` table should have the hash of the token exactly as delivered by email.
2. It lets a user enroll by entering either the ALL CAPS version or the multi-case version of the token, but there should only be 1 valid token to enter.

**To Reproduce**
1. Add a user in Participant Manager
2. Complete enrollment in the mobile app
3. check the hash of the token in `participant_info` table

Issue found while troubleshooting https://github.com/GoogleCloudPlatform/fda-mystudies/issues/2339

@aswinijena100

**Comment by aswinijena100** [comment]
@moschetti I revisited the code in participant enroll datastore, same already been handled . Even if backend received the multi case token while enroll , same is converted to uppercase first then hashed and share the same to both mobile as well as response datastore. Please find the code snippet from Participant Enroll Datastore's EnrollmentTokenServiceImpl.java class of your reference

```
public EnrollmentResponseBean enrollParticipant(
      String shortName, String tokenValue, String userId, AuditLogEventRequest auditRequest) {
    logger.info("EnrollmentTokenServiceImpl enrollParticipant() - Starts ");
    boolean isTokenRequired = enrollmentTokenDao.enrollmentTokenRequired(shortName);
    **String hashedTokenValue = EnrollmentManagementUtil.getHashedValue(tokenValue.toUpperCase());**
    String participantId =
        enrollUtil.getParticipantId("", hashedTokenValue, shortName, auditRequest);
    EnrollmentResponseBean participantBean =
        enrollmentTokenDao.enrollParticipant(
            shortName,
            tokenValue.toUpperCase(),
            commonService.getUserInfoDetails(userId),
            isTokenRequired,
            participantId);
    if (participantBean != null) {
      participantBean.setHashedToken(hashedTokenValue);
      participantBean.setParticipantId(participantId);
    }
    logger.info("EnrollmentTokenServiceImpl enrollParticipant() - Ends ");
    return participantBean;
  }
}
```

**Comment by aswinijena100** [comment]
@moschetti can we close this issue now as it resolved ?

**Comment by aswinijena100** [comment]
@moschetti  @jkrogers18  if this issue resolved, can we close this issue

**Comment by aswinijena100** [comment]
@moschetti this is not an issue. This scenario works as expected in the current code based. Please reopen this ticket is if reproducible at your end.
