### ISSUE TITLE
Site participant registry > Page is not getting refreshed automatically when user decommissioned/activated the site for a study 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2804]
AR : Site participant registry > Page is not getting refreshed automatically when user decommissioned/activated the site for a study 
ER : Page should be refreshed automatically

https://user-images.githubusercontent.com/71445210/104170683-8c588000-5427-11eb-846f-807ba539a8ba.mp4

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by nishit-v** [comment]
Issue is resolved in Dev
