### ISSUE TITLE
[SB] Publish updates is working incorrectly 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2805]
Steps:- 
1. Login into SB
2. Navigate to studies 
3. Click on edit study and update the sections except Basic info and Study settings.
4. Navigate to Actions without complete the above sections
5. Click on publish updates and verify

A/R:- Publish updates is allowed even when all the sections are not checked.

E/R: - Publish updates should not allow if all the sections are not checked

![image](https://user-images.githubusercontent.com/60500517/104177304-903bd080-542e-11eb-8a96-253ec1951034.png)

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 publish updates button is enabled only if all study sections are marked as completed, please test this issue in QA and confirm

**Comment by nagarjunav1** [comment]
Need to Validate notifications section also to be checked for publish updates. For remaining sections issue is fixed in latest QA build

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed in dev, please check and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
