### ISSUE TITLE
Scroll bar moved to default position when the user clicks on load more icon 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2806]
AR : Scroll bar moved to default position when the user clicks on load more icon 
ER : Scroll bar should not be moved to the default  position

[Note : Issue is observed only in firefox browser]

https://user-images.githubusercontent.com/71445210/104184500-8cfa1200-5439-11eb-9577-50f1c82aa2eb.mp4

**Comment by aswinijena100** [comment]
@prakashm181 @firdosebtc1 please check  this issue

**Comment by Lathan-btc** [comment]
Issue is still reproducible in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
