### ISSUE TITLE
[Hydra] PM and Mobile apps > Signin not available error page screen is displayed for account lock flow when Email service is disabled

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2814]
**Steps:**
1. Disable the email service i.e server couldn't send any emails
2. Navigate to signin page of PM/Mobile apps
3. Enter valid email and incorrect password 5 times
4. Observe the behaviour

**Actual:** Signin not available error page screen is displayed for account lock flow when Email service is disabled

**Expected:** "Sorry, an error has occurred and your request could not be processed. Please try again later." (EC_0009) should be displayed

https://user-images.githubusercontent.com/60386291/104307034-ba57c600-54f4-11eb-8938-ca2772e4e928.mp4

**Comment by harisboston** [comment]
@nishit-v Fix for this issue is deployed in QA envinonment, kindly test and update.

**Comment by nishit-v** [comment]
Expected result is wrong.

Actual: Account lock error message is displayed when email service is disabled

Expected:  "Sorry, an error has occurred and your request could not be processed. Please try again later." (EC_0009) should be displayed

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by harisboston** [comment]
@nishit-v Fix is deployed in QA environment, kindly test and update this ticket

**Comment by nishit-v** [comment]
Issue is resolved in Dev
