### ISSUE TITLE
[Hydra] [iOS] Forgot password flow is not working

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2823]
**Steps:**
1. Install iOS mobile
2. Click on Forgot Password
3. Enter valid email and submit
4. Observe the behaviour

**Actual:** Incorrect error message is displayed on entering valid email (Refer screenshot)

**Expected:** In the password help screen if the user enters the valid email id and clicks on the submit button then user should get a success message, user should be navigated to sign in screen and user should get a mail with a temporary password.

Note: Issue not observed in Android

![unnamed](https://user-images.githubusercontent.com/60386291/104334913-ebe28880-5518-11eb-9be8-b32b301b9121.png)

**Comment by harisboston** [comment]
@tushar-boston Please add "appName" in headers for 'password_reset' API call

**Comment by nishit-v** [comment]
Issue is resolved in V1.0.162

**Comment by nagarjunav1** [comment]
@tushar-boston attach the PR raised for the issue and close the ticket once merged into DEV
