### ISSUE TITLE
[Hydra][Audit logs] Event triggered in wrong scenario

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2827]
Event:-
1. PASSWORD_RESET_SUCCEEDED

A/R:- Event was triggered at the time of Password help requested by user.
E/R:- Event should trigger when user completed reset Password flow.

**Comment by harisboston** [comment]
We already have `PASSWORD_CHANGE_SUCCEEDED` once user change his password.
@SR-btc Kindly let us know when `PASSWORD_RESET_SUCCEEDED` even should be logged. 
Currently we are logging this even after password help mail is sent to user.

**Comment by harisboston** [comment]
@nagarjunav1  Fix is deployed in Dev environment, kindly test and update

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV deployment
