### ISSUE TITLE
Add questionnaire > Issue when user saves the entered data

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2828]
1. Add questionnaire > Question step / Form step > Text choice response type > Response level attributes > enter all valid data except any one of the mandatory fields under answer options > Click on Save > Click on back button > Edit questionnaire and observe fields in response level attributes
AR : Answer options fields are getting removed
ER : Entered data should be saved and  fields should not be removed

[ Note : This should also be fixed for 'Value picker' and 'Image choice' response types] 

https://user-images.githubusercontent.com/71445210/104427119-e2a0fc80-55a8-11eb-96fa-f1feae1ded7a.mp4

2. Add questionnaire > Question step / Form step > Value picker / Image choice response type > Response level attributes > enter all valid data except any one of the mandatory fields under answer options > Click on Save > Click on back button > Edit questionnaire > select 'Text choice' in question-level attributes and observe the fields in response level attributes
AR : Answer options fields are not displayed
ER : Answer options fields should be displayed

![text choice1](https://user-images.githubusercontent.com/71445210/104429278-7378d780-55ab-11eb-8971-ce29794b72f8.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
@madhurya-btc 
1. Issue is still reproducible for 'Image choice' response type

2. Text choice > If the user enters the values only for description fields > click on save > click on back button > Edit questionnaire > response level attributes > observe the data
AR : Entered data and one of the answer option are getting removed
ER :  Entered data and any of the answer options should not be removed

3. Text choice > Multiple select > If the user enters the values only for 'Mark as exclusive' fields > click on save > click on back button > Edit questionnaire > response level attributes > observe the data
AR : Entered data is getting removed
ER : Entered data should not be removed

4. Text choice > If the user enters the values only for description fields > Select include 'Other as an option' > observe the answer options
AR : One of the answer options is getting removed
ER :  One of the answer options should not be removed

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
