### ISSUE TITLE
[Audit Logs] Event is not triggered for some changes 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2830]
Event:-
1. STUDY_BASIC_INFO_SECTION_SAVED_OR_UPDATED

A/R:- Event is not triggered when email or thumbnail image updated in basic information screen 
E/R:- Event  should be triggered when any content is updated or saved in basic information screen

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed please check and confirm

**Comment by nagarjunav1** [comment]
Event is not trigged when user update the content in basic information screen and click on mark as complete button
