### ISSUE TITLE
[SB] Create study/Edit study > Consent section is getting mark as completed automatically

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2832]
Steps
1. Click on Create study / Edit study
2. Go to the Consent section
3. Add any one of the consent and click on the 'Mark as completed' button
4. Again go back to the consent section and add/delete/edit consent and observe 

AR : Consent section is getting mark as completed automatically
ER : Consent section should not be marked as completed automatically ( Section should be marked with blue tick only when user clicks on 'Mark as completed' button manually)

https://user-images.githubusercontent.com/71445210/104438472-0880ce00-55b6-11eb-9103-6dae98353636.mp4

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc  Please test and confirm in Dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc Issue is reproducing for the following scenario
1. Consent section > Add more than one consent and click on the 'mark as completed' button
2. Agin go to the consent section and delete any one of the consent 
3. Switch to any other section and observe the consent section

AR : The consent section is getting marked as completed automatically
ER : Consent section should not be marked as completed automatically ( Section should be marked with blue tick only when the user clicks on 'Mark as completed' button manually)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in DEV instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
