### ISSUE TITLE
[Audit Logs][SB] Event is not triggered

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2834]
Event:-
1. NEW_STUDY_CREATION_INITIATED

**Comment by chiranjibi009** [comment]
![image](https://user-images.githubusercontent.com/59357395/105037671-58630780-5a84-11eb-816b-c8e3de9e04da.png)

@nagarjunav1 I have checked that this event is captured.....Please check from your end and update.

**Comment by nagarjunav1** [comment]
Event triggered in wrong scenario
A/R:- 1. Event is triggered when admin edit any study basic info section and click on mark as complete
         2. Event triggered when admin click on create study button 
E/R:- Event should be triggered only when user click on create study button and it should not trigger in any other scenarios

**Comment by chiranjibi009** [comment]
Hi @nagarjunav1, please test this issue in dev environment and update.

**Comment by nagarjunav1** [comment]
@chiranjibi009 Still event is triggered for wrong scenario as mentioned before. It should be fixed 
1. Event is triggered when admin edit any study basic info section and click on mark as complete
Navigate to Studies > Edit study > Basic Information > Click on mark as complete 
Try the above scenario and check once from your end before assigning back.

**Comment by nishit-v** [comment]
Issue is fixed for above mentioned scenario

**Comment by chiranjibi009** [comment]
@nagarjunav1 Please close this issue....if it is fixed.

**Comment by nagarjunav1** [comment]
@chiranjibi009 attach the PR raised  to the issue.
