### ISSUE TITLE
[Mobile] [Dev] Unable to rejoin into Open study once withdrawn

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2839]
Unable to rejoin into Open study once withdrawn for Android and iOS

![iOS](https://user-images.githubusercontent.com/60386291/104462750-f7948480-55d6-11eb-81c4-b289183d0470.png)

**Comment by dhanyak-btc** [comment]
@nishit-v which env QA or DEV?

**Comment by nishit-v** [comment]
Dev Instance.

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue in dev and confirm

**Comment by nishit-v** [comment]
Issue is now resolved in Android and iOS.

**Comment by nishit-v** [comment]
Issue is observed again for below scenario:
1. Fail the eligibility test
2. Pass the eligibility test and enroll into open successfully
3. Withdraw from the study
4. Try to rejoin the study again
5. Observe user is not able to join

**Comment by Kantharajut-btc** [comment]
@nishit-v is this happening only for ios?

**Comment by nishit-v** [comment]
Issue happening for both Android and iOS

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev for Android and iOS

**Comment by Kantharajut-btc** [comment]
@nishit-v please close the issue if resolved
