### ISSUE TITLE
[SB] Questionnaires > Study activities for questionnaires are not displayed when viewed from last published version

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2842]
**Steps:**

1. Login to SB
2. Click on Last published version button
3. Navigate to questionnaires
4. Observe

**Actual:** Study activities for questionnaires are not displayed when viewed from last published version

**Expected:** Study activities for questionnaires should be displayed when viewed from last published version

When viewed from last published version
![Screenshot_3](https://user-images.githubusercontent.com/60386291/104467121-f7e34e80-55db-11eb-8c97-411b7f532dd3.png)

When viewed from View/Edit mode
![Screenshot_4](https://user-images.githubusercontent.com/60386291/104467181-0598d400-55dc-11eb-883b-ec406ac390c8.png)

**Comment by aswinijena100** [comment]
@nishit-v Please test this dev and let know

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
