### ISSUE TITLE
[SB] Questionnaires > Daily > Unable to enter date or time fields manually

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2844]
**Steps:**

1. Login to SB
2. Navigate to questionnaires
3. Select daily
4. Try to enter date or time manually
5. Observe the behaviour

**Actual:** Unable to enter date or time fields manually

**Expected:**  User should be able to enter date or time fields manually or clear(backspace)

**Note:** Issue not observed for Active task
issue not observed for other date/time fields in other frequencies

**Comment by navya-BTC** [comment]
@nishit-v  ,please test this issue in QA.

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by navya-BTC** [comment]
@nishit-v , please test this issue in dev
