### ISSUE TITLE
Text size of the loader page should be increased

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2852]
AR : The text size of the loader page is reduced
ER : The text size of the loader page should be increased (The size of the text should be same as other loader pages text)

![loader11](https://user-images.githubusercontent.com/71445210/104694093-b0baa200-5730-11eb-9853-37d0e7a467e4.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and update the ticket.

**Comment by Lathan-btc** [comment]
@harisboston Gap between loader icon and text should be reduced

![load1](https://user-images.githubusercontent.com/71445210/104717753-c8555300-574f-11eb-85cd-d4617b6e6038.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in Dev environment, kindly test and update

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
