### ISSUE TITLE
[SB] End date displaying null for one of the weekly activities in Study Builder and causing mobile apps to crash

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2853]
Steps:-
1. Enroll into closed study 
2. Navigate into the study activities screen and verify

StudyID:-  RenalStudy
Studyname:- Treatment of Renal Stones

App is getting crashed for above mentioned study

**Comment by nishit-v** [comment]
Issue is happening due to End date displaying null for one of the weekly activities in Study Builder

Study ID: RenalStudy
Activity ID: w
Activity Name: weekly

![unnamed](https://user-images.githubusercontent.com/60386291/104710757-73f9a580-5746-11eb-88ed-66a18cb40aa0.png)

**Comment by madhurya-btc** [comment]
![image](https://user-images.githubusercontent.com/65340564/104727221-f724f680-575a-11eb-9226-dcd3e7f8c79e.png)
@nagarjunav1 @nishit-v Not able to reproduce End date as NA for weekly Questionnaire. Please reproduce this issue or else please delete this weekly questionnaire.

**Comment by nagarjunav1** [comment]
**Steps to reproduce the issue** 
1. Navigate to questionnaires
2. Click on Add Questionnaire
3. Enter the required data in the content tab and click on save 
4. Add the instruction step/ question Step for the questionnaire 
5. navigate to schedule tab and select regular schedule type
6. Select Weekly frequency type
7. Then change the schedule type to anchor date and reselect to the regular type and click on Done button
8. Publish the updates once all sections are completed
9. Verify mobile app is crashed when navigate to activities screen

Note:- Issue also happens for Daily, Weekly and Monthly frequencies for Questionnaires

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in QA instance

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in Dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
