### ISSUE TITLE
[SB] Active task  > Add to line chart is automatically getting enabled

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2865]
**Steps:**
1. Edit a study
2. Navigate to Active task
3. Add an active task
4. Enter all mandatory fields
5. Set frequency to daily/weekly/monthly/custom
6. Click on done
7. Observe the behavior

**Actual:** Add to line chart is automatically getting enabled

**Expected:** Add to line chart should not be automatically getting enabled

https://user-images.githubusercontent.com/60386291/104797626-aad2c880-57e5-11eb-8d39-b60f06ecace5.mp4

**Comment by pujithr** [comment]
To Test in QA

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest instance.

**Comment by aswinijena100** [comment]
@Lathan-btc PR raised and merged in dev . Please test and close this issue if fix

**Comment by nishit-v** [comment]
The issue is fixed in the latest Dev instance.
