### ISSUE TITLE
[SB] Numeric response type > Default values of Minimum and Maximum values should be put into text fields

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2866]
**Steps:**
1. Edit study
2. Add a questionnaire
3. Add numeric response type for question step/form step
4. Navigate to Response level attributes
5. Observe the minimuma and maximum text fields

**Actual:** Currently default values are not mentioned in the UI part in these text fields

**Expected:** Minimum value  **0** and Maximum value  **10000** should be put into these fields as default

Note: above text fields can be editable if user wants to change other than default values

It should be handled for both Question step and Form step
![SB_numeric](https://user-images.githubusercontent.com/60386291/104797784-b1157480-57e6-11eb-9958-81e8f064f54a.png)

**Comment by pujithr** [comment]
@nishit-v Please test this in dev and let know if it works fine

**Comment by nishit-v** [comment]
Issue is resolved in Dev instance.
