### ISSUE TITLE
[Audit Logs] Event triggered in wrong scenario

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2867]
**Event:**

REGISTRATION_SUCCEEDED

**Actual:** Event is triggered even when mobile app user has not successfully verified the email code

**Expetced:** Event should be triggered only when mobile app user has successfully verified the email code

**Comment by navya-BTC** [comment]
@nishit-v please test this issue

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
