### ISSUE TITLE
[iOS] My Account > Receiving push notifications even when 'Receive Push Notifications?' is disabled

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2868]
**Steps:**
1. Login into mobile
2. Navigate to my account
3. Disable 'Receive Push Notifications?'
4. Send push notification from SB
5. Observe

**Actual:** Receiving push notifications even when 'Receive Push Notifications?' is disabled

**Expected:** Push notifications should not be displayed when 'Receive Push Notifications?' is disabled

**Comment by tushar-boston** [comment]
Push notifications are controlled by the server-side. I've verified the disabled settings getting updated properly to the server.

**Comment by aswinijena100** [comment]
> Push notifications are controlled by the server-side. I've verified the disabled settings getting updated properly to the server.

@tushar-boston which api update the disabled settings in back end ? Is it updateUserProfile endpoint ? Also please share the user details for which u disabled the settings

**Comment by tushar-boston** [comment]
Yes, it's `updateUserProfile`. You can check for any user on iOS. This isn't a user-specific issue.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev environment and update.

**Comment by nishit-v** [comment]
Issue is resolved in latest dev instance.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA environment and update.

**Comment by nishit-v** [comment]
Unable to test due to #3508.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance and verified in iOS build V1.0.206
