### ISSUE TITLE
Study Builder>Account Set up>check box tick not appearing and confusing the user

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#2869]
Invite new user
Click on the activation link 
fill details in the account set up a page and try clicking on the check box to accept terms and condition

AB: On selecting the check box the tick is not appearing and is confusing the user
EB: The tick should appear on selecting in the check box, 

The result of not seeing the tick is confusing to the user  and will not be able to register in the application

![image](https://user-images.githubusercontent.com/63578379/104799153-c7c1c880-57f2-11eb-9c32-ad5b17d4bcde.png)

**Comment by monica-BTC** [comment]
@sharathblr, not able to reproduce this issue. Please retest and confirm.

**Comment by sharathblr** [comment]
Unable to reproduce this issue and hence closing the ticket.
