### ISSUE TITLE
[iOS] Issues related to push notification

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2870]
**Issue 1:** **Receiving app level notification even when user is not logged in**

**Steps:**
1. Install the app
2. Send app level notification from SB
3. Observe

**Actual:** Receiving app level notification even when user is not logged in

**Expected:** App level notification should be received only for logged in users

**Issue 2:** **Receiving Study level notification even when user is not logged in/ enrolled**

**Steps:**
1. Install the app
2. Send study level notification from SB
3. Observe

**Actual:** Receiving Study level notification even when user is not logged in/ enrolled

**Expected:** Study level notification should be received only for logged in and who are successfully enrolled users

**Comment by aswinijena100** [comment]
@tushar-boston please let me know which flag u are updating in updateprofile api to for this scenario

**Comment by tushar-boston** [comment]
We don't call `updateUserProfile` service when users log out. It's a straight forward scenario where users getting the push notifications from the study builder after they logged out.

_Note: iOS Apps can't control notifications when App is not running._

**Comment by aswinijena100** [comment]
@tushar-boston Please invoke /updateUserProfile endpoint to nullify device token during the logout flow to resolve this issue. Please let me know once done , so that I can check from my end as well.

**Comment by nishit-v** [comment]
Issue is resolved in latest iOS build 1.0(169)
