### ISSUE TITLE
[iOS] Resource title is duplicated in email body when shared

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2871]
**Steps:**
1. Enroll into study
2. Navigate to resources
3. Click on any resource and share
4. Choose Gmail App
5. Observe

**Actual:** Resource title is duplicated in email body when shared

**Expected:** Resource title should not be  duplicated in email body when shared

![unnamed](https://user-images.githubusercontent.com/60386291/104799314-1de33b80-57f4-11eb-8fb9-1adc1d1119e5.png)

**Comment by tushar-boston** [comment]
This is working fine in the default email application.
