### ISSUE TITLE
[SB] Study level resend notification is not triggered

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2872]
Steps:- 
1. Create a new study level notification
2. Try to resend the notification

A/R:- Resent time is not updating for the notification and notification is not sent
E/R:- Resent time should be updated and notification should be triggered.

![image](https://user-images.githubusercontent.com/60500517/104799312-1ae84b00-57f4-11eb-8453-396f9930db6e.png)

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test and confirm in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
