### ISSUE TITLE
[SB] Need to adjust the UI in the Study notification screen 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2873]
Steps:- 
1. Navigate to Study notifications screen 
2. click on create notification button 
3. Select the Schedule notification option
4. Click on done button without filling mandatory fields and verify

A/R:- Validation messages are overlapping with the below hardcoded text
E/R:- Need to adjust the UI to avoid overlapping 

![StudyNotification_UI](https://user-images.githubusercontent.com/60500517/104799462-50416880-57f5-11eb-8501-3b746e8ed94b.png)

**Comment by pujithr** [comment]
To test in QA Env

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
