### ISSUE TITLE
[Mobile apps] Signin > Accessing terms and privacy policy links showing blank

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2877]
**Steps:**
1. Install mobile apps
2. Navigate to signin page
3. Click on Terms/Privacy policy
4. Blank page is shown

**Actual:** Accessing terms and privacy policy links showing blank

**Expected:** Should navigate to default pages (similar to PM)

**Comment by naveenr-btc** [comment]
@nishit-v similar to #2879 if the url is not configured in mobile app the pages will be empty for these pages. also we can't prevent the click action because it on login page of auth server where they'll not have this info.

**Comment by nishit-v** [comment]
Closing this issue as per the feedback provided
