### ISSUE TITLE
[Android][iOS] Terms and privacy policy hyperlinks are not clickable in Signup screen 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2879]
A/R:- Hyperlinks are not clickable

E/R:- Hyperlinks should be clickable and should navigate to respective pages

**Comment by naveenr-btc** [comment]
@nagarjunav1 unless Terms and privacy policy urls are configured in mobile apps these button will be non-functional. we were asked to remove the click action because if urls are not configured it'll display a empty page.

**Comment by nagarjunav1** [comment]
Closing this issue as per feed back provided
