### ISSUE TITLE
[Mobile Apps] Signup > Email code expiry time for resent verification is set to 48 mins instead of 48 hours

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2880]
**Steps:**
1. Navigate to singup in mobile apps
2. Enter email and password fields Eg. on 16th Jan 1PM
3. Navigated to verification step.
4. Expiry time for the email code will be on 18th Jan 1PM
5. Click on resend verification code
6. Observe that expiry time for resent verification is 48 mins i.e 16th Jan 1:48 PM

**Actual:** Email code expiry time for resent verification is incorrect and set to 48 minutes from the time when user clicks on resend verification code

**Expected:** Email code expiry time for resent verification should be always 48 hours

Issue not observed for PM

Before resend i.e after signup - 
![Before_resend](https://user-images.githubusercontent.com/60386291/104807577-044aef80-5806-11eb-9f0c-167ec055dece.png)

After resend i.e after clicking on resend verification - 
![After_resend](https://user-images.githubusercontent.com/60386291/104807578-07de7680-5806-11eb-83c4-2f48843c89fe.png)

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in QA.

**Comment by nishit-v** [comment]
Issue is resolved in Dev
