### ISSUE TITLE
[SB] Scheduled notifications are shown in the notifications list for mobile app users immediately

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2881]
**Steps:**

1. Schedule an app level/study level notification
2. Set future date and time
3. Update and save
4. Observe the notification list in mobile

**Actual:** Scheduled notifications are shown in the notifications list for mobile app users immediately

**Expected**: Scheduled notifications should only be shown on the specified date and time

![N1](https://user-images.githubusercontent.com/60386291/104807344-55f27a80-5804-11eb-9c7f-69d56164fa8e.png)

**Comment by aswinijena100** [comment]
@nishit-v Please test this in QA and let me know if works fine

**Comment by aswinijena100** [comment]
@nishit-v Please test this in dev and close the issue if fixed

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
