### ISSUE TITLE
[Hydra] Account lock functionality is failed in  Some scenario

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2882]
Steps:- 
1. Open the application
2. Navigate to sign in screen
3. Enter valid email and Invalid password for 5 times
4. Verify account is locked
5. Sign in using email and temporary password
6. Once navigated to reset password screen, enter the temp password received and enter old password used in the past in new password and confirm password fields and click on submit and verify

A/R:- Displaying error message and navigated to sign in screen
E/R:-  App should validate for password entered and user should be able to successfully reset password

https://user-images.githubusercontent.com/60500517/104809361-c2747600-5812-11eb-9d2c-6d0a6103d392.mp4

Note:- Refer attached video for more information

**Comment by harisboston** [comment]
Followed above steps, in the reset password screen, since we are using old password.
As per the requirement, if user tries to use last 10 password, app should show below error message

```
{
    "status": 400,
    "error_type": "Bad Request",
    "error_code": "EC_0011",
    "error_description": "Your new password should not match any of your previous 10 passwords",
    "timestamp": 1611315658105
}
```

Tested the scenario, `/users/{userId}/change_password` API is responding proper error message.
@naveenr-btc Kindly check this issue, if there is any mismatch in the `error_code` which is causing this issue.

**Comment by naveenr-btc** [comment]
@harisboston whenever user logs in with temp password, the deeplink url should have email in it. currently i'm not getting it. Please check.

**Comment by harisboston** [comment]
@nagarjunav1 Fix is deployed in QA environment. Kindly test and update this ticket.

**Comment by harisboston** [comment]
@nagarjunav1 Fix is deployed in Dev environment. Kindly test and update this ticket.

**Comment by nagarjunav1** [comment]
Issue is resolved in latest DEV build
