### ISSUE TITLE
[SB] Issues in Notifications 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2883]
The user is not receiving notifications for the following scenarios
1. Notifications > Copy notification > Send invitation with the scheduled date and time
2. Notifications >Create notifications > create a notification with the scheduled date and time
3. Notifications > Resend invitation > send study with the scheduled date and time ( Sometimes working )
4. Notifications > Notifications are not sent with scheduled time ( Sometimes working )  

![notification issue1](https://user-images.githubusercontent.com/71445210/104809253-edaa9580-5811-11eb-8447-c6fb550fe5b8.png)

**Comment by aswinijena100** [comment]
@Lathan-btc I tested these scenarios with scheduling the notifications found to be working fine. Initially it will be with Not Sent status, once successfully processed ,status will get change to sent . Please reverify and close the issue if it works fine.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc if this issue fixed, please close this. It does not require any PR to be raised.
