### ISSUE TITLE
My account screen > Assigned permissions section > Displaying view only permission even though user is doesn't have any permission for users and notifications

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2884]
AR : My account screen > Assigned permissions section > Displaying view only permission even though user is doesn't have any permission for users and notifications
ER : If the user doesn't have any permission, then permission text should not be displayed

![permission11](https://user-images.githubusercontent.com/71445210/104809492-ad4c1700-5813-11eb-8eb8-78f5fc67b788.png)

**Comment by aswinijena100** [comment]
@Lathan-btc please test this in dev and let know if it works fine

**Comment by nagarjunav1** [comment]
Issue is fixed now in DEV. But need to fix changes as expected in #2928

**Comment by aswinijena100** [comment]
> Issue is fixed now in DEV. But need to fix changes as expected in #2928

U have separate ticket for other scenarios. So please close this ticket if it fixed

**Comment by nagarjunav1** [comment]
Closing issue as main raised is fixed in latest Dev build
