### ISSUE TITLE
[SB] Studies > Last published version > 'Notifications' and 'Actions' fields are disabled

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2885]
AR : Studies > Last published version > 'Notifications' and 'Actions' fields are disabled
ER : Studies > Last published version > 'Notifications' and 'Actions' fields should be enabled

![last publishe version](https://user-images.githubusercontent.com/71445210/104809846-50059500-5816-11eb-992e-b5e0a731bee2.png)

**Comment by SR-btc** [comment]
It would be better to not display these sections altogether in this view. Notifications is a log/history of all notifications sent out to participants in the study and so the content is not specific to a previous version of the study. Actions is a section that cannot be used in this mode, so fine to hide that as well.

**Comment by ESWAR1994** [comment]
need to test in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in QA Instance

**Comment by ESWAR1994** [comment]
Latest changes are merged into develop branch need to test in dev

**Comment by Lathan-btc** [comment]
The issue is resolved in the latest Dev instance.
