### ISSUE TITLE
[SB] Comprehension test > 'Mark as completed' tick mark issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2886]
Comprehension test > for 'Comprehension test' and 'Informed consent' 'Mark as completed' tick mark should be removed when user add or edit compression test question
Steps
1. Go to a comprehension test
2.  Add/Edit comprehension test question and observe 'Mark as completed' tick mark is not removing for the 'Comprehension test' 
    and 'Informed consent' 

https://user-images.githubusercontent.com/71445210/104810688-5d258280-581c-11eb-8821-ad33b7bb5d2d.mp4

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
