### ISSUE TITLE
[SB] Studies tab > 'Edit' and 'last published version' icons should be highlighted in blue color when user mouse hovered on it

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2887]
AR : Studies tab > 'Edit' and 'last published version' icons are not highlighted in blue color when user mouse hovered on it
ER : Studies tab > 'Edit' and 'last published version' icons should be highlighted in blue color when user mouse hovered on it

[Note : It should be fixed in all the places, where ever edit icon comes] 

![edit1](https://user-images.githubusercontent.com/71445210/104810777-0c625980-581d-11eb-826f-3eca1d80327c.png)

**Comment by Madhud5** [comment]
Hi @fahad-kc @fahadbtc-zz  Please provide Imges for above icons.
Please check below link
http://35.222.67.4:8089/studybuilder/css/sprites-icons-2.png

**Comment by fahad-kc** [comment]
Provided

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check it.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is reproducible in the following pages
1.Eligibility test 
2. Consent section
3. Comprehension test and etc...

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it please check-in QA env and confirms here.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV- QA its fixed. Please check and close the issue.

**Comment by nishit-v** [comment]
Issue is resolved in QA instance.
