### ISSUE TITLE
Notifications > Dropdown should be disabled and selected app should be displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2888]
AR : Notifications > Click on view notification >  try to click on dropdown > Dropdown is enabled and the selected app is not displaying
ER : Notifications > Dropdown should be disabled and the selected app should be displayed

![notification view mode](https://user-images.githubusercontent.com/71445210/104810960-27819900-581e-11eb-9e6d-18fe195495da.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA.

**Comment by nishit-v** [comment]
Issue is resolved in QA.

**Comment by navya-BTC** [comment]
@nishit-v please test in dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
