### ISSUE TITLE
Reorganize activity list to put "completed" and "incomplete" activities in "past" section

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#289]
Currently the activity list keeps all completed and incomplete activities in the "current" section of the activities list. This clutters the "current" section which I would expect just to be activities that need my attention. We should move anything with a "completed" or "incomplete" status to "past."

Screenshot attached.
![IMG-4727](https://user-images.githubusercontent.com/35972680/80729866-d5091c80-8ad6-11ea-813f-60632dc4d5f6.PNG)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest build for  Android

**Comment by dhanyak-btc** [comment]
@nagarjunav1 please close this issue if it's fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest builds
