### ISSUE TITLE
[SB] Questionnaires > View instruction step >'Instruction Text' text area is editable 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2891]
Steps
1.Click on view study/Edit study/view questionnaire/Edit questionnaire
2. Go to questionnaires 
3. Click on the view instruction step question and try to edit the 'Instruction Text' text area field 

AR : 'Instruction Text' text area is editable
ER : 'Instruction Text' text area field should be disabled and non-editable icon should be displayed

![instructionstep](https://user-images.githubusercontent.com/71445210/104811592-ad074800-5822-11eb-9b36-64f69062b630.png)

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
