### ISSUE TITLE
[SB] Users > Assign permissions section should be disabled in view only mode

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2893]
AR : Users > Some of the fields in assign permission sections are editable in view-only mode 
ER : Users > Assign permissions section should be disabled > noneditable icon should be displayed

[ Note : It should also be handled for the admin who is having view-only permission for the Users]

![permission7](https://user-images.githubusercontent.com/71445210/104811822-3c612b00-5824-11eb-92e1-c231a845d6fa.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
