### ISSUE TITLE
[SB] Active task > OneTime > Start date and time showing empty in GetStudyActivityList API

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2894]
Steps:
1. Create an active task 
2. Set daily as frequency
3. Choose custom start date and time as start date
4. Choose study life time
5. Publish updates
6. Observe GetStudyActivityList API

Actual: Start date and time showing empty in GetStudyActivityList API

Expected: Start date and time should display properly which is entered from SB

SB screenshot:
![SB_1](https://user-images.githubusercontent.com/60386291/104812056-97475200-5825-11eb-8b45-12ec45cd4188.png)

GetStudyActivityList API for above activity

![Screenshot_2](https://user-images.githubusercontent.com/60386291/104812074-c6f65a00-5825-11eb-8086-2b886ac52bd3.png)

**Comment by nishit-v** [comment]
Instance: Dev
Study: Global Mental Health of Urban Mothers
Study ID: MUM
Activity ID: at_reg_onetime

**Comment by aswinijena100** [comment]
@nishit-v Fix deployed in QA please test and let me know

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by aswinijena100** [comment]
@nishit-v This issue fix is available in dev as well . Please test and close the same if it fixed

**Comment by nishit-v** [comment]
Issue is resolved now in Dev .
