### ISSUE TITLE
[SB] Active task > Error message is not removed for active task display name

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2895]
Steps:
1. Add an active task
2. Enter display name with invalid/unsupported special characters
3. Clear the unsupported words and enter valid name
4. Observe

Actual: Error message is not removed for active task display name

Expected: Error message should be removed for active task display name once user enters valid name

https://user-images.githubusercontent.com/60386291/104812229-df1aa900-5826-11eb-91a2-4580fc162c65.mp4

**Comment by ESWAR1994** [comment]
need to test in QA instance

**Comment by nishit-v** [comment]
Issue is still observed in QA

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest DEV deployment.
