### ISSUE TITLE
Add questionnaire > Daily frequency > User is able to create a study without entering the time of the occurrence

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2896]
Steps
1. Go to add questionnaire
2. Enter the values in content fields
3. Go to schedule tab > Enter all the values except 'Time(s) of the day for daily occurrence' field > click on Save
4. Go to contents tab > add any questionnaire 
5. Click on the schedule tab and observe

AR : 'Time(s) of the day for daily occurrence' field is disabled and the user is able to click on the done button 
ER :  'Time(s) of the day for daily occurrence' field should be enabled

**Comment by ESWAR1994** [comment]
need to test in QA instance

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
