### ISSUE TITLE
[PM] Sites tab > Contents are not displaying in the sites tab : getting error message 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2901]
Sites tab > Contents are not displaying in the sites tab : getting an error message 

![sites tab1](https://user-images.githubusercontent.com/71445210/104813803-7be24400-5831-11eb-8e53-a7ea7551f491.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
