### ISSUE TITLE
Studies tab > Study name column > Studies name should be adjusted as per the new column width

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2902]
AR : Studies tab > Study name column > Studies name are displayed with dots at the end even though there is more space
ER : Studies tab > Study name column > Studies name should be adjusted as per the new column width

![studies11](https://user-images.githubusercontent.com/71445210/104814412-b8636f00-5834-11eb-8a4d-3b9ba722d912.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check in QA env

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by Madhud5** [comment]
Hi @ESWAR1994 , Please raise PR and merge to Develop.
thank you

**Comment by ESWAR1994** [comment]
merged into develop branch need to  test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
