### ISSUE TITLE
[SB] Studies tab is not highlighted

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2903]
Actual : Studies tab is not highlighted
Expected : Studies tab should be highlighted when user is present in the following screens
1. Create Study
2. Edit study
3. View study
4. Viewed study from last published version
![Screenshot_3](https://user-images.githubusercontent.com/60386291/104814610-f319d700-5835-11eb-892f-91b693a8c61d.png)

**Comment by navya-BTC** [comment]
@nishit-v please test in QA.

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by nagarjunav1** [comment]
Issue is resolved in latest DEV build
