### ISSUE TITLE
[SB] Add questionnaires > Schedule schedule > Custom date frequency > Text changes is required

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2904]
AR : Add questionnaires > Schedule schedule > Custom date frequency >'Default Lifetime of each run' is displayed
ER : The text should be changed to 'Lifetime of each run'

[Note : It should be fixed for Questionnaires, Active tasks, Regular schedule type and Anchor date based schedule type]

![default1](https://user-images.githubusercontent.com/71445210/104814745-94a12880-5836-11eb-8d16-c4095d816b4f.png)

**Comment by pujithr** [comment]
to test in DEV ins

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
