### ISSUE TITLE
[SB} > Correct display of sent notifications

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2907]
**Describe the bug**
The text that displays the notification log in the Resend/View Notification screen (for sent notifications) needs correction

**To Reproduce**
1. Go to Study Builder > Notifications (outside of studies or within a study)
2. Click on Resend Notification
3. Scroll down to the date and time fields and view the list of dates and times the notification was already sent out on
4. See text displayed as 
Last sent on .............
Last sent on...............

**Expected behavior**
Text should be displayed as
Previously sent on: // static plain text label
......date and time 1...........
......date and time 2..............

**Screenshots**
![notifications resend issue](https://user-images.githubusercontent.com/63093896/104843624-97ad1f00-58f1-11eb-8834-52391ba86cda.JPG)

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA.

**Comment by nishit-v** [comment]
Issue is resolved in QA

![Screenshot_3](https://user-images.githubusercontent.com/60386291/105195341-90d81380-5b60-11eb-89a7-e6479db0af09.png)

**Comment by navya-BTC** [comment]
@nishit-v please test this in dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
