### ISSUE TITLE
PM>No record displayed when loading

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#2909]
**Describe the bug**
when the user navigates to a different tab, No record is displayed in the backend and then the result is displayed 
**To Reproduce**
1. Go to 'PM having only a site 
2. Click on Study or apps
3. No Record is displayed in the backend or when loading and then the result is displayed.

**Expected behavior**
On click on any tab, No record should not be displayed in the backend and instead display the actual result

**Screenshots**
![image](https://user-images.githubusercontent.com/63578379/104847533-9cc89900-5906-11eb-941c-198449432b24.png)

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev
