### ISSUE TITLE
PM> Search bar text correction 

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#2910]
**Describe the bug**
search tab text to should be 'Search by study ID or name'  instead of - Search BY Study ID or Name

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
