### ISSUE TITLE
PM>add user>Select study>Sites not displayed when selected 

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#2911]
**Describe the bug**
The number of sites when Study is selected is to be displayed even in add new user 

**To Reproduce**
1. Go to PM
2. Click on User>add new user
3. select study 
4. The number of sites selected under study is not displayed next to the study for add user 

Note: this is implemented only in edit user and the same should be in add user

**Expected behavior**
The number of sites selected under study should be displayed next to the study for add user 

**Screenshot**
![image](https://user-images.githubusercontent.com/63578379/104848520-4f9af600-590b-11eb-918f-3d8d78a08d00.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in latest QA instance.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.
