### ISSUE TITLE
SB > Eligibility Test and Comprehension Test > Issue with adding question

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2913]
If the 'token+test' or 'test' options are selected, users cannot add questions (the button is disabled) until they click on Save. In this case the 'Mark as complete' is also disabled asking the user to first add questions.  It is not apparent that the user needs to click Save to enable the "Add question' button. As a quick fix, to make it more apparent, suggest renaming the 'Save' button to Next until the 'Add question' button is enabled and back to Save thereafter. This does not need any functionality change for the Save/Next button. 

Also add mouse hover text to the 'Add question' button when disabled: Please click on Next to start adding questions
Edit mouse-hover text for the 'Mark as completed' button: Please add 1 or more questions to the test.'

Issue exists in the Comprehension Test screen as well.  Similar fix to be provided there as well.  
Also, the Comprehension Test screen has a field called 'Minimum score needed to pass' -  this should be hidden until the Add Question button is enabled.  Right now it is visible even when the Add Question button is disabled and appears usable/enabled, but no input is actually allowed when you type in it.

**Comment by Lathan-btc** [comment]
@navya-BTC tooltip text should be changed for the following scenario
Validation token an Eligibility test/Eligibility test > Add a question > Click on save button > Delete added question > Select Eligibility test/Validation token an Eligibility test  and mouse hovered on 'Mark as completed' button

AR : 

![tt1](https://user-images.githubusercontent.com/71445210/107649157-2fa8e900-6ca3-11eb-9723-88f0b7b741c7.png)

ER : 'Please click on Next to start adding questions' tooltip should be displayed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
