### ISSUE TITLE
[SB]  Eligibility Test and Consent Sections > Correct the messages displayed on click of Done

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2914]
After adding/editing  a question to the eligibility test and clicking on Done, the success message seen is incorrect and not relevant to the screen. Revise it to 'Eligibility question added', and 'Eligibility question updated'

After adding/editing  a consent section and clicking on Done, the success message seen is incorrect. Revise it to 'Consent section added', and 'Consent section updated'

After adding/editing  a comprehension test question section and clicking on Done, the success message seen is incorrect. Revise it to 'Comprehension question added', and 'Comprehension question updated'

Comprehension test > Minimum score needed to pass > Validation message seen when user enters a score greater than the number of questions seems to have a typo. Correct to 'The score should be less than or equal to the number of questions and greater than 0.'

Comprehension Test > Click on MAC without adding questions > Validation toast message to be corrected to 'Add at least one question'

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm

**Comment by monica-BTC** [comment]
@Lathan-btc , please test in dev and confirm

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA deployment

**Comment by monica-BTC** [comment]
@nagarjunav1 , please test and confirm in dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
