### ISSUE TITLE
iOS: Delete Account screen missing option to delete user account

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#2916]
**Describe the bug**
Delete account screen is different than Android

**To Reproduce**
1. Go to GCP mystudies app
2. Click on sign in and navigate to the home option
3. Select Delete account in My account
4. The screen of delete account is different than in Android

**Expected behavior**
The delete account should contain the option to delete the account for the user 

**Screenshots**
![image](https://user-images.githubusercontent.com/63578379/104875823-45fda680-597c-11eb-97fa-b4b3b396a3d0.png)

**Comment by tushar-boston** [comment]
This is working fine for me. Could you mention your device details?
![Simulator Screen Shot - iPhone 11 - 2021-01-18 at 12 10 02](https://user-images.githubusercontent.com/44088109/104881574-86165680-5987-11eb-895a-c57624245f33.png)

**Comment by sharathblr** [comment]
> This is working fine for me. Could you mention your device details?
> ![Simulator Screen Shot - iPhone 11 - 2021-01-18 at 12 10 02](https://user-images.githubusercontent.com/44088109/104881574-86165680-5987-11eb-895a-c57624245f33.png)

This is happening in iOS -13.6 Iphone 8

**Comment by nishit-v** [comment]
@sharathblr Please reverify this issue in 1.0(167)

Issue not reproducible in iPhone XS Max 14.3
