### ISSUE TITLE
[SB] Issues in view mode

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2919]
1. Delete button should be disabled and non-functional in view-only mode when the user has more than 2 answer options
AR :  Delete button is enabled and it is functional
ER : Delete button should be disabled and non-functional in view-only mode when the user has more than 2 answer options for the following
1. Comprehension test questions
2. Questionnaires > Value picker response type questions ( both question step and form step)
3. Questionnaires > Image choice response type questions ( both question step and form step)
4. Questionnaires > Text choice response type questions ( both question step and form step)
5. Questionnaires > Text scale response type questions ( both question step and form step)

![delete1](https://user-images.githubusercontent.com/71445210/104883995-9cbeac80-598b-11eb-8bbd-f5a871c583d9.png)

2. Questionnaires > Image choice response type questions > images fields should be disabled

![image112](https://user-images.githubusercontent.com/71445210/104892081-c2ea4980-5997-11eb-934b-9c07273bd369.png)

3. Questionnaires > response type dropdown is enabled and it is functional

![response1](https://user-images.githubusercontent.com/71445210/104894473-c6cb9b00-599a-11eb-85c3-eb50b6d240a0.png)

4. Questionnaires > Scheduled tab 
AR : User is able to switch between regular and anchor date-based, and able to edit the entered data.
ER : All the fields should be disabled

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please check and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
