### ISSUE TITLE
[SB] Functionality Buttons are enabled in Action screen in view mode

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2920]
A/R:- SB user can able to Pause, Resume, Deactivate..etc. for the Studies in view mode

E/R:- All the Functional buttons in the Actions screen should be disabled in view mode

![image](https://user-images.githubusercontent.com/60500517/104905720-c0442000-59a8-11eb-9e51-7715d671902a.png)

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in QA instance

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
