### ISSUE TITLE
[PM] Adjust the space between the icon and the text

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2922]
[PM] Adjust the space between the icon and text

![oauth](https://user-images.githubusercontent.com/71445210/104905422-53c92100-59a8-11eb-9af5-53b6db88fe33.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by Madhud5** [comment]
HI @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
