### ISSUE TITLE
[iOS] Closed study > Incorrect error message 'Your session is expired' is shown on using old token

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2923]
**Steps:**
1. PM admin adds an user to site A for a study
2. mobile app user enrolls into study successfully
3. WIthdraw from the study
4. PM admin adds the same user to site B for the same study
5. Enter old token of site A in eligibility screen
6. Observe the error message

**Actual:** Incorrect error message 'Your session is expired' is shown on using old token

**Expected:** 'Token already in use' should be displayed

**Screenshots:**

iOS:
![iOS](https://user-images.githubusercontent.com/60386291/104907615-5da05380-59ab-11eb-84c0-1e1a08253820.png)

Android for reference:
![Android](https://user-images.githubusercontent.com/60386291/104907620-609b4400-59ab-11eb-82bf-b30797611e61.jpg)

**Comment by tushar-boston** [comment]
The service is returning the error code 403.

Response: `{
  "timestamp" : 1610970974276,
  "status" : 403,
  "error_description" : "Token already in use",
  "error_type" : "Forbidden"
}`

For all the services, which return 403, the app will show Session expired. This has been implemented from the very starting.

**Comment by aswinijena100** [comment]
@tushar-boston U should under stand this happening only for IOS. Any changes at the backend will impact Android now. @naveenr-btc can u pls confirm if the same issue in Android as well

**Comment by tushar-boston** [comment]
@aswinijena100 I understand it's happening in iOS. But it's happening due to the wrong error code sent from the server which I've already mentioned above.

**Comment by aswinijena100** [comment]
@nishit-v please test and close the issue if fixed

**Comment by aswinijena100** [comment]
@nishit-v this issue fix is deployed in dev now . Please check and close the issue if fixed

**Comment by nishit-v** [comment]
Issue is resolved in Dev. Verified for Android and iOS.

![unnamed](https://user-images.githubusercontent.com/60386291/105342458-6476d280-5c06-11eb-984b-1553e7d06c1e.png)
