### ISSUE TITLE
[iOS] Enrollment and Onboarding status is not updated in PM post deleting account in mobile

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2924]
Steps:
1. Signup/login into iOS mobile app
2. Join any open/closed study successfully
3. Delete the accounnt 
4. Observe the Enrollment and Onboarding statuses

Actual: Enrollment and Onboarding status is not updated in PM post deleting account in mobile

Expected: Enrollment and Onboarding status should be updated in PM post deleting account in mobile

**Comment by nishit-v** [comment]
Issue is resolved in V1.0.165 build

**Comment by nagarjunav1** [comment]
@tushar-boston Merge the PR once approved and close the issue.
