### ISSUE TITLE
'Token already in use' error message should be displayed  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2927]
Steps
1. Add a user to closed study and invite 
2. Enroll into the study and withdrawn from the study
3. Again send the invitation through the same site
4. Mobile > Enter the previous token and observe the error message

AR : 'Unknown token' is displayed   
ER : 'Token already in use' should be displayed

**Comment by sharathblr** [comment]
@Lathan-btc - Since the participant is withdrawn and joining the Study, the participant ID is new here and the old token will be considered as unknown. This is working fine and closing the issue.
