### ISSUE TITLE
[SB] Hide the sections for which user does not permissions in My account section

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2928]
Steps:- 
1. Login into Study builder with Admin with edit Users permission or Superadmin access
2. Provide view/view&edit permissions for limited sections
3. Login with the user credentials
4. Navigate to My Account section and verify

A/R:- Currently, app displaying 'No' for the sections for which user doesn't have any permissions

E/R:- Hide the section itself for which user doesn't have any permissions

![image](https://user-images.githubusercontent.com/60500517/104915521-c5a86700-59b6-11eb-8cbb-7a23e47ed6b4.png)

**Comment by navya-BTC** [comment]
@nishit-v please test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
