### ISSUE TITLE
[SB] Revise text across screens

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2929]
Standardize use of title case and lower case across screens, and update text accordingly.

**Comment by monica-BTC** [comment]
@nishit-v , please test in QA and confirm

**Comment by monica-BTC** [comment]
@Lathan-btc , please test in Dev and confirm

**Comment by Lathan-btc** [comment]
@monica-BTC Issue is not fixed for the following

1. Manage Users > Add User > Role is displayed as 'ROLE' 
2. Manage Users > Add User > Permissions section > EXISTING STUDY PERMISSIONS  
3. Manage Users > View User > Email and Role
4. Manage Users > View User > Permissions section title
5. Manage Users > View User > Permissions section >EXISTING STUDY PERMISSIONS 
6. Create/Edit/Resend/Copy/View notification screen > Select App ID - A should be 'a'
7. Study Overview > For all 5 pages, default/alternative image info icon
8. Comprehension Test > not done for answer options

**Comment by monica-BTC** [comment]
@Lathan-btc , please test in QA and confirm

**Comment by Lathan-btc** [comment]
@monica-BTC 

Study Overview > For all 5 pages, default/alternative image info icon - not fixed for 2nd and 3rd page

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by monica-BTC** [comment]
@Lathan-btc , please test this issue in Dev and confirm

**Comment by nagarjunav1** [comment]
Issue is resolved in latest DEV build

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue should be fixed in all types of active tasks.

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
