### ISSUE TITLE
[PM] Default study thumbnail image is not displayed in sites and studies tab

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2933]
Steps:
1. Login to SB
2. Don't upload any thumbnail image i.e let be alternate image
3. Launch the study
4. Observe the study in PM

Actual: Default study thumbnail image is not displayed in sites and studies tab

Expected: Default study thumbnail image should be displayed in sites and studies tab

![Screenshot_3](https://user-images.githubusercontent.com/60386291/104925016-415ce080-59c4-11eb-9b07-4eee4420be45.png)

**Comment by nishit-v** [comment]
logoImageUrl is displaying empty string for sites API

![Screenshot_4](https://user-images.githubusercontent.com/60386291/104925292-a6183b00-59c4-11eb-8e27-e4a0cee16358.png)

**Comment by pujithr** [comment]
To test in DEV. Please let me know if it's works

**Comment by nishit-v** [comment]
Issue is resolved in Dev.

![Screenshot_3](https://user-images.githubusercontent.com/60386291/106138039-9d2c2400-6191-11eb-93cf-7226e06b8039.png)

**Comment by aswinijena100** [comment]
@nishit-v PR merged in dev , please retest and close the issue if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
