### ISSUE TITLE
[PM] Site participant registry > Invited tab > if user disables the participants then user is navigating to 'New' tab

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2940]
Scenario 1: New to Disable
Steps
1. Closed study > Site participant registry > go to the invited tab 
2. Select the participants email in New tab
3. Click on the disable invitation button
4. Observe the navigation of the user

AR : User is navigated to 'New' tab
ER : User should be navigated to Disable tab

Scenario 2: Invited to Disable 
1. Closed study > Site participant registry > go to the invited tab 
2. Select the participants email in the invited tab
3. Click on the disable invitation button
4. Observe the navigation of the user

AR : User is navigated to 'New' tab
ER : User should be navigated to Disable tab

Scenario 3: Disable to enable invitation

1. Closed study > Site participant registry > go to the invited tab 
2. Select the participants email in the disable tab
3. Click on the enable invitation button
4. Observe the navigation of the user

ER : User should be navigated to New  tab

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
