### ISSUE TITLE
[SB] Questionnaires > Branching > Destination step defined is not saving and hence unable to create branching questions

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2944]
**Steps:**

1. Edit the study
2. Add a questionnaire
3. Add some question steps
4. Apply branching and save
5. Edit the question step
6. Set destination step and save
7. Observe destination step is not saved

**Actual:** Destination step defined is not saving and hence branching is not working

**Expected:** Destination step defined should be saved

Due to above issue unable to create branching questions

https://user-images.githubusercontent.com/60386291/104996932-bffe6000-5a4e-11eb-8cdd-bcabfe6b73ca.mp4

Issue observed for Boolean and Text choice response types

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA and dev instance

**Comment by nishit-v** [comment]
Issue is resolved in Dev instance.
