### ISSUE TITLE
[SB] Questionnaires > Branching > UI Issue in response level attributes page

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2945]
Steps:

1. Edit the study
2. Add a questionnaire
3. Add some question steps of text choice response level attribute
4. Apply branching and save
5. Edit the question step
6. Observe the UI

![SB_1](https://user-images.githubusercontent.com/60386291/104997403-8aa64200-5a4f-11eb-80b1-c6814c51432b.png)

**Comment by monica-BTC** [comment]
@nishit-v , please test and confirm in dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
