### ISSUE TITLE
SB] Questionnaires > Branching > Destination step should not be mandatory for "other' option in text choice questions

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2946]
**Steps:**
1. Edit a study
2. Add a questionnaires
3. Add a text choice question with 'Other' option
4. Apply branching and save
5. Observe that Destination step is getting error message

**Actual:** Destination step is getting mandatory field for "other' option in text choice questions

**Expected:** Destination step should not be mandatory for "other' option in text choice questions

![Screenshot_1](https://user-images.githubusercontent.com/60386291/104997790-364f9200-5a50-11eb-8f44-020b125a8213.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build
