### ISSUE TITLE
[SB] Questionnaires > Branching > Conditional branching formula is not saving once Questionnaire is saved

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2947]
Steps:- 
1. Edit the study
2. Add a questionnaire
3. Add some question steps
4. Apply branching and save
5. Edit the question step
6. Set destination step and add conditional formula
7. Click on save and done button as shown
7. Observe applied formula is not saved

A/R:- Applied conditional formula for branching is not saved on Questionnaire
E/R:- Applied conditional  formula for branching should be saved on Questionnaire

note:- 1. Refer attached video for reference.
           2. Issue should be fixed for all the responses wherever conditional formula supported.
           i.e., Scale, Continuous scale, Numeric, Time interval, Height

https://user-images.githubusercontent.com/60500517/105006009-11611c00-5a5c-11eb-93ec-622388e7e8e2.mp4

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in Dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest DEV instance

**Comment by nagarjunav1** [comment]
Changing priority for the issue as main issue is resolved now. V1 value is deleted once click on done and edit questionnaire for < and > symbols.

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in Dev instance

**Comment by nagarjunav1** [comment]
App is crashing in mobile when when Questionnaires which are configured with > or < symbols are submitted

**Comment by madhurya-btc** [comment]
@naveenr-btc @tushar-boston Please check and let us know why app is crashing.

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in dev instance
