### ISSUE TITLE
studybuilder should accept images of varying sizes and scale them to fit the requirements

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#295]

**Comment by pujithr** [comment]
To test in DEV INS

**Comment by nagarjunav1** [comment]
Now able to update the images of varying sizes across study Builder wherever applicable. But, Images are not properly adjusted in the mobile .

![image](https://user-images.githubusercontent.com/60500517/111772200-9c328b80-88d2-11eb-9d35-ed26dd6092b1.png)

![image](https://user-images.githubusercontent.com/60500517/111772228-a5235d00-88d2-11eb-8db5-550999d98438.png)

**Comment by SR-btc** [comment]
@pujithr On the SB, we need a way to scale the images as required for the mobile screens. Please see how that can be done.  If it is necessary to have a minimum size uploaded by the user, we can have that validation in place but at least scale down images larger than that.

**Comment by dhanyak-btc** [comment]
@pujithr Please refer to the[ image resize ](https://www.baeldung.com/java-resize-image)article. Resize the large image to smaller image before storing into Cloud Storage.
I suggest using the Apache 2.0 or MIT license libraries. @SR-btc Please compare the image resize results and suggest which library to use.

**Comment by sharathblr** [comment]
Find the below validation  message and information icon messages:

Validation message, If uploaded image not in recommended size or format (png, jpg) -  Invalid image size or format

information message when user mouse hovers:
The default image shown below will be used for the study list thumbnail in the mobile app. Upload an alternate image if you wish to override it. 
The image must be of type . JPG or .PNG. The minimum required image size is <Pixel Size>. For optimum display in the mobile app, upload an image of either the minimum size or one that is proportionally larger.

CC: @pujithr, @nishit-v , @nagarjunav1 , @Lathan-btc , @SR-btc

**Comment by nagarjunav1** [comment]
Image in thumbnail is refreshing continuously in mobile. Refer video attached.
https://user-images.githubusercontent.com/60500517/116352666-21cf2280-a813-11eb-8ee0-61c0a41be6b8.mp4

**Comment by pujithr** [comment]
@nagarjunav1. Fix is deployed in QA environment, kindly test and update this ticket

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
