### ISSUE TITLE
[SB] Need to adjust the top bar UI in Create/Edit Study screen 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2952]
Logo and Profile are distorted when user mouse hover on tabs 

Note:- Refer attached video for reference

A/R:- Logo and Profile dropdown are distorted when mouse over on top bar tabs 

E/R:- Other elements in the top bar should not be distorted when user mouse over on different tabs 

https://user-images.githubusercontent.com/60500517/105035811-9d396f00-5a81-11eb-8bc5-c9eaf39910a3.mp4

**Comment by navya-BTC** [comment]
@nishit-v please test in QA.

**Comment by nishit-v** [comment]
Issue is resolved in QA

**Comment by navya-BTC** [comment]
@nagarjunav1 please test in dev.

**Comment by nagarjunav1** [comment]
Issue is resolved in latest DEV build
