### ISSUE TITLE
[SB] Text alignment issue when 'Apply branching' option is selected

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2957]
Steps
1. Questionnaires > Add/edit questionnaires 
2. Add some questions
3. Select the 'Apply branching' option and click on the 'Save' button
4. Click on the edit button of the questionnaire for which branching is applied
5. Navigate to the 'Response level attributes' tab 
6. Select the 'Use formula-based conditional branching logic' option
7. Select the destination step from the dropdown and then mouse hovered on the dropdown

AR : Alignment of the text is not proper
ER : Alignment of the text should be proper 

![branching](https://user-images.githubusercontent.com/71445210/105051569-e5ae5800-5a94-11eb-893d-c2c9ff7a84a8.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
