### ISSUE TITLE
[SB] UI issue in edit questionnaire page

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2959]
Steps
1. Questionnaires > Add/Edit questionnaires
2. Click on add question step or add form step
3. Navigate to Question level attributes and select text scale response type
4. Navigate to Response level attributes and enter the values in all the fields and click on save
5. Click on the back button and go to the edit questionnaire page 
6.  Add more than 2 answer options by Clicking on the + icon and observe the UI of the fields  

![textscale](https://user-images.githubusercontent.com/71445210/105055669-4dff3880-5a99-11eb-83bc-177c9f7296eb.png)

**Comment by pujithr** [comment]
to test in QA

**Comment by Lathan-btc** [comment]
@pujithr text fields length issue
1. Before saving the data or clicks on done botton

![textscale before](https://user-images.githubusercontent.com/71445210/105461105-c1c85d80-5cb2-11eb-8e05-d362d3cb862e.png)

2. In the edit questionnaire page ( After saving the data click on back/done button and agin navigate to edit questionnaire page)



![after](https://user-images.githubusercontent.com/71445210/105461929-ee30a980-5cb3-11eb-8ad5-1f6d142d92da.png)

**Comment by pujithr** [comment]
@Lathan-btc Reworked and deployed new changes. Please Verify and let me know if its works

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by pujithr** [comment]
To test in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
