### ISSUE TITLE
Questionnaires > Add/Edit questionnaire > Recently entered 'Time' and 'Number of times to repeat the task' is not getting reflected

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2962]
Steps 
1.Questionnaire > Create/Edit a questionnaire with daily/ weekly/monthly frequency 
2. Click on edit questionnaire 
3. Navigate to the schedule tab and Change the time and click on done
4. Again Click on the edit questionnaire, navigate to the schedule tab and observe the time

AR : Previously entered 'Time' and 'Number of times to repeat the task' is displayed
ER : Recently entered and saved 'Time' and 'Number of times to repeat the task' should be reflected in the schedule tab

[Note : it should be handled for both questionnaires and active tasks]

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
