### ISSUE TITLE
[SB] Questionnaires > Branching > Need to remove the delete icon from conditional based formula function

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2965]
Steps:-

1. Edit the study
2. Add a questionnaire
3. Add some question steps
4. Apply branching and save
5. Edit the question step
6. Set destination step and add conditional formula using function elements

A/R:- Delete icon is available for each element in function and it is not functional 

E/R:- Delete icon should be removed for each element in function

![image](https://user-images.githubusercontent.com/60500517/105137732-cefe1480-5b19-11eb-92ac-688071c54b6c.png)

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed please check and confirm

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed in QA, please check and confirm

**Comment by nagarjunav1** [comment]
Issue is resolved in latest QA build
