### ISSUE TITLE
[SB] Questionnaries > Scale > App should not allow to set default value less than minimum value 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2967]
Steps:- 
1. Login into application
2. Navigate to studies and then edit study
3. Navigate to questionnaires and configure an questionnaire with question step as shown in image
4. Click on done and verify

A/R:- App is allowing the user to configure the question step with default value which is less than minimum value
E/R:- App should not allow to set default value less than minimum value 

![image](https://user-images.githubusercontent.com/60500517/105167354-a0466500-5b3e-11eb-8200-10c2bed7ba1e.png)

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test this in dev and let know if works fine

**Comment by nagarjunav1** [comment]
It is not allowing the numbers less than minimum value but it is not displaying the validation message for numbers greater than max value.

**Comment by nagarjunav1** [comment]
Issue also need to fix for **scale** response in  **form step**. 
App should not allow to set default value less than minimum value and greater than maximum value.

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test this is in dev and closed if issue fixed in both the pages

**Comment by nagarjunav1** [comment]
Issue is fixed for Question Step and Form Step for minimum Value. But, when user set the default value greater than max value app displayed wrong error message.

![image](https://user-images.githubusercontent.com/60500517/105698885-8cc73f80-5f2c-11eb-9d2e-f339c4fa5a54.png)

**Comment by aswinijena100** [comment]
@nagarjunav1 This is the valid error message. I have already discussed with @nishit-v before fixing this issue.

**Comment by nagarjunav1** [comment]
Issue is fixed and working as expected.
