### ISSUE TITLE
[SB] Questionnaires > Add questionnaire > Text scale response type > Wrong radio button is selected in response level attributes

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2978]
Steps
1. Questionnaires > Click on add questionnaire 
2. Go to add question step/add form step
3. Question level attributes tab > select 'Text scale' response type 
4. Response level attributes tab> Don't change the scale type and enter all the required values and click on save
5. Click on the back button and again navigate to edit question step/ edit form step 
6. Observe the Scale type

AR : 'Horizontal' radio button is selected
ER : 'Vertical' radio button should be selected

https://user-images.githubusercontent.com/71445210/105217233-9b52d700-5b79-11eb-95da-b9e04ab809b7.mp4

**Comment by pujithr** [comment]
@Lathan-btc. Please Verify it in QA and let me know if it works fine

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by pujithr** [comment]
To test in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
