### ISSUE TITLE
[SB] Questionnaires > Add questionnaires > Schedule tab > Daily frequency > Delete button issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2980]
Questionnaires > Add questionnaires > Schedule tab > Daily frequency > Delete button issue
1. If the user click on the + icon of the 'Time(s) of the day for daily occurrence' then for the 1st option delete icon should be 
disaplyed

![daily1](https://user-images.githubusercontent.com/71445210/105219242-3f3d8200-5b7c-11eb-97c1-2689080794c6.png)

2. Create a questionnaire with daily frequency (only one time per day) > Click on save > Click on back button > Edit questionnaire > go to schedule tab > delete button should not be displayed when there is only one row under 'Time(s) of the day for daily' occurrence'

![daily2](https://user-images.githubusercontent.com/71445210/105219309-541a1580-5b7c-11eb-9fce-93d713d16948.png)

[Note : 1. it should be fixed for questionnaires (Anchor date based and regular), Active tasks (Anchor date based and regular)
            2. Issue should  be fixed for both Daily and Custom schedule]

**Comment by aswinijena100** [comment]
@Lathan-btc @nagarjunav1 Please test this issue in QA and close it fixed

**Comment by nishit-v** [comment]
Issue is resolved in QA and Dev.
