### ISSUE TITLE
[PM] Need to modify the UI/UX for the loader for better user experience in dashboard screens

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2981]
Need to display the text '+x more sites' in loader area in Sites, Studies and Apps screens

![image](https://user-images.githubusercontent.com/60500517/105283521-a556f300-5bd6-11eb-9576-b98211954a79.png)

**Comment by nagarjunav1** [comment]
For the loader icon in Sites/Studies/Apps tabs in PM, its better to add some informative text for the loader area so that it help user to what he should do to load remaining sites. Because as per current implementation, only first 10 sites will display and remaining sites will load only when user mouse over on loader icon area and user don't have any information on it.

@fahadbtc-zz  Please Provide better UI/UX solution for this. So that we can implement that for better user experience.
Thank you

**Comment by fahad-kc** [comment]
I have added the text along with the loader and shared with @sujatha-btc. It says "loading more sites...".

**Comment by sujatha-btc** [comment]
@nagarjunav1 deployed please test and confirm.

**Comment by nagarjunav1** [comment]
@fahad-kc Can you update the text to '**Load more sites**'.  Similarly for studies and apps.

@SR-btc can you please confirm on the text to display .

**Comment by nagarjunav1** [comment]
We can keep the text as below for sites, studies and apps respectively , confirmed by Shanthala.
'Load more sites'
 'Load more studies'
 'Load more apps'

**Comment by sujatha-btc** [comment]
@nagarjunav1 deployed please text and confirm.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build.

**Comment by aswinijena100** [comment]
@nagarjunav1 please test in QA and close if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
