### ISSUE TITLE
[PM] Fix text case usage across screens

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#2982]
Standardize use of title case, upper and lower case across screens, and update text accordingly.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
@firdosebtc1 Issue is not fixed for the following pages
1. Sites, studies, and apps tabs ( Number of sites/studies)
2. Add location page
3. Location details page 
4. Edit location details page
5. Add new admin page
6. Admin details page
7. Edit admin details page
8. My account page
9. Change password screen
10. Setup account page

**Comment by firdosebtc1** [comment]
> @firdosebtc1 Issue is not fixed for the following pages
> 
> 1. Sites, studies, and apps tabs ( Number of sites/studies)
> 2. Add location page
> 3. Location details page
> 4. Edit location details page
> 5. Add new admin page
> 6. Admin details page
> 7. Edit admin details page
> 8. My account page
> 9. Change password screen
> 10. Setup account page

@Madhud5 please check all points except 1st point as I have already changed text in code but because of CSS the labels are again changing to capitalized

![image](https://user-images.githubusercontent.com/60000166/105678767-89738a00-5f13-11eb-8286-5d34eaa679c2.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
Issue is not fixed for the following
1. Add new admin/Admin details/Edit admin details page > permissions section > 'View And Edit' text should be changed to 'View and edit'

![vae](https://user-images.githubusercontent.com/71445210/106133872-d366a500-618b-11eb-8910-e3996ab402bd.png)


2. Terms of service page > Page title > 'S' should be small 's'


![terms11](https://user-images.githubusercontent.com/71445210/106133893-dbbee000-618b-11eb-9edb-fec2406eb6f2.png)

**Comment by firdosebtc1** [comment]
> Issue is not fixed for the following
> 
> 1. Add new admin/Admin details/Edit admin details page > permissions section > 'View And Edit' text should be changed to 'View and edit'
> 
> ![vae](https://user-images.githubusercontent.com/71445210/106133872-d366a500-618b-11eb-8910-e3996ab402bd.png)
> 
> 1. Terms of service page > Page title > 'S' should be small 's'
> 
> ![terms11](https://user-images.githubusercontent.com/71445210/106133893-dbbee000-618b-11eb-9edb-fec2406eb6f2.png)

@Madhud5 please do css changes here also as I have already changed text

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
