### ISSUE TITLE
[SB] HTML breakage in study name field in basic information section once saved

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2987]
Steps:-
1. Login into SB
2. Navigate to studies
3. Click on edit the study and add any special characters as shown and click on save 
4. Observed saved data

Before saving
![image](https://user-images.githubusercontent.com/60500517/105362096-76fe0580-5c20-11eb-8979-626d6725d783.png)

After saving
![image](https://user-images.githubusercontent.com/60500517/105362348-ca705380-5c20-11eb-9d10-acd20a5c8bb5.png)

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please update, which and all page HTML is breaking.

**Comment by nagarjunav1** [comment]
HTML breakage happened in these text fields while using any special characters

**Study info**
1.Study name *
2.Descriptive study name (150 characters max) *

**Overview**
1.Title (50 characters max) *
Note:-Need to fix for all pages

**Eligibility**
1.Question (250 characters max) *

**Comprehension**
1.Question (300 characters max) *

**Questionnaires**
1. Question Text (1 to 300 characters) * 
2. Display name for the Stat (e.g. Total Hours of Activity Over 6 Months) (1 to 50 characters) *
3. Display Units (e.g. hours) (1 to 15 characters) * 
4. Display Text (1 to 20 characters) *
Note:- Need to fix for all response types

**Active tasks**
1. Display name (150 characters max) * 
2. Display name for the Stat (e.g. Total Hours of Activity Over 6 Months) (1 to 50 characters) *
3. Display Units (e.g. hours) (1 to 15 characters) * 

**Resources**
1.Title  (50 characters max) *

**Gateway notifications**
1. Notification Text

**Users**
1. First Name
2. Last Name

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test this in QA and close it if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
