### ISSUE TITLE
[SB] Custom schedule frequency > Time field is disabled in a scenario

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2994]
**Steps:**

1. Edit a study
2. Navigate to Questionnaires/Active tasks
3. Select 'Custom Schedule'
4. Select valid start date, end date and time
5. Again reselect same Start date and end date
6. Mouse hover on the time field
7. Observe Time field is disabled

**Actual:** Time field is disabled in a scenario

**Expected:** Time field should be enabled for valid SD and ED

Note: Issue observed for both Questionnaires and active tasks

https://user-images.githubusercontent.com/60386291/105453892-00f0b180-5ca7-11eb-995c-7adf96e60f78.mp4

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
