### ISSUE TITLE
[SB] Custom schedule frequency > Time field showing less than current server time

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2995]
**Steps:**

1. Edit a study
2. Navigate to Questionnaires/Active tasks
3. Select 'Custom Schedule'
4. Select current server's start date, valid end date
5. Click on the time field
6. Observe Hour field is showing less than current server time
7. Select a time less than current server time
8. Again click on the time field and observe issue is not observed

**Actual:** Time field showing less than current server time

**Expected:** Time field should show only till current server time (same as of daily/weekly/monthly time)

Note: Issue observed for both Questionnaires and active tasks

https://user-images.githubusercontent.com/60386291/105454703-52e60700-5ca8-11eb-9112-f55d58c601df.mp4

**Comment by pujithr** [comment]
To test in DEV ENV

**Comment by Lathan-btc** [comment]
Issue is resolved in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is not reproducible in Dev and QA(automated deployment). Hence closing this ticket
