### ISSUE TITLE
[SB] OneTime frequency > Time field taking less than current server time and able to save

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2996]
**Steps:**

1. Edit a study
2. Navigate to Questionnaires/Active tasks
3. Select One Time
4. Choose custom start date and time
5. Select current's server date (let server time - 01/22/2021 6AM)
6. select time less than the server's time Eg. select 01/22/2021 and 12AM 
7. Observe time field is taking less than server time

**Actual:** Time field taking less than current server time and able to save

**Expected:** Time field should not take less than current server time and able to save and handled same as like other time fields for other freuquencies (daily/weekly/monthly/custom)

Note: Issue observed for both Questionnaires and active tasks

![3rd](https://user-images.githubusercontent.com/60386291/105455226-2ed6f580-5ca9-11eb-859c-a1713ce00b0a.png)

**Comment by aswinijena100** [comment]
@nishit-v please test this issue in QA and close if fixed

**Comment by nishit-v** [comment]
Issue is still observed in QA instance.

![Screenshot_3](https://user-images.githubusercontent.com/60386291/109294715-8c83d200-7853-11eb-9aea-367807781950.png)

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in dev.

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.
