### ISSUE TITLE
[SB] Active tasks > Wrong validation message is displayed when active tasks are scheduled in past

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2997]
**Steps:-**

1. Schedule an active taks activity as per UTC time zone and complete the section
2. Complete all the sections of Study
3. Wait for the scheduled time to get expire
4. Click on Publish updates and verify the validation message displayed

**A/R:-** One or more of the study’s activities or resources has a schedule that needs an anchor date. Please add an anchor date and try again.
**E/R:-** One or more of the study's activities is scheduled for a date that has already expired. Please correct the same and try again.

![Screenshot_15](https://user-images.githubusercontent.com/60386291/105455612-c9cfcf80-5ca9-11eb-9df9-936907bf8bd0.png)

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in QA, please check and confirm

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please test and update the ticket

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev build
