### ISSUE TITLE
[PM] Sites page is not retained when user clicks on load more icon and adds a site

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2998]
**Steps:**
1. Login and navigate to sites
2. Click on load more icon
3. Next set of sites is loaded
4. Add a site to any of the study and save
5. Observe page is not retained

**Actual:** Scroll bar is moved to the first set of sites loaded

**Expected:** Sites page should be retained when user clicks adds a site i.e page should show the study which is recently added a site to it should visible on the page

https://user-images.githubusercontent.com/60386291/105457410-cbe75d80-5cac-11eb-8069-f336fdf66428.mp4

**Comment by monica-BTC** [comment]
@nishit-v , please test and confirm in dev

**Comment by nishit-v** [comment]
Issue is resolved in Dev

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
