### ISSUE TITLE
[PM] Open study > Enrollment status is incorrectly displayed as 'Not eligible' in participant details page

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2999]
**Steps:**
1. Enroll into any open study successfully
2. WIthdraw from the study
3. Fail the eligibility test for the same study
4. Observe the Enrollment status value in participant details page

**Actual:** Enrollment status is incorrect displayed as 'Not eligible' in participant details page

**Expected:** Enrollment status should displayt 'Withdrawn' in participant details page

Note: Issue not observed in Enrollment registry page

![Screenshot_2](https://user-images.githubusercontent.com/60386291/105465274-b5470380-5cb8-11eb-860f-caa948324401.png)

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev
