### ISSUE TITLE
[PM] Open study > Enrollment status is incorrectly displayed as 'Yet to enroll'

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3000]
**Steps:**

1. Enroll into any open study successfully
2. WIthdraw from the study
3. Pass the eligibility test for the same study and don't provide consent
4. Observe the Enrollment status value in participant details page

**Actual:** Enrollment status is incorrectly displayed as 'Yet to enroll'

**Expected:** Enrollment status should display 'Withdrawn'

Note: Issue observed in Enrollment registry page and participant details page

![Screenshot_3](https://user-images.githubusercontent.com/60386291/105465568-153daa00-5cb9-11eb-809c-d087adc6fb58.png)

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please check and confirm

**Comment by nishit-v** [comment]
Issue is now observed in Enrollment registry page only. Fixed in participant details page

![Screenshot_5](https://user-images.githubusercontent.com/60386291/105499521-99a72180-5ce7-11eb-9312-b4042a5dff70.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev.
