### ISSUE TITLE
[PM] Enrollment registry > Entered text is getting removed after searching

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3001]
**Steps:**
1. Navigate to any open study in sites/studies tab
2. Enter a valid/invalid search and click on enter
3. Observe entered text is getting removed 

**Actual:** Entered text is getting removed after searching

**Expected:** Entered text should be retained

Note: Issue not osberved in other pages

https://user-images.githubusercontent.com/60386291/105466168-dbb96e80-5cb9-11eb-8a7f-4b12e2da75f8.mp4

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@nishit-v  Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
