### ISSUE TITLE
[iOS] Study Activities > User is able to submit responses multiple times for a single run

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3004]
**Steps:**
1. Configure a daily/weekly/monthly/custom scedule activities having > 1 runs
2. Publish the updates
3. Login and enroll into study from iOS mobile
4. Submit response for first run. Status is completed
5. Again click on the completed activity and observe

**Actual:** Clicking on the completed activity, activity completed page displaying and user is able to click on 'Done' and submit the same response multiple times

**Expected:** Once a run is completed, user should be disallowed click action

Issue observed for Questionnaires and active tasks

https://user-images.githubusercontent.com/60386291/105481221-c26ded80-5ccc-11eb-9652-32cba68a1169.MOV

**Comment by tushar-boston** [comment]
This change was done for debugging purposes and the code is not merged to any branch. Hence closing the issue.
