### ISSUE TITLE
[PM] [Audit Logs] "studyVersion" is displayed null for the events

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3005]
Events in PM:

1. SITE_ADDED_FOR_STUDY
2. PARTICIPANT_EMAIL_ADDED
3. PARTICIPANTS_EMAIL_LIST_IMPORTED
4. PARTICIPANTS_EMAIL_LIST_IMPORT_FAILED
5. PARTICIPANTS_EMAIL_LIST_IMPORT_PARTIAL_FAILED
6. SITE_DECOMMISSIONED_FOR_STUDY
7. SITE_ACTIVATED_FOR_STUDY
8. PARTICIPANT_INVITATION_DISABLED
9. CONSENT_DOCUMENT_DOWNLOADED
10. INVITATION_EMAIL_SENT
11. INVITATION_EMAIL_FAILED
12. PARTICIPANT_INVITATION_ENABLED
13. ENROLLMENT_TARGET_UPDATED
14. SITE_PARTICIPANT_REGISTRY_VIEWED
15. STUDY_PARTICIPANT_REGISTRY_VIEWED

Sample snippet for event `SITE_ADDED_FOR_STUDY` event

```
{
  "insertId": "epzd98g1b9f0co",
  "jsonPayload": {
    "correlationId": "2eb996c6-4d84-435b-b438-35caf65ae6b2",
    "userAccessLevel": null,
    "eventCode": "SITE_ADDED_FOR_STUDY",
    "platformVersion": "1.0",
    "source": "PARTICIPANT MANAGER",
    "occurred": 1611313124346,
    "mobilePlatform": "UNKNOWN",
    "userId": "2c9180897689364401768a08f0060000",
    "studyId": "2c91808876fa9409017706d12918002a",
    "destinationApplicationVersion": "1.0",
    "participantId": null,
    "appVersion": "v0.1",
    "studyVersion": null,
    "siteId": "2c91808977290f8f017729bf13eb0006",
    "sourceApplicationVersion": "1.0",
    "destination": "PARTICIPANT USER DATASTORE",
    "resourceServer": null,
    "userIp": "117.211.20.33",
    "description": "Site added to study (site ID- 2c91808977290f8f017729bf13eb0006).",
    "appId": "2c91808876fa9409017706d11ea10028"
  }
```

**Comment by navya-BTC** [comment]
@nishit-v please test

**Comment by nishit-v** [comment]
Issue is resolved in DB.
