### ISSUE TITLE
Password help screen > Blank screen is displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3016]
AR : Password help screen > Blank screen is displayed for 2-3 seconds when a user enters registered email id and clicks on submit button
ER : Blank screen should not be displayed

![PWD help4](https://user-images.githubusercontent.com/71445210/105517608-450ea100-5cfd-11eb-9f6f-f390bab58e2d.png)

**Comment by prakashm181** [comment]
This cannot be handled .After password request it is redirecting to auth server it takes few seconds to redirect

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please confirm. can not be entirely remove the time will get issue in login. reduced the time for blank screen.

**Comment by aswinijena100** [comment]
@Lathan-btc  please test in QA and close if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
