### ISSUE TITLE
[SB] My account screen > Permission section issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3017]
Steps
1. log in as user A 
2. Assign a 'View and edit' permission for 'Users' and 'Notifications' for the userB
3. log in as a user B
4. Navigate to the My Account screen
5. Observe the contents of the assigned permissions section

AR : 'View only View & edit' is displayed
ER : It should display 'View and edit' 

![my account1](https://user-images.githubusercontent.com/71445210/105523980-11377980-5d05-11eb-8cb5-089a7ff89eb5.png)

**Comment by aswinijena100** [comment]
@Lathan-btc Please test and let know if issue fixed in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc PR merged in dev. Please retest and close this issue if fixed.

**Comment by Lathan-btc** [comment]
Issue is not reproducible in the latest Dev instance.
