### ISSUE TITLE
[SB] Provide setting for admin to decide if a new consent document version should trigger a consent flow in the mobile app for enrolled participants

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3022]
For a study that is already launched, the consent document undergoes a version increment when the corresponding section (Econsent)  is marked complete in the Study Builder and updates are published to the study .  This automatically results in the mobile app user being required to undergo consent again if they are already enrolled into the study and actively participating.  Changes to the consent document may at times be trivial or cosmetic in nature, and may not necessarily warrant the need for participants to undergo consent again. 

We should perhaps have a feature where we ask the Study Builder admin to confirm (at the point of marking the section complete) if the new version requires participants to undergo consent again. Alternatively, this could also be a checkbox-style preference on the SB's Consent screen, or a field that helps them specify if the update is a minor version increment of the consent document or major. The admin's input here would determine whether the mobile app user would need to undergo consent again or not. 

However, the rest of the behavior of this section would remain the same irrespective of this setting - that is, on marking the section complete and updates getting published,  the document version gets incremented, and the latest content would reflect in the mobile app. The latest content would show up for any new users who enroll and additionally for existing participants who are asked to consent again (based on the SB setting).

**Comment by SR-btc** [comment]
Checkbox to be used: Enforce e-consent flow again for enrolled participants (i)
Info icon text:  Check this box if you want enrolled participants to undergo consent in the mobile app again with the latest version of the consent document.  New participants will always see the latest version of the consent document.
Add text next to the subtitle called 'Consent Document' as follows: Consent Document (Current draft version: V<1.4>, Last published version: V<1.2>) (i)
Info icon text:  The version of the consent document gets updated each time you mark this section complete. The latest available version at any point is what mobile app users get when you publish updates to the study. The 'draft version' thus represents the latest version in the draft state of the study, while the 'last published version' represents the version that was last published to mobile app users.

The checkbox need not be shown as long as the study is in pre-launch status

**Comment by nagarjunav1** [comment]
Enhancement has been implemented in Android and Study Builder and it is working fine in latest DEV builds

**Comment by nishit-v** [comment]
Enhancement has been implemented in iOS and working fine in the latest Dev build V1.0.223

**Comment by aswinijena100** [comment]
@nishit-v Please test in QA and close once received latest build from IOS and Android

**Comment by nishit-v** [comment]
Issue is fixed in latest QA. Verified in SB,Android and iOS
