### ISSUE TITLE
[SB] Active tasks > Error message is not displayed for 'Activity short title or key'

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3025]
Steps
1. Active tasks > Click on Add active task button
2. Enter 'Activity short title or key' with invalid/unsupported special characters and observe

AR : An error message is not displayed
ER : 'Please use allowed characters only: lowercase alphabets (a-z), digits (0-9), _ (underscore) and -(minus).' error message should be displayed.

![titlekey1](https://user-images.githubusercontent.com/71445210/105703610-84263780-5f33-11eb-9f2a-f281b0c54cbe.png)

**Comment by pujithr** [comment]
to test in QA env

**Comment by Lathan-btc** [comment]
@pujithr Error message is overlapping with the text field

![e1](https://user-images.githubusercontent.com/71445210/106001182-a6f05180-60d5-11eb-9256-58b1efd21d9c.png)

**Comment by aswinijena100** [comment]
@Lathan-btc please verify in dev and close the issue if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
