### ISSUE TITLE
[PM] User details page > Search bar > 'No records found' text should be displayed when user searches with invalid input

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3029]
AR : User details page > Search bar > Empty section is displayed when a user searches with invalid input
ER : User details page > Search bar > 'No records found' text should be displayed when a user searches with invalid input

[Note : Issue should be fixed for Add new admin, Admin details page, and Edit admin details page]

![search21](https://user-images.githubusercontent.com/71445210/105741143-fa409380-5f5f-11eb-9cac-c4630a9a5d8d.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
@firdosebtc1 
'No records found' text should be displayed for the 'Add new admin' and 'Edit admin details' page

![search11](https://user-images.githubusercontent.com/71445210/106000479-dfdbf680-60d4-11eb-8fa9-7649584272f3.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance
