### ISSUE TITLE
[SB] Assigned permissions section > Text needs to be change

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3030]
AR : Assigned permissions section > 'View & edit' is displayed if user has view and edit permission
ER : 'View and edit' should be displayed

![perm1](https://user-images.githubusercontent.com/71445210/105742451-88694980-5f61-11eb-9523-cf5b2098a00e.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test in QA.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by navya-BTC** [comment]
@Lathan-btc please test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
