### ISSUE TITLE
Change the text from 'Email ID' to 'Email'

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3033]
For consistency change the text from 'Email ID' to 'Email' for the following screens
1. Add new admin screen
2. Edit admin details screen
3. My account screen

![emailid2](https://user-images.githubusercontent.com/71445210/105957913-e734dd00-609f-11eb-8a2b-0a4f015c38ce.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by nishit-v** [comment]
Issue is resolved in Dev
