### ISSUE TITLE
[SB] Need to adjust UI of the top white bar

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3035]
Needs to adjust UI of the top white bar same as other screens in SB for the following screens
1. Edit question step
2. Edit question in the form step
3. Error pages of the SB

https://user-images.githubusercontent.com/71445210/105978617-c0cf6b80-60b8-11eb-9f98-a2d1dfaa0cdd.mp4

**Comment by pujithr** [comment]
To test in QA Env

**Comment by Lathan-btc** [comment]
@pujithr Issue is still reproducible for the Error pages of the SB

![e11](https://user-images.githubusercontent.com/71445210/106282206-46dce500-6266-11eb-9305-e9140e40196e.png)

**Comment by pujithr** [comment]
@Lathan-btc .Please verify in DEV ENV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA Instance.
