### ISSUE TITLE
[SB] Daily / Custom schedule > Delete icon should not be displayed when there is only one run

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3037]
**Steps:**
1. Edit a study
2. Navigate to questionnaires/Active task
3. Create a daily/custom schedule activity with Regular/Anchor based
4. Add question step and click on done
5. Click on mark as completed 
6. Edit the same activity and navigate to scheduling
7. Click on delete icon and observe

**Actual:** Delete icon is displayed and user able to delete when there is only one run for Daily/Custom runs

**Expected:** Delete icon should not be displayed when there is only one run for Daily/Custom runs

**Note:** 

- Issue not observed while creating an acitivy but observed in Edit scenario
- Issue observed for both Questionnaires and Active tasks
- Issue observed for Daily and custom schedule frequencies 
- Issue observed for Regular and Anchor based frequency types

Daily: 

https://user-images.githubusercontent.com/60386291/105987145-de560280-60c3-11eb-9998-618ec3b49dbf.mp4

Custom schedule: 

https://user-images.githubusercontent.com/60386291/105987158-e2822000-60c3-11eb-9dc3-422111238ff4.mp4

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please check and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in QA, please test and confirm

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
