### ISSUE TITLE
[Audit Logs] "studyVersion" is displayed null for the event in Response module

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3039]
Event:

STUDY_METADATA_RECEIVED

![105966351-8a8aef80-60aa-11eb-8fd5-7bc18ddee4de](https://user-images.githubusercontent.com/60386291/105994561-c71c1280-60cd-11eb-8832-658967f60043.png)

**Comment by chiranjibi009** [comment]
![image](https://user-images.githubusercontent.com/59357395/105995877-9a68fa80-60cf-11eb-94e5-61f3443c674f.png)

@nishit-v Please check this. I have tested from my end.
Please test from your end and update.

**Comment by nishit-v** [comment]
Issue is resolved in Dev now. 
![Screenshot_5](https://user-images.githubusercontent.com/60386291/105999227-71e2ff80-60d3-11eb-94a9-726363be076a.png)

**Comment by chiranjibi009** [comment]
@nishit-v  Please test this issue in dev environment and update.
