### ISSUE TITLE
[SB] Adjust padding of first and last columns in table views

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3049]
SB > App-wide notifications >   increase left padding for first column and right padding for last column
Verify the same for other table views in the SB such as Manage Users

**Comment by Madhud5** [comment]
Hi @SR-btc   and @Lathan-btc  i have fixed please check this issue in QA env.
thank you

**Comment by Lathan-btc** [comment]
Issue is not fixed in the latest QA instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 Users > UI is broken 

[Note : Issue is observed only in Firefox browser]


![users7](https://user-images.githubusercontent.com/71445210/106429422-67888300-6490-11eb-871c-332c09e2ab52.png)

**Comment by Madhud5** [comment]
Hi, @Lathan-btc  I have fixed it please check-in QA env and confirms here.

**Comment by Lathan-btc** [comment]
@Madhud5 following point is reproducible
1. 'Actions' label should be left-aligned for the actions column for the following     
    1. Notifications table
    2. Comprehension test questions table
    3. Eligibility test questions table
