### ISSUE TITLE
[SB] App wide notifications list screen > Remove tooltip when user mouse hovered on the data present under 'Notification' column

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3051]
App wide notifications list screen > Remove tooltip when user mouse hovered on the data present under 'Notification' column

![noti1](https://user-images.githubusercontent.com/71445210/106096433-8ec31580-615b-11eb-9e89-0a37ac1db49c.png)

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm in QA

**Comment by nagarjunav1** [comment]
Issue is resolved in latest QA build

**Comment by monica-BTC** [comment]
@nagarjunav1 , please test and confirm in DEV

**Comment by Lathan-btc** [comment]
Issue is ixed in the latest Dev instance.
