### ISSUE TITLE
[SB] Study Overview > Text of info icon for 'Study overview pages' > Resize the info popup to have more width, and less height for easy readability

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3053]
Study Overview > Text of info icon for 'Study overview pages' > Resize the info popup to have more width, and less height for easy readability

![info](https://user-images.githubusercontent.com/71445210/106099672-12cbcc00-6161-11eb-906d-0a1333370d77.png)

**Comment by pujithr** [comment]
To Test in DEV ENV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance
