### ISSUE TITLE
[SB] Comprehension test > Questions table issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3054]
Comprehension test > Questions table issue
1. Add a heading for the questions table (similar to eligibility test table) > Heading text : Comprehension test questions
2. Questions table should be same as eligibility test table

Questions table for comprehension test

![cmp11](https://user-images.githubusercontent.com/71445210/106102144-f467cf80-6164-11eb-9571-3083a50bfbcd.png)

Questions table for Eligibility test

![eligibility1](https://user-images.githubusercontent.com/71445210/106102196-0ba6bd00-6165-11eb-91c7-ccae2702b8e3.png)

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
