### ISSUE TITLE
[SB] Comprehension Test > Reduce the width of the text field of 'Minimum score needed to pass' to match with that of the radio buttons field at the top

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3055]
Comprehension Test > Reduce the width of the text field of 'Minimum score needed to pass' to match with that of the radio buttons field at the top

![cmp12](https://user-images.githubusercontent.com/71445210/106102739-d8b0f900-6165-11eb-9853-3272beeae8ef.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please check and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this fix is deployed in dev environment, kindly test and update the ticket

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
