### ISSUE TITLE
[SB] App level notification > Create/Edit/Resend notification > App dropdown > Reduce the width to match with date field above it

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3058]
App level notification > Create/Edit/Resend notification > App dropdown > Reduce width to match with date field above it

![notification111](https://user-images.githubusercontent.com/71445210/106123500-ff7c2900-617f-11eb-8c57-4d7578acc6f0.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
