### ISSUE TITLE
[SB] Studies tab > Create/Edit study > Study Information > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3059]
Studies tab > Create/Edit study > Study Information > Align Upload button with the bottom of the image thumbnails, as given in Invision 

![info1](https://user-images.githubusercontent.com/71445210/106125533-4b2fd200-6182-11eb-9fca-bddab1621540.png)

**Comment by pujithr** [comment]
To test in DEV Env

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
