### ISSUE TITLE
[SB] Consent > Auto-created consent document > Reduce the font size of the title

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3060]
SB > Consent > Auto-created consent document > Reduce the font size of the titles of the consent sections in the auto-created document. They should proportional to the font size of the section's content.

![consent111](https://user-images.githubusercontent.com/71445210/106122843-2ede6600-617f-11eb-82c4-630b42ca6210.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in Dev environment, kindly test and update this ticket

**Comment by Lathan-btc** [comment]
Issue is fixed for the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev environment and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
