### ISSUE TITLE
[deployment] Pin terraform provider version

### ISSUE THREAD

**Issue by alanhughes** [GoogleCloudPlatform/fda-mystudies#3061]
**Describe the bug**
In the 2.0.0 release of the kubernetes terraform provider, the `load_config_file` parameter was removed. Since the version of the provider is not pinned in `./deployment/terraform/kubernetes/main.tf`, the latest 2.x version is downloaded, and the resultant terraform plan fails

**To Reproduce**
1. Run terraform init/apply in the `./deployment/terraform/kubernetes/` folder
2. See the error 
```
Error: Unsupported argument

  on main.tf line 36, in provider "kubernetes":
  36:   load_config_file       = false

An argument named "load_config_file" is not expected here.
```
As documented [here](https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v2.0.0), the load_config_file attribute was indeed removed in version 2.0.0

**Expected behavior**
`terraform plan`/`apply` runs successfully

**Desktop (please complete the following information):**
 - OS: macOS
 - `terraform version`
 ```
Terraform v0.12.29
+ provider.google v3.54.0
+ provider.google-beta v3.54.0
+ provider.kubernetes v1.13.3
```

**Comment by dhanyak-btc** [comment]
@mohangmk Please close this issue if it's fixed.

**Comment by mohangmk** [comment]
@moschetti 
Can we close this issues, as this issue was handled as part of PR#3144 and also merged in Develop branch?
Note:
We have tested the change by creating a new environment in our system and GKE cluster is created without any issues.
