### ISSUE TITLE
Multiple record for same study in studyState endpoint

### ISSUE THREAD

**Issue by naveenr-btc** [GoogleCloudPlatform/fda-mystudies#3071]
The studyState needs to send only the latest state of the study in the studySate endpoint. The front end application has no way to determine which among those should be used if multiple records are coming
![unnamed](https://user-images.githubusercontent.com/59356289/106239173-2857f900-6228-11eb-8e69-35420decfbce.png)

**Comment by aswinijena100** [comment]
Issue fix verifed by Mobile team and found to be working fine. PR raised for the same and merged with develop
