### ISSUE TITLE
[SB] Remove tooltip when user mouse hovered on the following

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3072]
1. App-level notification > Create/Edit/Resend notification > App dropdown
2. Manage users > When user mouse hovered on the data present under 'NAME' and 'EMAIL ADDRESS' column
3. Studies tab> Data present under the' STUDIES NAME' column
4. Studies > Eligibility > Eligibility test questions table > data present under 'QUESTIONS' column
5. Studies > Eligibility > Add/edit question > Pass/Fail dropdown
6. Studies > Consent section > Add/edit consent > Default options > 'Topic' dropdown
7. Studies > Comprehension test > Comprehension test questions table > data present under 'QUESTIONS' column
8. Studies > Comprehension test > Edit/Add Comprehension Test Question > Correct answers dropdown
9. Studies > Questionnaires > data present under 'Title' column 
10. Studies > Active tasks > data present under 'Title' column 

![app id](https://user-images.githubusercontent.com/71445210/106245853-33fced00-6233-11eb-8116-fa83dd8e2572.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test in dev

**Comment by Lathan-btc** [comment]
@navya-BTC Issue is fixed for the above scenarios but needs to be fixed for the following
1. Questionnaires > Question level attribute > Response type dropdown
2. Questionnaires > Question level attribute > Add response data to line chart on app dashboard > 'Time range for the chart' dropdown
3. Questionnaires > Question level attribute >Use response data for statistic on dashboard > 'Stat type for image upload' dropdown
4. Questionnaires > Question level attribute >Use response data for statistic on dashboard > 'Formula for to be applied' dropdown

[Note : Issue should be fixed for both question step and form step]

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
