### ISSUE TITLE
[iOS] Sign up flow > OS suggestions for password disrupting user flow 

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3073]
During sign-up, there are OS-triggered password/Keychain suggestions is interfering with the user flow as it is not easy to use or dismiss them and get back the default keypad to type in a password. The user gets stuck occasionally when this happens and needs to go a screen back and revisit the screen again to load it afresh and try again.  Issue is not reproducible every time but more often when a new version of the app is installed on the device and used for the first time.  Marking it as 'under observation' for QA to replicate exact steps for it.

**Comment by SR-btc** [comment]
![13](https://user-images.githubusercontent.com/63093896/106264906-4afc0900-624c-11eb-9a8f-10faca9de286.jpg)
![12](https://user-images.githubusercontent.com/63093896/106264909-4c2d3600-624c-11eb-9bef-b17f6a389ce3.jpg)

**Comment by nishit-v** [comment]
Verified the above issue in V1.0(171) - Testflight unable to reproduce in iPhone XS Max 14.3 iOS version.

Verified the probable fix in the V1.0(170) - Firebase, working fine with no issues.

@SR-btc Please verify the same in V1.0(170) - Firebase build. Thanks

**Comment by SR-btc** [comment]
Issue could not be observed in latest build

**Comment by nishit-v** [comment]
Re-opening this issue as PR is not raised for this ticket.

**Comment by nishit-v** [comment]
Issue is not reproducible in latest QA gateway build V1.0(189) and standalone build V1.0(190).
