### ISSUE TITLE
[iOS] Sign up > Keypad for password fields does not appear immediately

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3074]
During sign up, tap on the password or confirm password fields. Notice that the keypad does not come up immediately and the screen shows a blank space in the keypad area instead. The keypad shows up after some delay . 

EB - keypad should show up immediately once you tap on the field

**Comment by SR-btc** [comment]
Issue found on iPhone XS, iOS 14.2 - apparently not happening on every device/OS version. Marking as 'under observation' for QA to report reproducibility and devices/OS it was found on. Fix can be arrived at accordingly.

**Comment by nishit-v** [comment]
Verified the above issue in V1.0(171) - Testflight unable to reproduce in iPhone XS Max 14.3 iOS version.

Verified the probable fix in the V1.0(170) - Firebase, working fine with no issues.

@SR-btc Please verify the same in V1.0(170) - Firebase build. Thanks

**Comment by SR-btc** [comment]
Issue could not be observed in the latest build

**Comment by nishit-v** [comment]
Re-opening this issue as PR is not raised for this ticket.

**Comment by nishit-v** [comment]
Issue is not reproducible in latest QA gateway build V1.0(189) and standalone build V1.0(190).
