### ISSUE TITLE
[SB] Make account setup link expiry time configurable 

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3077]
The account setup link sent over email to users invited to the Study Builder has a hardset expiry of 48 hours. Make this configurable and have the application read the configured value for use at runtime.  

Also, ensure the text of the email is updated to correctly reflect this value as well.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
