### ISSUE TITLE
[iOS] [Android] Standardize case usage for text across screens

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3082]
Standardize case usage for text across screens removing capitalization where not necessary

**Comment by Lathan-btc** [comment]
@naveenr-btc Issue should be fixed for all the buttons ( eg: OK, SIGN OUT, CANCEL, EXIT, NEXT, SKIP etc..) and placeholders.

**Comment by nishit-v** [comment]
@GovindPrasadBostonTechnologyCorporation 
1. Signup page - `Terms` and `Privacy Policy` should be changed to `terms` and `privacy policy` in 'I agree to the Terms and Privacy Policy'

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev V1.0.225

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V1.0(241)
