### ISSUE TITLE
[SB] Add/Edit Comprehension test question > Wrong section is getting highlighted

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3089]
Steps
1. Add/Edit study
2. Go to the comprehension test section
3. Click on add/edit comprehension test question and observe 

AR : 'Study information' section is getting highlighted
ER : 'Comprehension test' section should be highlighted.

![cmp3](https://user-images.githubusercontent.com/71445210/106308528-d8f4e580-6286-11eb-944e-76417ac0a22b.png)

![cmp4](https://user-images.githubusercontent.com/71445210/106308544-ddb99980-6286-11eb-8527-dd414053e22a.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in QA instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
