### ISSUE TITLE
[iOS][Android} App intermittently shows wrong message when invalid token is entered

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3093]
In the token entry step of the study, if the user enters an invalid token, the message displayed is sometimes 'Unknown token' and sometimes a proper descriptive message of 'Sorry, this is not a valid token.....'. The latter must be shown consistently each time an invalid token is entered. 

For expired token, use EC_0066 is to be used.

Issue observed on iOS but to be verified for Android as well if the message is from the server.

**Comment by naveenr-btc** [comment]
This needs to be sent from backend.

**Comment by chiranjibi009** [comment]
@SR-btc Please test this issue fixes in dev environment and and update.

**Comment by nishit-v** [comment]
Issue is resolved now in Dev instance.

Error message "Sorry, this token is invalid. Please enter a valid token to continue." is displaying on entering Invalid token

**Comment by nishit-v** [comment]
Also verified in iOS build V1.0(171) to show only backend error message and not hardcoded error messages. Working fine in latest build.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA environment. If fixed close the issue

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
