### ISSUE TITLE
[SB] User is not able to create activities with Anchor date based schedule type and custom schedule frequency 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3094]
Steps 
1. Click on Add/Edit questionnaire
2. Navigate to the Schedule tab
3. Select 'Anchor date based' schedule type  
4. Select a Custom schedule frequency
5. Enter from date ( Enter X value) and press Enter
6. Observe

AR : Time picker field is hidden and the user is able to create an activity without entering a time 
ER : Time picker field should not be hidden

[Note : Issue should be fixed for both Questionnaires and Active tasks]

https://user-images.githubusercontent.com/71445210/106427655-bf71ba80-648d-11eb-90de-4ba06d31b8f8.mp4

**Comment by madhurya-btc** [comment]
@Lathan-btc please test in dev instance and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Madhud5** [comment]
Hi @Lathan-btc we have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
