### ISSUE TITLE
[Mobile] Unable to delete user account

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3095]
Unable to delete a user account in mobile

![image](https://user-images.githubusercontent.com/71445210/106448532-e8ec0f80-64a8-11eb-89b7-1da04e5a2f0e.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue and update

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in QA.
