### ISSUE TITLE
[SB] Default images are not displayed for thumbnail and overview in Study builder

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3097]
Note:- Issue is happened in automated deployment

![image](https://user-images.githubusercontent.com/60500517/106452243-9eb95d00-64ad-11eb-88d9-f5adeb63e0b6.png)

![image](https://user-images.githubusercontent.com/60500517/106452350-c3153980-64ad-11eb-895b-36b49b7a92fa.png)

**Comment by aswinijena100** [comment]
@nagarjunav1 Fix deployed in dev and please test .

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc @nagarjunav1 This issue's milestone changed to 2.0.2 now. Please test and close this issue if it fixed while retesting release candidate

**Comment by jkrogers18** [comment]
Release 2.0.2 is merged. If this is fixed, lets close. Otherwise we can move to the next milestone.

**Comment by nishit-v** [comment]
Fixed in 2.0.2 release candidate branch. Verified in QA and Dev Instance.
