### ISSUE TITLE
[SB] Comprehension test > Comprehension test questions table is displayed when 'No' radio button is selected

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3098]
AR : Comprehension test > Comprehension test questions section is displayed when the 'No' option is selected
ER : The comprehension test questions section should not be displayed when the 'No' radio button is selected

[Note : Issue happens only when the user enters the 'Comprehension test' page for the 1st time]

**Comment by nagarjunav1** [comment]
![image](https://user-images.githubusercontent.com/60500517/106453255-045a1900-64af-11eb-86f7-65166d863419.png)

**Comment by pujithr** [comment]
@Lathan-btc please test in Dev Env and confirm if it's working fine

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
To Test in QA ENV

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
