### ISSUE TITLE
[SB] App-level notifications > Actions buttons are non functional

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3101]
App-level notifications >Actions buttons are non functional

![notify1](https://user-images.githubusercontent.com/71445210/106467597-e4345500-64c2-11eb-8000-b2269b7584c1.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
