### ISSUE TITLE
[PM] Need to fix the UI of logo in error page

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3104]
A/R:- Currently app is shown some text in place of customer logo
E/R:- Text need to be replaced with customer logo as per design 

![image](https://user-images.githubusercontent.com/60500517/106480486-780d1d80-64d1-11eb-8307-cda6f3db1a85.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @nagarjunav1 i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
