### ISSUE TITLE
[SB] Questionnaires/Active tasks > Issue in custom schedule

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3105]
Steps
1. Add/edit questionnaire 
2. Navigate to the Schedule tab
3. Select Regular/Anchor date based and select the Custom schedule
4. Enter more than 1 time slots
5. Click on the Save/Done button
6. Go to the Edit questionnaire page
7. Navigate to the Schedule tab
8. Change the schedule type (Anchor date-based/Regular)  and observe the fields data

AR : Previously entered and fields are displayed
ER : Previously entered data should not be displayed

[Note : Issue should be fixed in questionnaires and activities]

https://user-images.githubusercontent.com/71445210/106491205-a17f7680-64dc-11eb-977b-a06eb49f181d.mp4

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in dev env, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
@harisboston Issue should also be fixed for Daily frequency.

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
Unable to test due to #3264 . Will be tested once the blocker issue is fixed in QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance
