### ISSUE TITLE
UI issue: forgot password label uneven in PM

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#3106]
Forgot password text in PM is overlapping

**To Reproduce**
1. Launch PM app
2. In sign-in screen check Forgot password label
3. Forgot password label is uneven in the UI

**Expected behavior**
Forgot password label to be in a single line.

**Comment by harisboston** [comment]
@sharathblr Fix id deployed in dev environment, kindly test and update this ticket

**Comment by nishit-v** [comment]
Issue is resolved in QA and Dev.
