### ISSUE TITLE
Add/Edit questionnaires > Question step/Form step > Question level attributes > Text case usage issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3112]
Add/Edit questionnaires > Question step/Form step > Question level attributes >Use response data for statistic on dashboard > Formula for to be applied > Observe the data selected from the dropdown
AR : 1st letter of each word in a sentence started with capital letters
ER : Standardize the text case usage

![formula](https://user-images.githubusercontent.com/71445210/106627192-8ecd7600-659e-11eb-8117-e22be81ea4ea.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA Instance.
