### ISSUE TITLE
[SB] Revise roles managed via UI

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3113]
On the Study Builder, remove project lead and coordinator roles, introduce superadmin role to be managed via the UI

Remove the project lead and coordinator roles from the Role dropdown in the Manage Users screen
Replace the dropdown values with Superadmin and Study Admin roles
Refresh the Role column in the Manage Users list screen to show the new role values and not the project lead/coordinator roles.

Superadmins will have all permissions in the system including the Manage Users permission. 
Study Admins will not have the Manage Users permission and will have a subset of  the other permissions for managing study and notifications content as assigned to them by the superadmins. 
Ensure existing users are all re-assigned with the Study Admin role.
Update audit logs code to have the user role captured from the user table in the database.

**Comment by SR-btc** [comment]
Some more points:
- Add an info icon next to the Role field. 
- Retain other functionality that is currently available for the superadmin (e.g. enforce password change for all users)
- The Users permission row in the Permissions table in the UI can be removed as only superadmins will be able to manage users

**Comment by Kantharajut-btc** [comment]
@SR-btc updated dev db to make existing non superadmin users to be re-assigned with the Study Admin role.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and update the ticket accordingly

**Comment by Lathan-btc** [comment]
@Kantharajut-btc Users > Filter by role > filter by using any values > Click on any other tabs and again switch to Users tab > Filter the values and observe > Selected value from the filter dropdown is not displayed

![users11](https://user-images.githubusercontent.com/71445210/108502680-2c33e400-72d9-11eb-9efe-7530978d4d9e.png)

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in Dev.

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in QA, please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.

**Comment by Kantharajut-btc** [comment]
Reopened issue to modify script for existing users

**Comment by aswinijena100** [comment]
Issue is resolved in the latest QA instance. And PR raised for the same with script change
