### ISSUE TITLE
[SB] Provision for import/export of studies

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3114]
Allow study admins to do the following (based on permissions)

- Export a study from the SB and be able to import into another version-compatible MyStudies environment's SB -the study must will get created in draft state in the destination environment and will need to be assigned a new Study ID and made content-complete before it can be launched or published

Notes:
- the newly created study must have all metadata and user-created data carried over from the origin study
- implementation should ideally be extensible and flexible enough to accommodate new SB features that get added over time

**Comment by dhanyak-btc** [comment]
@SR-btc Please split this into 2 issues - one for study replication, and another for import/export feature.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this enhancement is implemented in dev, please test and update the ticket accordingly.

**Comment by navya-BTC** [comment]
@Lathan-btc @nishit-v please test this enhancement in QA

**Comment by nishit-v** [comment]
Feature is implemented in QA.
