### ISSUE TITLE
[PM] '+' icon is not displayed in edit admin details screen 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3116]
Issue observed in automated QA environment

![image](https://user-images.githubusercontent.com/60500517/106719187-02679580-6628-11eb-871a-412a2f479362.png)

Note:- Due to the above issue unable to provide the site or study level permissions

**Comment by Madhud5** [comment]
Hi @nagarjunav1 i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
