### ISSUE TITLE
[PM] Unable to download email template

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3118]
Steps
1. Sites tab > Click on any one of the closed study
2. Navigate to site participant registry
3. Click on Add participant 
4. Click on 'Download template' 

AR : User is unable to download the template
ER : User should be able to download the email template 

[Note : Issue observed only in automated deployment branch]

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest automated deployment QA branch
