### ISSUE TITLE
[SB] Unable to delete active tasks

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3119]
User is unable to delete active tasks

[Note : Issue observe only in automated deployment branch]

![at](https://user-images.githubusercontent.com/71445210/106735577-701cbd00-663a-11eb-8aed-0b5d64d6c554.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
@madhurya-btc Issue is reproducible in the latest automated deployment QA branch


![delete11](https://user-images.githubusercontent.com/71445210/106998793-14257600-67ab-11eb-9474-72c5b531e307.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
