### ISSUE TITLE
[SB] Unable to create 'Tower of Hanoi' active task with Custom schedule

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3120]
User is not able to create a 'Tower of Hanoi' active task with Custom schedule

![at1](https://user-images.githubusercontent.com/71445210/106736979-2208b900-663c-11eb-8341-be6d33c87f22.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest automated deployment QA branch.
