### ISSUE TITLE
[SB] Study settings > Platform(s) supported  > Issue when only IOS platform is selected 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3121]
Steps
1. Create study/Edit study
2. Navigate to the study settings page 
3. Platform(s) supported > Select IOS and click on mark as completed
4. Go back to the study settings page and click on the mark as completed button and observe

AR : User is not able to navigate to next page and getting validation message
ER : User should navigate to next page of the study creation flow

https://user-images.githubusercontent.com/71445210/106742872-9a26ad00-6643-11eb-8575-ea620e658c66.mp4

**Comment by pujithr** [comment]
To Test in DEV ENV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA test instance.

**Comment by harisboston** [comment]
@Lathan-btc Kindly close this issue, as it is already tested in both Dev and QA environment.
