### ISSUE TITLE
[SB] Consent section > Default option > Issue in 'Title' drop down

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3122]
Steps
1. Create/ Edit study 
2. Click on add consent > Default options > Select a value from the drop-down and click on Save or Done button
3. Click on edit consent  > Select the custom radio button and create a consent
4.  Click on add consent 
5. Click on 'Topic' dropdown and observe > previously selected option is disabled

AR : Previously selected option from the drop-down is disabled 
ER : Option should not be disabled

https://user-images.githubusercontent.com/71445210/106745900-c5130000-6647-11eb-8e4e-e4af0ce2f06a.mp4

**Comment by pujithr** [comment]
To Test in DEV ENV

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
Issue is resolved in QA Instance.
