### ISSUE TITLE
[SB] Overview page > alternate image issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3123]
AR : Overview page > altermate image > uploade an image > remove image > again upload the same image and observe > image is not uplaoding
ER : Image should be saved /uploaded

[Note : Issue is observed only in automated deployment branch]

https://user-images.githubusercontent.com/71445210/106747297-b7f71080-6649-11eb-94c5-6d283e6c1d77.mp4

**Comment by pujithr** [comment]
To Test in DEV ENV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
