### ISSUE TITLE
Participant Datastore issues on Spring Tool Suite  Version: 4.8.0.RELEASE

### ISSUE THREAD

**Issue by dhanyak-btc** [GoogleCloudPlatform/fda-mystudies#3124]
Unable to start the applications on IDE Spring Tool Suite 4   Version: 4.8.0.RELEASE

Below changes are required to fix the issue and for consistency with other services like auth server and participant manager datastore.

1. Migrate the Spring Boot version to 2.2.6.RELEASE for consistency
2. Remove Spring Security dependency and it's configuration as we are using Hydra for resource access
3. Remove log4j.xml and configure logging in `application.properties` for consistency

This issue is applicable to user-management, enrollment, consent services and response server.

**Comment by aswinijena100** [comment]
PR raised for this change and merged with develop
