### ISSUE TITLE
API Documentation using Spring Fox library

### ISSUE THREAD

**Issue by dhanyak-btc** [GoogleCloudPlatform/fda-mystudies#3125]
1. Add ` @Api` to Controller classes
2. Add `@ApiOperation` to API endpoints
3. Add `SwaggerGeneratorTest `class to generate the` openapi.json` under` fda-mystudies/documentation/API/<service-context-path>/`

Related Issue #2976

**Comment by harisboston** [comment]
@aswinijena100 @nishit-v Kindly validate the study datastore API for QA environment and close this issue.
[study datastore API](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/develop/documentation/API/study-datastore/swagger.json)
[swagger editor](https://editor.swagger.io/)

**Comment by aswinijena100** [comment]
PRs for all the services raised for swagger documentation.
