### ISSUE TITLE
[SB] User is able to change the supported platforms after launching the study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3133]
Steps
1. Click on Create study
2. Study settings > Select only IOS/Android platform
3. Enter all the mandatory sections and launch the study successfully
4. Click on edit study
5. Go to the study settings section and try to select the Android/IOS platform also

AR : User is able to select the Android/IOS platform and able click on mark as completed button
ER : Both the checkboxes should be disabled once the study is launched

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and update the ticket accordingly

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
