### ISSUE TITLE
Add/Edit questionnaire > Reorder of questions is not working

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3135]
Add/Edit questionnaire > Reorder of questions is not working

https://user-images.githubusercontent.com/71445210/107198858-a8960f80-6a1b-11eb-87ae-8da376734991.mp4

**Comment by pujithr** [comment]
To Test in DEV ENV

**Comment by Lathan-btc** [comment]
Issue is fixed on the latest Dev instance.

**Comment by pujithr** [comment]
Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA enviornment.
