### ISSUE TITLE
[SB] Questionnaires > Add/Edit form step questionnaire > 'info' icon issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3136]
Questionnaires > Add/Edit form step questionnaire > 'info' icon issue > make consistancy of info icon

![isuu1](https://user-images.githubusercontent.com/71445210/107208025-054af780-6a27-11eb-82ef-d81e98454bf6.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in QA Instance.
