### ISSUE TITLE
[SB] User is not able to navigate to overview page for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3137]
Steps
1. Create/Edit study
2. Navigate to the 'Study settings' page
3. Select only the 'Android' platform
4. Click on the 'Save' button
5. Click on the 'Mark as completed' button and observe

AR : Page is continuously loading
ER : User should be able to navigate to the Overview page

[Note : Issue observed only in automated deployment branch]

https://user-images.githubusercontent.com/71445210/107328017-130a8680-6ad4-11eb-8194-4dc7ae3b7ba9.mp4

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest automated deployment branch
