### ISSUE TITLE
[SB] Add/Edit questionnaire > Questions are not removing from the list when the user clicks on delete questions  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3139]
Steps
1. Create/Edit study 
2. Navigate to the study settings tab
3. Select only IOS/Android platform and click on the Mark as completed button
4. Navigate to the questionnaires section 
5. Click on add/edit questionnaires 
6. Add Instruction step/Question step/Form step and try to delete the added question

AR : Questions are not removing from the list when the user clicks on delete questions but a success message is getting displayed 
ER : User should be able to delete the questions successfully

https://user-images.githubusercontent.com/71445210/107332201-dfcaf600-6ad9-11eb-80e9-c4f339aedf28.mp4

**Comment by chiranjibi009** [comment]
@Lathan-btc I have checked this issue. Its working fine from my end.
Please test from your end and update.

**Comment by Lathan-btc** [comment]
@chiranjibi009 I have updated the steps in the description, please check.

**Comment by harisboston** [comment]
@Lathan-btc  Fix is deployed in dev environment, kindly test and update this ticket.

**Comment by nagarjunav1** [comment]
Issue is resolved in latest DEV deployment

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest automated deployment QA branch.
