### ISSUE TITLE
[SB] Users > Account status should be consistent 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3140]
Users > Account status should be consistent 

https://user-images.githubusercontent.com/71445210/107357517-2deef200-6af8-11eb-9c76-6e7bef742487.mp4

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm this issue

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by nishit-v** [comment]
Issue is resolved in QA instance.
