### ISSUE TITLE
[SB] Account status is not displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3141]
Steps
1. Navigate to the Users tab
2. Add a new user
3. Mouse hovered on the status toggle button of an added user and observe the status

AR : Status is displayed as 'Account'
ER : 'Account status: Invitation sent, pending activation' should be displayed

![status11](https://user-images.githubusercontent.com/71445210/107371696-95ae3880-6b0a-11eb-9de5-d8438899e6d9.png)

**Comment by nishit-v** [comment]
Issue is resolved in QA instance.
