### ISSUE TITLE
[Mobile apps} Use local text message for consent confirmation

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3146]
For the text that was earlier being captured in the e-consent form field on the Study Builder, since this section is now removed- the mobile app will instead use a hardcoded (and not API-based) confirmation popup that says ‘By tapping on Agree, you confirm that you have reviewed the consent document and agree to participate in the study.’

**Comment by SR-btc** [comment]
QA to verify consent functionality once this is fixed.

**Comment by SR-btc** [comment]
Related ticket #3149

**Comment by Lathan-btc** [comment]
Issue is fixed for Android.

**Comment by nishit-v** [comment]
Issue is resolved in iOS builds - v1.0(181) Gateway build and v1.0(182) Standalone build - Dev Instance.

**Comment by Lathan-btc** [comment]
@naveenr-btc Issue is fixed for the latest QA Android build.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA build V1.0(189) - iOS
