### ISSUE TITLE
[Mobile app] Allow users to rejoin studies

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3147]
Since the study setting related to rejoining studies was removed from the study builder, the mobile app must be modified to not have dependence on the API for this and must always allow users to rejoin studies they have withdrawn from.

**Comment by SR-btc** [comment]
Once this is fixed, QA team to verify users are able to rejoin studies after withdrawal

**Comment by Lathan-btc** [comment]
Issue is fixed for Android.

**Comment by nishit-v** [comment]
@GovindPrasadBostonTechnologyCorporation Unable to rejoin closed study after withdrawing

Steps:
1. Join any closed study
2. Participant enrolled successfully
3. Withdraw from the study
4. Enable and send invitation for the same site
5. Try to enroll into the study
6. Observe continuous loading animator post digital signature flow

Issue not observed for Open study and Closed study having eligibility test.

**Comment by nishit-v** [comment]
Issue is fixed in iOS - Dev Instance V1.0(183)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build for Android  V1.0(70)

**Comment by nishit-v** [comment]
Issue is resolved in latest QA gateway iOS build V1.0(189) .

Verified for Open Study, Closed study and closed study with Elgibility test.
