### ISSUE TITLE
[Mobile Apps} Use local text messages for study withdrawal

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3148]
Since the study data deletion settings (on withdrawal from the study) were removed from the Study Builder, the mobile app must be modified to remove the dependence on APIs to get these settings and associated alert text.

The mobile app must handle the different scenarios as follows:
1. If user is withdrawing from a specific study in the gateway app, they should see only one confirmation alert (with the message 'Are you sure you want to leave the study?') and Yes, Cancel buttons. On confirmation, the app proceeds to withdrawing the user from the study.
2. If user is withdrawing from the study in a standalone app (which also means deleting app account), they should see only one confirmation alert (with the message 'Are you sure you want to leave the study? This will also delete your app account.') and Yes, Cancel buttons. On confirmation, the app proceeds to withdrawing the user from the study as well as deleting app account.
3. If the user deletes their app account in a gateway app, the current behavior is that an intermediate confirmation screen comes up that will display a list of studies which they are enrolled along with the data-retention setting per study. This screen will be modified to remove the study list and just show only the following text ‘You have chosen to delete your app account. This will result in automatic withdrawal from the studies you were enrolled in.’ The buttons can be same as before.

**Comment by Lathan-btc** [comment]
@naveenr-btc Tested the android gateway app. Points 1 and 3 are tested and fixed in the gateway app.

**Comment by nagarjunav1** [comment]
Tested the android Standalone app. Point 2 is tested and fixed in dev

**Comment by nishit-v** [comment]
@GovindPrasadBostonTechnologyCorporation 

Point 1 and 2 tested in iOS (v1.0(181) Gateway build and v1.0(182) Standalone build - Dev Instance.) and fixed.

Point 3 text needs to be updated in Delete Account screen

Actual: 'You have chosen to delete your App Name account. This will result in automatic withdrawal from the studies you were enrolled in.'

Expected: 'You have chosen to delete your app account. This will result in automatic withdrawal from the studies you were enrolled in.'

Refer screenshot:
![unnamed](https://user-images.githubusercontent.com/60386291/109460710-06e86800-7a87-11eb-90e9-ba8a6943adb0.png)

**Comment by nishit-v** [comment]
Point 3. Issue is resolved in latest Dev Instance v1.0(183) - iOS

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA Android build.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA gateway iOS build V1.0(189) and standalone iOS build V1.0(190).
