### ISSUE TITLE
[SB} Remove field for consent confirmation text 

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3149]
On the Study Builder, we no longer capture the consent confirmation text in the Consent section. This text is to be placed and used directly in the mobile app. Thus the field can be removed from the database and corresponding API.

Also, see #3146

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
