### ISSUE TITLE
[PD] [RD} Modifications for removed settings

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3151]
Since the data-retention setting was removed from study settings in the Study Builder, the Participant Datastore and Response Datastore APIs and code must be modified to no longer have any data-retention flag driven functionality when participants withdraw from a study. 

 In case of standalone studies or gateway apps, account deletion on the app is accompanied by withdrawal from study(ies).  While the above mentioned changes should apply to withdrawal in such cases, account deletion itself should continue to work as before as an action independent of withdrawal.

Once the changes are made, the corresponding audit logs must be modified as well.

**Comment by madhurya-btc** [comment]
@nishit-v @Lathan-btc Please test Deactivate and Withdrawl flow

**Comment by nagarjunav1** [comment]
Issue is fixed in Dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
