### ISSUE TITLE
Allow right click on Study Builder login page

### ISSUE THREAD

**Issue by brainsnorkel** [GoogleCloudPlatform/fda-mystudies#3152]
**Describe the bug**

Right-clicking on the login page for study builder pops a modal dialog that says "Right click has been disabled."

**To Reproduce**

1. Go to study builder login page
2. Right-click anywhere

**Expected behavior**

I would like to be able to use the mouse to right-click -> paste usernames and passwords from a password manager.

Notably, participant manager does not prevent right click in the same way.

**Screenshots**

<img width="581" alt="image" src="https://user-images.githubusercontent.com/17165/107461120-6b618700-6bad-11eb-82f1-16ef427c8a58.png">

**Desktop (please complete the following information):**

 - OS: MacOS Catalina 10.15.7
 - Browser Safari
 - Version 14.0.3

** Background **

common.js seems to prevent a few innocuous-seeming interactions: 

```javascript
          $(document).on("contextmenu", function (e) {
            e.preventDefault();
            alert("Right click has been disabled.");
            return false;
          });

          document.onkeypress = function (event) {
            event = (event || window.event);
            if (event.keyCode == 123) {
              alert("This action is disabled.")
              return false;
            }
          }

          document.onmousedown = function (event) {
            event = (event || window.event);
            if (event.keyCode == 123) {
              alert("This action is disabled.")
              return false;
            }
          }

          document.onkeydown = function (e) {
            if (e.keyCode == 123) {
              alert("This action is disabled.");
              return false;
            }
            if (e.ctrlKey && e.shiftKey
                && e.keyCode == 'I'.charCodeAt(0)) {
              alert("This action is disabled.");
              return false;
            }
            if (e.ctrlKey && e.shiftKey
                && e.keyCode == 'J'.charCodeAt(0)) {
              alert("This action is disabled.");
              return false;
            }
            if (e.ctrlKey && e.keyCode == 'U'.charCodeAt(0)) {
              alert("This action is disabled.");
              return false;
            }
            if (e.ctrlKey && e.shiftKey
                && e.keyCode == 'C'.charCodeAt(0)) {
              alert("This action is disabled.");
              return false;
            }
          }

        });
```

**Comment by aswinijena100** [comment]
@Lathan-btc Fix deployed in dev , please check and let know if issue fix

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc @nishit-v Please test in QA and close it if fixed

**Comment by nishit-v** [comment]
Issue is resolved in QA instance.

@brainsnorkel This has been handled as part of V2.0.3 release
