### ISSUE TITLE
[SB] modifications for removed settings

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3153]
The following settings functionality has been removed from the study builder and the associated database fields and APIs must be removed/modified as well.
1. allow users to rejoin a study
2. select data retention settings for a study
3.  text to be shown to users when they withdraw from the study

Dev team to also check if there are any APIs related to the Participant Datastore that are impacted by this and modify those as well

Once the above fixes are done, the corresponding audit logs must be modified as well.

Related tickets  #3148, #3147, #3151

**Comment by Kantharajut-btc** [comment]
ALTER TABLE `studies`
	DROP COLUMN `allow_rejoin`,
	DROP COLUMN `allow_rejoin_text`,
	DROP COLUMN `retain_participant`;
@SR-btc removed these columns in dev db as mentioned in the ticket

**Comment by Kantharajut-btc** [comment]
@Lathan-btc kindly create a new study or edit the existing study with study settings changes and check if it is not breaking the existing flow and update the ticket accordingly

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in QA, please check and confirm

**Comment by nishit-v** [comment]
Verified the flow in QA Instance. Working fine.
