### ISSUE TITLE
[SB] Alignment of text in info popups

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3155]
Left-align (not center-align) text within all info icon popup across the SB screens

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV- QA its fixed. Please check and close the issue.

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA and Dev instance.

@Madhud5 PR is not merged for this ticket
