### ISSUE TITLE
[SB] Section title alignment issues

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3156]
SB > All study sections > Move section title slightly to the left to align with other fields on the screen

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV- QA its fixed. Please check and close the issue.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build

**Comment by nagarjunav1** [comment]
Issue is not fixed in latest DEV build

**Comment by Madhud5** [comment]
Hi @nagarjunav1 its fixed in QA pl do check and close this issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in both Dev and QA instances.
