### ISSUE TITLE
[SB] Center-align checkbox text for Account Setup screen

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3157]
Account setup screen > Center-align checkbox text (checkbox along with its text) for the Account Setup screen

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV- QA its fixed. Please check and close the issue.

**Comment by nishit-v** [comment]
Issue is still reproducible in Dev Instance.

![SB_Dev](https://user-images.githubusercontent.com/60386291/109269786-0788c080-7833-11eb-9d90-89535431b77d.png)

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA and Dev instance.
