### ISSUE TITLE
[SB] Correct error text seen when passwords don't match

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3161]
Account setup, change password , forgot password userflows:

Edit error message when passwords don't match in the Enter password, Confirm password fields to 'Passwords do not match'

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV- QA its fixed. Please check and close the issue.

**Comment by nishit-v** [comment]
Issue is still reproducible in Dev instance.

![SB_Dev](https://user-images.githubusercontent.com/60386291/109269544-a2cd6600-7832-11eb-83d0-64df2c87f425.png)

**Comment by nishit-v** [comment]
Issue is still reproducible in Dev Instance.

![SB_Dev2](https://user-images.githubusercontent.com/60386291/109270028-6c441b00-7833-11eb-88dd-aee049df0ba7.png)

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA and Dev instance.

**Comment by nishit-v** [comment]
PR is not merged @Madhud5

**Comment by Madhud5** [comment]
PR merged, please close this issue. @nishit-v

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA and Dev instance. Closing this ticket.
