### ISSUE TITLE
[SB] Modify notification status text

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3165]
SB > App and Study-level notifications > Status column > Correct the status 'Not sent' to 'Scheduled' - in the UI as well as wherever the status is being handled in the code.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in QA, please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
