### ISSUE TITLE
[SB} Correction needed in notifications handling

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3166]
Currently, notifications set up in the SB are picked up on a minutely basis by the scheduler. However, there are scenarios when some of these failed to get picked up the scheduler or communicated to the Participant Datastore. We need to have a fix where the status of notification pick-up is tracked in the database and the ones that fail become part of the pipeline (within a time window) for subsequent pick-up.

**Comment by madhurya-btc** [comment]
@nishit-v @nagarjunav1 @Lathan-btc Please test in dev instance and confirm the same.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by nishit-v** [comment]
Reverified in latest dev instance, working fine and no issues found.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA Instance.
