### ISSUE TITLE
[SB] Create/Edit study > Comprehension test section > Issue in questions table 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3168]
Steps
1. Create/Edit study
2. Navigate to a Comprehension test section
3. Add 2 or more questions ( At least one question should be in draft)
4. Delete any one of the questions and observe the questions which are in the draft version

AR : Questions are not displayed in the draft version 
ER : Questions should not be removed from the draft version

https://user-images.githubusercontent.com/71445210/107613079-9ad7c880-6c6d-11eb-9fc9-1deb1f377b7a.mp4

**Comment by pujithr** [comment]
to test in DEV ENV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.

**Comment by pujithr** [comment]
To test in QA ENV

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
