### ISSUE TITLE
[SB] Tooltip text is not displayed 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3169]
The tooltip text is not displayed for the following 
1. Comprehension test questions table > When user mouse hovered on 'Edit' and 'Delete' icon 

![cmp123](https://user-images.githubusercontent.com/71445210/107615210-c3fa5800-6c71-11eb-8fbf-3cec8562ebc7.png)

2. Add/Edit questionnaire > When user mouse hovered on 'View', 'Edit' and 'Delete' icon 

![quest1](https://user-images.githubusercontent.com/71445210/107614597-9fea4700-6c70-11eb-9396-93989f41b8fd.png)

3. Add/Edit Form step > When user mouse hovered on 'View', 'Edit' and 'Delete' icon

![AFS](https://user-images.githubusercontent.com/71445210/107614764-f22b6800-6c70-11eb-8699-225db56579c0.png)

4. Consent section > Add more than one consent >Delete any one of the consent and user mouse hovered on 'View', 'Edit' and 'Delete' icon
5. Eligibility test / Validation token + Eligibility test > Add more than one questions > Delete any one of the question and user mouse hovered on 'View', 'Edit' and 'Delete' icon
6. Resources > Add more than one resource > Delete any one of the resources and user mouse hovered on 'View', 'Edit' and 'Delete' icon

**Comment by pujithr** [comment]
To test in DEV INS

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
PR is merged. Please test in QA ENV and update ticket

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
