### ISSUE TITLE
[SB] Eligibility section > 'Mark as completed' button is enabled even though created questions are in draft version

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3171]
Steps
1. Create/Edit study
2. Navigate to the eligibility questions tab
3. Click on Add question button
4. Enter all the values and click on the Save button
5. Click on the back button
6. Observe the 'Mark as completed' button 

AR : 'Mark as completed' button is enabled and the user is able to move next page
ER : 'Mark as completed' button should be disabled and tooltip text should be displayed

https://user-images.githubusercontent.com/71445210/107650399-7519e600-6ca4-11eb-9137-fb74ad136c1a.mp4

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
@navya-BTC

 'Mark as completed' button is disabled for the following sceanrio
Eligibility test/Comprehension test > Add more than 1 or 2 questions (Minimum one question should be in the draft and one question should not be in draft) > delete draft version questions > and Observe 'Mark as completed' button

AR : Mark as completed' button is disabled even though no questions are present in the draft version
ER : 'Mark as completed' button should be enabled

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.
