### ISSUE TITLE
[SB] [PM] When logged in with default superadmin credentials should force the admin to change password

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3173]
Current behavior: When logged in with default superadmin(created from script) credentials for SB and PM, default password is being used unless admin manually changes the password

Expected behaviour/approach: When logged in with default superadmin credentials for SB and PM, admins should be forced to change password and navigate to change password post logging in.

Needs to be handled for Study Builder and Participant Manager.

**Comment by nagarjunav1** [comment]
Featured is implemented in latest DEV instance and working fine

**Comment by nishit-v** [comment]
Featured is not implemented for Study Builder 2.0.5 code

**Comment by nishit-v** [comment]
Issue is fixed in RC 2.0.6
