### ISSUE TITLE
[SB] Users > Edit user details > Success message is not displayed when user clicks on Resend activation link

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3176]
Users > Add a super admin/study admin > Edit user details > Success is not displayed when the user clicks on Resend activation link

**Comment by Lathan-btc** [comment]
@SR-btc Please provide a validation message for the above scenario.

**Comment by SR-btc** [comment]
@Lathan-btc please provide the scenario for which the validation message is needed.

**Comment by Lathan-btc** [comment]
Users > Add a super admin/study admin > Edit user details > Success is not displayed when the user clicks on Resend activation link
AR: No success message is displayed
ER: 'Account setup invitation resent' success message should be displayed.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
@Kantharajut-btc Remove the full stop at the end of the success message


![resent](https://user-images.githubusercontent.com/71445210/116562054-7ad8ac80-a920-11eb-9124-deaea7f56dc7.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please retest this issue and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instnce.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
