### ISSUE TITLE
[PM] Password expired error message is displayed when logging in with default superadmin credentials

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3177]
Steps:
1. Login with default superadmin crdentials (updated by script)
2. Observe the error message

Actual: Password expired error message is displayed when logging in with default superadmin credentials

Expected: Should login without any error message

**Comment by aswinijena100** [comment]
@nishit-v Can u please close this ticket as we have a separate ticket #3173 to change this functionality . Please verify and close this

**Comment by smunini** [comment]
Is there a work-around for this issue?  I can't login to the participant manager at all.  I'm trying to change the super admin's password using the create_participant_manager_superadmin.sh script, and when I try to login, I get the message: "Your password has expired. Please use the Forgot Password link to get password help."

**Comment by nishit-v** [comment]
@saminguyen Please find below steps for the workaround until we fix the above issue in next release.
1. Click on 'Forgot Password' in Participant Manager
2. Enter default superadmin email and submit
3. Temporary password will be sent to an email
4. Login with email and temporary password. User will be navigated to Reset password
5. Enter temporary password, new password and confirm password. Password will be reset successfully.

**Comment by smunini** [comment]
Thank you very much, @saminguyen <https://github.com/saminguyen>  for your
response.

I know this is a separate issue, but I'm also having a problem configuring
the email send capability.  I have set the appropriate values in the Secret
Manager, however when I try to use the Forgot Password feature, I get the
error: "Sorry, an error occurred and we could not send you the email .
Please try again later."

Where would be the best place to find a more detailed log message?  I tried
looking in the Logs Explorer, but I didn't find anything that might point
me in the right direction.

**Comment by aswinijena100** [comment]
@nishit-v this is issue is fixed in release candidate environment. Please test and update the issue status

**Comment by nishit-v** [comment]
Issue is resolved now in RC environment.

**Comment by smunini** [comment]
Thank you @nishit-v for the fix, however I can't seem to install v2.0.3 due to this blocking issue:  https://github.com/GoogleCloudPlatform/fda-mystudies/issues/3339.  Any help greatly appreciated.

**Comment by aswinijena100** [comment]
@nishit-v please close this ticket if it is fixed already in QA

**Comment by nishit-v** [comment]
Issue is observed again for 2.0.5 code
