### ISSUE TITLE
[SB] Add/Edit active task > Anchor date based > Select anchor date type dropdown > Previously selected value is displayed for the particular scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3178]
Steps
1. Create/Edit study
2. Navigate to the active tasks section
3. Create/Edit active task
4. Switch to the Schedule tab
5. Select the 'Anchor date based' radio button
6. Select any value from the dropdown click on save
7. Select the 'Select' value from the dropdown and click on the Save button 
8. Observe the value in the dropdown

AR : Previously selected value is displayed
ER : Previously selected value should not be displayed

https://user-images.githubusercontent.com/71445210/107756516-553cfd80-6d4a-11eb-8da2-d846007ae284.mp4

**Comment by pujithr** [comment]
@Lathan-btc please test in DEV ENV and let me know if it's works fine

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
Test in QA ENV and update the Ticket

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
