### ISSUE TITLE
[SB] Create/Edit study > Study settings section > Error message is not displayed if user clicks on 'Mark as completed' button without selecting any platform

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3180]
Steps
1. Create/Edit study
2. Navigate to the 'Study settings' page
3. Don't select any platform and click on the 'Mark as completed' button and observe

AR : Error message is not displayed when the user clicks on the 'Mark as completed' button
ER : 'Please check these box if you want to proceed.' error message should be displayed

[Note : Without selecting any platform, if the user clicks on the 'Mark as completed' button, then the button is disabled, again if the user selects the supported platform(s) even then 'Mark as completed' button is disabled and the user is not able to proceed further. But after clicking the 'Save' button 'Mark as completed' is enabled] 

https://user-images.githubusercontent.com/71445210/107762894-b4ebd680-6d53-11eb-9e2c-99809508515d.mp4

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in dev environment, kindly test and update the ticket.

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
