### ISSUE TITLE
[SB] Replace the current logo with revised image

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3181]
For all screens where the logo appears, replace the current logo with a revised image that does not have 'Customer logo' text. Adjust the UI once the image is replaced to ensure it appears vertically and horizontally aligned in the logo area.

**Comment by Lathan-btc** [comment]
@fahad-kc @fahadbtc-zz Please provide the updated images to the team.

**Comment by fahad-kc** [comment]
Attached the updated logos 
![SB_innerScreen_Logo](https://user-images.githubusercontent.com/75824706/108059773-ffcf5c00-707b-11eb-9c7b-358839c199e1.png)
![SB_Landing_Logo](https://user-images.githubusercontent.com/75824706/108059780-01008900-707c-11eb-993f-6bbf998a23c3.png)

**Comment by pujithr** [comment]
To Test in DEV Ins

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
To Test in DEV Ins

**Comment by nishit-v** [comment]
Issue is resolved in QA and Dev.
