### ISSUE TITLE
[PM] Replace the current logo with revised image

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3182]
For all screens where the logo appears, replace the current logo with a revised image that does not have 'Customer logo' text. Adjust the UI once the image is replaced to ensure it appears vertically and horizontally aligned in the logo area.

**Comment by Lathan-btc** [comment]
@fahad-kc @fahadbtc-zz  Please provide the updated images to the team.

**Comment by fahad-kc** [comment]
Attached the updated logo

![PM_innerScreen_logo](https://user-images.githubusercontent.com/75824706/108059982-49b84200-707c-11eb-8a76-cd58d2222cde.png)
![PM_Login_Logo](https://user-images.githubusercontent.com/75824706/108059990-4b820580-707c-11eb-9372-10f0c46725a7.png)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest dev build

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
