### ISSUE TITLE
[Auth server] Replace the current logo with revised image

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3183]
For all screens where the logo appears, replace the current logo with a revised image that does not have 'Customer logo' text. Adjust the UI once the image is replaced to ensure it appears vertically and horizontally aligned in the logo area.

**Comment by Lathan-btc** [comment]
@fahad-kc @fahadbtc-zz Please provide the updated images to the team.

**Comment by fahad-kc** [comment]
Attached the updated logo

![Uploadin
![PM_Login_Logo](https://user-images.githubusercontent.com/75824706/108061024-b8e26600-707d-11eb-908b-7954e8366774.png)
g PM_innerScreen_logo.png…]()

**Comment by fahad-kc** [comment]
Attached the updated logo

![PM_innerScreen_logo](https://user-images.githubusercontent.com/75824706/108061553-808f5780-707e-11eb-9a0d-959540518d3b.png)
![PM_Login_Logo](https://user-images.githubusercontent.com/75824706/108061558-82f1b180-707e-11eb-9082-200aa01a060b.png)

**Comment by harisboston** [comment]
@Lathan-btc Updated logo image for oauth server in Dev environment and deployed, kindly test and update this ticket.

**Comment by harisboston** [comment]
@Lathan-btc Updated logo image for oauth server in QA environment and deployed, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
