### ISSUE TITLE
[Android] Replace the current logo with revised image

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3184]
For all screens where the logo appears, replace the current logo with a revised image that does not have 'Customer logo' text. Adjust the UI once the image is replaced to ensure it appears vertically and horizontally aligned in the logo area.

**Comment by Lathan-btc** [comment]
@fahad-kc @fahadbtc-zz Please provide the updated images to the team.

**Comment by fahad-kc** [comment]
Shared with android development team.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
