### ISSUE TITLE
[IOS] Replace the current logo with revised image

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3185]
For all screens where the logo appears, replace the current logo with a revised image that does not have 'Customer logo' text. Adjust the UI once the image is replaced to ensure it appears vertically and horizontally aligned in the logo area.

**Comment by Lathan-btc** [comment]
@fahad-kc @fahadbtc-zz Please provide the updated images to the team.

**Comment by fahad-kc** [comment]
Attached the updated logo

![logo1@2x](https://user-images.githubusercontent.com/75824706/108060391-d06d1f00-707c-11eb-9a4c-0e37a7ba42b9.png)
![logo1@3x](https://user-images.githubusercontent.com/75824706/108060400-d2cf7900-707c-11eb-8b20-35016637b959.png)

**Comment by nishit-v** [comment]
Verified in v1.0(181) Gateway build and v1.0(182) Standalone build - Dev Instance. Fixed.

Yet to verify for Splash screen.

**Comment by nishit-v** [comment]
Verified in v1.0(183) Gateway build for Splash screen - Dev Instance. Fixed.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA build V1.0(189)
