### ISSUE TITLE
[SB] Set up password screen > Center align all the fields to the screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3188]
[SB] Set up password screen > Center align all the fields to the screen ( horizontally and vertically)

![img21](https://user-images.githubusercontent.com/71445210/108058603-4459f800-707a-11eb-9425-e4a03cacabd7.png)

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
