### ISSUE TITLE
Study Migration/Automated Creation

### ISSUE THREAD

**Issue by alanhughes** [GoogleCloudPlatform/fda-mystudies#3189]
**What are you trying to accomplish?**
We would like to automate the creation of studies on the mystudies platform, as well as import existing studies from an installation of mystudies using https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System. As an end goal, I would like to be able to write my study configuration in some sort of structured format that I could store in source control, and have a script that either generated the required SQL to insert into the fdahphc database, or that hit the necessary APIs in the right order

**What challenge are you running into?**
At present, I can't get past creating a draft study - simulating a click on the "save" button on the "basic info" page led me [here](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/7627c0ade584a5f1e110fbbe70f983888406961f/study-builder/fdahpStudyDesigner/src/main/java/com/fdahpstudydesigner/controller/StudyController.java#L3083), but attaching a debugger to a locally-running docker container shows that my studySession within the `sesObj` is always null. 

As an aside, some docker-compose files or generally advice for running individual services locally would be great - I had to hack around a bit to stop the study builder from erroring every time it tried to write an audit log entry, it'd be nice to be able to switch that off easily.

**What have your tried so far?**
Here is a rough draft of the python script I've written:
https://gist.github.com/alanhughes/088f1a04435cb1a3e00223d35da656d5

**Comment by SR-btc** [comment]
@alanhughes the v2.0.6 release offers a provision to import and export studies between Study Builders or copy a study into a new one. Please check if that helps with your requirement.

**Comment by SR-btc** [comment]
@aswinijena100 @mohangmk please address this part of the query 
""As an aside, some docker-compose files or generally advice for running individual services locally would be great ""

**Comment by aswinijena100** [comment]
@alanhughes All  services are spring boot applications except study builder and study metadata which is spring MVC applications. To run the spring boot applications u can import these applications into an IDE ,like STS (Spring Tool Suite) as maven project and run as spring boot app after changing the configuration properties in application.properties file. To run Study builder and studymetadata , a server needs to be configured ,like tomcat in IDE. If you does not want to run the application through IDE , you can generate the war file and host it inside tomcat server which is running in you local system.

Please let me know if you need more clarifications in this regard.

**Comment by aswinijena100** [comment]
@alanhughes Hope you issue had been resolved . In case you still facing the issue , please reopen this ticket.
