### ISSUE TITLE
[SB] E-Consent steps > Data sharing permission > User is able to navigate to next page without entering the mandatory fields

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3190]
Steps
1. Create/Edit study 
2. Navigate to Econsent steps
3. Don't enter all the mandatory fields except 'Explanatory text that can be provided in a 'Learn More' section ' field
4. Click on 'Mark as completed' button and observe

AR : User is able to navigate to next page
ER : User should not be able to next page

https://user-images.githubusercontent.com/71445210/108165596-d6184280-7118-11eb-9e9d-cca0f3db000d.mp4

**Comment by Lathan-btc** [comment]
@navya-BTC Issue is still reproducible for the following scenario
E-Consent step > Yes radio button should be selected > Enter all the values into all the mandatory field > in description field enter 2 to 3 lines and click on 'Mark as completed' button again go to E-Consent section and delete the entered data in the description field and click on mark as completed button > user is navigating to the next page.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in QA
