### ISSUE TITLE
[Hydra] Sign in > Entered password is removing 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3204]
Steps
1. Create an account on the mobile app
2. Sign out from the app
3. Go to sign in screen
4. Enter valid email id and password 
4. Click on the Sign-in button and observe

AR : Occasionally entered password is removing
ER : Password should not be removed and the user should be able to log in

[Note : Issue is reproducible for Android, IOS and PM applications]

Refer attached video:

https://user-images.githubusercontent.com/60386291/108475241-73f54400-72b6-11eb-84d8-4dc07682d78f.MOV

**Comment by harisboston** [comment]
@Lathan-btc I tried couple of scenarios, like clearing cache, cookies, but not able to replicate this issue.
Putting this issue under observation, will observe if it happen again or till we get proper steps to replicate this issue.

**Comment by nishit-v** [comment]
Issue is reproducible frequently for below scenario in Mobile. Please find below steps to reproduce (frequency 5/5)

1. Freshly install the mobile app
2. Signup with new user
3. User is navigated to studies list
4. Click on signout. User is navigated to  signin screen
5. Enter valid email and valid password
6. Click on signin
7. Observe password field is removed without any error message

**Comment by aswinijena100** [comment]
@nishit-v can u please test this issue in QA and close if it is not reproducing

**Comment by nishit-v** [comment]
Issue is still reproducible in latest QA Android and iOS mobile builds.

**Comment by harisboston** [comment]
@nishit-v @Lathan-btc  Issue is fixed in Dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Verified the issue in both IOS and Android dev builds and it is fixed.

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in QA environment, kindly test and close this ticket.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA deployment
