### ISSUE TITLE
[SB] Questionnaires/Active Tasks > Custom Schedule > Time picker is not displayed from 3rd run onwards

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3225]
Steps:
1. log in to SB
2. Navigate to add questionnaire/active task
3. Click on the Custom schedule
4. Add 2 runs
5. Click on '+' icon and click on the time picker
6. Observe

Refer attached video

A/R: Time picker is not displayed from 3rd run onwards

E/R: Time picker should be displayed for all runs

[Note : If the user clicks on the + icon of the 2nd row then entered time in the 2nd row] 

https://user-images.githubusercontent.com/71445210/108524610-37950880-72f5-11eb-8243-76abdba5ed7a.mp4

**Comment by pujithr** [comment]
To Test in DEV ENV

**Comment by pujithr** [comment]
PR is merged. please test in QA ENV and update ticket

**Comment by nishit-v** [comment]
Unable to test due to #3264 . Will be tested once the blocker issue is fixed in QA instance.

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
