### ISSUE TITLE
[SB] Resources > Tooltip text is displayed even though resources are not present in the draft version 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3233]
Steps
1. Create/Edit study
2. Navigate to resources section
3. Add a resource in the draft version
4. Delete the added resource
5. Mouse hover on 'Mark as completed' button and observe

AR : Tooltip text is displaying
ER : Tooltip text should not be displayed when the resources are not present in the draft version

![resources](https://user-images.githubusercontent.com/71445210/108697707-33513100-7529-11eb-9a02-0ce410a02fb1.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev Instance.

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
