### ISSUE TITLE
[SB] Standalone > Error message is displayed for App ID on editing study ID

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3247]
**Describe the bug**
Error message is displayed for App ID on editing study ID

**To Reproduce**
1. Login and click on create study
2. Enter all valid details in basic information
3. Select 'Standalone' as study type
4. Click on Mark as complete
5. Navigate to studies
6. Again click on Edit study
7. Edit the Study ID and click on Mark as complete
8. Observe the error message

**Expected behavior**
Error message should not be displayed

**Notes:**
Issue not observed for 'Gateway' study type

**Refer attached video:**

https://user-images.githubusercontent.com/60386291/108820507-47a53480-75e2-11eb-8260-014bab1c679b.mp4

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev environment and update.

**Comment by nishit-v** [comment]
Issue is resolved in Dev instance.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA environment and close if resolved.

**Comment by nishit-v** [comment]
Issue is reproducible again in Dev and QA instance for below scenario:

1. Login and click on create study
2. Enter all valid details in basic information
3. Select 'Standalone' as study type
4. Click on Save
5. Click on Mark as complete
6. Observe the error message



https://user-images.githubusercontent.com/60386291/109467699-95fa7d80-7a91-11eb-881f-cd59d1987dce.mp4

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev environment and update.

**Comment by nishit-v** [comment]
Error message is not displayed for 'App ID' field on using already existing App ID for standalone.

Steps:
1. Create a standalone study let app ID be GCPST01
2. Launch the study
3. Click on create study
4. Select standalone
5. Enter app id which is already used like GCPST01
6. Observe error message is not displayed

**Comment by madhurya-btc** [comment]
@nishit-v Please test all scenarios in dev instance and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
