### ISSUE TITLE
[PM] Signup > Activation link not redirecting to setup account screen and hence unable to signup

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3253]
**Steps:**
1. Add an admin from PM
2. Admin receives the activation link
3. Click on the activation link
4. Observe the redirection page

**Actual:** Activation link redirecting to {{URL}} page

**Expected:** Activation link should redirect to the setup account screen

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
