### ISSUE TITLE
Documentation of manual-ios-deeplink-url is ambiguous

### ISSUE THREAD

**Issue by brainsnorkel** [GoogleCloudPlatform/fda-mystudies#3259]
**Is your feature request related to a problem? Please describe.**

I'm confused about the description of the form and function of this secret... 

```
manual-ios-deeplink-url is the URL to redirect to after iOS login
```

...from here: https://github.com/GoogleCloudPlatform/fda-mystudies/tree/master/deployment#prepare-your-mobile-applications

**Describe the solution you'd like**

I'm no iOS developer, but I think the documentation could be clearer about what this URL is for and what form it should take? I don't see the app redirecting to a URL after login, for instance. Also I don't know if this value is required or what the consequences of misconfiguring it are.

**Priority**

Low

**Labels**

ios

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello @brainsnorkel ,

We have changed the documentation for both Android and iOS in PR - #3882 
Thank you,
Govind
