### ISSUE TITLE
[ios] better documentation of where to obtain API_KEY's ios.apptoken string

### ISSUE THREAD

**Issue by brainsnorkel** [GoogleCloudPlatform/fda-mystudies#3260]
**Is your feature request related to a problem? Please describe.**

The documentation in Default.xcconfig about where to get ios.apptoken to build an API_KEY of the form `<ios.bundleid>:<ios.apptoken>` says that this value should match the ones set in the study datastore server.  

```
// API_KEY is <ios.bundleid>:<ios.apptoken>
// e.g. com.bundleID:axdks
// These values should match the ones set in study datastore server.
// see: study-datastore/src/main/resources/authorizationResource.properties
API_KEY = org.chip.woe.mystudies:aAaAbBbcCdDeE
```

However, the documented place to obtain this value looks like this:

```
ios.apptoken=${IOS_APP_TOKEN}
```

...which isn't all that helpful. The base install documentation and the documentation for [the ios install documentation](https://github.com/GoogleCloudPlatform/fda-mystudies/tree/master/iOS) doesn't talk about where this value comes from either.

**Describe the solution you'd like**

More documentation about how/when ios.apptoken is set, and where to get it from when you reach the iOS app configuration step.

**Priority**

low

**Labels**

ios, study-datastore

**Comment by smunini** [comment]
I'm at this point in the install and am stumped by this one too.  Where can I find this value?  I'm happy to write some documentation if someone can point me in the right direction for this setting.  Thanks!!

**Comment by smunini** [comment]
ios.bundleid can be found in XCode following these instructions:  Open your project with XCode, select the top project item in the project navigator at the left. Then select TARGETS -> General. Bundle Identifier is found under Identity.

ios.bundleid is generally of the form `com.your-company.app-name` and can be anything you wish during development but will need to be the same as you submit to Apple for production use.

Still unsure where to find this ios.apptoken.  @brainsnorkel , do you happen to know where to find this value?

**Comment by brainsnorkel** [comment]
> ios.bundleid can be found in XCode following these instructions: Open your project with XCode, select the top project item in the project navigator at the left. Then select TARGETS -> General. Bundle Identifier is found under Identity.
> 
> ios.bundleid is generally of the form `com.your-company.app-name` and can be anything you wish during development but will need to be the same as you submit to Apple for production use.
> 
> Still unsure where to find this ios.apptoken. @brainsnorkel , do you happen to know where to find this value?

Hi Steve, sorry to be late in replying. 

The strange part is that ios.bundleid _is not_ your com.your-company.appname as the name and comments might indicate, it's a random alphanumeric string. At least that's what it was for me. I'm trying to dig up where that came from, and hope to respond again soon.

The ios.apptoken is from the auto-generated secret here:

```
$ SECRET_PROJECT=${PREFIX}-${ENV}-secrets
$ gcloud --project=${SECRET_PROJECT} secrets versions access latest --secret=auto-sd-ios-token
```

...or you can look at this value in the secrets manager in your -secrets project in the console.

**Comment by smunini** [comment]
Thank you so much Chris!  I was continuing to debug this last night.  Incredibly helpful!! This worked perfectly.

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello @brainsnorkel ,

We have changed the documentation in Default.xcconfig to correct value of API_KEY - auto-sd-ios-id:auto-sd-ios-token in PR #3523 .

Thank you, 
Govind
