### ISSUE TITLE
[SB] Unable to schedule the the Questionnaries in the study

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3264]
Steps:- 
1. Navigate to Questionnaires section of study 
2. Click on add Questionnaire
3. Click on schedule tab
4. Select the different types of scheduling options and verify

Note:- Issue is observed in QA instance only

https://user-images.githubusercontent.com/60386291/109140348-7f4ae280-7782-11eb-8de5-822c61ef2726.mp4

**Comment by harisboston** [comment]
@nagarjunav1 Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
