### ISSUE TITLE
Update audit log for PM replace user term with admin

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#3273]
Need to update the audit log for PM. 

The terms user to be replaced with the admin.

**Comment by Kantharajut-btc** [comment]
@sharathblr this issue is fixed in dev environment, please check and confirm

**Comment by sharathblr** [comment]
@nishit-v / @nagarjunav1 - Can you verify this.

**Comment by nagarjunav1** [comment]
Need to update the Event Codes as well as per requirement and also the description for the Events. Currently only event description has been updated.

**Comment by Lathan-btc** [comment]
@Kantharajut-btc Logs are triggering for the old events, not for the updated events.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
@Kantharajut-btc 
Logs are not triggered for the following events
1. NEW_ADMIN_INVITATION_EMAIL_SENT
2. ACCOUNT_UPDATE_EMAIL_SENT

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
