### ISSUE TITLE
[PM] Password strength meter should be dismissed when password field is cleared

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3276]
**Steps:-** 
1. Enter the Password into the New Password field
2. Wait for the Password strength meter to appear 
3. Clear the Content entered in Step-1
4. Verify whether Password strength meter dismissed

A/R:- Password Strength meter is not disappear once field is cleared
E/R:- Password Strength meter should disappear when field is cleared

Note:- Issue needs to fix wherever Password strength meter appear across application.

**Comment by sujatha-btc** [comment]
Password meter could not be dismissed , can be reset the password meter if the password field is cleared. @nagarjunav1 deployed please test and confirm.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
