### ISSUE TITLE
[SB] Active tasks > Error message is not displayed for 'Activity short title or key'

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3277]
**Steps**

1. Active tasks > Click on Add active task button
2. Enter 'Activity short title or key' with already used short title and observe

AR: An error message is not displayed
ER:  ' < short tile key > has already been used in the past' error message should be displayed.

![Screenshot_4](https://user-images.githubusercontent.com/60386291/109298383-85f85900-7859-11eb-8798-f40d3664d366.png)

**Comment by chiranjibi009** [comment]
@nishit-v Please test the issue in dev and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc  Please test the issue in QA and update.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
