### ISSUE TITLE
Text changes for email templates 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3281]
Text changes should be done for all the email templates as per the updated email templates document.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue for Study Builder, Participant Datastore, Participant Manager Datastore in QA and close this issue if fixed.

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
