### ISSUE TITLE
Email templates > Org name issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3285]
AR : Org name is displayed as 'MyStudies MyStudies' 
ER : Org name should be displayed as 'Organization' for all the email templates

![pmtemp](https://user-images.githubusercontent.com/71445210/109522944-d0393e80-7ad4-11eb-8ef0-f1f45b69fbb7.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and update the ticket accordingly

**Comment by Lathan-btc** [comment]
@Kantharajut-btc 
The highlighted text in the attached screenshot should be changed in all the email templates except Account created email template

![temp11](https://user-images.githubusercontent.com/71445210/110773418-bb05a200-8282-11eb-91ad-f88e4e8f9ff4.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test the issue in dev and update the ticket accordingly

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please test and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
