### ISSUE TITLE
[SB] Manage users >Success message is not displayed for the account update

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3290]
Steps
1. Login in study builder application with super admin credentials
2. Add a user
3. Navigate to edit user details page
4. Update the user account details and observe

AR: An error message is getting displayed when a super admin updates the user details ( User account status should be 'Pending activation)
ER: 'User details updated' success message should be displayed. 

![rror1](https://user-images.githubusercontent.com/71445210/109640837-f9aaa680-7b76-11eb-8981-a368511d2a0e.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
