### ISSUE TITLE
[SB] Make expiry time value dynamic for links sent in emails

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3296]
Make the time value dynamic (configured and read from a centralized properties file) for the following emails and related functionality:

1. Account update (email change)
2.  Account reactivation after enforcement of password change
3.  Password help

(emails 2, 8 and 9 from the email document)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
