### ISSUE TITLE
Questionnaires/Active tasks > Issue in Custom schedule type

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3299]
Steps
1. Create/Edit study
2. Go to Questionnaire/Active tasks 
3. Switch to the Schedule tab
4. Select Regular and custom schedule
5. Add more than one run and enter all the required fields Click on the Save button
6. Delete any one of the rows and click on the Done button
6. Edit Questionnaire/Active tasks
7. Schedule tab > Select Anchor date based radio button
8. Select the Custom schedule and add some runs and click on the done button 
9. Again edit Questionnaire/Active tasks
10. Change the Anchor date based to Regular 
11. Add some runs and click on the Done button
12. Edit questionnaire/Active tasks and observe the fields in the schedule tab

AR : Deleted rows are displayed with empty fields
ER : Deleted rows should not be displayed

![test1](https://user-images.githubusercontent.com/71445210/109980259-b3e01080-7d25-11eb-9b33-ceb7361bfd70.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
@monica-BTC 

1. Add questionnaire/Active task > Schedule tab > Select Anchor date based and custom schedule > Add more than one run and enter all the required data and click on Done > Edit questionnaire/active task > Schedule tab > Switch to Regular and add a run and click on Done button > Edit questionnaire/active task > Schedule tab > Observe the Added run(s)

![jmjh](https://user-images.githubusercontent.com/71445210/111125610-cb29c400-8597-11eb-9b32-08a8dd20c406.png)

**Comment by monica-BTC** [comment]
@Lathan-btc please test and confirm this issue in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
