### ISSUE TITLE
[Android] App is getting crashed while enrolling into the study 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3301]
Steps
1. Login into SB
2. Add/Edit study
3. Create more than one consent with the same title
4. Launch the study
5. In mobile app try to enroll for the particular study

AR: App is getting crashed while enrolling into the study 
ER: The user should be able to enroll successfully

![image](https://user-images.githubusercontent.com/71445210/110089658-606cd180-7dbc-11eb-87bb-dd4307d5f6cb.png)

**Comment by nishit-v** [comment]
1. Issue is not observed for iOS.
2. Issue also observed for custom consent when same consent name is created.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
