### ISSUE TITLE
[iOS] Signup > Incorrect error message is displayed on trying to signup with already registered unverified user

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3304]
**Steps:**
1. Signup with a new user with valid email and password
2. Don't enter the verification code
3. Navigate back to signup
4. Enter same email ID entered in step 1
5. Observe the error message

**Actual:** 'Your Session is Expired' message is displayed

**Expected:** 'Your account is pending activation. Please check your email for details and signin to complete activation.' 

**iOS screenshot:**
![IMG_1324](https://user-images.githubusercontent.com/60386291/110289596-aa012a80-800f-11eb-9192-d569edae0a53.PNG)

Refer Android screenshot for reference:
![Screenshot_20210308-130426](https://user-images.githubusercontent.com/60386291/110289630-b6858300-800f-11eb-9922-a7f5b7c465c6.jpg)

**Comment by aswinijena100** [comment]
@nishit-v Please test and close this issue. U can test in yesterday's build . PR is merged yesterday only

**Comment by nishit-v** [comment]
Issue is resolved in latest iOS build V1.0.205 (After PR merge)
