### ISSUE TITLE
[Android] Hyperlinks are displayed as normal text in resources in android

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3306]
Steps:- 
1. Add a resource text with hyperlinks. eg:- http://www.google.com in WCP
2. Open the application and enroll into study 
3. Navigate to resource section and find the resource created
4. Verify the hyperlinks in the resource 

A/R: Hyperlinks are displayed as normal text and not clickable
E/R:- Hyperlinks should be clickable links and navigate to respective site

![image](https://user-images.githubusercontent.com/60500517/110322057-8f8f7700-8038-11eb-8814-2a3886d6307f.png)

**Comment by chiranjibi009** [comment]
@nagarjunav1 Please test this issue in dev instance and update.

**Comment by chiranjibi009** [comment]
@nagarjunav1 Please test this issue in QA instance and update.
