### ISSUE TITLE
[SB] Password reset screen > Validation is not happening properly

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3307]
Steps
1. log in as a super admin
2. Users tab > Navigate to edit user details of any study admin 
3. Click on Enforce new password button
4. Click on the link received through email
5. Enter New Password same as the last 10 passwords and confirm the password and click on submit button

AR : In the Password reset screen, the New Password field is allowing the last 10 passwords
ER : It should not allow the last 10 password
 
[Note: 1. Due to this user is not able to login into the application with the new password or previous password
           2. Issue should be fixed for all the scenario like Forgot password flow, Account lock and Password enforce  ]

**Comment by madhurya-btc** [comment]
@latha Please test #3164 issue also, along with this issue testing and confirm the same.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the Latest QA instance.
