### ISSUE TITLE
[PM] Location > Add/Edit location >Location name and description fields should allow the 'space' 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3312]
AR : Location > Add/Edit location >Location name and description fields are not allowing the space
ER : Location > Add/Edit location >Location name and description fields > Space character should be allowed 

[Note: Issue also should be fixed for First name and Last name fiels]

![location12](https://user-images.githubusercontent.com/71445210/110442663-10a24900-80e1-11eb-8d0a-55ddfe6776a8.png)

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please test and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
