### ISSUE TITLE
[SB] Password setup screen > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3313]
Password help screen > Password criteria should be pointed to the 'Password' text field

![pointing - pwd setup](https://user-images.githubusercontent.com/71445210/110475582-13179980-8107-11eb-9dfb-9705f1e812b4.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
@monica-BTC Issue should be fixed for the following screen 

Password reset screen after password expiry

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
