### ISSUE TITLE
[SB] Provision for study replication

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3321]
Allow study admins to do the following (based on permissions)

Copy a study into a new one within the same Study Builder - the study must get created in draft state and will need to be assigned a new Study ID and made content-complete before it can be launched or published

Notes:

The newly created study must have all metadata and user-created data carried over from the origin study
The implementation should ideally be extensible and flexible enough to accommodate new SB features that get added over time

Also , see #3114

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this enhancement is implemented in dev, please test and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this enhancement in QA
