### ISSUE TITLE
[PM] Open study > Enrollment registry > Multiple records are displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3322]
Steps
1. Join an open study
2. Delete the app account
3. Again create an app account with the same email 
4. Enroll into the same open study
5. PM > Observe the number of records on the enrollment registry page

AR: Multiple records are displayed
ER: Only one participant record should be displayed

 
![multiple records11](https://user-images.githubusercontent.com/71445210/110640666-18441980-81d7-11eb-9021-0d8a9be7450f.png)

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
