### ISSUE TITLE
[SB] App level notification > Adjust the alignment of the last column

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3323]
App-level notification > Adjust the alignment of the last(Actions) column

![app-noti](https://user-images.githubusercontent.com/71445210/110642904-81c52780-81d9-11eb-8f49-b4d160b6cdfd.png)

[Note: Issue observed only in QA instance]

**Comment by Madhud5** [comment]
Hi @Lathan-btc DEV- QA it's fixed. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. PR merged Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
