### ISSUE TITLE
[SB] Logo needs to be updated on Reset password screen post password expiry

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3324]
[SB] Logo needs to be updated on Reset password screen post password expiry

![logo1](https://user-images.githubusercontent.com/71445210/110791801-a46a4580-8298-11eb-95ef-dbab3bef46ac.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev instance and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in QA and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
