### ISSUE TITLE
[SB] Not able to add study admins with specific permissions 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3325]
Not able to add study admins with specific permissions

[Note : 1. Wrong values are displayed in the dropdown
            2. Issue observed in Release candidate branch]

![sb-rc](https://user-images.githubusercontent.com/71445210/110795542-f7de9280-829c-11eb-9b87-8c9767176c2f.png)

**Comment by aswinijena100** [comment]
@Lathan-btc please verify and close this issue if fixed. 

Note : This issue fix does not required PR to be raised

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest RC branch.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Release candidate branch.
