### ISSUE TITLE
[PM] Password strength meter fails to work for default superadmin user due to blank last name

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3326]
Steps:
1. Login with default superadmin (which is executed via script)
2. Try forgot password
3. Enter temporary password , new password and confirm password
4. Observe password strength meter fails to work for 'New password' field
Issue is observed due to blank Last name.

Actual: Password strength meter fails to work for default superadmin user due to blank last name

Expected: Last name should be updated via script similar to SB

Note: 
1. Issue is not observed when last name is updated

**Comment by nishit-v** [comment]
Refer attached video for reference:

https://user-images.githubusercontent.com/60386291/110914435-60308100-833c-11eb-9ada-5ef115eeefc1.mp4

**Comment by aswinijena100** [comment]
@nishit-v Please test this in 2.0.3 release candidate environment and let me know if it works fine.

**Comment by nishit-v** [comment]
Verified in 2.0.3 release candidate branch and issue is resolved for default superadmin.

![Screenshot_3](https://user-images.githubusercontent.com/60386291/111261013-cd4b5b80-8647-11eb-8a2b-e42a818d8edf.png)

**Comment by aswinijena100** [comment]
@nishit-v Please close this ticket if it fixed already in QA instance
