### ISSUE TITLE
[SB] Active tasks > Schedule tab > Anchor date > Custom schedule > UI  issue  when user clicks on the '+' icon

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3332]
Active tasks > Schedule tab > Anchor date > Custom schedule > UI  issue  when user clicks on the '+' icon

![alignment issue1](https://user-images.githubusercontent.com/71445210/110951189-c7652a00-836a-11eb-8c76-6bbc17748f22.png)

**Comment by Madhud5** [comment]
Hi @latha DEV- it's fixed. Please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. PR merged Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
