### ISSUE TITLE
[SB] 'Questionnaires'/'Active tasks' > Anchor date based > Error message issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3333]
Questionnaires'/'Active tasks' > Anchor date based > Error message should be displayed in the same line.

![em1](https://user-images.githubusercontent.com/71445210/110954707-d1892780-836e-11eb-8a19-c69457d004cd.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue fixed in dev, please test and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
@Kantharajut-btc Issue is reproducible in the latest dev instance for other error messages on the same screen.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please test and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
