### ISSUE TITLE
[PM] User details page > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3334]
User details page > UI issue

![ui issue5](https://user-images.githubusercontent.com/71445210/110955184-5411e700-836f-11eb-90c7-69f08c1482fb.png)

https://user-images.githubusercontent.com/71445210/110955232-612ed600-836f-11eb-8a92-4b2a1b6b1c55.mp4

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please test and confirm.

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance


![rr2](https://user-images.githubusercontent.com/71445210/111427548-47e5ab00-871c-11eb-9060-13c1d09dde79.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in DEV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc please test in QA and close if fixed

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
