### ISSUE TITLE
[PM] Site participant registry > Add participant > UI issue when it shows the validation message

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3340]
Site participant registry > Add participant > Adjust the UI when it shows the validation message

![ss2](https://user-images.githubusercontent.com/71445210/111437483-2b9c3b00-8729-11eb-9dba-c21b9e2dec6a.png)

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please test and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc please test in QA and close

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
