### ISSUE TITLE
[PM] Sites tab > Add location > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3341]
Sites tab > Add location > UI issue

[Note : Issue observed only in firefox browser]

![ss3](https://user-images.githubusercontent.com/71445210/111452929-06afc400-8739-11eb-9213-032671fd7639.png)

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please test and confirm.

**Comment by Lathan-btc** [comment]
@sujatha-btc Issue is reproducible when the user selects the value from the dropdown


![ss14](https://user-images.githubusercontent.com/71445210/111960195-6e895480-8b15-11eb-8f68-9bac4d2d8614.png)

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed test.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc  please test and close

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
