### ISSUE TITLE
[PM] Participant details page > Table columns alignment issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3342]
Participant details page > Enrollment history and consent history table columns should be aligned properly (As per invision screen)

![ss4](https://user-images.githubusercontent.com/71445210/111454145-5478fc00-873a-11eb-9718-210d30fe3e8a.png)

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please test.

**Comment by Lathan-btc** [comment]
@sujatha-btc Issue is still reproducible in the latest Dev instance.

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed test please.

**Comment by Lathan-btc** [comment]
@sujatha-btc Issue is reproducible in the latest Dev instance.

![ss55](https://user-images.githubusercontent.com/71445210/112150000-9e178a00-8c05-11eb-8b11-97ae48aa71d9.png)

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please test and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test in QA and close the issue

**Comment by Lathan-btc** [comment]
@sujatha-btc Issue is reproducible in the latest QA instance

![pp11](https://user-images.githubusercontent.com/71445210/116550817-d3a24800-a914-11eb-99c3-ce34e8823d27.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by Madhud5** [comment]
Hi @Lathan-btc Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
