### ISSUE TITLE
[Android] UI issues 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3352]
1. Adjust the UI when answer options displayed with Checkboxes
Eg: Comprehension test question and  questionnaires with text choice and etc

![ss5](https://user-images.githubusercontent.com/71445210/111487717-9b78e880-875e-11eb-9e1e-d90851bed4be.png)

2. All the values aligned properly till the end of the text scale

![ss6](https://user-images.githubusercontent.com/71445210/111488995-c4e64400-875f-11eb-81e5-4ace476a0d28.png)

3. 'Learn more' text on the consent screens should be aligned properly 

![ss7](https://user-images.githubusercontent.com/71445210/111490917-68842400-8761-11eb-8cd4-9bb696413361.png)

**Comment by naveenr-btc** [comment]
@SR-btc need your input on the 3rd point, it's default in ResearchStack, if you want it to be fixed we need to create a custom step completely.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test in QA and close if fixed

**Comment by Lathan-btc** [comment]
@naveenr-btc Please provide the latest QA build.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA Android build
