### ISSUE TITLE
[Android] Study activities > Value picker response type >App is allowing the user to submit the response without selecting any value

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3357]
Steps:-
1. Configure an activity with Value Picker based response type in Study builder
2. Open the Android application and login into App
3. Enroll into the study
4. Try to submit a response for Value Picker response type activities and verify

AR:- App is allowing the user to submit the response without selecting any value
ER:- App should not allow submitting the response until the user selects the value

**Comment by nagarjunav1** [comment]
Issue is fixed in  latest dev build
