### ISSUE TITLE
[SB] Password reset screen > User is not navigating back to the sign in screen when user click on the logo of the application

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3358]
[SB] Password reset screen > User is not navigating back to the sign-in screen when user click on the logo of the application

![ss8](https://user-images.githubusercontent.com/71445210/111497355-0b8b6c80-8767-11eb-8488-daa84353d88e.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev instance and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in QA and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
