### ISSUE TITLE
APNs - Upgrade to newer - HTTP/2-based Apple Push Notification service (APNs)

### ISSUE THREAD

**Issue by GovindPrasadBostonTechnologyCorporation** [GoogleCloudPlatform/fda-mystudies#3364]
APNs will no longer support the legacy binary protocol after March 31, 2021. Upgrade to newer - HTTP/2-based Apple Push Notification service (APNs) has to be done and tested before the deadline time.
Reference - https://developer.apple.com/news/?id=c88acm2b

**Comment by naveenr-btc** [comment]
Hi,
please use this library for push notification [Pushy](https://github.com/jchambers/pushy/tree/pushy-0.14.2)

**Comment by aswinijena100** [comment]
@nishit-v Changes to upgrade APNs is done and pushed to dev environment . Please test IOS push notifications and let me know if it is working fine.

**Comment by nishit-v** [comment]
Tested iOS push notifications in dev instance, Wokring fine and no issues found.

**Comment by nishit-v** [comment]
Tested iOS push notifications in new master instance, Wokring fine and no issues found.
