### ISSUE TITLE
Revise text across screens

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3365]
Standardize the use of title case and lower case across screens, and update text accordingly.
for example, Studies tab > Add/Edit/View eligibility test, Add/Edit/View comprehension test and etc....
                     Users tab > Add/Edit/View user
                     Notification tab > Add/Edit/View notification

[Note : It should not apply for the title of the main screen Eg. Studies tab > Eligibility, Comprehension test, Questionnaires and etc..]

**Comment by pujithr** [comment]
@Lathan-btc ,Issue is solved. please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
@Lathan-btc PR had merged. Please test in QA Env and Update ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
