### ISSUE TITLE
[SB] Use the proper text case for all the dropdown values

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3366]
Use the proper text case for all the dropdown values across the application
Eg: Questionnaires > Response type dropdown
      Questionnaires/Active task > Schedule tab > 'Select anchor date type' dropdown etc..
 

![ss9](https://user-images.githubusercontent.com/71445210/111611690-bb61e800-8802-11eb-9234-cf62148ef333.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
@harisboston issue is reproducible for 'Select anchor date type' dropdown on Questionnaires/Active task/Resources

![ss9](https://user-images.githubusercontent.com/71445210/111611690-bb61e800-8802-11eb-9234-cf62148ef333.png)

**Comment by harisboston** [comment]
@Lathan-btc Kindly create new study to test this scenario. Thanks.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest QA instance.

**Comment by Lathan-btc** [comment]
@harisboston Issue is reproducible in QA instance.

issue is reproducible for 'Select anchor date type' dropdown on Questionnaires/Active task/Resources

![ss9](https://user-images.githubusercontent.com/71445210/111611690-bb61e800-8802-11eb-9234-cf62148ef333.png)

**Comment by aswinijena100** [comment]
@Lathan-btc Please test in QA and close if fixed

**Comment by Lathan-btc** [comment]
@harisboston issue is reproducible for 'Select anchor date type' dropdown on Questionnaires/Active task/Resources

![ss9](https://user-images.githubusercontent.com/71445210/111611690-bb61e800-8802-11eb-9234-cf62148ef333.png)

**Comment by pujithr** [comment]
@Lathan-btc Please test in QA and update the ticket accordingly

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
