### ISSUE TITLE
[SB] Questionnaire/Active task > Create a activity with custom schedule > Observe the schedule type in activities screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3367]
Questionnaire/Active task > Create an activity with a custom schedule > Observe the schedule type in the activities screen
ER : 'Custom Schedule' should be changed to 'Custom schedule'

![ss11](https://user-images.githubusercontent.com/71445210/111614908-28c34800-8806-11eb-8c15-14c70c2b1428.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
