### ISSUE TITLE
[SB] Modify behavior of toast message on marking sections complete

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3373]
Study Builder > Mark as completed action in various study sections > Show the success toast message on the current screen for 2-3 seconds before navigating to the next section, so that the user receives contextual success message feedback on the action just taken before seeing the next section. Overall duration of the toast timer can remain the same as before. 

Also, modify the toast message to 'Section marked complete'

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
@monica-BTC 
1. Remove the full stop at the end of the success message
2. User is navigating to next section when user add a consent/comprehension test question/questionnaire/active task

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
