### ISSUE TITLE
[SB] Enable all study sections when editing Study Info or Settings sections of a launched study

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3374]
For studies that have been launched, and are being edited for subsequent publishing of updates, it is not necessary to disable other sections of the study if the Study Information and Study Settings sections are not marked complete at any point. 

This is needed only prior to study being launched for the first time in order to have pre-requisite settings configured before creating the rest of the study.  So the existing section-disabling behavior prior to launching a study can stay as it is, but the same should be removed once the study is launched.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
