### ISSUE TITLE
[SB] Behavior of Cancel button in E-Consent Steps not consistent with other sections

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3375]
The Cancel button in the e-Consent Steps section navigates to the Consent Sections screen, whereas from all other sections, this action takes users back to the study list.

Modify the behavior of the Cancel button in e-Consent to maintain a consistent user experience.

**Comment by pujithr** [comment]
@Lathan-btc changes are made and pushed to DEV environment . Please test in DEV and update ticket.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by pujithr** [comment]
@nagarjunav1 PR had merged. Please test in QA Env and Update ticket accordingly.
