### ISSUE TITLE
[SB} Eligibility screen UI issues 

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3376]
- Reduce the height of the text area field for instruction text  (seen for the first two eligibility methods) to be for a single line.
- After this, for the 2nd eligibility method,  reduce the vertical space between this instruction field and the table of questions below it
- For the 2nd and 3rd eligibility methods ( token + test, only test), vertically align all the elements on the right side of the page i.e. MAC button, Instruction text field, 'Add question' button and the 'Actions' column heading and action icons under it.

**Comment by Madhud5** [comment]
Hi @latha  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. PR merged Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
