### ISSUE TITLE
[SB} UI issues with appearance of placeholder text in empty tables

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3377]
For all SB screens that have tables and display 'No content created yet.'

- increase vertical space between the table header row and this text
- Reduce the font size of the text
- Reduce the darkness of the color to a faded out , lighter grey so it looks like a placeholder rather than primary text
- Text will read  - No content created yet

**Comment by Madhud5** [comment]
Hi @latha  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. PR merged Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instace.
