### ISSUE TITLE
[SB] Consent Sections table column header text correction

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3378]
The first column header should read SECTION TITLE instead of CONSENT TITLE

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in dev environment and update

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in QA and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
