### ISSUE TITLE
[SB] Edit Consent Section > Screen hangs on click of Done when 'Long description' is not filled out

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3379]
SB > Study > Consent Sections > Edit Consent Section

The 'Done' button that is meant to validate, save and mark the subsection completed, does not work if the 'Long Description' field is not filled out, and the screen hangs indefinitely

Steps to reproduce:
Navigate to an existing consent section
Clear out text from the long description if it exists
Click on Done

Expected behavior
- the missing field should be highlighted with an inline error message on click of the Done button

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
