### ISSUE TITLE
[SB] Add consent section > Save action does not work

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3380]
SB > Study > Informed Consent > Consent Sections > Add consent section

The Save button is not working and no action takes place when this button is used

Expected behavior:
The Save action should save all content on the screen in draft state and show the save success toast message

**Comment by SR-btc** [comment]
Steps to reproduce:

1. Visit the Add Consent Section screen
2.  Fill out some of the fields (not all)
3. Click on Save
4.  Observe that the content does not get saved and instead the Save action behaves like 'Done' running validations for missing fields

For the above scenario, If you fill out all fields and then save, the save action is successful because it is essentially mimicking the Done button behavior.

This issue does not occur if you clear out required fields after first doing a successful save by filling in all the fields. So the bug appears to be the first time add/insert operation and not for the edit/update operation on this screen.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in dev environment and update

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in QA and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
