### ISSUE TITLE
[SB} Text issues in Add/Edit Consent Section

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3381]
On the Add/Edit consent section screens, when the user has not provided input for the Visual Step field, correct error message seen, to ' Please select one of the above options'

On the Add/Edit consent section screens, under the 'Default Options' consent type, correct error message seen when the topic dropdown is not filled out:
'Please select a topic'

**Comment by pujithr** [comment]
@nagarjunav1. Please test this issue in Dev Instance and update the ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
@Lathan-btc PR had merged. Please test in QA Env and Update ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
