### ISSUE TITLE
[SB] Correct text seen on reordering elements (various screens)

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3382]
Success message (toast) seen on various screens that support reordering (Consent sections, eligibility test, comprehension test, questionnaire steps etc) must be changed to 'Content items reordered'

**Comment by pujithr** [comment]
@Lathan-btc Please test this issue in dev instance and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
@Lathan-btc PR had merged. Please test in QA Env and Update ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
