### ISSUE TITLE
[SB] Inconsistency in table UI

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3384]
Inconsistency observed in the UI of tables that hold content items in various screens

E.g. The comprehension test list of questions has a line that indicates the end of or the bottom of the table. This is missing in the Consent Sections table and the Resources table.

Please verify all screens that have these sort of tables (except where there is pagination) and fix the UI to have the end marker line similar to the Comprehension Test table of questions.

**Comment by Madhud5** [comment]
Hi @Lathan-btc   i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest DEV instance

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. PR merged Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
