### ISSUE TITLE
[SB] Right-alignment issue for screen elements on multiple screens

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3385]
On the Comprehension Test screen that displays the comprehension test questions, the elements to the right are not vertically aligned i.e. the MAC button, the Add question button, the Actions column header and the Action icons under it.

This issue has been observed in multiple screens. Please verify all screens for this issue and fix where needed.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi, @Lathan-btc I have fixed it. PR merged Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
