### ISSUE TITLE
[PM] UI issue with study status indicator 

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3387]
Dashbaord > Sites and Studies tabs > The indicator that displays study status is not vertically aligned with the study name text

**Comment by sujatha-btc** [comment]
@SR-btc  deployed please test.

**Comment by sujatha-btc** [comment]
@Lathan-btc please text and confirm. added vertical alignment for indicator(active)for both screens sites and study.

**Comment by Lathan-btc** [comment]
@sujatha-btc Issue is still reproducible for Deactivated status.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc please test in QA and close if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
