### ISSUE TITLE
[SB] Active task > Schedule tab > Anchor date based > Error message is not displayed for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3391]
Steps
1. Add/Edit active task
2. Go to the Schedule tab
3. Select anchor date based and custom schedule
4. Add 2 runs and enter valid inputs and click on Save
5. Change the X value of the 2nd row (changed value should be less than or equal to 1st row of the Y value) and observe

AR: Error message is not displayed
ER : 'X should be less than Y of the current row and greater than Y of the previous row.' error message should be displayed

![ss17](https://user-images.githubusercontent.com/71445210/112005926-37cd3180-8b49-11eb-9bde-0d6fa3be576e.png)

**Comment by Lathan-btc** [comment]
@harisboston 
Add/Edit active task > Schedule tab > Select anchor date based and custom schedule > Add 2 runs and enter valid inputs and click on Save > Delete 1st row > edit the X and Y value of the 2nd row with valid inputs and observe

AR : An error message is displayed for the 'Y' value field even though user enters valid inputs
ER : Error message should not be displayed 

![ss24](https://user-images.githubusercontent.com/71445210/112446429-316fcd00-8d76-11eb-8e32-45a2d367759e.png)

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in dev environment. Kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
