### ISSUE TITLE
[SB] Add/Edit Study > Notifications > User is navigating to studies list when user clicks on Save button

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3394]
Steps
1. Create/Edit study
2. Navigate to the Notification section
3. Click on add notification
4. Enter only 'Notification text' and click on Save button
5. Observe

AR : User is navigating to the Studies list page
ER : It should display a success message and the user should stay in the same page

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
