### ISSUE TITLE
[Enroll] Mobile app participant unable to enroll into any of the studies

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3395]
**Steps:**
1. Signup/Login into mobile
2. Try to enroll into any studies
3. Complete till digital signature
4. Observe the flow after consent

**Actual:** Error message is displayed and unable to enroll into any studies

**Expected:** User should be able to enroll successfully

Note:

Issue observed only in Dev instance.

![unnamed](https://user-images.githubusercontent.com/60386291/112028107-d6638d80-8b5d-11eb-876b-f4c3910cd6b1.png)

**Comment by navya-BTC** [comment]
@nishit-v please test and confirm this issue.

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.
