### ISSUE TITLE
[Android] Sign in screen > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3396]
Sign in screen > Footer is wrapping in mobile device

![ss18](https://user-images.githubusercontent.com/71445210/112110745-567b0900-8bd9-11eb-9396-a17420da233a.png)

**Comment by harisboston** [comment]
@Lathan-btc This issue is fixed in dev environment. Kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
