### ISSUE TITLE
[SB] User is able to create a consent without entering mandatory field

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3398]
Steps
1. Create a consent
2. Edit consent
3. Remove the data entered in the 'Long description' field
4. Click on Done

AR: Able to create a consent without entering the long description 
ER: User should get an error message and user should not be able to create a consent

[Note: Issue observed only in firefox browser]

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in dev environment and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in QA and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
