### ISSUE TITLE
[SB] Notifications > Server level automated notifications from Study Builder are not triggered and not shown in notifications list

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3405]
**Steps:**
1. Trigger server level automated notifications
eg. Create new study/ Pause a study/ Resume a study/ Deactivate a study / Create new activity etc.
2. Observe the same in mobile notifications list and observe push notification is not triggered

**Actual:** 
1. Push notifications are not triggered for Server level automated notifications
2. Notifications are not shown in the notifications screen in mobile

**Expected:** 
1. Push notifications should trigger for Server level automated notifications
2. Notifications should be shown in the notifications screen in mobile

Note: Issue not observed for manually created App level/study level notifications

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in Dev instance

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance. Automated notifications are getting triggered now and shown in the list.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA Instance.
