### ISSUE TITLE
[SB]Questionnaires/Active task > Anchor date based > Issues when a user add multiple runs and delete any of the runs

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3406]
Steps
1. Add/Edit Questionnaires/Active task
2. Go to the Schedule tab
3. Select anchor date based and custom schedule
4. Add 2 runs and enter valid inputs for the 1st row and delete the fist row
5. Again click on '+' icon
6. Enter the valid inputs for the 1st row and X value of the 2nd row
7. Observe

AR : 1. Error message is displayed for the 'Y' value field of the first row (image1)
       2. Time picker is not working for the next row (image2)
ER: Error message should not be displayed when a user enters valid inputs and time picker should be displayed

![ss21](https://user-images.githubusercontent.com/71445210/112176794-6963fc80-8c1e-11eb-80f1-9ee63b801baf.png)

![ss22](https://user-images.githubusercontent.com/71445210/112176829-71bc3780-8c1e-11eb-8cdd-334c14874c9d.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA  instance.
