### ISSUE TITLE
[PM] App participant registry > Text change

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3412]
App participant registry > Text change > Status 'Pending Activation' should be 'Pending activation'

![ss19](https://user-images.githubusercontent.com/71445210/112432604-23ff1680-8d67-11eb-8aa4-33cb2b9da16e.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
