### ISSUE TITLE
[PD[] Reorganize consent documents in Cloud Storage

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3418]
Consent documents in Cloud Storage must be organized as

Study  > Participant-specific ID (different from Participant ID) > Consent Documents

We also need a way for existing deployments to take the update

**Comment by chiranjibi009** [comment]
@nagarjunav1 Please test this issue using new data and update

**Comment by nagarjunav1** [comment]
Folder structure is now updated in the Cloud storage for DEV enironment
New folder structure is like Study > Participant-specific ID (different from Participant ID) > Consent Pdfs

**Comment by chiranjibi009** [comment]
@nagarjunav1 Please test the issue in QA and update.

**Comment by nagarjunav1** [comment]
Folder structure is now updated in the Cloud storage for QA environment
New folder structure is like, 
 Study > Participant-specific ID (different from Participant ID) > Consent Pdfs
