### ISSUE TITLE
[Android] UI Issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3420]
There are no proper margins for the content of the following screen
1. Instruction step content

 
![ss122](https://user-images.githubusercontent.com/71445210/112635082-63aa2900-8e61-11eb-9e28-28aa68234a70.png)

2. Confirmation screen after taking comprehension test

3. Review consent screen

4. Consent confirmed screen

5. Activity completed screen (Increase margins for the sentence in the middle of the screen)

![ss121](https://user-images.githubusercontent.com/71445210/112635119-702e8180-8e61-11eb-8fda-21e9801fb360.png)

**Comment by aswinijena100** [comment]
@Lathan-btc Please test and close the issue if fixed in QA

**Comment by Lathan-btc** [comment]
@naveenr-btc Please provide the latest QA build.
