### ISSUE TITLE
[Auth][UI] Sign in screen > Error messages are overlapping with the screen elements

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3422]
Sign in screen > Error messages are overlapping with the screen elements

[Note: Issue should be fixed for all the error messages] 

![ss25](https://user-images.githubusercontent.com/71445210/112954251-db2ad180-915b-11eb-8442-ec2384088ed4.png)

![ss26](https://user-images.githubusercontent.com/71445210/112954298-e41ba300-915b-11eb-8b66-caaeb40ee36c.png)

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in dev environment. Kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is still reproducible in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
