### ISSUE TITLE
[Android] Fetal kick counter activity > App is crashing for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3423]
Steps
1. Configure a study with 'Fetal kick counter' activity
2. Launch/Publish updates
3. In mobile > join that particular study
4. Click on Fetal kick counter activity
5. Enter the total number of kick count
6. Click on 'Edit' on the displayed popup
7. Remove the number of kick counts
8. Click on the Back button /Next button  and observe

AR : App is getting crashed
ER : It should display a validation message to enter the value if the user clicks on 'Next' button

**Comment by aswinijena100** [comment]
@Lathan-btc please check this issue in QA and close if fixed already

**Comment by Lathan-btc** [comment]
@naveenr-btc Please provide the latest QA build.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA build.
