### ISSUE TITLE
[PM] Password help email template issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3433]
AR : Password help email template > Some other character is displaying instead of ' icon
ER : It should display Org Name's

[Note: Issue observed only in master branch]

![ss62](https://user-images.githubusercontent.com/71445210/113580713-b941bb00-9643-11eb-868b-722bdaca9690.png)

**Comment by aswinijena100** [comment]
@Lathan-btc Please verify this issue and close if it fixed already

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Master branch.
