### ISSUE TITLE
[PM] UI issues with appearance of placeholder text in empty tables

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3435]
For all PM screens that have tables and display the placeholder
1.Reduce the font size of the text
2. Reduce the darkness of the color to a faded out, lighter grey so it looks like a placeholder rather than primary text
3. Remove the full stop at the end

![ss63](https://user-images.githubusercontent.com/71445210/113582483-0faff900-9646-11eb-8731-13bdaf918e7b.png)

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please test and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test in QA and close if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest build deployed
