### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by dhanyak-btc** [GoogleCloudPlatform/fda-mystudies#3438]
Copied from Andrew's email.

In addition to the one where it created bugs, here are the ones that it didn't create bugs for that also have a patched version available. Let me know if you need the details on the vulnerabilities. I added H/M/L for the ones marked as High severity, Moderate severity, & Low severity.

**study-builder/fdahpStudyDesigner/pom.xml**
M- Upgrade com.mchange:c3p0 to version 0.9.5.3 or later.
H- Upgrade commons-fileupload:commons-fileupload to version 1.3.3 or later.
H- Upgrade org.springframework:spring-core to version 4.3.20 or later. (note this one may not be possible. Dependabot reports the latest version that can be upgraded to is 3.2.8, but there are a few vulnerabilities so check and see.
participant-manager-datastore/participant-manager-service/pom.xml
M- Upgrade com.google.guava:guava to version 24.1.1 or later.
H- Upgrade org.apache.poi:poi to version 3.17 or later

**oauth-scim-service/pom.xml**
M- Upgrade com.google.guava:guava to version 24.1.1 or later.

**study-datastore/pom.xml**
L- Upgrade junit:junit to version 4.13.1 or later
M- Upgrade org.quartz-scheduler:quartz to version 2.3.2 or later
M- Upgrade mysql:mysql-connector-java to version 8.0.16 or later
H- Upgrade commons-collections:commons-collections to version 3.2.2 or later.

**participant-manager/packagelock.json**
L- Upgrade ini to version 1.3.6 or later
L- Upgrade webpack-subresource-integrity to version 1.5.1 or later
M- Upgrade socket.io to version 2.4.0 or later.

Also fix the issues raised by [dependabot ](https://github.com/GoogleCloudPlatform/fda-mystudies/issues?q=author%3Aapp%2Fdependabot)

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA environment and update.
