### ISSUE TITLE
[IOS] Wrong error messages is displayed for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3440]
Steps
1. Signup with a valid email on the signup screen
2. After navigating to the verification screen, kill the app 
3. Open the app
4. Navigate to Sign up screen
5. Enter the registered email id ( entered email in step1)
6. enter all the mandatory fields and click on Submit
7. Observe the error message

AR: 'Your session is expired' error message is displayed

![image](https://user-images.githubusercontent.com/71445210/113820859-e6ec4880-9798-11eb-984c-91bc2844e5c2.png)

ER : 

![image](https://user-images.githubusercontent.com/71445210/113820927-01262680-9799-11eb-9060-80c3575606a8.png)

**Comment by aswinijena100** [comment]
@Lathan-btc Please test and close this issue. U can test in yesterday's build . PR is merged yesterday only

**Comment by nishit-v** [comment]
Issue is resolved in latest iOS build V1.0.205 (After PR merge)

**Comment by nishit-v** [comment]
Issue is reproducible again in latest iOS dev build. 

![IMG_1822](https://user-images.githubusercontent.com/60386291/125897533-6b139a59-acb1-4d4b-afb9-e878f9f021a1.PNG)

**Comment by aswinijena100** [comment]
@nishit-v Please test now in dev

**Comment by nishit-v** [comment]
Issue is reproducible again in latest iOS dev build.

**Comment by aswinijena100** [comment]
@nishit-v my bad. I missed one change to add. I will get redeploy and let you know

**Comment by aswinijena100** [comment]
@nishit-v Please check now

**Comment by nishit-v** [comment]
Issue is fixed now in latest Dev instance.
