### ISSUE TITLE
[SB] Add/Edit questionnaires > Fields are not displayed in 'Response level attributes' tab for the following response types

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3442]
Add/Edit questionnaires > Fields are not displayed in the 'Response level attributes' tab for the following response types
1. Continuous scale
2. Text scale
3. Value picker
4. Image choice
5. Text choice

![cc7](https://user-images.githubusercontent.com/71445210/113858044-e36cb780-97c0-11eb-8a8b-eb3d8ce753d5.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
