### ISSUE TITLE
[PM] Participant details page > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3443]
[PM] Participant details page > UI issues

![cc8](https://user-images.githubusercontent.com/71445210/113862304-da321980-97c5-11eb-9bef-8a42f330f80c.png)

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed in dev please text.

**Comment by Lathan-btc** [comment]
@sujatha-btc Following UI issue is still reproducible in the latest Dev instance [ Only in firefox rowser] 

![112](https://user-images.githubusercontent.com/71445210/114033388-d7552880-989a-11eb-9701-dd28b784b117.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have checked in DEV its fixed. Please check and let me know.

**Comment by nagarjunav1** [comment]
![image](https://user-images.githubusercontent.com/60500517/114670382-8e7cf400-9d20-11eb-94af-abbd4825a8c7.png)

Last Enrollment status value is not aligned properly

**Comment by nagarjunav1** [comment]
![image](https://user-images.githubusercontent.com/60500517/114670929-24188380-9d21-11eb-95ff-a56b494814a0.png)

Last Enrollment Status value is aligned properly

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please test and update.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest  DEV deployment

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
