### ISSUE TITLE
[Mobile] Verification step > An option to be provided to correct the email in verification step if participant mistakenly signs up with incorrect email

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3445]
Steps:
1. Navigate to signup
2. Enter incorrect email
3. Enter rest of data and click on submit
4. Navigated to verification step
5. Observe

**Is your feature request related to a problem? Please describe.**
After following above steps, no option or guide for the participants to correct the email in verification step. User has to navigate back to signup page and re-enter all the fields again.

**Describe the solution you'd like**
Instead of back arrow, an option with hyperlink 'Entered the wrong email? Signup again!' can be provided which should navigate to signup page. So participant can re-enter with valid data and proceed further

**Describe alternatives you've considered**
An optional text field in the verification step page to correct the email with previously entered password. So user can just correct the email without re-entering any of the password fields.

**Comment by harshith2590** [comment]
Proposed Solution:
A Back button should be displayed in the Verification screen. On click of this button, the user shall be able to navigate back to the Signup screen and edit the email ID. In addition to this, when the user clicks on Back Button, email id which was previously provided in the Sign Up page should be retained and not deleted. This will help the user to check the email id provided and edit the same.

**Comment by naveenr-btc** [comment]
@nishit-v please test the proposed solution in existing android builds.

**Comment by Lathan-btc** [comment]
@naveenr-btc In android builds it is working as a proposed solution.

**Comment by nishit-v** [comment]
@GovindPrasadBostonTechnologyCorporation Above scenario is not handled in iOS for below scenario.

Steps:
1. Enter all the fields in signup page and click on submit
2. Navigated to verification
3. Click on back arrow
4. Edit the email and click on submit 
5. Observe 'Please enter your password' message is displayed even though password is prefilled

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev build V1.0(238)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA build V1.0(241)
