### ISSUE TITLE
[SB] Studies list screen > Blank screen is displayed when user clicks on  create study button 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3448]
Studies list screen > Blank screen is displayed when user clicks on Action button and create study button

Steps:- 
1. Login into Study builder
2. Navigate to studies
3. Click on Create study button and observe

**Note**:- Issue also observed in edit study, when click on any actions buttons like view, Edit etc.

[Note: Issue observed in QA instance] 

![cc9](https://user-images.githubusercontent.com/71445210/114015752-b0d9c200-9887-11eb-8bba-6a43aa499477.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test in QA and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
