### ISSUE TITLE
Need to Support multiple Email Providers

### ISSUE THREAD

**Issue by mohangmk** [GoogleCloudPlatform/fda-mystudies#3453]
Currently, we are supporting only Gmail but we need to support other email providers as well with MailGun API Support

**Priority**
High

**Labels**
Feature request

**Comment by madhurya-btc** [comment]
@nagarjunav1 @nishit-v Please provide different email service provider so that we can update.

**Comment by nishit-v** [comment]
@mohangmk Please provide a different email service provider to Dev team

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm.

**Comment by nishit-v** [comment]
Verified for `outlook` email service provider in Dev instance. Receiving emails for SB, user management, PM, hydra. Working fine

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm

**Comment by nishit-v** [comment]
Verified for `outlook` email service provider in Dev instance. Receiving emails for SB, user management, PM, hydra.
