### ISSUE TITLE
[SB] Active tasks > Schedule tab > Anchor date based > Custom schedule > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3459]
Active tasks > Schedule tab > Anchor date based > Custom schedule > Add more than one run click on Save/Done > Delete one row > Click on + icon and Observe

![anchor1q1](https://user-images.githubusercontent.com/71445210/121375849-ac508900-c95e-11eb-9b78-b433068e3c91.png)

**Comment by nishit-v** [comment]
Issue should be handled for Active tasks also

![Screenshot_3](https://user-images.githubusercontent.com/60386291/123656601-b3780200-d84d-11eb-81e6-bcf76592349a.png)

**Comment by Lathan-btc** [comment]
@harisboston issue is still reproducible in the latest Dev instance

[**Note:** Issue should be fixed for both questionnaires and active task]

![image](https://user-images.githubusercontent.com/71445210/123984585-5f525680-d9e2-11eb-9ef1-23a1da4837fd.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by harisboston** [comment]
@Lathan-btc Issue fix is deployed in QA, kindly test and close this issue

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
