### ISSUE TITLE
SB > Validation message fails to dismiss post entering the valid data for all the text fields in the application

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3464]
Steps:
1. Create a study
2. Enter valid study ID
3. Observe error message 'Please fill out this field' fails to dismiss 

Note: Issue observed for the all text fields in SB

**Due to above issue unable to create a study**

https://user-images.githubusercontent.com/60386291/114866645-73d67800-9e11-11eb-938d-c0ef7fb1a9fe.mp4

**Comment by madhurya-btc** [comment]
@nishit-v Please test in dev instance and close if it is fixed.

**Comment by nishit-v** [comment]
Issue is resolved in dev instance.
