### ISSUE TITLE
[PM] Responsive issues in Locations

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3471]
Responsive issues in Locations

1. Add new location > UI issue

![mb2](https://user-images.githubusercontent.com/71445210/115351780-3a688880-a1d4-11eb-890d-74dbe71a6cd0.png)

2. UI issues in table

![MB1](https://user-images.githubusercontent.com/71445210/115351369-cf1eb680-a1d3-11eb-8e78-a55745727aa4.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue s fixed in the latest QA instance.
