### ISSUE TITLE
[PM] Search bar > Responsive issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3473]
1. Search bar functionality is not working on all the pages
2. UI of the Search bar should be fixed  in all the pages

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc 
1. Search bar UI is breaking 
2. Entered data in the search bar field on one page is getting retained on another page

![img211](https://user-images.githubusercontent.com/71445210/124552724-87620f80-de51-11eb-8f5c-cafdba6d197d.png)

**Comment by madhurya-btc** [comment]
@Madhud5 Please check UI breaking one.

**Comment by Madhud5** [comment]
@madhurya-btc UI issue fixed

**Comment by madhurya-btc** [comment]
@Madhud5 Please check point 3 - After searching if a user navigates to any other pages then the customer logo s not getting displayed

**Comment by nishit-v** [comment]
@madhurya-btc 3rd point is being tracked separately in #3885

**Comment by madhurya-btc** [comment]
@nishit-v thanks
@Lathan-btc please test and confirm rest all point in dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QAinstance.
