### ISSUE TITLE
[PM] Responsive issue > Footer should be center aligned

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3474]
[PM] Responsive issue > Footer should be center aligned.

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Madhud5** [comment]
HI @Lathan-btc I have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instnce.
