### ISSUE TITLE
[PM] Responsive issues > All the tables > UI issues 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3475]
Responsive issues > All the tables > UI issues
1. UI issue in table column labels
2. All the contents in the table should be aligned properly

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
