### ISSUE TITLE
[PM] Responsive issue > Multiple logos are getting displayed where the device width is small

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3477]
Responsive issue > Multiple logos are getting displayed where the device width is small

![mpl1](https://user-images.githubusercontent.com/71445210/115364061-a224d080-a1e0-11eb-9381-cc1baa0bede8.png)

**Comment by sujatha-btc** [comment]
@Lathan-btc deployed please test.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
