### ISSUE TITLE
[Android] Resources are getting displayed in the mobile app irrespective of scheduled time

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3478]
Resources are displaying in the mobile app irrespective of the scheduled time
Eg: 1. New Test Study
      2. Study on Heart disease

[Note: Issue observed only for the newly created studies]

Issue is not observed in iOS

**Comment by naveenr-btc** [comment]
The issue is because `audience `value is wrong.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue by adding new resources in dev.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest DEV build

**Comment by aswinijena100** [comment]
@Lathan-btc please test in QA and close if fixed

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
