### ISSUE TITLE
[PM] Responsive issue in hamburger menu button

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3479]
Click on the hamburger menu button > Select any one of the options like location/Myaccount/Admins/Dashboard > After selecting the option, the options page should be removed

![mbh1](https://user-images.githubusercontent.com/71445210/115501583-19b23880-a291-11eb-849c-8f39ad3b05f1.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @latha Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
