### ISSUE TITLE
[PM] Responsive issue > UI is broken for toaster messages 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3480]
UI is broken for all the toaster messages 

[Note: Issue should be fixed for all the toaster messages]

 
![mbt1](https://user-images.githubusercontent.com/71445210/115513770-14f58080-a2a1-11eb-85a6-b45ef7c92fd2.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue id fixed in the latest QA instance.
