### ISSUE TITLE
[PM] Responsive issues in Site participant registry

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3481]
The responsive issues in Site participant registry
1.Multiple buttons are getting displayed to add participant, decommission site where the width is small
2. UI issues  

![mbs1](https://user-images.githubusercontent.com/71445210/115515146-7538f200-a2a2-11eb-9052-b841b6321725.png)

3. UI issue in tables[it should be fixed for 'All, New, Disabled, Invited tab] 

![mbs2](https://user-images.githubusercontent.com/71445210/115515611-f2646700-a2a2-11eb-987c-fe367268fb07.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
@Madhud5 
A check box is not displaying in New/inited/disabled tabs to select email

![spr3](https://user-images.githubusercontent.com/71445210/121712286-346a9600-caf9-11eb-8ccd-1e4114b007a1.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc Issue is fixed in the latest QA instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc Issue is fixed in the latest QA instance.

**Comment by Madhud5** [comment]
HI @Lathan-btc Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
