### ISSUE TITLE
[PM] Responsive issue in Participant details page

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3482]
Responsive issue in Participant details page
1. Text is wrapping up with the margins
![mbpd2](https://user-images.githubusercontent.com/71445210/115522228-8d603f80-a2a9-11eb-8447-80181ee8687b.png)

2. UI issue in table
![mbpd1](https://user-images.githubusercontent.com/71445210/115522276-96e9a780-a2a9-11eb-832e-ccc79bdfa489.png)

3. Closed study > participant details page > UI issues

![mbs3](https://user-images.githubusercontent.com/71445210/115522861-1d9e8480-a2aa-11eb-8c85-bf7eda162e0a.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
@madhu 1.  issue is reproducible in the latest Dev instance
![pdp2](https://user-images.githubusercontent.com/71445210/121711220-fae55b00-caf7-11eb-9f7a-f86943bc7971.png)
latest Dev instance.

2. When a participant is in disable state, 'Resend invitation' button should not be displayed on the participant details page

![pdp3](https://user-images.githubusercontent.com/71445210/121711851-ab535f00-caf8-11eb-843a-df31f8b71e08.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
