### ISSUE TITLE
[PM] Responsive issue in Sites tab > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3483]
Responsive issue in Sites tab > UI issues
1. Add site button is wrapping up with the above text 

![mbs4](https://user-images.githubusercontent.com/71445210/115548120-b7732b00-a2c4-11eb-80a0-2838c83c2ddc.png)

2. There should be a space between images and text and other UI issues

 
![mb5](https://user-images.githubusercontent.com/71445210/115548256-e25d7f00-a2c4-11eb-8d64-29300f451f21.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  I have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
