### ISSUE TITLE
[PM] Responsive issues in Studies and Apps tab > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3484]
Responsive issues in Studies tab > UI issues

1. Studies tab

![mb8](https://user-images.githubusercontent.com/71445210/115549680-8e539a00-a2c6-11eb-9acd-e04397c58fa9.png)

2. Apps app

![mba11](https://user-images.githubusercontent.com/71445210/115550158-2487c000-a2c7-11eb-9fc6-4b155f8e335a.png)

**Comment by Madhud5** [comment]
hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
