### ISSUE TITLE
[SB] Questionnaire > Question step/Form step > Fields are not displaying in 'Response level attributes'

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3485]
Questionnaire > Question step/Form step > Fields are not displaying in 'Response level attributes'

[Note: 1. Cancel/Save/Done buttons also not working
           2. It should be fixed for all the response types]

![sb1](https://user-images.githubusercontent.com/71445210/115552889-6a925300-a2ca-11eb-9519-0eff91089708.png)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test in QA and close if fixed.

Note : No PR required for this fix

**Comment by Lathan-btc** [comment]
Issue is not reproducible in the latest QA instance.
