### ISSUE TITLE
[PM] Responsive issue when user clicks on the logo

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3487]
AR: Studies tab is getting highlighted when the user click s on the customer logo 
ER: Sites tab should be highlighted when the user clicks on the customer logo

![mbss](https://user-images.githubusercontent.com/71445210/115670194-c5798800-a366-11eb-9bf4-75d9092219c0.png)

**Comment by Madhud5** [comment]
hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
HI @Lathan-btc  have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
