### ISSUE TITLE
[PM] Responsive issues in My account screen > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3488]
Responsive issues in My account screen > Contents are wrapping up with the margins and above frame (All the buttons)

![mbm1](https://user-images.githubusercontent.com/71445210/115671051-b9da9100-a367-11eb-94a3-ee87a413bd26.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
