### ISSUE TITLE
[PM] Responsive issue in Change password screen > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3489]
Responsive issue in the Change password screen > UI issues

![mbc](https://user-images.githubusercontent.com/71445210/115671667-5f8e0000-a368-11eb-8573-eeda2bfc11b4.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
