### ISSUE TITLE
[SB][QA] Users > Add user > Issue in Role 'dropdown' values

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3492]
Users > Add user > Issue in Role dropdown
AR: 'Project lead' and 'Study admin' values are displayed
ER: 'Superadmin' and 'Study admin' should be displayed

[Note: Issues should be fixed in Add user/Edit user/Manage users screens]
  
![sbqa](https://user-images.githubusercontent.com/71445210/115727246-0db59c00-a3a1-11eb-914b-e4aa37e28b8b.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please test and update the ticket accordingly

**Comment by Lathan-btc** [comment]
@Kantharajut-btc Selected values from the 'Filter by role' dropdown is not getting reflected


![drop1](https://user-images.githubusercontent.com/71445210/116552570-cede9380-a916-11eb-86d4-d6dbd63b601e.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please retest this issue in dev and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
