### ISSUE TITLE
[Mobile apps] Consent is not displaying in proper format when user clicks on 'View consent' button

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3494]
Steps
1. Click on any study
2. Click on the 'View consent' button 
3. Observe

AR: Consent is not displayed in a proper format
ER: Consent should be displayed in a proper format

![image](https://user-images.githubusercontent.com/71445210/116063038-1dcfc300-a6a2-11eb-8ae4-3bd9b837e02e.png)

**Comment by naveenr-btc** [comment]
I believe the format is changed, reverting it back should be fine for mobile apps.

**Comment by navya-BTC** [comment]
@Lathan-btc please test in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by nishit-v** [comment]
Issue is observed again for Android for 'View consent' screen.

Instance: Dev
Study ID: copied1201

![Copied1201](https://user-images.githubusercontent.com/60386291/120970804-88881a00-c789-11eb-89f3-a6c972254777.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test the issue

**Comment by Lathan-btc** [comment]
@navya-BTC Issue is reproducible for android users

![image](https://user-images.githubusercontent.com/71445210/121550053-02d7c900-ca2c-11eb-8022-20d2a1af237d.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test in dev

**Comment by Lathan-btc** [comment]
@navya-BTC UI is breaking for both Android and IOS

![image](https://user-images.githubusercontent.com/71445210/121656565-3e6ea380-cabd-11eb-8055-3d053086204c.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nagarjunav1** [comment]
Issue is again reproducing in Dev build

![image](https://user-images.githubusercontent.com/60500517/122232357-cd722600-ced8-11eb-9e91-96d064c6543c.png)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
