### ISSUE TITLE
[SB] Image file formats accepting other than JPG or PNG image type

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3503]
**Steps:**
1. Download a image file format other than JPG or PNG with VALID image resolution (Eg. 225*225 of GIF or BMP format)
2. Edit a study
3. Navigate to basic information screen
4. Click on Upload
5. Select 'All files' in windows screen
6. Select GIF or BMP format
7. Observe

**Actual:** Image file formats accepting other than JPG or PNG image type

**Expected:** Image file formats should accept only JPG or PNG image type

Note: Issue observed for 
1. Thumbnail images
2. Overview images (1st screen)
3. Overview images (2nd to 5th)
4. Image choice questions

Refer attached video:

https://user-images.githubusercontent.com/60386291/116235196-2e07a100-a77b-11eb-9b5f-ea589a5723a8.mp4

**Comment by pujithr** [comment]
@nishit-v please test this issue in dev and update the ticket accordingly.

**Comment by nishit-v** [comment]
Issue is resolved in the latest Dev instance SB build.

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
