### ISSUE TITLE
[SB] Edit user details page > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3504]
Edit user details page > Use proper text case for resend invitation link
AR: The displayed text is 'Re-send Activation Link' 
ER: Displayed text should be 'Re-send activation link' 

![u1](https://user-images.githubusercontent.com/71445210/116362105-534deb00-a81f-11eb-9507-9051a69a7e01.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in Dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
