### ISSUE TITLE
[SB] Replace 'user' with 'admin' in Study builder

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3505]
Terms 'user' should be replaced with 'admin' across the application
Eg: buttons labels, titles and toast messages, etc.. 

![admin1](https://user-images.githubusercontent.com/71445210/116372405-01f72900-a82a-11eb-8ed2-d139f4edb202.png)

**Comment by navya-BTC** [comment]
@Lathan-btc, please test in dev

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
