### ISSUE TITLE
[Auth server][Mobile apps]  Sign in screen > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3506]
Sign in screen > UI issue

[**Note:** Issue observed only in Mobile apps] 

![mbs5](https://user-images.githubusercontent.com/71445210/116398590-97ec7d00-a845-11eb-9d48-41564b4f0296.png)

**Comment by harisboston** [comment]
@Lathan-btc This issue is fixed in dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc This issue is fixed in QA environment, kindly test and update this ticket.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
