### ISSUE TITLE
[QA] Push notifications not triggered from SB

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3508]
**Steps:**
1. Send a manual app level/study level notification
2. Observe the status in 'Notifications' screen

**Actual:** Push notifications not triggered from SB and status is 'Sending'

**Expected:** Push notifications should be triggered

Note: Issue tested in QA
Issue also observed for automated push notifications

![Screenshot_1](https://user-images.githubusercontent.com/60386291/116519461-223ceb80-a8ef-11eb-81ea-5416854ddaa9.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by nishit-v** [comment]
Issue is again observed in RC 2.0.6 branch 

![Screenshot_5](https://user-images.githubusercontent.com/60386291/125324051-20ff5480-e35d-11eb-8b5d-d767655fdd5e.png)

**Comment by aswinijena100** [comment]
@nishit-v Please verify now .  App information update was not done during the deployment .

**Comment by nishit-v** [comment]
Issue is resolved in latest RC 2.0.6 env
