### ISSUE TITLE
[SB] Functional issue in Active tasks

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3515]
**Scenario 1**
Steps
1. Click on Add Active task
2. Select any one of the pre-defined active tasks from the drop-down
3. Navigate to schedule tab and Daily frequency under anchor date-based/Regular
4. Enter all required fields in the schedule tab
5. Navigate Content tab
6. Enter all the required values
7. Select 'Add to line chart' don't enter any values under it
8. Click on the Done button
9. Observe

AR : Error message is not displayed
ER : 'Please select an item in the list' error message should be displayed in the same line

**Scenario 2**
Steps
1. Click on Add Active task
2. Select any one of the pre-defined active tasks from the drop-down
3. Navigate to schedule tab and Daily frequency under anchor date-based/Regular
4. Enter all required fields in the schedule tab
5. Navigate Content tab
6. Enter all the required values
7. Select 'Add to line chart' don't enter any values under it
8. Enter the required values under 'line chart' except 'Time range for the chart'
9. Click on the Done button
10. Observe 

AR: User is able to create an active task without entering the  'Time range for the chart' mandatory field
ER: User should not be able to create an active task without entering the mandatory field

[Note: Issue should be fixed for Anchor date-based, Regular, Daily, Weekly, Monthly and Custom schedule] 

https://user-images.githubusercontent.com/71445210/116656228-f3d01680-a9a9-11eb-8004-66b82bafcad0.mp4

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
