### ISSUE TITLE
[SB] Consent sections are not reflecting in auto-created consent document

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3526]
Consent sections added into the Study Builder are not reflecting in the auto-created consent document field in the E-Consent steps screen.
Issue is observed in some cases only and could be related to the fonts used (see #1288 )

![image](https://user-images.githubusercontent.com/60500517/116849300-1fead200-ac0c-11eb-9fc9-80f217bfccaa.png)

**Comment by pujithr** [comment]
@nagarjunav1 please test this issue in DEV ENV and update ticket accordingly

**Comment by nagarjunav1** [comment]
![image](https://user-images.githubusercontent.com/60500517/119304856-8734f880-bc85-11eb-939b-ea2f7f20eceb.png)

![image](https://user-images.githubusercontent.com/60500517/119304695-4341f380-bc85-11eb-8b6a-705ddaddd909.png)

Still issue is reproducing in latest DEV

**Comment by pujithr** [comment]
@nagarjunav1. Changes are deployed. Please test in latest Dev Ins and update the ticket.

**Comment by pujithr** [comment]
@nagarjunav1. PR has merged. Please verify this issue in QA ins and update the ticket

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
