### ISSUE TITLE
[SB] Questionnaires > Question step > Text choice response type > Issue in 'Response level attributes' 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3529]
Steps 
1. Add/Edit questionnaire
2. Add question step
3. Select 'Text choice' response type in 'Question level attributes' tab
4. Navigate to the 'Response level attributes' tab
5. Select 'Include 'Other' as an option?'
6. Enter all the mandatory fields 
7. Select the 'Yes' radio button for the 'Include text field to specify 'Other'?'
7. Click on the Done button and Observe

AR: User is not able to create question step without entering 'Place holder text for the text field'
ER: User should be able to create a question step without entering 'Place holder text for the text field' because this is not a mandatory field

[Note: Correct the label of the text field from 'Place holder' to 'Placeholder]  

![ig1](https://user-images.githubusercontent.com/71445210/116869383-43bf0f80-ac2e-11eb-9597-50b129c073ce.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nagarjunav1** [comment]
Issue is not fixed in QA build

**Comment by nagarjunav1** [comment]
![image](https://user-images.githubusercontent.com/60500517/117263803-46a94280-ae70-11eb-90a3-26f37b73d346.png)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
