### ISSUE TITLE
Adjust login screen for stand-alone app

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#353]
- When signed out of the of standalone app, the first screen shows a button to "join study"
- This makes sense for someone who has never used the app before, but for participant who has already joined the study and is just signed-out this is confusing
- This screen should instead show sign-in and sign-up options
- When only a single page of content is configured on this screen, there is still a dot icon being rendered (which is left over from the UI elements that indicate the user can swipe between screens)
- This dot should not be rendered if there is only one screen

This was only tested on iOS, but may apply to Android as well.

Screenshot attached.

![IMG-4774](https://user-images.githubusercontent.com/35972680/81239902-00f33900-8fd4-11ea-89b2-f263ad84392f.PNG)

**Comment by SR-btc** [comment]
Addressed via #59
