### ISSUE TITLE
[SB] Questionnaires/Active tasks > Issue in Schedule tab

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3530]
Steps
1. Go to Active tasks
2. Click on Add active task
3. Enter all the mandatory fields in the Content tab
4. Navigate to the Schedule tab
5. Select anchor date based and click on Save
6. Switch back to Regular and select Weekly frequency
7. Click on Done and Observe the Time field of the week

AR: Error message is not getting displayed and the user is able to create an activity without entering the Time field  
ER: 'Please fill out this field' error message should be displayed

[**Note:** 1. If the user clicks on the 'Done' button instead of 'Save' in step 5 then user is able to create an activity without entering Day/Time (of the week)
2. Issue should be fixed for weekly and Monthly frequency and for both questionnaires and active tasks] 

https://user-images.githubusercontent.com/71445210/116880081-2fcfd980-ac3f-11eb-8954-18a2eb8da1ac.mp4

**Comment by navya-BTC** [comment]
@Lathan-btc please test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
