### ISSUE TITLE
[Android] User should be redirected to Password help screen for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3531]
**Steps**
1. Install mobile app in the device
2. Open the app
3. Click on Sign up
4. Enter all the required field and click on submit
5. After navigating to the verification step, without entering the verification code kill the app
6. Open the app
7. Click on forgot password
8. Enter a valid email and click on submit button
9. Enter verification code and click on done
10. Observe

**AR:** User is redirected to the Sign-in screen 
**ER:** User should be redirected to Password help screen

[**Note:** This is a scenario where a user attempts forgot a password without verifying the account]

**Comment by Lathan-btc** [comment]
@naveenr-btc After redirecting Password help screen if user enter registered email and click on submit button then **confirmation messages** is not getting displayed for the above mentioned scenario

**For reference:** in the normal flow

![image](https://user-images.githubusercontent.com/71445210/123396808-5ff08480-d5bf-11eb-8a04-2f44175245e7.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest Android build 1.0(91) pointing to Dev
