### ISSUE TITLE
[SB] Modify the text format for toast messages

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3532]
1. Remove the full stop at the end of the toast messages where ever it is not required
2. Use proper text case for the toast messages 
 Eg: 'Question Step added successfully.' should be changed to 'Question step added successfully'  

![tm1](https://user-images.githubusercontent.com/71445210/116971017-92c07f80-acd6-11eb-9910-82dbadad6ad1.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev.

**Comment by Lathan-btc** [comment]
@monica-BTC Issue is reproducible in the 'My account' screen

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
