### ISSUE TITLE
Build fails in xcode 12.5

### ISSUE THREAD

**Issue by alanhughes** [GoogleCloudPlatform/fda-mystudies#3536]
**Describe the bug**
After downloading the latest xcode version 12.5, the warning 
```
'exported: true' has no effect in '_specialize' attribute
```
e.g. [here](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/v2.0.4/iOS/MyStudies/Pods/CryptoSwift/Sources/CryptoSwift/UInt64+Extension.swift#L23)  has become an error, and the build fails accordingly.

**To Reproduce**
Attempt to compile the iOS app on xcode 12.5

**Expected behavior**
The app compiles

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: [Xcode 12.5](https://download.developer.apple.com/Developer_Tools/Xcode_12.5/Xcode_12.5.xip)

**Labels**
iOS

**Comment by smunini** [comment]
@alanhughes, I needed to upgrade CryptoSwift to the latest version to fix this issue.

**Comment by amruthbtc** [comment]
This issue is related to #3566 and once it is fixed, #3536 will also be resolved.

**Comment by nishit-v** [comment]
Handled as part of 2.0.7 release
