### ISSUE TITLE
Summernote not saving formatting in Study Builder

### ISSUE THREAD

**Issue by smunini** [GoogleCloudPlatform/fda-mystudies#3540]
**Describe the bug**
The Summernote plugin is failing to store formatting.

**To Reproduce**
1. Go to a Consent Section in the Study Builder
2. Add some bullets in the Description section.
3. Select Save then Done
4. View or Edit the consent item - All formatting has been removed.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 90.0.4430.93

<img width="946" alt="Screen Shot 2021-05-06 at 8 29 41 PM" src="https://user-images.githubusercontent.com/4219075/117381617-7d03b380-aeaa-11eb-9ac5-bb7a7c2de58f.png">

After re-opening the Consent Section.
<img width="933" alt="Screen Shot 2021-05-06 at 8 30 00 PM" src="https://user-images.githubusercontent.com/4219075/117381632-84c35800-aeaa-11eb-9501-47ccfb885b2a.png">

**Comment by SR-btc** [comment]
#1288 has been reported and is in progress. That should fix this.

**Comment by pujithr** [comment]
@Lathan-btc .please test in DEV Ins and update ticket accordingly

**Comment by pujithr** [comment]
@nagarjunav1 please test in DEV Ins and update ticket accordingly

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by pujithr** [comment]
@nagarjunav1.PR has merged. Please verify this issue in QA ins and update the ticket

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
