### ISSUE TITLE
Multiple Overview pages are not showing in the mobile app.  Also, missing font information.

### ISSUE THREAD

**Issue by smunini** [GoogleCloudPlatform/fda-mystudies#3541]
**Describe the bug**
We have configured multiple Overview sections in Study Builder.  Only the first page appears in the mobile app.  Additionally, the font is ignored in the mobile app and the text is very small.

**To Reproduce**
1. Go to the Study Builder, and create multiple Overview Pages.
3. Only the first page is displayed.

<img width="1214" alt="Screen Shot 2021-05-06 at 9 09 29 PM" src="https://user-images.githubusercontent.com/4219075/117384001-fbaf1f80-aeaf-11eb-85a3-85a78128ce47.png">

<img width="423" alt="Screen Shot 2021-05-06 at 9 08 20 PM" src="https://user-images.githubusercontent.com/4219075/117384018-02d62d80-aeb0-11eb-94c1-b42d571a0d1f.png">

**Comment by smunini** [comment]
I suspect that this may be another issue with summernote, but I'm not yet entirely sure.

**Comment by SR-btc** [comment]
Thanks for the update on the multiple overview pages issue. For the fonts issue, it is to do with the summernote editor. Please see #1288 which is underway already that should help fix it.

**Comment by SR-btc** [comment]
@nagarjunav1 please verify if the summernote editor fix , has resolved this issue

**Comment by nagarjunav1** [comment]
Closing this ticket as no feedback from the user. Reopen this ticket if issue still exist in the latest builds
