### ISSUE TITLE
[SB] Active task > Schedule tab > Regular > Weekly frequency > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3543]
Active task > Schedule tab > Regular > Weekly frequency > Error messages are getting overlapped 

[Note: 1. The issue should be fixed for both active task and questionnaires
           2. In questionnaires wrong error message is displayed 
           3. Change the error message 'Please fill out this field' to 'Please select an item in the list'] 

![error12](https://user-images.githubusercontent.com/71445210/117421921-a5d48900-af3c-11eb-84d2-fa933525bff0.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
