### ISSUE TITLE
[SB] Resources > User is able to click on the mark as completed even though added resources are in draft

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3546]
Steps
1. Create/Edit study
2. Navigate to the Resources section
3. Add more than 1 resource ( Resources should be in draft)
4. Delete any one of the resources
5. Click on the mark as complete button and observe

AR: User is able to click on the 'Mark as completed' button
ER: 'Mark as completed button should be disabled and it should display the highlighted text in the following screenshot when user mouse hovered on the button
    
![res1](https://user-images.githubusercontent.com/71445210/117650948-f521f000-b1ae-11eb-92fc-1cf73a446b92.png)

**Comment by pujithr** [comment]
@Lathan-btc Please verify this issue and update ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by pujithr** [comment]
@Lathan-btc Please verify this issue in QA ENV and update ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
