### ISSUE TITLE
Support rich text in study overview description

### ISSUE THREAD

**Issue by morethanreal** [GoogleCloudPlatform/fda-mystudies#355]
The description in the "basic information" section in the WCP supports rich text, but the one in the "overview" section doesn't. Both should support rich text.

**Comment by pujithr** [comment]
To test in Dev Ins

**Comment by nagarjunav1** [comment]
![image](https://user-images.githubusercontent.com/60500517/111737022-df760580-88a4-11eb-93d5-1ae65a02f7e4.png)
![image](https://user-images.githubusercontent.com/60500517/111737252-45628d00-88a5-11eb-9f0e-040aad760096.png)

1. HTML breakage is happened in mobile in Overview screens both in Android and iOS.
2. Complete text is not displaying from 2nd screen to 5th screen of Overview

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build for Android

**Comment by nagarjunav1** [comment]
Changes needed in Rich text Editor in Overview screens
1. Apply the character limit for RTE to 200 characters max.
2. Modify the field name  to **Description (200 characters max) ***

Note:- Above changes need to do for all the 5 pages in Overview

**Comment by pujithr** [comment]
@nagarjunav1.Changes are made as mentioned and deployed to DEV INS. Please verify in DEV instance and update ticket accordingly.

**Comment by nagarjunav1** [comment]
Changes made are working and no issues found. @pujithr

**Comment by nishit-v** [comment]
Issues in iOS:
1. Hyperlinks displaying in grey color instead of default blue color
2. Overview 1st page displaying in black colour

![2](https://user-images.githubusercontent.com/60386291/116691413-67891800-a9d8-11eb-92e3-33648cf6b6d3.png)
![1st](https://user-images.githubusercontent.com/60386291/116691432-6bb53580-a9d8-11eb-850e-9eb9dc49b8c5.png)

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test this issue in QA and close if fixed

**Comment by nagarjunav1** [comment]
Waiting for QA android build @naveenr-btc

**Comment by nishit-v** [comment]
Issue is resolved in latest SB and iOS build (V1.0.203) in QA instance.

**Comment by nagarjunav1** [comment]
Issue is resolved in latest android build (v1.0.81) in QA instance
