### ISSUE TITLE
[SB] Active task > Schedule tab > Weekly or Monthly frequency > issue in time field 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3550]
Steps
1. Create/Edit study
2. Navigate to the Active tasks section
3. Add Active task 
4. Enter all the mandatory values in the Content tab
5. Switch to the Schedule tab and Select Regular
6. Select any frequency and enter the time in the time field and click on Save ( lets entered time is 6.30)
7. Switch to Weekly or Monthly frequency
8. Enter a time other than 6.30 and Click on Save 
9. Observe the time in the time fields 

AR: Previously selected and saved time (6.30) is getting displayed (Selected time in step 6 is getting displayed) 
ER: Currently entered and saved time should be displayed ( Selected time in step 8 should be displayed)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
