### ISSUE TITLE
Type Choice no longer works - along with others

### ISSUE THREAD

**Issue by smunini** [GoogleCloudPlatform/fda-mystudies#3551]
Renaming of the fields failed to also update the text in the code causing several of the selections to be unavailable.  

"Text Choice" != "Text choice"

<img width="1273" alt="Screen Shot 2021-05-10 at 8 59 42 PM" src="https://user-images.githubusercontent.com/4219075/117742515-f5cc7d80-b1d2-11eb-93c8-db0e9783233d.png">

**Comment by aswinijena100** [comment]
@smunini We found the issue and PR #3619 is raised and merged with develop. it will be available with release 2.0.6

**Comment by nishit-v** [comment]
This fix is available as part of 2.0.6 release.
