### ISSUE TITLE
[SB] Study level notifications > info icon text is not displayed after launching the study 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3555]
Steps
1. Edit study ( Study should be in Active status)
2. Navigate to the 'Notification' section
3. Click on Add notification 
4. Mouse hover on info icon of the 'Schedule this notification'
5. Observe

AR: Info icon text is not displayed 
ER: Info icon text should be displayed when the user mouse hovered on the info icon
Text: 'The notification gets delivered to mobile app users at the selected date and time as per server time zone which is EDT.'

[Note: 1. Issue observed only for the launched studies
           2. Issue Observed only in QA instance] 

![notifi1](https://user-images.githubusercontent.com/71445210/117824465-23c1c880-b28c-11eb-8bf0-3979e49dc428.png)

**Comment by aswinijena100** [comment]
@Lathan-btc Please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
