### ISSUE TITLE
[SB] Edit resource > 'Select anchor date type' dropdown is enabled for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3558]
Steps
1. Create/Edit study
2. Navigate to the Resources section
3. Click on Add resource
4. Enter all the mandatory fields
5. 'No' radio button should be selected under the period of visibility of the resource
6. Click on Save/Done button
7. Navigate to Edit resource screen and Observe the dropdown

AR: 'Select anchor date type' dropdown is enabled even though 'No' radio button is selected
ER: 'Select anchor date type' dropdown should be disabled

![rsrc1](https://user-images.githubusercontent.com/71445210/117841796-f4ff1e80-b29a-11eb-970c-a8428ec3eedc.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev environment and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test this issue in QA and close if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
