### ISSUE TITLE
[SB] Active task > Success message needs to be corrected when a user adds an active task 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3563]
Steps
1. Create/Edit study
2. Navigate to the Active tasks section
3. Click on Add active task
4. Enter all the mandatory fields and click on Done
5. Observe the success message

AR: 'Active task updated successfully' success message is displayed
ER: 'Active task created successfully' should be displayed

![tm2](https://user-images.githubusercontent.com/71445210/117944226-a8632400-b32a-11eb-988b-43d75650304d.png)

**Comment by madhurya-btc** [comment]
Please test and confirm in Dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc If the user saves the changes first and then clicks on the 'Done' button the following success message should be displayed
Success message: 'Active task updated successfully'
AR: 'Active task created successfully' is getting displayed

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA instance
