### ISSUE TITLE
[SB] Questionnaires > Add question step/form step > Issue in date picker

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3564]
Steps
1. Add/Edit questionnaire
2. Click on add question step/Form step 
3. Question level attributes > Select 'Date' response type
4. Response level attributes > select 'Custom'
4. Click on the Date fields and observe

AR: All the dates and months are displaying in the time picker and able to select a date which is before the current server date ( eg: 
 If the Current date is 5/12/2021 but the user is able to select 5/7/2021)
ER: User should be able to select only from the current server date

![datepickr2](https://user-images.githubusercontent.com/71445210/117946738-32ac8780-b32d-11eb-801c-c9cbc1c9601b.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
