### ISSUE TITLE
[SB] Overview > Description field should allow 200 characters max

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3567]
AR: Overview > Description field is allowing only 199 characters max
ER: Rich text editor should allow 200 characters max 

[Note: If user copy the text which is equal to or more than 200 characters and paste the same text into the description field and observes the number of characters it is taking randomly eg: 199, 198 characters]

![RTE](https://user-images.githubusercontent.com/71445210/117996463-cb5bfb00-b35f-11eb-9a56-4aab3ab32599.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance.

**Comment by Lathan-btc** [comment]
'This issue has been reported to be caused by the summer note editor behavior. Closing it for now as it is a low priority issue, and a fix is not immediately available.'
