### ISSUE TITLE
[iOS] Push notifications are not triggered to iOS on disabling and re-enabling the 'Receive Push Notifications?' option

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3568]
**Steps:**

1. Login/Signup into mobile
2. Navigate to my account
3. Disable 'Receive Push Notifications?'
4. Send push notification from SB. Push notifications are not triggered to iOS
5. Enable the option 'Receive Push Notifications?' again
6. Send push notification from SB and Observe

**Actual:** Push notifications are not triggered to iOS on disabling and enabling the 'Receive Push Notifications?' option

**Expected:** Push notifications should be triggered. 

1. Issue not observed in Android.
2. Issue not observed once user logs out and logs in again after step 5

**Comment by nishit-v** [comment]
Issue is resolved in latest iOS build V1.0.207 pointing to QA instance (Before PR)

**Comment by aswinijena100** [comment]
@nishit-v Please test this issue in QA and close the ticket if fixed .

**Comment by nishit-v** [comment]
Issue is resolved in latest iOS build V1.0.207 pointing to QA instance (After PR)
