### ISSUE TITLE
[SB] Study settings page > Wrong error message is getting displayed for the following scenario 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3572]
Steps
1. Create/Edit study
2. Study settings > Select 'Yes' radio button to use enrollment date as anchor date
3. Click on the mark as completed
4. Add any activity/resource by using enrollment date as an anchor date
5. Navigate to the study setting page 
6. Select 'No' radio button to use enrollment date as anchor date
7. Click on Save/Done button and observe

AR: Getting the wrong error message
ER: 'You have chosen not to use enrollment date as an anchor date. You will need to revise the schedules of activities or resources, if any, that were set based on the enrollment date as anchor date.' Buttons: Ok'  warning message should be displayed in a pop-up

![anchor21](https://user-images.githubusercontent.com/71445210/118003747-77084980-b366-11eb-80ee-34e44d7419b9.png)

**Comment by madhurya-btc** [comment]
Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
