### ISSUE TITLE
Study-builder fails to build in Cloud Build

### ISSUE THREAD

**Issue by rpbaquing-stratusmeridian** [GoogleCloudPlatform/fda-mystudies#3573]
**What are you trying to accomplish?**
To complete the deployment of the platform.

**What challenge are you running into?**

I am following the deployment guide and currently stuck on the application configuration stage.
The other images were built except for study-builder. It didn't went to the check in Github Actions because the directory fdahpStudyDesigner it checks doesn't have any changes.

![image](https://user-images.githubusercontent.com/82572819/118092420-acf90c80-b3fe-11eb-9b02-b421e1827cb1.png)

![image](https://user-images.githubusercontent.com/82572819/118091690-b2a22280-b3fd-11eb-8e15-b332e1155ad5.png)

---

ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
ERROR
The command '/bin/sh -c mvn package' returned a non-zero code: 1
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] Please refer to /app/target/surefire-reports for the individual test results.
[ERROR] 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project fdahpStudyDesigner: There are test failures.
[INFO] ------------------------------------------------------------------------
[INFO] Finished at: 2021-05-13T06:46:56Z
[INFO] Total time:  01:55 min
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Tests run: 77, Failures: 0, Errors: 2, Skipped: 0

  shouldAddUserDetails(com.fdahpstudydesigner.controller.UsersControllerTest)
  shouldResendActivateDetailsLink(com.fdahpstudydesigner.controller.UsersControllerTest)

---

**What have your tried so far?**
Initially after merging the pull request so the images will be built in the apps project, both auth-server and study-builder failed. I did a retry on both and successfully built the auth-server image. However, after 4 retries in study-builder. It was still failing for me. 

![image](https://user-images.githubusercontent.com/82572819/118091601-97371780-b3fd-11eb-89e6-7b010d3f0195.png)

**Labels**
study-builder

**Comment by mohangmk** [comment]
@rpbaquing-stratusmeridian 
Please share cloudbuild.yaml which you're using it for study builder deployment, and also please confirm which Release Version of master you have used for environment setup

To confirm the version
Please visit ./documentation/whats-new.md and check the top version number.

**Comment by rpbaquing-stratusmeridian** [comment]
@mohangmk version is Release 2.0.4

Here's the cloudbuild yaml file contents:

```bash
# Copyright 2020 Google LLC# Use of this source code is governed by an MIT-style# license that can be found in the LICENSE file or at# https://opensource.org/licenses/MIT.
steps:  
  - name: 'gcr.io/cloud-builders/docker'    
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/study-builder', '.']    
    dir: "study-builder"

images: ['gcr.io/$PROJECT_ID/study-builder']
```

**Comment by aswinijena100** [comment]
@rpbaquing-stratusmeridian latest release 2.0.5 is live now. Could you please upgrade it and retry . Please do let us know if you still face the same issue with release version 2.0.5.

**Comment by rpbaquing-stratusmeridian** [comment]
@aswinijena100 @mohangmk I've tested the new release 2.0.5 and confirmed that the issue has been fixed. Thank you for your support
