### ISSUE TITLE
Unable to upload Study Thumbnail Image

### ISSUE THREAD

**Issue by bdoohan-goog** [GoogleCloudPlatform/fda-mystudies#3576]
**Describe the bug**
When creating a new study I am unable to Upload an Image, even if I use [one of these images from the github repo](https://github.com/GoogleCloudPlatform/fda-mystudies/tree/master/study-builder).

**To Reproduce**
1. Go to 'https://studies.mystudies-demo.hcls.joonix.net/studybuilder/adminStudies/viewBasicInfo.do'
2. Click on 'Upload Image'
3. See error "Please upload image as per provided guidelines."

**Expected behavior**
I expect the photo to be uploaded.

**Screenshots**
Screenshots below.

![image](https://user-images.githubusercontent.com/74371449/118178433-eda65500-b401-11eb-8123-678461e0be11.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Debian, etc] Linux
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Not sure .. . 

**Additional context**
This is my first time creating a study on the joonix account.

**Logs**
Any relevant logs that you can provide. Please remove any identifying information.

**Labels**
Please add a label that identifies what component(s) this issue applies to.
#Blocker  #Feedback

**Comment by SR-btc** [comment]
Could you please confirm which release you are using (2.0.4 or earlier?)

**Comment by bdoohan-goog** [comment]
Hi - Is there a way to tell from the Studies Manager UI or the Participant Manager UI? I am using a demo version from my employer and did not take part in setting it up.

**Comment by bdoohan-goog** [comment]
It is 2.0.0

**Comment by SR-btc** [comment]
Please try uploading an image as per the given guidelines (see the 'i' info icon next to the field name). Alternatively, you could upgrade to the latest code (2.0.4) or 2.0.5 which is out for release in a day or so - these have images uploaded already by default and also allow you to upload a broader range of sizes if you wish to over-ride the default image.

**Comment by aswinijena100** [comment]
@bdoohan-goog 2.0.5 release is live now . Could you please update on this ticket if it fixed with the latest release .

**Comment by aswinijena100** [comment]
@bdoohan-goog fix for this is live now , hence closing this ticket . Please reopen the ticket if still exist with release v2.0.5.
