### ISSUE TITLE
Deployment Read me document update-2

### ISSUE THREAD

**Issue by mohangmk** [GoogleCloudPlatform/fda-mystudies#3578]
@moschetti 

After provisioning the Devops project, we are unable to connect the repository  for cloud builds, as we are facing with the below error, when trying to access any resources in the project.
  
" You do not have permission to see this information"

![image (1)](https://user-images.githubusercontent.com/60384913/118262603-bb185d00-b4d2-11eb-9234-8a9a6bb5eb11.png)

To solve this issue, we need to provide "Project Owner access for the folder to see all resources and connecting repositories for cloud builds to any project in the folder.

**Comment by moschetti** [comment]
The deployment guide instructs users to add their user to the group `{PREFIX}-{ENV}-devops-owners@{DOMAIN}` which will add your user to that group, and that group will have the owner role in the devops project.
