### ISSUE TITLE
[SB] Consent section > Add/Edit consent > Entered data in multiple lines is getting displayed in a single line  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3579]
Steps
1. Create/Edit study
2. Navigate to the Consent section
3. Add/Edit consent enter all the mandatory fields 
4. In the 'Long description' field enter the data in multiple lines
5. Click on the Done button
6. Navigate to edit consent page
7. Observe the data in the long description  

AR: Entered data in multiple lines is getting displayed in the single line
ER: Entered data should be displayed properly 

![cs1](https://user-images.githubusercontent.com/71445210/118440890-f8186580-b705-11eb-820e-71c23b018f64.png)

**Comment by Lathan-btc** [comment]
This issue will be tracked in #3540

**Comment by SR-btc** [comment]
The original ticket is #1288.

Reopening this, to be tested after 1288 is fixed

**Comment by pujithr** [comment]
@Lathan-btc . Please verify in DEV ins and update ticket accordingly

**Comment by Lathan-btc** [comment]
@pujithr issue should also be fixed in the 'Brief summary' field

**Comment by pujithr** [comment]
@nagarjunav1 please test in DEV Ins and update ticket accordingly

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by pujithr** [comment]
@nagarjunav1. PR has merged. Please verify this issue in QA ins and update the ticket
