### ISSUE TITLE
[SB] Admins > Edit admin details > Issue in the studies dropdown  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3581]
Steps
1. Login into SB
2. Navigate to Admins tab
3. Add an admin with Superadmin role
4. Navigate to Edit admin details page
5. Change the role to Study admin
6. Click on 'Remove all' under permissions
7. Click on the 'Select and add studies' dropdown
8. Select one or more studies and click on the + icon 
9. Again click on the 'Select and add studies' dropdown and observe

AR: In the drop-down, it is showing 'All items are already selected' text
ER: Dropdown should display all the studies which are not assigned

![ad1](https://user-images.githubusercontent.com/71445210/118447905-ed160300-b70e-11eb-8802-1e7fe255fa92.png)

**Comment by Lathan-btc** [comment]
@monica-BTC Issue should also be fixed for the following scenario
Steps
1. Click on the Admins tab
2. Click on Add admin
3. select 'Study admin' role
4. Select all the studies and click on the '+' icon
5. Click on 'Remove all' 
6. Click on the 'Select and add studies' dropdown and observe

AR: Empty list is displayed
ER: All the studies should be displayed in the dropdown


![img114](https://user-images.githubusercontent.com/71445210/118646904-650f2680-b7fe-11eb-8b0a-137d0169f562.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in new Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
