### ISSUE TITLE
[SB] Add/Edit questionnaire > Add question step/Form step > Response level attributes > Use the proper text case for the inline error messages

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3582]
1. Add/Edit questionnaires 
 2. Add question step/Form step 
 3. Select 'Date' response type in 'Question level attributes' tab
 4. Switch to Response level attributes
 5. Observe the text case of the error messages for the highlighted fields in the attached screenshot 

AR: Text case usage is not proper
ER: Remove the capitalization of the letters wherever it is not necessary

![EM3](https://user-images.githubusercontent.com/71445210/118453092-74b24080-b714-11eb-99a1-fb9b503f5a64.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
