### ISSUE TITLE
Remove first column from email list import template

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3585]
When importing a list of participants into the Participant Manager, users can download a template to use. The template has a column (the first one for serial number) that is unnecessary and can be removed.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in new dev environment and update.

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev Instance

**Comment by aswinijena100** [comment]
@nishit-v please test this issue in QA and close if fixed

**Comment by nishit-v** [comment]
Issue is resolved in latest QA Instance
