### ISSUE TITLE
[SB] Create/Edit study > E-consent steps > Data sharing permission > Text case usage issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3586]
Steps
1. Create/Edit study
2. Navigate to the E-consent steps section
3. Select the 'Yes' radio button in the 'Data sharing permission'
4. Use the proper text case

![tc1](https://user-images.githubusercontent.com/71445210/118512614-97624a80-b750-11eb-863c-1330d02ff031.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in dev environment, kindly test and update this ticket

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
