### ISSUE TITLE
[PM] Need to increase detectable area for Password Criteria icon (?) in change Password screen

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3596]
Steps:
1. Login into Participant manager 
2. Navigate to My Account section
3. Click on Change Password link
4. Verify the password criteria icon in change password screen

**A/R**:- Detectable area for Password Criteria icon is very less.
**E/R**:- Detectable area should be increase for Password Criteria icon for better user experience

**Note**:- Need to fix the above issue wherever Password criteria icon appears.

![image](https://user-images.githubusercontent.com/60500517/118836324-5e0d1480-b8e1-11eb-9340-1aabc44a526c.png)

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc due to the #3615 issue I'm unable to test in the setup password screen, I will test it once 3615 is fixed.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
