### ISSUE TITLE
[SB] View mode of the study > Overview screen > User is able to edit the 'Description' field in view mode

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3600]
AR: View mode of the study > Overview screen > User is able to edit the 'Description' field from the 2nd page to 5th page 
ER: User should not be able to edit the fields in View mode 

![rte1](https://user-images.githubusercontent.com/71445210/119157011-5b8df480-ba72-11eb-9401-9f981ba55f31.png)

**Comment by harisboston** [comment]
@Lathan-btc This issue is fixed in dev environment, kindly test and update this ticket.

**Comment by harisboston** [comment]
@Lathan-btc This issue is fixed in QA environment, kindly test and close this issue. Thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
