### ISSUE TITLE
SB > Add audit logs for study replication , import and export 

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3602]
Update SB audit logs to capture events related to:

1. Replication of a study within the Study Builder
2. Export of a study from a Study Builder
3. Import of a study into a Study Builder

Reference tickets
#3321 #3114 #3593

**Comment by nagarjunav1** [comment]
Audit logs are implemented for COPY, IMPORT and EXPORT and logs are captured as events gets triggered in DEV

**Comment by Kantharajut-btc** [comment]
please test this issue in QA and confirm.

**Comment by nishit-v** [comment]
Audit logs are implemented for COPY, IMPORT and EXPORT and logs are captured as events gets triggered in QA
