### ISSUE TITLE
DB migration checks for v2.0.6 and v2.0.7

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3603]
Dev team, creating this ticket to track changes for the 2.0.6 release for any db updates and to update db migration scripts if needed

QA team to verify db migration after the final (pre-RC) build is released to QA for 2.0.6

**Comment by aswinijena100** [comment]
DB Migration checks is completed for v2.0.6 and hence moving this issue to next milestone for verifying future releases

**Comment by aswinijena100** [comment]
All DB migration changes are in place for RC 2.0.6 and there is no DB changes in RC 2.0.7.
