### ISSUE TITLE
[SB] Comprehension test > 'Minimum score needed to pass the test' field should be mandatory field

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3606]
Comprehension test > 'Minimum score needed to pass the test' field should be a mandatory field

AR: 'Minimum score needed to pass the test' field; is not a mandatory field so the user is able to do 'Mark as completed' without entering that field
ER: 'Minimum score needed to pass the test' field' should have '*' symbol and if the user tries to do a section completed without entering this field then it should display an inline error message - 'Please fill out this field'

![ct1](https://user-images.githubusercontent.com/71445210/119444767-646c1800-bd49-11eb-9dd6-8428af74855e.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc This issue is fixed in QA environment, kindly test and close this issue. Thanks

**Comment by Lathan-btc** [comment]
@harisboston User is able to mark the section as completed without entering 'Minimum score needed to pass the test' mandatory field
[Note: Issue observed in both QA and Dev instance]

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in QA environment, kindly test and close this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
