### ISSUE TITLE
[PM] Locations > Edit location screen > 'This site cannot be modified' error message is displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3607]
Steps
1. Sign in to PM
2. Go to Locations
3. Try to edit the location

AR: 'This site cannot be modified' error message is displaying

[Note: Issue has happened only for location with locationID = 'location1']  

![location21](https://user-images.githubusercontent.com/71445210/119445601-b06b8c80-bd4a-11eb-8362-361e67799025.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev.

**Comment by Lathan-btc** [comment]
@monica-BTC 
1. Default location should also be removed from add site dropdown

![defaultloc](https://user-images.githubusercontent.com/71445210/119940496-e740dd00-bfac-11eb-968d-b11eac221b4d.png)

2. It should be handled for old closed studies for which default location added as a site

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
