### ISSUE TITLE
[SB] User is able to click on other sections even though 'Study information' section is not marked as completed for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3608]
Steps
1. Sign in to SB
2. Navigate to the studies list page
3. Click on 'Create study'
4. try to click on any other sections without entering any data on the 'Study information' page and observe

AR: The user is able to click on other sections and navigating to the studies list page
ER: All the sections should be disabled until 'Study information' and 'Study settings' sections are marked as completed for the prelaunch studies

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
