### ISSUE TITLE
[Mobile] Studies are not displaying in Study list screen in mobile

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3609]
Issue is observed in QA instance 

![image](https://user-images.githubusercontent.com/60500517/119483056-3818c180-bd72-11eb-8da5-3780529abc46.png)

**Comment by harisboston** [comment]
@nagarjunav1 This issue is fixed in QA environment, kindly test and close this issue. Thanks

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
