### ISSUE TITLE
[SB] Overview screen > Images are getting removed for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3621]
Steps
1. Sign in to SB
2. Navigate to the Overview screen
3. Add an image for all the pages
4. Remove the image for  4/5th page
5. Upload the image
6. Click on save or mark as completed
7. Observe the image for the first 3 pages

AR: Images are getting removed 
ER: Images should not be removed from the previous pages

 [Note: Issue should also be fixed when a user uploads an invalid image]

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc  Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
