### ISSUE TITLE
[SB] Questionnaires/Active tasks > Schedule tab > Data display issue when switching schedule type 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3622]
**Questionnaires**

**Scenario 1.** Schedule tab > Regular > Add all the values > switch to anchor date > Observe the data

**AR:**
- One-time frequency:  All data gets cleared 
- Daily frequency: Entered time, number of times to repeat the task getting displayed
- For other frequencies> Entered data in regular is not getting displayed in anchor date based

**ER:**

- One-time frequency:  All data must get cleared (same as AR) 
- Daily frequency: Entered times, number of times can be displayed, but end date should be NA (we will go with this for now as 
 there is some technical complexity involved in clearing out all the data for this page, as conveyed by the tech team)
- For other frequencies: Same as AR but ensure end date field value is displayed as NA 

 **Scenario 2.** Schedule tab > Regular > Add all the values > save > switch to anchor date > Observe the data

**AR:**  

- For all the frequencies > Entered data in regular is not getting displayed in anchor date based

**ER:**
- For all the frequencies > Same as AR but ensure end date is displayed as NA wherever the field exists

**Active task**

**Scenario 1.** Schedule tab > Regular > Add all the values > switch to anchor date > Observe the data

**AR:**
- One-time frequency:  All data gets cleared 
- Daily frequency: Entered time, number of times to repeat the task and end date getting displayed
- Custom frequency:  All data gets cleared
- Weekly and Monthly frequency: Only the end date is getting displayed and other data gets cleared

**ER:**

- One-time scheduling option:  All data must get cleared (same as AR) 
- Daily frequency: Entered times, number of times can be displayed, but end date should be NA (we will go with this for now as 
 there is some technical complexity involved in clearing out all the data for this page, as conveyed by the tech team)
- Custom scheduling option:  All data must get cleared (same as AR)
- Weekly and Monthly frequency: All data should be cleared end date should be displayed as 'NA' 

 **Scenario 2.** Schedule tab > Regular > Add all the values > save > switch to anchor date > Observe the data

**AR:**  

- One-time frequency:  All data gets cleared 
- Daily frequency: Entered time, number of times to repeat the task and end date getting displayed
- weekly/monthly: Entered time, number of times to repeat the task and end date getting displayed
- Custom frequency: Start time and end time is getting displayed

**ER:**
- One-time frequency:  All data must get cleared (same as AR)
- Daily frequency: All the data should be cleared and the end date should be displayed as 'NA'
- weekly/monthly frequency: All the data should be cleared and the end date should be displayed as 'NA'
- Custom frequency: Start time and end time can be displayed (we will go with this for now as there is some technical complexity involved in clearing out all the data for this page, as conveyed by the tech team)

[**Note:** For questionnaires it is already working as expected and it should be fixed for the active tasks]

**Comment by harisboston** [comment]
@SR-btc Kindly confirm, Is it fine to clear the data of common fields, once users toggle between regular and anchor date based schedule types?
Even if we retain the data of common fields, user can keep the same data or change as per their need.

**Comment by Lathan-btc** [comment]
@Haris and @madhurya-btc Above description has been updated and implement as per the updated document

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in dev

**Comment by Lathan-btc** [comment]
@navya-BTC 
**1.** Regular > Daily frequency > Enters multiple runs > Switch to anchor date > Observe the contents 
**AR:** Entered multiple runs are getting displayed
**ER:** All fields/contents should be displayed freshly without any data

**2.** Questionnaires > Regular > Custom > Enter all the data > click on Done button > click on edit questionnaire >Go to schedule tab > switch to anchor date based and observe the data
**AR:** Start time and end time are getting displayed
**ER:** All fields should be displayed freshly without any data

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in QA

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
