### ISSUE TITLE
[PM] Add location/Edit location > Below mentioned error messages should be displayed for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3626]
Steps
1. Log in to PM
2. Navigate to the Locations tab
3. Add/Edit location
4. Enter location ID/Name same the default location ID/name used in the system

AR: 
1. When location ID is the same as the default location ID
    Error message: Location ID must be unique across the location directory

2. When the location name is the same as the default location name
    Error message: Sorry, a location with this name already exists

ER: 
1. When location ID is the same as the default location ID
   Error message: This is a default location ID in use by the system already. Please enter a different location ID.
      
2. When the location name is the same as the default location name
   Error message: This is a default location name in use by the system already. Please enter a different location name.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
