### ISSUE TITLE
[SB] Instruction step is not saving on pasting a copied paragraph contents from other sources

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3627]
**Steps:**
1. Copy a paragraph content from other document eg. wikipedia
2. Paste the copied content in Instruction step rich text editor
3. Fill the mandatory fields and click on done
4. Observe the behaviour

**Actual:** Instruction step is not saving on pasting a copied paragraph contents from other sources and incorrect message 'instruction step updated' is displaying

**Expected:** Instruction step should be saved properly

Issue not observed for other summer note editors on pasting the same copied content

Refer video:
[SB_Instr_Issue.zip](https://github.com/GoogleCloudPlatform/fda-mystudies/files/6560537/SB_Instr_Issue.zip)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev Instance.

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA Instance.
