### ISSUE TITLE
[Android] Text in Data sharing screen is not displaying as configured in Study builder

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3628]
**Steps**:- 
1. Configure the Data sharing  in E-consent screen in the Study builder as shown below.
2. Login into android  application
3. Navigate to the studies list 
4. Click on study and try to enroll
5. Navigate to Data sharing screen and click on **Learn more** 
6. Verify the text in Learn more screen

**A/R**:- Text is displaying in a single line
**E/R**:- Text should display as configured in the Study builder

![image](https://user-images.githubusercontent.com/60500517/119983826-4d922380-bfde-11eb-8e44-830ed294baf6.png)

![image](https://user-images.githubusercontent.com/60500517/119983859-5aaf1280-bfde-11eb-86d2-8be3699e28c8.png)

**Comment by chiranjibi009** [comment]
@nagarjunav1 Please test this issue in dev environment and update.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by chiranjibi009** [comment]
@nagarjunav1 Please test this issue in QA instance and update.

**Comment by nagarjunav1** [comment]
Issue is not fixed in latest QA build 

![image](https://user-images.githubusercontent.com/60500517/121880313-7aa73b80-cd2b-11eb-9684-324b1eda5528.png)

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
