### ISSUE TITLE
[SB] Activities > Validation message is not displayed when questionnaires/active tasks which are scheduled in past and admin is trying to publish updates/launch study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3629]
**Steps:**

1. Schedule a questionnaire/ active taks activity as per server  time zone and complete the section
2. Complete all the sections of Study
3. Wait for the scheduled time to get expire
4. Click on Publish updates and verify the validation message displayed

**A/R:-** Validation message is not displayed when questionnaires/active tasks are scheduled in past and trying to publish updates/launch study

**E/R:-** Validation Message `One or more of the study's activities are scheduled for dates that are in the past. Please configure activity schedules to have upcoming dates and try again.` should be displayed in Actions page

Note: 

- Issue observed only in Dev instance
- Issue observed for Questionnaires and Active tasks
- Issue observed while launching the study and publishing updates
- Issue also observed for new studies which are copied/exported.

**Comment by Kantharajut-btc** [comment]
@nishit-v  this issue is fixed in dev, please check and confirm.

**Comment by nishit-v** [comment]
Issue is resolved in latest dev instance.

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue in QA and confirm.
