### ISSUE TITLE
[SB][COPY] Comprehension test section content  is not copied into new study 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3630]
Steps:-
1. Login into SB
2. Navigate to Studies screen
3. Create/Edit study and add comprehension question
4. Select the study that need to copy and click on copy icon
5. Open the new study which is created from original study and in draft
6. Navigate to Comprehension section and verify the content 

A/R:- Content in the Comprehension test section is not copied into new study 
E/R:- All the content should be copied into new study 

![image](https://user-images.githubusercontent.com/60500517/119992639-699ac280-bfe8-11eb-8ec6-0a6e75608ef1.png)

![image](https://user-images.githubusercontent.com/60500517/119992727-761f1b00-bfe8-11eb-99f8-c0863e4a3bcb.png)

**Comment by nishit-v** [comment]
Issue is resolved in Dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
