### ISSUE TITLE
[SB] Date response type > Unable to select past date in 'Minimum Date' fields

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3633]
**Steps:**

1. Add a date response type for question/form step
2. Click on Minimum date field in 'Response level attributes' page
3. Observe the date selection

**Actual:** Unable to select past date in 'Minimum Date' fields and showing only till current date

**Expected:** User should be able to select any past date and no validation should be there for the fields

![DateIssue](https://user-images.githubusercontent.com/60386291/119998122-07dd5700-bfee-11eb-8d33-faea46b77b30.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is fixed for 'Minimum Date' field. Issue should be handled for 'Default date' field as well.

Actual: Unable to select Past date even though minimum date is selected in past

Expected: 'Default date' field range should be date selected in from minimum to Maxmimum date fields.

**Comment by madhurya-btc** [comment]
@nishit-v Please check and confirm in dev.

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in QA instance.
