### ISSUE TITLE
[SB] Questionnaires > UI issue in questionnaires page when viewed from last published version

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3634]
Steps:
1. Add a questionnaire and set scheduling
2. Add some question step(s)
3. Apply branching and save
4. Publish updates
5. Click on Last published version button
6. Navigate to questionnaires and open questionnaires
7. Observe the UI issue

Note: Issue observed only for branching questionnaires

Issue observed only in Dev

![SB_UI](https://user-images.githubusercontent.com/60386291/119998987-e16beb80-bfee-11eb-9a26-5652e1b72c0d.png)

**Comment by chiranjibi009** [comment]
@nishit-v This issue is not reproducible. Please check this issue again and update

**Comment by nishit-v** [comment]
Issue is not reproducible in latest QA instance.
