### ISSUE TITLE
[SB] Continuous loading animator on navigating to a 'view question step' page for some of the questions

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3637]
Steps:
1. Click on Edit/view/last published version for the study
2. Navigate to questionnaires
3. Click on edit/view for the question step
4. Observe

Question details:
Instance - Dev
Study ID - CopyStudy
Questionnaire ID - ranching
Questionnaire name - Branching
Question step name - 2
Question key ID - 2

1. 'Issue has been observed for multiple question steps across questionnaires and studies
2. Issue observed only for this particular question step.
2. Issue also observed when copied this questionnaire/ study
3. Due to above issue, branching is not working as expected in mobile apps

![loading issue](https://user-images.githubusercontent.com/60386291/120002786-c7340c80-bff2-11eb-8506-3c9177dfd8e9.png)

**Comment by nishit-v** [comment]
Issue also observed for below two questions:

Question details:
Instance - Dev
Study ID - NewOriginal
Questionnaire ID - branching
Questionnaire name - Branching
Question step name - 2
Question key ID - 2

Question details:
Instance - Dev
Study ID - NewOriginal
Questionnaire ID - branching
Questionnaire name - Branching
Question step name - 7
Question key ID - 7

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is resolved in latest dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
