### ISSUE TITLE
[SB] [Copy] App ID field should be cleared on copying a standalone study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3638]
**Steps:**
1. Launch a standalone study
2. Copy the study
3. Observe the App ID field in a) studies list  b) Basic information for the copied study

**Actual:** App ID field is getting retained on copying a standalone study

**Expected:** App ID field should be cleared on copying a standalone study

![Standalone](https://user-images.githubusercontent.com/60386291/120006228-52fb6800-bff6-11eb-8410-b660393bd265.png)

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please test and update the ticket accordingly.

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev Instance.

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue in QA and confirm.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA Instance.
