### ISSUE TITLE
[SB] Comprehension test > 'Mark as completed' button is non functional

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3643]
Steps
1. Log in to SB
2. Click on Create study
3. Navigate to the Comprehension test screen
4. Try to click on the 'Mark as completed' button when the 'No' option is selected 

AR: 'Mark as completed' button is nonfunctional
ER: 'Mark as completed' button should be functional and when the user clicks on this button then the user should navigate to the next section 

![ct2](https://user-images.githubusercontent.com/71445210/120189480-0a7dbd80-c235-11eb-9383-c2bff7ed2ada.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in QA environment, kindly test and close this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
