### ISSUE TITLE
[SB] [Import] Overview > Order of the overview pages is getting changed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3644]
AR: In the Original study order of the overview screen is Page1, Page2, Page3, Page4, and Page5
but for the imported study, the order of the overview pages is Page1, Page5, Page4, Page2, and page3

ER: For the imported studies, overview pages should be displayed in the same order as present in the original study

![image](https://user-images.githubusercontent.com/71445210/120192075-5c741280-c238-11eb-9acb-008716a922ed.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev environment and update.

**Comment by Lathan-btc** [comment]
@navya-BTC 1st page is getting displayed in the last.

**Comment by Lathan-btc** [comment]
@chiranjibi009 in the original study, overview pages are reordering in ascending order when the user clicks on the save or mark as completed button. It should be displayed in the same order as whatever we had given while adding the overview pages.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please check and confirm.

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
