### ISSUE TITLE
[SB] [Import] Data-sharing permission section content is not imported into new study 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3646]
**Steps:-**

1. Login into SB
2. Navigate to Studies screen
3. Create/Edit study and add Navigate to E-Consent steps
4. On the data-sharing permission and enter all the fields 
5. Click on Save or MAC button
6. Navigate to the Actions section and click on the Export button
5. Copy the signed URL
6. Import the study successfully
7. Click on the edit button of the imported study 
8. Navigate to the E-Consent steps section and observe

**AR:-** Content in the Data-sharing section is not imported into new study

**ER:-** All the content should be imported into new study

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
