### ISSUE TITLE
[SB] User is unable to export the study : Error message is getting displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3648]
User is unable to export the study: An error message is getting displayed

![export1](https://user-images.githubusercontent.com/71445210/120210388-589ebb00-c24d-11eb-9227-ca4509ab4f1d.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please check and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
