### ISSUE TITLE
[SB] [Copy] Questionnaires/Active task > Schedule > Selected anchor date type is not copied into new study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3650]
**Steps**
1. Login to SB
2. Create/Edit study
3. Add questionnaires and active task with an anchor date based schedule type
4. Copy the particular study
5. Click on the edit button of the new study
6. Navigate to Questionnaires and Active task section
7. Switch to the schedule tab
8. Observe the value 'Select anchor date type' dropdown

**AR:** Anchor date type is not copied into new study
**ER:** All the contents should be copied into a new study

[Note: Issue should be fixed in questionnaires, Active task and Resources]

**Comment by Kantharajut-btc** [comment]
@Lathan-btc  this issue is fixed in dev, please test and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
@Kantharajut-btc 
1. Login to SB
2. Create/Edit study
3. Add a source question
4. Add questionnaires and active task with Enrollment date as an anchor date
4. Copy the particular study
5. Click on the edit button of the new study
6. Navigate to Questionnaires and Active task section
7. Switch to the schedule tab
8. Observe the value 'Select anchor date type' dropdown

AR: Wrong anchor date is copied into a new study
ER: Newly created study should be a replica of the original study 


![copy-anchor](https://user-images.githubusercontent.com/71445210/120324916-c78b1b00-c304-11eb-91e1-045d4dfacea0.png)
original study

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc  please test this issue in QA and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
