### ISSUE TITLE
[SB] Resources > Custom schedule > Start date is getting removed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3651]
**Steps**
1. Login to SB
2. Create/Edit study
3. Add resource with 'Custom schedule' 
4. Enter current date as start date
5. Once entered date becomes a past date, click on the edit button of the study
6. Navigate to the Resources section
7. Observe the value present in the 'Select date' field

**AR:** Select date is getting removed
**ER:** Entered content should not be removed 

[Note: It should be handled for the Original study, Copied study and imported study]

![cr1](https://user-images.githubusercontent.com/71445210/120275972-b4aa2380-c2cf-11eb-8d21-8fdf12322119.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in the QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in te latest QA instance
