### ISSUE TITLE
[SB] Notifications > Selected date for scheduling is getting removed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3652]
**Steps**
1. Login to SB
2. Create/Edit study
3. Add notification with 'Schedule this notification' 
4. Enter the current date and save
5. Once entered date becomes a past date, click on the edit button of the study 
6. Navigate to the Notifications section
7. Observe the value present in the 'Select date' field

**AR:** Select date is getting removed
**ER:** Entered content should not be removed 

[Note: It should be handled for the Original study, Copied study, and imported study]

![noti11](https://user-images.githubusercontent.com/71445210/120276977-0f904a80-c2d1-11eb-963b-881875c3d6b6.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc Issue is still reproducible in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in the QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.
