### ISSUE TITLE
[SB] Text in the pop-up should be center-aligned

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3653]
**AR:** Text in the pop-up is left aligned
**ER:** Text in the pop-up should be center-aligned

[Note: Issue should be fixed for all the pop-up's present in the SB]

![image](https://user-images.githubusercontent.com/71445210/120277928-4e72d000-c2d2-11eb-8be5-4888cc4cb54e.png)

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in Dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in QA environment, kindly test and close this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
