### ISSUE TITLE
[SB] [Copy] Questionnaires > Schedule tab > Custom schedule > Start date is not copied into new study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3654]
**Steps**
1. Login to SB
2. Create/Edit study
3. Add Questionnaires with Regular and custom schedule
4. Once the entered start date expired, copy the particular study
5. Click on the edit button of the new study
6. Navigate to the Questionnaires section
7. Select questionnaire created with a custom schedule
8. Navigate to the Schedule tab
9. Observe the value present in the 'Start date' field

**AR:** Start date is not copied into a new study
**ER:** All the contents should be copied into a new study

![custom-c](https://user-images.githubusercontent.com/71445210/120291176-a9132880-c2e0-11eb-83b2-36671f928075.png)

**Comment by harisboston** [comment]
@Lathan-btc Issue is not reproducible in Dev environment, kindly test and close this issue if it working as expected.

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in Dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc  Issue is fixed in QA instance, kindly test and update this ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
