### ISSUE TITLE
[SB] Consent version is not getting updated correctly

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3655]
The consent version is not updating correctly on the following screen when the user published the updates
1. Consent section
2. E-Consent steps > Consent document

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in dev.

**Comment by Lathan-btc** [comment]
@monica-BTC In the consent section, it is still showing the version as v1.0 ( version is not updating)

[Note: Issue observed only for the original studies]

**Comment by monica-BTC** [comment]
@Lathan-btc, please test by creating a new Study and confirm this issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
