### ISSUE TITLE
[SB] Last published version of the study is not getting updated for the original studies

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3656]
**Steps**
1. Create a new study
2. Launch the study and observe the last published version
3. Click on the edit button of the study
4. Update the values in the study and mark all the sections completed
5. Publish the updates
6. Click on the 'Last publish version' button
7. Observe the last published version of the study

**AR:** Last published version of the study is not getting updated
**ER:** Version of the study should be updated properly

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev instance and confirm back.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in QA and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
