### ISSUE TITLE
[SB] [Import] Study settings > 'Use participant enrollment date as anchor date?' is setting to 'No' even though 'Yes' is selected in original study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3657]
**Steps**
1. Login to SB
2. Create/Edit study
3. In the study setting page select 'Yes' for 'Use participant enrollment date as anchor date?'
4. Copy the particular study
5. Click on the edit button of the new study
6. Navigate to the Study settings page section
7. Observe the settings 

AR: 'Use participant enrollment date as anchor date?' is setting to 'No' even though 'Yes' is selected in the original study
ER: The imported study should be a replica of the original study

![imp1](https://user-images.githubusercontent.com/71445210/120315043-8a6d5b80-c2f9-11eb-9141-83aa7df45865.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm.

**Comment by Lathan-btc** [comment]
Isse is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
