### ISSUE TITLE
[SB] [Copy/Import] Order of the data should be same as original study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3660]
The order of the data should be the same as the original study
Eg: 1. Questionnaires list
      2. Response level attributes > when we use multi-choice response type
      3. In custom schedule if we use more than 1 run etc...
      4. Notifications list (study level)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
