### ISSUE TITLE
[Dev] Push notifications not triggered from SB

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3662]
**Steps:**

1. Send a manual app level/study level notification
2. Observe the status in 'Notifications' screen

**Actual:** Push notifications not triggered from SB and status is 'Sending'

**Expected:** Push notifications should be triggered

Note: Issue observed only in Dev
Issue also observed for automated push notifications

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.

**Comment by aswinijena100** [comment]
@nishit-v please test in QA and close if fixed

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.

**Comment by nishit-v** [comment]
Issue is observed again in Dev instance. Not observed in QA instance

![Screenshot_1](https://user-images.githubusercontent.com/60386291/123437576-71508580-d5ed-11eb-87e6-fa5d79f6d2eb.png)

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev and update.

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
