### ISSUE TITLE
[SB] [Import] Questionnaires > Schedule tab > Custom schedule > Start date is not copied into new study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3664]
**Steps**
1. Login to SB
2. Create/Edit study
3. Add Questionnaires with Regular and custom schedule
4. Export the study and copy the signed URL 
5. Import the study
6. Click on the edit button of the imported study
7. Navigate to the Questionnaires section
8. Select questionnaire created with a custom schedule
9. Navigate to the Schedule tab
10. Observe the value present in the 'Start date' field

**AR:** Start date is not copied into a new study
**ER:** All the contents should be copied into a new study

![imp11](https://user-images.githubusercontent.com/71445210/120350047-42136500-c31c-11eb-8188-229369c6aa4c.png)

**Comment by harisboston** [comment]
@Lathan-btc Issue is not reproducible in Dev environment, kindly test and close this issue if it working as expected.

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in Dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed n the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc  Issue is fixed in QA instance, kindly test and update this ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
