### ISSUE TITLE
[SB][Export] Actions section > Success message is not displayed when admin clicks on the copy icon of the signed URL

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3666]
**Steps**
1. Login to SB
2. Crete/Edit study
3. Navigate to Actions section
4. Click on Export button
5. Click on the copy icon of the signed URL

**AR:** Success message is not displayed
**ER:** 'URL copied to clipboard' success message should be displayed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
