### ISSUE TITLE
[SB] [Import] [Audit Logs] Study version is incorrect for the event

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3669]
**Event:**
STUDY_IMPORTED

**Actual:** Study version displaying `null`

**Expected:** Study version should be `0.0` as it will be in pre-launch

![StudyVersion](https://user-images.githubusercontent.com/60386291/120463567-ab958100-c3b9-11eb-864e-f7d36fec9971.png)

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev instance and update

**Comment by nishit-v** [comment]
Issue is not resolved in latest Dev build.

![studyversion](https://user-images.githubusercontent.com/60386291/121876964-b809ca00-cd27-11eb-9862-f5cb00d0cfb3.png)

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev instance and update

**Comment by nishit-v** [comment]
Issue is resolved in latest dev instance.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA and update.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.
