### ISSUE TITLE
[SB] [Import] [Audit Logs] App ID is incorrect for the event 

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3670]
**Event:**
STUDY_IMPORTED

**Actual:** 
a) App ID is displaying `STUDY BUILDER` on importing gateway study
b) App ID is displaying `STUDY BUILDER` on importing standalone study

**Expected:** 
a) App ID should display exported study's App ID value as `NA` if technically infeasible to read the App ID of the exported study
b) App ID should display exported study's App ID value as `NA` if technically infeasible to read the App ID of the exported study

Refer screenshot for standalone study:
![Audit](https://user-images.githubusercontent.com/60386291/120464184-4726f180-c3ba-11eb-8ce0-2cc04554640a.png)

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev instance and update

**Comment by nishit-v** [comment]
Issue is not resolved in latest Dev build.

![AppID](https://user-images.githubusercontent.com/60386291/121876856-9d375580-cd27-11eb-958b-9726ccb4ef7c.png)

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev instance and update

**Comment by nishit-v** [comment]
Issue is resolved in latest dev instance.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA and update.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.
