### ISSUE TITLE
[SB] [Import] App ID field should be cleared on importing a standalone study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3671]
**Steps:**
1. Launch a standalone study
2. Import the study
3. Observe the App ID field in a) studies list  b) Basic information for the copied study

**Actual:** App ID field is getting retained on copying a standalone study

**Expected:** App ID field should be cleared on copying a standalone study

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
