### ISSUE TITLE
[SB] [Import] Questionnaires > User is able to edit the scheduling for published questionnaires for the imported study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3673]
Steps:

1. Login into SB
2. Navigate to Studies screen
3. Export a study having questionnaires and Import. Imported successfully
4. Click on edit for imported study
5. Complete all the sections and launch
6. Click on Edit study and navigate to questionnaires
7. Observe the scheduling section

A/R: User is able to edit the scheduling for published questionnaires for the imported study

E/R: User should not be able to edit the scheduling for published questionnaires

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in QA and confirm.
