### ISSUE TITLE
[SB] [Import] Custom schedule > Unable to edit custom schedule frequency changes in pre-launch mode for imported study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3676]
**Steps:**

1. Login into SB
2. Export a study having custom schedule questionnaires/active tasks and import
3. Imported successfully
4. Click on edit for imported study
5. Navigate to custom schedule frequency
6. Observe that date/time fields are disabled

**A/R:** Unable to edit custom schedule frequency changes in pre-launch mode for imported study

**E/R:** User should not be able to edit the scheduling in pre-launch mode

**Note:**
1. Issue observed for both questionnaires and active tasks
2. Issue observed for both regular and anchor based frequency

![custom_pre-launch](https://user-images.githubusercontent.com/60386291/120494828-c7108400-c3d9-11eb-80de-46f51810d4db.png)

**Comment by nishit-v** [comment]
Issue is resolved in the latest dev instance.

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in QA and confirm.
