### ISSUE TITLE
[SB] unable to create following active task with anchor date based schedule with weekly frequency

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3677]
unable to create following active task with anchor date based schedule with weekly frequency even though user filled all the mandatory fields
1. Tower of Hanoi  
2. Spatial span memory' active task 

![image](https://user-images.githubusercontent.com/71445210/120499153-7438cb80-c3dd-11eb-84ac-eb7daa5aa498.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc The issue is still reproducible when user clicks on Save and then Done button

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test now and confirm

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
