### ISSUE TITLE
[SB] [Import] 'Anchor date based' radio button is disabled for the new study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3679]
Steps
1. Login to SB
2. Create/edit study
3. Select 'Yes' to 'Use enrollment date as anchor date' on the study settings page
4. Import the study
5. Click on the edit button of the newly created study
6. Navigate to Questionnaire/active task/resources 
7. Click on add questionnaire
8. Switch to the schedule tab and try to select the anchor date based radio button

AR: 'Anchor date based' radio button is disabled
ER: 'Anchor date based' radio button is enabled

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
