### ISSUE TITLE
[SB] 'No' radio button is disabled for 'Use participant enrollment date as anchor date?' for the following scenario 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3680]
Steps
1. Login to SB
2. Create/edit study
3. Set 'Use participant enrollment date as anchor date?' to 'Yes' and Save/MAC
4. Add questionnaires with an anchor date
5. Navigate to the 'Study settings' page
6. Try to select the 'No' radio button

AR: 'No' radio button is disabled for 'Use participant enrollment date as anchor date?'
ER: 'No' radio button should be enabled 

**Note:** 

1. The issue happens when the user adds the questionnaires with an anchor date
2. It should be fixed for original, copied and imported studies

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please close this issue, which is happening only in dev due to import/export

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
