### ISSUE TITLE
Mobile apps] Dashboard stats are not displaying for some studies

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3682]
Steps

1. Create/Edit study
2. Navigate Questionnaires/Active tasks
3. Add questionnaire/active task with stats
4. Launch/publish the study
5. Join a study through a mobile app
6. Mobile app > Click on Dashboard and observe

AR : Stats are not displaying
ER : Stats should be displayed

[Note: Stats are not displaying for the following studies
1. Brain Activity - Original study(001)
Study ID - Originalstudy

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm in dev.

**Comment by nishit-v** [comment]
Issue is still observed in Dev instance.

**Comment by monica-BTC** [comment]
@nishit-v, I can see the values from the API. Please retest and confirm.

**Comment by nishit-v** [comment]
Issue is resolved in the latest dev instance. Verified for newly created/copied/imported studies

**Comment by nishit-v** [comment]
Issue is still observed for some of the studies in QA

Eg. NewStudy

![Screenshot_2](https://user-images.githubusercontent.com/60386291/122891742-6209d780-d362-11eb-8621-9df854eed2d3.png)

**Comment by monica-BTC** [comment]
@nishit-v, please test this and confirm in QA

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance (After PR)
