### ISSUE TITLE
[SB] Notifications > Change the error message text when entered time has expired

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3685]
Steps
1. Login to SB
2. Crete/Edit study
3. Navigate to the Notifications section
4. Add /edit notification
5. Enter the date and time
6. Wait till the entered time is get expired
7. Click on the Save/Done button and observe the error message

AR: An error message is displayed as shown in the below attached image
ER: 'Please select a time that has not gone past yet' inline error message should be displayed

![Overlap](https://user-images.githubusercontent.com/71445210/120637650-cab11300-c48c-11eb-906b-61e0360f7390.png)

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in Dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc  Issue is fixed in QA environment, kindly test and close this ticket.
Updated error message to `Please select a time in the future`, as per PR #3704 comment.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
