### ISSUE TITLE
[SB] Active task > Add to chart >  Values in the 'Time range for the chart' dropdown getting duplicated 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3686]
Active task > Add to chart >  Values in the 'Time range for the chart' dropdown getting duplicated

**Note:** 
1.Issue should be fixed for all the types of active tasks
2. It should be fixed for all the frequency types like daily, weekly, monthly, and custom

![activeta](https://user-images.githubusercontent.com/71445210/120640064-ae62a580-c48f-11eb-8dcb-1044b24a04d6.png)

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in the dev environment, kindly test and update this ticket.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in the QA environment, kindly test and close this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
