### ISSUE TITLE
[SB] [Copy/Import] Notifications are copying with the sent status into the new study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3689]
**Steps**
1. Login to SB
2. Create/Edit study
3. Create Notifications and launch the study 
4. Once notifications sent to the users copy the particular study
5. Click on the edit button of the copied study
6. Navigate to Notifications
7. Observe the status

AR: Notifications are copied with 'Sent' status
ER: 
1. Notifications should be in draft state and resend icon should be replaced with Edit icon with dot icon(draft)
2. Send immediately: Cleared out and disabled field for Send Immediately, 'Schedule this notification' radio button should be 
    selected and date and time should be displayed when it sent immediately and when the user clicks on the done button it 
    should validate for the past date.  
3. Scheduled and sent: Recently sent date and time should be displayed and when the user clicks on the done button it 
    should validate for the past date.
4. Scheduled with future date: Contents should be copied over as it is

Note: Issue should be fixed for both copy and import]

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
