### ISSUE TITLE
[SB] > Notifications > Text change for Add/Edit/ Resend/ Copy notifications screen

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3690]
**New text** - For studies that are already launched, notifications get scheduled for delivery to
participants, immediately upon marking this screen as Done, not requiring an explicit 'Publish
updates' action at the study level.

![image](https://user-images.githubusercontent.com/60500517/120654052-ee7d5480-c49e-11eb-86a8-2d69338620a7.png)

**Comment by madhurya-btc** [comment]
@nagarjunav1  Please test and confirm in the dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest dev build

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in the QA instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
