### ISSUE TITLE
[SB] Question/form step > Response type options are in incorrect order

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3691]
**Steps:**
1. Edit a study
2. Add a question/form step
3. Navigate to Response level attributes page
4. Click on 'Response type' dropdown
5. Observe the order

**Actual:** Response type options are in incorrect order

**Expected:** Response type options should be in original previous order (Refer QA instance)

Dev (Actual):

![Order_Dev](https://user-images.githubusercontent.com/60386291/120655154-01dcef80-c4a0-11eb-9295-6200364308b4.png)

QA(Expected): 

![Order_QA](https://user-images.githubusercontent.com/60386291/120655178-07d2d080-c4a0-11eb-9430-e1ae64dfa353.png)

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm in dev.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.
