### ISSUE TITLE
[SB] [Copy/Import] Active task custom schedule > User is able to edit the start time for published active tasks for the copied/imported study 

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3693]
**Steps:**

1. Create a study with anchor based active task custom scheduling
2. Launch the study
3. Copy/import the study
4. Launch the copied/imported study by filling all the details
5. Edit the study again
6. Navigate to the scheduling of active tasks for custom schedule 
7. Observe the start time

**A/R:** User is able to edit the start time for published active tasks for the copied/imported study 

**E/R:** Start time should be disabled

**Note:** 

1. Issue observed only for active tasks and not questionnaires
2. Issue observed for custom schedule

![cust](https://user-images.githubusercontent.com/60386291/120668983-a5cc9800-c4ac-11eb-8465-9aad5aaec775.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in the latest dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
