### ISSUE TITLE
[PM] First study is not showing in Participant Manager

### ISSUE THREAD

**Issue by rpbaquing-stratusmeridian** [GoogleCloudPlatform/fda-mystudies#3696]
Application Version: v2.0.5

**What are you trying to accomplish?**
Are you trying to deploy the platform for the first time?
Yes

Is this about operating a deployed platform?
Yes

Tell us a bit about what is going on.
I've completed setting up the infrastructure and now configuring my first study. After creating the example study, I am unable to see it in Participant Manager even though the study is already launched.

**What challenge are you running into?**
Are you receiving an error or are things just not working as expected?
I was expecting that the sample study will show in Participant Manager

What specifically is the problem?
Possibly that both Study Builder and Participant Manager are not in sync? Not really sure about it. I do not see any errors in the container logs.

**What have your tried so far?**
Include any relevant code snippets or logs that might help us understand.
- I've tried to update the mobile-app-appid variable and redeploy the secret and restart the k8s deployments (app related containers only).

UI:
![image](https://user-images.githubusercontent.com/82572819/120774191-a1f45080-c554-11eb-80a5-dd3ffd852913.png)

![image](https://user-images.githubusercontent.com/82572819/120774246-af113f80-c554-11eb-9fa8-1aeebc9d4316.png)

Participant Manager Logs:
![image](https://user-images.githubusercontent.com/82572819/120774619-06afab00-c555-11eb-921a-c517f0871a38.png)

Study Builder Logs:
![image](https://user-images.githubusercontent.com/82572819/120774752-2b0b8780-c555-11eb-84f0-d166eebb4295.png)

**Labels**
Please add labels that indicate which component(s) this request is related to.
Participant Manager, Study Builder

**Comment by aswinijena100** [comment]
@rpbaquing-stratusmeridian could you please do the health check of all the application and let know if all the applications are up and running . Also please verify published study in SB  is available  _**study_info**_ table in _**mystudies_participant_datastore**_ database or not. If the publshed not exist in  mystudies_participant_datastore database ,please verify Participant User Datastore logs and let know if you find any error or exception.

**Comment by rpbaquing-stratusmeridian** [comment]
Hello @aswinijena100, all applications are healthy and running.
![image](https://user-images.githubusercontent.com/82572819/121015714-e0487480-c7cd-11eb-914e-0a447373b029.png)

The table study_info is empty.
![image](https://user-images.githubusercontent.com/82572819/121023177-9bc0d700-c7d5-11eb-8cd5-280e4ed2c2e9.png)

And also I am seeing these errors in the mystudies_participant_datastore logs 
![image](https://user-images.githubusercontent.com/82572819/121016175-65338e00-c7ce-11eb-9ba8-ebcdf3a8fd77.png)

Let me know if you need anything else

**Comment by aswinijena100** [comment]
@rpbaquing-stratusmeridian Thanks for sharing the log details. As per the log I can see the error **Unknown column 'studyentit0_.contact_email' in 'filed list'** . This could be due to not executing the DB migration script. Hence request the follow this [link](https://github.com/GoogleCloudPlatform/fda-mystudies/tree/master/db-migration) to execute the db migration script. Once this step is completed , please re published the study from Study Builder and verify if study is appearing in the Participant Manager . Please let me know if you need any clarification.

**Comment by rpbaquing-stratusmeridian** [comment]
Hi @aswinijena100, first  do I need to do the db migration even if I was using the latest version (2.0.5)? It was mentioned in the deployment guide: "When updating FDA MyStudies it may be necessary to migrate the databases to support the new version." But I started from scratch.

Anyway, I tried following the db migration guide however, it wasn't mentioned where to get the database names. I looked the deployment guide and Cloud SQL instance databases but couldn't find them.

![image](https://user-images.githubusercontent.com/82572819/121187243-6fbb5980-c89a-11eb-9893-4ade564617e6.png)

![image](https://user-images.githubusercontent.com/82572819/121187329-88c40a80-c89a-11eb-960b-aaa9a28205d1.png)

**Comment by mohangmk** [comment]
@rpbaquing-stratusmeridian 
All Database names are listed in your above screen shot itself

Authserver Database name: oauth_server_hydra
Participant-datastore database: mystudies_partcipant_datastore
response-datastore database: mystudies_response_server
study-builder database: fda_hphc

**Comment by rpbaquing-stratusmeridian** [comment]
Thank you @mohangmk it worked. However, is this step necessary for new deployment? In the deployment guide, it was only mentioned to do it when updating FDA mystudies. If not, then updating the deployment guide will help others for future deployments.

**Comment by aswinijena100** [comment]
@rpbaquing-stratusmeridian Yes, if a release contains any database changes that will be part of of the db migration step. Hence please execute the db migration steps whenever code upgraded to latest release .

If the this issue is fixed , request you to kindly close this ticket.
