### ISSUE TITLE
[SB] [Export] Wrong Pop-up window is getting displayed when user export the paused study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3698]
Steps
1. Login to SB
2. Navigate to the studies list screen 
3. Click on the edit button of the active study
4. Navigate to the Actions section
5. Pause the study
6. Without navigating to any section, click on the Export button and observe

AR: Unwanted popup window is getting displayed
ER:  Popup window should not be displayed 

[Note: Issue observed only in Firefox browser]

![image](https://user-images.githubusercontent.com/71445210/120889803-894f6d80-c61c-11eb-8551-a671a7a5cf5f.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
