### ISSUE TITLE
[SB] Active task > Schedule tab > One time / Custom schedule > Start and/or end date is not getting displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3700]
**Steps**
1. Login to SB
2. Create/Edit study
3. Add active task with Regular and One time/custom schedule
4. Once the entered start/end date got expired
5. Click on the edit button of the study
6. Navigate to the Active task section
7. Select questionnaire created with a one time/custom schedule
8. Navigate to the Schedule tab
9. Observe the value present in the 'Start/End date' field

**AR:** Start/End dates are getting removed
**ER:** Start and end dates should be displayed 

Note:
The issue should be fixed for both questionnaires and active task
1. Active task > One time and custom schedule
2. Questionnaires > One time

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
