### ISSUE TITLE
[Android] Custom consent is not showing in visual step

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3705]
Steps
1. Login to SB
2. Create study/Edit study
3. Go to the consent section
4. Add custom consent with visual step
5. Launch/Publish the updates
6. Go to mobile application
7. Click on the particular study
8. Observe the custom consent while providing the consent 

AR: Custom consent is not getting displayed
ER: Consent should be shown

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
