### ISSUE TITLE
[Mobile apps] Images are not getting displayed in the mobile apps

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3706]
Images are not getting displayed for Scale/Continuous scale/ Image choice response types in mobile

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc Form step > images are not displaying for scale and continuous scale response types

![image](https://user-images.githubusercontent.com/71445210/121355151-398ae200-c94d-11eb-855d-400bf56ee8f0.png)

**Comment by madhurya-btc** [comment]
@naveenr-btc Can u please check and let me know what's causing the issue

**Comment by madhurya-btc** [comment]
@naveenr-btc Its causing because of import/export. Backend team will look into that.
@nishit-v Can u please  confirm

**Comment by nishit-v** [comment]
Images are getting displayed in mobile apps for question step and form step . Verified for copied/imported study

**Comment by madhurya-btc** [comment]
@Lathan-btc Please close this issue if it is tested QA

**Comment by Lathan-btc** [comment]
Issue s fixed in the latest QA instance.
