### ISSUE TITLE
[SB] Active task > Regular weekly > Start date and start time displaying empty in Activitylist and Activitymetadata API

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3707]
Steps:
1. Configure a weekly active task from SB
2. Publish updates
3. Check the start time in Activitylist or start date in Activitiymetadata API
4. Observe value is showing empty and due to this activities are not showing in iOS and incorrect start date in Android

Actual: Start date and start time displaying empty in Activitylist and Activitymetadata API

Expected: Start date and start time should display proper values

SB:
![SB_activetask](https://user-images.githubusercontent.com/60386291/121004837-c21e4c80-c7ac-11eb-8ceb-21ae2687b626.png)

APIs:
![SB_weekly](https://user-images.githubusercontent.com/60386291/121004666-9733f880-c7ac-11eb-8bb2-645d39a1f164.png)

![Screenshot_2](https://user-images.githubusercontent.com/60386291/121004681-9b601600-c7ac-11eb-8653-e2885161f9f4.png)

**Comment by harisboston** [comment]
@nishit-v this issue is fixed in dev environment, kindly test and confirm

**Comment by nishit-v** [comment]
@harisboston `startDate` / `startTime` is displaying in incorrect format for Active task weekly activities in GetStudyActivityMetadata API and GetStudyActivityList API respectively

![Screenshot_1](https://user-images.githubusercontent.com/60386291/121337748-7bf6f380-c93a-11eb-98c3-32e52077698d.png)

![Screenshot_3](https://user-images.githubusercontent.com/60386291/121338254-f45db480-c93a-11eb-95a1-5827b75035df.png)

**Comment by harisboston** [comment]
@nishit-v  Issue is fixed in dev environment, kindly test and update this ticket

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.

**Comment by harisboston** [comment]
@nishit-v  Issue is fixed in QA instance, kindly test and update this ticket accordingly.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA  instance
