### ISSUE TITLE
[Android] Resources are getting displayed in mobile app irrespective of scheduled date

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3709]
Resources are getting displayed in the mobile app irrespective of the scheduled date

Eg: 

**Study name:** Mobile App Open study(Original)

**Resources** 
1. Resource with Custom schedule
2. Resource scheduled on 14/6/21

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
