### ISSUE TITLE
[PM] Dashboard > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3711]
UI issue in sites, studies and apps tab

![Sites (1)](https://user-images.githubusercontent.com/71445210/121032014-7f6a6d80-c7c8-11eb-9de7-4e87c56ac49f.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the qa instance
