### ISSUE TITLE
[SB] [Copy/Import] GetStudyActivityList API > 'anchorDate' values are not shown for Copied/Imported study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3713]
Steps:
1. Edit a study
2. Add date response type question/form step
3. Enable checkbox 'Use response as anchor date' and enter the value
4. Configure anchor based activities by selecting anchor date option.
5. Publish updates
6. Copy/Import the study
7. Observe the GetStudyActivityList API for 'anchorDate' array

Actual: 'anchorDate' values are not shown for Copied/Imported study

Expected: 'anchorDate' values should be retained for Copied/Imported study

Note: Due to above issue, target based activities are not shown in mobile apps after submitting source based questionnaires

Study ID - import0728
Activity ID - targetfkc7

Screenshot for copied/imported study
![src](https://user-images.githubusercontent.com/60386291/121035495-9199db00-c7cb-11eb-85a8-dcc4957d41de.png)

Screenshot for original study
![src_original](https://user-images.githubusercontent.com/60386291/121035994-05d47e80-c7cc-11eb-878a-f7a4f136e044.png)

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue in dev and update the ticket accordingly, make sure export and copy the study again from the original study and do the testing, thanks

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue in QA and confirm.

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
