### ISSUE TITLE
[SB] Automated notifications sent to mobile app for platform (iOS/Android) that is not configured for the study 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3714]
When study is launched, which study is configured for only Android, the notifications also triggered for iOS and vice versa. 

![image](https://user-images.githubusercontent.com/60500517/121043981-c3627000-c7d2-11eb-8ffe-5715aa7c5364.png)

**Comment by chiranjibi009** [comment]
@nagarjunav1 Please test this issue for all notification scenarios as we have modified the notification implementation in dev and update.

**Comment by nishit-v** [comment]
Unable to test in Dev due to #3662

**Comment by chiranjibi009** [comment]
@nagarjunav1 please test this issue in dev and update.

**Comment by nagarjunav1** [comment]
Issue is fixed for all scenarios except the below scenario

A/R:-  When new Android study is launched, it is displaying in the notification list of iOS app and vice versa
E/R:- It should not display that notification in the list which are not available to that platform

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test in QA and close if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
