### ISSUE TITLE
[SB] Branching questions > Destination step is incorrectly set for branching questions and not working as expected 

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3715]
Steps:
1. Configure some text choice questions
2. Apply branching
3. Publish the updates
4. Observe GetStudyActivityMetadata API

Actual: Destination step is default set to self question step which is causing mobile apps to behave incorrectly

Expected: Branching questions should work as expected

Study ID - copied1141
Activity ID - 21978

Refer screenshot for acutal and expected behaviour of the API
![Branching Issue](https://user-images.githubusercontent.com/60386291/121142282-737abc00-c859-11eb-8716-e756675a13b2.png)

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in QA and confirm.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
