### ISSUE TITLE
[SB] Add active task > Contents tab Add to line chart > Radio button issue for 'Allow rollback of chart?' 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3717]
Steps
1. Login to SB
2. Navigate to Active task
3. Click on Add active task
4. Enter all the required data 
5. Navigate to the Schedule tab
6. Select any frequency except one time
7. Without saving the contents switch back to the Content tab
8. Select 'Add to line chart' check box
9. Observe the default radio button selected for 'Allow rollback of chart?' 

AR: Any radio button is not selected
ER: By default 'No' radio button should be selected

![linechart](https://user-images.githubusercontent.com/71445210/121174930-1d694100-c878-11eb-95c2-a4cfd6eb84f8.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
