### ISSUE TITLE
[SB] Questionnaires/Active tasks > Schedule tab > Text update

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3718]
Schedule tab > Text needs to be change

Add/Edit questionnaires > Schedule tab > Questionnaire scheduling options > should be changed to 'Scheduling options'
Add/Edit active task > Schedule tab >Active task scheduling options > should be changed to 'Scheduling options'

![textchang1](https://user-images.githubusercontent.com/71445210/121179376-50620380-c87d-11eb-88af-3bb605e0d505.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in dev.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
