### ISSUE TITLE
[SB] Resources > Study builder should not accept the PDF file with size more than 5MB

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3719]
To avoid performance issues on the mobile app, the Study Builder should not accept PDFs of size greater than 5MB to be uploaded by the admin

Also need to add a validation message  '**File size should not exceed 5MB**' as inline error message and it should  display when user tries to upload a file of higher size

A/R:- Study builder is accepting the PDF file more than 5MB
E/R:- Study builder should accepts up to 5MB only

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in QA instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
