### ISSUE TITLE
[SB] Questionnaires > Schedule tab > Wrong contents/values are getting displayed for custom schedule on launching the study or publishing the updates

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3721]
Steps
1. Login to SB
2. Create/Edit study
3. Navigate to questionnaires
4. Add questionnaires with a custom schedule
5. Launch/publish updates
6. Click on the edit button of the study
7. Go to questionnaires
8. Click on the particular questionnaire
9. Navigate to the schedule tab and observe

AR: Wrong contents are displayed for the custom schedule 
ER: Proper contents and values should be displayed

![custom9](https://user-images.githubusercontent.com/71445210/121310985-94a6df80-c921-11eb-8b27-67c4ad3a3fd4.png)

**Comment by harisboston** [comment]
From browser console:

jquery-3.1.1.min.js:2 Uncaught TypeError: Cannot read property 'minDate' of undefined
    at HTMLDivElement.<anonymous> (viewQuestionnaire.do?_S=1:2706)
    at Function.each (jquery-3.1.1.min.js:2)
    at r.fn.init.each (jquery-3.1.1.min.js:2)
    at HTMLDocument.<anonymous> (viewQuestionnaire.do?_S=1:2704)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
