### ISSUE TITLE
[SB] Overview > Page-1 is getting collapsed on clicking on Mark as completed without entering description field

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3722]
Steps:
1. Create a study
2. Navigate to Overview
3. Click on 'Mark as completed' without entering description field
4. Observe the behaviour

Actual: First page is getting collapsed on clicking on Mark as completed without entering description field

Expected: Page should not be collapsed and be visible to show the error message to admin

https://user-images.githubusercontent.com/60386291/121340176-ef016980-c93c-11eb-96b2-b2b980dd5a4f.mp4

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in dev

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev

**Comment by aswinijena100** [comment]
@nishit-v Please test in QA and close if fixed
