### ISSUE TITLE
[SB] [Copy/Import] Deleted notifications in original study are displayed for copied/imported study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3723]
Steps:
1. Edit a original study
2. Add a notification and keep it in draft/scheduled/sent status
3. Delete the notification
4. Copy/Import
5. Observe the notifications list for copied/imported study

Actual: Deleted notifications in original study are displayed for copied/imported study

Expected: Deleted notifications should not be retained for copied/imported study

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in QA and confirm.
