### ISSUE TITLE
[SB] HTML breakage in summer note editor in Instuction Step 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3725]
HTML breakage happened in instruction step for summer note field in particular scenario.

Steps:- 
1. Login to Study builder
2. Navigate to studies screen 
3. Navigate to Add study/ Edit Study
4. Navigate to Questionnaires
5. Add a Questionnaire 
6. Click on instruction step and add the content as shown
7. Click on Save button and Navigate to any other section 
8. Now Edit that instruction step added and verify 

A/R:- HTML is breaking in Summer note editor
E/R:- Content should displayed properly as configured

**Note**:- Issue is only happened for Instruction step. In other sections it is working fine.

When Saved:
![image](https://user-images.githubusercontent.com/60500517/121382085-e40dff80-c963-11eb-8007-2d8ae7e033b7.png)

When Edited
![image](https://user-images.githubusercontent.com/60500517/121382293-13bd0780-c964-11eb-8b22-16595af2ad47.png)

**Comment by harisboston** [comment]
@nagarjunav1 Issue is not replicable in dev environment, added data to test as per issue description.
Study ID: Activity,   Questionnaire: enroll007

**Comment by nagarjunav1** [comment]
![image](https://user-images.githubusercontent.com/60500517/121711170-ee610280-caf7-11eb-8e0c-9b742e449481.png)

**Comment by nagarjunav1** [comment]
@Haris Issue is replicable in dev environment, Study ID: Activity, Questionnaire: enroll007, Instruction3

**Comment by harisboston** [comment]
@nagarjunav1  Issue is fixed in QA instance, kindly test and update this ticket accordingly.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
