### ISSUE TITLE
[SB] [Import] App ID field should be cleared on importing a study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3727]
Steps:

1. Launch a study
2. Export and import the study
3. Observe the App ID field in a) studies list b) Basic information for the imported study

Actual: App ID field is getting retained on importing a study

Expected: App ID field should be cleared on importing a study

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev instance and update

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA and update.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA  instance.
