### ISSUE TITLE
[SB] Title of the import pop up should be left aligned as per the invision screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3728]
The title of the import pop up should be left-aligned as per the invision screen

![popup21](https://user-images.githubusercontent.com/71445210/121494505-6e06a880-c9f6-11eb-9543-89323434be36.png)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
