### ISSUE TITLE
[SB] [Import] Actions > Actions buttons are disabled for the studies which are imported by other admins

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3733]
**Steps**
1. log in to SB as admin A
2. Import a study
3. Logout
4. Login as admin B
5. Navigate to the Actions tab and observe

**AR:** All the actions buttons are disabled
**ER:** Actions buttons should work as expected

[**Note:** Issue observed only for the imported studies]

![image](https://user-images.githubusercontent.com/71445210/121547742-08341400-ca2a-11eb-96f6-298be01c2d23.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in dev and update the ticket accordingly.

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
