### ISSUE TITLE
[SB] Active tasks > Unable to add an active task with custom start date and study lifetime

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3737]
Steps:
1. Edit a study
2. Navigate to active task schedule tab
3. Select 'Regular' and 'One Time' as scheduling options
4. Select 'Custom start date and time' and enable 'study lifetime'
5. Fill rest of the details and click on done
6. Observe the error

Actual:  Unable to add an active task with custom start date and study lifetime

Expected:  Admin should be able to add active tasks without any error messages

Note: Issue not observed for questionnaires
Issue observed for all active tasks

Error screenshot
![AT4](https://user-images.githubusercontent.com/60386291/121710204-fd938080-caf6-11eb-9cbc-b1179df65867.png)

schedule configuration for which, error is displayed
![configuration](https://user-images.githubusercontent.com/60386291/121710357-29af0180-caf7-11eb-8bf5-03d0e6a50347.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test this and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.
