### ISSUE TITLE
[SB] Active tasks > Daily > Anchor days value is incorrect in GetStudyActivityList API

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3739]
Steps:
1. Configure a daily anchor based scheduling task
2. Enter 'X' days eg. 4
3. Fill rest of the details
4. Publish updates
5. Observe the anchor days value in GetStudyActivityList API

Actual: Anchor days value is incorrect in GetStudyActivityList API

Expected: Anchor days value should be same as value configured from SB

Issue not observed for other frequencies
Issue not observed for Questionnaires

SB:
![SB_config](https://user-images.githubusercontent.com/60386291/121721967-78ae6400-cb02-11eb-9d6e-8ccaf4b874a3.png)

API:
![XdaysIssue](https://user-images.githubusercontent.com/60386291/121722006-849a2600-cb02-11eb-8316-b2f5fb2af157.png)

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev instance and update

**Comment by nishit-v** [comment]
Issue is not resolved in latest dev instance.

![Reopen](https://user-images.githubusercontent.com/60386291/122009220-7c2e3d80-cdd7-11eb-9aee-108aa889b5a9.png)

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev instance and update

**Comment by nishit-v** [comment]
Issue is resolved in latest dev instance.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA instance and update

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.

**Comment by nishit-v** [comment]
Issue is observed again in Dev and QA.

Dev: `anchorDays` is displaying null

QA: `anchorDays` parameter itself is not displayed for `start` array

Refer screenshots:

Dev: 
![Screenshot_2](https://user-images.githubusercontent.com/60386291/124431218-ba42cf80-dd8d-11eb-8022-7747f0c28586.png)


QA: 
![qa](https://user-images.githubusercontent.com/60386291/124431281-cc247280-dd8d-11eb-9f2b-64cd7b3456ac.png)


Study details:
Dev: ImageStudy
ActivityID - fkc_target

QA: imported0739
ActivityID - fkc_target

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
