### ISSUE TITLE
[SB] Custom schedule > Anchor based scheduling > 'time' value displaying in incorrect format and hence activities are not displayed in mobile apps

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3740]
Steps:
1. Configure a custom schedule anchor based questionnaires/active tasks
2. Fill rest of the details
3. Publish updates
4. Observe the activities in mobile apps or GetStudyActivityList API

Actual: 'time' value displaying in `HH:MM`

Expected: 'time' value should display in `HH:MM:SS`

Note:
Issue observed for questionnaires and active tasks
Issue observed only for anchor based custom scheduling

![Screenshot_1](https://user-images.githubusercontent.com/60386291/121722761-5701ac80-cb03-11eb-89c6-8e9a7c27fb85.png)

**Comment by nishit-v** [comment]
Issue is still not fixed. Tested for new activities

![Screenshot_2](https://user-images.githubusercontent.com/60386291/121863976-057f3a80-cd1a-11eb-88c7-8aec14618496.png)

**Comment by nishit-v** [comment]
Issue is resolved in latest dev instance.

**Comment by harisboston** [comment]
@nishit-v  Issue is fixed in QA instance, kindly test and update this ticket accordingly.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance.
