### ISSUE TITLE
[SB] Questionnaires/Active task > Custom schedule > Use proper text case for the error messages

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3743]
Questionnaires/Active task > Custom schedule > Use proper text case for the error messages

[Note: Issue should be fixed in all the fields of custom schedule]

![image](https://user-images.githubusercontent.com/71445210/121847003-8d0e7e80-cd05-11eb-84b3-af2b43b35f99.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
@monica-BTC HTML is breaking in Active task


![image](https://user-images.githubusercontent.com/71445210/121898092-a680ec00-cd40-11eb-953d-06e12276a8e4.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
