### ISSUE TITLE
[SB] The following error message should be changed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3745]
**AR:** `The characters like (< >) are not allowed` error message is getting displayed when a user enters other than the following special characters 
**Allowed characters:** `*()+.|_-:`

**ER:** The error message should be changed to `Please use characters from the following set only: A-Z a-z 0-9 *()_+|:.-`

**Note:** It should be fixed in all the places where ever this error message comes
Eg: 
Study info > Study ID and App ID
Eligibility test > Question key or short title 
and etc.....

![title11](https://user-images.githubusercontent.com/71445210/121889460-e511a900-cd36-11eb-9f40-28d368fe889d.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest Dev build

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
