### ISSUE TITLE
[Android] Custom Schedule > Anchor date based > Additional random schedule data is shown for custom schedules in upcoming section

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3747]
Steps:
1. Configure anchor date based custom schedule so that it will show in upcoming in mobile
2. Observe the start date and time in Android Mobile

Actual: Additional random schedule data is shown for custom schedules in upcoming section

Expected: Start and End time for all the runs should be as per configured from SB

Notes:
1. Issue observed for both questionnaires and active tasks
2. Issue observed only for anchor based custom schedule
3. Issue NOT observed when activities are in 'Current' /' 'Past' section

![Androidcustom](https://user-images.githubusercontent.com/60386291/122042651-0c7c7a80-cdf8-11eb-8ac7-92068131d3ff.png)

**Comment by nishit-v** [comment]
Study details:
Study Name - Activity Study 2
Activity IDs - fkc_target_008, fkc_enroll_007, target007, enroll007

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev build V1.0.213

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build v1.0(89)
