### ISSUE TITLE
[SB] One Time > Previously entered data is getting retained for 'startTime' and 'endTime' in the GetStudyActivityList API in one of the scenario

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3750]
Steps:
1. Edit study
2. Navigate to Questionnaires/active tasks
3. Add activity with Regular/Anchor based for One time
4. Enter custom start date and time
5. Enter custom end date
6. Now select 'Launch with study' option and 'Study lifetime'
7. Fill rest of the details and publish
8. Observe the activity in mobile or GetStudyActivityList API

Actual: Data entered in step 4 and step 5 is getting retained even though  'Launch with study' option and 'Study lifetime' is selected for OneTime

Expected: Data entered should not be retained

Note:
Issue observed for both questionnaires and active tasks
Issue observed for OneTime - Regular and anchor based
Issue observed in QA and Dev instance

![SB](https://user-images.githubusercontent.com/60386291/122047114-603d9280-cdfd-11eb-8361-0e39d362cfd9.png)

![SB_Issue](https://user-images.githubusercontent.com/60386291/122047122-63388300-cdfd-11eb-878c-2d103b16caf2.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
