### ISSUE TITLE
[SB] > Active Tasks > Error message is overlapped on static text 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3751]
Steps:- 
1. Login into SB
2. Navigate to studies and edit study
3. Navigate to active tasks
4. Configure the Statistics for Active tasks
5. Enter the non-allowed characters like **<>** into Short name field and verify

A/R:- Error message is overlapping on below static text
E/R:- Error message should be adjust to not overlap on other elements

![image](https://user-images.githubusercontent.com/60500517/122058677-7ea98b00-ce09-11eb-932d-2f67c3973c46.png)

**Comment by navya-BTC** [comment]
@nagarjunav1 please test this issue in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by navya-BTC** [comment]
@nagarjunav1 please test this issue in QA

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
