### ISSUE TITLE
[SB] Questionnaires > Question step > Image choice > Added images are not getting saved

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3757]
Steps
1. Add/Edit questionnaire
2. Click on the Question step
3. Question level attributes > Select Image choice response type
4. Enter all the mandatory fields 
5. Click on Save/Done button
6. Click on the edit button of the image choice question
7. Observe the added images

AR: Images are not getting saved
ER: Images should be saved  

![imagec1](https://user-images.githubusercontent.com/71445210/122228214-41aaca80-ced5-11eb-8d04-59ab260a92b8.png)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in QA and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
