### ISSUE TITLE
[SB] [Import] Comprehension test section > Edit comprehension test question > Order of the options should be the same as the original study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3760]
**AR:** Comprehension test section > Edit comprehension test question > Order of the options are getting changed for the imported study
**ER:** The order of the options should be the same as the original study

![cmpt1](https://user-images.githubusercontent.com/71445210/122235231-26db5480-cedb-11eb-88c9-ea8c2a5df1eb.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in QA and confirm.
