### ISSUE TITLE
[SB] [Import] Questionnaires/Active task > Schedule tab > Daily frequency > Order of the added runs should be the same as the original study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3761]
**Steps:**
1. Go to questionnaires 
2. Add questionnaires with daily frequency (Add multiple runs)
3. Export and import the particular study
4. Click on the edit button of the imported study
5. Navigate to the questionnaires section
6. Click on the edit button of the particular study
7. Switch to the schedule tab
8. Observe the order of the runs

**AR:** The order of the runs is getting changed
**ER:** The order of the runs should be the same as the original study

[**Note:** Issue should be fixed for Regular, Anchor date based questionnaires and active tasks]

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.
