### ISSUE TITLE
[SB] Study level notification > Resend notification > The following text should be displayed for the history  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3762]
Steps
1. Go to active study
2. Navigate to notifications
3. Send a notification
4. Wait till notification sent to the users
5. Click on resend notification button
6. Observe the text for the history

AR: A text is missed for the sent history
ER: `Previously sent on:`text should be displayed for the history

![sln1](https://user-images.githubusercontent.com/71445210/122240668-95221600-cedf-11eb-9278-cfdff817d268.png)

For reference: App level notification 

![aln1](https://user-images.githubusercontent.com/71445210/122240839-b2ef7b00-cedf-11eb-9c81-b76abd5db03b.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
