### ISSUE TITLE
[PM] Responsive issue (functionality) > Participant details page

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3766]
**Participant details page**

**AR:** 'Resent invitation button is displayed for the participants who are having onboarding status=Disabled
**ER:** 'Resend invitation' button should not be displayed and Only the 'Enable invitation'  button should be displayed when the participant Onboarding status = Disabled

![admin122](https://user-images.githubusercontent.com/71445210/122364226-34461c80-cf77-11eb-9fce-be15d5060de9.png)

[**Note:** This issue does not happen in desktop view]

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
