### ISSUE TITLE
[PM] Responsive issue in Enrollment registry screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3767]
The responsive issue in the Enrollment registry screen

![er11](https://user-images.githubusercontent.com/71445210/122365075-fdbcd180-cf77-11eb-802d-ba4302cb4ec6.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is still reproducible
1. Enrollment target should be displayed in the white frame
2. Edit button and text is not aligned properly


![imge121](https://user-images.githubusercontent.com/71445210/124083675-c831e100-da6b-11eb-9027-c79954a4d9d4.png)

**Comment by Lathan-btc** [comment]
@Madhud5 There is no proper alignment between edit button and enrollment target text

![responsive1](https://user-images.githubusercontent.com/71445210/124144283-73ad5680-daa9-11eb-96ee-bfe04580a182.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test it in QA and close if fixed

**Comment by nagarjunav1** [comment]
Issue is still not fixed in QA build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
