### ISSUE TITLE
[SB] Questionnaires/Active task > Anchor based > Schedule tab > Validations needs to be handled for custom schedule

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3769]
Questionnaires/Active task > Anchor based > Schedule tab >

1. Unable to add same value for 'X' days and 'Y' days
2. '+' icon is not enabled post entering same value for 'X' days and 'Y' days in the first row

Expected:
1. Admin should be able to add same value for 'X' days and 'Y' days for one row or multiple rows as long as there is NO time overlap between the runs
2. +' icon should be enabled post entering same value for 'X' days and 'Y' days in the first row

Note:
Validation should be handled for questionnaires and active tasks
Validation should be handled for 'Enrollment' anchor date based and Source date questionnaire based
Validation should be handled properly even after deleting the rows in between

![Screenshot_1](https://user-images.githubusercontent.com/60386291/122387663-b7be3880-cf8c-11eb-85c6-308bc481abe2.png)

**Comment by harisboston** [comment]
@nishit-v Issue is fixed in dev environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
@harisboston Please find below issues for above validation:

1. If admin enters Y time ≤ X time, entered time in Y field should be removed (Refer Regular custom schedule for functionality). Admin able to click on done and publish updates in this scenario

![SB_AT_2](https://user-images.githubusercontent.com/60386291/123673574-428d1600-d85e-11eb-8bd9-731fb79ede77.png)

2. If admin fills negative Values in 1st row and enters positive X value in 2nd row, incorrect validation message is displayed.

![SB_AT_1](https://user-images.githubusercontent.com/60386291/123673765-7b2cef80-d85e-11eb-8e8a-a1a2131095cf.png)

Issue observed for both Questionnaires and Active tasks

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.

**Comment by harisboston** [comment]
@nishit-v  Issue fix is deployed in QA, kindly test and close this issue

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
