### ISSUE TITLE
[PM] Responsive issue in the Participant details page 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3770]
Participant details page > UI issue

![ui table](https://user-images.githubusercontent.com/71445210/122389084-2f409780-cf8e-11eb-92d5-6a6e52c95a03.png)

**Comment by Madhud5** [comment]
Hi @latha i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
Hi @Lathan-btc   please check in QA and close if issue fixed

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is still reproducible in the latest QA instance.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.
