### ISSUE TITLE
[SB] Questionnaires > Anchor based > Unable to enter time from 2nd run onwards for daily frequency

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3772]
Steps:
1. Edit a study
2. Navigate to Questionnaires
3. Selecte anchor based and select daily
4. Enter 'X' days and number of times to repeat field
5. Enter time for 1st time field
6. CLick on '+' icon and try to enter time for 2nd time field
7. Observe

A/R: Unable to enter time from 2nd run onwards for daily frequency

E/R: User should be able to enter time from 2nd run onwards for daily frequency

Issue not observed for active tasks regular/anchor based
Issue not observed for questionnaires - regular

![Screenshot_1](https://user-images.githubusercontent.com/60386291/122398862-eee61700-cf97-11eb-92b0-f9f3f75d3c69.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in Dev instance

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance

**Comment by nishit-v** [comment]
Issue is observed again in QA instance .

Note: Not observed in Dev instance.

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
