### ISSUE TITLE
[PM] responsive issue > UI issue in the table

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3773]
1. 'No records found' and pagination links should be center-aligned

![norecords](https://user-images.githubusercontent.com/71445210/122406593-97977500-cf9e-11eb-83e6-04b30b484b6c.png)

2. 'Sort by:' text should be removed for the tables

![sort1](https://user-images.githubusercontent.com/71445210/122412721-6f5e4500-cfa3-11eb-9993-61a955cf3287.png)

[Note: It should be fixed in all the places wherever above mentioned contents are present]

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
@Madhud5 
1. 'No records found' and pagination links should be center-aligned - issue reproducible for Site participant registry and study participant registry

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test it in QA and close if fixed

**Comment by nagarjunav1** [comment]
Issue is not fixed in latest QA build

**Comment by aswinijena100** [comment]
@nagarjunav1 lease test it in QA and close if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
