### ISSUE TITLE
[PM] Responsive issue in hamburger menu 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3775]
The hamburger menu button is overlapping with the horizontal scrollbar

![scrlbar](https://user-images.githubusercontent.com/71445210/122417963-84d56e00-cfa7-11eb-939e-6b618bb5d62b.png)

**Comment by Madhud5** [comment]
Hi @latha i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is still reproducible in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev istance.

**Comment by aswinijena100** [comment]
Hi @Lathan-btc  please check in QA and close if issue fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
