### ISSUE TITLE
[SB] Questionnaires > Question step/Form step > User is able to click on Done button in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3782]
Steps
1. Go to questionnaires
2. Add Question step/Form step
3. Add image choice questionnaire
4. Click on the edit button of the questionnaire
5. Go to the response level attributes tab  
6. Enter the invalid format image
7. After getting an error message try to click on the Done button 

AR: The user is able to click on the Done button
ER: User should not be able to click on Done button

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
@monica-BTC Issue is again reproducible when the user uploaded invalid file format other than the invalid image size

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in dev.

**Comment by bhoomikav16** [comment]
Issue is fixed in latest dev instance

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
