### ISSUE TITLE
[SB] Questionnaires > Form step > Added images are not getting saved for the following scenario 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3783]
Steps
1. Go to questionnaires
2. Add/Edit questionnaire
3. Add Form step
4. Select Scale/continuous scale response type
5. Add images for min and max values
6. Enter all the required values
7. Click on the Done button 
8. Navigate to edit questionnaire page
9. Switch to Response level attributes tab
10. Observe the added images

AR: Uploaded images are not getting displayed 
ER: Uploaded images should be displayed

[Note: Issue not observed when user clicks on Save and Done button]

![image211](https://user-images.githubusercontent.com/71445210/122520319-14732f00-d031-11eb-83a9-c7bea2d2e223.jpg)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
