### ISSUE TITLE
Is there a branch with a working iOS build environment, or documentation with how to achieve a clean build?

### ISSUE THREAD

**Issue by brainsnorkel** [GoogleCloudPlatform/fda-mystudies#3786]
**What are you trying to accomplish?**

I have been trying to build the 2.0.5 iOS app and struggling with getting a clean build. I've managed it, but It seems there is either missing documentation, or out of date code in the release.

**What have your tried so far?**

To get the app building I have had to:

* Configure my own bundle and apple developer account (that's ok, pretty easy to work out)
* Set the main app deployment to ios 13.0 and add the following to the end of the Podfile:

```
post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
```

* I have also had to change the version of CryptoSwift in Podfile.lock to:

```
  - CryptoSwift (1.3.3)
```

I wondered if the documentation could be enhanced slightly, or if I hadn't found the right documentation to follow.

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello @brainsnorkel 

1)The CryptoSwift and other pod changes we have addressed in PR #3873 .
2)The project target OS version we have set to iOS 13 and above. This is addressed in 2.5 release.
3)The Target build version we have kept iOS 11 for the GitHub build actions. As the Build actions we target for iPhone 11 which still has the iOS 11 support and we have to retain the target version to iOS 11. This wont affect the normal functionality of the project. 

Thank you,
Govind
