### ISSUE TITLE
[SB] [Import] [QA] Unable to import the study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3787]
Steps:
1. Edit a study
2. Export a study and copy URL
3. Try to import and enter copied URL
4. Observe the message

Actual: 'Please enter valid URL' error message is displayed

Expected: Study should be imported

Issue observed only in QA instance

**Comment by nishit-v** [comment]
Issue is resolved in latest QA build.

**Comment by navya-BTC** [comment]
@nishit-v PR is merged, please close this issue if it is working.

**Comment by navya-BTC** [comment]
@nishit-v PR is merged, please close this issue if it is working.
