### ISSUE TITLE
[SB] [Import] Unable to import the study from different environment

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3788]
Steps:
1. Login to env A
2. Edit a study and export
3. Copy the URL
4. Login to env B
5. Try to import the study and observe

Actual: 'Please enter valid URL' error message is displayed

Expected: Study should be imported

Issue observed if A and B is QA and Dev env or vice versa respectively

**Comment by nishit-v** [comment]
Issue is still not resolved in latest build.

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue by exporting the study either in QA or dev.

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue and let me know if the issue still exists

**Comment by nishit-v** [comment]
Issue is resolved in latest QA and Dev

**Comment by nishit-v** [comment]
Issue is resolved in latest QA and Dev (After PR merge)
