### ISSUE TITLE
[SB] [Copy] Comprehension test  section > Actions buttons are non functional for the comprehension test questions

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3791]
Comprehension test  section > Actions buttons are non functional for the comprehension test questions

[**Note:** Issue observed only in the QA instance]

![actions1](https://user-images.githubusercontent.com/71445210/122758880-ef8fed80-d2b6-11eb-949e-134ff9da776c.png)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance (before PR)

**Comment by navya-BTC** [comment]
@Lathan-btc PR is merged, please close this issue if it is working.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
