### ISSUE TITLE
[SB] Consent sections created are not reflecting in Auto-created consent document

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3792]
Note:- Issue is happened only in QA instance #3526 

![image](https://user-images.githubusercontent.com/60500517/122759782-f79c5d00-d2b7-11eb-83da-a4c43355e3bb.png)

![image](https://user-images.githubusercontent.com/60500517/122759809-fff49800-d2b7-11eb-900a-a3ea3e3612b6.png)

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in QA instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
