### ISSUE TITLE
[SB] [QA] E-Consent steps > Consent document tab > Highlighted text should be removed 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3796]
E-Consent steps > Consent document tab > Highlighted text should be removed as it is a part of the 2.0.7 release

[Note: Text should be removed only in QA instance]

![consent21](https://user-images.githubusercontent.com/71445210/122876377-11d74900-d353-11eb-9364-796b44267bf0.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
