### ISSUE TITLE
[SB] [QA] Active tasks custom schedule > Three time fields are showing for each custom schedule row and UI is distorted

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3797]
Steps:
1. Edit a study
2. Add an active with custom schedule
3. Fill the details
4. Again click on edit for the active task
5. Navigate to active task custom schedule
6. Observe

A/R: Three time fields are showing for each custom schedule row and UI is distorted

E/R: Only starttime and endtime fields should display for each custom schedule row and UI should be proper

Issue observed only for Regular type frequency
Issue observed only for active tasks

![Screenshot_1](https://user-images.githubusercontent.com/60386291/122885765-ff620d00-d35c-11eb-8a5f-dc2f05681fb2.png)

**Comment by harisboston** [comment]
@nishit-v Issue is fixed in QA instance, kindly test and update this ticket

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance. (Before PR)

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance. (After PR)
