### ISSUE TITLE
[SB] [Import] Images and Resource PDFs are not getting retained on importing from one environment to other environment

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3799]
Steps:
1. Login to env A
2. Edit a study and export
3. Login to env B
4. Import the study
5. Observe the images in env B for imported study

Actual: Images and Resource PDFs are not getting retained on importing from one environment to other environment .

Issue observed for
1. Thumbnail images
2. Overview images
3. Image choice questions
4. Images in scale and continuous scale response types
5. PDFs uploaded in resources

Expected: Images and Resource PDFs should be retained on importing from one environment to other environment .

**Comment by madhurya-btc** [comment]
@nishit-v please test and confirm in dev instance

**Comment by nishit-v** [comment]
Images are fixed for copied/imported study in Dev

Resource PDFs are fixed for copied study

Some of the resource PDFs fails to load for imported study

Study details:
1. Image Study (imported0904)
2. PDF name - 1mb

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Images and resources fails to import in the below scenario

1. Export a study from env A
2. Copy the URL
3. Import the study in env B
4. Edit a study
5. Observe thumbnail image is displayed
6. Click on Mark as complete
7. Observe the images imported are not displayed


https://user-images.githubusercontent.com/60386291/124252760-ef101600-db44-11eb-8589-413626263b89.mp4

**Comment by madhurya-btc** [comment]
@nishit-v Please check and confirm

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev and QA (Before PR merge)

**Comment by madhurya-btc** [comment]
@nishit-v  Please test in QA instance
