### ISSUE TITLE
[SB] Some of the imported studies are not getting displayed in the studies list

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3800]
**Steps:**
1. Login to QA SB 
2. Export and copy the signed URL for the below mentioned study
3. Login to Dev SB
4. Click on the Import button on the studies list screen
5. Enter copied URL in step 2 
6. Click on Submit and observe

**Study ID:** NewStudy
**Study name:** New Study 

**AR:** Imported study is not getting displayed
**ER:** Imported study should be displayed in the studies list

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please create a new study and try to reproduce this for newly created study and let me if issue exists.

**Comment by Lathan-btc** [comment]
Issue is not reproducible for other studies, so the issue will be under observation.

**Comment by Lathan-btc** [comment]
Issue is not reproducible in the latest Dev or QA instance.

**Comment by Lathan-btc** [comment]
@Kantharajut-btc issue is reproducible for the following scenario

**Steps:**
1. Login as Super admin1
2. Add admin2
3. Create an account for admin2 and login with admin2 credentials
4. Create a study in one environment
5. Try to import that created study in another environment

**AR:** Imported study is not getting displayed in the studies list
**ER:** Imported studies should be displayed in the studies list 

[**Note:** If any studies are created by newly added admin, then that particular imported study in another environment is not getting displayed]

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in dev and qa, update accordingly

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
