### ISSUE TITLE
[SB] [Copy/Import] Edit eligibility question > 'Question key or short title' field is disabled 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3802]
**Steps:**
1. Add eligibility questions for a study
2. Launch the study
3. Copy/Import the particular study
4. Click on the edit button of the newly created study
5. Navigate to the Eligibility section
6. Click on the edit button of the question
7. Observe the 'Question key or short title'

**AR:** 'Question key or short title' field is disabled
**ER:** Field should be enabled and it should be editable in prelaunch status

**Note:** 
1. Issue observed only when user copy/import the active study
 2. Issue should be fixed for both Active and Paused study

 
![et3](https://user-images.githubusercontent.com/71445210/122940829-72d24180-d392-11eb-8725-b70e404ed8f7.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
