### ISSUE TITLE
[SB] [Import] Overview > Order of the overview pages is getting changed in mobile apps

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3807]
A/R: In the Original study order of the overview screen is Page1, Page2, Page3, Page4, and Page5

E/R: In the Imported study order of the overview screen is Page1, Page3, Page2, Page4, and Page5

Issue not observed in SB
Issue observed in Android and iOS mobile apps

Order is incorrect in `GetStudyInfo` API

![Overview](https://user-images.githubusercontent.com/60386291/122955940-3278c080-d39e-11eb-9699-31739899b001.png)

**Comment by monica-BTC** [comment]
@nishit-v, please check this issue and confirm in dev

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm in QA

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance
