### ISSUE TITLE
[SB] [Export] Opening the exported study URL in browser downloading as SQL file exposing all the queries

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3812]
Steps:
1. Edit a study and export
2. Copy the URL
3. Hit the URL in browser
4. File is downloaded as SQL file
5. Edit the file and observe

Actual: Opening the exported study URL in browser downloading as SQL file exposing all the queries

Expected: Opening the study URL should NOT download any file or expose any queries

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please test and confirm

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in QA, please test and confirm

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.(Before PR)

**Comment by Kantharajut-btc** [comment]
@nishit-v PR is merged with develop branch, please test in QA and confirm.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.(After PR)
