### ISSUE TITLE
[SB] [Import] Wrong pop up window is getting displayed on importing from one environment to other environment

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3813]
**Steps:**
1. Login to env A
2. Click on any original study and export
3. Login to env B
4. Import the study
5. Observe the popup 

**AR:** Wrong popup window getting displayed. 
If the user clicks on 'Resend' then the study is getting imported successfully
If the user clicks on the 'Cancel' button then the study is not getting displayed in the studies list screen until and unless the user refreshes the page

**ER:** Popup window should not be displayed

[**Note:** Issue observed only in firefox browser]

![image](https://user-images.githubusercontent.com/71445210/123095866-22b7b580-d44c-11eb-8b59-4e1e417928e7.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test the issue once deployed in QA.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc  PR is merged with develop branch, please test in QA and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
