### ISSUE TITLE
[PM] Responsive issue > Customer logo is not getting displayed on error pages

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3816]
AR: Customer logo is not getting displayed on error pages
ER: Customer logo should be displayed on all the error pages and if the user click on logo then user should be navigate to sign in page

![image](https://user-images.githubusercontent.com/71445210/123227496-41708780-d4f2-11eb-84d9-d60896a3c8a3.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
