### ISSUE TITLE
[SB] My Account > Account Manager text should be removed in my account screen

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3817]
A/R:- Currently it is displaying for the account with super admin role
E/R:- Text should be removed for accounts with any role

![image](https://user-images.githubusercontent.com/60500517/123229586-125b1580-d4f4-11eb-8041-b16f32af6d2e.png)

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in dev.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest Dev build

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in QA.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
