### ISSUE TITLE
[PM] Responsive issue > Site participant registry > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3818]
Responsive issue > Site participant registry > Text is overlapping with scroll bar

[Note: Issue observed only in firefox browser]

![spm1](https://user-images.githubusercontent.com/71445210/123251420-cff00380-d508-11eb-883b-5a89317847e1.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is reproducible in the latest Dev instance

![img212](https://user-images.githubusercontent.com/71445210/124082042-e565b000-da69-11eb-9d5b-dd1ec7be4dde.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test it in QA and close if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
