### ISSUE TITLE
[SB] Study information page > Entered lower case data in app ID is getting converted into upper case for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3823]
Steps
1. Login to SB
2. Click on Create new study
3. In the basic info page enter all the required values
4. Enter the lower case data in the app id field
5. Click on Save/Mark as completed button
6. Observe the entered data in the app ID field

AR: Entered lower case data in app ID is getting converted into upper case
ER: The entered data by the user should be shown in the same format when the user clicks on save/mac

[**Note:** Issue is not happening for the editing study]

**Before clicking on Save or Mark as completed**

![bf](https://user-images.githubusercontent.com/71445210/123286237-5e757c80-d52b-11eb-879e-244bfe347016.png)

**After clicking on Save or Mark as completed** 

![as](https://user-images.githubusercontent.com/71445210/123286409-8369ef80-d52b-11eb-9793-a5b878817ee8.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please this issue in dev and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test it in QA and close if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
