### ISSUE TITLE
[SB] [Import] Import study popup > Error message is getting displayed when user clicks Cancel button 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3824]
**AR:** Import study popup > Error message is getting displayed when user clicks Cancel button
**ER:** Any error message should not be displayed

![cancel button1](https://user-images.githubusercontent.com/71445210/123288015-d09a9100-d52c-11eb-9c93-0917bed49a88.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in dev and confirm.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please test and confirm.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
