### ISSUE TITLE
[SB] Import study popup > Submit button non functional occasionally in firefox browser

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3828]
Steps
1. Click on any study 
2. Export and copy signed URL
3. Navigate to the Studies list screen
4. Click on the Import button
5. Enter copied signed URL
6. Edit some characters in the URL
7.  Try to click on Submit button

AR: Submit button non functional occasionally in firefox browser
ER: Button should be functional and if the user clicks on submit button then 'Please enter a valid URL' error message should be displayed 

[Note: Issue observed only in firefox browser]

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
