### ISSUE TITLE
[SB] [Import] Newly created studies are getting displayed on studies list screen based on the exported time instead of imported time

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3833]
Steps:
1. Export study A
2. Export study B
3. First import study B
4. Then import the study A
5. Observe the order of the studies displayed in the list

AR: According to the above scenario study B is getting displayed in the top
ER: Study A should be displayed in the top

[Note: Newly created studies by importing should be displayed based on the imported time instead of the exported time of the study]

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed in dev, please test and confirm.

**Comment by nagarjunav1** [comment]
Issue is still reproducible in Dev instance

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 please check now.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest Dev build

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please test and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
