### ISSUE TITLE
[SB] App level notifications > Order of the notifications should be displayed based on the created date and time

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3835]
**AR:** Created notifications are displayed in the alphabetical order
**ER:** Order of the notifications should be displayed based on the created date and time

**Comment by monica-BTC** [comment]
@nagarjunav1, please test this issue and confirm in dev.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
