### ISSUE TITLE
[SB] Notifications > Old notification list is displayed for newly signed mobile participants

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3839]
Steps:
1. Signup in Android/iOS mobile
2. Navigate to studies list
3. Click on Notifications icon
4. Observe the list

Actual: Old notification list is displayed for newly signed mobile participants

Expected: Old notification list should not be displayed for newly signed mobile participants

Refer screenshot (Below participant signed up on 06/29):

![old](https://user-images.githubusercontent.com/60386291/123762628-9f311500-d8e0-11eb-924f-98c165f5f58c.png)

**Comment by Kantharajut-btc** [comment]
@naveenr-btc @GovindPrasadBostonTechnologyCorporation please send `verificationTime ` as a request param in /notifications endpoint. please check  /userProfile API response to get `verificationTime `

**Comment by nagarjunav1** [comment]
As per discussion and final conclusion with BA and DEV team, notifications list behavior on different scenarios are as follows:-

1)If an old user signed in, notification List should display  App Level + Study level notifications (Specific to users)

2)If user without sign in click on get Started button and navigated to the notification list,  - App level Notifications to be shown

3)If new user Signup, app level notifications to be shown and user should see app-level notifications on initial sign up same as what he saw before sign up.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build in Android v1.0(97) as per above comment.

**Comment by nishit-v** [comment]
Issue is fixed in latest DEV build in iOS v1.0(243) as per above comment.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA build in iOS v1.0(259).
