### ISSUE TITLE
[SB] Questionnaires > Instruction step > Done functionality is happening instead of Save when user clicks on save for the following scenario  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3841]
Steps
1. Login to SB
2. Click on any study
3. Navigate to questionnaires
4. Click on Add/Edit questionnaire
5. Add/Edit instruction step
6. Don't enter the 'Instruction text (500 characters max) *' field
7. Click on Save and observe

AR: 'Please fill out this field' error message is getting displayed and entered data is not getting saved
ER: Entered data should be saved and an error message should not be displayed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test in QA and close if fixed

**Comment by bhoomikav16** [comment]
Issue is fixed in the qa instance
