### ISSUE TITLE
[SB] Comprehension test > Add comprehension test > One of the answer options is getting removed for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3845]
**Steps:**
1. Login to SB
2. Click on edit study
3. Navigate to the Comprehension test section
4. Add/edit comprehension test
5. Enter the values only for the one row of the answer options
6. Click on the Save button
7. Click on the back button
8. Click on edit comprehension test question 
9. Observe

**AR:** One of the answer options is getting removed and the user is able to click on the done button
**ER:** Minimum 2 answer options should be present

![ao](https://user-images.githubusercontent.com/71445210/123908792-a9f9b180-d995-11eb-9173-1c41f9f0c12c.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
