### ISSUE TITLE
[SB] Issue when user clicks on Save button for the below mentioned screens

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3846]
**Steps**
1. log in to SB
2. Click on edit study
3. Navigate to the Consent section
4. Add/edit consent
5. Don't enter the values into the Brief summary, Long description, and Show as a visual step?
6. Click on the Done button
7. After fields validation click on the Save button
8. Observe

**AR:** Validation messages are getting displayed after clicking on the Save button
**ER:** Validation message should not be displayed 

**Note:**
 Issue also be fixed for the following screens
1. Consent section > Brief summary, Long description, and Show as a visual step? fields
2. Questionnaires > Add question step/form step > Question text and Display text fields  
3. Questionnaire > all the fields under HealthKit, line chart, and statistics on the dashboard 
4. Questionnaires > Question step/Form step > Fields in response level attributes tab
5. Questionnaires > Instruction step > Title field

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@nagarjunav1, please test this issue and confirm in QA

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest qa instance
