### ISSUE TITLE
[SB] Anchor date based custom scheduling > Order of anchor runs is incorrect in GetStudyActivityList API

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3848]
Steps:
1. Configure a date based source questionnaire
2. Add a questionnaire and choose anchor based custom schdule
3. Configure some runs involving negative X/Y values
4. Publish updates
5. Observe the order in GetStudyActivityList API

Actual: Order is incorrect

Expected: Order should lowest X value run to Highest

Issue should be fixed for questionnaires and active tasks custom schedule
Issue should be fixed for `start `& `end `arrays and `anchorRuns `array

![Screenshot_3](https://user-images.githubusercontent.com/60386291/123982041-5c566680-d9e0-11eb-8d0e-edae6384289d.png)

![Screenshot_4](https://user-images.githubusercontent.com/60386291/123982073-5fe9ed80-d9e0-11eb-81e9-9549594e9a3d.png)

**Comment by harisboston** [comment]
@nishit-v issue is fixed in dev env, kindly test and update this ticket

**Comment by nishit-v** [comment]
@harisboston Sorting issue is fixed for original study. But issue is observed for imported study, 

Actual: Sorting for imported study is in incorrect order

Expected: Sorting for imported study should be same as of original study

Study details (Dev):
1. Original study - iOStest5
2. Imported study - imported0812
3. Activity IDs - a1,a2,a3,c1,c2,c3

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
