### ISSUE TITLE
[PM] Responsive issue > Issues in Set up password screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3850]
Responsive issue > Issues in Set up password screen
1. Hamburger menu button should not be displayed
2. Customer logo should be disabled

![sps](https://user-images.githubusercontent.com/71445210/123985213-e99aba80-d9e2-11eb-968a-66041976add4.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and let me know.
Thank you.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test and close if fixed in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
