### ISSUE TITLE
[PM] Responsive issue > Set up account screen > Customer logo is not getting displayed 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3851]
Responsive issue 
AR: Set up account screen > Customer logo is not getting displayed 
ER: Set up account screen > Customer logo should be displayed 

![image](https://user-images.githubusercontent.com/71445210/123988440-a68e1680-d9e5-11eb-99ec-67087e4d67f9.png)

**Comment by Madhud5** [comment]
Hi, @Lathan-btc I have fixed it in dev please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test and close if fixed in QA

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest QA instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  pls check this

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
