### ISSUE TITLE
[PM] Blank screen is getting displayed for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3852]
**Steps:**
1. Login as admin a
2. Add admin b
3. Go to the inbox of the admin b 
4. Click on the received account activation link
5. Set up the account successfully
6. Click on forgot password link
7. Enter that newly created admin email id
8. Click on submit button
9. Observe

AR: After getting toast message blank screen is getting displayed
ER: Login screen should be displayed 

[Note: Issue is observed only when after creating an account if the user tries to forgot password without closing the tab/browser]

![image](https://user-images.githubusercontent.com/71445210/123994445-04712d00-d9eb-11eb-9280-8538d1b14d52.png)

**Comment by Rashi-395** [comment]
@Lathan-btc [PM] Blank screen is getting displayed for the following scenario #3852 -fixed and deployed

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance.

**Comment by Rashi-395** [comment]
@Lathan-btc [PM] Blank screen is getting displayed for the following scenario is fixed . Please check

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
