### ISSUE TITLE
[SB] [Import] Resources > Some of the resource PDF's file fails to import for imported study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3854]
**Steps:**
1. Edit a study
2. Navigate to resources
3. Add a resource with PDF
4. Export the study and import
5. Open the PDF file in imported study

**Actual:** Some of the resource PDF's file fails to import for imported study

**Expected:** All Resource PDFs should be imported successfully

Issue not observed for other PDFs and observed only for that particular PDF
Issue not observed for copied study

**Study details:**

Image Study (imported0904)
PDF name - 1mb

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance

**Comment by nishit-v** [comment]
Issue is fixed in dev instance. (Exported from QA and Imported in Dev)

**Comment by madhurya-btc** [comment]
@nishit-v Please test in QA instance

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
