### ISSUE TITLE
[SB] Questionnaires > Instruction step > Validation message is not getting displayed for the 'Title' field in the following scenario  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3858]
**Steps**
1. Login to SB
2. Click on edit study
3. Navigate to questionnaires
4. Add/Edit questionnaire
5. Click on Add instruction step
6. Without entering any data click on the Done button 
7. Observe

**AR:** Validation message is not getting displayed for the 'Title' field
**ER:** 'Please fill out this field' error message should be displayed because it is a mandatory field 

![img2121](https://user-images.githubusercontent.com/71445210/124124580-38edf300-da96-11eb-87db-ad1efd2dd548.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and confirm.
.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by nagarjunav1** [comment]
A/R:- Validation message is still displaying after text is entered and click on save button
 E/R:- Validation messages should not display after text is entered
 
 
![image](https://user-images.githubusercontent.com/60500517/124281228-24c5f680-db67-11eb-8d90-76b3bc0bdc68.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
