### ISSUE TITLE
[SB] Anchor date based custom scheduling > Able to enter start time greater than end time in a scenario and publish the activitiy

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3863]
**Steps:**
1. Edit a study
2. Add an anchor date-based custom scheduling
3. Add a row with start time in AM and fill rest of the details
5. Once added change start time AM to PM so it should be greater than end time
6. Observe that user is able to save and publish even though error message is displayed

**Actual:** Able to enter start time greater than end time in a scenario

**Expected:** Once user changes AM to PM and if start time is greater than end time, entered time should be cleared out (Refer regular custom schedule for flow)

- Issue should be handled for questionnaires and active tasks
- Error message is not displayed from 2nd row onwards and above scenario should be handled for all the rows

https://user-images.githubusercontent.com/60386291/124235969-8a988b00-db33-11eb-958c-b5d01ca8214b.mp4

**Comment by Lathan-btc** [comment]
This issue will be tracked in the #3868 issue.
