### ISSUE TITLE
[SB] Anchor date based custom scheduling > Start time is allowing greater value than the end time for the following scenarios and publish the activity

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3868]
**Scenario 1**
**Steps:**
1. Go to Questionnaires/Active task 
2. Schedule tab > select anchor date based and custom schedule
3. Add multiple runs and enter valid inputs  (X and Y values should be the same)
4. Try to change the start time to greater than the end time and observe

**AR:** Start time is allowing greater value than the end time
**ER:** Start time should not be greater than the end time and if the user tries to enter greater time then it should through the proper error message

![sc11](https://user-images.githubusercontent.com/71445210/124466784-98a90e80-ddb4-11eb-9263-2dc993060df9.png)

**Scenario 2**
**Steps:**
1.Go to Questionnaires/Active task 
2. Schedule tab > select anchor date based and custom schedule
3. Add a run and enter valid inputs (Eg: X=1 Start time=2 pm Y=2 and End time=1 pm)
4. Then change the Y to 1 ( X value and Y value should be the same)
5. Observe

**AR:** When the user changes the 'Y' value(4th step), the start time is greater than the end time but the proper error message is not getting displayed and the user is able to publish the activity   
**ER:** Proper error message should be displayed when the start time is greater than nd time

**Note:**
1. Scenario 1 is not observed in regular frequency
2. Scenario 2 is observed in both regular and anchor date based
3. Issue should be fixed in both questionnaires and active task  

**Scenario 3**
**Steps:**
1. Edit a study
2. Add an anchor date-based custom scheduling
3. Add a row with a start time in AM and fill rest of the details
5. Once added change start time AM to PM so it should be greater than the end time
6. Observe that the user is able to save and publish even though an error message is displayed

**Actual:** Able to enter start time greater than end time in a scenario

**Expected:** Once user changes AM to PM and if the start time is greater than end time, entered time should be cleared out (Refer regular custom schedule for flow)

- Issue should be handled for questionnaires and active tasks
- Error message is not displayed from 2nd row onwards and the above scenario should be handled for all the rows

https://user-images.githubusercontent.com/60386291/124235969-8a988b00-db33-11eb-958c-b5d01ca8214b.mp4

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc As mentioned above 
1. Scenario 2 is reproducible for Regular schedule type
2. Scenario 2 for anchor date > When the user changes the Y value then a proper error message should be displayed for the end time and entered time should be cleared out 

![2scenario-anchor](https://user-images.githubusercontent.com/71445210/124703780-847a2400-df10-11eb-93e3-c8b8c7521467.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
