### ISSUE TITLE
[SB] Active tasks > Anchor based daily scheduling > '-ve' value entered in X days displaying in '+ve' value in GetStudyActivityList API

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3871]
Steps:
1. Configure an anchor based daily scheduling
2. Enter '-ve' value for 'X' days value
3. Publish updates
4. Observe the value in API

Actual: '-ve' value entered in X days displaying in '+ve' value in GetStudyActivityList API

Expected: '-ve' value entered in X days should display in '-ve' value in GetStudyActivityList API

Issue not observed for other scheduling
Issue not observed for questionnaires

![SB](https://user-images.githubusercontent.com/60386291/124547801-56caa780-de4a-11eb-8fe1-186ad37b013d.png)

![API](https://user-images.githubusercontent.com/60386291/124547810-5af6c500-de4a-11eb-9329-09d91d89cdcf.png)

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in dev

**Comment by nishit-v** [comment]
Issue is fixed in Dev

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
