### ISSUE TITLE
[SB] Questionnaires/Active > Regular > Custom schedule > End date field > Calendar issue for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3879]
Steps:
1. Create/Edit study
2. Go to the questionnaire
3. Add/edit questionnaire
4. Navigate to the Schedule tab
5. Select Regular and custom schedule
6. Enter the start date other than the current date and enter all the fields 
7. Click on Save/Done button
8. Click on the end date field and observe the calender

AR: In the calendar, it is displaying from the current date
ER: Date should be displayed from whatever date entered in the start date field of the current run

[Note: Issue should be fixed for both questionnaires and active tasks]

![time issue11](https://user-images.githubusercontent.com/71445210/124717065-64ebf700-df22-11eb-8f9a-9c4a85c5d778.png)

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
