### ISSUE TITLE
[PM] Search bar > Customer logo > Responsive issue

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3885]
After searching if a user navigates to any other pages then the customer logo is not getting displayed

![124619706-80a9bb80-de96-11eb-9d65-589c01813ced](https://user-images.githubusercontent.com/60386291/124902301-6d1a6400-e000-11eb-8eaf-2d2e2d623c82.png)

**Comment by Rashi-395** [comment]
[PM] Search bar > Customer logo > Responsive issue #3885 - fixed

**Comment by Lathan-btc** [comment]
@Rashi-395 Issue is reproducible for the Admins and Locations

**Comment by Rashi-395** [comment]
@Lathan-btc [PM] Search bar > Customer logo > Responsive issue #3885 - fixed and tested

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
