### ISSUE TITLE
A project ID is required - study-builder

### ISSUE THREAD

**Issue by usbulat** [GoogleCloudPlatform/fda-mystudies#3890]
Hi!

I'm trying to deploy fda-mystudies on a local machine, but experiencing a problem with study-builder:

```
2021-07-09 11:46:48,159 ERROR [http-nio-8080-exec-9] (AuditEventServiceImpl.java:55) - PASSWORD_HELP_REQUESTED failed with an exception
java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
```
```
2021-07-09 13:24:23,499 ERROR [http-nio-8080-exec-3] (AuditEventServiceImpl.java:55) - NEW_USER_INVITATION_EMAIL_FAILED failed with an exception
java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
```
I get these errors when trying to create new admin, or trying to change a password.
What can I do to make it work?

**Comment by aswinijena100** [comment]
@usbulat we are able to run study builder locally  with release 2.0.7 without any error/exception . Could you please re try with latest release 2.0.7 and do let us know if you still see same error. In case if you see the same error again with latest release , please let us know how you are trying to deploy locally.

**Comment by aswinijena100** [comment]
@usbulat Hope you are able to run the study builder application locally now . Closing this ticket for now , incase you still facing this issue please reopen the same .
