### ISSUE TITLE
[SB] Active task > Schedule tab > Regular > Error message should be displayed for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3894]
**Steps:**
1. Create/edit study
2. Navigate to the active task
3. Create an activity with Regular and any scheduling type
4. Once entered date is expired  click on the edit button of the particular activity
5. Switch to the schedule tab
6. Click on the Done button
7. Observe

**AR:** Error message is not getting displayed 
**ER:** 'Please select a valid date' error message should be displayed for the date field when the entered date is expired and clicks on the done button

Note:
1. Issue is observed only for the active tasks and not observe for questionnaires
2. Issue should be fixed for all the schedule types

![activetask](https://user-images.githubusercontent.com/71445210/125252878-7bc18d80-e316-11eb-9c50-ca20bd88d2f9.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in te latest QA instance.
