### ISSUE TITLE
[SB] Questionnaires/Active task > Schedule tab > Regular > One time > Error message should not be displayed when user enters valid input in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3895]
**Steps:**
1. Create/edit study
2. Navigate to questionnaires
3. Create an activity with a Regular and one-time scheduling option
4. Once entered date is expired  click on the edit button of the particular activity
5. Switch to the schedule tab
6. Click on the Done button
7. Enter the valid date and observe

**AR:** 'Please select a valid date' error message is getting displayed even though the admin enters the valid date
**ER:** Error message should not be displayed when valid data is entered

![onetime](https://user-images.githubusercontent.com/71445210/125255128-bd533800-e318-11eb-98fe-f47dd34e1ca0.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev and update

**Comment by Lathan-btc** [comment]
@chiranjibi009 
1. Issue also be fixed for the onetime > Active task
2. Weekly > for both regular and active task 

![onetime1](https://user-images.githubusercontent.com/71445210/125570406-29108e01-d818-4200-93a3-545c2bb5ec94.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev and update.

**Comment by Lathan-btc** [comment]
@chiranjibi009 Issue is still reproducible when a user enters the current date: it should be fixed for onetime, weekly, questionnaires, and active tasks  


![1time](https://user-images.githubusercontent.com/71445210/125645278-37a56469-ee9e-43b2-aca9-defc196460b9.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in QA and update.

**Comment by Lathan-btc** [comment]
@chiranjibi009 Issue is reproducible for the Active task > Weekly scheduling type 

[Note: Issue is reproducible only in QA instance]

![at12](https://user-images.githubusercontent.com/71445210/126479896-36c9e509-121b-490c-8364-b89aa3fc3732.png)

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in QA and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
