### ISSUE TITLE
[PM] Open study > Enrollment registry > Enrollment target > Text case issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3896]
Open study > Enrollment registry > Click on enrollment target > 'Edit Enrollment Target' should be changed to 'Edit enrollment target'

![et1](https://user-images.githubusercontent.com/71445210/125257237-d65ce880-e31a-11eb-966b-851af2a9e0d1.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA intance.
