### ISSUE TITLE
[SB] Resources > If text for notifying participant about a resource is not entered, blank notification is triggered in mobile apps

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3900]
#2371

**Steps**:
1. Login to SB
2. Navigate to resources
3. Add a resource without entering any text in the resource
4. Save and publish the updates
5. Observe the notification in mobile

A/R: If text for notifying participant about a resource is not entered, blank notification is triggered in mobile apps

E/R: Notification should not be triggered if text for notifying participant about a resource is not entered.

![image](https://user-images.githubusercontent.com/60500517/125327500-cec03280-e360-11eb-8536-e4b0668f2bf5.png)

![image](https://user-images.githubusercontent.com/60500517/125327538-daabf480-e360-11eb-8753-e9df2e96bbf8.png)

**Comment by harisboston** [comment]
@SR-btc 
As per issue E/R: Notification should not be triggered if text for notifying participants about a resource is not entered.

How will the admin come to know why the notification was not triggered if Text is empty?
1) Should we make "Text for notifying participants.." as a mandatory field in study builder?
or
2) Add backend validation to not trigger notification if Text is empty?

**Comment by SR-btc** [comment]
The E/R is (2) , the field is already non-mandatory.

**Comment by harisboston** [comment]
@nagarjunav1 Issue is fixed in dev environment, kindly test and update the ticket.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by harisboston** [comment]
@nagarjunav1 Issue is fixed in QA env., kindly test and close this ticket

**Comment by nagarjunav1** [comment]
Issue fixed in latest QA build
