### ISSUE TITLE
[SB] [Import] Issues related to branching questions for imported study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3902]
Steps:
1. Edit an original study
2. Add some activities with branching enabled
3. Publish updates
4. Export the study
5. Import the study in same/different environment
6. Edit the imported study
7. Observe

Issue 1: UI issue in question step

Issue 2: Values in destination step is not retained in SB and hence in mobile any option provided navigating to destination step

Issue not observed for copied study

Study details:
1. Orginal study - PatientConfiden (Instance - QA)
2. Imported study - p2 (Instance - QA)

![UI](https://user-images.githubusercontent.com/60386291/125407175-416bf500-e3d7-11eb-8de6-24b3a633a3a6.png)

Org study:
![Org](https://user-images.githubusercontent.com/60386291/125407224-4a5cc680-e3d7-11eb-80d9-dfd1d2c3d318.png)

Imported study:
![Imported](https://user-images.githubusercontent.com/60386291/125407250-5183d480-e3d7-11eb-9775-f67f90a1e1b8.png)

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue in dev and update the ticket accordingly.

**Comment by nishit-v** [comment]
1. UI issue is fixed
2. Values in destination step is not retained in SB other than 'Completion step'

Org:
![Org](https://user-images.githubusercontent.com/60386291/125449035-1bdfe3ff-dfe2-4398-8b82-dd192defa68e.png)

Imported:
![Imported](https://user-images.githubusercontent.com/60386291/125449052-b2bf8824-6bbb-40c2-8388-b359d577ddb6.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
