### ISSUE TITLE
Corrections needed in the study metadata API

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3903]
After the study is launched, certain fields like "studyId" and "appId" are never going to change in the next publish updates to the study. So while updating the study in the participant datastore, it's better to exclude such fields from being updated.

And also some fields like "study category" are removed from the study itself, it's better to exclude them from the API as well.

**Comment by navya-BTC** [comment]
@nagarjunav1 please test this issue in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
