### ISSUE TITLE
Ambiguous tokens leading to participants not being able to register

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3904]
Exclude the ambiguous characters from Validation code generation. This is having troubles when retype the code in the field while registering for app access due to ambiguous characters generated by the token generator for the registration email.

**ambiguous characters**
I: capital i
l: small L
0: zero
O: capital o
o: small o

![image](https://user-images.githubusercontent.com/60500517/125441301-6a59cebe-22bc-4d86-9bc0-a45ab319ed95.png)

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm this issue in dev.

**Comment by nagarjunav1** [comment]
Verified for the verification code in the Send and Resend flows and found ambiguous characters are still available in the codes. Below are the some of the verification codes generated.

**sEnt5s**
**Mz1NoB**
**GN07w8**
**nPTQMx**

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in dev.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest Dev build

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in QA.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
