### ISSUE TITLE
Update XCode and iOS version support information

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3908]
Please update the documentation here for XCode and iOS version support information
https://github.com/GoogleCloudPlatform/fda-mystudies/tree/master/iOS

Specifically, the line,
The FDA MyStudies iOS application requires Xcode 11 or newer, and can be run on iOS versions 11 and above.

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
This issue is addressed in PR #3950 
Thank you,
Govind
