### ISSUE TITLE
Display offline indicator for mobile apps

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3910]
The mobile app must show a standard offline indicator when the user is not connected. Actions on the screen that cannot be used in such situations must get disabled (e.g. Sign up, profile updates, enrollment). Sections that support offline capability must continue to be enabled for use. 

Message to be shown on screens that don't have offline capability - You are offline
Message to be shown on screens that have offline capability - You are offline and may be missing out on content updates

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev builds in both ios and android

**Comment by nagarjunav1** [comment]
The feature is implemented and working as expected in the latest QA builds for both ios and android.
