### ISSUE TITLE
[Mobile apps] [Imported study] Comprehension test questions > Order of answer options is incorrect in mobile apps 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3919]
**Steps:**
1. Create a study with comprehension test questions
2. Import the study
3. Launch the study
4. In mobile apps, navigate to the comprehension test questions section 
5. Observe the order of the answer options

**AR:**  Answer options are getting displayed properly in mobile apps
**ER:** Answer options should be displayed in the same order configured in the SB

[**Note:** Issue not observed in Dev. It is observed in QA, RC, and master branch]

**In mobile apps**

![image](https://user-images.githubusercontent.com/71445210/125635680-3487f269-16fd-40d2-8947-b088fedd5e3c.png)

**In SB**

![image](https://user-images.githubusercontent.com/71445210/125635341-97d965c4-e7b0-48b1-9957-6e31c0a6c915.png)

**Comment by nishit-v** [comment]
Order of comprehension test options is incorrect in GetEligibilityConsentMetadata API

![CT](https://user-images.githubusercontent.com/60386291/125637957-ed437438-980e-4cc0-bfcb-172f0c8eabae.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and confirm

**Comment by nishit-v** [comment]
No issues found for order of answer options in dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please check and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
