### ISSUE TITLE
[PM] Admins > Add new admin screen > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3923]
Admins > Add new admin screen > Buttons are not aligned properly

![uiadmin](https://user-images.githubusercontent.com/71445210/125814920-c791e36d-47a7-44be-a965-79f77986392d.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.
