### ISSUE TITLE
[Response Datastore] Remove unused fields

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3928]
Remove unused fields from the response document structure for the responses getting stored in collections within Firestore

**Comment by nagarjunav1** [comment]
Changes made are reflecting now in latest DEV build

Unused fields are removed from Response data store after published updates for the old studies and when launched for the new studies

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
