### ISSUE TITLE
[SB] Questionnaires > Schedule tab > '+' icon is not getting displayed for the daily frequency for the following scenario 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3929]
**Steps:**
1. Edit study
2. Create a questionnaire with Regular and any scheduling option
3. Copy that particular questionnaire
4. Switch to the schedule tab
5. Select the daily scheduling option
6. Enter the same date whatever date is entered in the original questionnaire (eg: if you create a monthly questionnaire with 7/17/2021, then for the copied questionnaire enter the same date for the daily scheduling option) 
7. Observe the '+' icon 

**AR:** '+' icon is not getting displayed, due to this admin is not able to add multiple runs
**ER:** '+' icon should be displayed

![daily11](https://user-images.githubusercontent.com/71445210/125951047-cfff9395-fb9b-48a8-bd01-c57422f5ba9a.png)

**Comment by Lathan-btc** [comment]
@harisboston 
**AR:** '+' icon is getting displayed when admin clicks on time field
**ER:** '+' icon should be displayed when admin enters the time start date

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by harisboston** [comment]
@Lathan-btc issue is fixed in QA environment, kindly test and close this ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
