### ISSUE TITLE
[SB] Questionnaires > Functional issue for the copied questionnaires 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3930]
**Steps:**
1. Edit study
2. Create a questionnaire with Regular and monthly scheduling
3. Copy that particular questionnaire
4. Switch to the schedule tab
5. Change regular to anchor date based
6. Enter all the valid inputs
7. Click on the Save/done button and observe

**AR:** Copied questionnaire is not gatting saved with the latest changes 
**ER:** 
1. The copied questionnaire should be created successfully with the latest changes when the user clicks on the Done
2. Latest changes should be saved when the admin clicks on saving and go back to the main and again admin navigate to the edit questionnaire page of the copied questionnaire   

https://user-images.githubusercontent.com/71445210/125965082-aa1e4b84-3105-49c9-9efe-3edba4151a81.mp4

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in QA, please check and confirm.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
