### ISSUE TITLE
Provision for app-specific deep links

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3932]
Have app-specific deep links configured for redirection to the native app from the auth server based webview screen.  The app's bundle ID could be used for this.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest Android build v1.0(97)

**Comment by nishit-v** [comment]
Issue is fixed in latest iOS build v1.0(243)

**Comment by nishit-v** [comment]
Issue is fixed in latest iOS QA build v1.0(244)

**Comment by aswinijena100** [comment]
@GovindPrasadBostonTechnologyCorporation and @naveenr-btc Please share the QA build to test and close . @nishit-v @nagarjunav1 Please test once received the latest QA build.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest Android build v1.0(100)
