### ISSUE TITLE
[SB] Questionnaires/Active task > Schedule tab > Time picker is not working for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3935]
Steps:
1. Edit study
2. Navigate to the questionnaires/Active task section
3. Navigate to the Schedule tab
4. Select Regular and monthly scheduling type
5. Select any future date in the date field and enter below the current time of the server (eg: if the server time is 5 am then enter below 5 pm) 
6. Change the date to the current date 
7. Click on the time field and try to select the time

AR: Time picker is not working (Time is not getting changed when admin clicks on up and down arrows)
ER: Admin should be able to select time from the time picker

Note: 
1. Issue should be fixed for all the scheduling options
2. Issue should be fixed for both questionnaires and active task

![image](https://user-images.githubusercontent.com/71445210/126289884-99814a87-6561-4922-b9fb-4ae26ddb67cb.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc 
1. Active tsk > Regular > Custom schedule > 'Time reset to current time' inline message is not getting displayed for the time field after changing to current date

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
