### ISSUE TITLE
Attach a prefix to names of newly created studies (via copy, import actions)

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3937]
For a newly created study, generated out of the copy action, the new study should have the name:

{Copy of) <original study name>

For a newly created study, generated out of the Import action, the new study should have the name:

{Imported) <original study name>

Admins can edit the study name subsequently

**Comment by Lathan-btc** [comment]
@Kantharajut-btc Study name field is exceeding more than 50 characters
Steps:
1. Create study/Edit study
2. In the study name field, enter maximum characters and complete the section
3. Copy/import the study
4. Click on the edit button of the newly created study by copying/importing
5. Observe the length of the characters in the study name field

**AR:** It is exceeding maximum characters length
**ER:** It should not exceed the length of the maximum characters

![study name](https://user-images.githubusercontent.com/71445210/126342669-7a48fc8a-1f2e-4d23-8808-87a1bb4cfab0.png)

**Comment by Lathan-btc** [comment]
@Kantharajut-btc @monica-BTC As discussed with the BA team, for the 'Study name' field remove the inline restriction for 50 characters and instead validate it when the admin mark the section as completed in the new study.
Show inline error message below the field - `Study name cannot exceed 50 characters`
The same behavior can apply to original as well as copied/imported study
We can check the char limit of this whenever we do MAC on the section

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
