### ISSUE TITLE
Access of resources for client applications without GCP cloud storage signed URLs

### ISSUE THREAD

**Issue by aswinijena100** [GoogleCloudPlatform/fda-mystudies#3938]
Currently, client applications such as the SB and Mobile apps utilize  gcp cloud storage signed URLs to access resources/documents and images. This should be changed as it may be an issue to use signed URLs-based access to Cloud Storage buckets in some deployments based on organizational policy/ VPN restrictions.

**Comment by madhurya-btc** [comment]
@naveenr-btc @GovindPrasadBostonTechnologyCorporation Changes are implemented in SB, PD and SD.

**Comment by nagarjunav1** [comment]
Feature is Working fine as expected in Android

**Comment by nishit-v** [comment]
Feature is Working fine as expected in iOS Dev build V1.0(245)

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in QA instance

**Comment by nagarjunav1** [comment]
Issue is fixed in Android latest QA build v1.0(102)

**Comment by nishit-v** [comment]
Feature is Working fine as expected in iOS QA build V1.0(246)
