### ISSUE TITLE
Provide ability to copy/export either the draft version or last published version of a study

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3939]
Currently, the copy and export actions in the SB copies or exports a study by using the content from its draft version. However, each study is also associated with a 'last published version'.  At times, it may desired to copy or export that version of the study.  This is specially for situations when a minor change needs to be tested on a study that is already live, without pushing out other updates that are still in progress. 

To meet this requirement, the following will be done:

When the user clicks on Copy or Export , they are asked to choose with a radio button, between 'Draft version' or 'Last Published version'.  The study content utilized for the copy/export action must be picked up accordingly and used to create the replicated study or the exported file.

**Comment by navya-BTC** [comment]
@Lathan-btc please test this enhancement in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by navya-BTC** [comment]
@Lathan-btc  please test this enhancement in QA

**Comment by nishit-v** [comment]
Enhancement has been implemented in the QA instance.
