### ISSUE TITLE
Export action UI issue

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3942]
Place appropriate horizontal gap between the Export button and the 'Copy signed URL' action. Refer to the mockup

![image](https://user-images.githubusercontent.com/63093896/126447982-0d38d294-ba64-4cbb-bc7a-68ab22cf37f8.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
