### ISSUE TITLE
[SB] Delete icon is not working in the assigned permissions section in admin details page 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3951]
Steps:- 
1. Login into SB
2. Navigate to Admins 
3. Add/Edit Admin details 
4. Provide the Admin with Study admin permission
5. Assign some studies to the account 
6. Click on delete icon and verify 

A/R:- Delete icon is not working to delete the studies assigned to the admin
E/R:- Delete icon should be working and able to delete and update the study permissions 

Note:- Issue should be fixed in all the applicable screens 

![image](https://user-images.githubusercontent.com/60500517/127003960-db82bc03-14b0-48a3-87fd-169ad940c505.png)

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in QA.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
