### ISSUE TITLE
[SB] Text correction is required

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3959]
Change the text from `Select and Add Studies` to 'Select and add studies' for the following screens
1. Add admin 
2. Edit admin details

![image](https://user-images.githubusercontent.com/71445210/127270411-fc431f19-6467-4d4a-b7be-f42b477b72c6.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
