### ISSUE TITLE
[Android] Custom Informed Consent PDF loses carriage returns and formatting

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3960]
A/R:- Carriage return and formatting is not saving in generated consent PDF
E/R:- Carriage return and formatting should be same in both PDF generated and consent screens in mobile

Review and E-consent 
![image](https://user-images.githubusercontent.com/60500517/127282130-daa3dc8c-eb64-4832-b53c-74b3a7a51bed.png)

Consent PDF
![image](https://user-images.githubusercontent.com/60500517/127282311-3f86ccdc-642b-440e-9ca9-796efa733051.png)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev.
Android build version: **V1.0(101)**

**Comment by nagarjunav1** [comment]
Issue is fixed in the latest QA build v1.0(104)
