### ISSUE TITLE
[SB] [Copy/Import] Copy/Export and import last published >  Contents of the notification section not getting copied into new study  

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3961]
Steps
1. Create/edit study
2. Add notification and complete all the sections
3. Launch the study
4. Click on edit the study and edit any of the section
5. Click on copy
6. Select 'last published version' to copy
7. click on submit 
8. Click on the new study
9. Observe the contents in the notification section 

AR: The notification section is empty in the new study
ER: Contents should be displayed in the Notifications section

[Note: Issue should be fixed for both Copied and imported studies by using copy/export last published version]

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
