### ISSUE TITLE
[SB]  A popup message is getting displayed in the middle of the Action screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#3963]
Steps:
1.Login into SB.
2.Create/Edit the study.
3.Navigate to Action section.
4.Click on Launch study or publish updates and Observe.

AR: A popup message is displaying in the middle of action screen.
ER: A popup message should be displayed in the top of the action screen.

[Note: Issue should be fixed for all the applicable popups displayed]

![Screenshot_1_n_1](https://user-images.githubusercontent.com/86007179/127286903-c58d6baf-1129-47f5-99aa-edebec1fe656.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by harisboston** [comment]
This issue is reported only in dev environment and is caused by enhancement #3939 (milestone 2.0.8), so changing the milestone of this issue to 2.0.8

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
