### ISSUE TITLE
[SB] [Copy] Study thumbnail image is not retained for copied last published version of the study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3965]
Steps:

1. Create a new study
2. Add all contents and upload a study thumbnail image in the basic info
3. Launch the study
4. Edit the study again remove the thumbnail image 
5. Let study be in draft
6. Copy the last published version of the study. Successfully copied
7. Edit copied study 
8. Click the save /mark as a completed button and observe the thumbnail image

Actual: Study thumbnail image is not retained for copied last published version of the study

Expected: Study thumbnail image should be retained for copied last published version of the study

1. Issue observed for thumbnail image/overview images/images in questionnaires
2. Issue not observed on copying working version of the study
3. Issue not observed for copying active study (without draft)

![image](https://user-images.githubusercontent.com/60386291/127291794-6a9ad68a-6ce4-4fea-8066-507abfd68466.png)

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
