### ISSUE TITLE
[SB] [Import] 'Anchor date based' radio button is disabled for Imported last published version of the study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3966]
Steps:

1. Create new study
2. Add all contents and let 'Use participant enrollment date as anchor date?' be Yes in settings
3. Launch the study
4. Edit the study again and add some contents.
5. Let study be in draft
6. Export the last published version for the study. Import the same and Successfully imported.
7. Edit imported study and observe 'Anchor date based' radio button

Actual: 'Anchor date based' radio button is disabled for Imported last published version of the study

Expected: 'Anchor date based' radio button should be enabled for imported last published version of the study

Issue not observed on exporting working version of the study
Issue not observed for exporting active study (without draft)

**Due to above issue, anchor based activities for imported last published version of the study not showing proper data in GetStudyActivityList and GetStudyActivityMetadata**

**Comment by Kantharajut-btc** [comment]
@nishit-v please test this issue in dev and confirm

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev Instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
