### ISSUE TITLE
[Study datastore] [Copy] Stats and trends are duplicated in GetStudyDashboardInfo for original study on copying last published version

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3967]
**Steps:**

1. Create new study
2. Add all contents and add stats and trends
3. Launch the study
4. Edit the study again and add some contents.
5. Let study be in draft
6. Copy the last published version for the study. Successfully copied
7. Check API response for GetStudyDashboardInfo after step 6

Actual: Stats and trends are duplicated in study datastore for original study on copying last published version

Expected: Stats and trends should not be duplicated

Issue not observed on copying working version of the study
Issue not observed for copying active study (without draft)
Issue not observed for importing last published version

![stats](https://user-images.githubusercontent.com/60386291/127314606-553965a0-98cc-4adb-bb98-6210d0b3290b.png)

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm in dev

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm in QA.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
