### ISSUE TITLE
[SB] Overview section accepting invalid image size

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3972]
Steps:
1. Edit a study
2. Navigate to overview
3. Upload an image of invalid size eg. 104*78 Pixels
4. Error message is displayed.
5. Click on Mark as complete
6. Navigate back to overview and observe

Actual: Overview section accepting invalid image size

Expected: Images having invalid size should not be accepted and saved

Issue not observed for Thumbnail image/Images in questionnaires section

https://user-images.githubusercontent.com/60386291/127615539-2f7bbf7f-f415-400e-95c7-20859fd72c9e.mp4

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in dev and update.

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue in QA and update.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
