### ISSUE TITLE
[SB] [Copy/Export] Unable to copy or export a pre-launch study and getting 500 internal server error

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3973]
**Steps:**
1. Create a study
2. Add some contents. Don't launch the study
3. Navigate to studies list
4. Click on 'Copy'
5. Observe the behaviour

**Actual:** Unable to copy a pre-launch study and getting 500 internal server error

**Expected:** User should be able to copy pre-launch study

1. Issue also observed on exporting the pre-launch study
2. Issue not observed in QA instance
3. Issue not observed for Active studies

Error post copying:
![Screenshot_2](https://user-images.githubusercontent.com/60386291/127618580-1149cdd1-8928-4273-a053-2fa4c4ad3bac.png)

Error post exporting:
![Screenshot_1](https://user-images.githubusercontent.com/60386291/127618441-ace1c8e1-21a1-4974-85e4-b760dd3981e0.png)

**Comment by Kantharajut-btc** [comment]
@nishit-v issue is fixed in dev, please test and confirm.

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
