### ISSUE TITLE
[SB] [Copy last published version] Study activities are getting duplicated for the original study post copying last published version for the study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3974]
**Steps:**

1. Create new study
2. Add all contents and add activities
3. Launch the study
4. Edit the study again and edit basic info section only
5. Let study be in draft
6. Copy the last published version for the study. Successfully copied
7. Check last published version for the study and check API response for `GetStudyActivityList`

**Actual:** Study activities are getting duplicated for the original study post copying last published version for the study

**Expected:** Activities should not be duplicated

**Issue should be handled in SB and Study datastore i.e `GetStudyActivityLis` API**

1. Due to above issue, iOS mobile app is crashing on navigating to study activities list
2. Issue observed for questionnaires and active tasks
2. Issue not observed for exporting last published version

![duplicate](https://user-images.githubusercontent.com/60386291/127619813-8f0005c1-82e5-4f7c-929b-b466e0c6dd10.png)

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm in dev

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by monica-BTC** [comment]
@nishit-v, please test and confirm in QA.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
