### ISSUE TITLE
[SB] Active task > Schedule tab > Custom schedule > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3976]
**Steps:**
1. Edit study
2. Navigate to active tasks
3. Add active task
4. Switch to the schedule tab
5. Select a Custom schedule 
6. Enter all the fields
7. Remove entered data in the end time field and observe

**AR:**
For **Regular**
1. Duplicate error messages are getting displayed for the end time field  
2. End time field is moving a little above vertically

For **Anchordate based**
1. Error message is not getting displayed for both start time and end time fields when admin removes the entered data

Note: Issue observed for Active tasks > Regular and anchor date based

**Regular**
![errmessage](https://user-images.githubusercontent.com/71445210/127648105-f86e1c2f-28c9-4c39-a8fc-2a5c0a955d24.png)

**Anchor date based**

![image](https://user-images.githubusercontent.com/71445210/127675984-fe071cee-65f6-4160-8264-a476dc8139a8.png)

**Comment by harisboston** [comment]
@Lathan-btc issue is not reproducible in dev environment, can you please confirm the steps

**Comment by Lathan-btc** [comment]
@harisboston I have updated the steps, please check.

**Comment by bhoomikav16** [comment]
Issue is fixed in the dev instance

**Comment by harisboston** [comment]
@bhoomikav16 Issue is fixed in QA env., kindly test and close this ticket

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
