### ISSUE TITLE
[SB] Email field is not allowing the Domain name extension with more than 3 characters

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#3982]
A/R:- Email field not allowing the Email with domain name extension with more than 3 characters Eg. Sample@mail.tech
E/R - Email field should allow Domain name extension with min 2 and max 24 characters

Note:- Issue should be handled across study builder wherever applicable 

![image](https://user-images.githubusercontent.com/60500517/127863677-3832f1ae-517a-49eb-8424-6423082b86e6.png)

**Comment by madhurya-btc** [comment]
The longest TLD  (Top level domain) currently in existence is 24 characters long. [Latest list of actual existing TLDs](http://data.iana.org/TLD/tlds-alpha-by-domain.txt)

**Comment by madhurya-btc** [comment]
@nagarjunav1 please test and confirm in dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test in QA and close if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
