### ISSUE TITLE
[SB] [Copy/import] Questionnaires > Edit questionnaire > Latest updated title for the questionnaire is not getting retained in the new studies

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3985]
Steps:
1. Login to SB 
2. Create a study
3. Add questionnaires and complete all te sections
4. Launch the study
5. Edit study
6. Edit the Title of the questionnaires
7. Publish the updates
8. Click on edit study again and edit any section and let it be in the draft
9. Copy/export and import the Last published version of the study 
10. Observe the title of the questionnaires

AR: Updated title for the questionnaires is not getting retained
ER: For the new studies, all the contents should be retained as it is whatever is present in the last published version of the original study

Note: Issue observe only when admin copies/imports the last published version of the study

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
