### ISSUE TITLE
[SB] Study is not getting moved to draft when admin deletes the active tasks

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3986]
**Steps:**
1. Create a study 
2. Add active tasks and complete all the sections
3. Launch the study
4. Click on edit study
5. Navigate to active tasks 
6. Delete the active tasks and don't click on mark as a completed button
7. Navigate to the studies list screen
8. Observe the study 

**AR:** Study is not getting moved to draft state
**ER:** Study should be moved to draft state if user edit any sections

Note: Issue is observed when an admin deletes the contents in the following screens  
1. Eligibility > Eligibility test questions
2. Consent section > Consents
3. Comprehension test questions  
4. Active tasks
5. Resources

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please test this issue in QA and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
