### ISSUE TITLE
[SB] Resources > Blue tick mark is not getting removed on the side menu bar for the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3987]
Steps
1. Create/edit study
2. Navigate to resources 
3. Add resources and mark the section as completed
4. Delete the added resources
5. And observe the blue tick mark on the side menu bar for resources 

AR: Tick mark is not getting removed when an admin deletes the resources
ER: Tick mark should get removed for the particular section when admin does some changes 

![rsrc2](https://user-images.githubusercontent.com/71445210/127985176-ecf9da74-9207-4244-aa72-97437ce6b0a6.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
