### ISSUE TITLE
[SB] [Copy] App ID is getting retained in caps for the new studies   

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3997]
Steps
1. Create a study
2. Enter the app in small letters
3. Complete the sections
4. Copy the particular study 
5. Observe

AR: Data in the app id field is getting retained in the caps for the copied studies  
ER: App id should be retained in the same text case whatever is present in the original study

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance
