### ISSUE TITLE
[PM] Exclude ambiguous characters from Enrollment token generation

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4002]
Exclude the ambiguous characters from enrollment token generation. This is having troubles when retype the code in the field while Enrolling for token based studies.

ambiguous characters
I: capital i
l: small L
0: zero
O: capital o
o: small o

![image](https://user-images.githubusercontent.com/60500517/128695473-705dc7dd-95d5-47aa-8705-d4a10dc55ef0.png)

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in QA.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
