### ISSUE TITLE
[SB] Deployment version is not getting updated automatically 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4008]
AR: Deployment version is not getting updated to 2.0.7 automatically after 2.0.7 release
ER: Deployment version should be updated automatically after each deployment

[Note: Issue should be handled in all the screens across the Study builder]

![version21](https://user-images.githubusercontent.com/71445210/128977392-a562587c-b693-4afa-9b47-56e21e77adca.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA and RC2.0.7 environment
