### ISSUE TITLE
[SB] Active task custom scheduling > Order of runs is incorrect in GetStudyActivityList API in a scenario

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4012]
Steps:
1. Configure active task custom schedule in SB
2. First run -> let start time be past of admin's device time and end time be future time
3. 2nd and 3rd run - let runs be in future time
4. Publish updates
5. Observe the `GetStudyActivityList` API 

Actual: Order of runs is incorrect

Expected: Order of runs should be in ascending order of runs

Issue not observed for questionnaires for same set of runs
Issue not observed when runs are in future

![SB](https://user-images.githubusercontent.com/60386291/128997423-8f6a03d7-1abd-4418-9b37-5cc67b3fc000.png)

![Screenshot_1](https://user-images.githubusercontent.com/60386291/128997443-979f050b-fbf6-4e8e-aa3d-9029a5095a06.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by harisboston** [comment]
@nishit-v Issue is deployed in QA env, kindly test and close this ticket

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
