### ISSUE TITLE
[SB] [Import] ')' is missing in the error message pop-up

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4013]
Actual: Refer screenshot

Expected: Import failed. Studies can only be imported from compatible Study Builder applications (running a platform release version of 2.0.6 or higher, and lower than or equal to the destination platform version which is 2.0.6).

![129001695-8b84788d-a56c-48f1-b374-b733ca6bcfd3](https://user-images.githubusercontent.com/60386291/129006538-6b4ec99c-88cb-4a72-9682-3bbabc6f30ec.png)

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please test and confirm.

**Comment by nishit-v** [comment]
Unable to test this scenario in Dev instance as there is no instance higher than 2.0.7 to Export.

**Comment by Kantharajut-btc** [comment]
@nishit-v I have merged PR for this fix, please close this issue.
