### ISSUE TITLE
[SB] [Copy/Import last published version] Questionnaires are getting duplicated for imported study in a scenario

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4024]
**Steps:**
1. Create a study and add 1 or more questionnaires
2. Fill rest of the details and launch the study
3. Edit study again and let study be draft
4. Copy last published version
5. Launch the copied study
6. Export last published version for the original study
7. Import
8. Edit the imported study
9. Observe questionnaires is duplicated

**Actual:** Questionnaires are getting duplicated for imported study

**Expected:** Should not be duplicated

1. Issue not obserevd directly for imported study i.e skipping step 4 and 5
2. Issue not observed for copied study
3. Issue not observed for active tasks

![Screenshot_1](https://user-images.githubusercontent.com/60386291/129357454-4cad466f-fc97-41ee-815f-ff5be77f22c6.png)

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in dev

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.
