### ISSUE TITLE
[SB] [Copy/Import last published version] Contents are not getting retained in Consent section for the following scenario 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4026]
Steps:

1. Create a study.
2. Add Comprehension test and E-Consent section
3. Complete all the sections
4. Launch the study
5. Edit the study and add some contents
6. Publish the updates
7. Edit the study again and add some contents
8. Let the study be in draft
9. Copy the last published version of the study. Successfully copied
10. Edit copied study and Observe the contents in the consent section

AR: Contents in the consent section are not getting retained in the new study
ER: Contents in the consent section should be retained as it is present in the last published version of the study

Note: Issue is obseved for both copy and import last published version of the study

**Comment by navya-BTC** [comment]
@bhoomikav16 please test this issue in dev

**Comment by bhoomikav16** [comment]
@navya-BTC Issue is still reproduciable in the latest dev instance

**Comment by navya-BTC** [comment]
@bhoomikav16  please test this issue in dev

**Comment by bhoomikav16** [comment]
@navya-BTC  Issue is still reproduciable for imported studies

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
