### ISSUE TITLE
[SB] Admin is getting navigated to studies list screen when admin clicks on the 'Actions' section or the following copied studies

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4028]
**Steps**
1. Click on edit study
2. Navigate to the 'Actions' section
3. Observe

**Study 1**
**Study id**: cDup003d 
**Study name**: Copy of cDup003 

**Study 2**
**Study id**: copied-LPV 
**Study name**: Copy of Original new study (Open study)

**AR:** Admin is getting navigated to the 'Studies list' screen
**ER:** Admin should be navigated to the 'Actions' screen

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and confirm

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
