### ISSUE TITLE
[SB] Custom schedule > Issues related to editable fields for studies when viewed from last published version

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4035]
Steps:
1. Edit a study
2. Add custom schedule activities
3. Publish updates
4. View study from last published version
5. Navigate to schedule tab of custom schedule
6. Observe 

Below fields are editable when viewed from last published version

1. Questionnaires > Regular custom schedule - **Start time, End time and Delete icons are editable**
2. Questionnaires > Anchor based custom schedule - **Delete icons are editable**
3. Active tasks > Regular custom schedule - **Start time and End time is editable**

Expected: All fields should be non-editable and hand cursor icon should be disabled when mouse hovered

![SB](https://user-images.githubusercontent.com/60386291/130020227-a07dc6fc-a799-40f2-b128-14a3a75f17cc.png)

**Comment by navya-BTC** [comment]
@nishit-v please test this issue in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
