### ISSUE TITLE
[PM] Alignment is not proper in My account screen

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4039]
A/R:- Alignment is not proper for **Update** and **Cancel** buttons
E/R:- Alignment should be proper for all the elements on the screen 

![image](https://user-images.githubusercontent.com/60500517/130240565-633dcb67-f0b4-4013-89bf-fcb1c832402c.png)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test in QA and close if fixed.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
