### ISSUE TITLE
Software release version to display v in front of the release version number

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#4048]
Currently, the study builder is displaying the version release number ex: 2.0.7. a version v needs to be appended in front of this release number to represent the version of release ex: v2.0.7. 

Note: it is a small v with no space to the release number

![image](https://user-images.githubusercontent.com/63578379/130811356-b4989665-b429-4766-9a58-6c065f44486f.png)

**Comment by nagarjunav1** [comment]
Feature is implemented in DEV and changes are reflected as expected.

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 please test this issue in QA and update the ticket accordingly.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
