### ISSUE TITLE
[Notifications] Notifications are not displayed in the notifications list in particular scenario

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4050]
Steps:- 
1. Login into SB
2. Navigate to notifications section and Resend the existing notifications
3. Verify the notification list in mobile once received the push notification

A/R:- Push notifications sent to mobile are not displaying in the notification list when Resent the Old notifications
E/R:- Push notifications sent to mobile should display in even it is sent for 1st time, Resent or Copy and Sent

Refer #3855 

Note:- 
**1. Issue observed only in QA env**
2. Issue observed for both Android and iOS
3. Issue should be fixed for both study and App level

![image](https://user-images.githubusercontent.com/60500517/130983166-7324bf9f-4249-4e16-b79a-c07eb0d0bf02.png)

![image](https://user-images.githubusercontent.com/60500517/130983287-3a2a22b1-2b48-4def-9389-735491f4ab8a.png)

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed in QA, please test and confirm.

**Comment by nagarjunav1** [comment]
Issue is still not fixed in latest QA build. Still not displaying notification in the list

![image](https://user-images.githubusercontent.com/60500517/131514146-8f915bcb-d5e7-4189-bd05-d00a0edf1d2a.png)

![image](https://user-images.githubusercontent.com/60500517/131514299-1b538b96-dfd0-45fa-b8d6-da5c6bc8f903.png)

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed in QA, please check and confirm

**Comment by nagarjunav1** [comment]
Main issue is fixed now for this ticket and Resend notifications are working fine now in notification list. Any other notification issues found will be tracked separately.

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 I have merged PR for this issue, please close the ticket.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
