### ISSUE TITLE
[SB] [UI] Questionnaires > Image choice > Length of the text fields should be the same in both Question step and Form step

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4054]
**Steps:**
1. Click on edit study
2. Go to questionnaires
3. Click on Add/edit questionnaire
4. Click on Question step and/or form step
5. Select image choice response type
6. Switch to Response level attributes tab
7. Observe the field length

**AR:** Field length of the text fields is different in both the Question step and Form step
**ER:** Field length of the text fields should be the same in both the Question step and Form step

**Question step**

![QS](https://user-images.githubusercontent.com/71445210/131125296-6d7dfe8f-772c-4fbc-8f0e-853876919410.png)

**Form step**

![FS](https://user-images.githubusercontent.com/71445210/131125326-ba0455f6-32f2-4ea4-81d2-9ae433788ded.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
