### ISSUE TITLE
[SB] Questionnaires > Instruction step > Validation message is getting displayed for the 'Instruction text' field for the following scenario 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4055]
Steps:

1. Click on edit study.
2. Navigate to questionnaires.
3. Add/Edit the questionnaire.
4. Click on add instruction step.
5. Enter the value only for step short title or key field.
6. Click on done button.
7. Then click on save button and Observe.

AR: Validation message is getting displayed for the 'Instruction text' field
ER: Validation message should not be displayed for the 'Instruction text' field

![INSTRUCTIONSTEP](https://user-images.githubusercontent.com/86007179/131126594-5eeef0d6-6c91-48c4-9d4e-7f1ccf0f7c21.png)

**Comment by monica-BTC** [comment]
@bhoomikav16, please test and confirm in dev

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
