### ISSUE TITLE
[PM] My account tab > Text change is required

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4056]
Change the from **`My Account`** to **`My account`** 

![MA1](https://user-images.githubusercontent.com/71445210/131129895-a467a5f8-ac7a-48e8-a5cc-0bf752f32b55.png)

**Comment by Rashi-395** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Rashi-395** [comment]
@Lathan-btc Please test in QA environment

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
