### ISSUE TITLE
[SB] Choose Spatial span memory from active task dropdown > After selecting activity observe the text displayed below the dropdown.

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4060]
**Steps:**

1. Login to SB.
2. Edit the study which support IOS platform.
3. Navigate to Active task section.
4. Click on add active task button.
5. Choose spatial span memory active task from dropdown.
6. Observe the text below the dropdown and Verify. 

**AR**:Character P is displayed below the text.
**ER**:Character P should not be displayed below the text.

**Note:** Issue is observed in QA instance

![Untitled22](https://user-images.githubusercontent.com/86007179/131527088-2a32714e-bf12-4173-a1d1-5be003b22913.png)

**Comment by Kantharajut-btc** [comment]
@bhoomikav16 please test this issue in QA and update the ticket accordingly.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
