### ISSUE TITLE
To remove Terms and privacy policy in Auth server log in for Mobile

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#4062]
To remove the Terms and Privacy policy in the Sign-in screen footer in mobile-only(for iOS and Android).

The footer page of the sign-in page currently displays Copyright text, terms, and Privacy policy. We need to remove the Terms and Privacy policy and keep only Copyright text displayed for Mobile
 
thanks,
Sharath

**Comment by harisboston** [comment]
@nishit issue is fixed in dev environment

**Comment by nishit-v** [comment]
Feature is implemented in latest Dev instance.

![aa](https://user-images.githubusercontent.com/60386291/131990180-74134d2c-2ab6-4201-8f54-bb3215f35120.png)

**Comment by harisboston** [comment]
@nishit-v issue is fixed in QA environment, kindly test and close this ticket.

**Comment by nishit-v** [comment]
Feature is implemented in latest QA instance.
