### ISSUE TITLE
Terms and Privacy policy page to be displayed in app resource in Gateway app

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#4063]
The Terms, Privacy policy needs to be displayed under the cheeseburger menu>resource>app glossary for the Gateway app

**Comment by nishit-v** [comment]
Feature is implemented in iOS Dev build V1.0.273. 

One correction needs to be changed in Resources section. 'Terms of use' should be changed to 'Terms'

![Image_20210902_110304](https://user-images.githubusercontent.com/60386291/131788105-db401ad4-728a-4750-b1a7-e0e6cc6d843f.png)

**Comment by nishit-v** [comment]
Above issue is fixed in the latest iOS dev gateway app V1.0 (275)

**Comment by nagarjunav1** [comment]
Feature is implemented in Android Dev build V1.0.111 and it is working as expected

**Comment by nagarjunav1** [comment]
![image](https://user-images.githubusercontent.com/60500517/132537443-c64e490f-cde9-40d5-80d3-991c6581e825.png)

Update the screen header text to **TERMS**

**Comment by nagarjunav1** [comment]
Above issue is fixed now in latest Android build 1.0(114)

**Comment by nagarjunav1** [comment]
Feature is implemented in Android QA build v1.0(121) and it is working as expected

**Comment by nishit-v** [comment]
Feature is implemented in iOS QA build v10(29) and it is working as expected
