### ISSUE TITLE
Terms and Privacy policy page to be displayed above "Leave study' in resource page of the Standalone app

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#4064]
To display Terms, Privacy policy above leave study in the resource page of the standalone app.

**Comment by nishit-v** [comment]
Above issue is fixed in the latest iOS dev standalone app V1.0 (276)

**Comment by nagarjunav1** [comment]
Feature is implemented in Android Dev standalone build v1.0.109 and it is working as expected

**Comment by nagarjunav1** [comment]
Feature is implemented in Android QA standalone build v1.0(122) and it is working as expected

**Comment by nishit-v** [comment]
Feature is implemented in iOS QA standalone build v10(30) and it is working as expected
