### ISSUE TITLE
[SB] [UI Issue] Questionnaires > Text Scale > Observe the asterisk symbol (*) beside display text field in response-level attributes screen 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4068]
**Steps:**

1. Edit the study.
2. Navigate to Questionnaires section.
3. Click on Add/Edit Questionnaires.
4. Click on add question step.
5. Select response type as Text Scale.
6. Navigate to response-level attributes screen.
7. Observe the asterisk symbol beside display text field and Verify.

**AR:**  Asterisk symbol is not alligned properly.
**ER:**  Asterisk symbol should be alligned properly.

**Note:** Issue is observed only for question step.

![Untitled4444](https://user-images.githubusercontent.com/86007179/131840247-59a86b3f-aad1-44ed-a37a-0c14287e2564.png)

**Comment by Kantharajut-btc** [comment]
@bhoomikav16 this issue is fixed in dev, please check and confirm.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by Kantharajut-btc** [comment]
@bhoomikav16 this issue is fixed in QA, please test and confirm.

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance
