### ISSUE TITLE
[SB] [Manage apps] App information screen > 'App name' field is accepting more than 15 characters

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4073]
AR: 'App name' field is getting exceeded the 15 characters
ER: 'App name' field should accept a maximum of 15 characters

![AN1](https://user-images.githubusercontent.com/71445210/132173534-1a9aeb64-64c7-495e-9ff4-3bbc183e1356.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
