### ISSUE TITLE
[SB] [Manage apps] App list screen > App is not getting displayed in the draft

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4074]
Steps
1. Click on Create  app
2. Enter the required data 
3. Click on Save/Mark as completed and observe

AR: App is not getting displayed in the draft
ER: App should be displayed in the draft (blue dot on the edit icon should be displayed)

![image](https://user-images.githubusercontent.com/71445210/132174718-68126273-69c3-4117-a607-06ce2e426631.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance
