### ISSUE TITLE
[SB] Password authentication > Validation message is incorrectly displayed on choosing 4 unique characters for new password

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4075]
Steps:
1. Create an admin in SB
2. Let initital password be `Qwerty@1`
3. Do actions like Change password or Password expiry flows
4. Enter new password so that there are at least 4 unique characters from previous password. Eg. `Qweruz$2`
5. Submit and observe the validation message

**Actual:** Validation message is incorrectly displayed on choosing 4 unique characters for new password i.e `uz$2` characters are unique

**Expected:** Validation message should not be displayed and new password should be accepted if there are at least 4 unique characters between old and new password

1. Issue not observed if there are <4 unique characters i.e validation message is displayed
2. Issue not observed if there are >4 unique chatacters i.e accepting the new password 
3. Issue should be handled for Change password and Password expiry flows

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in  dev instance

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by aswinijena100** [comment]
@nishit-v Please test this issue in QA and close if fixed

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
