### ISSUE TITLE
[SB] [Manage apps] UI > Apps list screen > 'Create New' button label should be changed to 'Create new'

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4076]
App list screen > 'Create New' button label should be changed to 'Create new'

![image](https://user-images.githubusercontent.com/71445210/132211226-572fc6ab-6f86-4fc8-bc75-a7cdb3f59a7e.png)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
