### ISSUE TITLE
[SB] [Manage Apps] App list screen > Type column

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4079]
Apps list screen > Type column

AR: In Type column, App type is displaying as GT for gateway and SD for standalone apps.
ER: In Type column, App type should be dispalyed as Gateway for gateway apps and Standalone for standalone apps.

 
![Untitled1111111111111111](https://user-images.githubusercontent.com/86007179/132213731-0104bf17-2e05-43db-9768-2a78c5033e04.png)

**Comment by navya-BTC** [comment]
@bhoomikav16 please test this issue in dev

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
