### ISSUE TITLE
[SB] [Manage Apps] Spelling mistakes in Action screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4080]
Steps:
1. Edit the app.
2. Navigate to Action section.
3. Observe the text below the Mark iOS app as distributed button and Mark Android app as distributed button.

AR: Distributed spelling is displaying as 'distrbuted' for both Mark iOS app as distributed and Mark Android app as distributed for on-screen text under the buttons.
ER: Distributed spelling should be displayed as 'distributed' for both Mark iOS app as distributed and Mark Android app as distributed for on-screen text under the buttons.

![Untitled5444444444](https://user-images.githubusercontent.com/86007179/132215955-fcccc333-05fa-438d-a467-42994d0755b5.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
@madhurya-btc  Issue is reproducing in both dev and qa instance.

![Untitledqwe1](https://user-images.githubusercontent.com/86007179/136013754-5b29e0db-0e84-43cb-bac6-f8a4fdf0cce4.png)

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in dev instance

**Comment by bhoomikav16** [comment]
@madhurya-btc  Issue is fixed in the latest dev instance.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance
