### ISSUE TITLE
[SB] [Manage apps] Edit app details screen > App status > Use the proper text case 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4081]
**Steps:**
1. Login to SB
2. Click on Manage apps
3. Create a new or Click on edit app 
4. Observe the Status's of the app on the side menu bar

**ER:**
Use the proper text case for the different statuses of the app
1. 'Not Published' should be changed to 'Not published'
2. 'Not Distributed' should be changed to 'Not distributed'

![image](https://user-images.githubusercontent.com/71445210/132217153-5497396c-eef3-493b-8b85-4cd5a9fbad11.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
