### ISSUE TITLE
[SB] [Manage Apps] Clicking on 'Mark as completed' in App settings page should navigate to App Properties page post creating an app

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4083]
**Steps:**
1. Login to SB
2. Create an app successfully
3. Edit the app
4. Click on 'Mark as complete' in App settings page
5. Observe the navigation

**Actual:** Navigating to Actions page

**Expected:** Clicking on 'Mark as completed' in App settings page should navigate to App Properties page post creating an app.

**Note:** Before creating an app, clicking on 'Mark as completed' in app settings page navigating to Actions which is expected behavior

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please check and confirm.

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by aswinijena100** [comment]
@nishit-v  Please test in QA and close if fixed

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
