### ISSUE TITLE
[SB] [Manage apps] Welcome screen > 'Manage apps' icon should be disabled when admin doesn't have permission to Manage apps

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4084]
Steps:
1. Login to SB
2. Add study admin and assign permission only to the manage studies
3. Create an account for the new account and login to SB
4. Observe the 'Manage apps' icon on the Welcome screen

AR: 'Manage apps' button is enabled even though the admin doesn't have permission to Manage apps
ER: 'Manage apps' icon should be disabled on the welcome screen

[Note:  Apps tab should not be displayed on the top bar]

![image](https://user-images.githubusercontent.com/71445210/132302683-e3371dfe-8c6e-41ae-ae79-7ace74e5b26d.png)

**Comment by navya-BTC** [comment]
@Lathan-btc please test this issue in dev

**Comment by Lathan-btc** [comment]
This issue will be tracked in #4107.
