### ISSUE TITLE
[SB] [Manage apps] Studies list screen > 'Select app' filter dropdown > Number of selected apps are not getting displayed in the dropdown

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4085]
Steps:
1. Login to SB
2. Click on Manage apps
3. Click on 'View associated studies' action of the app (Studies should be associated with that particular app)
4. After navigating to the 'Studies list' screen, observe the 'Select app' filter dropdown

AR: The number of selected apps is not getting displayed in the 'Select apps' filter dropdown
ER: The number of selected apps should be displayed 

Note: For the above scenario '(1) Selected' should be displayed on the filter dropdown

![image](https://user-images.githubusercontent.com/71445210/132309009-30ee8c90-0b0e-4396-bf28-105079c5da01.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
