### ISSUE TITLE
[SB] [Manage Apps] Developer Configuration > Latest app build version (for iOS app) and Latest app version code (for Android app)

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4087]
**Steps:**

1. Edit the app.
2. Navigate to Developer Configuration section.
3. Click on Latest app build version (for iOS app) field.
4. Validate the Latest app build version (for iOS app) field and Verify.

**AR:** Latest app build version (for iOS app) field is accepting negative intergers.
**ER:** Latest app build version (for iOS app) field should not accept negative integers.

**Note:** Issue needs to be fixed for both Latest app build version (for iOS app) field and Latest app version code (for Android app).

![Untitled888](https://user-images.githubusercontent.com/86007179/132326179-388dc917-7a67-4aa8-a51a-9d99ce25e83b.png)

**Comment by monica-BTC** [comment]
@bhoomikav16, please test and confirm in dev.

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest dev instance.

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
