### ISSUE TITLE
[SB] [Manage Apps] Developer Configuration > Latest app build version (for iOS app) and Latest app version code (for Android app) text validation

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4088]
**Steps:** 

1. Open the firefox browser.
2. Enter SB URL.
3. Login with valid credentials.
4. Click on manage apps icon.
5. Edit the app.
6. Navigate to Developer Configuration section.
7. Click on Latest app build version (for iOS app) field.
8. Enter invalid input and validate the Latest app build version (for iOS app) field and Verify.

**AR:** 1. Able to enter characters ( like A,a,!~) in the field.
            2. Wrong validation message is displaying.

**ER:** 1. Should allow only intergers to enter in the field.
            2. A proper validation message should be displayed.

Note: Issue needs to be fixed for both Latest app build version (for iOS app) and Latest app version code (for Android app) fields. 

![Untitled9999999987](https://user-images.githubusercontent.com/86007179/132330454-03273a16-db13-41c6-81ba-8ff03ad12e45.png)

**Comment by monica-BTC** [comment]
@bhoomikav16, please test and confirm in dev

**Comment by bhoomikav16** [comment]
The issue is fixed in the lateset dev instance.

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
