### ISSUE TITLE
[SB] [Manage apps] Edit app details > 'Blue tick mark' is getting displayed for the 'Actions' section on the side menu bar

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4089]
Steps:
1. Login to SB
2. Click on Manage apps
3. Create an app
4. Click on the edit button of the app
5. Observe the 'Actions' section on the side menu bar

AR: Blue tick mark is getting displayed for the Actions tab
ER: Blue tick mark should not be displayed for the 'Actions' section present on the side menu bar

![image](https://user-images.githubusercontent.com/71445210/132332035-8732c792-594d-4c3e-9efb-d174de048f3f.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test in QA and close if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
