### ISSUE TITLE
[SB] [Manage Apps] Action screen > Mark iOS app as distributed > Mark Android app as distributed > Success message is not getting displayed.

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4091]
**Steps:**

1. Edit the App.
2. Complete all the sections.
3. Navigate to Action screen.
4. Click on Mark iOS app as distributed button.
5. Click on OK and Observe the screen.

**AR:**  Success message is not displayed.
**ER:**  Success message should be displayed.

**Note:**  Issue is observed also when click on Mark Android app as distributed button in Action screen.

**Comment by navya-BTC** [comment]
@bhoomikav16 please test this issue in dev

**Comment by aswinijena100** [comment]
@bhoomikav16  Please test in QA and close if fixed

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
