### ISSUE TITLE
[SB] [Manage Apps] App list screen > View > Edit icons in the App list screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4092]
**Steps:**

1. Click on manage app icon.
2. Navigate to second page in app list screen.
3. Click on view icon in the action column and Verify.

**AR:**  View icon is disabled.
**ER:**   View icon should not be disabled.

**Note:** Issue needs to be fixed for edit icon and also for view associated studies(n) in action column.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev istance

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
