### ISSUE TITLE
[SB] [Manage apps] Edit app > Actions section > 'Deactivate app' button is disabled in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4093]
Steps:
1. Login to SB
2. Click on Manage apps
3. Create an app
4. Create a study for the app
5. Deactivate the created study
6. Then go to the apps section
7. Click on the Edit button of the particular app
8. Go to the Actions section
9. Observe the 'Deactivate app' button

AR: 'Deactivate app' action button is disabled
ER: 'Deactivate app' button should be disabled once all the associated studies are deactivated for that particular app

![image](https://user-images.githubusercontent.com/71445210/132342629-3d0cbe83-05bd-4f0d-9106-f2653749399f.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc  Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
