### ISSUE TITLE
[SB] [Manage apps] Edit study > Study information screen > 'Select app' dropdown field > Selected app name is not getting displayed when admin doesn't have permission to apps/if user have only view permission

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4095]
Steps:
1. Login to SB
2. Add an admin with edit permission for the prelaunch study (Don't provide the permission for the Manage apps)
3. Create a new user account and login to SB
4. Click on edit study 
5. In the Study information screen
6. Observe the value of the 'Select app' dropdown and 'App type' field 

AR: Selected app and app type  is not getting displayed on the 'App name' dropdown field and 'App type' field
ER: Selected 'App name' and 'App type' should be displayed 

[Note: 
1. The issue should be handled when the admin has only view permission for the app and no permission for the Manage apps
2. The issue should be handled for both View and view and edit study

![image](https://user-images.githubusercontent.com/71445210/132375632-52978072-4228-4500-ad05-aa653990dead.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
