### ISSUE TITLE
[SB] [Manage] apps] Add admin details screen > Study admin role > Assigned permission section > Admin is able to select 'Create new apps/studies' checkbox

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4097]
**Steps:**
1. Login as Superadmin to SB
2. Click on admins
3. Click on add admin
4. Select study admin from the 'Role' dropdown
5. Go to the Assigned permission section
6. Try to select 'Create new app'/Create new studies' without selecting 'Manage apps'/Manage studies' checkbox

**AR:** Admin is able to select 'Create new apps'/Create new studies' checkbox
**ER:** Admin should not be able to select 'Create new apps'/Create new studies' checkbox until admin selects the 'Manage apps/studies' check box

![image](https://user-images.githubusercontent.com/71445210/132464417-7de3161b-d8c0-4c98-a80a-51316cb37008.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test in QA and close if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
