### ISSUE TITLE
[SB] [Manage apps] Studies list screen > All the assigned studies are getting displayed when admin clicks on 'View associated studies' icon in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4098]
Steps:
1. log in to SB
2. Click on Manage apps
3. Create a new app
4. Create a study for the newly created app in step3
5. Deactivate a study
6. Then deactivate that particular app
7. In the app list screen, click on 'View associated studies' 
8. Observe the studies list screen

AR: All the studies present in SB are getting displayed
ER: Empty studies list should be displayed and if admin on the 'Show deactivated' studies toggle button then the studies should be shown

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
