### ISSUE TITLE
[SB] Add admin screen > Study admin > Permission section > Already selected apps/studies are getting displayed in the 'Select and add apps/studies' dropdown in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4099]
Steps:
1. Login to SB
2. Click on Admins
3. Click on Create new admin and select study admin
4. Go to the Assigned permission section
5. Select Manages apps checkbox
6. Select and add some of the Apps from the dropdown
7. Then deselect the 'Manage apps' checkbox
8. Again select the 'Manage apps' checkbox 
9. Click on the 'Select and add apps' dropdown and observe the values

AR: Already selected values are getting displayed and admin is able to select the values and add
ER: Selected values should not be displayed

![img1ma](https://user-images.githubusercontent.com/71445210/132474513-bc311c12-f2b2-473b-959f-09886c06c6a0.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
