### ISSUE TITLE
[Manage Apps] Mobile app emails > Contact Us email is displayed for app support email address in emails

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4101]
Steps:
1. Login to SB
2. Configure an app support email in Manage apps section
3. Publish the same
4. Perform account related actions like signup/forgot password/account lock in mobile
5. Observe the app support email address in the emails triggered

Actual: Contact Us email is displayed for app support email address in emails

Expected: app support email address should be shown in emails

Email: 
![Screenshot_1](https://user-images.githubusercontent.com/60386291/132502496-07f9ed64-39a4-4638-98f8-0665cd4e31fa.png)

SB: 
![Screenshot_2](https://user-images.githubusercontent.com/60386291/132502445-22a8c1df-a806-4ce7-8389-538b4d73592f.png)

**Comment by nagarjunav1** [comment]
Issue is fixed now for Dev Android build v1.0(116)

**Comment by nishit-v** [comment]
Issue is fixed now for Dev iOS build v10(18)

**Comment by aswinijena100** [comment]
@nishit-v Please test in QA once you get latest mobile build and close if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed now for QA Android build v1.0(122)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V10(29)
