### ISSUE TITLE
[PM][manage apps] Participant invitation > Email template issue

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4102]
**AR:**  Participant invitation email > UI breakage in the Email template.
**ER:**  Participant invitation email should be according to the Email template. 

![Screenshot (209)](https://user-images.githubusercontent.com/86007179/132504193-fac49ae8-33f6-481c-9fd0-d186f184be1b.png)

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in dev instance

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest dev instance.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
