### ISSUE TITLE
[Manage apps] App Properties > Emails are not triggered from sender email configured in SB

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4104]
Steps:
1. Edit an app
2. Configure valid email address for field `'From' email for outgoing app emails'`
3. Publish app
4. Perform account related actions like signup/forgot password/account lock in mobile
5. Observe the sender emails triggered

Actual: Emails are not triggered from sender email configured in SB

Expected: Email ID configured for field `'From' email for outgoing app emails'` should be set as sender email

**Comment by harisboston** [comment]
@nishit-v 
As we are using gmail to send mails, Google won't allow us to send mail from different "from address"
So it will override Sender with the account we authorized with.

Workaround:
To use a gmail account with changed "setFrom" to another email address we have to add a new address to your gmail account.
Instruction is here: https://support.google.com/mail/answer/22370?hl=en

Only those lists of "from addresses"(authorized emails) can be used while creating an app in Study Builder.

**Comment by nishit-v** [comment]
Verified 'from' email address flow using above workaround and working fine.

Flow followed:
1. Configure abc@gmail.com and Password in secrets during deployment
2. Login to abc@gmail.com gmail account-> Navigate to settings -> accounts
3. Add email (which SB admin wish to configure in manage apps section for sending emails.) eg. xyz@gmail.com in `send email as` field in gmail account settings
4. Authorize and save
5. Login to SB and add xyz@gmail.com to `'From' email for outgoing app emails'` field in app properties section
6. Create/Publish app
7. All app related emails will be sent from xyz@gmail.com
