### ISSUE TITLE
[SB] [Manage apps] UI issue in App properties screen 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4105]
**Steps:**

1.Edit the created app.
2. Navigate to App Properties section and Observe.

AR: In App Properties screen below fields are displayed as below,
1. Contact Us email 
2. App Privacy policy URL
3. 'From' email for outoging app emails

ER: In App Properties screen below fields should be displayed as below,
1. 'Contact Us' email 
2. App Privacy Policy URL
3. 'From' email for outgoing app emails

![Untitled99999999999999991111111111111](https://user-images.githubusercontent.com/86007179/132510591-b1afb15b-5ba7-478d-9da8-6d76d0455926.png)

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest dev instance.

**Comment by aswinijena100** [comment]
@bhoomikav16 Please test in QA and close if fixed

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
