### ISSUE TITLE
[SB] [Manage apps] UI issue > Edit app details >Actions screen > (right mark) in green color is not getting the displayed next to the 'Distributed' text

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4112]
**Steps:**
1. Login to SB
2. Click on Manage apps
3. Create an app
4. Click on the edit icon of the app
5. Complete all the sections and Publish the app
6. Again click on the edit icon of the app
7. Go to the 'Actions' section
8. Distribute the apps
9. Observe the Actions section

**AR:** (right mark) in green color is not getting the displayed next to the 'Distributed' text
**ER:** (right mark) in green color should be displayed next to the 'Distributed' text

![image](https://user-images.githubusercontent.com/71445210/132533546-400918fa-3169-4727-b8bb-791549d8bb84.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
