### ISSUE TITLE
[SB] [Manage Apps] Edit app detail screen > App status > UI issue on the side menu bar

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4114]
AR: Status of the app record are not separated with a separator line
ER: Status should be shown as per the invision screen

Note: 
1. Issue observed only in Firefox browser
2. Refer invision screen or in Chome browser

![image](https://user-images.githubusercontent.com/71445210/132537650-2071ab41-8808-47ea-b36a-c7045501dc43.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 i have fixed please check and let me know.
thanks.

**Comment by bhoomikav16** [comment]
@Madhud5  Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
