### ISSUE TITLE
[SB] Edit admin details screen > 'Delete admin' icon should be displayed for the admins who's account is not activated

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4115]
Steps:
1. SB > Login as superadmin
2. Go to Admins screens
3. Click on Create admin
4. Create a new admin
5. Click on the edit icon of the admin
6. Observe 

AR: On the edit admin screen, the 'Delete admin' button is not displayed
ER:  'Delete admin' icon should be displayed for the admins who's account is not activated

**Comment by akashkumarv3** [comment]
@Lathan-btc #4115 issue is fixed in dev env.   please test and update .

**Comment by bhoomikav16** [comment]
@akashkumarv3  The issue is fixed in the latest dev instance.

**Comment by akashkumarv3** [comment]
@bhoomikav16 Issue #4115 Please test in QA and update it.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
