### ISSUE TITLE
[SB] [Manage apps] Edit app details screen > Actions section > 'Mark iOS/Android app as distributed' button should be disabled until the latest changes are published

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4121]
Steps:
1. Login to SB
2. Create an app
3. After completing all the sections, publish the app updates
4. Again edit the properties and don't publish the updates
5. Observe the  'Mark iOS/Android app as distributed' button on the Actions screen

AR: 'Mark iOS/Android app as distributed' button is enabled and able to distribute apps
ER: If the apps are not already distributed, then 'Mark iOS/Android app as distributed' buttons should be disabled until the latest properties are published.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue in Dev

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.
