### ISSUE TITLE
[SB] [Manage apps] Studies list screen > 'Select apps' dropdown filter > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4124]
Studies list screen > 'Select apps' dropdown filter > UI issues
1. When admin clicks on the 'Select apps' dropdown, the background color should be white 
2. Scrollbar should be displayed when admin clicks on 'Select apps' dropdown
3. Width of the values of the dropdown should be the same as the width of the 'Select apps' dropdown
4. 'All apps' should be aligned with other values in the dropdown

[Note: 1st point should also be fixed for 'Select app' dropdown present on the study information screen]

![image](https://user-images.githubusercontent.com/71445210/133380045-96ee244f-e993-4a6f-9568-4bbcbd13a5a7.png)

**Comment by Madhud5** [comment]
@bhoomikav16  i have fixed please check and let me know.
thank you.

**Comment by bhoomikav16** [comment]
@Madhud5  Issue is fixed in the latest dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc pls check this issue and let me know.
thanks

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc  Please test in QA and close if fixed.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
