### ISSUE TITLE
[PM] User data is missing in Apps tab

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4125]
A/R:- User data is not displaying properly in Apps tab and data available in Participant details page.
E/R:-  User data should displayed properly across the application

**Note**:- Because of above issue, user is unable to sign in into mobile app and getting **user not found** error.

![image](https://user-images.githubusercontent.com/60500517/133394748-5335e0ca-5f20-44c1-a8d4-be5b815762f9.png)

![image](https://user-images.githubusercontent.com/60500517/133395260-c6086db6-1ef6-429f-8dd5-f3120fc24e5a.png)

![image](https://user-images.githubusercontent.com/60500517/133395318-539a9029-863b-424a-a432-af883de89b34.png)

**Comment by Lathan-btc** [comment]
The issue is not reproducible for new participants
