### ISSUE TITLE
[SB] Edit admin details screen > 'Create new apps/studies' checkbox is disabled in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4127]
Steps
1. Login to SB
2. Create an admin with Superadmin role
3. Click on the edit button of the admin
4. Change the role from 'Superadmin' to 'Study admin'
5. Observe the 'Create new apps/studies' checkbox 

AR: 
1. 'Create new apps/studies' check box is disabled
2. 'Create new studies' button checkbox is deselected

ER: 
1. 'Create new apps/studies' checkbox should be enabled
2. 'Create new studies' button checkbox should be selected

![image](https://user-images.githubusercontent.com/71445210/133424438-bfc24bd5-c11d-48d5-a00d-d821dd1e20d1.png)

![image](https://user-images.githubusercontent.com/71445210/133424242-5a005c07-a78d-4ba3-9cc6-fc948cc2f593.png)

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please test and confirm.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc  Please test in QA and close if fixed

**Comment by Lathan-btc** [comment]
issue is fixed in the latest QA instance.
