### ISSUE TITLE
[PM] Add/admin screen > Change 'User' to 'admin' in the following error message

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4128]
Steps:
1. Login to PM
2. Click on the admins tab
3. Click on add admin or edit admin
4. do not assign any permissions
5. Click on the 'Add admin user and invite' button and observe

ER: in the following error message, 'user' should be changed to 'admin'.

![image](https://user-images.githubusercontent.com/71445210/133580249-8a6c1f19-a5b3-4d34-b567-4058190118dc.png)

**Comment by Rashi-395** [comment]
@Lathan-btc  [PM] Add/admin screen > Change 'User' to 'admin' in the following error message #4128 -fixed

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc  Please test in QA and close if fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in the QA instance.
