### ISSUE TITLE
[SB] [Manage apps] [Copy] Permissions > Studies list screen > Copied study > Study information screen > App related details should not be copied into new study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4130]
Step:
1. Login to SB
2. Go to the Studies list screen
3. Copy the particular study 
4. Click on the edit button of the copied study
5. Observe the 'App type' and 'App ID' fields on the 'Study information' screen

AR: Data in 'App type' and 'App ID'  fields getting displayed but data in 'Select app' dropdown is getting cleared
ER: App related information should not be copied into new study

![image](https://user-images.githubusercontent.com/71445210/133632909-2e9c3a78-b944-45c7-a781-d5fcdff5cc42.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
