### ISSUE TITLE
[SB] [Manage apps] Create app > App settings screen > Validation should be done for the following scenario 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4131]
Steps:
1. Login to SB
2. Click on Manage apps'
3. Click on Create app
4. Enter the app id which is already used for more than one study
5. App settings screen, select 'Standalone' as the app type
6. Enter all the required fields
7. And try to click on 'Mark as completed' 

AR: Admin is able to click on the 'Mark as completed' button and the section is getting completed
ER: The following warning popup should be displayed when the admin click on the 'Mark as completed' button
'This app seems to be linked to multiple studies. Please select the 'gateway' app type to proceed.' with 'Ok' and 'Cancel' buttons
- If the admin clicks on the 'Ok' button admin should stay in the same 'App settings' screen

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev.

**Comment by Lathan-btc** [comment]
@monica-BTC If the admin clicks on Mark as completed button without entering the required fields then above mentioned pop-up should not be displayed.

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by bhoomikav16** [comment]
@monica-BTC  Issue is fixed in the latest dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
