### ISSUE TITLE
[SB] Add/edit admin screen > Permissions section > Text case issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4132]
'Manage Studies' should be changed to 'Manage studies' (S in studies should be in lowercase)

![image](https://user-images.githubusercontent.com/71445210/133960120-cadf440e-6e23-4f00-9944-873dfb543a52.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
