### ISSUE TITLE
[Android] User is able to skip the force upgrade pop-up and continue using the app by clicking on 'Forgot passcode?Sign in again'

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4139]
**Steps:**

1. Signup/login to Android app and create a passcode
2. Configure force upgrade from SB and publish app
3. Kill and relaunch the app/minimize the app
4. Click on 'Forgot passcode?Sign in again' link
5. User is navigated to signin. 
6. Again signin/signup with new user, user is able to enroll/take activities or perform any actions.

**Actual:** User is able to skip the force upgrade pop-up and continue using the app by clicking on 'Forgot passcode?Sign in again'

**Expected:** Force upgrade should always be displayed and restrict user to navigate inside any other screens

Refer video

https://user-images.githubusercontent.com/60386291/134026653-60334695-7940-49aa-a54a-78654b069ecc.mp4

**Comment by naveenr-btc** [comment]
Made changes to show update popup, if only it's a force update.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV gateway build v1.0(117)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV Standalone build v1.0(118)

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build v1.0(121)
