### ISSUE TITLE
[SB] [Manage apps] Create app > App settings screen > View associated studies icon should be disabled for the following scenario.

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4140]
**Steps:**

1. Login to SB
2. Click on Manage apps icon.
3. Click on Create app.
4. Enter the app id which is already used for more than one study.
5. App settings screen, select 'Standalone' as the app type.
6. Enter all the required fields.
7. And try to click on 'Mark as completed'.

**AR:**  If the app status is in draft, view associated studies icon is enabled.
**ER:** If the app status is in draft, view associated studies icon should be disabled.

**Comment by monica-BTC** [comment]
@bhoomikav16, please test and confirm in dev

**Comment by bhoomikav16** [comment]
@monica-BTC  Issue is fixed in the latest dev instance.

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
