### ISSUE TITLE
[SB] [Manage Apps] [Developer Configurations ] Need to update the character length for the Server Keys for both Android and iOS

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4146]
A/R:- Currently the limit is **100** characters for 'Android Server Key' and 'iOS Server Key'

E/R:- It should be the increased to **255** characters for 'Android Server Key' and 'iOS Server Key'

**Note**:- Because of current implementation, unable to enter the complete server key inside the field

![image](https://user-images.githubusercontent.com/60500517/134370265-4f128c93-444d-497c-9004-9ab8484ed9b8.png)

**Comment by monica-BTC** [comment]
@nagarjunav1, Please test and confirm in dev

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
