### ISSUE TITLE
[SB] [Manage Apps]  App name should get changed when study is active irrespective of app published or not published.

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4151]
**Steps:** 

1. Create an app.
2. Click on studies tab.
3. Click on create study button.
4. Add created app from the select app dropdown in the study information screen and complete all the sections.
5. Lauch the study.
6. Click on Apps tab.
7. Edit the app which was created as in the step 1.
8. Edit the app name and click on mark as completed button.
9. Complete all the sections and publish the app.
10. Again edit app name for the same published app and click on mark as completed.
11. Again navigate to the study for which app was added.
12. Observe the App name in the study information screen and Verify.

**AR:** App name is not getting changed in the study information screen.
**ER:** App name should be changed in the study information screen irrespective of app published or not published.

Note: To maintain consistency app name should get changed when study is active irrespective of app published or not published.

**Comment by monica-BTC** [comment]
@bhoomikav16, please test and confirm in dev

**Comment by bhoomikav16** [comment]
@monica-BTC Issue is fixed in the latest dev instance.

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
