### ISSUE TITLE
[SB] [Manage apps] Studies list screen > Filter by apps dropdown > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4154]
1. Length of the 'Filter by apps' dropdown and dropdown values field should be the same
2. When the admin filter the apps, the dropdown values field looks like it has been a break

![image](https://user-images.githubusercontent.com/71445210/134897297-32b83a9f-7204-4568-9246-47fddd4d4342.png)

3. Ui issue when there are no records in the 'Filter by apps' dropdown

![image](https://user-images.githubusercontent.com/71445210/134898462-baa5bb54-ae5c-4d1a-81c4-c1ead4b9b494.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc  Please test in QA and close if fixed.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
