### ISSUE TITLE
[SB] [Manage apps] Studies list screen > 'Filter by apps' dropdown > Functional issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4156]
AR: Apps are getting displayed in the dropdown for which admin is having the permission
ER: Apps should be displayed in the filter dropdown list based on the studies displayed in the studies list screen

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test and confirm in dev

**Comment by Lathan-btc** [comment]
@monica-BTC Only one app ID is getting displayed n the dropdown even though there are multiple studies with the different app ID

![image](https://user-images.githubusercontent.com/71445210/135221372-4b243b4f-3ba0-47ce-b10d-2795e2ba2182.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, not able to reproduce this issue. Please retest and update the ticket.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
