### ISSUE TITLE
[SB] [Manage apps] Notifications tab is getting displayed on the main bar

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4159]
Steps:
1. Login to SB
2. Create an admin by providing permission only for the studies
3. Create an account for the new admin and login to SB
4. Click on Configure studies and observe 

AR: Notifications tab is getting displayed on the main bar
ER: Notifications tab should be hidden when admin doesn't have permission to Manage apps

![image](https://user-images.githubusercontent.com/71445210/135073178-b2b6a174-6176-48ec-b98a-06a66823cb97.png)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
