### ISSUE TITLE
[SB] [Manage apps] Check box > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4160]
**AR:** Check box is getting displayed in 3D view

**Note:** 
1. Issue observed only in the latest version of firefox browser
2. Issue should be fixed for all the checkboxes present in the study builder application

![image](https://user-images.githubusercontent.com/71445210/135077173-f93e6146-ea17-4f63-a25a-c5abfe7d4e90.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Madhud5** [comment]
HI, @Lathan-btc I have fixed in Dev pls check and let me know.
thank you.

**Comment by Lathan-btc** [comment]
issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc Please test in QA and close if fixed.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
