### ISSUE TITLE
[SB] [Manage apps] App level notifications > Create/edit notifications > 'App to which the notification must be sent' dropdown field should be mandatory

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4161]
**AR:** Create/edit notifications > Admin is able to create notifications without selecting any app from the 'App to which the notification must be sent' dropdown
**ER:** 'App to which the notification must be sent' dropdown should be a mandatory field 

![image](https://user-images.githubusercontent.com/71445210/135218037-66ce26a9-af5a-4579-8b43-8e69ca9ee5f9.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test and confirm this issue.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
