### ISSUE TITLE
[SB] [Manage apps] Add/edit admin screen > Study admin > 'Select and add studies' dropdown > UI issue 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4162]
Add/edit admin screen > Study admin > 'Select and add studies' dropdown > Fields are not aligned properly 

![image](https://user-images.githubusercontent.com/71445210/135224292-9d5e9440-bc18-4986-ae4a-5f31275e1079.png)

**Comment by Madhud5** [comment]
HI, @Lathan-btc I have fixed in Dev pls check and let me know.
thank you.

**Comment by Lathan-btc** [comment]
@Madhud5 issue is reproducible in the latest Dev instance

![image](https://user-images.githubusercontent.com/71445210/135442273-4af43243-8db2-4b5b-b8cf-e2d0433785a1.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@Lathan-btc  Please test in QA and close if fixed.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by bhoomikav16** [comment]
UI issue in the add/edit admin screen > Study admin > Select and add studies dropdown.

**AR:**  There is no scroll down icon in the dropdown.
**ER:**  Scroll down icon should be displayed.


![Untitledm](https://user-images.githubusercontent.com/86007179/142421924-ec111ff6-6a08-4f05-8520-6083f5ece078.png)

**Comment by bhoomikav16** [comment]
The issue is fixed in the dev instance.
