### ISSUE TITLE
[SB] [Manage apps] Create/edit study > Study settings screen > Page is loading continuously in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4163]
**Steps:**
1. Login to SB and click on Configure studies 
2. Create/Edit study
3. Study information screen > Select the app which supports only iOS
4. Mark the section as completed
5. Study settings screen > Don't select any platform
6. Click on Mark as completed button and observe

ER: Page is loading continuously
ER: Error message should be displayed and the page should not load continuously

![image](https://user-images.githubusercontent.com/71445210/135234885-e6250571-d1bd-4c15-80ec-c1f7165e2999.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
