### ISSUE TITLE
[SB] [Manage apps] UI issue in App sections

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4165]
**AR:**  App information screen , app settings screen , app properties screen and developer configuration screen is not alligned properly.
**ER:**  App information screen , app settings screen , app properties screen and developer configuration screen should be properly alligned as per invision screen.

1. App information screen
![Screenshot (291)](https://user-images.githubusercontent.com/86007179/135268248-572e898c-42e2-43a3-ba9a-82dbf499d446.png)

2. App settings screen
![Screenshot (290)](https://user-images.githubusercontent.com/86007179/135268370-b4452699-9433-4234-b0ad-b330edb474c7.png)

3. App properties screen
![Untitled11111222](https://user-images.githubusercontent.com/86007179/135266282-3ef2eecd-fd9b-4157-aaa6-9fa2931579b2.png)

4. Developer configuration screen
![qwe](https://user-images.githubusercontent.com/86007179/135268681-3ab3b9b9-a83f-48a2-9550-629347596baa.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 I have fixed it in dev, pls check and let me know.
thank you.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by aswinijena100** [comment]
@bhoomikav16 @Lathan-btc  Please test in QA and close if fixed.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
