### ISSUE TITLE
[SB] Full stop should be removed at the end of place holder text.

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4166]
Full stop should be removed at the end of place holder text when there are no records in the table.

![Untitled123987](https://user-images.githubusercontent.com/86007179/135281117-4b6a735a-82bd-4e01-b1ab-2066642be141.png)

**Comment by aswinijena100** [comment]
@bhoomikav16 Please test it in QA and close if fixed

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
