### ISSUE TITLE
[SB] [Manage apps] Add/edit app > Actions section > Change the text under action buttons as per the updated sheet

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4167]
Add/edit app > Actions section > Change the text under the following action buttons as per the updated excel sheet 
1. Publish app
2. Mark iOS app as distributed
3. Mark Android app as distributed

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
