### ISSUE TITLE
[SB] [Manage apps] Deactivated apps > View mode > Admin is not able to navigate to the following screens

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4168]
Deactivated apps > view mode > Admin is not able to navigate to the following screens
1. App properties 
2. Developer configurations

![image](https://user-images.githubusercontent.com/71445210/135441632-351e8ffb-3f49-423b-9c3b-9491a996b398.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc please test and confirm in dev instance.

**Comment by Lathan-btc** [comment]
@madhurya-btc Unable to click on Any sections in the following scenario
1. For an active app Don't mark the App information/app settings/both sections
2. Deactivate the app
3. Click on the View icon of the deactivated app
4. Try to click on other sections

AR: All the sections are enabled but nonfunctional
ER: Admin should navigate to respective screens when admin clicks on remaining sections

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
