### ISSUE TITLE
Disallow '+' as activity id in StudyBuilder

### ISSUE THREAD

**Issue by kuoyuchi** [GoogleCloudPlatform/fda-mystudies#418]
We configured a questionnaire with activityId=`PHQ9+SH` in StudyBuilder. In the app, user sees "not able to get data" error when clicking on this questionnaire from activity list.

I did some digging and the issue is that `+` is used as the special character to escape spaces in URL. Therefore, when I print out `activityId` in `/StudyMetaData/activity` controller, it prints `PHQ9 SH` instead of `PHQ9+SH`.

Therefore, I think we should either disallow `+` in activity id in StudyBuilder, or support this properly in StudyMetaData. I think the former one would be easier.

https://www.urlencoder.io/java/

**Comment by Lathan-btc** [comment]
Issue is fixed in latest  Dev instance
