### ISSUE TITLE
[SB][Manage apps] [QA] Create/edit study >Study settings screen > Platform(s) supported > Admin is able to select both the platforms even though the selected app supports only one platform

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4184]
**Steps:**
1. Log in to SB 
2. Go to the Studies list screen
3. Click on create/edit study
4. Study information screen > Select the app which supports only iOS/Android
5. Mark the section as completed
6. Study settings page > Observe the checkboxes under the 'Platforms supported' section

**AR:** Both the Checkboxes are enabled and the admin is able to select
**ER:** Only supported platform(s) should be enabled (if App support only iOS then in the study settings page, only iOS should be enabled and android should be disabled and vice versa)

[Note: Issue observed only in QA instance]

![image](https://user-images.githubusercontent.com/71445210/136021015-0fc5b1d4-e899-4a39-adc9-726fb09f200f.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test in QA and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
