### ISSUE TITLE
[SB] [Manage apps] [QA] UI issue in the Add / Edit admin screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4191]
Add admin or Edit admin > Assigned permissions > Manage apps > Select and add apps from the dropdown > Observe the radio buttons and Verify.

![Screenshot (333)](https://user-images.githubusercontent.com/86007179/136147901-4a8d070b-79dd-4f08-9c56-bb922a07ba8c.png)

**Comment by Lathan-btc** [comment]
@Madhud5 Please assign the ticket to the QA team once PR is approved and Merged
