### ISSUE TITLE
[SB][Manage apps][QA] Unable to Deactivate the app > getting error message

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4193]
Unable to Deactivate the app > getting an error message

![image](https://user-images.githubusercontent.com/71445210/136149392-11986420-089a-4da8-8ef5-a8c1044e6cb5.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance.
