### ISSUE TITLE
[SB] [Import / Export] Apostrophe symbol is not getting retained in the imported study.

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4209]
**Steps:**

1. Create a study by including  **Apostrophe symbol '**  in the text fields like Study name / Overview title / Description / Question name / Text choice / Options name / consent etc.
2. Launch the study.
3. Import the created study and Observe all the fields in the imported study and Verify.

**AR:**  Apostrophe symbol `'`   is not getting retained in the imported study.
**ER:**  Apostrophe symbol `'`  should be retained in the imported study.

**Note:** Issue is observed in all the sections [Study information, Overview, Informed consent, Study activities , Resources. Notifications sections]
Issue not observed for copied studies

1. Active Study.

![Untitledqw123](https://user-images.githubusercontent.com/86007179/136578184-78af2ff3-567d-402b-abd4-0194453b74e6.png)

2. Imported Study.

![Untitledqaqaqaq111111111111](https://user-images.githubusercontent.com/86007179/136575734-a773595e-7cdf-4eeb-b85f-e00a39183fd3.png)

**Comment by monica-BTC** [comment]
@bhoomikav16, Please test and confirm in QA
