### ISSUE TITLE
[SB] Some of the studies are not getting displayed in the study list screen 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4212]
Add / Edit admin Screen > Study admin > Assigned permission > Select and add studies dropdown > Following study is getting displayed in the dropdown but not getting displayed in the study list screen.

Note: Issue is observed for superadmin also.

Study name: 
1.new_study_12345 ()
2.New Study11 () 
3.Demo study for both IOS Android-copiedstudy ()

**Comment by Lathan-btc** [comment]
@madhurya-btc @aswinijena100 Issue is not reproducible in the QA instance and we will reopen the ticket once we get the exact scenario.
