### ISSUE TITLE
[SB] 'Show deactivated studies' button is not getting displayed for the Study admin who does not have permission to create a study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4213]
AR: 'Show deactivated studies' toggle button is not getting displayed for the Study admin who does not have permission to create a study 
ER: 'Show deactivated button' should be displayed for all the admins and if the admin does not have permission to create a study then the toggle button should be aligned to the right.

Note: Issue observed only when admin does not have permission to create a study

![image](https://user-images.githubusercontent.com/71445210/136750847-0dff19f8-e35f-413a-b911-fa45561c9e43.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
