### ISSUE TITLE
[PM] Sent invitation email > Wrong 'From' email address is getting displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4222]
AR: Sent invitation email > Wrong 'From' email address is getting displayed
ER: 'From' email address should be the same as configured in the SB for that particular app

Received email:

![image](https://user-images.githubusercontent.com/71445210/137755128-8696b725-48bc-4eb9-8363-6af0eb74849d.png)

Configured in SB for that particular app

![image](https://user-images.githubusercontent.com/71445210/137755628-9b8f3694-ef78-4e03-8b51-2cb500edb776.png)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in QA
