### ISSUE TITLE
[SB] Edit study admin > Assigned permission > Manage studies > Select and add studies dropdown

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4224]
Edit study admin > Assigned permission > Manage studies > Select and add all the studies from the dropdown > Again click on select and add studies dropdown and Observe.

**AR:**  No text is displayed when all the studies are already added from the dropdown.
**ER:**  'All items are already selected' text should be dispalyed when all the studies are already added and when again clicked on select and add studies dropdown.

![c](https://user-images.githubusercontent.com/86007179/137757366-4855cb44-6d1e-49be-872e-c82077eb15f9.png)

**Comment by bhoomikav16** [comment]
@akashkumarv3 

Edit study admin > Assigned permission > Manage studies > Select and add the studies from the dropdown > Getting text in the dropdown as 'All items are already selected' , while few studies only were added from the dropdown > Again Edit same admin > Still studies are available in the dropdown.

ER: 'All items are already selected' text should be displayed when all the studies are added and when again clicked on select and add studies dropdown.

**Comment by akashkumarv3** [comment]
@bhoomikav16 #4224 is fixed please test and update this.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by akashkumarv3** [comment]
@bhoomikav16  Please test in QA environment  and update it .

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
