### ISSUE TITLE
[PM] [Permission] Getting error message when clicked on Apps tab in dashbord.

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4229]
**Steps:**

1. Login as Superadmin.
2. Admins > Edit the admins and give all permissions to site admin.
3. Logout as Superadmin.
4. Login as Site admin.
5. Click on Apps tab in dashboard and Observe.

**AR:**  Getting error message when clicked on Apps tab in dashbord.
**ER:** When clicked on Apps tab , Apps screen should be displayed.

Issue is observed only for the admins who has other than Superadmin permission.

![Screenshot (446)](https://user-images.githubusercontent.com/86007179/137920887-499e5ca1-5ef2-4cf4-8489-492a7a3fd8bf.png)

**Comment by aswinijena100** [comment]
@bhoomikav16 Please check this issue in dev and confirm
