### ISSUE TITLE
[PM] [Permission] App status is not getting displayed in the below mentioned screens 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4230]
**Login as Site admin** 
 
1. Site > Enrollment registry.
2. Studies > Enrollment registry.
3. Studies > Study participant registry.

**Note:**  
1. Issue is observed only in above three screens for the admins who has other than super admin permission.
2. Issue is observed only for open studies in Site > Enrollment registry

**Site > Enrollment registry.**
![q](https://user-images.githubusercontent.com/86007179/137934499-da67ef97-fa3e-48a6-baa6-ee9b82d94962.png)

 **Studies > Study participant registry.**
![w](https://user-images.githubusercontent.com/86007179/137936293-2bad9987-61ef-4ab1-9dc2-d5381fcd5da7.png)

**Studies > Enrollment registry.**
![e](https://user-images.githubusercontent.com/86007179/137937536-543cdb52-ebaf-430a-b8a6-aafc75b4c1fb.png)

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in dev instance.

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
