### ISSUE TITLE
[SB] Radio buttons and plus icon beside select and add apps / studies in assigned permission is getting enabled for the below scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4232]
**Steps:**

1. Login to SB.
2. Click on Manage admins icon.
3. Click on add / edit Study admin.
4. Assigned permission > Select Manage apps > click on select and add apps dropdown > Select one / multiple apps.
5. Now deselect the Manage apps checkbox and then click on plus icon beside the select and add apps dropdown and Observe.

 **AR:** View only and view and edit radio buttons and also plus icon beside select and add apps dropdown is getting enabled for the above scenario.
**ER:**  View only and view and edit radio buttons and also plus icon beside select and add apps dropdown should not be enabled for the above scenario.

**Note:**  Issue needs to be fixed for Manage studies >  select and add studies dropdown.

![t](https://user-images.githubusercontent.com/86007179/138033780-ec848216-e281-48ac-9a32-b57e075652b7.png)

**Comment by aswinijena100** [comment]
@bhoomikav16 Please test it in QA and close if fixed

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest QA instance.
