### ISSUE TITLE
[PM] Below study is not getting displayed in PM.

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4233]
Below study is not getting displayed in PM.

**StudyID -**  Ipv5
**Study name -**  Imported Mobile App Open Study (Original )

![Screenshot (478)](https://user-images.githubusercontent.com/86007179/138041389-a2bc8d92-279a-438d-be10-e9353985c4ea.png)

**Comment by Rashi-395** [comment]
@bhoomikav16 issue in not reproducible in latest QA instance . Please test and close

**Comment by bhoomikav16** [comment]
Issue is not observed in the QA instance
