### ISSUE TITLE
[Response Server] Issue related to duplicate responses getting saved with same activityRunId and endTime

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4252]
**Issue:** Occasionally, duplicate entries are found (same activityRunId and endTime but different created date) in the Firestore Activities that corrupts reporting results when fetched.

**Approach:** Changes should be made to check if the current response already exists for a participant/study combination and It will submit the response only if the response does not exist on the Response Server.

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in a dev instance

**Comment by nishit-v** [comment]
Flow is working fine and no duplicate entires found in dev intance.

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Flow is working fine and no duplicate entires found in QA intance.
