### ISSUE TITLE
[SB] Studies list screen > Place the Delete icon for the studies which are in Prelaunch status

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4254]
Steps:
1. Login to SB
2. Go to Studies list screen

AR: Currently there is no option to delete the studies which are in Prelaunch status in the SB
ER: Add an option to delete the studies that are in Pre-launch status.  The Delete action icon can be placed in the Studies list screen as the last action icon in the Actions column (in place of View last published version - which is anyway an action that is not available for Pre-launch studies). The Delete action will completely delete the study from the Study Builder

[Note: Study admin > if admin doesn't have the view and edit permission for any prelaunch studies, then Delete icon should be disabled]

**Comment by Lathan-btc** [comment]
Delete functionality is not working

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by akashkumarv3** [comment]
@Lathan-btc please test in QA and update this.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
