### ISSUE TITLE
[Unknown Backend] Questionnaires > Text response type > Validations are not proper in the following scenarios

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4256]
Questionnaires > Text response type > Validations are not proper in the following scenarios

1. Allow > All characters > except ? and / > in mobile app not accepting any characters > showing 'Invalid input. Please try again'
2. Disallow > All characters > except ? and / > In mobile app, not accepting / and ?  > showing 'Invalid input. Please try again'

Steps:
1. Login to SB
2. Edit Study
3. Go to questionnaires
4. Add/edit questionnaire
5. Add question step/form step 
6. Select 'Text' response type
7. Complete the questionnaire with the above conditions in the 'Response level attributes' tab
8. Publish the updates
9. In mobile app > enroll into the study
10. Click on particular text response type activity
11. Check the validations based on the above mentioned conditions

**Comment by bhoomikav16** [comment]
Issue is still reproducing in dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
