### ISSUE TITLE
[iOS] Sign in screen > UI issue 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4257]
Sign in screen > 'New User? Sign up' is getting wrapped into two lines

[Note: Issue observed in  iPhone XS]

![image](https://user-images.githubusercontent.com/71445210/141324871-871096e7-fd26-4cfd-bf18-093f77a52a2d.png)

**Comment by Rashi-395** [comment]
@Lathan-btc [iOS] Sign in screen > UI issue is fixed in latest dev instance . please check

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest  dev instance

![image](https://user-images.githubusercontent.com/71445210/148338223-588b8178-d8f7-4aff-bac6-ab3587d41c23.png)

**Comment by harisboston** [comment]
@Lathan-btc  issue is fixed in QA environment

**Comment by Lathan-btc** [comment]
@harisboston issue is reproducible in the latest QA instance and also found the following UI issues
 1. Copy right text should be center-aligned 
 2. Unnecessary white space is getting displayed at the bottom of the screen> It should not be present

![image](https://user-images.githubusercontent.com/71445210/161034809-52857a35-853b-41fe-aec5-733f194988f8.png)

**Comment by Lathan-btc** [comment]
@harisboston 
1. Forgot password link should move a little above
2.  Copyright text should be vertically center-aligned

**Comment by Lathan-btc** [comment]
@harisboston Copyright text should be vertically center-aligned - the issue is reproducible in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by harisboston** [comment]
@Lathan-btc This issue is fixed in QA environment

**Comment by bhoomikav16** [comment]
@harisboston 
Copyright text is not center aligned in sign in screen

![screenshot](https://user-images.githubusercontent.com/86007179/164176400-08e722de-f573-4c4f-b53a-25dbfe048b65.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
