### ISSUE TITLE
[SB] Questionnaires are not getting saved in the draft status in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4258]
Steps:
1. Login to SB
2. Go to Questionnaires
3. Add a questionnaire
4. Click on dit questionnaire
5. Add any step by directly clicking on the Done button (While adding step Don't click on Save)
6. Go to the main questionnaires list screen
7. Observe the questionnaire

AR: Questionnaires is not showing in draft status
ER: Questionnaires should be saved in draft

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
@sheelakanni97 issue is reproducible in the latest QA instance

**Comment by sheelakanni97** [comment]
@Lathan-btc  I will check it.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
