### ISSUE TITLE
[PM] Dashboard > Sites > Add Site > in the popup > Select Location dropdown > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4259]
Dashboard > Sites > Add site > In the popup > Select location dropdown > there is no right/left padding or margin for the list of locations displayed in the dropdown

![image](https://user-images.githubusercontent.com/71445210/141466499-f1f86fe6-013a-4d78-8faf-7350a0931393.png)

**Comment by Rashi-395** [comment]
@Lathan-btc [PM] Dashboard > Sites > Add Site > in the popup > Select Location dropdown > UI issue #4259 -fixed

**Comment by Lathan-btc** [comment]
@Rashi-395 Issue is reproducible in the latest Dev instance

![image](https://user-images.githubusercontent.com/71445210/144198440-eee05c4f-effd-44c6-bc9e-6ce35304dc00.png)

**Comment by Rashi-395** [comment]
@Lathan-btc Fixed in latest DEV instance

**Comment by Lathan-btc** [comment]
@Rashi-395 there is no space between margins and values

![image](https://user-images.githubusercontent.com/71445210/144570338-ff082bf5-2233-4ed6-a67e-3fe9323006b9.png)

**Comment by Rashi-395** [comment]
@bhoomikav16 [PM] Dashboard > Sites > Add Site > in the popup > Select Location dropdown > UI issue is completed in latest dev instance

**Comment by Lathan-btc** [comment]
@Rashi-395 UI issue after selecting the value from the dropdown

![image](https://user-images.githubusercontent.com/71445210/146766858-1d09e334-afb4-486a-957f-4b9cc1831ca6.png)

**Comment by Rashi-395** [comment]
@Lathan-btc [PM] Dashboard > Sites > Add Site > in the popup > Select Location dropdown > UI issue is resolved in latest dev instance . please check.

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by Rashi-395** [comment]
@Lathan-btc Please test and confirm in QA instance.

**Comment by Lathan-btc** [comment]
@Rashi-395 Remove 'Select location' value from the select location dropdown


![image](https://user-images.githubusercontent.com/71445210/158817238-e616d979-29be-488f-88a2-04cfb0afc376.png)

[Note: Issue observed only in QA instance]

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
