### ISSUE TITLE
[Android] Getting error when opened the android app

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4266]
**Steps:**
1. Install the app.
2. Open the app and Observe.

AR:
![Screenshot_20211122-105152_FDA MyStudies](https://user-images.githubusercontent.com/86007179/142809988-bb00ddba-ae94-4be1-894c-2cef4d6150e5.jpg)

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest DEV build v1.0(130)
