### ISSUE TITLE
[iOS] Text scale > Slider button not visible on clicking 'Save for later' and opening the activity

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4267]
**Steps:**
1. Configure a text scale horizontal/vertical for question/form step
2. Publish updates
3. Enroll into study from iOS
4. Open the activity
5. Choose some of the options and click on Cancel
6. Choose save for later
7. Again open the activity
8. Observe slider button not visible

**Actual:** Slider button not visible on clicking 'Save for later' and opening the activity

**Expected:** Slider button should be visible 

Issue observed for
1. Question step - Text scale horizontal
2. Question step - Text scale Vertical
3. Form step - Text scale horizontal
4. Form step - Text scale Vertical

App ID - GCPMOB001
Study ID - TriteraNatural

**Refer video**

https://user-images.githubusercontent.com/60386291/143011833-4c57808f-d870-4da4-9c2b-b12b82c22c97.MOV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest build

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA build V11.1
