### ISSUE TITLE
[SB] Active task > Duplicate active tasks are getting created in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4268]
Steps:
1. Login to SB
2. Click on edit study (Study should be created only for iOS platform)
3. Go to Active tasks section
4. Click on add Active task
5. Select any one of the active task from the dropdown
6. Then Again change the active task from the dropdown 
7. Enter all the required data
8. Click on Done button and observe

AR: Duplicate active tasks are getting created
ER: Only one active task should be created

![image](https://user-images.githubusercontent.com/71445210/143013492-eb1da6a1-0f38-46aa-968b-461c116375a7.png)

**Comment by Lathan-btc** [comment]
@akashkumarv3 issue is reproducible in the latest Dev instance

![image](https://user-images.githubusercontent.com/71445210/143999744-f3faa3c7-7c24-457d-af46-deac8400666e.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by akashkumarv3** [comment]
@Lathan-btc please test in QA  and update this.

**Comment by Lathan-btc** [comment]
Issue is happening randomly and getting the error message when admin added active task

![image](https://user-images.githubusercontent.com/71445210/146375957-74325d51-4d58-4f17-adb7-87253610ddc2.png)

**Comment by Lathan-btc** [comment]
@akashkumarv3 

1. Active tasks are getting duplicated 

Steps:
1. Add/edit study
2. Go to activities 
3. Click on Add activities
4. Select 'Tower of Hanoi' and again change 'Spacial span memory' to 'Fetal kick counter'
5. Again select 'Tower of hanoi'
6. Enter all the mandatory fields
7. In the Schedule tab, select 'Regular' and 'One time' frequency
8. Click on the Done button and observe

![image](https://user-images.githubusercontent.com/71445210/150809919-62e13380-8df2-4b4a-a4eb-2f0393e001b1.png)

2. Getting the following error message

Steps:
1. Add/edit study
2. Go to activities 
3. Click on Add activities
4. Select 'Tower of Hanoi' and again change 'Tower of Hanoi' to 'Fetal kick counter'
5. Again select 'Tower of hanoi'
6. Enter all the mandatory fields
7. In the Schedule tab, select Regular and daily frequency
8. Click on the Done button and observe

![image](https://user-images.githubusercontent.com/71445210/150812505-b76810af-2b42-4ca6-a00a-0b726512746f.png)

3. Not able to add the active task in the following scenario

Steps:
1. Add/edit study
2. Go to activities 
3. Click on Add activities
4. Select 'Tower of Hanoi' and again change 'Spacial span memory' to 'Fetal kick counter'
5. Again select 'Tower of hanoi'
6. Enter all the mandatory fields
7. In the Schedule tab, select Regular and daily frequency
8. Click on the Done button and observe

AR: Not able to add the active task, admin will be staying in the Add activity screen after screen loading
ER: Admin should be able to add the active task successfully

**Comment by Lathan-btc** [comment]
@akashkumarv 3rd scenario is reproducible in the latest Dev instance

**Comment by navya-BTC** [comment]
@Lathan-btc can you please test and confirm

**Comment by Lathan-btc** [comment]
@navya-BTC issue is happening randomly in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is not observed in the latest Dev instance

**Comment by akashkumarv3** [comment]
@Lathan-btc please test in QA and update this.

**Comment by Lathan-btc** [comment]
Issue is not observed in the QA instance
