### ISSUE TITLE
[PM] [DEV] Forgot password is not working properly 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4269]
**Steps:**
1. Click on forgot password link in sign in screen.
2. Enter mail in password help screen and Observe.

https://user-images.githubusercontent.com/8600717.9/143412116-5fd370f2-cfe1-4153-8a1e-e262b5493893.mp4

**Comment by DebinJose** [comment]
@bhoomikav16 [PM] [DEV] Forgot password is not working properly #4269 is fixed

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Rashi-395** [comment]
@bhoomikav16 kindly test and close this issue for QA instance.

**Comment by bhoomikav16** [comment]
Issue is not observed in the QA instance
