### ISSUE TITLE
[Android] Issue with the automated notifications

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4270]
When new study is available for the mobile apps,

**AR:**
When clicked on automated notification , navigating to study list screen 

**ER:**
When clicked on automated notification for Enrolled study , Should navigate to activities list screen
When clicked on automated notification for New study, Should navigate to overview screen

**Note:**
Issue also needs to be fixed when new activities are available for the mobile apps

https://user-images.githubusercontent.com/86007179/143416830-9fb32421-3c81-4d00-9aff-af73cd9512ff.mp4

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest android dev build 1.0(137)

**Comment by nishit-v** [comment]
Verified iOS build V3.0(10)

1. New study added notification > App is navigating to the study list screen > it should be navigated to the overview screen of the study

2: Resources added notifications > Participant is navigating to the study activities screen > Participants should be navigated to the resources list screen

3. When study is paused > Participant is navigating to to study list screen but study has been paused popup is getting displayed > Pop up should be displayed only when participant clicks on paused study

**Comment by Lathan-btc** [comment]
1. When the study is paused > Participant is navigating to Activities list screen of the study > Participant should navigate to the Study lists screen
2. Resources notification > if admin clicks on notifications then admin is navigating to the Study lists screen > Admin should be navigated to the Resources of the particular study

**Comment by nishit-v** [comment]
Verified iOS build V3.0.19 for below scenarios and is fixed.

1. When the study is paused > Participant is navigating to Activities list screen of the study > Participant should navigate to the Study lists screen
2. Resources notification > if admin clicks on notifications then admin is navigating to the Study lists screen > Admin should be navigated to the Resources of the particular study

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation 
1. If participants receive any automated notification when a user on the Study activities list screen > then Participant automatically navigate to the particular screen (Ex: If participants receive Resource notification then automatically navigate to the Resource list screen without clicking on the notification)
2. If participants not using the app(the app should not run even though in the background) then if they receive any notification > Click on received notification > then Participant will be in the Mobile home screen 
3. When the study is paused > Participant is navigating to Activities list screen of the study > Participant should navigate to the Study lists screen

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
@Lathan-btc  ,
1st and 2nd scenarios are in progress. We will handel it in 2.11 release.
3rd scenario is resolved please verify.

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation I Have tested 3rd scenario but it is reproducible in the following 
Sign in to the mobile app > Enroll to the study > Navigate to the study list screen > Minimize the app >  In SB, pause the study > After receiving the Paused notification, click on the notification and observe

AR: Participant is navigating to the Paused study activities list screen
ER: Participant should be navigate to the study list screen

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation 
1. Added notifications are not reflected in the notifications list 
2. Close the app > Add resource > after receiving the notification > click on notification > After navigating to the resources screen > Click on home icon > Observe > Admin is navigating to resources screen

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA build 30(40)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA build 1.0(158)

**Comment by Lathan-btc** [comment]
iOS > Once the PR is raised and merged to QA then will close the issue

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance after merging the PR
