### ISSUE TITLE
[Unknown backend] Newly created activities are not getting displayed in 'Study activities' list screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4275]
Steps:
1. I iOS, enroll into the study
2. In SB, configure the activities for the rolled study
3. Publish the updates
4. Go to the mobile app
5. Click on the enrolled study
6. Observe the newly created activities

Issue observed only for the following study

App id: GCPMOB001
Study id: iOSStudyM1
Study name: IOS study

AR: Newly created activities are not getting displayed in the 'Study activities' list screen
ER: newly created activities should be displayed

**Comment by monica-BTC** [comment]
@GovindPrasadBostonTechnologyCorporation studyUpdate API is working as expected from the backend. Please check from IOS end.

**Comment by monica-BTC** [comment]
@nishit-v, Please test this issue and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test and confirm in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
