### ISSUE TITLE
[GCI] [SB] [PM] UI issue in the email dropdown

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4281]
AR: UI issue in the email dropdown.

Note:
1. In Chrome browser,
* There is no scrollbar displayed for the email dropdown. 
* Dropdown icon is getting displayed only when mouse hovered on the field.
* Email text field and dropdown are not aligned properly.
* Outline dropdown is not similar to the other fields.

2. In Firefox browser,
* There is no dropdown icon displayed in the email field.
* Email text field and dropdown are not aligned properly.(Observed only in PM)

In Chrome browser,

![3](https://user-images.githubusercontent.com/86007179/145189691-5f1889c3-b97a-448f-abe7-4f18233e1466.png)

In Firefox browser,
![4](https://user-images.githubusercontent.com/86007179/145190099-91036a2a-00c0-4612-8327-eeb26bf285e7.png)

**Note:** Issue should be fixed in both SB and PM.

**Comment by Madhud5** [comment]
Hi @bhoomikav16 , please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
@Madhud5 Issue is still reproducing in the latest dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check in dev env in PM only  and let me know.
thanks

**Comment by bhoomikav16** [comment]
@Madhud5  Issue is still reproducing in the latest dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check in both PM and SB dev env and let me know.
thanks

**Comment by bhoomikav16** [comment]
@Madhud5 Issue is still reproducing in the latest dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check in both PM and SB dev env and let me know.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by bhoomikav16** [comment]
@harisboston @Madhud5 Issue is still reproducing in Chrome browser
![Screenshot (425)](https://user-images.githubusercontent.com/86007179/159438073-fa131e71-844f-4a22-83ba-143adb8df930.png)

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest Idp branch in dev instance

**Note:** Functionality of email dropdown is working fine and alignment issue of email text and dropdown field is tracked in separate ticket.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest Idp branch in QA instance
