### ISSUE TITLE
[GCI] [SB] [PM] All values in the email dropdown are not getting displayed in the below scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4282]
**Steps:**

1. Login into SB
2. Click on manage admins icon 
3. Click on Add admin button
4. Select any value in the email dropdown
5. Again click on email field and Observe.

**AR:** All values in the email dropdown are not getting displayed for the above scenario
**ER:** All values in the email dropdown should be displayed for the above scenario

**Note:** Issue is observed in the participant manager also for the above steps

**Comment by harisboston** [comment]
@sharathblr Email drop down works like filter when user type email ID, so if user select any email from drop down then it will not show other emails, user need to remove the email to check the other dropdown values.

**Comment by harshith2590** [comment]
The Email dropdown should work like a filter. If the dropdown is working as a filter and letting the user to select the email id then it is a valid flow.

**Comment by bhoomikav16** [comment]
Closing the ticket after confirmation from the BA.
