### ISSUE TITLE
[GCI] [SB] [Email] Issue related to account reactivation mail 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4283]
**Steps:**
1. Add GCI user mail in the SB.
2. Decativate same user in the identity platform.
3. Again reactivate same user in the identity platform.
4. Now again reactivate same user in the study builder.

**AR:** Account reactivation mail is not getting for the GCI user.
**ER:** Account reactivation mail should be sent even for GCI user.

**Comment by harisboston** [comment]
@bhoomikav16 Tested this issue for multiple users, not able to replicate. User: "test123@grr.la"
Kindly test and update this ticket accordingly.

**Comment by bhoomikav16** [comment]
Issue is not reproducible, It will be under observation.

**Comment by bhoomikav16** [comment]
Tested this issue for multiple users, Issue is still not reproducible in the latest dev instance. So closing the issue.
