### ISSUE TITLE
[SB] [GCI] Sign in screen > Entered email id is not displaying in Email id text field when admin clicks on the Sign in button

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4284]
AR: Sign in screen > Entered email id is not displaying in Email id text field when admin clicks on the Sign in button
ER: Email id should be displayed

https://user-images.githubusercontent.com/71445210/145214399-6a399c84-bcba-4147-b467-64cfeb0c4607.mp4

**Comment by Lathan-btc** [comment]
@harisboston After clicking on sign in button > getting 2 loading animators

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance

**Comment by akashkumarv3** [comment]
@Lathan-btc  its fixed now  in dev please test and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
