### ISSUE TITLE
[GCI] [SB] Enforce password change is available for the organizational admins

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4285]
**Steps:**

1. Edit the organizational superadmin to studyadmin and update.
2. Again edit the same admin and Observe.

**AR:** Enforce password change is available for the organizational admins.
**ER:** Enforce password change should not be available for the organizational admins

**Note:** Issue should be fixed when changed studyadmin to superadmin and again to studyadmin .

**Comment by bhoomikav16** [comment]
Issue is still reproducing for old organizational user

**Comment by harisboston** [comment]
@bhoomikav16 Yaah, that's fine, because of a bug, the status of the old admin got changed to non-gci user. Going forward for new admins this issues will not happen.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
