### ISSUE TITLE
[SB] [GCI] Admins screen > Account status toggle button is displayed in green color when account is deactivated in identity platform

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4286]
AR: Admins screen > Account status toggle button is displayed in green color when the account is deactivated in identity platform
ER: The account status toggle button should be displayed in Red color when the account is deactivated

![image](https://user-images.githubusercontent.com/71445210/145218731-d3ac4f97-2f54-4ae9-9a3e-5018e35f32a4.png)

**Comment by harisboston** [comment]
@sharathblr Study builder custom scheduler will update the user status as deactivated when user is deactivated/disabled from GCP console,  within 1 min toggle button will display as green only and after 1 min when super admin refresh the page the toggle button will turn red. 
Please let us know , if it fine or need to update the functionality.

**Comment by harshith2590** [comment]
As we are running the scheduler in every 1 minute after the user is deactivated. So, if the toggle button turns red after completion of a minute, then it's acceptable.

**Comment by Lathan-btc** [comment]
It is working as per the above mentioned comment
