### ISSUE TITLE
[SB][GCI] Edit admin screen > Superadmin is is able to edit the email id of the organizational admin in the SB

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4288]
Steps:
1. Admin should be added to identity platform
2. Add same admin in SB
3. Create an account for the admin
4. Change the permission to super admin/study admin
5. Click on edit admin
6. Try to edit the email id field

AR: Edit admin screen > Superadmin is is able to edit the email id of the organizational admin in the SB
ER: Edit admin screen > email id of the organizational admin should not be editable

![image](https://user-images.githubusercontent.com/71445210/145224856-97b4fe03-c717-487f-b531-54fb29cdb705.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by harisboston** [comment]
@bhoomikav16 Yaah, that's fine, because of a bug, the status of the old admin got changed to non-gci user. Going forward for new admins this issues will not happen.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
