### ISSUE TITLE
[SB] UI issue in the set up your study builder account screen 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4290]
**Steps:**
1. Add admins in the study builder.
2. Click on the link which is sent for the admins mail to set up their account in SB.
3. Select the checkbox in the set up your study builder account screen and again uncheck and Observe.

**ER:** Error message text should be displayed below the text which is displayed beside the checkbox.
![5](https://user-images.githubusercontent.com/86007179/145340379-ae353174-4e73-4122-9a12-1a73ae33c87d.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by Ranjithabtc** [comment]
@bhoomikav16 please test in QA and update this.

**Comment by bhoomikav16** [comment]
@Ranjithabtc 
Wrong error message text is displayed. 
**AR:**
![8](https://user-images.githubusercontent.com/86007179/146178666-0319de8a-7cb2-4559-a540-1ff087ff9179.png)
**ER:**
Please check this box if you want to proceed text should be displayed as a error message

**Comment by Ranjithabtc** [comment]
Okay I'll check this

**Comment by bhoomikav16** [comment]
@Ranjithabtc Issue is fixed only in the latest dev instance.

**Comment by Ranjithabtc** [comment]
@Bhoomika Vasanth ***@***.***> okay thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
