### ISSUE TITLE
[GCI] [SB] Getting failure message for organizational user during their account setup

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4291]
**Steps:**
1. Add organizational user in the SB.
2. Click on the link which is sent for the admins mail to set up their account in SB.
3. Complete all the fields in the set up your study builder account screen.
4. Click on submit button and Observe.

**AR:** Getting failure message for organizational user during account setup.
**ER:** Organizational user should set up their account without any error message.

https://user-images.githubusercontent.com/86007179/145399345-dd34ad4c-d330-45ea-9811-79f76bffc9f4.mp4

**Comment by harisboston** [comment]
@bhoomikav16 This issue was because of restricted access of Identity Platform to Study builder GCP service account. 
It's fixed now.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
