### ISSUE TITLE
[iOS] Back arrow is not available on the top left for the 'Text choice' response type questions

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4298]
The back arrow is not available on the top left for the 'Text choice' response type questions

![image](https://user-images.githubusercontent.com/71445210/145942951-0219d642-38aa-4a4a-85fd-4cab06feaa65.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build 2.0 (54)

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA build V11.1
