### ISSUE TITLE
[Mobile apps] Resources > Page is continuously loading when participant clicks on newly added resource pdf's

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4300]
In iOS > Page is continuously loading

![image](https://user-images.githubusercontent.com/71445210/146004266-7228f717-ae2d-4ba5-b5a4-4516e8510274.png)

In Android > Getting 'App isn't responding' message

![image](https://user-images.githubusercontent.com/71445210/146003989-f6be7add-eb4b-49ba-ad51-7bf3bb34ed8e.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest android dev buid 1.0(134)

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation issue is fixed in the latest ios build 3.0(3)

**Comment by Lathan-btc** [comment]
Issue is fixed in latest QA build 30(35)

**Comment by Lathan-btc** [comment]
@bhoomikav16 check in Android QA build and close if it is fixed

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA build 1.0(154)
