### ISSUE TITLE
 [PM] Submit button is disabled for the admin during their account setup

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4304]
**Steps:**
1. Login into PM.
2. Click on Admins tab.
3. Click on Add admin button.
4. Enter first name by giving space.(eg. Demo User)
5. Complete all the fields.
6. Click on add admin.
7. Click on the link which is sent for the admins mail to set up their account in PM.
8. Complete all the fields in the set up your account screen.
9. Click on submit button and Observe.

**AR:** Submit button is disabled for the admin.
**ER:**  Submit button should not be disabled for the admin.

https://user-images.githubusercontent.com/86007179/146361301-de5f2101-dec8-4f84-9a92-0d8d18b6b017.mp4

**Comment by harisboston** [comment]
@SR-btc Add admin screen there is no validation of space for First name, but validation is there in account setup screen.
Can you please confirm, whether space validation should be added for the first name in add admin screen?

**Comment by aswinijena100** [comment]
test cooment

**Comment by harshith2590** [comment]
It would be better if we allow space in First name and maintain consistency in both Add admin and Account Setup screen. Last Name functionality shall remain as it is now.

**Comment by Rashi-395** [comment]
@bhoomikav16 [PM] Submit button is disabled for the admin during their account setup is completed in latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
