### ISSUE TITLE
[PM] UI issue in the location screen and admins screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4305]
**Steps:**
1. Login into PM
2. Navigate to admins tab and Observe

**AR:**
1.For Location screen

![9](https://user-images.githubusercontent.com/86007179/146380098-a3efe44a-c229-43f6-b6e1-96fdd16ae922.png)

2.For Admins screen

![Screenshot (92)](https://user-images.githubusercontent.com/86007179/146377385-15ca24e9-eaf3-4205-bdff-f2e2e21a8a75.png)
**Note:** 
1. Issue is observed only in the dev instance.
2. Issue is observed in Location screen also.

**Comment by Rashi-395** [comment]
@bhoomikav16 [PM] UI issue in the location screen and admins screen is completed in latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
