### ISSUE TITLE
[SB] Admins are not able to login into the study builder

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4313]
**Steps:**

1. Add user in the SB.
2. Click on the link which is sent for the admins mail to set up their account in SB.
3. Complete all the fields in the set up your study builder account screen.
4. Click on submit button.
5. Now try to login from the same user's registered credentials and Observe.

**AR:** Getting an error message when tried to login into the SB.
**ER:** Admin should be able to login from their registered credentials into the SB.

**Note:**
Issue is observed for both organizational and non-organizational admins

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Ranjithabtc** [comment]
Changes are already deployed in both the environments so please check this issue in both local and dev and please close the ticket.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
