### ISSUE TITLE
[PM] [GCI] Add admins > Pop up > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4314]
UI issues Pop up while adding non-organization admins in Participant manager

1. 'cancel' button text should be changed to 'Cancel'
2. 'confirm' button text should be changed to 'Confirm'
3. Remove cross mark and Upper line present above the text
4. Margins should be present before and after the text 
5. Buttons should be left-aligned on the popup (to maintain consistency across the application)
6. 'Confirm' button should come first and after that 'Cancel' button should be displayed (to maintain consistency across the application)

[Note: Refer 'Edit enrollment target' popup 

![image](https://user-images.githubusercontent.com/71445210/146887497-5b92280c-43ec-480b-a137-d1cd24688fb0.png)

**Comment by Rashi-395** [comment]
@Lathan-btc  [PM] [GCI] Add admins > Pop up > UI issues is fixed in latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
