### ISSUE TITLE
Add Delete event for deleting a study in Study Builder.

### ISSUE THREAD

**Issue by harshith2590** [GoogleCloudPlatform/fda-mystudies#4315]
Kindly add audit log event for the action of deleting a study from the study list in study builder.

https://docs.google.com/spreadsheets/d/1XXiK9-zmvZv_ztsrfJgptIwBl4LKpM74oeoBY8u98ZE/edit#gid=1237915281

**Comment by Lathan-btc** [comment]
@akashkumarv3 Event is not getting triggered

**Comment by akashkumarv3** [comment]
@Lathan-btc issue is fixed .please test and update

**Comment by Lathan-btc** [comment]
The log is getting triggered

**Comment by akashkumarv3** [comment]
@Lathan-btc  Issue is fixed please test and confirm .

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
