### ISSUE TITLE
[PM] UI issue is observed in the below mentioned screens of the dashboard

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4316]
UI issue is observed in the below mentioned screens:
1. Sites > Enrollment registry screen
2. Sites > Participant details screen
3. Study > Enrollment registry screen
4. Study > Participant details screen
5. App > App user registry screen

Issue needs to be fixed in all the above mentioned screens.

**Comment by Rashi-395** [comment]
@bhoomikav16 [PM] UI issue is observed in the below mentioned screens of the dashboard is resolved in latest dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
