### ISSUE TITLE
[SB] Success message is not displayed when deleted the study in the study builder

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4317]
Delete the study in the study builder and Observe.

**AR:**  Success message is not displayed when deleted the study in the study builder.
**ER:**   Success message should be displayed when deleted the study in the study builder.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest DEV build

**Comment by Ranjithabtc** [comment]
Changes are already deployed in both the environments so please check this issue in both local and dev and please close the ticket.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
