### ISSUE TITLE
[iOS] Active tasks > active tasks are configured with the following scheduling type are not getting displayed in the mobile app

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4318]
**Steps:**
1. Log in to SB
2. Click on edit study
3. Go to Active task 
4. Add activity with Regular > onetime with a custom start date and time and by selecting 'Study lifetime' checkbox
5. Publish the updates
6. Go to mobile app
7. Click on a particular study
8. Observe the added activity on the 'Study activities' list screen

**AR:** Configured activity with above mentioned scheduling type  is not getting displayed in the mobile app
**ER:** Activity should be displayed in the 'Study activities' screen 

**Note:** 
1. Issue not observed for anchor date based active tasks and questionnaires
2. Issue not observed in Android

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
The following is the response we are getting from backend for the activity with Regular > onetime with a custom start date and time and by selecting 'Study lifetime' checkbox. 
The one mentioned 'CORRECT' is that of type questionnaire and the one that is mentioned 'WRONG' is that of a type task for startTime parameter.

({
    activities =     (
                {
            activityId = a1;
            activityVersion = "1.0";
            anchorDate =             {
                end =                 {
                    anchorDays = 0;
                    repeatInterval = 0;
                    time = "";
                };
                sourceActivityId = "";
                sourceFormKey = "";
                sourceKey = "";
                sourceType = "";
                start =                 {
                    anchorDays = 0;
                    dateOfMonth = "";
                    dayOfWeek = 0;
                    time = "";
                };
            };
            branching = 0;
            endTime = "";
            frequency =             {
                anchorRuns =                 (
                );
                runs =                 (
                );
                type = "One time";
            };
            isLaunchStudy = 0;
            isStudyLifeTime = 1;
            lastModified = "2022-01-17T11:24:00.000+0000";
            schedulingType = Regular;
            startTime = ""; ===(WRONG)
            state = active;
            taskSubType = fetalKickCounter;
            title = a1;
            type = task;
        },
                {
            activityId = q1;
            activityVersion = "1.0";
            anchorDate =             {
                end =                 {
                    anchorDays = 0;
                    repeatInterval = 0;
                    time = "";
                };
                sourceActivityId = "";
                sourceFormKey = "";
                sourceKey = "";
                sourceType = "";
                start =                 {
                    anchorDays = 0;
                    dateOfMonth = "";
                    dayOfWeek = 0;
                    time = "";
                };
            };
            branching = 0;
            endTime = "";
            frequency =             {
                anchorRuns =                 (
                );
                runs =                 (
                );
                type = "One time";
            };
            isLaunchStudy = 0;
            isStudyLifeTime = 1;
            lastModified = "2022-01-17T11:25:04.000+0000";
            schedulingType = Regular;
            startTime = "2022-01-17T21:54:00.000+0000"; ===(CORRECT)
            state = active;
            taskSubType = "";
            title = q1;
            type = questionnaire;
        }
    );
    message = SUCCESS;
})

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test by adding new Activity for the above scenario in SB and confirm this issue in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test and confirm in QA

**Comment by monica-BTC** [comment]
@Lathan-btc please test and confirm in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
