### ISSUE TITLE
[FHIR] Json file > Time stamp should be local time 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4321]
AR: JSON file > Timestamp: Server time is getting displayed
ER: JSON file > Timestamp: It should display the local time for the following keys
1. authored
2. lastUpdated

![timestamp-json](https://user-images.githubusercontent.com/71445210/147337622-99ead721-346e-4c7d-8027-b205d50edd2b.png)

**Comment by madhurya-btc** [comment]
Please add "submittedTime" key for the response submitted by the participant. @naveenr-btc  @GovindPrasadBostonTechnologyCorporation

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance. Please check in the latest build of Android and IOS.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest builds

Android: V1.0(134)
iOS: Build version is 2.0(61)

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation FHIR enhancement is not present in QA instance, till then not able to test this issue.

**Comment by bhoomikav16** [comment]
Issue is fixed in the both Android and iOS latest QA builds
