### ISSUE TITLE
[FHIR] Unable to submit the responses for all the activities

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4325]
Unable to submit the responses for all the activities

**AR:**  The activity will be in 'Resume' status if the participant clicks the Done button on the 'Activity completed' screen 
**ER:** Participant should be submitted the response successfully and activity should be in 'Completed' status

**Comment by Lathan-btc** [comment]
Issue is reproducible only for the following response types

1. Question step > Scale
2. Question step> Numeric

**Comment by aswinijena100** [comment]
@Lathan-btc Please test and close if fixed. This was due to deployment , so no PR needs to be raised for the same.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest deployment

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest FHIR deployment

**Comment by Lathan-btc** [comment]
@madhurya-btc issue is reproducible in the latest Deployment of FHIR

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc @navya-BTC Issue is reproducible in the latest deployment

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in both Dev and FHIR branches.
