### ISSUE TITLE
[SB] Created app is not getting displayed in the app list screen for the study admins

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4333]
**Steps:**

1. Add study admin in the study builder by giving create app permission.
2. Login as study admin.
3. Click on manage app icon.
4. Click on create app button.
5. Create an app and Observe.

**AR:**  Created app is not getting displayed in the app list screen.
**ER:** Created app should be displayed in the app list screen.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in Dev instance.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
@madhurya-btc Issue is still reproducing in the latest QA instance

**Comment by madhurya-btc** [comment]
@bhoomikav16 There was a deployment issue, please check now in QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
