### ISSUE TITLE
[SB] [GCI] Issue related to alert popup message while adding non-organizational users as study builder admin 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4338]
**Steps:**

1. Add admin screen > Complete all the fields in the add admin screen other than phone number field.
2. Click on Add button .
3. Alert popup message is getting displayed > Click on Ok button > Now field validation message is getting displayed for the phone number
4. Again click on Add button and Observe.

**ER:** Alert popup message should be dispalyed once all the fields are completed in the add admin screen while adding non-organizational users as study builder admin

**Comment by harisboston** [comment]
@bhoomikav16 
1) As per GCI requirement, alert message will display only when super admin tries to add non-gci user. This alert/validation is only associated with email field.

2) "required" field validation will happen once user submit the complete form.
If any field is empty then it will show respective error message.
I guess you can close this issue, or let me know if any changes required.
Thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
