### ISSUE TITLE
[Mobile apps] Unable to sign in with registered credentials in the mobile apps

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4347]
For some of the users > Unable to sign in with registered credentials in the mobile apps.

Can refer the below mentioned user:
bhoomikav@boston-technology.com

 Getting error message only in android as in the below screenshot
![1](https://user-images.githubusercontent.com/86007179/148186985-676b7a43-361d-4e38-99d2-1c5673850e2c.png)

**Comment by aswinijena100** [comment]
@nagarjunav1 @bhoomikav16 is this issue still happening ?

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
