### ISSUE TITLE
[Mobile Apps] UI issue in the sign in screen of the mobile apps

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4349]
UI issue is observed in the sign in screen of the mobile apps (Refer the screenshot attached)

**Note:** Issue should be fixed for both Android and iOS mobile apps

![6](https://user-images.githubusercontent.com/86007179/148215674-d7a80864-c76d-41ef-8bde-577e659d8ea4.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16, please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the android mobile app.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by harisboston** [comment]
@bhoomikav16  issue is fixed in QA environment

**Comment by bhoomikav16** [comment]
@harisboston  Issue is reproducing in QA instance
![qa1](https://user-images.githubusercontent.com/86007179/160778111-1f80f22c-176d-4b7b-850b-8d4ad491dbba.png)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance

**Comment by harisboston** [comment]
@Lathan-btc This issue is fixed in QA environment

**Comment by bhoomikav16** [comment]
@harisboston 
Copy right text is not center aligned in sign in screen in QA instance

![screenshot](https://user-images.githubusercontent.com/86007179/164169264-741080ac-bb3f-47f2-ade2-3d56754214a4.png)
