### ISSUE TITLE
Mention version supported 

### ISSUE THREAD

**Issue by naveenr-btc** [GoogleCloudPlatform/fda-mystudies#4351]
Mention version supported for both iOS and android anywhere in the document.

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello team, 
The version supported is mentioned in readme file - https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/iOS/README.md 
We can close this issue.

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Took BA confirmation for the above.
