### ISSUE TITLE
[SB] Add or edit active tasks > Activity short title or key > Text field length should be increased

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4354]
Active tasks > Activity short title or key > Text field length should be increased same as an above dropdown field

![image](https://user-images.githubusercontent.com/71445210/148775773-1b10cf1c-a805-4cb6-8a4b-ed6ec369dd06.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by monica-BTC** [comment]
@Lathan-btc , please test and confirm in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
