### ISSUE TITLE
[SB] [Copy][Overview] Sequence of overview pages is not same in original and copied studies

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4355]
Scenario 1:- 
1. Launch/Publish a study with 2 study overview pages.
2. Import the study on either same server or different server.
3. In the imported study add 2 or more overview pages.
4. Copy the imported study into a new study.
5. Check the sequence of overview pages

Scenario 2:- 
1. Launch/Publish a study with 5 study overview pages.
2. Import the study on either same server or different server.
3. In the imported study delete last 2 overview pages, mark as complete, now add 2 overview pages again.
4. Copy/clone the imported study.
5. Check the sequence of overview pages in the copied study

A/R:- Recently  added pages are displaying on top and old pages in the bottom
E/R:- Overview pages should be in the same sequence from the Original study in both copy/import scenarios

Overview pages in original study
![image](https://user-images.githubusercontent.com/60500517/148928602-3f1a7b5e-de70-465e-90d9-1559c3e93382.png)

Overview pages in Copied study
![image](https://user-images.githubusercontent.com/60500517/148928418-2bef15a7-638d-4065-b0ce-a761b43bd59d.png)

**Comment by monica-BTC** [comment]
@nagarjunav1, Please test and confirm this issue in dev

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by monica-BTC** [comment]
@nagarjunav1, please test and confirm in QA

**Comment by nagarjunav1** [comment]
Issue is fixed in the latest QA build
