### ISSUE TITLE
[SB] Questionnaires > Validation message is displayed on trying to launch/publish the study in a below scenario

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4358]
Scenario 1: Validation message is displayed on trying to publish updates for the study in a below scenario

Steps:
1. Create a study
2. Create a questionnaires > OneTime schedule with 'Launch with study' enabled and 'Study Lifetime'/or custom end date
3. Enter rest of the sections and launch study
4. Wait for at least 1 day 
5. Edit the study
6. Copy the above questionnaire
7. Change schedule from Regular Onetime to Anchor based onetime. Enter X days and time and Y days/study lifetime
8. Enter Rest of the sections
9. Try to publish updates
10. Observe the validation message

A/R: Validation message is displayed on trying to publish updates

E/R: Validation message should not be displayed on trying to publish updates if all activities are configured in future

Refer video attached

https://user-images.githubusercontent.com/60386291/149284141-154641fc-b1f8-4709-9fd2-c30fac9de944.mp4

--------------------------------------------------------------------------------------------------------------------------------
Scenario 2: Validation message is displayed on trying to launch copied/imported study in a below scenario

Steps:
1. Create a study
2. Create a questionnaires > OneTime schedule with 'Launch with study' enabled and 'Study Lifetime'/or custom end date
3. Enter rest of the sections and launch study
4. Wait for at least 1 day 
5. Copy or import the study. Edit the study
6. Change schedule from Regular Onetime to Anchor based onetime. Enter X days and time and Y days/study lifetime
7. Enter Rest of the sections
8. Try to launch study
9. Observe the validation message

A/R: Validation message is displayed on trying to launch copied/imported study

E/R: Validation message should not be displayed on trying to launch copied/imported study if all activities are configured in future

1. Issue not observed for Active tasks

Study ID - studyidnew12345
Instance - Dev

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by akashkumarv3** [comment]
@nishit-v  Issue is fixed please test  in QA and confirm this.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
