### ISSUE TITLE
[SB] Import > JPEG format images uploaded in a study fails to import 

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4359]
Steps:
1. Edit a study
2. Upload images with JPEG format in thumbnail/overview/response types which support images
3. Publish updates
4. Export the study
5. Import the study in a different environment or same environment
6. Observe

Actual: JPEG format images uploaded in a study fails to import 

Expected: JPEG format images uploaded in a study should be imported

Note:
Issue not observed for copied study
Issue not observed for JPG/PNG format
![Screenshot_1](https://user-images.githubusercontent.com/60386291/149293259-ee8ac126-cb98-40a9-bdd6-962b755b2693.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in Dev instance

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
