### ISSUE TITLE
[SB] Active task > Deleted Active task again getting displayed in the active task section

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4363]
**Steps:**
1. Edit the study.
2. Navigate to Active task section.
3. Delete the active task.
4. Refresh the page and Observe.

**AR:**  Deleted Active task again getting displayed in the active task section.
**ER:**  Deleted Active task should not be displayed in the active task section.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
