### ISSUE TITLE
[Consent API] Issue related to consentArtifacts get method API.

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4365]
Getting permission denied error when executed consentArtifacts get method API in the google cloud console.

**Note:** Issue is not happening frequently.
![111](https://user-images.githubusercontent.com/86007179/149504523-667d60e8-4618-4ed5-935e-9f67f1f6ebeb.png)

**Comment by navya-BTC** [comment]
@bhoomikav16 please test this issue and confirm

**Comment by bhoomikav16** [comment]
Issue is fixed, Not getting error when executing the consentArtifacts get method API.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
