### ISSUE TITLE
[SB][Form step] Information text is not displayed when user mouse hover on the tool tip

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4368]
Steps:- 
1. Login into SB
2. Navigate to studies 
3. Add/Edit the study and Navigate to Questionnaires
4. Add/Edit the Questionnaire and Add a Form step
5. Add a form question with response types scale/ Continuous scale and mouse hover on the tool tip for image upload 
6. Observe the behavior as shown in attached video

A/R:- Information text added is not displaying for the tool tips
E/R:- Information text added should be displayed for the tool tips

https://user-images.githubusercontent.com/60500517/149777359-c4b419dd-1dd6-4d46-affb-af0f65f53463.mp4

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by akashkumarv3** [comment]
@nagarjunav1 Issue is fixed in QA  please test and confirm this .

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
