### ISSUE TITLE
[DID] Location is not getting de-identified

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4372]
Location is not getting de-identified

![image](https://user-images.githubusercontent.com/71445210/149908396-a3b371ab-d7f3-4994-be14-c0c081046c07.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test and confirm this issue in FHIR branch

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest FHIR deployment

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
