### ISSUE TITLE
[Consent API] Enrolled time is getting displayed wrongly in consent list method

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4374]
**AR:** Enrolled time is getting displayed wrongly in consent list method.
**ER:** Enrolled time should be displayed correctly in consent list method.

**Note:**  
1. Issue is observed in both primary and data sharing consent.
2. Issue needs to be fixed even for revisionCreateTime

* In primary consent.
![3](https://user-images.githubusercontent.com/86007179/149937259-996a75fd-7ecb-4fda-b611-64cb90bb0f4a.png)
* In data sharing consent.
![Untitled](https://user-images.githubusercontent.com/86007179/149937376-0bc70c6a-aa49-4f34-bba2-d31dcce2c9f9.png)
* In revisionCreateTime
![Capture1](https://user-images.githubusercontent.com/86007179/150330037-2d0dafbf-1573-4f4a-8ec0-18b25f176688.PNG)

**Comment by navya-BTC** [comment]
@bhoomikav16 
- The `Enrolled time` is taking a `server time` That's why there is a difference between `Enroll time` and local time.
- The `revisionCreateTime ` is a API level key. we are not creating `revisionCreateTime `.

**Comment by bhoomikav16** [comment]
@SR-btc  Could you please update as per the above comments?
