### ISSUE TITLE
[Consent API] [Mobile Apps] Unable to withdrawn from the study in the mobile apps

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4376]
**Steps:**
1. Enroll into the study.
2. Submitting response or without submitting any response, Click on Leave study and Observe.

**Note:** 
1. Unable to deactivate the app also
2. Can refer below study name to enroll in the mobile apps:
* demo_test_on_consent
* Copy of demo_test_on_consent
* CONSENT_1

**AR:** Getting error as attached in the below screenshots.
1. 
![Screenshot_20220118-110738_FDA MyStudies](https://user-images.githubusercontent.com/86007179/149957030-0429a9ee-d8c5-420e-b16d-c260c460912b.jpg)

2.
![Screenshot_20220118-201727_FDA MyStudies](https://user-images.githubusercontent.com/86007179/149965555-2f7286a9-903a-4736-8605-dcc48a226de1.jpg)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance builds.
