### ISSUE TITLE
iOS > Create passcode screen is displayed twice after signup/login in below scenario

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4377]
**Steps:**

1. Login/Signup
2. Create passcode screen is displayed
3. Kill and relaunch the app
4. Create passcode screen is displayed
5. Enter passcode
6. Observe create passcode screen is again displayed

**Actual:** Create passcode screen is displayed twice after signup/login in below scenario

**Expected:** Create passcode screen should be displayed only once

**Refer video:**

https://user-images.githubusercontent.com/60386291/150069335-f171708a-16b6-479f-8242-c4001d2bd764.MOV

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0.5

**Comment by financce** [comment]
Hi guys, can you help me with this problem? Maybe when you installed this project first time, have the same problem?
https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4369

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V30.35
