### ISSUE TITLE
[DID] 'linkid' and 'text' are getting de-identified

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4378]
'linkid' and 'text' are getting de-identified when the admin configure the activity id and name with the following in the Study builder

Activity id and name: dated, timeff

![image](https://user-images.githubusercontent.com/71445210/150072379-936ec47a-8a7f-46d2-b9d5-7ee0f5c2a144.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest FHIR deployment

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
