### ISSUE TITLE
[SB][Copy][Import] Branching logic mismatch for Questionnaire with text choice questions

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4379]
Steps :- 
1. Login into SB
2. Navigate to manage studies 
3. Create/Edit the study
4. Navigate to Questionnaires and Add/Edit a Questionnaire
5. Create 3 question steps Q1, Q2, Q3 (of response type text choice) for that Question.
6. Apply branching to the questionnaire.
7. In all Question steps, select a value (other than "select") in destination step dropdown (on response level attributes tab) and mark done.
8. Now in Q1, in destination step dropdown choose "select" and mark done.
9. Clone the study and observe destination step values in all the Question Steps.

A/R:- Destination step values are mismatching between Original and cloned study
E/R:- Destination step values should be same in between Original and cloned study

Note:- Issue should be fixed for both Copy and Import scenarios

Question steps added for Questionnaire
![image](https://user-images.githubusercontent.com/60500517/150097220-6ce68d39-46f7-4622-8886-ab5dde79e9cf.png)

Destination step for text choice options (Response level attributes)
![image](https://user-images.githubusercontent.com/60500517/150097501-e8af7642-8007-4664-aee8-c9cb178c7ac0.png)

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in dev instance

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
@madhurya-btc Issue is reproducible for the copied study in the latest QA instance 

![image](https://user-images.githubusercontent.com/71445210/151967810-8840c93b-a508-42f2-9d31-5d2bdbe30b9c.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc There was a deployment issue, please check now in the QA instance

**Comment by Lathan-btc** [comment]
@madhurya-btc Issue is reproducible for the imported studies in the latest QA instance

[Note: For the 2nd question selected value from the dropdown is not getting displayed]

![image](https://user-images.githubusercontent.com/71445210/152123299-bca4b2da-a790-4f09-90fe-5c7e53e354b5.png)

**Comment by Lathan-btc** [comment]
@madhurya-btc i have updated the steps, please check.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in a dev instance

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by madhurya-btc** [comment]
@nagarjunav1 Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
