### ISSUE TITLE
 [GCI] [SB] [PM] UI Issue in the reCapthcha pop up message in the sign in screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4383]
UI Issue is observed in the recaptcha popup message in the sign in screen.

**In SB,**
![bb](https://user-images.githubusercontent.com/86007179/150544116-c9f197bf-4a86-4c6a-953e-c2c3ece2be84.png)

**In PM,**
![qq](https://user-images.githubusercontent.com/86007179/150795164-f9eeef3b-a17b-4904-b571-5220774136e1.png)

**Comment by bhoomikav16** [comment]
@fahad-kc / @fahadbtc-zz /  Please provide proper UI for the sign in screen

**Comment by harisboston** [comment]
@bhoomikav16 As discussed with @fahad-kc , reCaptcha should be center aligned with sign-in button.
PM reCaptcha was already center aligned, we updated Study builder reCaptcha only.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
