### ISSUE TITLE
[IDP] [SB] [PM] UI Issue in the verification code popup message of the phone number in the sign in screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4384]
UI Issue is observed in the "Please enter the verification code that was sent to your mobile device." pop up message in the sign in screen

In SB,
1. There is no space between "Please enter the verification code that was sent to your mobile device." and the textbox.
2. Text box which is present in the pop up message is center alligned.
3. Colour of the text present in the pop up message.
4. Allignment issue even in the reference value showed when clicked on text box.
5. Allignment issue in the pop up message.

![mn](https://user-images.githubusercontent.com/86007179/150550074-d592231b-01ee-4cde-9b6f-135ae718d6d0.png)

In PM,
1. There is no space between "Please enter the verification code that was sent to your mobile device." and the textbox.
2. Buttons should be left-aligned on the popup (to maintain consistency across the application)
3. Allignment issue in the pop up message.
4. 'OK' button should come first and after that 'Cancel' button should be displayed (to maintain consistency across the application)

![12](https://user-images.githubusercontent.com/86007179/150793601-d5ff92ab-cf5c-4605-abe0-bbe01b7bf924.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16, please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
@Madhud5  Issue is reproducing in the latest dev instance

**Comment by bhoomikav16** [comment]
@Madhud5  
The popup message should be aligned similar to the other fields in Sign in screen

![1](https://user-images.githubusercontent.com/86007179/159908008-00c88517-b557-424e-9167-57a18c7e2f8f.png)

**Comment by bhoomikav16** [comment]
This issue will be tested once mfa is enabled in the both SB and PM

**Comment by Madhud5** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
Issue is reproduciable for SB and will test in PM once https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4686 is fixed

**Comment by bhoomikav16** [comment]
Issue is reproduciable in both SB and PM

**Comment by madhud-btc** [comment]
Hi @Lathan-btc please check and close this ticket.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest IDP branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP QA branch
