### ISSUE TITLE
[Consent API] [PM] Participant Details > Consent History > Recent version should be displayed on top(first row)

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4388]
**AR:**  Recent consent pdf (same version or different versions) is displaying in last row
**ER:**  Recent consent pdf (same version or different versions) should be displayed on first row
![Screenshot (914)](https://user-images.githubusercontent.com/86007179/150731280-a272957b-836e-4232-b5f0-186239a677c6.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by bhoomikav16** [comment]
Issue is reproducing in the latest dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
