### ISSUE TITLE
[GCI] [PM] UI issue in the sign in screen when entered invalid credentials

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4390]
UI issue is observed in the sign in screen when entered invalid credentials.

![1m](https://user-images.githubusercontent.com/86007179/150780135-cf1203a7-402c-4389-89c4-329ad3545dde.png)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

![idp1](https://user-images.githubusercontent.com/86007179/171400065-279deeea-629e-4161-8baf-9d6ec740ba33.png)

**Comment by akashkumarv3** [comment]
@bhoomikav16 Issue is now fixed in dev ,please test and update.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
