### ISSUE TITLE
[DID] Some of Locations and Names are not getting de-identified

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4395]
Some of the Locations and Names are not getting de-identified
Eg: America etc...

![image](https://user-images.githubusercontent.com/71445210/151390116-0b1f83c9-4731-426b-977f-03a77ad86688.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, De-identification API is not detecting these values as PII. Please close this issue.
