### ISSUE TITLE
[SB] Active tasks > Functionality of Save and Done buttons is not working properly  for the following scenarios

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4396]
Scenario 1

Steps:
1. Login to SB
2. Click on add/edit study
3. Go to active tasks 
4. Click on Add activity
5. Enter all the required fields
6. Click on the Save button
7. Click on the Done button
8. Observe

AR: Active tasks are getting saved in the draft
ER: Active tasks should not be saved in the draft

Scenario2

Steps:
1. Login to SB
2. Click on add/edit study
3. Go to active tasks 
4. Click on Add activity
5. Enter all the required fields
6. Click on the Done button
7. Click on edit activity
8. Click on Save button
9. Go back to the Active tasks list screen
10. Observe

AR: Active tasks are not getting saved in the draft
ER: Active tasks should be saved in the draft

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by akashkumarv3** [comment]
@Lathan-btc Issue is fixed please test in QA and confirm this .

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
