### ISSUE TITLE
[Android][iOS] Inconsistent study order between Android and iOS for study list

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4398]
Steps:- 
1. Login into the mobile apps (Gateway)
2. Navigate to Study list 
3. Compare the study order in the list between Android and iOS

A/R:- Inconsistency between Android and iOS platforms for study order
E/R:- Consistency should be maintained between the platforms for study order

**Comment by naveenr-btc** [comment]
Android displays the list order with the same order that comes in api.

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
In iOS studylist, we are first displaying the studies in following order - active, paused and closed.
 Amoung the active studies, we are first displaying the studies in following order - enrolled, yetToEnroll, completed, withdrawn, notEligible. 
 The studies is the above all types of the ordering we are again arranging in the ascending order of the name of study.

**Comment by sharathblr** [comment]
Had discussion with Android and iOS team , per discussion we will be making changes to Android and we will follow the implementation of iOS. Android team to check and make the necessary changes to match iOS ordering

**Comment by bhoomikav16** [comment]
Issue is still reproducing for the following scenario,



**AR:**
1. For active studies, order is getting displayed as, enrolled, yetToEnroll, notEligible.  withdrawn and again notEligible. 
2. For paused studies , Inconsistent order is observed

**ER:** 
Active/Paused/Closed studies, should be displayed in the following order - enrolled, yetToEnroll, completed, withdrawn, and notEligible.

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev build

**AR:**
1. The studies are not arranged in the ascending order of the name of study 
2. For paused studies, order is getting displayed as, enrolled, withdrawn, yetToEnroll, enrolled, and notEligible 

**ER:**
1. Active/Paused/Closed studies, should be displayed in the following order - enrolled, yetToEnroll, completed, withdrawn, and notEligible. 
2.   The studies should be arranged in the ascending order of the name of study

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev build 1.0(174)

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
