### ISSUE TITLE
[iOS] [FHIR] Responses are not getting submitted in the standalone app (Build Version v3.0.13)

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4413]
Responses are not getting submitted in the standalone app (Build Version v3.0.13)

Study id: Standalone(ios)
App id: NS001

**Comment by Lathan-btc** [comment]
Issue is happening only for the specific study

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance. Please check for new studies.

**Comment by Lathan-btc** [comment]
Issue is fixed for the newly created studies

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.189
