### ISSUE TITLE
[SB] [Safari] Add/edit study > Questionnaires > Question step/from step > Scale and continuous scale > Response level attributes > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4416]
Add/edit study > Questionnaires > Question step/from step > Scale and continuous scale > Response level attributes > UI issue > Text field name is getting displayed in 2 lines

![image](https://user-images.githubusercontent.com/71445210/152357874-1f518f87-836e-436e-bee0-fe99c1e42436.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc  , please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment]
@Madhud5 'Maximum fraction digits' field alignment is not proper for continuous scale

[Note: It is happening in all browsers after fixing the above mentioned UI issue]

![image](https://user-images.githubusercontent.com/71445210/153868079-e90af728-b83b-4455-88a4-456ae60bf933.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check in dev env and let me know.
thanks

**Comment by Madhud5** [comment]
Hi @Lathan-btc , please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment]
@Madhud5 Length of the 'Max fraction digits' field is more 

![image](https://user-images.githubusercontent.com/71445210/155343195-2d626cbb-851f-41b4-8af6-569b36c89114.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check in dev env and let me know.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue and let me know.
thank you

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
