### ISSUE TITLE
[SB] Edit admin screen > UI fixed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4421]
Steps: Edit admin screen > UI fixed
1. Login to SB
2. Click on Admins
3. Add 'Study admin' by selecting some of the apps and studies and add the admin successfully
4. Again click on edit admin
5. Again add some more apps and studies

![image](https://user-images.githubusercontent.com/71445210/152830974-fde63685-8b80-4408-b05a-46da8d48be02.png)

[Note: Issue is fixed for both Studies and apps]

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
