### ISSUE TITLE
[SB] Active task > Anchor date > UI issue is observed in the custom scheduling type

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4425]
**Steps:**
1. Edit the study.
2. Navigate to active task section.
3. Add / Edit the active task.
4. In schedule tab, select Anchor date custom scheduling type.
5. Click on plus icon and Observe.

**AR:**  Fields are not properly alligned for Anchor date custom scheduling type.
**ER:**  Fields should be properly alligned.

**Note:** Issue should be fixed for both questionnaires and active task.
![lk](https://user-images.githubusercontent.com/86007179/153131119-5e171717-2f21-4519-b124-c671482e70c0.png)

**Comment by monica-BTC** [comment]
@bhoomikav16, please test and confirm in dev.

**Comment by monica-BTC** [comment]
@bhoomikav16, please test and confirm

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by monica-BTC** [comment]
@bhoomikav16, please test and confirm in QA

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
