### ISSUE TITLE
[SB] UI issue is observed in the eligibility screen in the below scenario 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4429]
**Steps:**
1. Edit the study.
2. Naviagte to eligibity section.
3. Navigate from Token validation radio button to Token validation and eligibility test radio button as similar to the attached video and Verify

**AR:** Unwanted line is getting dispalyed for the above scenario.
**ER:** Unwanted line should not get displayed.

**Note:** Issue needs to be fixed when navigated from Eligibility test also.

https://user-images.githubusercontent.com/86007179/153192041-cd15116f-b609-4f88-ae2f-e510df55df62.mp4

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check in dev env and let me know.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by Madhud5** [comment]
Hi @bhoomikav16  please check this issue and let me know.
thank you
