### ISSUE TITLE
[PM] Responsive issue > Customer logo is not getting dispalyed in the forgot password help screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4432]
Responsive issue,

**AR:** Forgot password screen > Customer logo is not getting dispalyed in the forgot password help screen.
**ER:** Forgot password screen > Customer logo should get dispalyed in the forgot password help screen.

![w](https://user-images.githubusercontent.com/86007179/153371471-17f9e7c7-db49-4797-92f5-84955d07724f.png)

**Note:** Issue needs to be fixed even in About and Terms of service screen also

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check in dev env and let me know.
thanks

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is reproducible in the latest Dev instance

[Note: Issue should also be fixed in the error pages ]

![image](https://user-images.githubusercontent.com/71445210/155123096-404dd1f3-92bd-4917-a84d-9344c70127c3.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc , please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment]
@Madhud5 Password help screen > logo is not getting displayed when screen size set between above 500px and below 1020 (including 768px)

![image](https://user-images.githubusercontent.com/71445210/155307396-aec69849-f07a-407c-8267-1870d4c7a030.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment]
issue is fixed in the latest Dev instance

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
