### ISSUE TITLE
[PM] Responsive issue > Customer Logo is getting displayed twice when the width of the device is small

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4433]
Customer Logo is getting displayed twice when the width of the device is small

![2](https://user-images.githubusercontent.com/86007179/153395488-b344c869-694b-44a5-9a33-e05d8e450498.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check in dev env and let me know.
thanks

**Comment by Madhud5** [comment]
Hi @bhoomikav16  please do check like device vise like 1920px,1280px, 768px,320px like this. and let me know.
don't check below 320px.

**Comment by bhoomikav16** [comment]
As per the above comment, Issue is fixed in the latest dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16  please check this issue and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
