### ISSUE TITLE
[PM] Responsive issue > UI Issues in My account screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4434]
In My account screen,

**AR:** There is no space between Update and Cancel buttons.
**ER:** There should be some space between Update and Cancel buttons.

![u](https://user-images.githubusercontent.com/86007179/153402681-a62ed15d-8371-4023-b51d-5575cbd68b15.png)

**Note:** Issue is observed in iPhone 12 Pro device

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is reproducible for the 'Galaxy fold' device

1. Buttons are overlapped
2.  There are no margins between the application screen and the device edges

![image](https://user-images.githubusercontent.com/71445210/155122058-7d92cec1-da93-4200-8d96-30357236fb2f.png)

**Comment by Madhud5** [comment]
Hi @latha please be check UI from 320px to 1920px only. not below 320px.

**Comment by Lathan-btc** [comment]
As per the above comment, it is working fine in the devices which has 320px and more than 320px.

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
