### ISSUE TITLE
[PM] Responsive issue > UI issue in study participant registry, app user registry  and location screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4438]
UI issue is observed in,

1. Study participant registry screen.

![k3](https://user-images.githubusercontent.com/86007179/153435417-29af8a70-4d5c-402e-b313-0b92bbbec08d.png)

2. App user registry screen.

![k2](https://user-images.githubusercontent.com/86007179/153435488-dab893a3-4085-4a66-82fb-814d858cdc25.png)

3. Location screen.

![k1](https://user-images.githubusercontent.com/86007179/153435548-56db38f5-26fb-4e96-a7f0-d551abcd4d93.png)

Note: Issue is observed in iPad Air device

**Comment by Madhud5** [comment]
Hi @bhoomikav16  please check this issue in dev and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue and let me know.
thank you

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
