### ISSUE TITLE
[SB] Eligibility section can not be marked as complete in the below scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4446]
**Steps:**
1. Edit the study.
2. Naviagte to eligibility section.
3. In token validation > Remove the instruction text and then click on save button.
4. Now navigate to eligibility test > add eligibility test questions.
5. Click on mark as complete button and Observe.

**AR:** Eligibility section can not be marked as complete in the above scenario.
**ER:** Eligibility section should be marked as complete in the above scenario.

**Comment by monica-BTC** [comment]
@bhoomikav16, please test and confirm in dev

**Comment by bhoomikav16** [comment]
@monica-BTC  Issue is fixed in the latest dev instance

**Comment by monica-BTC** [comment]
@Lathan-btc , Please test and confirm in QA

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
