### ISSUE TITLE
[SB] Questionnaires > Form step > 'Anchor date' cannot be used when questions are added with 'Repeatable' type of form

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4448]
AR: Admin can use anchor date option for the questions which are added with 'Repeat form' option
ER: Admin should not be able to use Anchor date, charts, and statistics when questionnaires are created with the 'Repeat form' option

**Comment by monica-BTC** [comment]
@Lathan-btc, the error message will be shown when the user selects 'Use response as anchor date'. Please test and update the ticket.

**Comment by Lathan-btc** [comment]
@monica-BTC 
1. As per the above comment, it is working fine
2. Change the validation message to 'The following attributes/properties cannot be used with questions that are added to a 'repeatable' type of form: Use response as anchor date, chart for app dashboard, statistic for app dashboard.

![image](https://user-images.githubusercontent.com/71445210/154500871-ef9eebf7-bea9-4043-8cf7-83ec6271137f.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm in Dev

**Comment by monica-BTC** [comment]
@Lathan-btc, Please test and confirm in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
