### ISSUE TITLE
[SB] Questionnaires > Issues in Anchor date custom scheduling type

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4450]
**Steps:**
1. Edit the study.
2. Navigate to Questionnaires section.
3. Add / Edit the Questionnaires.
4. In schedule tab, select Anchor date custom scheduling type.
5. Click on plus icon and Observe.

**AR:** 
1. Alignment issue is observed in the Anchor date custom scheduling type.
2. Validation message is not getting displayed for all the fields when clicked on 'Done' button.

**ER:** 
1. Alignment issue should be fixed for Anchor date custom scheduling type.
2. Validation message should get displayed for all the fields when clicked on 'Done' button.

**Note:**
1. Alignment issue is observed only in Questionnaires section.
2. Validation message should be fixed for both questionnaires and active task section.

![1](https://user-images.githubusercontent.com/86007179/154253410-e9a26448-aff7-4c03-a7db-3130025da9b9.png)
![2](https://user-images.githubusercontent.com/86007179/154254282-a9ce35f7-25d8-4288-beab-9b9bd8be7d66.png)

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in the dev instance.

**Comment by bhoomikav16** [comment]
@madhurya-btc  Allignment issue is still reproducing in Questionnaires section
![f](https://user-images.githubusercontent.com/86007179/154704550-f1f9e0dd-53d9-4001-95fa-960f796bbfe6.png)

**Comment by madhurya-btc** [comment]
@bhoomikav16 please test and confirm in Dev instance

**Comment by bhoomikav16** [comment]
@madhurya-btc 
Validation message is not getting displayed for all the fields when clicked on 'Done' button. Issue is reproducing for both questionnaires and active task section.
![m](https://user-images.githubusercontent.com/86007179/155130105-b83ec233-e9c2-4487-9d91-5cab1e7c8d6c.png)

**Comment by harisboston** [comment]
@bhoomikav16 Issue fix id deployed in QA environment, kindly test and close this ticket

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA instance

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA instance

**Comment by harisboston** [comment]
@bhoomikav16 issue is fixed in QA environment

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
