### ISSUE TITLE
[SB] UI issue is observed in the study activities section for the below scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4454]
**Steps:**
1. Edit the study.
2. Navigate to Questionnaires section.
3. Click on Add questionnaires button.
4. Navigate to Schedule tab.
5. Select daily radio button and then select anchor date schedule type radio button and Observe.

**AR:** UI issue is observed in anchor date field. (Refer screenshot attached)

**Note:**  Issue needs to be fixed for both questionnaires and active task section.
![j](https://user-images.githubusercontent.com/86007179/154510201-69fa6018-a3a9-4ce9-a033-735ba9863e72.png)

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in Dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
