### ISSUE TITLE
[GCI] [SB] A popup message is getting displayed while adding non-organizational user account in the below scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4456]
**Steps:**
1. Login to SB
2. Click on Manage admins icon
3. Click on Add admin button
4. Complete first name, last name , select the role and enter non-organizational user email 
5. Now enter invalid number in phone number field 
6. Click on Add button and Observe.

**AR:**  A popup message is getting displayed while adding non-organizational user account in the above scenario
**ER:**  A popup message should get displayed once all the mandatory fields are completed without any error messages

https://user-images.githubusercontent.com/86007179/154673694-471cb419-d757-44ed-a2dc-6a935c8646cd.mp4

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance

**Comment by bhoomikav16** [comment]
Issue is reproducing in the IDP QA branch

**Comment by akashkumarv3** [comment]
@bhoomikav16 Issue is fixed in QA also please check and update.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
