### ISSUE TITLE
[PM] Responsive issue > Customer logo is non functional 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4461]
Responsive issue > Customer logo is nonfunctional> After login to the application, if admin clicks on the customer logo it should be navigated to the dashboard

![image](https://user-images.githubusercontent.com/71445210/155124004-00203df4-777d-4d44-8b2a-9e7c4d292bde.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check in dev env and let me know.
thanks

**Comment by Lathan-btc** [comment]
@Madhud5 
AR: Studies tab is getting highlighted when admin clicks on customer logo
ER: Sites tab should be highlighted in the dashboard when the admin clicks on the customer logo

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check in dev env and let me know.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
