### ISSUE TITLE
[DID] Console > Duplicate patient records are getting created when same participant provides the responses for the multiple activities 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4464]
AR: Console > Duplicate patient records are getting created when the same participant provides the responses for the multiple activities
ER: Single patient record should be there for each participant

![image](https://user-images.githubusercontent.com/71445210/155280477-1f5e0d48-a051-4e9e-8b55-3cd23c976638.png)

**Comment by monica-BTC** [comment]
@Lathan-btc, please test and confirm this issue

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest FHIR deployment

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
