### ISSUE TITLE
[PM] Responsive issue > Dashboard > UI issue is observed in the sites and studies screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4469]
UI issue is observed in the sites and studies screen.

**ER:** No records found should be center aligned.
![1m](https://user-images.githubusercontent.com/86007179/155551656-f332d4e7-ebbb-43a7-9bb2-1a783672170d.png)

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment]
@Madhud5 issue is reproducible in the latest Dev instance

Note:
1. Issue is fixed in Dashboard but it is reproducible on other screens
2. Issue should be fixed in all the screens

![image](https://user-images.githubusercontent.com/71445210/155982403-60d4cae5-51ae-4315-8423-56dedf2a78e9.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest De instance

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue and let me know.
thank you

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance
