### ISSUE TITLE
[Mobile apps] Dashboard > Charts > Proper values are not getting displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4474]
Dashboard > Charts > Proper values are not getting displayed
iOS >  For scale1 chart
Provided values: 3, 4, 1, 3
Displayed values on Chart: Same value is getting displayed for all the runs

![image](https://user-images.githubusercontent.com/71445210/156166151-1a31ef9a-1e7f-4175-8bf9-bc45152bf2b1.png)

Android > For scale1-chart and numeric-chart
Provided values: Provided the different values for each run
Displayed values on chart: 'No data' is getting displayed

![image](https://user-images.githubusercontent.com/71445210/156166488-e90a7031-6735-4d11-87f7-c4dfb6f454a1.png)

AR: Provided values are not getting displayed properly on the charts
ER: Proper values provided from the participants should be displayed

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest android dev build 1.0(148)

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation For the form step questions  getting 'No data' even though we provided the responses

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello @Lathan-btc ,
The no Data display is due to trends not manually moved back to dashboard screen. This is the general flow followed as of now. This flow can be modified based on discussion.

Thank you,
Govind

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance if the page is refreshed.

**Comment by bhoomikav16** [comment]
@Shashank-btc  Issue is fixed in the latest android QA build  1.0(149)

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation Issue is fixed reproducible for form step questions

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS build V30(27)
