### ISSUE TITLE
Update Spring Framework from 3.x to 5.3.x

### ISSUE THREAD

**Issue by blnkumar-btc** [GoogleCloudPlatform/fda-mystudies#4476]
As sprint framework 3.x has reached end of life end of life in 2016 and no longer receives security patches. According to wiki ([https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions)] we need to upgrade to 5.3.x to be on a supported release.

**Comment by Lathan-btc** [comment]
Issue is fixed in both Dev and QA instance
