### ISSUE TITLE
[PM] Responsive issue > Participant details page > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4483]
Responsive issue > Participant details page > UI issue

![image](https://user-images.githubusercontent.com/71445210/156581999-c42d1f2d-7cff-4ae7-87e9-45185da57a78.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc  please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
