### ISSUE TITLE
External HTTPS load balancer that will allow it to negotiate HTTP/3

### ISSUE THREAD

**Issue by usbulat** [GoogleCloudPlatform/fda-mystudies#4491]
Hi!

Deployed version: 2.0.5
We've received the following email from GCP:

> We are rolling out a change to the External HTTPS load balancer that will allow it to negotiate HTTP/3 if no quicOverride setting has been applied.
> Hello Google External HTTPS Load Balancing Customer,
> 
> We are writing to let you know that the Global External HTTPS Load Balancers will change the week of March 21, 2022 so that HTTP/3 is enabled by default unless it is explicitly disabled in the load balancer’s configuration. Some of your projects are configured with Global External HTTPS Load Balancing and they might be affected by this update.
> 
> What do I need to know?
> 
> We are rolling out a change to the Global External HTTPS Load Balancer, allowing it to negotiate HTTP/3 if no quicOverride setting has been applied.
> 
> You can control whether or not your load balancer will negotiate HTTP/3 by configuring the [QUIC protocol support](https://notifications.google.com/g/p/AD-FnExhI6wG31RFpdVYlX6EmvJVh9FpAUqTn1MLDIl0D8MwpwEezsCmTW6sGAk-hn8SPijAkqoL398ImQG7oESbWWVCj42EhWhTady5xNG_2Zedql2G5tVcVQ5r5Q) on your load balancer. (QUIC is the [standardized transport](https://notifications.google.com/g/p/AD-FnEx0CnbJIP4Zen10dFrnO8f8iQG47zOPfEgBGf8CfNtqvdJ9sK7EmcZlSAuUt-poebdjRH1ryP13m-D6-p1fPBRwbZORXkzZCv5ZX__Vgou9) used by HTTP/3.)
> 
> HTTP/3 is a new version of HTTP that has been supported by the External HTTPS Load Balancer [since June 2021](https://notifications.google.com/g/p/AD-FnEwM5wJzmmFz4TyBqIApi1VKayAPT2gzk0EFj9RaDUnmYiM9gEDhF5JIU4QFPERJpe5PGylquvPaHEYIEKdkWkQS3UMdQUAsZv2D-rk59aNyi1XfjiDRoOR72m43ZPFFm_pEdnyEoQKCJHRGAt2mtAPsozB6x2Ak-2cG0SfI3hg). With HTTP/3 support, clients that support HTTP/3 can use it to communicate with the load balancer. This HTTP/3 support does not change the protocol used between the load balancer and backends.
> 
> Clients that do not support HTTP/3 are unaffected by this change. They can continue to use HTTP or HTTP2 when connecting to the load balancer.
> 
> What do I need to do?
> 
> No action is required for your load balancer to make use of HTTP/3. However, you can perform the following actions:
> 
> If you want to prevent your load balancer from using HTTP/3, you can set quicOverride in TargetHttpsProxy to DISABLE.
> If you want to test HTTP/3 prior to it being enabled, you can set quicOverride to ENABLE.
> If you want to verify that HTTP/3 is enabled in your load balancer, you can inspect the ‘alt-svc’ header in an HTTPS response from the load balancer. If this contains ‘h3’ then HTTP/3 is enabled.
> What happens if I don't do anything?
> 
> If you have not specified a quicOverride setting, with this change your load balancer will allow clients to use HTTP/3.

Can this affect our deployment? Do we need to do any actions according to these changes? Won't this affect any security aspects?

**Comment by yugandhar-btc** [comment]
@usbulat Google is rolling out this change across the Global External HTTPS Load Balancers and for now it will not effect to our deployment, we don't need to do any action because in our deployment the HTTPS Load Balancer QUIC negotiate is set as "default" (quicOverride=NONE). 

for more information please follow the [HTTP/3 and QUIC protocol support](https://cloud.google.com/load-balancing/docs/https#QUIC).

**Comment by usbulat** [comment]
Thanks @yugandhar-btc !
