### ISSUE TITLE
[PM] [Consent] Getting an error message in the participants details screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4505]
Getting an error message in the participants details screen, when clicked on participant email in the Enrollment registry.

![1](https://user-images.githubusercontent.com/86007179/160362571-e9a99799-f978-4be2-9d49-e92e27805216.png)

**Comment by bhoomikav16** [comment]
@navya-BTC Issue is still reproducing in the latest dev instance

**Comment by navya-BTC** [comment]
@bhoomikav16 please test for new studies

**Comment by bhoomikav16** [comment]
@navya-BTC Issue is not observed for new studies, and also this issue is still reproduicng for old studies

**Comment by bhoomikav16** [comment]
@harisboston  Issue is fixed and it is not observed for new studies, and also this issue is still reproducing for older studies only in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
