### ISSUE TITLE
[Consent API] State should be changed in the data sharing consent type for the below scenarios

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4506]
State should be changed in the data sharing consent type for below scenarios,

**1.**
**AR:** The state of the consent record is 'ACTIVE' for data sharing status Not Provided
**ER:** The state of the consent record should be 'REJECTED' for data sharing status Not Provided

**2.**
**AR:** The state of the consent record is 'ACTIVE' for data sharing status Not Applicable
**ER:** The state of the consent record is 'STATE_UNSPECIFIED' for data sharing status Not Applicable

**Note:** Issue needs to be fixed for below scenario also,
If the previous version of data sharing consent is Provided and the latest version is Not Provided then the state of consent record should be REVOKED.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is reproducing for below scenario,
**AR:**  The state of the consent record is 'ACTIVE' for data sharing status Not Applicable
**ER:**  The state of the consent record is 'STATE_UNSPECIFIED' for data sharing status Not Applicable

**Comment by akashkumarv3** [comment]
@bhoomikav16  Issue is fixed now please check and update .

**Comment by bhoomikav16** [comment]
AR: The state of the consent record is 'ACTIVE' for data sharing status Not Applicable
ER: The state of the consent record is 'STATE_UNSPECIFIED' for data sharing status Not Applicable
Issue for below scenario is not valid as per new implementations . Issue is fixed in the latest dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
