### ISSUE TITLE
[Consent API] Data sharing consent artifact is not getting created in the below scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4507]
**Steps:**
1. Edit the study.
2. Enforce e-consent flow in the study builder for enrolled participants.
3. Publish the study.
4.  Now in mobile app, complete e-consent flow again and Submit.

**AR:** Data sharing consent artifact is not getting created in the above scenario
**ER:** Data sharing consent artifact should be created in the above scenario

**Comment by harisboston** [comment]
Artifacts are created only once right now when participants enrolls for the first time
