### ISSUE TITLE
[FHIR] Display name of activities should be mapped to "name" key of /process-response API

### ISSUE THREAD

**Issue by madhurya-btc** [GoogleCloudPlatform/fda-mystudies#4508]

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build 3.0(49)

**Comment by Shashank-btc** [comment]
Android Display name of activities are mapping to "name" key

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest Dev build 1.0(171)

**Comment by Lathan-btc** [comment]
Issuie is fixed in the latest QA builds
