### ISSUE TITLE
[iOS] iOS 15.4 > HTML breakage in Rich text editor in instruction step for iOS 15.4 version

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4511]
**Steps:**

1. Upgrade iOS version to 15.4
2. Install the app
3. Login and enroll into study (eg. StudyID - AMobileStudy in Dev Instance)
4. Open instruction step and observe HTML is not rendered sometimes
5. Discard results and re-open again
6. Observe HTML is not rendered consistently

**Actual:** HTML breakage in Rich text editor in instruction step

**Expected:** Text should render properly

**Note:**

1. Issue not observed in other iOS versions like 15.1/15.2
2. Issue not observed in other RTE pages eg. consent, overview, Resources, Data sharing but need to verified from code level so it doesn't break for different combinations in the 15.4 version

**Refer video:**

https://user-images.githubusercontent.com/60386291/160422449-39bb8dde-b26b-4ea7-baea-df8434506c5b.MOV

**Comment by nishit-v** [comment]
Issue is fixed in latest iOS Dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest iOS QA build V30.35

**Comment by nishit-v** [comment]
Above issue should be fixed for all Rich Text Editors like Consent screens, Data sharing, Resources etc..

**Comment by nishit-v** [comment]
Issue is fixed in Consent learn more, instruction step, resources, overview.

Issue needs to be fixed in 'View Consent' section in study overview screen. Refer video

https://user-images.githubusercontent.com/60386291/167793269-24018f81-7284-47ca-a274-17e74081ceae.MOV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build 3.0(66)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
