### ISSUE TITLE
[iOS] Resources > Special characters are inserted into file names shared for RTE or PDFs

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4513]
Steps:

1. Install the iOS app
2. Signup/login and enroll into study
3. Navigate to resources
4. Open any resource with RTE/PDF configured
5. Click on share and choose email
6. Open the file attached and observe the file name

Actual: Special characters are inserted into file names shared for RTE or PDFs

Expected: File name should be proper

**Issue not observed in older GCP versions eg. 2.0.9**

![iOS_Resources](https://user-images.githubusercontent.com/60386291/160425029-8d57c02e-e043-400b-913e-96c46c004365.png)

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
1)In iOS the following special characters are not supported - 
/ %  ~

2)The following charaters are already restricted in studybuilder - 
#^}{ 

3) The following charaters are not alllowed in studybuilder which has to be included in the error message
\< >

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0.49

Refer screenshot:
![PDF](https://user-images.githubusercontent.com/60386291/166868080-4d29f2f7-65f6-4591-8fab-2133dad2b65b.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
