### ISSUE TITLE
[Android] Resources > Resources configured with Rich text editor fails to share as PDF

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4515]
**Steps:**
1. Install the Android app
2. Signup/login and enroll into study
3. Navigate to resources
4. Open any resource with RTE configured
5. Click on share and choose email
6. Observe the file attached

**AR:** Resources configured with Rich text editor fails to share as PDF.
**ER:** Resources configured with Rich text editor should be shared as PDF.

**Comment by Shashank-btc** [comment]
BA team need to verify this ticket

**Comment by bhoomikav16** [comment]
As per the above comment, Closing this issue.
