### ISSUE TITLE
[Android] Resources > HTML breakage is observed when resources configured with Rich text editor is shared

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4516]
**Steps:**
1. Install the Android app
2. Signup/login and enroll into study
3. Navigate to resources
4. Open any resource with RTE configured
5. Click on share and choose email
6. Observe the file attached

**AR:** HTML breakage is observed when resources configured with Rich text editor is shared
**ER:** HTML breakage should not be observed when resources configured with Rich text editor is shared

![43a4c1a8-afb2-4e17-92f5-ac1519b6014e](https://user-images.githubusercontent.com/86007179/160767719-aeb86400-831a-4a84-a9e1-eadf8bcc2460.jpg)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev build 1.0(151)

**Comment by naveenr-btc** [comment]
This has been identified before that gsuite apps doesn't allow this after their update. so please check this with other sharing methods like outlook to see if the functionality is working fine.
