### ISSUE TITLE
[Android] App is crashing in the below scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4517]
**Steps:**
1. Install the android app and signup
2. Enroll into the study
3. Navigate to resources
4. Open any pdf resources and lock the phone once after pdf resouce is loaded
5. Now, go back to SB 
6. Publish resources from the SB
7. Unlock the mobile device now
8.  And navigate from Resources to Dashboard and again to Study activities screen
9. Refresh the screen and Verify

**AR:** App is crashing in the above scenario.
**ER:** App should not crash in the above scenario and participants should remain in the study activities screen only.

**Note:**
App is restarting in some of the devices and navigating to study list screen for the above scenario

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev build

**Comment by bhoomikav16** [comment]
@Shashank-btc Issue is still reproducing for the below scenario also,
For the same above steps, In step 7 when navigated from Resources to Dashboard and again to Study activities screen, App is crashing.

**Comment by bhoomikav16** [comment]
@Shashank-btc Issue is still reproducing as mentioned in the above comment

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the dev build 1.0(165)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev build 1.0(167)

**Comment by naveenr-btc** [comment]
Try in other devices and check if it's still happening. need to confirm if it's a device specific issue.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev build 1.0(174)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA build 1.0(217)

**Comment by bhoomikav16** [comment]
Issue got reproduced only twice. After installing the build again, tried above scenario multiple times, Issue is not reproducing in the latest QA build 1.0(217). So closing this issue
