### ISSUE TITLE
[Consent API] [SB] E-Consent section > No button is disabled in data sharing permission screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4529]
**Steps:**
1. Copy the study
2. Edit the  copied study
3. Navigate to E-Consent section and Verify

**AR:** No button is disabled in data sharing permission screen
**ER:** No button should not be disabled in data sharing permission screen

**Note:**  Issue also needs to fixed when study is imported

![consent](https://user-images.githubusercontent.com/86007179/161760033-4b78e7e8-cbe6-45fa-a992-598534492242.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
