### ISSUE TITLE
[Consent API] Edit study > Econsent steps > 'Consent document' tab > Values are not getting displayed in the 'Consent document' field

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4530]
Steps:

1. Login to SB 
2. Create a study 
3. Launch the study
4. Click on edit study
5. Go to 'Econsent steps'
6. Click on the 'Consent document' tab
7. Observe the values in the 'Consent document (last published version: V1.n) field

AR: 'Consent document' field is empty
ER: Created consent in the Consent section should be displayed in the 'Consent document' field

![image](https://user-images.githubusercontent.com/71445210/161763565-00675b51-9196-4ad8-aeb1-f4d5c6907789.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
