### ISSUE TITLE
[Consent API] [SB] E-Consent section > Data sharing permission screen > Explanatory text that can be provided in a 'Learn more' section is enabled for launched study

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4531]
**Steps:**
1. Create a study by providing yes in the data sharing permission 
2. Launch the study
3. Edit the launched study
4. Navigate to E- Consent steps and Verify

**AR:** Explanatory text that can be provided in a 'Learn more' section field is enabled for launched study
**ER:** Explanatory text that can be provided in a 'Learn more' section field should be disabled for launched study

![Consent2](https://user-images.githubusercontent.com/86007179/161764194-7724360c-740e-48aa-be53-4927171ba8a5.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
