### ISSUE TITLE
[Android] Share icon is disabled in the mobile app > If PDF resources title is configured with slash special character in the study builder

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4532]
**Steps:**
1. Configure PDF resources with slash special character as title in SB. ( Eg:PDF/ )
2. Now in mobile app, Navigate to resources screen
3. Open that particular PDF resource
4. Click on Share icon and Verify

**AR:**  Share icon is disabled in the mobile app , If PDF resources title is configured with slash special character in the study builder
**ER:** Share icon should not be disabled in the mobile app , If PDF resources title is configured with slash special character in the study builder

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA build 1.0(217)

**Comment by Shashank-btc** [comment]
Hi 

StudyBuild should not accept the below characters, now the change are done by backend you can test above flow.
 / %
 
 Thanks

**Comment by bhoomikav16** [comment]
As per the above comment, Issue is fixed in the latest QA instance
