### ISSUE TITLE
[SB] Add/edit study > Add/edit questionnaires > Not able to add any questionnaire steps in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4536]
Steps:
1. Sign in to SB 
2. Edit study
3. Go to Questionnaires
4. Add/edit questionnaire
5. Add the question steps and form steps
6. Delete the added question step questions
7. Try to add any questionnaire steps

AR: Success message is getting displayed but added questionnaire steps not getting reflected in the list
ER: Added questionnaire steps should be reflected in the questions list

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in dev env, kindly test and confirm. Thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc This issue is fixed in QA environment

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest QA instance

**Comment by Lathan-btc** [comment]
Issue is not reproducible in the DEV instance

[Note: Its reproducible only in QA instance]

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
