### ISSUE TITLE
Response Datastore and Android Lint Work flows failed

### ISSUE THREAD

**Issue by mohangmk** [GoogleCloudPlatform/fda-mystudies#4537]
Lint check workflows are failed on Response Datastore and Android Lint (#4528)- I believe you have resolved this issue in the QA Environment, so please move same changes to Public repo Develop branch

**Comment by madhurya-btc** [comment]
In the public repo Develop branch Android-Lint / Checkstyle job is successful, so will move this to the next milestone and observe.

**Comment by madhurya-btc** [comment]
@mohangmk Issue is not reproducible hence closing
