### ISSUE TITLE
[SB] [PM] [QA] Add admin screen > Dropdown icon is getting displayed in the email field

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4545]
**AR:** Add admin screen > Dropdown icon is getting displayed in the email field
**ER:** Add admin screen > Dropdown icon should not get displayed in the email field

**Note:** For 2.0.10 release , there is no GCI enhancement.

Kindly find attached screenshots below for the issue.

**1. SB**
![admin](https://user-images.githubusercontent.com/86007179/163409500-5d8115f0-ff72-45b5-a6a3-9cd48799891d.png)

**2. PM**
![admin1](https://user-images.githubusercontent.com/86007179/163409894-2b870635-318e-499f-888a-bf7afe782551.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
