### ISSUE TITLE
[iOS] [QA]Notification list > Notifications are not getting displayed in the notifications list

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4549]
Notification list > Notifications are not getting displayed in the notifications list

[Note: Issue observed only in QA instance]

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest QA instance

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
