### ISSUE TITLE
[iOS] Notifications issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4556]
1. if we get activities added notification > After clicking the notification activities screen is not getting refreshed
2. In the mobile app, go to the activities list screen > Minimize the app > Pause the particular study > after getting the notification click on paused notification > Then Resume the study in SB and publish the updates > after receiving the notification click on the Notification and observe > Participant is navigating to the Study activities list screen > Participant should be in the study list screen

**Comment by Lathan-btc** [comment]
@amruthbtc 
1. if we get activities added notification > After clicking the notification activities screen is not getting refreshed - **Fixed**
2. In the mobile app, go to the activities list screen > Minimize the app > Pause the particular study > after getting the notification click on paused notification > Then Resume the study in SB and publish the updates > after receiving the notification click on the Notification and observe > Participant is navigating to the Study list screen > Participant should be in the study list screen - **Issue is reproducible in the latest build**

**Comment by Lathan-btc** [comment]
The issue is reproducible in the latest build 3.0(76)

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev build 3.0(115)

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev build

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
