### ISSUE TITLE
[PM] Participant details screen > Consent history > Enrolled date is displayed as consented date when user provides the updated consent

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4562]
Steps:
1. In mobile, enroll to the study (enrolled date is (4/14/2022)
2. In SB, update the consent for a particular enrolled to study with e 'Enforce consent for enrolled participants' option)
3. In Mobile, click on the particular enrolled study
4. Provide the updated consent ( Eg: latest consent provided date 20/04//2022)
5. In PM, Click on the particular study 
6. Click on the particular participant record
7. Observe the consented date in the latest consent history

AR: Enrolled date is displayed as the consented date when the user provides the updated consent
ER: Latest consent provided date should be displayed (As per the above scenario 20/04/2022 should be displayed as consented date

![image](https://user-images.githubusercontent.com/71445210/164450844-1b69afa6-98ad-48ec-88ab-98dfb490e493.png)

**Comment by akashkumarv3** [comment]
Its not backend issue, from backend "consentedDate":"04/12/2022"  is coming correct  but in UI date is not updating correct its showing  "consentedDate" : 04/06/2022.


{"participantDetails":{"id":null,"email":"mobileapps+and1@boston-technology.com","onboardingStatus":"Invited","enrollmentStatus":"Enrolled","enrollmentDate":"04/12/2022","withdrawalDate":"NA","invitedDate":null,"disabledDate":null,"siteId":"2c90808c7fbdeba8017fd10361c10021","locationName":"defaultLocation_OpenStudy","customLocationId":"default_OpnStdy","participantRegistrySiteid":"2c9081a48019f48a01801ce466200004","customStudyId":"gcp28","studyName":"Imported health tips to help you(open study)","studyType":"OPEN","customAppId":"GCPDEV001","appName":"BTC Devv","invitationDate":"04/12/2022","userDetailsId":null,"registrationStatus":null,"studiesEnrolled":null,"registrationDate":null,"sitePermission":1,"studyStatus":"Active","siteStatus":1,"appStatus":"Active","enrolledStudies":[],"enrollments":[{"participantId":null,"withdrawalDate":"NA","enrollmentStatus":"Enrolled","enrollmentDate":"04/12/2022"}],"consentHistory":[{"id":"gcp28@31812206-6417-412b-93c4-9ebd777eaabb","consentVersion":"1.2","consentedDate":"04/12/2022","consentDocumentPath":"gcp28/0393dc71-6665-4ca8-8414-75728d4498be-9465a9ba4fa48q40bfs83c9xeda5b573fced/1.2_04122022082936.pdf","dataSharingPermissions":"Not Applicable","createTimeStamp":"04122022082936"}],"newlyCreatedUser":false},"totalConsentHistoryCount":0,"status":200,"code":"MSG_0017","message":"Participant details fetched successfully"}

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in the dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build

**Comment by bhoomikav16** [comment]
Issue is reproducing in the latest Dev instance

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
