### ISSUE TITLE
fda_hphc DB migration Warnings 

### ISSUE THREAD

**Issue by yugandhar-btc** [GoogleCloudPlatform/fda-mystudies#4566]
While in the process of **fda_hphc** DB migration, as a part of **v2.0.10**, We have observed Warnings. 

![image](https://user-images.githubusercontent.com/69250111/164717766-0709e23d-5a2c-4184-8fe4-6da5a42e9c4d.png)

**Comment by madhurya-btc** [comment]
We can ignore these warnings, hence closing the ticket
