### ISSUE TITLE
[PM] [QA] Dashboard > Sites / Studies > UI Issue is observed in Participants details screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4569]
UI issue is observed in ,
Sites / Studies > Participants details screen

![1](https://user-images.githubusercontent.com/86007179/165103591-7fa78288-ce09-4c2e-aeac-94d530b853f5.png)

**Comment by Madhud5** [comment]
hi @bhoomikav16 i have fixed please check and let me know.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
