### ISSUE TITLE
[PM] Admins are navigated to dashboard by using temporary password in the below scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4578]
**Steps:**
1. In Sign in screen, Click on forgot password link
2. Enter the registered admin's email and Click on Submit button
3. Now, sign in with Superadmin's account and navigate to Admins tab
4. Deactivate the admin account which was entered in forgot password in step 2
5. Again reactivate the same account
6. And then Sign out as Superadmin
7. Again Sign in with admin account email which was entered in forgot password in step 2 and with temporary password and then Verify

**AR:** Admins are navigated to dashboard by using temporary password in the above scenario
**ER:** Admins should be navigated to set up password screen in the above scenario

**Comment by harisboston** [comment]
@bhoomikav16 Since it's a very rare scenario, if super admin deactivates admin, who requested for forgot password. We will expire that admin's password. 
So that again admin can request for forgot password and use temp password to reset his password.

**Comment by bhoomikav16** [comment]
As per the above comment, Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
