### ISSUE TITLE
[PM] When clicked on Cancel button in My account screen, Admins are navigated to Studies screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4579]
**AR:** When clicked on 'Cancel' button in My account screen, Admins are navigated to 'Studies' screen
**ER:** When clicked on 'Cancel' button in My account screen, Admins should be navigated to 'Sites' screen

**Comment by Madhud5** [comment]
hi @bhoomikav16 i have fixed please check and let me know.

**Comment by bhoomikav16** [comment]
@Madhud5  Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
