### ISSUE TITLE
[Mobile apps] [FHIR]  Enrollment flow is not working in the android mobile apps

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4580]
**AR:** Enrollment flow is not working in the android mobile apps 
**ER:** Participants should be able to enroll in the android mobile apps 
![Untitled](https://user-images.githubusercontent.com/86007179/165324483-a56576b1-4405-4a7d-a0b2-1dbdd74aa1ac.png)

**Comment by harisboston** [comment]
Error
`500 responseData ={"status":500,"error_type":"500 INTERNAL_SERVER_ERROR","error_code":"EC_0009","error_description":"Sorry, an error has occurred and your request could not be processed. Please try again later.","timestamp":1651053719091}`
For GCP DEV API  `/updateEligibilityConsentStatus`

**Comment by bhoomikav16** [comment]
@harisboston Issue is fixed and it is not observed for new studies, and also this issue is still reproducing for older studies only in dev instance

**Comment by harisboston** [comment]
Since consent store logic is changed recently in dev env, so this issue is occurring only for old studies in dev env only. This issue will not happen for new studies.

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
