### ISSUE TITLE
[iOS] Eligibility test > The following changes needs to be done on the Eligibility questions screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4581]
1. Remove the arrow marks present which are present next to the Data sharing options
2. AR: A participant is automatically navigating to the next screen after selecting any one of the options
    ER: After selecting the option, the participant should stay on the same screen and participant should click on 
          next button to navigate to the next page

![image](https://user-images.githubusercontent.com/71445210/165716891-4ca06279-ba79-4b49-b2af-ef756b4ac2ac.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest dev iOS build V3.0(53)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA instance.
