### ISSUE TITLE
[iOS] Comprehension test > Blank white screen is displayed on failing comprehension test and clicking on cancel

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4587]
Steps:
1. Install the app
2. Login/Signup
3. Enroll into study
4. Fail the comprehension test questions
5. Click on the 'Cancel' button on the top right
6. Observe

AR: Blank white screen is displayed on failing comprehension test and clicking on cancel
ER: Should be redirected to consent sections

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build 3.0(55)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
