### ISSUE TITLE
[iOS] Hamburger menu icon > Sections are non functional in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4590]
Steps:
1. Install the app
2. Sign up or login to the app
3. Click on Hamburger menu icon
4. Minimize the app / lock the mobile
5. Maximize/unlock the mobile
6. Enter the passcode 
7. Try to click on any section present on the hamburger menu 

AR: All the sections are non functional
ER: All the sections should be functional and participant should navigate to proper sections when they clicks on the each section

![image](https://user-images.githubusercontent.com/71445210/167639784-a2947305-a094-460e-ad94-049ac9ed9b86.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest dev iOS build V3.0(53)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
