### ISSUE TITLE
[GCI] [SB] [PM] Add admin > Email > Issues with respect to Email dropdown in add admin screen 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4593]
**Scenario 1:**

1. Login to SB
2. Click on manage admins icon
3. Click on add admin button
4. Select the email dropdown 
5. Click on any other field and Verify

**AR:** Email dropdown is still getting displayed
**ER:** Email dropdown should not get displayed when navigated to other field

**Scenario 2:**

1. Login to SB
2. Click on manage admins icon
3. Click on add admin button
4. Select the email dropdown 
5. Select the value and remove the value again
6. Again select the value and Verify

**AR:** 'Please fill out this field' error message is still getting displayed below the email dropdown
**ER:** Error message should not get displayed below the email dropdown

![Untitled](https://user-images.githubusercontent.com/86007179/168074064-8002aa7b-1603-429a-ad5c-7a6cc9c5d1c2.png)

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP branch in dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP branch in QA instance
