### ISSUE TITLE
[Mobile apps] Enforce e-consent flow again for enrolled participants is not getting displayed in the mobile apps

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4594]
**Steps:**
1. Sign out from the mobile app
2. Go back to SB and Update Enforce e-consent flow again for enrolled participants and Publish the study
3. Now in the mobile apps, sign in and Verify

**AR:** Enforce e-consent flow again for enrolled participants is not getting displayed in the mobile apps
**ER:** Enforce e-consent flow again for enrolled participants should get displayed in the mobile apps

**Note:** Issue needs to be fixed for both standalone and gateway app

**Comment by bhoomikav16** [comment]
@Shashank-btc  Please provide the build for the this issue

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Standalone Android app

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA gateway build 1.0(217)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
