### ISSUE TITLE
iOS > Create passcode is displayed twice for new user

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4596]
**Steps:**
1. Install the app
2. Signup
3. Enter verification code
4. Create a passcode and re-enter the passcode
5. Click on 'Next' and observe

AR: Create passcode is displayed twice after the user signs up
ER: Create passcode should be displayed only once

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev build

**Comment by nishit-v** [comment]
Issue is fixed in the latest Dev build 3.0(106)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
