### ISSUE TITLE
[iOS] 'View consent' and 'View website' buttons are not getting displayed on the study overview screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4597]
Steps:
1. Sign up or sign in to the app
2. Click on any study to enroll
3. Click on the participate
4. I enrollment flow, click on the 'Cancel' button
5. Click on 'End task' or 'Click on 'Discard result' and observe

AR: 'View consent' and 'View website' buttons are not getting displayed on the study overview screen
ER: ''View consent' and 'View website' buttons should get displayed on the study overview screen

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0.105

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
