### ISSUE TITLE
Android > App is crashing in the below scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4598]
**Steps:**
1. Install the app
2. Sign in and complete the passcode process
3. Minimize / Lock the app once after study list screen is loaded
4. Open the app and Click on 'Sign in again' in passcode screen
5. Click on 'Ok' button
6. Click on back button in 'Sign in' screen
7. Click on 'Get started' button and Verify

**AR:**  App is crashing in the above scenario
**ER:** App should not crash and study list screen should be available for the participant

https://user-images.githubusercontent.com/86007179/169323816-98d096eb-5588-404a-a9e2-03054bbc0b16.mp4

**Comment by bhoomikav16** [comment]
@Shashank-btc 

For the above same scenario, 

**AR:** Getting blank screen in study list screen for more than 10 seconds
**ER:** Study list screen should be loaded and should be available for the participant

Note: As app is not crashing so reducing the priority

![Screenshot_20220526-130939_FDA MyStudies](https://user-images.githubusercontent.com/86007179/170442750-9e5be8e1-dbb5-41ec-84ef-89167264efb2.jpg)

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA build 1.0(217)
