### ISSUE TITLE
[PM] Deactivated admin should be auto signed out on the next user action

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4604]
**Steps:**
1. Login to participant manger
2. Navigate to admins tab
3. Admin should deactivate their own account and Verify

**AR:**  Deactivated  admin can still use the participant manager application even after next user action
**ER:** Deactivated admin should be auto signed out on the next user action

https://user-images.githubusercontent.com/86007179/170426384-4139f412-7613-4071-9ff1-b69530669def.mp4

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
