### ISSUE TITLE
[SB] Add admin > Create new apps / studies checkbox is getting disabled when changing the admin's role in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4606]
**Steps:**
1. Login to SB
2. Click on 'Manage admins' icon in 'Dashboard'
3. Click on 'Add admin' button
4. Click on 'Role' dropdown and Select Study admin from the dropdown
5. Select the Manage apps / Manage studies checkbox
6. Now again change the role to super admin and then to study admin
7. Verify the  Create new apps / studies checkbox

**AR:** Create new apps / studies checkbox is getting disabled
**ER:**  Create new apps / studies checkbox should not get disabled

![CheckboxIssue](https://user-images.githubusercontent.com/86007179/170647406-6b94c638-6653-47fd-a182-0cb5fa08e1f8.png)

**Comment by bhoomikav16** [comment]
Issue is reproducing in the below scenario,
1. Login to SB
2. Click on 'Manage admins' icon in 'Dashboard'
3. Click on 'Add admin' button
4. Click on 'Role' dropdown and Select Study admin from the dropdown
5. Select the Manage apps / Manage studies checkbox and also add few apps and studies
6. Now again change the role to super admin and then to study admin and Verify


**AR:**  
1.  Selected values in the manage apps is not getting displayed
2. Create new studies checkbox is getting unselected


**ER:**
1.  Selected values in the manage apps should get displayed
2. Create new studies checkbox should be selected


**Note:**
Previously added data for the study admins should reflect for the above scenario

![admin](https://user-images.githubusercontent.com/86007179/172184046-6400f410-2d17-44e5-947f-1c23a7327175.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest QA instance

**Comment by akashkumarv3** [comment]
@Lathan-btc please check and update this ticket .

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by akashkumarv3** [comment]
@Lathan-btc please test in QA and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
