### ISSUE TITLE
[IDP] [SB] Organizational admin should be auto signed out on the next user action, when disabled in the organizational directory

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4613]
**Steps:** 
1. Login as organizational admin to study builder
2. Disable same admin in the organizational directory
3. Go back to SB, perform any user action in the application and Verify

**AR:**   Disable admin can still use the SB application even after next user action
**ER:**  Organizational admin should be auto signed out on the next user action , when disabled in the organizational directory

**Comment by harisboston** [comment]
As per configuration, scheduler to update the idp user status runs on every 1 min. So, once user is disabled or deleted in IdP, it will get updated within a min, till then user will be active in SB and will be able to perform all operations.

**Comment by bhoomikav16** [comment]
Hi @harshith2590 ,

Could you please provide feedback on the above issue?

**Comment by harshith2590** [comment]
Here the scheduler run is required for notifying system about the user disability. As the duration (1 min) is configurable and can be changed on client needs, we can live with this approach and issue can be closed.

**Comment by bhoomikav16** [comment]
Closing this issue, after confirmation from BA team.
