### ISSUE TITLE
[IDP] [SB] [PM] Verification code > Same verification code is getting generated in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4615]
**Steps:**
1. Try to 'Sign in' with valid organizational admin account
2. Select the reCapthcha in sign in screen
3. In verification popup message , Click on 'Cancel' button
4. Again try to sign in with same admin credentials
5. Observe the verification code received in the text message by the admin and Verify

**AR:** Same verification code is getting generated multiple times
**ER:** Same verification code should not be generated 

![verification code](https://user-images.githubusercontent.com/86007179/171143952-bc9a51ff-4a51-4194-a972-5b285d39d4af.png)

**Comment by harisboston** [comment]
verification code is google specific, we are invoking one function to get code
for a specific phone number, for some duration it will generate the same code.

**Comment by harshith2590** [comment]
Hi Bhoomika,
The verification code will change after every 1-2 minutes. Its only when user tries multiple click before the duration, the same code will be sent. This is fine and we can live with it.

**Comment by bhoomikav16** [comment]
@harshith2590 @harisboston 
 Same Verification code is getting displayed even after 5 minutes , when tried to sign in as organizational admin

**Comment by bhoomikav16** [comment]
Closing this issue as per the above comment.
