### ISSUE TITLE
[SB] Create a new password screen > UI Issue 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4617]
**Steps:**
1. Click on 'Forgot password' screen
2. Enter the registered email 
3. Click on 'Submit' button
4. Click on the link received to set up a new password to sign in in Chrome browser and Verify

**AR:** 
![forgotpassword](https://user-images.githubusercontent.com/86007179/171201869-dd81b66a-19b3-40de-82e3-544b9ee0062e.png)
 

**ER:**
![fp](https://user-images.githubusercontent.com/86007179/171202303-bdc721b6-bdd8-482f-9ea4-cc73578af79e.png)

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev IDP branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
