### ISSUE TITLE
Participant Manager Build Fail

### ISSUE THREAD

**Issue by yugandhar-btc** [GoogleCloudPlatform/fda-mystudies#4622]
The participant-manager build is getting failed.

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Performed sanity testing on PM dev IDP branch and everything looks good

**Comment by bhoomikav16** [comment]
Performed sanity testing on PM dev branch and everything looks good

**Comment by bhoomikav16** [comment]
Performed sanity testing on PM QA branch and everything looks good
