### ISSUE TITLE
[IDP] [PM] UI issue in the non-organizational admin popup message

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4627]
UI issue is observed in the non-organizational admin popup message while adding the admin in the application

**AR:**
![PM3](https://user-images.githubusercontent.com/86007179/172861642-bc51a1f9-067e-4c3f-8586-226525feb30c.png)

**ER:**
![PM5](https://user-images.githubusercontent.com/86007179/172863373-5e70c5ea-bc63-4bbe-b33f-6207fc248b67.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
@Madhud5 
 Margins for the text should be as per the attached screenshot in the expected result
**AR:**
![UI](https://user-images.githubusercontent.com/86007179/173569876-5d0d6600-3b4f-4101-b796-08f0cd25cace.png)
**ER:**
![ui2](https://user-images.githubusercontent.com/86007179/173570196-e2bdb4fe-4ab3-47a2-98c9-5348213fec91.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
