### ISSUE TITLE
[PM] Admins > Add new admin > UI issue in add new admin screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4628]
**Steps:**
1. Login to PM
2. Click on  'Admins' tab
3. Click on 'Add new admin' button
4. Verify the email field 

**AR:** Dropdown icon is getting displayed in the email field
**ER:** Dropdown icon should not get displayed in the email field
![PmUI](https://user-images.githubusercontent.com/86007179/173838121-47c86858-ea04-482c-b67c-9367e0a67389.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
