### ISSUE TITLE
[PM] Admins > Search user by name or email ID > Getting 'No records found' when searched admin with their email ID

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4629]
**Steps:**
1. Login to PM
2. Click on 'Admins'  tab
3. Click on 'Add new admin' button and add admin in the application
4. Search that admin with email ID and Verify

**AR:** Getting 'No records found' when searched admin with their email ID
**ER:** When searched admin with their email ID, their record should get displayed
![PMIssue](https://user-images.githubusercontent.com/86007179/173840744-8bcfda19-66e4-41e8-84c3-168dcf04418e.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
