### ISSUE TITLE
[WCP] On Enforcing Password change for all users exclude super admin 

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#463]
![Screenshot_1](https://user-images.githubusercontent.com/60500517/84112127-cc94f180-aa45-11ea-868b-fb77616268f8.png)

**Comment by madhurya-btc** [comment]
@nagarjunav1 This appears to be working fine, please test and close.

**Comment by nagarjunav1** [comment]
Issue is fixed now in dev. Now on enforcing password change super admin will be excluded.
