### ISSUE TITLE
[SB] UI issues in the E-consent screen 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4631]
In the E-consent screen, 
1. The font size of the 'Consent document (last published version: N/A)' should be changed
2. The font size of the 'Enforce e-consent flow again for enrolled participants' should be changed

**Please refer attached screenshot below**
![UI](https://user-images.githubusercontent.com/86007179/174072365-fbd10ce1-ddbe-48ca-99af-9db1e5bd47f3.png)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by Lathan-btc** [comment]
@sheelakanni97 Text present inside the bracket should be same as 'Consent document'

![image](https://user-images.githubusercontent.com/71445210/181272534-faacda8d-cd44-44b7-928f-6f117354d924.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
