### ISSUE TITLE
[IDP] [SB] There is much space between the error message and the Email field in the sign in screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4635]
**Steps:**
1. Click on SB URL
2. Enter valid Email and invalid password and Verify

**AR:**  There is much space between the error message and the Email field in the sign in screen
**ER:**  There should not be much space between the error message and the Email field in the sign in screen

![SB UI Issue](https://user-images.githubusercontent.com/86007179/174536922-11d0ce26-12c7-469c-a766-45ec7ae3f0ae.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
Issue will be tested once when IDP branch is pointed

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev IDP instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA IDP instance
