### ISSUE TITLE
[WCP] 'Enforce Password change' button for all users should be enabled only for super admin credentials

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#464]
![Screenshot_1](https://user-images.githubusercontent.com/60500517/84112310-21d10300-aa46-11ea-874d-b6da9a116848.png)

**Comment by SR-btc** [comment]
This issue can be closed if the action button is available only for the superadmin.  Enhancements will be addressed in future releases.

**Comment by nishit-v** [comment]
'Enforce Password change' action button is available only to superadmin access. Closing this ticket
