### ISSUE TITLE
[IDP] [PM] Not able to set up new admin account in the PM

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4640]
**Pre-condition:** mfa should be disabled in the PM

**Steps:**

1. Login to PM
2. Click on 'Admins' tab
3. Click on 'Add new admin' button
4. Add admin in the application
5. Click on account activation link 
6. Try to set up account without 'Phone number' and Verify

**AR:**  Not able to set up new admin account in the PM
**ER:** Admin should be able to set up their account in the PM ,without entering phone number field.

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
