### ISSUE TITLE
[IDP] [PM] UI issue in the admin details screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4642]
**Pre-condition:**  mfa should be disabled in the PM

**Steps:**
1. Login to PM
2. Click on 'Admins' tab
3. Edit admin in the list and Verify

**AR:**  UI issue is observed in the admin details screen
**ER:**  All the field should be aligned properly

![UIPhone](https://user-images.githubusercontent.com/86007179/175250064-aab4edf7-c20c-44c9-9c2e-15b3618f02a9.png)

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
