### ISSUE TITLE
[IDP] [SB] UI issue in all the screens of the study builder

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4643]
Font size and font style is different in all the screens

**Note:** Issue needs to be fixed throughout the application

![StudyBuilder](https://user-images.githubusercontent.com/86007179/175257520-452700b6-37c2-4042-bf45-0ebc21d5e996.png)

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
