### ISSUE TITLE
[PM] [QA]  Alignment issue is observed in the PM

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4644]
My account tab should aligned properly 
![image (5)](https://user-images.githubusercontent.com/86007179/175262622-4e0cb0c2-89f6-461e-ab5c-8ff71a29372e.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue and close it.

**Comment by bhoomikav16** [comment]
Issue will be tested once in the QA environment

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance
