### ISSUE TITLE
[IDP] [PM] Not able to update admin in the my account screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4645]
**Pre-condition:** mfa should be disabled in the PM

**Steps:**
1. Login to PM
2. Click on 'My account' tab
3. Remove the phone number
4. Try to click on 'Update' button and Verify

**AR:** Not able to update admin , Update button is disabled
**ER:** Update button should be enabled and account should be updated

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by Madhud5** [comment]
hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
