### ISSUE TITLE
[Mobile apps] Study activities screen > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4646]
Study activities screen > UI issue > There should be a gap between time and time unit (AM or PM)

![image](https://user-images.githubusercontent.com/71445210/175470010-29c06148-fa9c-4597-a6f5-67f47b2b2292.png)

![image](https://user-images.githubusercontent.com/71445210/175470311-58cc0947-63e6-4901-9c66-502fe98bc9f5.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS Dev build 3.(72)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest Android Dev build 1.0(182)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.186

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA build 1.0(217)
