### ISSUE TITLE
[IDP] [PM] Participant details screen > UI Issue

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4648]
UI breakage is observed in the participant details screen

![pm](https://user-images.githubusercontent.com/86007179/175492976-5048157a-0cd5-48e1-a85a-4f92e5a20476.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this and close this.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
