### ISSUE TITLE
[iOS] Notifications > Participant is not entering into the mobile app in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4649]
Kill the app > Add activities and publish > After getting notification > click on the notification > user will be staying in the Mobile home screen > Not entering into the app

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation App is crashing for the above scenario

**Comment by Lathan-btc** [comment]
Activities screen is loading twice in the above scenario

**Comment by Lathan-btc** [comment]
Kill the app > Add activities and publish > After getting notification > click on the notification >User is navigating to the Studies list screen > User should be navigated to Study activities screen

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
