### ISSUE TITLE
Android Crashlytics Support required

### ISSUE THREAD

**Issue by mohangmk** [GoogleCloudPlatform/fda-mystudies#4650]
Android is not supporting Crashlytics . Please let me know whether it is already supported in 2.0.10

**Comment by naveenr-btc** [comment]
2.0.10 has necessary framework updates that's needed for crashlytics. once 2.0.10 is merged they can enable crashlytics if they wish to.

**Comment by mohangmk** [comment]
Based on his comment, we are closing this issue.
