### ISSUE TITLE
Complete mobile details need to be captured from Android and iOS devices 

### ISSUE THREAD

**Issue by mohangmk** [GoogleCloudPlatform/fda-mystudies#4651]
Currently, only mobile platform information is collecting in the database but this information is not sufficient to know the participant device details.

Please collect at least below details so that it will be useful for debugging the issues
1. Mobile Platform (iOS /Android)- Already capturing
2. Mobile device type ( iPhone11, iPhone 12, once plus 8 ......etc)
3. Mobile device OS versions

@blnkumar-btc Please assign this ticket to right developers

**Comment by akashkumarv3** [comment]
@GovindPrasadBostonTechnologyCorporation @Shashank-btc  Hi ,from backend all new required field  now are added
 "deviceType",
 "deviceOS",
"mobilePlatform" and mapped into "/studyState" API.

**Comment by Lathan-btc** [comment]
The feature is implemented in the latest iOS build 3.0(124) and it is working as expected

**Comment by nagarjunav1** [comment]
The feature is implemented in the latest Android build 1.0(196) and it is working as expected

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
