### ISSUE TITLE
[IDP] [SB] Admins > Add new admin > UI issue in add new admin screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4656]
**Pre-condition:** IDP should be disabled in the SB

**Steps:**
1. Login to SB
2. Click on 'Manage admins' icon
3. Click on 'Add new admin' button
4. Verify the email field

**AR:** Dropdown icon is getting displayed in the email field
**ER:** Dropdown icon should not get displayed in the email field

![uisb](https://user-images.githubusercontent.com/86007179/176379304-82270e70-2f57-4380-8f49-8c4f22b73a77.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
@Madhud5 
Dropdown icon should not get displayed in the email field, If IDP is disabled and Dropdown icon should get displayed in the email field, If IDP is enabled

**Comment by madhud-btc** [comment]
Hi @Lathan-btc please check and close this ticket.
thanks

**Comment by Lathan-btc** [comment]
@Madhud5 Dropdown icon is not getting displayed in PM even though IDP is enabled for PM


![image](https://user-images.githubusercontent.com/71445210/200322970-045a3779-25ee-4935-a56c-f5888d88af09.png)

**Comment by madhud-btc** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest SB IDP dev branch, when IDP and MFA is enabled

**Comment by bhoomikav16** [comment]
Issue is observed in PM IDP DEV branch, when IDP and MFA is disabled

**Note:** Issue is fixed in the latest SB IDP dev branch, when IDP and MFA is disabled

**Comment by madhud-btc** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest SB and PM IDP dev branch, when IDP and MFA is disabled

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
