### ISSUE TITLE
[IDP] [PM] A popup message is getting displayed when adding a new admin in the PM

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4657]
**Pre-condition:** IDP should be disabled in the PM

**Steps:**
1. Login to PM
2. Click on 'Admins' tab
3. Click on 'Add new admin' button
4. Complete all the fields
5. Click on 'Add admin user and invite' button and Verify

**AR:** A popup message is getting displayed when adding a new admin in the PM
**ER:** A popup message should not get displayed when adding a new admin in the PM

![PM](https://user-images.githubusercontent.com/86007179/176381596-d68a3faa-7ba9-4b25-b71d-5bf39b512e4a.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
Issue will be tested once https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4686 is fixed

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest IDP branch

**Comment by bhoomikav16** [comment]
A popup message is not getting displayed while adding a non-organizational admin in the PM

**Comment by madhud-btc** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest PM IDP dev branch, when IDP and MFA is enabled

**Comment by bhoomikav16** [comment]
Issue is reproducing in the latest PM IDP dev branch, when IDP and MFA is disabled

**Comment by madhud-btc** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest PM IDP dev branch, when IDP and MFA is disabled

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
