### ISSUE TITLE
[IDP] [SB] [PM] Deactivated admin > Error message should not get displayed 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4658]
**Pre-condition:** IDP should be disabled for the SB and PM

**Steps:**
1. Login to SB
2. Click on 'Manage admins' icon
3. Verify the deactivated admin in the admin list screen

**AR:** Error message is getting displayed when mouse hover on toggle button
**ER:**  Error message should not get displayed when mouse hover on toggle button

![admin](https://user-images.githubusercontent.com/86007179/176400218-16a630a7-bc3f-483d-a801-26d4fe140fd7.png)

**Note:** 
1. All the error messages with respect to IDP admin should not get displayed when IDP is disabled for the application
2. Issue needs to be fixed in PM also

**Comment by harisboston** [comment]
@bhoomikav16 Since this user was added when Idp was enabled, and its org user, so even after Idp is disabled. the above error message should display for org users.
So that Super admin will know that this is an org user and should be activated from the gcp Idp console only.

**Comment by bhoomikav16** [comment]
Closing this issue as per above comment
