### ISSUE TITLE
[PM] [Angular Upgrade] All the tabs should be aligned properly in the main screen of the participant manager

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4665]
Login to PM and Verify,
1. Alignment issue
**AR:** All the tabs such as  'Dashboard' , ' Locations' , 'Admins' , 'My Account' and also 'Search by site or study ID or name 'is not aligned properly in the main screen of the participant manager as per the design document
**ER:** All the tabs should be aligned properly in the main screen of the participant manager as per the design document
2. A line is getting displayed in all the tabs below , So it should not get displayed. It should be fixed throughout the application

**1.**

![PM](https://user-images.githubusercontent.com/86007179/177713995-8fbb041f-fdf0-43ff-9381-f3315e970ebd.png)

**2.**
![Untitled](https://user-images.githubusercontent.com/86007179/177784678-6ca40951-599e-456a-b184-ce57b93bc24f.png)

**Comment by Madhud5** [comment]
HI @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
