### ISSUE TITLE
[PM] [Angular Upgrade] Search bar > Search icon is not getting displayed 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4666]
**AR:** Search bar > Search icon is not getting displayed in the participant manager
**ER:** Search bar > Search icon should get displayed in the participant manager

**Note:** Issue needs to be fixed throughout the applications wherever search bar is available

![Searchicon](https://user-images.githubusercontent.com/86007179/177715751-8d290e35-1ec5-4c17-87fa-77878de7144a.png)

**Comment by Madhud5** [comment]
HI @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
