### ISSUE TITLE
[PM] [Angular Upgrade] Success message should get displayed at the center of the screen 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4667]
**AR:** Success message is getting displayed at the right corner of the screen 
**ER:**  Success message should get displayed at the center of the screen 

**Note:** Issue needs to be fixed for all the messages which are available in the participant manager

![Message](https://user-images.githubusercontent.com/86007179/177719297-eb67eed1-4cd7-4d3e-b454-250b5b10871d.png)

**Comment by Madhud5** [comment]
HI @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
