### ISSUE TITLE
[PM] [Angular Upgrade] 'Admins profile' icon is not getting displayed beside 'My account' tab

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4668]
**AR:** 'Admins profile' icon is not getting displayed beside 'My account tab
**ER:** 'Admins profile' icon should get displayed beside 'My account tab i.e., Admins first letter of first name should get displayed.

**Actual :**
![ICON](https://user-images.githubusercontent.com/86007179/177720781-b3bf2328-8cd6-44c2-8ef0-fcef58199fbd.png)

**Expected:**
![er](https://user-images.githubusercontent.com/86007179/177722182-eddbc9ef-ac8d-4e3f-a8d0-e8e62ee7e5a5.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
