### ISSUE TITLE
[PM] [Angular Upgrade] Password criteria should be aligned as per the design document

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4669]
Password criteria should be aligned as per the design document

**Note:**  Issue needs to be fixed wherever 'Password criteria' is available 

**AR:**
![password](https://user-images.githubusercontent.com/86007179/177725970-95ce898c-2c6c-4878-b450-f6b4c162561c.png)

**ER:**
![ERof_PC](https://user-images.githubusercontent.com/86007179/177726031-e21a59fb-9989-4540-977e-94ae98822159.png)

**Comment by Madhud5** [comment]
HI @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
