### ISSUE TITLE
[PM] [Angular Upgrade] My account > Change password > New password > Password view icon should get displayed

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4670]
My account > Change password > New password > Password view icon should get displayed

**Note:** Issue needs to be fixed wherever password view icon is getting displayed

**AR:**
![AR](https://user-images.githubusercontent.com/86007179/177728146-987a8684-16db-43cf-a30e-e312e7164531.png)

**ER:**
![er 1](https://user-images.githubusercontent.com/86007179/177728244-48823e1f-bfcf-4adf-a1ce-1f4de0f26547.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
