### ISSUE TITLE
[PM] [Angular Upgrade] My account > Change password > Password criteria > UI of password criteria message should be as per the design document

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4671]
My account > Change password > Password criteria > UI of password criteria message should be as per the design document

**Note:** Issue needs to be fixed wherever password criteria message is available

**AR:**
![messagecriteria](https://user-images.githubusercontent.com/86007179/177730936-7a51c577-7da7-45bb-ae7a-2e8be1413c31.png)

**ER:**
![erpc](https://user-images.githubusercontent.com/86007179/177730623-7bcc6ba8-4116-4f8d-813d-4765afa13c0c.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
