### ISSUE TITLE
[IDP] [PM] Null value is getting displayed in the phone number field in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4673]
**Pre-condition:** mfa should be disabled in the PM

**Steps:**
1. Login to PM
2. Add admin in the application
3. Click on account activation link of added admin
4. Set up account without 'Phone number' 
5. Login as added admin 
6. Navigate to 'My account' screen and Verify

**AR:** Null value is getting displayed in the phone number field in the following scenario
**ER:** Phone number field should be empty without any value

![null](https://user-images.githubusercontent.com/86007179/177759020-45e4b60d-0a87-40d6-859d-e9bb412cc181.png)

**Comment by Madhud5** [comment]
Hi @harisboston  your sending null values when mfa false pls handle it from backend. 
dont send null values. 
![image](https://user-images.githubusercontent.com/59555917/180752513-006631bb-4a3e-4153-97ec-65fc24d39c33.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
