### ISSUE TITLE
[PM] [QA] Getting server error for the participant manager

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4675]
Getting '502 Server Error' for the participant manager in QA instance

![server](https://user-images.githubusercontent.com/86007179/177997009-5d737df9-481b-4fe7-b31f-f1c056ebc20c.png)

**Comment by harisboston** [comment]
@bhoomikav16 As devops team is working on deployment file changes, so PM is down currently, will update once fixed.

**Comment by yugandhar-btc** [comment]
@sheelakanni97 @bhoomikav16 @harisboston The PM is up and running in QA, please verify.

CC @mohangmk

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA instance

**Comment by yugandhar-btc** [comment]
@bharathkkb @sheelakanni97 Could you please check now and confirm

**Comment by sheelakanni97** [comment]
@Yugandhar Eekati ***@***.***>  Now it is working
fine.
Thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
