### ISSUE TITLE
[PM] [Angular Upgrade] Dashboard > Sites > UI issue

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4676]
UI issue is observed in the 'Sites' screen i.e., Alignment is not proper

**AR:**
![AR](https://user-images.githubusercontent.com/86007179/178000649-b3b43df1-dc09-46e7-a67d-541b3fd90430.png)

**ER:**
![Screenshot (1782)](https://user-images.githubusercontent.com/86007179/178001340-61c6a01d-4977-48d4-aca1-019f526d2e5c.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest build

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
