### ISSUE TITLE
[Android] [Angular Upgrade] Getting 'Invalid data sharing status' error message in the consent flow

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4677]
**Steps:**
1. Sign in and complete the passcode process
2. Enroll to the study
3. Now, go back to SB 
4. Edit the study for which participant has enrolled 
5. Update 'Enforce e-consent flow again for enrolled participants' and Publish the study
6. Open the mobile app
7. Try to complete the consent flow and Verify

**AR:** Getting 'Invalid data sharing status' error message in the consent flow
**ER:** Participant should be able to complete the consent flow without any error's

![Android](https://user-images.githubusercontent.com/86007179/178019280-d11fda88-3cb0-4055-8812-d49ca631f36e.png)

**Comment by Shashank-btc** [comment]
Hi,

/studyState api we are not getting the variable "DataSharingPermission"

thanks

**Comment by akashkumarv3** [comment]
@bhoomikav16 Hi Bhoomika ,this is new implementation which done in FHIR Branch .So Once all changes  will move to GCP Dev it will resolved Automatically. Check this issue after moved in GCP dev.

**Comment by bhoomikav16** [comment]
Issue will be tested once all changes has move to GCP Dev as per the above comment

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA build 1.0(217)
