### ISSUE TITLE
[PM] [Angular Upgrade] Dashboard > Sites > Site participant registry > UI issue 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4678]
UI issue is observed in 'Site participant registry'

![image](https://user-images.githubusercontent.com/86007179/178207416-6b009777-4471-4b1b-a5d1-069f9247a1ef.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check this issue in dev and let me know.
thank you

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest Dev build

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA build
