### ISSUE TITLE
[PM] [Angular Upgrade] Sites > Add site > Select location > Scroll bar is not getting displayed

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4679]
**AR:**  Sites > Add site > Select location > Scroll bar is not getting displayed in the dropdown
**ER:** Sites > Add site > Select location > Scroll bar should get displayed in the dropdown

![PM](https://user-images.githubusercontent.com/86007179/178266169-ec2945a9-cbf7-4144-902e-566f83c3fd6f.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 scroll will appear once number of options list is more. pls check and close this

**Comment by bhoomikav16** [comment]
As per above comment, Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
