### ISSUE TITLE
[iOS] [Offline indicator] Sign in screen > Empty screen is getting displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4680]
Steps:
1. Install the app and open the app
2. Click on the 'Get started' 
3. Click on the Hamburger menu button
4. Click on 'Signin'
5. Blank screen is getting displayed with a 'You are offline' message
6. Turn on the data and observe

AR: Blank screen is getting displayed even though user turn on their mobile data
ER: Sign in page should get a load

Refer to the attached video

https://user-images.githubusercontent.com/71445210/178304851-3e80bd15-49c3-40f8-9aed-f60f73332919.MOV

**Comment by Lathan-btc** [comment]
Sign in button is enabled when the participant is offline until he/she clicks on the Sign in > Sign in button should be disable

![image](https://user-images.githubusercontent.com/71445210/179455913-b2595b00-b96c-4cb8-a628-ea5e6093901f.png)

**Comment by nishit-v** [comment]
Since in webview, there is no control to handle individual buttons, working as expected .

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
