### ISSUE TITLE
[iOS] [Offline indicator] Error message is not getting displayed for the following

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4682]
Steps:
1. Sign in to the app
2. Click on the enrolled study
3. Turn off the data
4. Click on the Activity
5. Observe

AR: Offline error message is not getting displayed
ER: 'Seems to be offline...' error message should get displayed to the user

Note:
The issue should also be fixed when the user clicks on the 'View website', 'Terms' 'Privacy policy' etc.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
