### ISSUE TITLE
[iOS] [Offline indicator] Enrollment flow > Offline error message should get displayed when participant clicks on the 'Next' button on the signature screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4684]
Steps:
1. Signup or sign in to the app
2. CLick on the Study
3. Turn off the internet
4. Complete all the steps in the enrollment flow
5. On the signature screen, click on Next and observe

AR: Screen is continuously loading
ER: Offline error message should get displayed when participants click on the Next button present on the Signature screen

![image](https://user-images.githubusercontent.com/71445210/178414243-c103145f-1f23-4fb0-8adc-5c0c36625eca.png)

**Comment by amruthbtc** [comment]
Enrollment flow is not suppose to work in offline, we are not saving the data locally, we are restricting at the entry point itself, There is a limitation in controlling the enrolment flow without internet, so need BA input for alternative flow.

**Comment by nishit-v** [comment]
@amruthbtc Please assign to Harshith and check the flow

**Comment by amruthbtc** [comment]
@Lathan-btc @nishit-v There is a flow change in the enrolment flow. Enrollment flow is not suppose to work in offline, we are not saving the data locally, we are restricting the usr at the entry point itself, There is a limitation in controlling the enrolment flow without internet, so we made a flow change when there is no internet, as during the enrolment flow, if we lost internet we have to exit from the enrolment process, if any further actions are proceeded without internet. We need BA Confirmation for this alternative flow.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest IOS dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
