### ISSUE TITLE
[iOS] [Offline indicator] Share button should be disabled in the below mentioned screens when participant is offline

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4685]
Share button should be disabled in the below mentioned screens when the participant is offline
1. App glossary
2. Dashboard
3. Consent pdf ( both resources screen and study overview screen)

![image](https://user-images.githubusercontent.com/71445210/178414692-938d662b-29d7-4d77-bece-14d6e2fc2e6c.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest dev iOS build V3.0.82

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
