### ISSUE TITLE
[IDP] [PM] Getting 'An internal error has occurred' message in participant manager when tried to sign in

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4686]
**Pre-condition:** idp and mfa should be enabled in the PM

**Steps:**
1. Add organizational user in the participant manager
2. Complete set up your account process
3. Sign in with registered credentials and Verify

**AR:** Getting an internal error has occurred message when tried to sign in
**ER:** Admin's should be able to sign without any error's

![Untitled](https://user-images.githubusercontent.com/86007179/178441102-f1d47479-b1ad-4661-b31b-5abde48b9b46.png)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

![Untitled](https://user-images.githubusercontent.com/86007179/179150139-0b368b66-a0c8-4eaf-abdb-12b3ffaf243a.png)

**Comment by harisboston** [comment]
@bhoomikav16 This issue was happening because the phone number was not getting saved in DB because of a bug.
Please create a new user to test.

**Comment by Lathan-btc** [comment]
Issue will be tested once after fixing the #5024 issue

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP dev branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP QA branch
