### ISSUE TITLE
[Android] [Offline indicator] Share button should be disabled in the below mentioned screens when participant is offline

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4693]
Share button should be disabled in all the below mentioned screens when the participant is offline

1. App glossary
2. Dashboard
3. Consent pdf ( both resources screen and study overview screen)

![Screenshot_20220712-173058_FDA MyStudies](https://user-images.githubusercontent.com/86007179/178485547-70573203-9eec-47ee-a7e9-5e0af8606091.jpg)

**Comment by bhoomikav16** [comment]
Share button is not disabled in the enrollment flow

**Comment by Shashank-btc** [comment]
Hi,

For the share button in the consent flow,
when user come to consent complete screen and when user click on "view/email eConsent PDF" it will check the internet connection at the time of click on this  "view/email eConsent PDF" base on this share button will disable but not when the user in pdf screen

Thanks
Shashank

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev build 1.0(185)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA build 1.0(217)
