### ISSUE TITLE
[iOS] [Offline indicator] 'You are offline' error message is not getting displayed when participant clicks on the Notifications

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4695]
AR: Blank screen is getting displayed and the 'You are offline error message is not getting displayed when the participant clicks on the Notifications if a participant is offline
ER: You are offline error message should get displayed

![image](https://user-images.githubusercontent.com/71445210/178506443-9d3b4ee5-d756-476b-af37-28658828a8ec.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest dev iOS build V3.0.82

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
