### ISSUE TITLE
[iOS] [Offline indicator] Participant is navigating to the Study lists screen when participant clicks on Review button in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4696]
Steps:
1. Signup or Sign in to the mobile
2. Enroll to the study
3. in SB, Update the consent for the enrolled participant
4. Click on the Enrolled study in the mobile app
5. Turn off the internet
6. Click on the Review and observe

AR: Participant is navigating the Study list screen and an offline error message is getting displayed
ER: Offline error message should get displayed

**Comment by nishit-v** [comment]
Issue is still reproducible in latest dev iOS build V3.0.82

**Comment by amruthbtc** [comment]
Issue fix available in 3.0 (98) build

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0(98)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
