### ISSUE TITLE
[Android] [Offline indicator] Participant is navigating to the Study activities screen when participant clicks on updated consent for the enrolled study 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4700]
**Steps:**
1. Signup or Sign in to the mobile
2. Enroll to the study
3. In SB, Update the consent for the enrolled participant
4. Click on the Enrolled study in the mobile app
5. Turn off the internet
6. Click on the Review and observe

**AR:**  Participant is navigating the Study list screen and an offline error message is getting displayed
**ER:**  Offline error message should get displayed

**Comment by Shashank-btc** [comment]
Hi,
The above mention flow will block the offline capabality .

Thank you

**Comment by bhoomikav16** [comment]
Closing this ticket as it is valid scenario
