### ISSUE TITLE
[iOS] [Offline indicator] Enrollment flow > the following offline error message should get displayed when user is offline in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4703]
Steps:
1. Sign up or sign in to the mobile app
2. Click on the study
3. Click on the Participate
4. Turn off the data and observe

AR: Offline error message is not getting displayed
ER: 'You are offline, You can still use this section but may miss out on the latest content updates' error message should get displayed

[Note: Issue should be fixed for Open study closed study and consent update after clicking on the review button]

For error message UI please refer to the following attached screen

![image](https://user-images.githubusercontent.com/71445210/179159298-8c22a1bc-e101-46b8-801a-41cf0298c87e.png)

**Comment by amruthbtc** [comment]
This is an online capable screen, we don't need to show long message as per BA. Anchored toast message is showing in this scenario

**Comment by nishit-v** [comment]
Issue is still reproducible in latest dev iOS build V3.0.82.

AR: Offline error message is not getting displayed
ER: 'You are offline, You can still use this section but may miss out on the latest content updates' error message should get displayed

![IMG_3099](https://user-images.githubusercontent.com/60386291/179532000-9ba29d80-9efa-46d6-bcbb-9636e7584ad1.PNG)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
