### ISSUE TITLE
[Android] [Offline indicator] There should be consistency in offline error message which is getting displayed for terms and privacy policy screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4705]
There should be consistency in offline error message which is getting displayed for terms and privacy policy screen
i.e., There are two different screens which are getting dispalyed for terms and privacy policy screens

**First screen:**

![Screenshot_20220715-131709_FDA MyStudies](https://user-images.githubusercontent.com/86007179/179180374-4fee4287-72cd-4807-ac88-951f38c9fd4b.jpg)

**Second screen:**

![Screenshot_20220715-132117_FDA MyStudies](https://user-images.githubusercontent.com/86007179/179180383-b4b1b5c7-cdb0-4c22-a9bc-722171379cd0.jpg)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev build 1.0(185)

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
