### ISSUE TITLE
[Mobile apps] unable to enroll to the study 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4707]
unable to enroll to the study  > getting the following error message

![image](https://user-images.githubusercontent.com/71445210/179495030-7df8e4db-e67f-4cfc-b7ce-19e0fe2a29b6.png)

**Comment by Lathan-btc** [comment]
Not able to enroll to the old studies

**Comment by harisboston** [comment]
@Lathan-btc Because of other blocker issues and  change in the dataset name, enrollment flow will not work for old studies, as currently it is in the development phase only.

**Comment by Lathan-btc** [comment]
As per the above issue closing the issue
