### ISSUE TITLE
[Mobile apps] Study activities are not getting loaded for enrolled studies

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4708]
Study activities are not getting loaded for enrolled studies - Getting continuous loading

![image](https://user-images.githubusercontent.com/71445210/179495423-1a1f2f78-fc70-49e8-8552-a8c084a7a99d.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS and Android builds.
