### ISSUE TITLE
[SB] Add/edit questionnaire > Unable to add/edit and update/delete the questionnaire

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4709]
AR: Add/edit questionnaire > Unable to add/edit and update/delete the questionnaire > Getting server error
ER: Admin should be able to add/edit and update/ delete the questionnaires successfully

![image](https://user-images.githubusercontent.com/71445210/179516715-064d1c7b-5eab-447a-b4e3-7e9edde98de9.png)

**Comment by Lathan-btc** [comment]
The issue is reproducible in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev environment

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance.

**Comment by harisboston** [comment]
Issue is fixed in dev env, and will keep under observation for a few days. @Lathan-btc Please update here the screen/section if this issue happens again.

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is not reproducible in the latest Dev instance

**Comment by bhoomikav16** [comment]
The issue is still reproducible in the latest Dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
