### ISSUE TITLE
[SB] Add/edit notification > Unable to add/edit and update/delete the notification

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4711]
AR: Add/edit notification > Unable to add/edit and update/delete the notification and getting the server error

ER: Admin should be able to add/edit and update/delete the notification(s) successfully
![179517165-9f8869c7-1b7e-407c-97b4-c77c9baecf1e](https://user-images.githubusercontent.com/60386291/179517967-6c872122-84b5-4503-97f2-b4da256c65a6.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
