### ISSUE TITLE
[PM] [Consent API] Consent pdf is not getting displayed in the participant manager

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4712]
**Steps:**
1. Install the mobile app
2. Sign in / Sign up
3. Enroll to the study
4. Now, Go back to PM
5. Go to participants details screen and Verify

**AR:**  Consent pdf is not getting displayed in the participant manager
**ER:** Consent pdf should get displayed in the participant manager

![pm](https://user-images.githubusercontent.com/86007179/179538108-401e25c7-8abf-4855-bf98-2ddc9dcbc214.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
