### ISSUE TITLE
[iOS] [Offline indicator] Toast message is displayed instead of pop-up message in below scenario

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4713]
**Steps:**

1. Install the app
2. Don't sign in/signup
3. Click on any study
4. Switch off the internet
5. Click on 'Participate'
6. Observe

**Actual:** Toast message 'You are offline' is displayed in sign in screen

**Expected:** Pop-up message 'You seem to be offline. Please connect to a network to proceed with this action.' pop-up should be displayed

**Issue not observed for logged in users**

Actual:
![IMG_3102](https://user-images.githubusercontent.com/60386291/179543178-9656a690-efbd-439f-8717-28632f8b5091.PNG)

Expected pop-up screen:
![Screenshot 2022-07-18 at 8 41 23 PM](https://user-images.githubusercontent.com/60386291/179543354-15421bf4-a875-4c2a-af60-755d8081fff0.png)

**Comment by amruthbtc** [comment]
We can disable the participate button

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0(83)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
