### ISSUE TITLE
[Consent API] Cloud storage > Unsigned document > Issue related to consent version in the naming convention of the unsigned document

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4716]
Publish the study for the fourth time in the study builder and Verify the naming convention of unsigned document in the cloud storage.

**AR:** Consent version is getting displayed as "1.3000001" in cloud storage
**ER:**  Consent version should be displayed as "1.3" in cloud storage

**Note:**
1. Issue is observed only when published the study for fourth time.
2. Issue is not observed for other published version.

**Screenshot of the issue:**
![image](https://user-images.githubusercontent.com/86007179/179722095-c7051752-6d66-45e3-8610-94efdf7f437f.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
