### ISSUE TITLE
[Consent API] [PM] Data sharing permissions is getting displayed as N/A in the participant manager in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4718]
**Steps:**
1. Install the mobile app
2. Sign in / Sign up
3. Enroll to the study
4. Now, Go back to SB
5. Select 'Enforce e-consent flow again for enrolled participants' in the SB and Publish the study
6. Open the mobile app and submit the updated consent flow 
7.  Login to PM
8. Go to participants details screen and Verify

**AR:**  Data sharing permissions is getting displayed as N/A in the participant manager in the following scenario
**ER:** 
Data sharing permissions should get displayed as,
1. Provided > If participants has provided the data sharing permission in the mobile app
2. Not Provided >  If participants has not provided the data sharing permission in the mobile app
3. Not Applicable > If there is no data sharing record available for the participant

![Untitled](https://user-images.githubusercontent.com/86007179/179900626-ed043f87-e8ea-45de-a246-e9757d65b1e1.png)

**Comment by bhoomikav16** [comment]
Issue will be tested once [4736](https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4736) is fixed in the dev build

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
