### ISSUE TITLE
[Consent API] [SB] E-Consent steps > Data sharing permission > UI Issue in 'Explanatory text that can be provided in a 'Learn more' section'

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4720]
UI issue is observed in 'Explanatory text that can be provided in a 'Learn more' section' field

**AR:** 

![UI](https://user-images.githubusercontent.com/86007179/179911065-e95780d0-1871-470e-91a2-6a2a7463cdf3.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
