### ISSUE TITLE
[Mobile apps] Not able to delete the participant account > Error message is getting displayed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4723]
AR: Not able to delete the participant account > Error message is getting displayed
ER: Participants should be able to delete their app account 

![image](https://user-images.githubusercontent.com/71445210/179921432-93c43611-c6ed-4274-b307-888f636bda6b.png)

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
