### ISSUE TITLE
[iOS] Review consent should not get displayed for the enrolled users in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4724]
Steps:
1. Create a study in SB and launch the study
2. Click on edit study
3. Update the consent and enforce the consent for the enrolled participant
4. Publish the update
5. Launch the mobile app and sign up or sign in to the mobile app
6. Click on the particular study
7. Enroll to the study
8. Go back to the study list screen
9. Again click on the enrolled study 
10. Observe

AR: The review consent popup is getting displayed to the newly enrolled participants in the above scenario
ER: The review consent popup should not be displayed to the newly enrolled participants in the above scenario

![image](https://user-images.githubusercontent.com/71445210/179925289-567f4aad-77e7-41b1-b341-e1865e771410.png)

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0(99)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
