### ISSUE TITLE
[Consent API] [iOS] Study resources screen > Participants should be able to view and download the data-sharing consent screenshot, in the mobile app

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4725]
**Description:**
Pre-condition: The study should be created in SB by enabling data sharing permission

**Steps:**
1. Install the mobile app
3. Sign in / Sign up
4. Enroll to the study 
5. Navigate to 'Study Resources' screen and Verify

**AR:** Participants are not able to view and download the data-sharing consent screenshot, if applicable, from the Study Resources screen
**ER:**  Participants should be able to view and download the data-sharing consent screenshot, if applicable, from the Study Resources screen

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.189
