### ISSUE TITLE
[Consent API]  State is getting displayed as 'Active' in the following scenarios

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4726]
State should be changed in primary consent when withdrawn from the study

**AR:**  State is getting displayed as 'Active'
**ER:**  State should be displayed as 'Revoked'

**Note:** Issue needs to be fixed even when participants deletes their app account

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
