### ISSUE TITLE
[Participant Manager] Participant details screen is not working for Closed study

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4728]
Steps:- 
1. Login into PM
2. Navigate to any closed study 
3. Navigate to Participant details screen from any site and observe

A/R:- Getting error message in Participant details
E/R:- Participant details should be displayed without any error message

Note:- Issue is not observed for open study

![image](https://user-images.githubusercontent.com/60500517/179978623-ee8ffdef-7ce0-49f8-a61d-d1376397a3b5.png)

**Comment by harisboston** [comment]
@nagarjunav1 Above issue id happening for old studies, if google healthcare consent is enabled. 
Handled the app crash issue but consent record will be empty for old studies.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
