### ISSUE TITLE
[iOS] Unable to signup or signin into iOS mobile app

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4729]
Unable to signup or signin into iOS mobile app V3.0(83) and 3.0(84)

**Issue not observed in Android**

Refer below screenshots and video
![IMG_3110](https://user-images.githubusercontent.com/60386291/179990817-ac858dd4-bc91-4973-b487-3f882c73fbbd.PNG)

https://user-images.githubusercontent.com/60386291/179992025-c8490965-26d7-4947-8c5c-b178cf7d3969.MOV

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
The issue is not reproducible now. Keeping it under obervation.

**Comment by nishit-v** [comment]
Issue is again observed now. Time frame : 10:46 AM to 10:52 AM IST 21/07/2022

**Comment by nishit-v** [comment]
Above issue is not reproducible in latest Dev environment.
