### ISSUE TITLE
[Consent API] [Mobile apps] [Standalone app] Consent API Enabled > Getting 'No data available' in the data sharing image screen in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4730]
**Steps:**
1. Sign in / Sign up 
2. Enroll to the study
3. Leave the study / Delete the app account
4. Again , create account with same email
5. Enroll to the study
6. Navigate to 'Resources' screen
7. Click on 'Data sharing image' and Verify

**AR:** Getting 'No data available' in the data sharing image screen in the following scenario
**ER:**  'Data sharing image' should get displayed

**Note:**  Issue is observed in the consent pdf also 

![image](https://user-images.githubusercontent.com/86007179/180159092-9f092e73-168c-4e48-a0d6-9b12015ab345.png)

**Comment by Shashank-btc** [comment]
Hi,

getting 400 error when user try to open the datasharing image in resours screen

https://participants.btcsoft-dev.boston-technology.com/participant-consent-datastore/consentDocument?studyId=STwithDSEnable&consentVersion=

heders:
Authorization -> Bearer vFXo0P-DMpVen2L10vApzOwWvzUYLhchn1AAAeoUwbg.6dYfWMuNrt67Bivu6N7TgZD18v-I_eL1IRWoNQYnIpI

userId -> e7311429f512314c41hb697ga9e41af4df6c


response -400;

Thanks

**Comment by akashkumarv3** [comment]
Hi    ,We will update this ticket when consent API is enabled .

**Comment by Shashank-btc** [comment]
Hi

now from tne back end they resoved the Consent PDF display in the resources
only Data sharing image is not work,

we will chekc this when consent API is enabled 

Thanks

**Comment by akashkumarv3** [comment]
Issue is fixed now from backend .

**Comment by Shashank-btc** [comment]
HI 

@bhoomikav16 can you please check this issue in 186th build this is fixed from backend


Thanks

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation Please provide the standalone build to test this issue.

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest Android standalone Dev build v1.0(186)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest Android standalone QA build v1.0(219)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA build 3.0(191)
