### ISSUE TITLE
[iOS] [Consent API] Gateway app > App is is crashing in the below scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4731]
Steps:
1. Install the app
2. Create the account
3. Enter a valid verification code
4. Create a passcode
5. Click on Next 
6. Select any value displayed on the notification settings pop up
7. Observe

AR: App is crashing 
ER: Participant should be able to navigate to the studies list screen

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
As discussed this is due to memory issue occuring due to mude data of GCPDEV001 appid. This wont be observed in other AppIDs. Once other functionalities are tested will provide build for other APP Id.

**Comment by Lathan-btc** [comment]
Issue is not observed in the latest Build with the latest App ID
