### ISSUE TITLE
[iOS] [Offline indicator] Issues related to offline message in consent PDF while enrolling into study

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4733]
Steps:
1. Signup/login
2. Enroll into the study
3. Navigate till enrollment completion screen
4. Click on View consent
5. Switch off the internet

Actual: 
1. You are offline message is displayed on top
2. Share button is enabled

Expected:
1. Toast message should be displayed instead of message on top
2. Share button should be disabled

Refer screenshot
![IMG_3117](https://user-images.githubusercontent.com/60386291/180207794-cc2e2880-be72-449b-927b-7488e9c88a39.PNG)

**Comment by amruthbtc** [comment]
Issue fixed in 3.0.97 build

**Comment by amruthbtc** [comment]
Issue fix available in 3.0 (98) build

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0(98)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
