### ISSUE TITLE
[iOS] [ Consent API] Consent API disabled > Study resources screen > Data sharing image > previously selected option is getting displayed in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4734]
**Description:**

**Pre-condition** - The study should be created by enabling data sharing permission

**Steps:**
1. Sign up or sign in to the mobile app
2. Enroll to the study [eg: on the data sharing permission screen select 'provided']
3. Withdrawn from the study
4. Rejoin the same study [ on the data sharing permission screen select 'Not provided']
5. Click on the Study resources screen
6. Click on Data sharing image and observe

**AR:** Previously selected screenshot is getting displayed ( as per the above scenario provided option is selected in the captured screenshot)
**ER:** As per the above scenario, Not provided status should be selected on the data sharing image

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
waiting for issue #4730  deployment

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev build
