### ISSUE TITLE
[Consent API] Consent API Disable > Cloud Storage > Data sharing image is not getting displayed in the cloud storage in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4735]
**Pre-Condition:** Study should be created with the data sharing permission

**Steps:**
1. Install the mobile app
2. Sign in / Sign up
3. Enroll to the study by providing data sharing permission
4. Withdraw from that study 
5. Again enroll to the same study without providing data sharing permission
6. Now, Go to Cloud storage 
7. Search the studyID in the consent bucket
8. Click on the participant record and Verify

**AR:**  Data sharing image is not getting displayed in the cloud storage in the following scenario
**ER:**  Data sharing image should get displayed in the cloud storage in the following scenario

**Note:** Issue needs to be fixed even when without providing data sharing permission in step 3 and by providing data sharing permission in step 5 scenario

**Comment by akashkumarv3** [comment]
Hi , We will update this ticket when consent API is enabled .

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
