### ISSUE TITLE
[iOS] [Standalone] 'Review' consent popup is getting displayed on sign in screen in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4744]
Steps:
1. Signup or sign in to the mobile app
2. Enroll to the study
3. In SB, update the consent for enrolled participants and publish the study updates
4. Go to the mobile app
5. Minimize the app once after getting the 'Review' consent popup
6. Maximize the app
7. On the Passcode screen, click on ### 'Forgot passcode? Sign in again and observe

AR: 'Review' consent popup is getting displayed on the sign-in screen
ER: 'Review' consent popup should not be displayed on the sign-in screen

![image](https://user-images.githubusercontent.com/71445210/180446274-bb711bea-c6a3-4b70-b050-80a1e4597cf5.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0(99)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.186
