### ISSUE TITLE
[Participant manager] [Study participant registry] Searched results are not displaying for few participant email address

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4745]
Steps:- 
1. Login into PM
2. Navigate to Study participant registry
3. Search for the participant email similar to **abc+1@xyz.com** which is available in the added participant email list in the Search bar and observe

A/R:- Displaying as 'No records found' 
E/R:- App should display search results if the email is available in the list for that study

![image](https://user-images.githubusercontent.com/60500517/180450428-79f3bafa-281c-4e3c-b4a6-4bf26f754ad9.png)
![image](https://user-images.githubusercontent.com/60500517/180450685-a796459c-b251-4ac2-96b5-71b02859b135.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
