### ISSUE TITLE
[Consent API] [Android] Data sharing image > UI Issue in the data sharing image screenshot in the mobile app

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4751]
**Pre-condition -**  The study should be created by enabling data sharing permission

**Steps:**

1. Sign up or sign in to the mobile app
2. Enroll to the study [eg: on the data sharing permission screen select 'provided']
3. Withdrawn from the study
4. Rejoin the same study [ on the data sharing permission screen select 'Not provided']
4. Click on the Study resources screen
5. Click on Data sharing image and observe

**AR:** Data sharing image > UI Issue in the data sharing image screenshot in the mobile app

![ma](https://user-images.githubusercontent.com/86007179/180783300-1a98c7ee-41a6-414f-afa3-19622016b9ad.png)

**Comment by nagarjunav1** [comment]
Issue is fixed now in Android Dev build v1.0(186)

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
