### ISSUE TITLE
[PM] Locations > Search bar placeholder text should be changed

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4753]
Actual: "Search location"

Expected: "Search by location ID or name"

Note: Functionality wise, search results are getting displayed if admin searches by location ID or location name and hence we have to specify both in placeholder

![Screenshot_4](https://user-images.githubusercontent.com/60386291/180806981-1aff1033-3c93-49eb-b32f-d9f2795fbee5.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in latest QA build
