### ISSUE TITLE
[SB] Manage studies > Questionnaires section > Add question step / form step > UI Issue is observed in all the screens

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4754]
**Steps:**
1. Create / Edit the study
2. Navigate to Questionnaires section
3. Add / edit the Questionnaires 
4. Click on Add question step / form step and Verify all the screens

**AR:** Manage studies > Questionnaires section > Add question step / form step > UI Issue is observed in all the screens
**ER:** Manage studies > Questionnaires section > Add question step / form step > UI of all the screen should be according to the design document 

![SB_UI](https://user-images.githubusercontent.com/86007179/180934660-234e40d3-4012-4515-9528-dac317299fe6.png)

**Comment by Lathan-btc** [comment]
@sheelakanni97 Issue is reproducible for instruction step

![image](https://user-images.githubusercontent.com/71445210/181274879-3963b3b1-8ad0-423b-8aae-742fabd09133.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
