### ISSUE TITLE
[Cross Browser] [PM] Site participant registry > Add participants > Import email list > 'Choose file' popup is not getting displayed in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4756]
**Steps:**
1. Open the 'Firefox' browser
2. Enter the PM URL
3. Login to the application
4. Click on site and navigate to 'Site participant registry'
5.  Click on 'Add participants' button
6. Click on 'Import email list' button
7. Click on 'Choose file' and then cancel the window which got displayed to choose the file and Verify

**AR:** Choose file popup which was available is not getting displayed in the following scenario
**ER:** Choose file popup which was available should get displayed in the following scenario

**Note:** Issue is observed only in 'Firefox' browser

**Comment by Madhud5** [comment]
Hi @bhoomikav16 Firefox library functionality behaves in same manner for security purpose and also its more restricted library functionality which we cont. customize scripts in it. so please check and close this ticket. thank you

**Comment by bhoomikav16** [comment]
As per the above comment, Closing this issue
