### ISSUE TITLE
[Consent API] [iOS] Updated consent is getting displayed to the enrolled participant in the following scenarios

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4758]
Steps:
1. Sign up or sign in to the mobile app
2. Enroll to the study
3. Navigate to the Study resources screen or Dashboard
4. In SB, update the consent for enrolled participants
5. In the Mobile app, Navigate to the Study activities screen and observe

AR: Updated consent is not getting displayed to the enrolled participants
ER: Updated consent should get displayed to the enrolled Participants

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.189
