### ISSUE TITLE
[PM][Cross browser] UI issue in the Change password screen in Microsoft edge browser

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4759]
Steps:- 
1. Login into PM
2. Naviagte to My account 
3. Click on Change Password link 
4. Enter the data in the Password fields and observe

A/R:- Black coloured extra icon is displaying near the eye icon
E/R:- No extra icons should be displayed near eye icon

**Note**:- Issue only observed in Edge browser

![image](https://user-images.githubusercontent.com/60500517/180989917-d5a2176f-8a5a-48bc-99af-20c8e76d57de.png)

**Comment by Madhud5** [comment]
Hi @nagarjunav1 please check this issue and close it.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
