### ISSUE TITLE
[iOS] [Consent API] Cloud storage > Data sharing image PDF is not getting generated in the Cloud storage when Consent API is enabled

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4760]
Steps:
1. Sign up or sign in to the mobile app
2. Enroll to the study (Study should be created by enabling data sharing permission)
3. Go to the cloud storage and observe

AR: Data sharing image PDF is not getting generated in the cloud storage
ER: Data sharing image PDF should get generated in the cloud storage

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation Issue is reproducible in the latest Dev build

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev build

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA  build
