### ISSUE TITLE
[PM] Sign in screen > Password field > 'Eye' icon is not getting displayed in the following browsers

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4763]
Sign in screen > Password field > 'Eye' icon is not getting displayed in the following browsers

1. Chrome
2. Safari
3. Firefox

**Comment by Madhud5** [comment]
Hi @Lathan-btc issue fixed please check and let us know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
