### ISSUE TITLE
[PM] [Edge browser] Sign in screen > Password field > 'Eye' icon is not getting displayed in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4764]
Steps:
1. Open the edge browser
2. Enter the PM test URL
3. Enter a valid email id
4. Click on the Password field and enter the password
5. Click on somewhere on the screen
6. Again click on the Password field and observe

AR: 'Eye' icon is not getting displayed 
ER: 'Eye' icon should get displayed to the user

**Comment by Madhud5** [comment]
Hi @Lathan-btc issue fixed please check and let us know.
thank you

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance
