### ISSUE TITLE
[DID] Questionnaire responses > Responses are not getting mapped into DID datastore even though DID is Enabled

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4773]
Steps:
1. Signup or sign in to mobile app
2. Enroll to the study
3. Submit the responses only for active tasks
4. Go to the Response server
5. Go to DID datastore 
6. Click on QuestionnaireResponse and Patient and observe

AR: Questionnaire responses > Responses are not getting mapped into DID datastore
ER: Questionnaire responses > Responses should get mapped into DID datastore

**Comment by nagarjunav1** [comment]
Issue is still reproducing in the latest build

**Comment by akashkumarv3** [comment]
Issue is fixed now

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
