### ISSUE TITLE
[FHIR] JSON > Time is getting displayed in different time zones for 'Date' and 'lastupdated'

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4776]
JSON > Time is getting displayed in different time zones for 'Date' and 'lastupdated'

Date:
![image](https://user-images.githubusercontent.com/71445210/181714157-63711742-f72c-4741-aab1-7cdf9da0e995.png)

Lastupdated:

![image](https://user-images.githubusercontent.com/71445210/181714471-744bba28-29f8-439a-92d1-09cfa0e53f09.png)

**Comment by harisboston** [comment]
@Lathan-btc Date is lastmodified date of questionnire in study builder.
meta: {lastUpdated} is last modified date of questionnire  resource in healthcare APi, when study was published to create or update questionnire resource.

**Comment by Lathan-btc** [comment]
As per the above comment QA is closing the issue
**Note:**
Activities start and end date are getting displayed in the Server timezone and last updated date is getting displayed in GMT timezone
