### ISSUE TITLE
SB > Getting error's while publishing updates in the study builder for following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4778]
**Steps:**
1. Edit the study
2. Navigate to Questionnaires section
3. Delete the Questionnaires response and mark section as complete 
4. Publish the updates and Verify

**AR:** Getting '502 Server Error' for the study builder in dev instance when reload the page / Action screen is loading continuously / Session is getting expire
**ER:** Publish updates should work fine without any error's

**1.** 
![SB](https://user-images.githubusercontent.com/86007179/181749285-a98a649a-720d-4342-8501-e09383f371f3.png)

**2.**
![image](https://user-images.githubusercontent.com/86007179/181746578-d5a890f0-a831-4646-a97f-8491d51d84c0.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
issue is fixed in the latest QA instance
