### ISSUE TITLE
[FHIR] Questionnaire resource > 'Type' should be 'Boolean' for the Boolean response type

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4779]
Questionnaire resource > 'Type' should be 'Boolean' for the Boolean response type

![image](https://user-images.githubusercontent.com/71445210/181773761-494996f5-380d-4cd3-b7f3-6c6fbc0d40e0.png)

**Comment by harisboston** [comment]
As per fhir standards, type should be one of the below following. It can not be boolean, In linkId booleanis already present, so will keep type as 'choice' only.

type ='choice' or type = 'open-choice' or type = 'decimal' or type = 'integer' or type = 'date' or type = 'dateTime' or type = 'time' or type = 'string' or type = 'quantity'

**Comment by Lathan-btc** [comment]
As per the above document closing the this issue
