### ISSUE TITLE
[Mobile app] Not able to enroll to the study > getting 500 error

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4780]
Not able to enroll to the study > getting 500 error

Note:
1.  issue observe in the Myaccount screen
2. Enrollment flow
3. Previously enrolled studies are getting displayed in the Yet to enroll status

![image](https://user-images.githubusercontent.com/71445210/182104286-e1d5e071-8da2-429c-93f0-7b607843157a.png)

**Comment by Lathan-btc** [comment]
Issue is reproducible for the below study

Study ID: Imported26Study
Study name: FHIR_DID-Study (All response types)[Import]

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest dev instance

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS and Android builds.
