### ISSUE TITLE
SB > Study activities > Weekly/Monthly schedule > Date picker displaying all the dates irrespective of 'Day of week'/'date of month'

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4781]
**Steps:**
1. Edit a study
2. Create a questionnaire and choose weekly
3. Select Day of week as 'Monday' and click on start date field. Observe only dates which appears on monday are displayed
4. Click on Save and add any instruction/question/form step and click on done
5. Edit questionnaire and navigate to schedule option
6. Again click on start date field.
7. Observe date picker displaying all the dates

**A/R:** Date picker displaying all the dates irrespective of 'Day of week'/'date of month'

**E/R:** Date picker should display dates based on 'Day of week'/'date of month'

**Notes:**
1. Issue observed for both weekly and monthly
2. Issue observed for both questionnaires and active tasks
3. Issue also observed in edit study activities also

Refer video
[Schedule.webm](https://user-images.githubusercontent.com/60386291/182304068-8e08effd-c2cb-47b1-b8d5-17d80361c7f3.webm)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
