### ISSUE TITLE
[FHIR] Questionnaire resource > Following fields are not getting mapped into Questionnaire resource

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4782]
Questionnaire resource > Following fields are not getting mapped into the Questionnaire resource

Scale : 
1. Default value (slider position)
2. Description for minimum value
3. Description for maximum value

Continuous scale:
1. Default value (slider position)
2. Description for minimum value
3. Description for maximum value

Text scale:
1. Default slider position

Text choice:
1. All the fields Include 'Other' option

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
