### ISSUE TITLE
[DID] The below entered name is not getting de-identified

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4785]
1. The below entered name is not getting de-identified

'My name is Naga'

2. Locations  not getting redacted

![image](https://user-images.githubusercontent.com/71445210/182391718-43c2065d-4219-4b3c-8b03-542977d350b0.png)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by harisboston** [comment]
@bhoomikav16 Google Healthcare API De-Identification has limitations of many current systems including an inability to detect misspellings, typographical errors, and proper names that share characteristics with non-PHI.
So it may not redact all names, specially nick-Names.

**Comment by bhoomikav16** [comment]
As per the above comments , Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
As per the above comment, Issue is closed in the latest QA instance
