### ISSUE TITLE
[FHIR] Questionnaire resources >JSON >  'Initial' key not getting displayed when admin adds placeholder text in the study builder

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4788]
Questionnaire resources > 'Initial' key not getting displayed when admin adds placeholder text in the study builder

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
