### ISSUE TITLE
[FHIR] JSON > Text response type > Some other values are getting displayed 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4789]
JSON > Text response type > Some other values are getting displayed 

1. Configured values in SB

![image](https://user-images.githubusercontent.com/71445210/182408094-8a6a3b84-ccf4-414c-8bec-9a874b9c7eb2.png)

2. JSON values

![image](https://user-images.githubusercontent.com/71445210/182408563-4fadebda-f076-429f-9e4c-81cea65853a9.png)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by bhoomikav16** [comment]
As per the above comment, Issue is fixed in the latest dev instance
