### ISSUE TITLE
[FHIR] Questionnaire resources > Study version is not getting updated when user deletes the activity and publish the updates

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4790]
Steps:
1. Create a study in SB with questionnaires and active tasks 
2. Launch the study
3. Edit the study
4. Delete the activity (For ex: while deleting the activity Study version is 1.3)
5. Publish the Updates
6. Go to the FHIR datastore
7. Go to Questionnaire response and click on the particular study and observe

AR: Study version is not getting updated when a user deletes the activity and publishes the updates
ER: Study version should get updated when user deletes the activity and publish the updates (As per the above steps study version should get updated to 1.4)

**Comment by harisboston** [comment]
@Lathan-btc If user is updating any data in questionnaire resource then version is getting updated, but if questionnaire resource is deleted, then version should be same, that shows the last version no. when it was deleted. Please confirm.

**Comment by harshith2590** [comment]
@harisboston : Yes the flow is correct.

**Comment by Lathan-btc** [comment]
As per the above comment, QA is closing the issue.
