### ISSUE TITLE
[FHIR] Questionnaire resource > JSON > Branching logic data is not getting mapped into the JSON file 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4791]
AR: Questionnaire resource > JSON > Branching logic data is not mapped into the JSON file 
ER: Branching logic data should get mapped into the JSON file as configured in the SB

**Comment by bhoomikav16** [comment]
Branching is not mapping properly as per the configuration in the study builder

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
