### ISSUE TITLE
[iOS] Study activities screen > 'No activities found' error message getting displayed for few seconds in the following screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4792]
Steps:
1. Sign up or sign in to the mobile app
2. Enroll to the study
3. Navigate to study activities screen and observe

AR: 'No activities found' error message getting displayed for few seconds
ER: 'No activities found' error message should not get displayed

[Issue observed when user enters to study activities screen for the fist time after enrolling into the study]

https://user-images.githubusercontent.com/71445210/182616320-5f56a357-7011-4c49-b0b0-b6ebdae1ff9a.mp4

**Comment by nishit-v** [comment]
Issue is fixed in latest dev iOS build V3.0.116

**Comment by nishit-v** [comment]
Issue is still reproducible in latest iOS dev build V3.0.147

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
