### ISSUE TITLE
[FHIR] Questionnaire resource > 'Type' should be 'open-choice' for the questions with response type = text choice + Other option with text entry allowed

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4794]
AR: Questionnaire resource > 'Type' is getting displayed as 'choice' for the questions with response type = text choice + Other option with text entry allowed
ER: Questionnaire resource > 'Type' should be 'open-choice' for the questions with response type = text choice + Other option with text entry allowed

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance
