### ISSUE TITLE
[FHIR] Questionnaire Response is not getting created in the FHIR viewer for active tasks

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4801]
**AR:** Questionnaire Response is not getting created in the FHIR viewer for active tasks
**ER:** Questionnaire Response should be created in the FHIR viewer, when participants submit response for the active task

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance

**Comment by akashkumarv3** [comment]
@Lathan-btc  Please create new active task and then test for this Issue . it is working fine .

**Comment by Lathan-btc** [comment]
Issue is working for newly created activities
