### ISSUE TITLE
[FHIR] Spatial span memory > JSON > Maximum consecutive failures > Need to correct the Spelling(typo) for the linkID 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4802]
Spatial span memory > JSON > Maximum consecutive failures > Need to correct the Spelling(typo) for the linkID,
linkID should be - Maximum_Consecutive_Failures_spatial

![j1](https://user-images.githubusercontent.com/86007179/183687063-d75e8b04-d965-421f-ae18-f362a87eaa3b.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
