### ISSUE TITLE
[FHIR] FHIR viewer > Questionnaire > 'Spatial span memory' activity is not getting displayed 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4806]
**Pre-condition:** Add 'Spatial span memory' activity in the study builder and publish the study

**AR:** FHIR viewer > Questionnaire > Spatial span memory activity is not getting displayed 
**ER:** FHIR viewer > Questionnaire > Spatial span memory activity should get displayed

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
