### ISSUE TITLE
[Big query] Views are not getting created for the tables under the datasets

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4807]
AR: Views are not getting created for the tables under the datasets
ER: Views should get created for the tables in Big query for each datasets

![image](https://user-images.githubusercontent.com/71445210/183894908-cc789dda-c156-4ac5-8d5a-4367391684bf.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance

**Comment by bhoomikav16** [comment]
Issue is reproducing only for iOS Studies

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
