### ISSUE TITLE
[PM] Participants are navigating to change password screen, when signed in with the temporary password in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4808]
**Steps:**
1. Sign in with the temporary password 
2. Reload / Refresh the set up password screen and Verify

**AR:** Participants are navigating to change password screen in the following scenario
**ER:** Participants should not navigate to any other screen in the following scenario

[screen-capture (90).webm](https://user-images.githubusercontent.com/86007179/183926471-59a84477-e610-40e2-9516-8e067f0ea396.webm)

**Comment by harisboston** [comment]
Looks similar to #4578

**Comment by Madhud5** [comment]
Hi @akashkumarv3 this issue similar to  #4578 session issues, pls check.

**Comment by akashkumarv3** [comment]
@Madhud5 Hi Madhu ,I have checked this issue its not backend issue .  After Reload / Refresh the set up password screen  its navigating to change password screen.

**Comment by Madhud5** [comment]
Hi @bhoomikav16 issue resolved pls check and let me know.
thanks

**Comment by bhoomikav16** [comment]
Issue is reproducing in the latest dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 issue resolved pls check and let me know.
thanks

**Comment by bhoomikav16** [comment]
Issue is reproducing in the latest dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 issue resolved pls check and let me know.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance
