### ISSUE TITLE
[iOS] Activities will be in Resume status in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4810]
Steps:
1. Sign in to SB
2. Create a study
3. Click on edit study and go to questionnaires/active tasks
4. Edt the activities and publish the updates
5. Sign up or sign in to the mobile app and enroll to the particular study
6. Try to provide the responses for the activities which are edited and published in step 4
7. Observe

AR: Activities are moving to Resume state
ER: Activities should move to a completed state

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello Akash,
process-response is failing when submitted with older study version. Please verify.

**Comment by Lathan-btc** [comment]
Issue is reproducible in the following scenarios

Steps:
1. Add or edit and go to questionnaires
2. Add a form step question with 'Boolean and 'date' response type and publish the study
3. Gop to mobile app, enroll to the study
4. Click on a particular activity
5. select a value for Boolean and don't select any value for the 'Date' question 
6. Submit and observe

AR: After submitting the response activity will be in completed status but if participant logout and login then it will show in Resume status
ER: Activity should get completed successfully

**Comment by akashkumarv3** [comment]
@GovindPrasadBostonTechnologyCorporation  Hi Govind ,From backend its resolved already no issue from backend .

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
