### ISSUE TITLE
[Mobile apps] Sign in screen > Password field > 'Eye' icon should not get displayed in the mobile apps

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4818]
Sign in screen > Password field > 'Eye' icon should not get displayed in the mobile apps

**Comment by Madhud5** [comment]
hi @bhoomikav16 issue fixed please check and close ticket.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev build
