### ISSUE TITLE
[PM] Dashboard, Locations, Admins and My account tabs are not getting displayed in the participant manager

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4821]
Dashboard, Locations, Admins and My account tabs are not getting displayed in the participant manager

![BlockerPM](https://user-images.githubusercontent.com/86007179/184888884-5fe75d50-1edd-45f3-a676-c744884fc4e6.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 issue resolved pls check and let me know.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
