### ISSUE TITLE
[FHIR] QuestionnaireResponse > JSON file > Response value is not getting mapped in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4822]
Steps:
1. In SB create a study with Text choice response type activity by using 'Other' answer options
2. launch the study
3. In mobile, Sign up or sign in to the mobile app
4. Enroll to the above study
5. Submit the response for above created activity by selecting Other option
6. Observe

AR: QuestionnaireResponse > JSON file > Response value is not getting mapped
ER: QuestionnaireResponse > JSON file > Response value should get mapped into JSON even though when the participant selects the Other option

![image](https://user-images.githubusercontent.com/71445210/185109730-22b1851e-89c0-4ba0-983a-e1676b1afe9b.png)

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance

**Comment by Lathan-btc** [comment]
@akashkumarv3 Answer options are not getting mapped into the FHIR store when the 'Other' answer option is selected for text choice response type

**Comment by akashkumarv3** [comment]
@Lathan-btc Hi Latha, Issue is resolved from backend ,So please test when mobile team provide new build .

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev build 1.0(200)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build 3.0(135)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.189
