### ISSUE TITLE
[IOS] Study list screen > Enrolled studies are studies are getting displayed in 'Yet to enroll' status

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4830]
AR: Enrolled studies are not studies are getting displayed in 'Yet to enroll' status
ER: Enrolled Studies should get displayed with 'Enrolled' status on the Study list screen

Note: 
1. Issue observe in the latest build 3.0(125)
2. Issue observed for both old participants and new old participants

**Comment by amruthbtc** [comment]
Issue not visible in 3.0 (131)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
