### ISSUE TITLE
[iOS] Activities list screen > All the activities status is showing as 'Missed'

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4831]
Activities list screen > All the activities status is showing as 'Missed'

Note:
1. Issue observe in the latest build 3.0(125)

![image](https://user-images.githubusercontent.com/71445210/185338079-da2c954a-ec6a-4b50-8a09-5a61823c5487.png)

**Comment by amruthbtc** [comment]
Issue not visible in 3.0 (131)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build 3.0(131)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
