### ISSUE TITLE
[iOS] Formstep > text choice > user is able to select multiple answer options even though 'Single select' option is selected in the SB 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4839]
Steps:
1. In SB, create a study with a 'Text choice' response type by selecting single select option
2. Launch the study
3. Sign up or sign in to the mobile app
4. Enroll to the study
5. Click on text choice activity
6. Try to select multiple answer options 

AR: Participant is able to select multiple answer options
ER: Participant should not able to select multiple answer options when the 'single select' option is selected in the SB

SB: 

![image](https://user-images.githubusercontent.com/71445210/185600408-eb9c9796-db7a-455c-a2c3-226d64bba8c4.png)

ER:

![image](https://user-images.githubusercontent.com/71445210/185600787-80a511c9-6acd-4f8a-80c9-dadc496e7452.png)

**Comment by Lathan-btc** [comment]
@GovindPrasadBostonTechnologyCorporation 
1. Issue is fixed for the above scenario
2. Form step > text choice > user is not able to select multiple answer options even though the 'Multiple select' option is selected in the SB

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello team the multi select issue will be handled in #4855  issue

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.186
