### ISSUE TITLE
[iOS] [Offline indicator] Empty screen is getting displayed when user clicks on the 'Disagree' present on the Review consent screen 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4844]
Steps:
1. Sign up or sign in to the app
2. Click on the study and try to enroll
3. Navigate to the 'Review consent' screen
4. turn off the internet
5. Click on the Done button
6. Observe

AR: Participant is navigating to the empty screen
ER: Participant should get alert pop up and after clicking on 'Ok' button participant should navigate to the study list screen

Note: 
1. Issue should also be fixed in the review updated consent flow
2. Issue observed when Participant clicks on the 'Next' button present on the Signature screen

https://user-images.githubusercontent.com/71445210/185955899-89f08802-d329-4f1b-9e79-e7c83dc42848.MOV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
