### ISSUE TITLE
[iOS] Only first consent is getting displayed to the mobile participants 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4848]
Steps:
1. In SB, click on create study
2. In the consent section, add multiple consents  and launch the study
3. Go to the mobile app
4. Sign up or sign in to the mobile app
5. Click on the created study
6. while enrolling, observe the consent

AR: Only first consent is getting displayed to the mobile participants
ER: All the created consent should get displayed to the mobile participants

**Configurations in SB**

![image](https://user-images.githubusercontent.com/71445210/186197508-bbb9d28a-ad7c-44a2-bf08-75b62de65d28.png)

https://user-images.githubusercontent.com/71445210/186198635-b1b864b4-4e69-4727-b3c5-22ec875f8b5b.MOV

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS Dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
