### ISSUE TITLE
[iOS] Spatial span memory > Some of the activities will be in Resume status even though participant submits the response successfully

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4849]
Spatial span memory > Some of the activities will be in Resume status even though the participant submits the response successfully

Study id: CopyofNew09
Study name: Copy of NewStudy09/09
Activity name: spmnew10

**Comment by akashkumarv3** [comment]
@GovindPrasadBostonTechnologyCorporation Hi Govind ,from backend its resolved now .
@Lathan-btc  Hi Latha ,its resolved now .

**Comment by Lathan-btc** [comment]
Issue fixed in the latest Dev instance

**Comment by nishit-v** [comment]
Issue is not reproducible in latest QA iOS build V3.0.185
