### ISSUE TITLE
[iOS] Occasionally some activities are getting saved in the Resume status 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4859]
Occasionally some activities are getting saved in the Resume status even though the participant has completed the activities successfully

Refer the below-mentioned study

Study id: newstudyon25_08
Study name: Imported iosupdate1(newstudyon25_08)

![image](https://user-images.githubusercontent.com/71445210/186709651-e50a0dde-a504-40e3-be96-8963e73b8d50.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build

**Comment by nishit-v** [comment]
Issue is not observed in latest QA iOS build V3.0.185
