### ISSUE TITLE
[FHIR] Questionnaire resource > Active tasks > 'Start' date and 'end date' are getting displayed when active tasks are configured with anchor date schedule type

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4861]
AR: Questionnaire resource > Active tasks > 'Start' date and 'end date' getting displayed when active tasks are configured with anchor date schedule type
ER: Questionnaire resource > Active tasks > 'Start' date and 'end date' should not get displayed when active tasks are configured with anchor date schedule type

Note:
1. Issues observed for active tasks when those are configured with anchor date scheduling type
2. Issue observed for questionnaires when those are configured with a one-time anchor date

![image](https://user-images.githubusercontent.com/71445210/186864709-4126e126-0efe-4805-8b53-debae1896368.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance
