### ISSUE TITLE
[IDP] [PM] Not able to add non-organizational admins in the participant manager

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4866]
Not able to add non-organizational admins in the participant manager

**Comment by Madhud5** [comment]
@Lathan-btc issue fixed pls check and close this

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest IDP branch

**Comment by bhoomikav16** [comment]
The issue is fixed in the latest IDP QA branch
