### ISSUE TITLE
[Android][iOS] Inconsistency between Android and iOS for the sorting order for study resources

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4872]
Steps:- 
1. Add few resources for the study and publish from SB
2. Navigate to resources section in mobile and observe the available resources

A/R:- Available resources are displaying in different sorting order in Android and iOS apps
E/R:- Available resources should be displayed in same order and should be consistent between both platforms

**Android**
![image](https://user-images.githubusercontent.com/60500517/187446790-e32336d5-7157-4c40-811a-11e35d193441.png)

**iOS**
![image](https://user-images.githubusercontent.com/60500517/187447453-f3abb615-04e3-4e0d-a766-a3c92f946956.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0.147

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA build 3.0(185)
