### ISSUE TITLE
[Auth Server] Randomly getting session expired message and user is automatically logged off

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4886]
**Steps:**
1. Login into app (iOS)
2. Enroll into the study
3. Keep the app idle for some time(>30 mins)
4. Open the app again and observe user got session expired message

**Actual:** Randomly getting session expired message and user is automatically logged off

**Expected:** User should not be automatically logged off

1. One of the user got session expired message at 6:44PM - Sep 02 2022

**Comment by bhoomikav16** [comment]
Issue is again observed in android device, User got session expired at 04:32PM - Sep 05 2022

**Comment by Lathan-btc** [comment]
Issue is again observed in the iOS device, User got session expired at 09:12 PM - Sep 07 2022

**Comment by harisboston** [comment]
From auth-server logs, I can see null, while getting the refresh token from ORY Hydra.
Looks like network issue or token got expired. Will keep this issue under observation.

**Comment by nishit-v** [comment]
Issue is reproducible again for multiple users.

**Comment by harisboston** [comment]
In ORY Hydra, by default refresh token will expire after 720h. 
Added logger in getToken/refresh token in auth server to analyze further, @nishit-v please update the time if issue will occur again.
Thanks

**Comment by bhoomikav16** [comment]
Issue was observed even in PM web app at 5.25 PM , 21/09/2022

**Comment by harisboston** [comment]
NO error in Auth server at 5.25 PM , 21/09/2022, Hydra responded with proper refresh_token  for grantType: authorization_code,
same updated in users table of auth DB

**Comment by Lathan-btc** [comment]
Issue observed again at 2.11 PM, 22/09/2022

**Comment by harisboston** [comment]
Analyzed the Auth-server log at 2.11 PM, 22/09/2022:

Received request from Mobile to get refresh token at 2022-09-22 14:11:02.986 IST.

paramMap value: 
{client_id=[TUUo9PjRQN80y3Mt], grant_type=[refresh_token], redirect_uri=[https://participants.btcsoft-dev.boston-technology.com/auth-server/callback], refresh_token=[RQP-2fHQx7kye5IPjuVaxP3BUgnq2N6FA0VQgJErJzk.cXRBDFuNKSFFaxjbUNuJAfDsmM0EKR1uejkvF-2ebnc], userId=[c54848f2b0a26e4509e9021o40c3096af8a2]}

From auth server, requested Hydra to get refresh token and updated the same in authserver DB  users table in encrypted form.
and revoked previous refresh token.

New refreshToken recieved  from Hydra: MOIOucF8Qn13FBxj-pXY-B9vkj89fiTs8ekpUOiErwk.vq5OlSzgBSVfKe9wvkKGSJdKa1mLYJU8kDVVdYTvees


Again received request from Mobile to get refresh token at  2022-09-22 14:11:03.371 IST

paramMap value: 
 {client_id=[TUUo9PjRQN80y3Mt], grant_type=[refresh_token], redirect_uri=[https://participants.btcsoft-dev.boston-technology.com/auth-server/callback], refresh_token=[RQP-2fHQx7kye5IPjuVaxP3BUgnq2N6FA0VQgJErJzk.cXRBDFuNKSFFaxjbUNuJAfDsmM0EKR1uejkvF-2ebnc], userId=[c54848f2b0a26e4509e9021o40c3096af8a2]}

In auth server, got exception when again tried to get refresh token from Hydra using above refresh_token received from Mobile.
I can see same refresh_token in second request from Mobile, this refresh token was revoked and new refresh token was generated by Hydra in first request.

Mobile need to send updated  refresh_token.

**Comment by Lathan-btc** [comment]
Issue observed again in iOS at 1.10 PM 26/09/2022

**Comment by bhoomikav16** [comment]
Issue is not observed again in the androd latest dev build 1.0(213)

**Comment by Lathan-btc** [comment]
Issue is not observed in the latest Dev build 3.0 (183)

**Comment by nishit-v** [comment]
Issue is not observed in latest mobile builds.
