### ISSUE TITLE
[Android] Comprehension success screen is not getting displayed in updated consent flow

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4888]
**Steps:**
1. Sign in and enroll to the study
2. Now, Go to SB and update the consent for enrolled participants
3. Open the mobile app and complete the eligibility section
4. Navigate to comprehension section
5. Complete the comprehension section and Observe

**AR:**  Comprehension success screen is not getting displayed in updated consent flow
**ER:**  Comprehension success screen should get displayed in updated consent flow [ Refer the screenshot attached]

![Screenshot_20220905-133902_FDA MyStudies](https://user-images.githubusercontent.com/86007179/188403771-1363fd4d-36c4-464e-94e6-8e69b1284956.jpg)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev build 1.0(204)

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
