### ISSUE TITLE
[iOS] Enrollment flow > Data sharing permission > Participant is able to select both data sharing options present on the screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4889]
AR: Enrollment flow > Data sharing permission > Participant is able to select both data sharing options present on the screen
ER: Participants should be able to select only one option at a time on the data sharing permission screen

![image](https://user-images.githubusercontent.com/71445210/188405882-79fec2d7-5769-4ecd-a78b-73ea2d98849c.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.186
