### ISSUE TITLE
[iOS] updated consent is not getting displayed to the participants in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4890]
Steps:
1. Sign up or Sign in to the mobile app
2. Enroll to the study 
3. After navigating to the activities screen, lock the mobile
4. Go to the SB, update the consent for enrolled participants and publish the updates
5. Unlock the mobile app
6. Enter the passcode for the app
7. Refresh the page and observe

AR: Updated consent is not getting displayed to the participants
ER: Updated consent should get displayed to the participants

[Note: Issue should also be fixed for newly added active tasks for the above scenario]

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS Dev instance

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
