### ISSUE TITLE
[iOS] Anchor date based activities/resources disappears once user logs out and logs in

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4897]
**Steps:**

1. Create a source and target questionnaire from SB and publish
2. From mobile answer a source questionnaire
3. Target questionnaire is displayed in the list
4. Logout and login with same user credentials
5. Observe target questionnaire disappears

**Actual result:** Anchor date based activities/resources disappears once user logs out and logs in

**Expected result:**  Anchor date based activities/resources should not disappear

Note: Issue not observed for Enrollment based activities

Issue observed for questionnaires, active tasks and resources

Study ID - ComprTest
App ID - GCPMOB001

**Comment by amruthbtc** [comment]
activityRunId required as url param in "/participant/getresponse?" api

**Comment by akashkumarv3** [comment]
Hi, from backend it is fixed and activityRunId is added  as url param in "/participant/getresponse?" api.

**Comment by nishit-v** [comment]
Issue is fixed for study activities(Questionnaires and Active tasks) but not fixed for Resources. Verified in iOS build V3.0.164

Steps:

1. Create a source questionnaire from SB
2. Create a target based resources and publish
3. From mobile answer a source questionnaire
4. Resources displayed in the list
5. Logout and login with same user credentials
6. Observe target resources disappears

Actual result: Anchor date based resources disappears once user logs out and logs in

Expected result: Anchor date based resources should not disappear

**Comment by nagarjunav1** [comment]
Issue is observed for Resources now in Android. Verified in Android build v1.0(205)

Steps:

Create a source questionnaire from SB
Create a target based resources and publish
From mobile answer a source questionnaire
All the new target resources are not displayed in the list

Actual result: All the new source based resources are not displaying in resources screen
Expected result: Anchor date based resources should not disappear

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0 (170)

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest build v1.0(205)
