### ISSUE TITLE
[SB] Questionnaires > Duplicate questionnaires are created in the study builder 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4900]
Questionnaires > Duplicate questionnaires are created in the study builder for the following study
Study name - StandaloneNewApp
Study ID - StandaloneNewAp

![Question](https://user-images.githubusercontent.com/86007179/188561717-0145ea79-6573-435c-9b9a-8b5969b05066.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is not observed in the latest QA instance
