### ISSUE TITLE
[FHIR store] Questionnaire response > Text choice > Single select > Answer option is not getting displayed when participant selects 'Other' answer option

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4905]
Steps:
1. SB> Add/edit questionnaire > Add text choice questionnaire with 'Other' option and single select
2. Launch or publish the updates
3. Sign up or sign in to the mobile app
4. Enroll to the study
5. Submit the response by selecting the 'Other' answer option
6. Go to the FHIR store and observe

AR: 'Other' answer option is not getting stored in the FHIR store
ER: 'Other' answer option should get stored in the FHIR store

![image](https://user-images.githubusercontent.com/71445210/188666210-a568ad41-2312-436d-8a00-b72cc1dec7a0.png)

**Comment by Lathan-btc** [comment]
@harisboston 

The highlighted value should be displayed in the FHIR JSON file

![image](https://user-images.githubusercontent.com/71445210/190166444-d186e4b6-321e-466c-981e-e67e3c4e9f02.png)

Displayed value in the JSON ( value in the 'Display value' field is getting displayed in the JON )

![image](https://user-images.githubusercontent.com/71445210/190167078-f18c9311-16c0-45d2-9fdc-312e2825c905.png)

**Comment by amruthbtc** [comment]
@Lathan-btc Issue fixed in ios build 3.0 (174)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS dev build.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest android dev build 1.0(208)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.189
