### ISSUE TITLE
[iOS] Responses are not getting synced if user submits multiple study activities in offline (Refer scenarios)

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4907]
**Scenario 1:** Study activities which are submitted in offline are not synced

**Steps:**
1. Login and enroll into a study
2. Open any study activity 1
3. Switch off the internet connection
4. Submit the response
5. Switch on the internet connection
6. Again open any other study activity 2
7. Switch off the internet connection
8. Submit the response
9. Switch on the internet connection and wait > 10 mins
10. Logout and login and observe responses are not synced and status showing 'Resume'

**Scenario 2:** Study activities which are submitted in online are also not synced in below scenario

**Steps:**
1. Login and enroll into a study
2. Open any study activity 1
3. Switch off the internet connection
4. Submit the response
5. Switch on the internet connection
6. Again open any other study activity 2
7. Switch off the internet connection
8. Submit the response
9. Switch on the internet connection
10. Again open any other study activity 3 and submit the response in online
11. Logout and login and observe responses are not synced and status showing 'Resume' even for online activities

**A/R:** Responses are not getting synced if user submits multiple study activities in offline

**E/R:** Responses should be synced properly

Refer attached video:

https://user-images.githubusercontent.com/60386291/188820554-e0ca6ea9-9e2d-4b74-8473-9fc14691e7be.mp4

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS dev build V3.0.159

**Comment by nishit-v** [comment]
Issue is again reproducible in latest QA V3.0.162

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello team,
The backend server is failing in this scenario and error logs are recorded by Harris.

**Comment by nishit-v** [comment]
Issue is still reproducible in latest Dev instance and latest iOS dev build V3.0.170. Above 2 scenarios are reproducible.

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.186
