### ISSUE TITLE
[iOS] Study resources screen > Source anchor date related resources are not getting displayed in the study resources screen

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4908]
Description:

Precondition : 
1. Source question should be added by using the date response type
2. Source anchor date related resources should be added in the SB 

Steps:
1. Sign up or sign in to the mobile app
3. Enroll to the study
4. Submit the source question
5. Go to the resources screen and Observe (all the anchor date resources are getting displayed)
6. Go to SB, add a new resource in the SB for a particular study
7. Go to the mobile app, click on a particular study
8. Navigate to the resources screen and observe

AR: Source anchor date related resources are not getting displayed in the study resources screen
ER: All the resources should get displayed to the participant

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest iOS Dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev iOS build V3.0 (170)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.186
