### ISSUE TITLE
[iOS] [Offline indicator] Offline feature is not working in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4909]
**Description**

**Pre_condition:** The testing device should connect to WiFi

**Steps:**
1. Install the mobile app on the testing device
2. Turn off the main data (Don't turn off the WI-FI of the testing device)
3. Observe

**AR:** Offline indicator feature is not working
**ER:** Offline indicator feature should work as per expected in the above scenario

Note: Issue is not observed in android

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello team,
1)This as informed is happening when the hotspot is on device 1 and app is installed in device2.
 a)If internet is turned off in device 1 without disconnecting hotspot then the device 2 reachability class will consider this scenario as no internet change i.e internet is present. 
b)In this scenario, as there is no connection change in device 2, the app will consider it as internet present and will try connecting to internet but finally fails giving error - -1001,-1003,-1004 which indicates unable to establish connection. 
c)In the above scenario as informed we won’t be able to show offline indicator but to avoid data loss at the time of activity submit, we are saving it in the local realm and syncing it back when internet resumes back. note- The app will be able to see if any connection can be made with server only by making another api call.

Thank you,

**Comment by nishit-v** [comment]
Closing as per above comment.
