### ISSUE TITLE
[iOS] Mobile participant is not able to complete their sign up flow in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4910]
**Steps:**
1. Install the mobile app in the testing device
2. Go to sign in screen
3. Click on the Signup button
4. Enter all the required fields and click on submit
5. Enter the received verification code
6. Observe

**AR:** Sign in not available error page is getting displayed
**ER:** Mobile users should be able to sign up for their account successfully

Note: if the user goes back to sign in screen and tries to sign in then gets a 'Sorry an error has occurred....' error message is getting displayed

![image](https://user-images.githubusercontent.com/71445210/188866851-16f15c6e-315b-4999-a367-f89d4d7fe528.png)

![image](https://user-images.githubusercontent.com/71445210/188866945-239f8a9c-fc5b-4724-ba89-7abc2a0a2f7b.png)

**Comment by Lathan-btc** [comment]
@harisboston Issue is reproducible in the latest Dev instance

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello team,
Keeping this issue under observation. Please report when seen again

**Comment by nishit-v** [comment]
Issue is not intermittent and reproducible consistently in below scenario: 

**Steps:**

1. Install the mobile app in the testing device
2. Go to sign in screen
3. Click on the Signup button
4. Enter all the required fields and click on submit
5. Enter the received verification code
6. Observe

**Note: Issue is not reproducible if user directly navigates to signup from app overview screen**

**Comment by nishit-v** [comment]
Issue is fixed in latest iOS dev build V3.0(173)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185
