### ISSUE TITLE
[Mobile apps] Sign in screen > All the text fields, buttons, hyperlinks in sign in screen are displayed in smaller size in higher screen size devices

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4911]
Steps:
1. Install the app (android or iOS) on devices having at least> 5.5 inch screen size
2. Navigate to signin screen
3. Observe the text fields, buttons, and hyperlinks

Note: Issue not observed in smaller screen size devices eg. iPhone SE 2nd gen

Refer screenshots for the below devices:

iOS - iPhone XS Max (6.46" screen size)
![Image_20220907_162331_114](https://user-images.githubusercontent.com/60386291/188866010-efa6a3f9-e27b-449e-8608-42df7a5b4cc7.png)

Android - Samsung M32 (6.4" screen size)
![3b8c7941-6b76-488e-ad6a-5bc1ebe35c6e](https://user-images.githubusercontent.com/60386291/188866274-f8de6abe-1b1a-4a0e-9254-6fa48471ee34.jpg)

Android - OnePlus 8T (6.55" screen size)
![8367e570-fb7f-47e9-a28a-704ec8ebcec7](https://user-images.githubusercontent.com/60386291/188866382-b1c08900-b41e-4c34-918f-c2f9ce109d82.jpg)

**Comment by Madhud5** [comment]
Hi @nishit-v please check and confirm. thanks

**Comment by nishit-v** [comment]
Issue is still reproducible in Mobile apps - dev instance

**Comment by Madhud5** [comment]
Hi @nishit-v please check and confirm. 
here Please note we cant increase the size's because it will other issues. 
thanks

**Comment by nishit-v** [comment]
Issue is not fixed still. Cleared browser cache and reverified again in both Android and iOS. No difference is observed between screenshot attached earlier and taken now.



![IMG_3350](https://user-images.githubusercontent.com/60386291/189071040-b0658965-1a80-467e-9ac2-57964f4e7d31.PNG)

**Comment by nishit-v** [comment]
Only Hyperlinks like `Forgot password?`, `Sign up` size is increased but still layout of signin screen remains same. Attaching screenshot of old signin screen.
![IMG_3352](https://user-images.githubusercontent.com/60386291/189084059-95e670ae-5113-460e-8887-0d7729616f33.PNG)

**Comment by nishit-v** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.189
