### ISSUE TITLE
[IOS] [Standalone] Updated consent is not getting displayed in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4912]
**Description**

**Pre-condition:** Study should be created with Comprehension test questions in the Study builder and the study should be launched

**Steps:**
1. Sign up or sign in to the mobile app
2. Enroll to the study
3. Go to the study builder and update the consent for enrolled participants
4. Go to the mobile app, click on the review consent pop up
5. Navigate to the comprehension test screen
6. Fail the comprehension test
7. Click on the 'Cancel' button on the retry screen
8. Observe

**AR:** Updated review consent popup is not getting displayed 
ER: Updated review consent popup should get displayed to the participant

[Note: If the participant refreshes the page then an updated review consent popup is getting displayed]

https://user-images.githubusercontent.com/71445210/188878223-f373d1d0-4efe-4c10-a3ff-e9cd51fc68fe.MOV

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.186
