### ISSUE TITLE
[iOS] Force upgrade > Force upgrade/Optional upgrade screens are displayed in mobile if app build version is lesser than or equal to installed version

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4913]
**Steps:**
1. Install the iOS app. Let app version by V3.0.151
2. Login to SB and navigate to Manage apps
3. Edit the particular app and navigate to developer configurations
4. Enter `Latest XCode app version` as 3 and `Latest app build version` ≤ 151 (Eg. 150 or 151 etc)
5. Publish the updates
6. Open the app and observe

**Actual:** Force upgrade/Optional upgrade screens are displayed in mobile if app build version is lesser than or equal to installed version

**Expected:** Force upgrade/Optional upgrade screens should not displayed in mobile if app build version is lesser than or equal to installed version

**Comment by GovindPrasadBostonTechnologyCorporation** [comment]
Hello team,
In Manage apps version in number should be entered exact format as given in Xcode version part. For example 3 and 3.0 are different version number.

Thank you,
Govind

**Comment by nishit-v** [comment]
Closing as per above comment. XCode version 3.0 is not same as 3. Working fine now if admin enter 3.0 in SB if 3.0 is entered in build generating process.
