### ISSUE TITLE
[Mobileapps] Getting an error message in consent signature screen in enrollment flow

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4930]
**Steps:**
1. Sign in / Sign up
2. Click on any study, Complete the eligibilty flow
3. Navigate to consent signature , Click on 'Next' button and Verify

**AR:** Getting an error message in consent signature screen in enrollment flow
**ER:** Enrollment flow should be completed by the participant without any error's

![Screenshot_20220914-132943_FDA MyStudies](https://user-images.githubusercontent.com/86007179/190096877-ad310c92-2c6e-4bc6-9171-dd2acf57c72b.jpg)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS and Android builds.
