### ISSUE TITLE
[PM] [VAPT] Sign in Screen > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4933]
Sign in Screen > UI issue > 'Sign in' text is splitted into 2 lines

![image](https://user-images.githubusercontent.com/71445210/190192448-60c31792-b0db-429c-ac2b-b16521261f5e.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and let me know. thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
