### ISSUE TITLE
[VAPT] [SB] My account section is not available in the study builder

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4934]
My account section is not available in the study builder

**Note:** Issue needs to be fixed in welcome screen also

![Myaccount](https://user-images.githubusercontent.com/86007179/190197208-079a9caa-7efb-4151-ae46-d10dab12fc8c.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the 'Welcome' screen

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the 'Welcome' screen

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev branch

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
