### ISSUE TITLE
[VAPT] [SB] Edit admin > 'ACTIVATE / DEACTIVATE' toggle button is not aligned properly

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4935]
Edit admin > 'ACTIVATE / DEACTIVATE'  toggle button is not aligned properly, Alignment should be as per the design document

![admin](https://user-images.githubusercontent.com/86007179/190199009-ec8313d1-f4b5-453c-9cac-d2683d1178bd.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
