### ISSUE TITLE
[VAPT] [SB] Add / Edit admin > Select and add studies dropdown > Two scrollbars are getting displayed in the dropdown

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4936]
Add / Edit admin > Select and add studies dropdown > Two scrollbars are getting displayed in the dropdown

![edit](https://user-images.githubusercontent.com/86007179/190201204-333d262b-e616-402b-ac6a-5381a21d11e0.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest VAPT dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
@Madhud5  Dropdown is not getting displayed in the 'Select and add apps ' field

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev branch

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
