### ISSUE TITLE
[VAPT] [SB] Notifications section > Create / Edit notification screen > UI Issue

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4937]
Notifications section > Create / Edit notification screen > UI Issue

**AR:** All the dropdown fields are not aligned properly
**ER:** All the dropdown fields should be aligned properly

**1.**
![N3](https://user-images.githubusercontent.com/86007179/190202884-48d603f9-7381-493d-afbf-800bb901ef11.png)

**2.**
![N2](https://user-images.githubusercontent.com/86007179/190202576-77f51cfe-db55-4322-b5ea-4ff24a1f40c4.png)

**3.**
![N1](https://user-images.githubusercontent.com/86007179/190202725-1aab4f76-e189-462c-b434-01406a6fddfc.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 here Datetimepicker plugins width fetching from library so where manual customize wont allow. other width part for select fixed. please check and close thanks

**Comment by bhoomikav16** [comment]
Based on the above comment, Issue is fixed in the latest VAPT dev instance

**Comment by Lathan-btc** [comment]
As per the above comment closing this issue
