### ISSUE TITLE
[VAPT] [SB] Create / Edit Studies > Study Information screen > UI Issue 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4939]
Create / Edit Studies > Study Information screen > UI Issue is observed , UI of study information screen should be according to the design document

![11](https://user-images.githubusercontent.com/86007179/190370860-8c4cd141-3083-4a13-aad7-91fa839fb6cc.png)

![si](https://user-images.githubusercontent.com/86007179/190345846-1f9712ba-e8b2-427e-8f89-8deb8236c589.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest VAPT dev instance

![image](https://user-images.githubusercontent.com/86007179/191011572-e6df294d-150b-4067-af99-c1a8c0ca6f79.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest VAPT dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev instance
