### ISSUE TITLE
[VAPT] [SB] Create / Edit Studies > Study overview screen > UI Issue

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4940]
Create / Edit Studies > Study overview screen > UI Issue

**AR:**
 ![Overview](https://user-images.githubusercontent.com/86007179/190346948-795769fc-c1f9-47eb-a9f4-2a9e89ddbad7.png)

**ER:** By default first page in the overview screen should be available for the admins
![Untitled](https://user-images.githubusercontent.com/86007179/190347737-23cd7057-8922-4f01-9759-70749fc6ac91.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 Please check and close this issue.

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest VAPT dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 Please check and close this issue.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
