### ISSUE TITLE
[iOS] Enrollment flow/updated consent flow > Review consent screen > Study name is not getting displayed for the Custom consent

### ISSUE THREAD

**Issue by GovindPrasadBostonTechnologyCorporation** [GoogleCloudPlatform/fda-mystudies#4941]
1)Study name is not getting displayed for the Custom consent
2)Pdf is generated without study name

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS Dev build 3.0(174)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA build
