### ISSUE TITLE
[VAPT] [SB] Create / Edit Studies > Issues in 'Eligibility' section 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4944]
Create / Edit Studies > Issues in 'Eligibility' section 

1. Response options are not getting displayed 
2. UI is not according to the design document

**1.**
![e2](https://user-images.githubusercontent.com/86007179/190348836-5ab23365-21bd-40da-b8e7-52a901502b9c.png)

**2.**
![Eligiblity](https://user-images.githubusercontent.com/86007179/190348426-fdef2741-a79d-45d6-bc45-b34a8d4816aa.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
