### ISSUE TITLE
[VAPT] [SB] Create / Edit Studies > 'Consent' section > Add consent section > Topic > UI Issue in the dropdown 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4945]
Create / Edit Studies > 'Consent' section > Add consent section > Topic > UI Issue in the dropdown 

**ER:** Dropdown and also the UI of consent screens should be according to the design document

![C1](https://user-images.githubusercontent.com/86007179/190352684-54212f9c-9ff4-4f6b-82c2-31474340fdf2.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
