### ISSUE TITLE
[VAPT] [SB] Create / Edit Studies > 'Comprehension Test' section > Add comprehension test question section > Answer options are not aligned properly

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4946]
Create / Edit Studies > 'Comprehension Test' section > Add comprehension test question screen > Answer options are not aligned properly

![comp](https://user-images.githubusercontent.com/86007179/190353653-6e4624e2-7d1d-4a45-93f2-d8c69985e82a.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest VAPT dev instance

![re](https://user-images.githubusercontent.com/86007179/190970583-50fbe371-9143-419d-83ac-8acfc0a47d6d.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
