### ISSUE TITLE
[VAPT] [SB] Create / Edit Studies > 'Resources' section > Add / Edit resources screen > Fields are not aligned properly 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4947]
Create / Edit Studies > 'Resources' section > Add / Edit resources screen > Fields are not aligned properly 

![r1](https://user-images.githubusercontent.com/86007179/190356020-52e6e513-8d32-494c-9b28-9861f8c7c7b9.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest VAPT dev branch
![r2](https://user-images.githubusercontent.com/86007179/191013752-ceb64e0c-f189-4795-a42d-3bc29d0516e2.png)
![resourcesnew](https://user-images.githubusercontent.com/86007179/191013786-23c36c67-0b8a-4fc0-b2cc-9af5c771f25a.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
