### ISSUE TITLE
[PM] [VAPT] Red color disable icon should get displayed when admin mouse hovered on the disabled fields

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4949]
Red color disable icon should get displayed when the admin mouse hovered on the disabled fields

1. Participant details screen > Enrolled users > Enable invitation and Disable invitation
2. Forgot Password screen
3. My account screen

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest VAPT branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
