### ISSUE TITLE
[VAPT] [SB] Manage Apps > Edit app > Spelling mistakes in Action screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4950]
**Steps:**
1. Edit the app.
2. Navigate to Action section.
3. Observe the text below the Mark iOS app as distributed button and Mark Android app as distributed button.

**AR:** Distributed spelling is displaying as 'distrbuted' for both Mark iOS app as distributed and Mark Android app as distributed for on-screen text under the buttons.
**ER:** Distributed spelling should be displayed as 'distributed' for both Mark iOS app as distributed and Mark Android app as distributed for on-screen text under the buttons.

![apps](https://user-images.githubusercontent.com/86007179/190364286-78e2cd27-224b-4ad9-8b0b-0cad6bac3f21.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT branch

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks
