### ISSUE TITLE
[VAPT] [SB] UI Isssue in all the screens of the study builder

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4951]
1. All the text fonts should be same as per the requirements
2. Tool tip text font should be same as per the requirements
3. Alignment should be proper throughtout the application
4. Spacing is more in between the two fields

**Note:** Issue needs to be fixed throughout the application

![ui1](https://user-images.githubusercontent.com/86007179/190366696-928059e0-f8fc-4478-b365-cf63c50a5c4d.png)

![ui2](https://user-images.githubusercontent.com/86007179/190366833-ed5b421b-d29e-4c88-a101-5d5b0800a3c4.png)

![ui3](https://user-images.githubusercontent.com/86007179/190366975-eb99c993-d851-410a-aa3c-16a6b22aae46.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest VAPT dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
