### ISSUE TITLE
[VAPT] [SB] My account screen > UI Issue

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4953]
My account screen > UI Issue

![my](https://user-images.githubusercontent.com/86007179/190369320-e582dced-8b06-4ac8-9cd4-682cf1da1ffc.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
