### ISSUE TITLE
[VAPT] [SB] E-consent steps > Consent document > Mark as completed success message is getting displayed in the data sharing permission screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4959]
**Steps:**
1. Edit the study
2. Navigate to 'E-consent steps' section
3. Go to 'Consent document' screen
4. Click on 'Mark as completed' button and Verify

**AR:**  Mark as completed success message is getting displayed in the 'Data sharing permission' screen
**ER:**  Mark as completed success message should get displayed on 'Consent document' screen

[screen-capture (95).webm](https://user-images.githubusercontent.com/86007179/190409110-8aa2439f-83de-43e0-87a1-717e3d930e5d.webm)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 
functionality : after click on "mark as completed" button page will get refresh then default the first tab will be in active state.

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance
