### ISSUE TITLE
[SB] [VAPT] Add/edit questionnaire > Unable to add/edit and update/delete the questionnaires

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4960]
Steps:
1. Sign in to the Study builder
2. Navigate to the Studies list screen
3. Click on create/edit study
4. Go to the Questionnaires
5. Add form step questions
6. Try to delete 

AR: Unable to add/edit and update/delete the questionnaires and getting continuous loading
ER: Admins should be able to add/edit and update/delete the questionnaires

**Comment by Madhud5** [comment]
Hi @harisboston and @akashkumarv3 its also not working in Dev env please check

**Comment by akashkumarv3** [comment]
@Madhud5 Hi Madhu ,

It's not backend issue its bootstrap issue, please check once  .

DevTools failed to load source map: Could not load content for https://studies.btcsoft-dev.boston-technology.com/studybuilder/vendor/boostrap/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by akashkumarv3** [comment]
Hi , after upgrading my sql version to 8 from server side .
Now its working fine .

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest deployment

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
