### ISSUE TITLE
[SB] Regex is not working as configured for 'Text' responce type

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4962]
**Steps**:- 
1. Configure the activity with 'Text' responce type as shown in attached Image
2. Publish the updates for the study
3. Install and open the mobile app
4. Enroll into the study which is configured from SB
5. Navigate to the Activity list and open the activity which is configured in step-1
6. Try to enter period(.) symbol and click on Next button
7. Observe the app behaviour

**A/R:**- Period(.) symbol is accepting in the text field
**E/R:**- Text field should not accept any characters including symbols, alphabets and numbers as per the configuration in SB

![image](https://user-images.githubusercontent.com/60500517/190627123-749d0d4d-5c1a-4296-b6cd-3824924a3ce8.png)

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA build
