### ISSUE TITLE
[VAPT] [SB] Create / Edit study > Study Information > Study type field is getting displayed in the study information screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4966]
**AR:** Create / Edit study > Study Information > Study type field is getting displayed in the study information screen
**ER:** Create / Edit study > Study Information > Study type field should not get displayed in the study information screen

![study](https://user-images.githubusercontent.com/86007179/191173260-bc5b78f8-1bf3-470c-b9f0-44bb85fb2614.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
