### ISSUE TITLE
[VAPT] [SB] Hand cursor icons should be displayed for all radio buttons and checkboxes through out the application when mouse hovered

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4967]
A/R: Hand cursor icons are not displayed for any of the radio buttons or checkboxes through out the application when mouse hovered

E/R: Hand cursor icons should be displayed for all radio buttons and checkboxes through out the application when mouse hovered

Eg.
![SB](https://user-images.githubusercontent.com/60386291/191176336-fa84c5fd-7a88-4349-a317-07464b07b104.png)

**Comment by Madhud5** [comment]
Hi @nishit-v  please check and close the issue.
thanks

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance in VAPT branch.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
