### ISSUE TITLE
[VAPT] [SB] Studies > UI Issue in the 'Filter by apps' dropdown

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4969]
Studies > UI Issue in the 'Filter by apps' dropdown i.e., There is no outline border getting displayed in the dropdown and also no separtaion of all apps and app values

![UI](https://user-images.githubusercontent.com/86007179/191177448-70b56caf-0dce-481d-aba0-9507d61c9a68.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest VAPT dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in latest QA instance.
