### ISSUE TITLE
[PM] Admin details screen > UI issue 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4970]
Admin details screen > UI issue  > Reduce the gap between the search bar and selected apps

![image](https://user-images.githubusercontent.com/71445210/191192632-f643db8e-e410-44f1-a5f4-eccf91210503.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Deployment

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
