### ISSUE TITLE
[PM] Edit admin details screen > Deactivated admins > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4971]
Edit admin details screen > Deactivated admins > UI issue 
1. there should be a little gap between the title and placeholder
2. Place holder text should be center aligned to the grayed out area
3. Disabled icon should get displayed when the admin mouse hovered on the dropdown

![image](https://user-images.githubusercontent.com/71445210/191196037-44fdaf44-c376-4125-8f14-61b91913a3ac.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue.
thanks

**Comment by nishit-v** [comment]
First 2 points are fixed and 3rd point is still reproducible

- Disabled icon should get displayed when the admin mouse hovered on the dropdown

**Comment by Lathan-btc** [comment]
@Madhud5 When the admin mouse hovered on the dropdown, sometimes disable icon is getting displayed, and sometimes it is not getting displayed.

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check this issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
