### ISSUE TITLE
[VAPT] [SB] Question/Form step > Add or Edit question > UI issue

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4972]
**Actual:** Selected tab is not highlighted when navigated to the page first time

**Expected:**  Selected tab should be highlighted 

Note: Issue observed for both question step and form step. Issue observed for both Add or edit question
Issue also observed for Active tasks

Refer screenshots for Actual and Expected
![Actual](https://user-images.githubusercontent.com/60386291/191521146-d04d768a-6b45-479c-9d1c-7c3d3801be03.png)

Expected:
![Expected](https://user-images.githubusercontent.com/60386291/191521209-5054dfd0-a659-4a67-95eb-c592c7315f4a.png)

**Comment by Madhud5** [comment]
Hi @nishit-v please check this issue and close

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance
