### ISSUE TITLE
[VAPT] [SB] Placeholder text color for all the dropdown values is not as per design throughout the application

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4973]
**Actual:** Placeholder text colour for all the dropdown values is in black colour throughout the application.

**Expected:** Placeholder text colour for all the dropdown values should be in light grey (Refer previous designs)

Refer screenshot for one of the page
![Placeholder](https://user-images.githubusercontent.com/60386291/191522091-6062f02e-3d93-49a1-9af3-119f943af08e.png)

**Comment by Madhud5** [comment]
Hi @nishit-v please check and close the issue.
thanks

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in latest QA instance.
