### ISSUE TITLE
[iOS] Form step questions with 'Repeat form' option > UI issue

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4977]
Form step questions with 'Repeat form' option > UI issue > 'Repeat' text should align middle to the white layout ( both vertically and horizontally)

![image](https://user-images.githubusercontent.com/71445210/191534883-fec8839b-a43b-44cd-8b9e-0ade216a63fb.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.186
