### ISSUE TITLE
[VAPT] [SB] Resource > Alignment issue for anchor date options

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4978]
**Actual:** Alignment issue for anchor date options

**Expected:** Alignment should be proper

![Resource_UI](https://user-images.githubusercontent.com/60386291/191538151-0772007c-1efd-4257-afa1-4b4d2c76f906.png)

**Comment by Madhud5** [comment]
Hi @nishit-v  please check and close the issue.
thanks

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in latest QA instance
