### ISSUE TITLE
[VAPT] [SB] Active task > Regular One Time > Alignment issue 

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4979]
**Actual:** Alignment issue for date picker and time picker values

**Expected:** Alignment should be proper

Issue not observed for questionnaires

![Active Task_UI](https://user-images.githubusercontent.com/60386291/191539111-ec5d8a2a-76eb-4f0b-83a7-c4147f14d105.png)

**Comment by Madhud5** [comment]
Hi @nishit-v  please check and close the issue.
thanks

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in latest QA instance
