### ISSUE TITLE
[VAPT] [SB] All the screens > Text is not visible inside some of the buttons when mouse hovered 

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4991]
A/R: Text is not visible inside some of the below buttons (buttons having grey colour)

1. Cancel
2. Save
3. Next
4. Upload
5. Change password
6. Upload PDF
7. Enforce password change etc

E/R: Text should be visible

Issue should be fixed for all the buttons across the application

Eg in basic info when mouse hovered:
![BasicInfo](https://user-images.githubusercontent.com/60386291/191946541-d60d98cd-5358-45e8-9b07-10a10e32f481.png)

**Comment by Madhud5** [comment]
Hi @nishit-v  please check and close the issue.
thanks

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in latest QA instance
