### ISSUE TITLE
[SB] [VAPT] Rich text editor > UI issues

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4992]
Rich text editor > UI issues

1. Font Style > UI issue > Values are not aligned properly
2. Font size > UI issue > Values are not aligned properly
3. All icons are moving when the admin clicks on the icons present in the Rich text editor
4. Insert link > UI issue > Cross mark not aligned properly
5. Insert link > Select check box is not getting displayed for 'Open in new window
6. Drag icon is not working (this UI issue was observed only in the Overview screen)

https://user-images.githubusercontent.com/71445210/191950929-a37e63e6-588c-47ae-b32c-8eea58d3f11e.mp4

**Comment by Madhud5** [comment]
Hi @Lathan-btc  please check and close the issue.
thanks

**Comment by Lathan-btc** [comment]
@Madhud5 
1. 1 to 5 points are fixed
2. 6th point is reproducible in the VAPT branch

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by nishit-v** [comment]
> Drag icon is not working (this UI issue was observed only in the Overview screen)

Issue is fixed only for 1st overview page and for remaining pages issue is reproducible.

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance.

**Comment by Lathan-btc** [comment]
The below mentioned issues are reproducible in the Consent section and resources section

4. Insert link > UI issue > Cross mark not aligned properly
5. Insert link > Select check box is not getting displayed for 'Open in new window

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest VAPT dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
