### ISSUE TITLE
[SB] Overview screen > Uploaded overview image is not getting displayed in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4993]
Steps:

1. Login to SB
2. Create or edit the study
3. Navigate to the overview screen
4. Upload an overview image
5. Remove the image
6. Again upload the same image and observe

AR: Image is not getting uploaded
ER: Image should get displayed

https://user-images.githubusercontent.com/71445210/191952461-a2603665-4bf9-4689-9df5-fdbe1f76a545.mp4

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest dev instance

**Comment by akashkumarv3** [comment]
@Lathan-btc Hi Latha ,Please test in btc-dev2dev-deploment branch .

**Comment by akashkumarv3** [comment]
@Lathan-btc Branch is merged now So you can test now.

**Comment by Lathan-btc** [comment]
@akashkumarv3 Issue is fixed only for the first page and for remaining pages issue is reproducible

**Comment by nishit-v** [comment]
Issue is fixed in latest Dev instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance

**Comment by akashkumarv3** [comment]
@Lathan-btc please check and update

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest DEV VAPT branch
