### ISSUE TITLE
[VAPT] [SB] Alignment issue in the 'Select the study version to be exported / copied popup message

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4994]
**AR:**  Alignment issue in the 'Select the study version to be exported / copied popup message in the study builder
**ER:**  'Select the study version to be exported / copied popup messages should be center aligned in the study builder

![copied](https://user-images.githubusercontent.com/86007179/191963203-98430c43-7974-42a3-b1b7-690baa6fc30f.png)

![Export](https://user-images.githubusercontent.com/86007179/191963295-8acb9819-316a-4077-b988-f5e03be00341.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance, i.e., UI od popup message should also be vertically center aligned

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
UI Issue is observed only for 'Select the study version to be copied' popup message in the study builder

**Comment by madhud-btc** [comment]
Hi @bhoomikav16 pls check and close this ticket.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP Dev branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP QA branch
