### ISSUE TITLE
[Android] [Consent API] Consent record with revoked state should be created ,when participant account is deleted in the mobile app

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4999]
**Pre-condition:** Study should be created in the study builder

**Steps:**
1. Sign in / Sign up
2. Enroll for the  study
3. Now go to 'My account' section and delete the user account
4. Go to that particular consent record and Verify

**AR:** Consent record with revoked state is not getting created ,when participant account is deleted in the mobile app
**ER:** Consent record with revoked state should be created ,when participant account is deleted in the mobile app

**Note:** Issue is observed only when response is submitted from android 12 device

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
