### ISSUE TITLE
Revisit Superadmin

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#500]
Superadmin/admin user, as is, poses a security risk to any deployment.
Steps proposed to mitigate that:

### Change initial value
1. Create script that accepts admin + password and overwrites the values copies in the gcs bucket per [SQL setup](https://github.com/GoogleCloudPlatform/fda-mystudies/tree/early-access/kubernetes#sql)

### Treat admin role as a normal role
1. Allow admin to assign admin role to other users
1. List admin as a user under users tab, or on a separate page with only admin access

**Comment by SR-btc** [comment]
This has been addressed along with the Manage Apps feature (R2.0.8)
