### ISSUE TITLE
[VAPT] [SB] Questionnaires > Question step / Form step > Text choice response type > UI Issue in the Response level attribute screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5000]
Questionnaires > Question step / Form step > Text choice response type > UI Issue in the Response level attribute screen

![ui](https://user-images.githubusercontent.com/86007179/192081205-44f23daf-ce77-4267-88a9-aa52ae9802c5.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
