### ISSUE TITLE
[SB] [VAPT] Buttons are blinking when admin clicks on the buttons 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5001]
Buttons are blinking when the admin clicks on the buttons (eg: Save, Cancel, Mark as completed, Upload)

**Note:** 
1. Issue should be fixed in all the places
2. Issue observed after resolving #4991 issue

https://user-images.githubusercontent.com/71445210/192081980-bf00ff71-2900-4865-8367-d35058c7b4db.mp4

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest VAPT branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
