### ISSUE TITLE
[PM] Admins > Search bar > Placeholder text >Text change

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5002]
Admins > Search bar > Placeholder text >Text change > 'user' should be changed to 'admin'

![image](https://user-images.githubusercontent.com/71445210/192086563-af160b74-6fbf-4386-8120-889605668d71.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest build

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
