### ISSUE TITLE
[VAPT] [PM] Participant details > Consent history > Consent history values should be aligned in the center

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5003]
Participant details > Consent history > Consent history values should be aligned in the center

![PM](https://user-images.githubusercontent.com/86007179/192086883-d6d567dd-30d6-4818-b994-d6b6924400ac.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by Madhud5** [comment]
![image](https://user-images.githubusercontent.com/59555917/192246889-cd1144cf-3545-4870-8bc3-c8c68a149bc7.png)

Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
