### ISSUE TITLE
[SB] [VAPT] Dropdown is getting grayed out when admin selects the value from the dropdown

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5007]
The dropdown is getting grayed out when the admin selects the value from the dropdown

![image](https://user-images.githubusercontent.com/71445210/192230051-828de9f9-33bf-4f20-9cf9-a700f642570a.png)

[Note: Issue should be fixed in the places where ever dropdowns are present]

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest deployment

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
