### ISSUE TITLE
[VAPT][SB] Tick mark is getting overlapped with the study name is add /edit admin screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5008]
**Pre-condition:** Create a study with larger name 

Tick mark is getting overlapped with the study name is add /edit admin screen

![image](https://user-images.githubusercontent.com/86007179/192234500-f2d145fe-d17f-440b-8120-9e4d04b25f8d.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16  please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
