### ISSUE TITLE
[iOS] [FHIR] Questionnaire response > Other answers are getting stored for the form step questions in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5011]
Steps:
1. In SB add multiple text choice questions in the form of step
2. In mobile, provide the response only for the first question
3. Don't provide the answer to the 2nd question
4. Submit the response
5. Go to the FHIR store and observe

AR: Selected value for the first question in the form is getting displayed for the skipped question
ER: Answer options should get displayed properly

![image](https://user-images.githubusercontent.com/71445210/192263421-f7d2ea22-b69e-4681-b1b7-fcdb9fdf3f06.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest iOS Dev build 3.0(182)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.189
