### ISSUE TITLE
[SB] Inconsistency in the UI for the date and time picker throughtout the application

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5023]
Inconsistency in the UI for the date and time picker throughtout the application

**Note:** Please refer the few screenshot attached below
**1.**
![image](https://user-images.githubusercontent.com/86007179/193263100-7bb4a796-a99e-4ca3-a71b-5a9bf004dbe4.png)
**2.**
![image](https://user-images.githubusercontent.com/86007179/193263143-685fab1f-e9a9-48c9-afbf-0b717d6c0dde.png)
**3.**
![image](https://user-images.githubusercontent.com/86007179/193263215-6c9c6f07-91a6-4502-8fcd-8ecf482e2662.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 as we discussed after Plugins upgradation date picker will UI will change according to update from plugin third party.  We can't customize plugins

**Comment by nagarjunav1** [comment]
Closed the ticket as above comment from developer
