### ISSUE TITLE
[IDP] [PM] Submit button is disabled in the account setup screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5026]
**Steps:**
1. Add admins in the participant manager by entering the value in the phone number field which should be as similar in the format displayed in the UI
2. After getting account setup link in an email, click on that link
3. Complete all the fields and click on Submit button and Verify

**AR:** Submit button is disabled in the account setup screen
**ER:** Submit button should not be disabled in the account setup screen

[screen-capture (99).webm](https://user-images.githubusercontent.com/86007179/194277119-34e340cb-2d15-42a1-9e91-3b04a01b5596.webm)

**Comment by madhud-btc** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest PM IDP dev branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest PM IDP QA branch
