### ISSUE TITLE
[SB] [QA] Getting 'Failure' error message when importing the study in the study builder

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5031]
Getting 'Failure' error message when importing the study in the study builder

![Screenshot (2083)](https://user-images.githubusercontent.com/86007179/194847082-1e8d51ca-dab2-4953-a9d1-8821bb953fb7.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA Instance
