### ISSUE TITLE
[SB] Error message is overlapping with the text in the study settings screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5032]
Error message is overlapping with the text in the study settings screen

![image](https://user-images.githubusercontent.com/86007179/195297638-fc0e81a2-6395-439d-9568-4cd867af81ff.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest VAPT branch

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA instance
