### ISSUE TITLE
[SB] Admin My account dropdown > UI Issue in the dropdown

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5033]
UI issue is observed in the admin my account dropdown i.e., dropdown is shifted to the right side and the font size is also large

![image (16)](https://user-images.githubusercontent.com/86007179/195302580-6a2d62f2-cefb-42d8-b275-0220e997bae7.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
