### ISSUE TITLE
[PM] [QA] Alternative thumbnail image is not getting displayed in the participant manager

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5034]
Alternative thumbnail image is not getting displayed in the participant manager

![image](https://user-images.githubusercontent.com/86007179/195331559-68ecdf27-960e-40ce-953c-c2a4649706e9.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
