### ISSUE TITLE
[PM] Dashboard >Sites tab > Add location dropdown > Placeholder text should get displayed in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5036]
Dashboard >Sites tab > Add location dropdown > Proper placeholder text should get displayed when no values are present in the 'Add location' dropdown

Placeholder text: 'No items are available to select' placeholder text should get displayed in the gray color

[Note: Issue should be fixed in the Add/edit admin > Study admin > 'Select app ID or name']

![image](https://user-images.githubusercontent.com/71445210/195359653-744595b7-b779-40da-a842-dbc4dbaed479.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc issue fixed in Site and in admin plugins wont support it will break complete select dropdown functionality pls note.
Please check and close ticket.
thanks

**Comment by Lathan-btc** [comment]
As per the above comment it is working fine

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
