### ISSUE TITLE
[SB] Spatial span memory > Content screen > UI issue is observed in the content screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5039]
Spatial span memory > Content screen > UI issue is observed in the content screen i.e., Alignment is not according to the design document

**AR:**
![image](https://user-images.githubusercontent.com/86007179/195775132-64b03630-5e4f-498c-be50-d6308f6390f9.png)

**ER:**
![image](https://user-images.githubusercontent.com/86007179/195775810-26545598-fca8-4d7d-a6de-38cae14a8f6f.png)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance, i.e.,
Enter the values in the fields then, click on Save / Done button and Verify

![image](https://user-images.githubusercontent.com/86007179/196092710-341bbe38-3729-4948-b362-b2592cbd4e50.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is fixed in the latest Dev instance

**Comment by Madhud5** [comment]
Hi @bhoomikav16 please check and close the issue.
thanks

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
