### ISSUE TITLE
[iOS] [Standalone build] [QA] Blank screen is getting displayed to the mobile participants in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5040]
Steps:
1. Install the standalone build
2. Sign up or Sign in to the mobile app
3. Enroll to the study
4. After navigating to the review screen, click on 'Disagree' and observe

AR: Blank screen is getting displayed
ER: Study overview screen should get displayed 

[Note: Issue not observed in Dev instance)

**Comment by nishit-v** [comment]
Issue is fixed in latest dev instance V3.0.193

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.194
