### ISSUE TITLE
[SB] [UI] Edit questionnaire section > 'Activity short title or key'  > Error message is overlapping with the title field

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5074]
**AR:** Error message is overlapping in the 'Activity short title or key' ,  when we enter the value which has been used in the past
**ER:** Error message should not overlap in the 'Activity short title or key' , when we enter the value which has been used in the past

![Ui](https://user-images.githubusercontent.com/86007179/199659202-af55d4fa-bc7f-4885-90ad-acd3865f2c8c.png)

**Comment by madhud-btc** [comment]
Hi @Lathan-btc please check and close this ticket.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev-IDP instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA-IDP instance
