### ISSUE TITLE
[IDP] [SB] Getting error when try to sign in with organizational admins in the study builder

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5075]
**Pre-condition-** IDP and MFA should be enabled in the study builder

Getting error when try to sign in with organizational admins in the study builder with valid credentials

![SB](https://user-images.githubusercontent.com/86007179/199665837-e75e07a3-7bb7-4918-8054-c2777d4e6fc9.png)

**Comment by akashkumarv3** [comment]
@Lathan-btc Issue is not reproducible. please test and update

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest deployment

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
