### ISSUE TITLE
[IDP] [SB] [PM] Not able to complete the sign in process in the following scenario for the organizational admins

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5078]
**Pre-condition:** 
1. Organizational admin should be added in the SB and PM
2. IDP and MFA should be enabled in both SB and PM

**Steps:**
1. Enter valid credentials and sign in and select the re-Captcha
2. Then, Enter verification code in the verification popup message in the sign in screen
3. Press 'Enter' button on the keyboard and Verify

In SB,
**AR:** Not able to sign in in the above scenario and admins are staying in the same sign in screen
**ER:** Admins should be able to sign in and should be navigated to 'Dashboard' screen

In PM,
**AR:** Getting 'Sign in is not available. Please try again later. ' error message in the participant manager
**ER:** Admins should be able to sign in and should be navigated to 'Dashboard' screen

![image](https://user-images.githubusercontent.com/86007179/199957579-9282560d-12d6-47eb-962d-aea3525c8278.png)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev IDP branch

**Comment by akashkumarv3** [comment]
Hi,
 This is browser keyboard limitation functionality, it does not allow us to customize the browser functionality   consider this please kindly close the ticket as per discussion with @Madhud5

**Comment by bhoomikav16** [comment]
As per the above comment, Closing this issue.
