### ISSUE TITLE
[IDP] [PM] UI Issue when user enters wrong password in the auth server

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5079]
UI Issue when user enters wrong password in the 'AUTH' server

**AR:**
![UI PM](https://user-images.githubusercontent.com/86007179/199964208-754f65de-5630-49ff-9441-2e1f9507b334.png)

**ER:**
![image](https://user-images.githubusercontent.com/86007179/199963807-b20201fb-fcb0-4a04-96fd-e1eb5985a8a3.png)

**Comment by madhud-btc** [comment]
Hi @Lathan-btc please check and close this ticket.
thanks

**Comment by Lathan-btc** [comment]
Now, issue is getting observed if admins open the Sign in page of the PM


![image](https://user-images.githubusercontent.com/71445210/200312841-9c21c5a2-9c0c-4929-a5a1-ff3526ff8631.png)

**Comment by Lathan-btc** [comment]
Issue i s fixed in the latest Dev_IDP instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
