### ISSUE TITLE
[IDP] [PM] Entered value in sign in screen is not getting displayed in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5080]
**Steps:**
1. Enter email and password of non -organizational admin 
2. Click on eye icon present in the password field (Password will be decrypted)
3. Click on 'Sign in' button and Verify

**AR:** Entered values in sign in screen are not getting displayed in the following scenario
**ER:** Entered values in sign in screen should get displayed in the following scenario

[screen-capture (11).webm](https://user-images.githubusercontent.com/86007179/199964888-c66bc07e-3145-4d7a-b622-7e380267d5cb.webm)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
