### ISSUE TITLE
[IDP] [SB] [PM] Pop up to enter the OTP is not getting displayed in the following scenario

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5081]
Steps:
1. Go to the login page of the SB/PM
2. Enter a valid email and password
3. Select the captcha 
4. On the displayed popup enter the invalid OTP and click on OK or click on the cancel button
5. Again try to sign in with a valid email and password without refreshing the page

AR: Pop up to enter the OTP is not getting displayed
ER: Pop up should get displayed to the admins

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the PM IDP dev branch

**Comment by akashkumarv3** [comment]
@bhoomikav16 Issue is fixed in PM also. please check and update.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP dev branch in both SB and PM

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP QA instance
