### ISSUE TITLE
Upgrade from v2.0.10 to v2.0.11: DB Migration Build Fails for Study Builder

### ISSUE THREAD

**Issue by jaseva** [GoogleCloudPlatform/fda-mystudies#5086]
Hi there,

I initially had v2.0.10 installed and am attempting to upgrade to v2.0.11 following the instructions. The build for the studybuilder database seems to fail while following the DB migration instructions https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/db-migration/README.md:

![image](https://user-images.githubusercontent.com/5480431/200654539-62c32304-7bf3-4881-a55e-2c6fc8bd13c9.png)

When I try to run repair to update the schema it fails:

mvn flyway:repair

The build fails:

![image](https://user-images.githubusercontent.com/5480431/200656122-5aa80cf0-f083-4f9a-b8f0-8a6dc657ccee.png)

@yugandhar-btc Do you know how I can resolve this issue? It seems it is unable to connect to the studybuilder database. 

I noticed that there is an open issue for the study-builder-db-migration script: https://github.com/GoogleCloudPlatform/fda-mystudies/pull/5072

I upgraded in study-builder-db-migration > db > pom.xml

	1. Upgrade flyway-maven-plugin:
		v7.5.0 to v9.4.0

	2. Upgrade mysql-connector-plugin:
		v8.0.23 to v8.0.28

It still fails to build:

![image](https://user-images.githubusercontent.com/5480431/200688546-ae33d437-b6db-4015-9873-5470090aa3af.png)

It throws a FlywayException and it says there is no database found to handle jdbc:mysql://127.0.0.1.3306/fda_hphc

When pom.xml had flyway-maven-plugin v7.5.0 and mysql-connector-plugin v8.0.23 it was complaining about (first image):

Migration checksum mismatch for migration version 2.0.8

When pom.xml had flyway-maven-plugin v9.4.0 and mysql-connector-plugin v8.0.28 it was complaining about (last image):

No database found to handle jdbc:mysql://127.0.0.1.3306/fda_hphc

**POTENTIAL SOLUTION**

I sourced another potential solution that said to go directly into the database to fix the checksum error though I'm not sure if this will work and will mess things up further:

UPDATE schema_version SET checksum = 634791453 WHERE version_rank = 8 AND checksum = -1476074480;

How I would access an editor to run the SQL command in GCP for the fda_hphc database? I'm new to GCP.

![image](https://user-images.githubusercontent.com/5480431/200696901-da452db8-a65d-4ba8-9c03-0161acc3dba2.png)

I would prefer not to drop the database and rebuild it if possible as I have test data in it which will need to be re-populated.

Reference: 
https://stackoverflow.com/questions/41147768/caused-by-org-flywaydb-core-api-flywayexception-validate-failed-migration-che

Here is a MojoExecutionException help file:

![image](https://user-images.githubusercontent.com/5480431/200695013-f2a648c5-d06d-499b-aa07-1f5eb2828902.png)

**Comment by yugandhar-btc** [comment]
@jaseva are you facing this No database found issue only to the fda_hphc database ?

**Comment by jaseva** [comment]
> @jaseva are you facing this No database found issue only to the fda_hphc database ?

@yugandhar-btc Initially it was a checksum mismatch for the fda_hphc database when I used the default versions listed in pom.xml. When I upgrdaded the versions as a potential fix, it says no database found.  I do not think it is related to the versions listed in pom.xml as the migration for the other databases worked fined using the same early versions.

**Comment by yugandhar-btc** [comment]
@jaseva could you please repair flyway with below command and try  

mvn flyway:repair -Dflyway.user=${DB_USER} -Dflyway.configFiles=flyway.properties -Dflyway.password=${DB_PASS} -Dflyway.url=jdbc:mysql://127.0.0.1:3306/fda_hphc

**Comment by jaseva** [comment]
@yugandhar-btc thanks for the command, it produced an error though (in the bastion-vm of the networks project). When I started the vm, I set the environment variables in the deployment/scripts folder "source set_env_var.sh" and then executed the command you provided:

![image](https://user-images.githubusercontent.com/5480431/200840715-c910b776-9087-4514-bb4b-0e0c3e6fddda.png)

Should I try reverting back to the default flyway-maven-plugin and mysql-connector-plugin versions that were part of the v2.0.11?

**Comment by yugandhar-btc** [comment]
@jaseva please revert the changes you made and then start from the beginning of [db-migration](https://github.com/GoogleCloudPlatform/fda-mystudies/tree/develop-IDP/db-migration) steps.

**Comment by jaseva** [comment]
Okay, I'll try that again @yugandhar-btc

**Comment by jaseva** [comment]
@yugandhar-btc I reverted back the plugin versions in pom.xml, updated the dev-vm github repo, successuly completed another cloud build in the dev-ops project, ran a git pull origin <branch> command in the bastion-vm of the network project, re-ran the deployment instructions for the database migration. The first 3 databases successfully built, the study-builder failed again with the original checksum database error message. 

![image](https://user-images.githubusercontent.com/5480431/200846154-be6a9485-50a7-4740-9fa7-4a64790d5b77.png)

I did not run the flyway-plugin repair command that you provided. I'll try that now and re-run the database migration steps.

![image](https://user-images.githubusercontent.com/5480431/200846485-5f4d077f-d795-4997-a993-4d627b4617e9.png)

The repair command on the prior default v2.0.11 plugin pom.xml versions was successful. I'll try re-running the migration step for the fda_hphc database again:

![image](https://user-images.githubusercontent.com/5480431/200846841-565b743a-ab28-4b95-a1ec-118a576d311d.png)

When I log into the study builder website, I am still seeing that it is v2.0.10 unless the version number on the homepage wasn't updated in the source code release?

![image](https://user-images.githubusercontent.com/5480431/200847068-5ac59f40-70ba-4c50-b9fe-4cabaf9b927b.png)

I repeated all database migration scripts in sequence again as per the instructions, all built successfully, though it still displays v2.0.10.

Even when I clear the cache it still says v2.0.10.

When I check the application.properties file to see the study version in the source code in the repo on the bastion-vm (network project), it is listed as v2.0.11:

![image](https://user-images.githubusercontent.com/5480431/200849843-8ae301d1-3a83-4ec0-9bad-61a8a6bf25d0.png)

It looks like the secrets I had added were lost. I'll likely have to repeat the steps of the 2.0.11 upgrade again I'm thinking:

![image](https://user-images.githubusercontent.com/5480431/200922391-61a5617c-9093-4471-b3f4-519407a79f82.png)

Does it matter if I re-create the security groups from within secret manager as opposed through the script? When it is created via secret manager, it shows as automatically replicated as opposed to us-central1 when it was created through the script. The replication policy is automated vs user managed (us-central1) when you compare.

![image](https://user-images.githubusercontent.com/5480431/200925291-8516df7b-083f-4ec8-9f5e-a06cfd37f10c.png)

![image](https://user-images.githubusercontent.com/5480431/200925359-68084966-5599-4c88-9286-ea093f972062.png)

![image](https://user-images.githubusercontent.com/5480431/200925450-6b47453c-1517-469f-8703-66333a9b3169.png)

All of the security group IAM permissions have been applied already from the previous deployment attempt. Just the secret groups in the secret manager are missing for whatever reason.

I manually added and set the secret groups and values. I ignored the security IAM settings that were previosuly set. When I ran the terraform init && apply it failed:

![image](https://user-images.githubusercontent.com/5480431/200928933-b3a6b98e-a20a-40e4-b06b-c46da9279998.png)

![image](https://user-images.githubusercontent.com/5480431/200929087-3979c73a-b957-470e-bf02-d51071f7aeb9.png)

Everything else worked fine though including restarting the default pods and re-running the db migration steps again.

When I delete the manually created secret groups in secret manager and run terraform init && terraform apply it fails with a different message this time:

![image](https://user-images.githubusercontent.com/5480431/200932628-8de5d045-41e6-42d4-b930-9f90688802ab.png)

I had previously commented out the codeblock for the secret groups in the secrets > main.tf file in the past as I think I had incorrect syntax:

resource "google_secret_manager_secret" "manual_region_id" {
  provider = google-beta
  
  secret_id    = "manual_region_id"
  project = module.project.project_id
  
  replication {
    user_managed {
      replicas {
        location = "us-central1"
      }
    }
  }
}

resource "google_secret_manager_secret" "manual_consent_enabled" {
  provider = google-beta
  
  secret_id    = "manual_consent_enabled"
  project = module.project.project_id
  
  replication {
    user_managed {
      replicas {
        location = "us-central1"
      }
    }
  }
}

resource "google_secret_manager_secret" "manual_fhir_enabled" {
  provider = google-beta
  
  secret_id    = "manual_fhir_enabled"
  project = module.project.project_id
  
  replication {
    user_managed {
      replicas {
        location = "us-central1"
      }
    }
  }
}

resource "google_secret_manager_secret" "manual_discard_fhir" {
  provider = google-beta
  
  secret_id    = "manual_discard_fhir"
  project = module.project.project_id
  
  replication {
    user_managed {
      replicas {
        location = "us-central1"
      }
    }
  }
}

resource "google_secret_manager_secret" "manual_ingest_data_to_bigquery" {
  provider = google-beta
  
  secret_id    = "manual_ingest_data_to_bigquery"
  project = module.project.project_id
 
  replication {
    user_managed {
      replicas {
        location = "us-central1"
      }
    }
  }
}

Does this look correct? I removed the uncommented codeblock and pulled the git repo  in my dev-ops vm and rebuilt a new cloud build in the data project of the github repo which worked fine without any error. All secrets were available now in the secret manager in which I added values to each. I tried using that code syntax above and sadly it produced the same terraform init && apply error message.

**Comment by yugandhar-btc** [comment]
@jaseva Looks the  [Migration](https://github.com/GoogleCloudPlatform/fda-mystudies/tree/master/deployment#migration-to-cloud-healthcare-api-from-firestore-2011-upgrade) was no done properly and you no need to add secrets manually in console, those are supposed to be created from the script.

**Comment by jaseva** [comment]
Hi @yugandhar-btc, I figured out my mistake, it turns out in the script above, I was using underscores as opposed to hyphens for the secret id values. 

Once corrected, I rebuilt the cloud build project from the GitHub repo, and terraform init && apply worked fine, I repeated all steps, including migrating the databases. There were no errors. 

I still see the version 2.0.10 displayed on the Study Builder website even though in the application.properties file in the cloned github repos in the bastion-vm and dev-vm all display 2.0.11. 

Do you have 2.0.11 deployed and does the correct version display for you in the Study Builder website? Or is this something in my deployment process for upgrading from 2.0.10 to 2.0.11?

**Comment by jaseva** [comment]
Hi @yugandhar-btc I tried deploying an Android app today, I seem to run into an issue with configuring the participant-datastore. 

I am following the Android instructions here: https://github.com/GoogleCloudPlatform/fda-mystudies/tree/master/Android

For the 5th step, I initially skipped this as I thought I had configured previously by following the semi-automated deployment instructions.

![image](https://user-images.githubusercontent.com/5480431/201267601-b9a6be64-7561-4457-815b-2e348cb52812.png)

I am able to sign up and login to the Android app when I deploy it to my cellphone. It seems to to shoot out an error message whenever it tries to load the homepage which I assume is loading data from the participant-datastore. Here is the error message screenshot:

![Screenshot_20221110-221704](https://user-images.githubusercontent.com/5480431/201267994-563beb1b-bbcd-4636-861d-c76031cfaafd.jpg)

For the instruction that says to copy the [mystudies_participant_datastore_db_script.sql](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/participant-datastore/sqlscript/mystudies_app_info_update_db_script.sql), after I input the values specific to my deployment, how do I execute this script and which environment (i.e. vm gcp console or Cloud Shell in GCP connecting to the MySQL instance of the participant-datastore database)? 

I repeated similar steps as per the semi-automated deployment in the 'Configure your deployment's databases' section with the commands:

gsutil cp \
${GIT_ROOT}/participant-datastore/sqlscript/mystudies_app_info_update_db_script.sql \
gs://${PREFIX}-${ENV}-mystudies-sql-import

gcloud sql import sql --project=${PREFIX}-${ENV}-data mystudies gs://${PREFIX}-${ENV}-mystudies-sql-import/mystudies_app_info_update_db_script.sql -q

I used cloud-build with a tf-apply trigger which was successful. I rebuilt the Android project and it still seems to be experiencing the same connection issue. I am unsure if the issue is related to the pariticpant-datastore or something else.

@Shashank-btc @bhoomikav16 I saw you commenting on another issue related to Offline Activity in the Android app. Do you have any insight into this issue I am experiening? https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/Android/app/src/fda/java/com/harvard/studyappmodule/StudyActivity.java

I rebuilt each app in Cloud Build in the apps project related to the participant-manager.

All app triggers rebuilt successfully in the apps project:

auth-server
hydra
participant-manager-consent-mgmt-module
participant-manager-datastore-enroll-mgmt-module
participant-datastore-user-mgmt-module
participant-manager
participant-manager-datastore
response-datastore
study-builder
study-datastore

https://github.com/GoogleCloudPlatform/fda-mystudies/issues/4699

![image](https://user-images.githubusercontent.com/5480431/201383096-347e54e8-b03d-49eb-a135-894449d433a4.png)

![image](https://user-images.githubusercontent.com/5480431/201383153-2857b199-a464-4cfb-a6f2-5af81b7d873c.png)

I am repeating all the semi-automated deployment steps and now I am running into workload errors in my app project:

![image](https://user-images.githubusercontent.com/5480431/201412925-21da8b77-4626-4fde-9497-19166c81f13a.png)

![image](https://user-images.githubusercontent.com/5480431/201413162-8d87b684-f0f2-4840-85f3-d99b9f0b642e.png)

![image](https://user-images.githubusercontent.com/5480431/201414707-925ace3e-41f7-460d-8b52-06715a8852e8.png)

![image](https://user-images.githubusercontent.com/5480431/201414984-c558be5f-b40a-46cd-97e4-266387173aeb.png)

![image](https://user-images.githubusercontent.com/5480431/201415152-77531439-af4c-47e3-85aa-0eafe4224f0f.png)

![image](https://user-images.githubusercontent.com/5480431/201416092-ea31499b-6398-4068-8835-b14b02435f18.png)

**Comment by yugandhar-btc** [comment]
@jaseva could you please confirm what is the **data_project_id** secret value in deployment/terraform/Kubernetes/main.tf. if there is no secret, please add data project is as a value to the **data_project_id**.

Example: -
    data_project_id                   = "{{.prefix}}-{{.env}}-data"

**Comment by jaseva** [comment]
@yugandhar-btc thanks for the info, which section in the main.tf file should I add this value as it is missing:

data_project_id = "{{.prefix}}-{{.env}}-data"

**Comment by yugandhar-btc** [comment]
@jaseva  please update _deployment/terraform/kubernetes/main.tf_ with data project value and make sure you terraform and re-deploy all the modules. 

cd $GIT_ROOT/deployment/terraform/kubernetes/
terraform init && terraform apply

**Comment by jaseva** [comment]
Hi @yugandhar-btc, I didn't find this value in the deployment/terraform/kubernets/main.tf data project however I found it missing in the mystudies.hcl location where it was referenced in the code repo in 14 files (while using the search):

https://github.com/GoogleCloudPlatform/fda-mystudies/search?p=1&q=data_project_id 

Should I go in and manually re-add it to the other 13 files that are referenced?

It seems to be missing from all the referenced file locations. I modified all 14 files and only the mystudies.hcl reference was missing which I added: 

data_project_id = "{{.prefix}}-{{.env}}-data"

In the deployment/terraform/kubernetes/main.tf data project file I added it yesterday and it produced an error when I ran terraform initi && terraform apply. Which line number in the deployment/terraform/kubernetes/main.tf file should I add the data_project_id = "{{.prefix}}-{{.env}}-data"? Thank you.

**Comment by yugandhar-btc** [comment]
@jaseva You need to add data_project_id = "{{.prefix}}-{{.env}}-data" in _deployment/terraform/kubernetes/main.tf_ under the 
#Shared secrets module.

**Comment by jaseva** [comment]
Hi @yugandhar-btc, I added the reference you specified, rebuilt from my DevOps project, rebuilt all the apps within the Apps project, and I am still producing issues with the Kuberenetes Ingress and Workloads. 

I might follow your steps from the past and try deleting the databases and re-deploying in an effort to save this environment deployment, in particular, the assigned domain name server shards for the Cloud DNS Zone settings.

These are your provided instructions from before:

Please do not continue with the next step if you face any errors in the previous steps/scripts
Step 1:- Delete all the Databases from the SQL.
Step 2:- Delete all the default namespace pods.
Step 3:- In the [configure-your-deployments-databases](https://github.com/GoogleCloudPlatform/fda-mystudies/tree/master/deployment#configure-your-deployments-databases) section, please execute point 4.
Step 4:- ( Please make sure all secrets values are filled in the secret manager)
After successful execution of all above steps, please follow remaining all steps from Point-5 of [configure-and-deploy-your-applications](https://github.com/GoogleCloudPlatform/fda-mystudies/tree/master/deployment#configure-and-deploy-your-applications)

I tried these steps with a prior deployment and did not have success. 

For clarification purposes, do you recommend that I manually delete all databases:

![image](https://user-images.githubusercontent.com/5480431/204849584-b870f3dc-2523-409c-9f61-b53d90157b24.png)

Or do I only delete theses databases outlined here:

![image](https://user-images.githubusercontent.com/5480431/204850924-442ed028-1977-4232-a370-21b72f59a421.png)

Or do I delete the instance which would delete all databases?

And then do I delete all deafult namespace pods as outlined here:

![image](https://user-images.githubusercontent.com/5480431/204849978-ab886d45-5725-4343-b445-07141d807ea6.png)

I would prefer to keep my projects as I am likely at my liimit with available name server shards.

Thanks again for your help.

**Comment by jaseva** [comment]
Closing this issue as I was able to deploy one of the environments.
