### ISSUE TITLE
[IDP] [PM] [MFA Disabled] Submit button is disabled in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5095]
**Pre-condition:** mfa should be disabled in the PM
**Steps:**
1. Login to PM
2. Navigate to admins section 
3. Add admin in the application with phone number in the following format +919999999999
4. Click on the account creation link of added admin
5. Complete all the fields
6. Click on 'Submit' button and Verify

**AR:** Submit button is disabled in the following scenario
**ER:** Submit button should not be disabled in the following scenario

[screen-capture (13).webm](https://user-images.githubusercontent.com/86007179/203272936-f49b56f2-49e6-49a4-a7cf-06b480b47b86.webm)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
