### ISSUE TITLE
[IDP] [SB] Admin is able to create the questionnaires without entering data in the scheduling screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5096]
For monthly,
Admin is able to create the questionnaires without entering data in the scheduling screen
For Weekly,
Fields are not getting displayed when admins clicks on 'Done' button without any data in the scheduling screen

[screen-capture (14).webm](https://user-images.githubusercontent.com/86007179/203306064-edf4a878-42a4-4422-8359-8e8b1eb7dd5a.webm)

**Note:**
Issue is observed in both anchor and regular scheduling options

**Comment by bhoomikav16** [comment]
@akashkumarv3 Above issue was happening because of cache issue , Tried after clearing browsing data. It is working fine.

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev and QA instance

**Comment by akashkumarv3** [comment]
@bhoomikav16 Issue is fixed now ,please check and update .

**Comment by bhoomikav16** [comment]
Issue is reproducing for anchor monthly option in both dev and QA instance

**Comment by akashkumarv3** [comment]
@bhoomikav16 issue is fixed now .

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev and QA instance
