### ISSUE TITLE
[Android] Getting 'You are offline' popup message when tried to signup in the mobile app

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5097]
**Steps:**
1. Install the build
2. Open the app
3. Sign up for the app
4. Complete the sign up process and Verify, after navigating to study list screen

**AR:** Getting 'You are offline' popup message when tried to signup in the mobile app
**ER:** Study list should be loaded without any error's

**Note:**
1.  Issue is observed intermittently
2. Issue is observed only in sign up flow

![Screenshot_20221122-181931_FDA MyStudies](https://user-images.githubusercontent.com/86007179/203319028-24ddf7c4-4abd-441b-a34b-988f6503c181.jpg)

**Comment by akashkumarv3** [comment]
@bhoomikav16 HI, Issue is fixed, please check and update.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest android dev build

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest android QA build
