### ISSUE TITLE
[IDP] [SB] Edit admins screen > Already added data is getting displayed in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5101]
**Steps:**
1.  Edit 'Super admin' in the SB 
2.  Change to role to 'Study admin' 
3. Click the 'Select and add apps' dropdown and Verify

**AR:** Edit admins screen > Already added data is getting displayed in the following scenario
**ER:** Edit admins screen > Already added data should not get displayed in the following scenario

**Note:** Issue is observed in both 'Select and add apps' dropdown and 'Select and add studies' dropdown

**Comment by akashkumarv3** [comment]
@bhoomikav16 Issue is fixed, please test and update .

**Comment by Lathan-btc** [comment]
Issue is reproducible in the following scenario

1. Click on Super admin
2. Change super admin to study admin
3. Click on updates
4. Again click on the edit icon 
5. Click on the Studies and apps dropdown 
6. Observe

AR: Edit admins screen > Already added data is getting displayed in the following scenario
ER: Edit admins screen > Already added data should not get displayed in the following scenario

**Comment by akashkumarv3** [comment]
@Madhud5 Above issue is happening due upgradation of bootstrap. So please look into this

**Comment by Lathan-btc** [comment]
@akashkumarv3 

1. Extra value is getting displayed in the 'Select and add studies' dropdown  for the above scenario


![image](https://user-images.githubusercontent.com/71445210/204977166-2f9eab54-9529-423a-b9b4-9283e9ae610a.png)

2. After selecting all the items present in the dropdowns, Empty space is getting displayed

![image](https://user-images.githubusercontent.com/71445210/204980253-7222fb42-9b48-4979-b54e-b64db11866d1.png)

**Comment by Lathan-btc** [comment]
@Akash 'All items are already selected' text is not getting displayed in the 'Select and add studies' dropdown

![image](https://user-images.githubusercontent.com/71445210/205011660-9f4b60f0-d6dc-41e7-aca4-a617bedd5f98.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance
