### ISSUE TITLE
[iOS] Not getting the study completion pop up in the study activities screen even though user submitted all the activities

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5102]
Not getting the study completed pop-up is not getting displayed on the study activities screen even though the user submitted all the activities present in the activities screen

Actual result:

![image](https://user-images.githubusercontent.com/71445210/203822030-30c159dd-c46b-40bb-b303-6ef52d63075a.png)

Expected result:

![image](https://user-images.githubusercontent.com/71445210/203822187-6231afa8-dda4-4bff-b10b-dbbdcaca7d62.png)

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest iOS QA build 3.0(204)
