### ISSUE TITLE
[IDP [QA] [SB] Popup message is getting displayed while adding a non organizational admin in the study builder in the following scenario

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5103]
Try to add non organizational admin in the study builder without phone number field and Verify

**AR:** Popup message is getting displayed while adding a non organizational admin in the study builder in the following scenario
**ER:** Popup message should get displayed while adding a non organizational admin in the study builder only when all the mandatory fields are completed in the screen

**Note:**
Issue is observed only in QA instance

[screen-capture (15).webm](https://user-images.githubusercontent.com/86007179/203903215-d872f1b3-0f70-44d6-bf3d-eef65d225924.webm)

**Comment by akashkumarv3** [comment]
@bhoomikav16 Hi, Issue is fixed now. please check and update.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
