### ISSUE TITLE
[app] Go back to intro screen after sign out

### ISSUE THREAD

**Issue by morethanreal** [GoogleCloudPlatform/fda-mystudies#59]
After signing out, the app appears the same except the study list is blank. It's not very obvious that the user is signed out. Let's go back to the intro screen (blue screen with 2 buttons) after sign out.

**Comment by SR-btc** [comment]
Given the new Hydra based sign-in screen, here's what has been agreed on:

Standalone App > App behavior after sign out

1. The app must navigate to the Welcome/Overview screen after sign out.
2. The Welcome screen of the app will have the Join Study button renamed to ‘Participate’, this will redirect to the Sign In screen and from here, the user can either sign in or sign up as required. 
3. The Welcome screen will also have the View Consent shortcut removed. 

Gateway app 
User will be redirected to App Overview screen after sign out

**Comment by nishit-v** [comment]
Above enhancement is verified and working fine in iOS builds 
Standalone app - 1.0(147)
Gateway app - 1.0(148)

**Comment by Lathan-btc** [comment]
Above enhancement is verified and working fine in Android builds
Standalone app - 1.0(44)
Gateway app - 1.0(44)
