### ISSUE TITLE
Use Token-Based Connection to APNs

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#614]
User registration service is using certificate + password for authentication when connecting to APNs 

Using token authentication is the new and preferred way and simplifies the workflow for users. see: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

**Comment by mohangmk** [comment]
@aswinijena100 , Please list the Secrets which you would like to have as part APNS connection, it will be helpful to analyze the changes required to implement the same.

**Comment by monica-BTC** [comment]
@nishit-v, please check notifications in IOS and confirm in Dev.

**Comment by nishit-v** [comment]
Unable to test due to #3839

**Comment by nishit-v** [comment]
Issue is fixed in latest iOS Dev build v1.0(243)

**Comment by aswinijena100** [comment]
Closing this ticket as FCM is used instead of Token for sending push notification. Please refer #616 for details.
