### ISSUE TITLE
Use FCM instead of APNS for iOS push notifications

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#616]
Firebase notifications can handle iOS as well as Android notifications; using FCM instead of APNS would simplify the logic as well as the setup of the push notifications.

**Comment by nishit-v** [comment]
Push notifications working fine in iOS dev build V1.0(266). Verified for automated/manual study level/app level notifications. Working fine.

**Comment by nishit-v** [comment]
Push notifications working fine in iOS QA build V1.0(29). Verified for automated/manual study level/app level notifications. Working fine.
