### ISSUE TITLE
[study builder] account screen - UI changes

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#936]
- Make phone field optional
- Remove the “(50 characters max)” text
- Remove  “Project Lead” and “Coordinator”. Also remove associated database fields; there should not be any functionality changes for these roles.
- Text on top should wrap when page resizes.
- Remove list of special characters from tooltip

**Comment by SR-btc** [comment]
For the 3rd point, refer to ticket #3113

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in dev, please check and confirm

**Comment by nishit-v** [comment]
Verified in Dev instance and implemented as per above mentioned points and 3rd point via #3113

**Comment by Kantharajut-btc** [comment]
@nishit-v this issue is fixed in QA, please check and confirm

**Comment by nishit-v** [comment]
Issue is resolved in the latest QA instance.
