### ISSUE TITLE
[study builder] settings and admin - UI changes

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#937]
Admin list has a mixture of mutually exclusive and non-mutually exclusive options that all have radio buttons

non-mutually exclusive options should use checkboxes instead.

**Comment by SR-btc** [comment]
The Admins section is intended to be removed, and is covered as a Track 3 item.

**Comment by Kantharajut-btc** [comment]
@sharathblr @nishit-v this issue is fixed please check in QA and confirm

**Comment by Lathan-btc** [comment]
@Kantharajut-btc Studies are not displaying in the studies list when user clicks on 'Mark as complete' button present on the 'STUDY SETTINGS' page.

**Comment by Lathan-btc** [comment]
@Kantharajut-btc Issue is fixed in latest QA instance.

**Comment by nagarjunav1** [comment]
![Admins](https://user-images.githubusercontent.com/60500517/103408941-93130780-4b8a-11eb-8f9e-72ab9da4cb07.png)
Still admin section is displaying in DEV

**Comment by SR-btc** [comment]
@Kantharajut-btc  also modify the screen to retain the first 3 settings only

**Comment by Kantharajut-btc** [comment]
@SR-btc @nagarjunav1 this issue is fixed in QA please check and confirm

**Comment by nagarjunav1** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/60500517/103413784-f4de6c00-4ba0-11eb-997a-51bc978c3ba2.png)
@SR-btc is this correct as per enhancement ?

**Comment by nagarjunav1** [comment]
Modified the screen to retain the first 3 settings only.
@Kantharajut-btc above enhancements is fixed in latest QA build

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest DEV build
