### ISSUE TITLE
[study builder] user gets logged out of the platform when confirming admin selections

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#938]

**Comment by sharathblr** [comment]
The below scenario explains the session handling- Forced logout behavior for Study Builder:

Scenario | EB | AB | Error message
-- | -- | -- | --
User session Timeout | User to be logged out even when in idle state and navigated to sign in screen | User is logged out even when in idle state | Your session has expired. Please sign in again.


Superadmin updates the user profile and when user is logged in | Error message displayed on the screen and when user click on OK, user redirected to sign in screen | Error message displayed on the screen and when user click on OK, user redirected to sign in screen | Your user account has been updated. Please sign in again to continue using the portal.
Parallel Login in different browser | User to be logged out in previously logged in browser and the error message to be displayed in sign in screen | User logged out in previously logged in browser and the error message to be displayed in sign in screen | Your session has expired. Please sign in again.
When superadmin update his own profile | Error message displayed on the screen and when user click on OK, user redirected to sign in screen | Error message displayed on the screen and when user click on OK, user redirected to sign in screen | Your user account has been updated. Please sign in again to continue using the portal.

**Comment by sharathblr** [comment]
@nishit-v - can you verify the above scenario working in SB and confirm and close the ticket accoridngly

**Comment by nishit-v** [comment]
As part of track 3 changes, Admins section is being removed in 'Settings' study zone section. Hence this issue will not be applicable for current changes.
