### ISSUE TITLE
[study builder] assets should be stored in a hierarchy

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#940]
All images are getting uploaded under a main directory (<app_name>_fda_resources) currently. 
Dividing them into sub directories based on the resource they belong to, makes finding them and deleting them easier.
images for study/123 should be stored under `<app_name>_fda_resources/studies/123/`
When/if we delete or export an study, then we can simply delete or copy the directory studies/123.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
@madhurya-btc Images are not getting displayed in PM and Mobile apps

PM

![PMn](https://user-images.githubusercontent.com/71445210/119158386-c855be80-ba73-11eb-92e1-238cc16a8ada.png)


Mobile app

![mbn](https://user-images.githubusercontent.com/71445210/119158672-1965b280-ba74-11eb-8cf6-621715800921.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Its fixed, Please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please retest once again in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm in QA instance

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
