### ISSUE TITLE
[study builder] consent and actions- UI changes

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#941]
- The elaborated content portion should be optional
- Add description that elaborated content can be formatted using markdown.
- Get rid of dialog box that shows up when trying to save the consent section
- Also, remove the e-consent form tab in the e-consent section and the  'Publish as upcoming'  option in the actions screen

**Comment by SR-btc** [comment]
1. The elaborated content portion gets utilized to generate the auto-created consent document, should the user opt for one.
2.  Added description to this screen in another ticket 2196, the RTE used indicates the available formatting options 
3. Fix in progress
4.  Fix in progress

**Comment by Lathan-btc** [comment]
@monica-BTC 
1. Get rid of dialog box that shows up when trying to save the consent section - Fixed
2. Also, remove the e-consent form tab in the e-consent section - Fixed

**Comment by Lathan-btc** [comment]
Following points are fixed in the latest Dev instance
1. Get rid of the dialog box that shows up when trying to save the consent section - Fixed
2. Also, remove the e-consent form tab in the e-consent section - Fixed

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev please check and confirm

**Comment by Lathan-btc** [comment]
@Kantharajut-btc  the 'Publish as upcoming' option is removed in the actions screen.
