### ISSUE TITLE
[study builder] studies - display deactivated studies in a separate tab

### ISSUE THREAD

**Issue by zohrehj** [GoogleCloudPlatform/fda-mystudies#943]

**Comment by SR-btc** [comment]
Changes to be done:
Study Builder > Study List > Hide deactivated studies under a toggle-style filter

-do not display deactivated studies in the default view
- have a toggle option to turn the display of these studies ON or OFF in the list

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by ESWAR1994** [comment]
merged into develop branch need to test in dev

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance
