### ISSUE TITLE
Fix study builder password reset process

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#954]
- Change top text to "Your password has expired. Please create a new password."
- Change top text box text to "Previous password"
- Change middle text box text to "New password"
- Change bottom text box text to "Confirm new password"
- Change "Copyright Placeholder" to "Copyright"
- Change first row of password rule text "Be at least 8 characters"
- Either drop the special character list or make it fit on one row
- When clicking submit - the circles that represent the number of password characters expand to fill the entire text box space which is confusing - please remove this feature.
- The password help shows green check-marks next to each password rule but still tells me the password is invalid
- Consider making the invalid password error message red so that it is easier to see
- The logo in the upper left corner does not link back to the main study builder landing page and the upper right link says "sign out" which is not correct because I'm not signed on this page - it should be something like "Return to Study Builder login" or something like that
- It appears that it is not possible to reset the password using this screen - nothing happens after I enter my old password and the valid new password
- The confirmation messages that appear after clicking "submit" are displayed for 1 or 2 seconds, which is not enough time to read them. Is there a reason not to let those messages stay on the screen? I believe the copy of those messages needs to be adjusted but I cannot read or screenshot them fast enough to see.
- There is a different password reset screen when the user initiates the password reset (screenshot below). Can we just have one password reset screen that both paths lead to? This is easier to maintain and a more consistent user experience.
- For the user initiated password reset screen, drop the access code requirement, fix the text so that it says "New password" and "Confirm new password" "Back to sign in" Give the page a title that says something like "Create new password" instead of the poorly written small text that is currently there.
- Sometimes the submit button is in all caps and other times it is in title case - pick one style and stick with it
- Fix the invalid password reset link screen to have correct capitalization and provide instructions to the user for what to do next (e.g. give them a link to request a new password reset email) 

![Screenshot 2020-09-12 at 12 30 36 PM](https://user-images.githubusercontent.com/35972680/93000130-47155780-f4f4-11ea-83fa-66a8fd722124.png)

![Screenshot 2020-09-12 at 12 35 24 PM](https://user-images.githubusercontent.com/35972680/93000198-b12dfc80-f4f4-11ea-8006-da3ad45ef2c8.png)

![Screenshot 2020-09-12 at 12 38 34 PM](https://user-images.githubusercontent.com/35972680/93000238-171a8400-f4f5-11ea-8ba8-1e15f62a19a2.png)

![image](https://user-images.githubusercontent.com/35972680/93001060-5b5c5300-f4fa-11ea-971c-36172dec2600.png)

![image](https://user-images.githubusercontent.com/35972680/93001200-5c41b480-f4fb-11ea-9956-4f12e76eb4f7.png)

**Comment by SR-btc** [comment]
@sharathblr please close this if it was already addressed via other tickets?

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue in dev instance and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in QA and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
