### ISSUE TITLE
Fix text in study builder forgot password screen

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#956]
- Change "Enter your Email address to get a link to reset your password" to "Enter your email to receive a password reset link"
- Remove period at end of the required field error message
- Change "Back to Sign in" to "Back to sign in"
- The confirmation messages that appear after clicking "submit" are displayed for 1 or 2 seconds, which is not enough time to read them. Is there a reason not to let those messages stay on the screen? I believe the copy of those messages needs to be adjusted but I cannot read or screenshot them fast enough to see.

![Screenshot 2020-09-12 at 12 57 48 PM](https://user-images.githubusercontent.com/35972680/93000719-2bac4b80-f4f8-11ea-90e7-2611f238da4b.png)

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in dev environment.  
Updated the error messages to be consistent "Please complete this field." as per issue #955.

**Comment by Lathan-btc** [comment]
Issue is resolved in latest Dev instance.
