### ISSUE TITLE
Update study builder password reset email text

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#957]
- Adjust subject line to be more clear and have proper capitalization: "Your study builder password reset request"
- Adjust body text to what I've written below
- Remove the 'access code' requirement - this does not seem to provide any additional security and only adds an unnecessary step for the user -- if some additional access code needs to be sent to the application do it using the URL

Hi Jamie,

We have received your password reset request. Please use the link below to create a new password:

[link] 

If you did not make this password reset request, of if you need additional assistance, please contact your system administrator.

![image](https://user-images.githubusercontent.com/35972680/93000826-d4f34180-f4f8-11ea-9538-e0f576b8c86f.png)

**Comment by SR-btc** [comment]
This is being addressed via https://github.com/GoogleCloudPlatform/fda-mystudies/issues/2607
