### ISSUE TITLE
Adjust study builder landing screen

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#958]
- Use the same style of account management in the upper right hand corner that the rest of the application uses (it should say my name and when I click the drop-down it gives me options to manage my account and logout)
- Change "Study Builder Portal" to "Study Builder"
- Remove the My Account from the main row of icons
- Change "Studies" to "Configure Studies" over two lines
- Change "Notifications" to "Send Notifications" over two lines
- Change "Users" to "Manage Users" over two lines

![Screenshot 2020-09-12 at 1 29 46 PM](https://user-images.githubusercontent.com/35972680/93001443-f6eec300-f4fc-11ea-9406-edda4f619ce3.png)

**Comment by Lathan-btc** [comment]
@monica-BTC 

1. Both first name and last name should be displayed
2. All the letters should be in caps
3. Drop down should be reduced


![landing screen](https://user-images.githubusercontent.com/71445210/104008516-8e280680-51cf-11eb-9ee9-4b4c1808e97f.png)

**Comment by Lathan-btc** [comment]
@Madhud5 All the icons should be aligned properly

![main icons ](https://user-images.githubusercontent.com/71445210/104192025-4bbb2f80-5444-11eb-896a-b932f7ae3888.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
